"""C++ 고급 문법 (코딩테스트 STL/문법 핵심 8꼭지)."""

from engine.models import Lesson

LESSONS = [

    Lesson(
        id="cpp-adv-01",
        lang="cpp", level="고급",
        title="우선순위 큐(priority_queue) — 최소/최대 힙",
        summary="기본 최대 힙 · greater 로 최소 힙",
        explanation=(
            "[개요]\n"
            "priority_queue는 삽입 순서와 무관하게 우선순위가 가장 높은 원소를\n"
            "항상 먼저 반환하는 컨테이너 어댑터이다. 옵션을 지정하지 않으면\n"
            "최댓값을 우선하는 최대 힙으로 동작한다.\n"
            "\n"
            "[핵심 개념]\n"
            "• 내부 자료구조는 힙(heap) 트리이며, push와 pop이 모두 O(log n)에 동작한다.\n"
            "• 어떤 값을 넣든 꺼낼 때는 항상 가장 크거나 가장 작은 값이 먼저 나온다.\n"
            "• 비교 방식을 세 번째 템플릿 인자로 지정하여 최소 힙으로 전환할 수 있다.\n"
            "\n"
            "[코드 분석]\n"
            "  priority_queue<int> maxHeap;\n"
            "      → 정수를 담는 최대 힙을 선언한다. 별도 옵션이 없으면 가장 큰 값이\n"
            "        항상 맨 앞에 위치한다.\n"
            "\n"
            "  for (int x : {3, 1, 4, 1, 5, 9}) maxHeap.push(x);\n"
            "      → 3, 1, 4, 1, 5, 9를 순서대로 삽입한다. 삽입 순서는 무관하며\n"
            "        내부적으로 자동 정렬된다.\n"
            "\n"
            "  cout << maxHeap.top() << \"\\n\";\n"
            "      → top()은 원소를 제거하지 않고 최상단 값(최댓값)만 조회한다.\n"
            "        결과는 9이며, 실제 제거는 pop()으로 수행한다.\n"
            "\n"
            "  priority_queue<int, vector<int>, greater<int>> minHeap;\n"
            "      → 최소 힙을 선언한다. 세 번째 인자 greater<int>가 '작은 값 우선'\n"
            "        비교 방식을 지정한다.\n"
            "\n"
            "  cout << minHeap.top() << \"\\n\";\n"
            "      → 최소 힙에서 top()은 가장 작은 값을 반환한다. 결과는 1이다.\n"
            "\n"
            "  while (!minHeap.empty()) { cout << minHeap.top() << ' '; minHeap.pop(); }\n"
            "      → 큐가 빌 때까지 반복하여 원소를 제거한다. empty()로 상태를 확인한다.\n"
            "        최소 힙에서 꺼내면 작은 값부터 나오므로 오름차순으로 출력된다.\n"
            "\n"
            "[유의 사항]\n"
            "• top()은 조회만 수행하며, 실제 제거는 pop()을 별도로 호출해야 한다.\n"
            "• 빈 큐에서 top()이나 pop()을 호출하면 정의되지 않은 동작(undefined\n"
            "  behavior)이 발생한다. 접근 전 반드시 empty()로 비어 있는지 확인한다."
        ),
        usage="다익스트라 최단경로, K번째 큰 수, 작업 스케줄링 등 '항상 최대/최소를 빠르게' 꺼내야 할 때.",
        cons="중간 원소 조회·임의 삭제가 불가능하다. 그런 연산이 필요하면 set/multiset 를 쓴다.",
        code=(
            "#include <bits/stdc++.h>\n"
            "using namespace std;\n"
            "\n"
            "int main() {\n"
            "    // 최대 힙 (기본)\n"
            "    priority_queue<int> maxHeap;\n"
            "    for (int x : {3, 1, 4, 1, 5, 9}) maxHeap.push(x);\n"
            "    cout << \"최댓값: \" << maxHeap.top() << \"\\n\";   // 9\n"
            "\n"
            "    // 최소 힙\n"
            "    priority_queue<int, vector<int>, greater<int>> minHeap;\n"
            "    for (int x : {3, 1, 4, 1, 5, 9}) minHeap.push(x);\n"
            "    cout << \"최솟값: \" << minHeap.top() << \"\\n\";   // 1\n"
            "\n"
            "    // 최소 힙에서 꺼내면 오름차순\n"
            "    cout << \"오름차순: \";\n"
            "    while (!minHeap.empty()) {\n"
            "        cout << minHeap.top() << ' ';\n"
            "        minHeap.pop();\n"
            "    }\n"
            "    cout << \"\\n\";\n"
            "    return 0;\n"
            "}\n"
        ),
    ),

    Lesson(
        id="cpp-adv-02",
        lang="cpp", level="고급",
        title="deque · stack · queue",
        summary="양끝 덱 · LIFO 스택 · FIFO 큐",
        explanation=(
            "[개요]\n"
            "deque, stack, queue는 원소 삽입·제거 방식이 각기 다른 세 가지 컨테이너이다.\n"
            "\n"
            "[핵심 개념]\n"
            "• deque(덱): 앞과 뒤 양쪽 모두에서 삽입·삭제가 가능한 양방향 큐이다.\n"
            "• stack(스택): 최상단에서만 삽입·삭제가 이루어지는 LIFO(Last In First\n"
            "  Out) 구조이다. 나중에 들어간 원소가 먼저 나온다.\n"
            "• queue(큐): 뒤에서 삽입하고 앞에서 제거하는 FIFO(First In First Out)\n"
            "  구조이다. 먼저 들어간 원소가 먼저 나온다.\n"
            "\n"
            "[코드 분석]\n"
            "  deque<int> dq;\n"
            "      → 정수를 담는 양방향 큐(덱)를 선언한다.\n"
            "\n"
            "  dq.push_back(2);\n"
            "      → 2를 덱의 뒤쪽에 삽입한다. 현재 덱: [2]\n"
            "\n"
            "  dq.push_front(1);\n"
            "      → 1을 덱의 앞쪽에 삽입한다. 현재 덱: [1, 2]\n"
            "\n"
            "  dq.push_back(3);\n"
            "      → 3을 덱의 뒤쪽에 삽입한다. 현재 덱: [1, 2, 3]\n"
            "\n"
            "  cout << dq.front() << ' ' << dq.back() << \"\\n\";\n"
            "      → front()는 맨 앞(1), back()은 맨 뒤(3)를 조회한다. 결과: 1 3\n"
            "\n"
            "  stack<int> st;\n"
            "      → 정수를 담는 스택을 선언한다.\n"
            "\n"
            "  st.push(10); st.push(20); st.push(30);\n"
            "      → 10, 20, 30을 차례로 삽입한다. 마지막에 넣은 30이 최상단에 위치한다.\n"
            "\n"
            "  cout << st.top() << \"\\n\";\n"
            "      → top()은 최상단 값(30)을 조회한다. 스택은 나중에 넣은 값이 먼저 조회된다.\n"
            "\n"
            "  queue<int> q;\n"
            "      → 정수를 담는 큐를 선언한다.\n"
            "\n"
            "  q.push(10); q.push(20); q.push(30);\n"
            "      → 10, 20, 30을 순서대로 삽입한다. 10이 맨 앞에 위치한다.\n"
            "\n"
            "  cout << q.front() << \"\\n\";\n"
            "      → front()는 맨 앞(10)을 조회한다. 큐는 먼저 넣은 값이 먼저 나온다.\n"
            "\n"
            "[유의 사항]\n"
            "• 첫 번째 값 조회 시 stack은 top(), queue는 front()를 사용한다. 혼동하지 않는다.\n"
            "• 두 자료구조 모두 중간 원소에는 직접 접근할 수 없다.\n"
            "• 빈 상태에서 top()/front()/pop()을 호출하면 프로그램이 비정상 종료된다.\n"
            "  접근 전 반드시 empty()로 확인한다."
        ),
        usage="BFS 는 queue, DFS·괄호검사·후위표기는 stack, 슬라이딩 윈도우 최댓값은 deque 가 정석이다.",
        cons="stack/queue 는 중간 원소 접근이 안 된다. deque 는 인덱스 접근은 되지만 중간 삽입은 느리다.",
        code=(
            "#include <bits/stdc++.h>\n"
            "using namespace std;\n"
            "\n"
            "int main() {\n"
            "    deque<int> dq;\n"
            "    dq.push_back(2);\n"
            "    dq.push_front(1);\n"
            "    dq.push_back(3);\n"
            "    cout << \"덱 앞/뒤: \" << dq.front() << ' ' << dq.back() << \"\\n\"; // 1 3\n"
            "\n"
            "    stack<int> st;\n"
            "    st.push(10); st.push(20); st.push(30);\n"
            "    cout << \"스택 top: \" << st.top() << \"\\n\";  // 30 (마지막에 넣은 것)\n"
            "\n"
            "    queue<int> q;\n"
            "    q.push(10); q.push(20); q.push(30);\n"
            "    cout << \"큐 front: \" << q.front() << \"\\n\"; // 10 (처음에 넣은 것)\n"
            "    return 0;\n"
            "}\n"
        ),
    ),

    Lesson(
        id="cpp-adv-03",
        lang="cpp", level="고급",
        title="람다와 함수 객체",
        summary="[](){}  · 캡처 · 커스텀 정렬",
        explanation=(
            "[개요]\n"
            "람다(lambda)는 이름 없이 그 자리에서 정의하는 일회용 함수이다. 한 번만\n"
            "사용할 동작을 별도 함수로 선언하지 않고 직접 인자로 전달할 때 유용하다.\n"
            "\n"
            "[핵심 개념 — 람다 문법]\n"
            "형식: [캡처](매개변수) { 동작 }\n"
            "• [  ] : 바깥 변수를 가져오지 않는다(캡처 없음).\n"
            "• [&]  : 바깥 변수를 참조로 가져온다(변경 가능).\n"
            "• [=]  : 바깥 변수를 복사하여 가져온다(원본 변경 없음).\n"
            "• [x]  : 변수 x만 복사하여 가져온다.\n"
            "\n"
            "[코드 분석]\n"
            "  vector<int> v = {5, 2, 8, 1, 9, 3};\n"
            "      → 원소 6개를 담은 벡터를 선언한다.\n"
            "\n"
            "  sort(v.begin(), v.end(), [](int a, int b) { return a > b; });\n"
            "      → 세 번째 인자로 람다 비교자를 전달하여 정렬한다.\n"
            "        'a > b이면 a를 앞에 배치'하라는 의미로, 내림차순 정렬이다.\n"
            "        []는 캡처 없음, (int a, int b)는 비교 대상 두 값이다.\n"
            "\n"
            "  for (int x : v) cout << x << ' ';\n"
            "      → 정렬된 벡터를 순서대로 출력한다. 결과: 9 8 5 3 2 1\n"
            "\n"
            "  int 기준 = 4;\n"
            "      → 비교 기준값 4를 담는 변수를 선언한다.\n"
            "\n"
            "  int cnt = count_if(v.begin(), v.end(), [기준](int x) { return x > 기준; });\n"
            "      → 조건을 만족하는 원소 개수를 센다.\n"
            "        [기준]은 바깥 변수 '기준'을 복사하여 람다 내부로 가져온다.\n"
            "        (int x)는 각 벡터 원소이며, return x > 기준으로 4보다 큰 원소만\n"
            "        개수에 포함한다. 9, 8, 5가 해당하므로 cnt = 3이다.\n"
            "\n"
            "[유의 사항]\n"
            "• [&]로 캡처한 람다를 나중에 실행하면 그 사이 참조 대상 변수가 소멸할 수\n"
            "  있다. 즉시 사용하는 경우는 무방하나, 저장 후 지연 실행 시에는 [=] 복사가\n"
            "  안전하다.\n"
            "• 함수 객체(functor)는 operator()를 가진 구조체로 람다와 동일한 역할을\n"
            "  한다. 람다는 이를 간결하게 표현하는 현대 C++ 방식이다."
        ),
        usage="정렬 기준을 즉석에서 지정하거나, 알고리즘에 동작을 인자로 넘길 때 코드가 간결해진다.",
        cons="캡처를 [&] 로 무심코 쓰면 수명이 끝난 변수를 참조해 버그가 날 수 있어 캡처 범위를 명확히 해야 한다.",
        code=(
            "#include <bits/stdc++.h>\n"
            "using namespace std;\n"
            "\n"
            "int main() {\n"
            "    vector<int> v = {5, 2, 8, 1, 9, 3};\n"
            "\n"
            "    // 내림차순 정렬 (람다 비교자)\n"
            "    sort(v.begin(), v.end(), [](int a, int b) {\n"
            "        return a > b;\n"
            "    });\n"
            "    cout << \"내림차순: \";\n"
            "    for (int x : v) cout << x << ' ';\n"
            "    cout << \"\\n\";\n"
            "\n"
            "    // 값 캡처: 기준값보다 큰 원소 개수 세기\n"
            "    int 기준 = 4;\n"
            "    int cnt = count_if(v.begin(), v.end(), [기준](int x) {\n"
            "        return x > 기준;\n"
            "    });\n"
            "    cout << 기준 << \"보다 큰 원소 수: \" << cnt << \"\\n\"; // 3\n"
            "    return 0;\n"
            "}\n"
        ),
    ),

    Lesson(
        id="cpp-adv-04",
        lang="cpp", level="고급",
        title="이터레이터와 알고리즘 — lower_bound · upper_bound · accumulate",
        summary="이분 탐색 위치 · 구간 합",
        explanation=(
            "[개요]\n"
            "lower_bound와 upper_bound는 정렬된 범위에서 이분 탐색으로 특정 값의\n"
            "위치를 찾는 함수이며, accumulate는 범위의 모든 값을 누적 합산하는 함수이다.\n"
            "\n"
            "[핵심 개념]\n"
            "• lower_bound(시작, 끝, x): x 이상인 값이 처음 나오는 위치를 반환한다.\n"
            "• upper_bound(시작, 끝, x): x 초과인 값이 처음 나오는 위치를 반환한다.\n"
            "• 두 위치의 차이가 곧 값 x의 개수이다.\n"
            "  예) [1, 2, 2, 2, 4, 5, 7]에서 2를 탐색하면\n"
            "      lower_bound → index 1 (처음 등장하는 2의 위치)\n"
            "      upper_bound → index 4 (2보다 큰 4의 위치)\n"
            "      개수 = 4 - 1 = 3\n"
            "• accumulate는 범위 내 모든 원소를 초기값에 더해 합을 구한다.\n"
            "\n"
            "[코드 분석]\n"
            "  vector<int> v = {1, 2, 2, 2, 4, 5, 7};\n"
            "      → 이미 정렬된 벡터를 선언한다. lower/upper_bound는 정렬 상태를 전제로 한다.\n"
            "\n"
            "  auto lo = lower_bound(v.begin(), v.end(), 2);\n"
            "      → 2 이상인 값이 처음 나오는 위치를 찾는다. 반환값은 이터레이터이며\n"
            "        auto로 타입을 자동 추론한다. 결과 위치는 index 1이다.\n"
            "\n"
            "  auto hi = upper_bound(v.begin(), v.end(), 2);\n"
            "      → 2 초과인 값이 처음 나오는 위치를 찾는다. 값 4가 있는 index 4이다.\n"
            "\n"
            "  cout << (lo - v.begin()) << \"\\n\";\n"
            "      → 이터레이터에서 begin()을 빼면 인덱스가 산출된다. lo - v.begin() = 1\n"
            "\n"
            "  cout << (hi - lo) << \"\\n\";\n"
            "      → 두 위치의 차이가 2의 개수이다. 4 - 1 = 3\n"
            "\n"
            "  int sum = accumulate(v.begin(), v.end(), 0);\n"
            "      → v의 모든 원소를 더한다. 세 번째 인자 0은 초기값이다.\n"
            "        1+2+2+2+4+5+7 = 23\n"
            "\n"
            "  cout << \"전체 합: \" << sum << \"\\n\";\n"
            "      → 결과 23을 출력한다.\n"
            "\n"
            "[유의 사항]\n"
            "• lower_bound/upper_bound는 정렬된 배열에서만 정확히 동작한다. 정렬되지\n"
            "  않은 배열에 사용하면 결과가 부정확하므로 반드시 sort() 이후에 사용한다.\n"
            "• accumulate는 #include <numeric>이 필요하다(bits/stdc++.h 사용 시 자동 포함)."
        ),
        usage="정렬된 배열에서 특정 값의 개수·삽입 위치를 빠르게 구하거나, 합/곱 누적을 한 줄로 처리할 때.",
        cons="lower_bound/upper_bound 는 범위가 반드시 정렬돼 있어야 정확하다. 정렬이 깨지면 결과가 틀린다.",
        code=(
            "#include <bits/stdc++.h>\n"
            "using namespace std;\n"
            "\n"
            "int main() {\n"
            "    vector<int> v = {1, 2, 2, 2, 4, 5, 7};  // 정렬된 상태\n"
            "\n"
            "    auto lo = lower_bound(v.begin(), v.end(), 2); // 2 이상 첫 위치\n"
            "    auto hi = upper_bound(v.begin(), v.end(), 2); // 2 초과 첫 위치\n"
            "    cout << \"2의 시작 인덱스: \" << (lo - v.begin()) << \"\\n\"; // 1\n"
            "    cout << \"2의 개수: \" << (hi - lo) << \"\\n\";              // 3\n"
            "\n"
            "    int sum = accumulate(v.begin(), v.end(), 0);\n"
            "    cout << \"전체 합: \" << sum << \"\\n\";   // 23\n"
            "    return 0;\n"
            "}\n"
        ),
    ),

    Lesson(
        id="cpp-adv-05",
        lang="cpp", level="고급",
        title="비트 연산과 비트마스킹",
        summary="& | ^ ~ << >> · 부분집합 표현",
        explanation=(
            "[개요]\n"
            "비트 연산은 데이터를 이진수 단위(0과 1)로 직접 조작하는 연산이다.\n"
            "각 비트를 상태 플래그로 활용하면 집합을 정수 하나로 압축 표현할 수 있으며,\n"
            "이를 비트마스킹이라 한다. 예로 정수 10은 이진수 00001010으로, 1번과\n"
            "3번 비트가 켜진 상태를 나타낸다.\n"
            "\n"
            "[핵심 개념 — 비트 연산자]\n"
            "• &  (AND) : 두 비트가 모두 1이면 1이다.\n"
            "• |  (OR)  : 두 비트 중 하나라도 1이면 1이다.\n"
            "• ^  (XOR) : 두 비트가 서로 다르면 1이다.\n"
            "• ~  (NOT) : 0과 1을 반전한다.\n"
            "• << (왼쪽 시프트)  : 비트를 왼쪽으로 이동한다(1<<3 은 8).\n"
            "• >> (오른쪽 시프트) : 비트를 오른쪽으로 이동한다.\n"
            "\n"
            "[코드 분석]\n"
            "  int mask = 0;\n"
            "      → 모든 비트가 꺼진 상태로 초기화한다. 이진수 00000000\n"
            "\n"
            "  mask |= (1 << 1);\n"
            "      → 1번 비트를 켠다. (1<<1)은 이진수 00000010이며, OR 연산으로 해당\n"
            "        비트를 1로 설정한다. mask: 00000010 = 2\n"
            "\n"
            "  mask |= (1 << 3);\n"
            "      → 3번 비트를 켠다. (1<<3)은 이진수 00001000이다.\n"
            "        mask: 00001010 = 10\n"
            "\n"
            "  cout << \"mask = \" << mask << \"\\n\";\n"
            "      → mask 값 10을 출력한다(이진수 1010).\n"
            "\n"
            "  cout << ((mask & (1 << 1)) ? 1 : 0) << \"\\n\";\n"
            "      → 1번 비트의 설정 여부를 확인한다.\n"
            "        mask & (1<<1) = 1010 & 0010 = 0010(0이 아님)이므로 1을 출력한다.\n"
            "        결과가 0이 아니면 해당 비트가 켜진 것, 0이면 꺼진 것이다.\n"
            "\n"
            "  cout << __builtin_popcount(mask) << \"\\n\";\n"
            "      → 켜진 비트(1인 비트)의 개수를 센다. 1010에서 1이 2개이므로 결과는 2이다.\n"
            "        __builtin_popcount는 GCC 내장 함수로 매우 빠르게 동작한다.\n"
            "\n"
            "  for (int s = 0; s < (1 << 3); s++) { ... }\n"
            "      → (1<<3) = 8이므로 s는 0~7(이진수 000~111)까지 반복한다.\n"
            "        3개 원소의 모든 부분집합 8가지(공집합 포함)를 표현한다.\n"
            "        s=0: {} / s=1: {A} / s=2: {B} / s=3: {A,B} / ... / s=7: {A,B,C}\n"
            "\n"
            "  if (s & (1 << i)) cout << item[i];\n"
            "      → s의 i번 비트가 1이면 item[i]를 출력한다. 부분집합에 i번 원소가\n"
            "        포함됨을 의미한다.\n"
            "\n"
            "[유의 사항]\n"
            "• (1<<i)처럼 반드시 괄호로 감싼다. << 연산자의 우선순위가 낮아\n"
            "  1<<3 + 1은 1<<(3+1) = 16으로 해석된다.\n"
            "• n이 30 이상이면 1<<n이 int 범위를 초과한다. 1LL<<n처럼 long long으로 쓴다.\n"
            "• 비트마스크 전체 탐색은 n이 20 정도까지가 실용적이다. n이 25 이상이면\n"
            "  2^n 폭발로 시간 초과 위험이 있다."
        ),
        usage="집합 DP(외판원 TSP 등), 상태 압축, 부분집합 전체 탐색에서 메모리·속도를 크게 아낀다.",
        cons="가독성이 떨어지고 우선순위 실수가 잦다. (1<<i) 처럼 괄호를 꼭 씌우고, n이 크면 2^n 폭발에 주의.",
        code=(
            "#include <bits/stdc++.h>\n"
            "using namespace std;\n"
            "\n"
            "int main() {\n"
            "    int mask = 0;\n"
            "    mask |= (1 << 1);   // 1번 비트 켜기\n"
            "    mask |= (1 << 3);   // 3번 비트 켜기\n"
            "    cout << \"mask = \" << mask << \"\\n\";              // 10 (2진수 1010)\n"
            "    cout << \"1번 비트 켜짐? \" << ((mask & (1 << 1)) ? 1 : 0) << \"\\n\"; // 1\n"
            "    cout << \"켜진 비트 수: \" << __builtin_popcount(mask) << \"\\n\";     // 2\n"
            "\n"
            "    // {A,B,C} 3원소의 모든 부분집합 출력\n"
            "    string item[3] = {\"A\", \"B\", \"C\"};\n"
            "    for (int s = 0; s < (1 << 3); s++) {\n"
            "        cout << '{';\n"
            "        for (int i = 0; i < 3; i++)\n"
            "            if (s & (1 << i)) cout << item[i];\n"
            "        cout << \"} \";\n"
            "    }\n"
            "    cout << \"\\n\";\n"
            "    return 0;\n"
            "}\n"
        ),
    ),

    Lesson(
        id="cpp-adv-06",
        lang="cpp", level="고급",
        title="빠른 입출력 — ios_base::sync_with_stdio",
        summary="C 스트림 동기화 해제 · cin.tie 해제",
        explanation=(
            "[개요]\n"
            "cin/cout은 기본적으로 C의 scanf/printf와 함께 사용할 수 있도록\n"
            "동기화되어 있다. 이 동기화 과정은 입출력 성능을 저하시키므로, 대용량\n"
            "입출력 문제에서는 동기화를 해제하여 속도를 확보한다.\n"
            "\n"
            "[핵심 개념]\n"
            "• sync_with_stdio(false): C 표준 입출력과의 동기화를 해제하여 cin/cout이\n"
            "  독립적으로 동작하게 한다. 입출력 속도가 크게 향상된다.\n"
            "• cin.tie(NULL): cin이 입력 전 cout을 자동으로 flush하는 연결을 해제한다.\n"
            "  불필요한 flush를 제거하여 추가로 속도를 높인다.\n"
            "\n"
            "[코드 분석]\n"
            "  ios_base::sync_with_stdio(false);\n"
            "      → cin/cout과 scanf/printf의 동기화를 해제한다. 입출력이 수 배 빨라질\n"
            "        수 있으며, main() 시작부에서 한 번만 호출한다.\n"
            "\n"
            "  cin.tie(NULL);\n"
            "      → cin이 cout을 자동 flush하는 동작을 차단한다. 위 sync_with_stdio(false)와\n"
            "        함께 사용하는 관용구이다.\n"
            "\n"
            "  int n = 5;\n"
            "      → 반복 횟수 5를 저장한다. 실제 문제에서는 cin >> n;으로 입력받는다.\n"
            "\n"
            "  long long sum = 0;\n"
            "      → 합계를 저장할 변수이다. 값이 커질 수 있어 long long을 사용한다.\n"
            "        int는 약 21억, long long은 약 920경까지 저장할 수 있다.\n"
            "\n"
            "  for (int i = 1; i <= n; i++) {\n"
            "      → 1부터 n까지 반복한다.\n"
            "\n"
            "  sum += i;\n"
            "      → 합계에 i를 누적한다. 1+2+3+4+5 = 15\n"
            "\n"
            "  cout << i << (i < n ? ' ' : '\\n');\n"
            "      → i를 출력하고, 마지막이 아니면 공백, 마지막이면 줄바꿈을 출력한다.\n"
            "        endl 대신 '\\n'을 사용하는 것이 핵심이다. endl은 출력마다 버퍼를\n"
            "        강제 flush하므로 느리다.\n"
            "\n"
            "  cout << \"합: \" << sum << \"\\n\";\n"
            "      → 최종 합계 15를 출력한다.\n"
            "\n"
            "[유의 사항]\n"
            "• sync_with_stdio(false) 이후에는 scanf/printf를 혼용하면 안 된다. 출력\n"
            "  순서가 뒤섞여 결과가 어긋날 수 있다.\n"
            "• endl은 매 호출마다 flush하므로 입력이 많은 문제에서 시간 초과(TLE)의\n"
            "  원인이 된다. 줄바꿈은 '\\n'을 사용한다.\n"
            "• 위 두 줄은 대용량 입출력 문제에서 사실상 필수 관용구이다."
        ),
        usage="입력이 수십만 줄 이상인 백준 문제에서 시간초과를 피하는 거의 필수 관용구.",
        cons="동기화를 끄면 C 입출력(scanf/printf)과 섞어 쓰면 안 된다. main 시작부에 한 번만 설정한다.",
        code=(
            "#include <bits/stdc++.h>\n"
            "using namespace std;\n"
            "\n"
            "int main() {\n"
            "    ios_base::sync_with_stdio(false);\n"
            "    cin.tie(NULL);\n"
            "\n"
            "    // 데모: 입력 대신 고정값으로 빠른 출력 시연\n"
            "    int n = 5;\n"
            "    long long sum = 0;\n"
            "    for (int i = 1; i <= n; i++) {\n"
            "        sum += i;\n"
            "        cout << i << (i < n ? ' ' : '\\n');  // endl 대신 '\\n'\n"
            "    }\n"
            "    cout << \"합: \" << sum << \"\\n\";   // 15\n"
            "    return 0;\n"
            "}\n"
        ),
    ),

    Lesson(
        id="cpp-adv-07",
        lang="cpp", level="고급",
        title="multiset · multimap",
        summary="중복 허용 정렬 컨테이너",
        explanation=(
            "[개요]\n"
            "multiset과 multimap은 중복 원소를 허용하는 자동 정렬 컨테이너이다.\n"
            "set은 동일 값을 하나만 저장하지만, multiset은 같은 값을 여러 개 저장한다.\n"
            "예로 100점이 5명이면 set은 100 하나만, multiset은 100을 5개 저장한다.\n"
            "\n"
            "[핵심 개념]\n"
            "• 모든 원소가 자동 정렬 상태를 유지한다. begin()은 최솟값, rbegin()은\n"
            "  최댓값을 가리킨다.\n"
            "• 삽입·삭제·탐색이 모두 O(log n)에 동작한다.\n"
            "• multimap은 동일 키에 여러 값을 저장할 수 있는 정렬된 맵이다.\n"
            "\n"
            "[코드 분석]\n"
            "  multiset<int> ms;\n"
            "      → 정수를 담는 멀티셋을 선언한다. 중복을 허용하며 자동 정렬된다.\n"
            "\n"
            "  for (int x : {5, 1, 3, 1, 5, 1}) ms.insert(x);\n"
            "      → 5, 1, 3, 1, 5, 1을 삽입한다. 자동 정렬되어 내부 상태는\n"
            "        {1, 1, 1, 3, 5, 5}이다.\n"
            "\n"
            "  for (int x : ms) cout << x << ' ';\n"
            "      → 정렬된 순서로 출력한다. 결과: 1 1 1 3 5 5\n"
            "\n"
            "  cout << ms.count(1) << \"\\n\";\n"
            "      → 1의 개수를 센다. 결과: 3\n"
            "\n"
            "  cout << *ms.begin() << \"\\n\";\n"
            "      → begin()은 최솟값을 가리키는 이터레이터이며, *로 실제 값을 참조한다.\n"
            "        결과: 1\n"
            "\n"
            "  ms.erase(ms.find(1));\n"
            "      → 핵심 코드이다. ms.erase(1)로 호출하면 값 1이 전부(3개) 삭제된다.\n"
            "        ms.find(1)은 1이 위치한 이터레이터 하나를 반환하며, 그 위치만\n"
            "        erase하면 1이 하나만 삭제된다.\n"
            "\n"
            "  cout << ms.count(1) << \"\\n\";\n"
            "      → 하나 삭제 후 1의 개수. 결과: 2\n"
            "\n"
            "  multimap<string, int> mm;\n"
            "      → 문자열 키, 정수 값의 멀티맵을 선언한다.\n"
            "\n"
            "  mm.insert({\"kim\", 90}); mm.insert({\"kim\", 85});\n"
            "      → 동일 키 \"kim\"에 90과 85 두 값을 삽입한다. 일반 map에서는 불가능하다.\n"
            "\n"
            "  cout << mm.count(\"kim\") << \"\\n\";\n"
            "      → \"kim\" 키의 개수. 결과: 2\n"
            "\n"
            "[유의 사항]\n"
            "• erase(값)은 해당 값을 전부 삭제한다. 하나만 삭제하려면 반드시\n"
            "  erase(find(값))을 사용한다. 자주 발생하는 실수이므로 주의한다.\n"
            "• 해시 계열(unordered_*)보다 상수 시간이 크고 메모리 사용량도 많다.\n"
            "  단순 조회만 필요하면 unordered_set/unordered_map이 더 빠르다."
        ),
        usage="정렬 상태를 유지하면서 중복값을 다루거나, 최솟/최댓값을 계속 꺼내며 임의 삭제도 필요할 때.",
        cons="해시(unordered_*)보다 상수가 크고 메모리도 더 쓴다. 단순 조회만 필요하면 unordered 계열이 빠르다.",
        code=(
            "#include <bits/stdc++.h>\n"
            "using namespace std;\n"
            "\n"
            "int main() {\n"
            "    multiset<int> ms;\n"
            "    for (int x : {5, 1, 3, 1, 5, 1}) ms.insert(x);\n"
            "\n"
            "    cout << \"정렬+중복: \";\n"
            "    for (int x : ms) cout << x << ' ';   // 1 1 1 3 5 5\n"
            "    cout << \"\\n\";\n"
            "    cout << \"1의 개수: \" << ms.count(1) << \"\\n\";   // 3\n"
            "    cout << \"최솟값: \" << *ms.begin() << \"\\n\";      // 1\n"
            "\n"
            "    ms.erase(ms.find(1));   // 1을 '하나만' 삭제\n"
            "    cout << \"하나 삭제 후 1의 개수: \" << ms.count(1) << \"\\n\"; // 2\n"
            "\n"
            "    multimap<string, int> mm;\n"
            "    mm.insert({\"kim\", 90});\n"
            "    mm.insert({\"kim\", 85});\n"
            "    cout << \"kim 키 개수: \" << mm.count(\"kim\") << \"\\n\"; // 2\n"
            "    return 0;\n"
            "}\n"
        ),
    ),

    Lesson(
        id="cpp-adv-08",
        lang="cpp", level="고급",
        title="auto · 범위 기반 for · 구조적 바인딩",
        summary="타입 추론 · for(x : v) · auto [a,b]",
        explanation=(
            "[개요]\n"
            "auto, 범위 기반 for, 구조적 바인딩은 코드를 간결하게 하는 현대 C++ 문법이다.\n"
            "특히 map 이터레이터처럼 긴 타입 선언을 줄이는 데 유용하다.\n"
            "  map<string, int>::iterator it = m.begin();\n"
            "  → auto it = m.begin();\n"
            "\n"
            "[핵심 개념]\n"
            "• auto: 우변 값을 보고 타입을 자동 추론한다.\n"
            "• 범위 기반 for: 배열/벡터의 모든 원소를 순서대로 순회한다. 인덱스\n"
            "  변수를 두지 않아 코드가 간결하다.\n"
            "• 구조적 바인딩(C++17): pair나 tuple을 여러 변수로 한 번에 분해한다.\n"
            "\n"
            "[코드 분석]\n"
            "  vector<int> v = {10, 20, 30};\n"
            "      → 정수 벡터를 선언한다.\n"
            "\n"
            "  for (auto& x : v) x += 1;\n"
            "      → v의 모든 원소를 순서대로 순회하며 x로 참조한다. &를 붙여 참조로\n"
            "        받으므로 x를 변경하면 원본 v도 변경된다. 결과: {11, 21, 31}\n"
            "\n"
            "  for (auto x : v) cout << x << ' ';\n"
            "      → 이번에는 & 없이 복사로 받는다. 출력만 할 때는 복사로 충분하다.\n"
            "        결과: 11 21 31\n"
            "\n"
            "  map<string, int> score = {{\"kim\", 90}, {\"lee\", 80}};\n"
            "      → 이름→점수 맵을 선언한다.\n"
            "\n"
            "  for (const auto& [name, point] : score)\n"
            "      → map의 각 항목을 [name, point]로 분해하여 받는다. 구조적 바인딩으로\n"
            "        key는 name, value는 point에 대응한다. const auto&는 복사 없이\n"
            "        참조로 받되 변경하지 않음을 의미한다.\n"
            "\n"
            "  cout << name << \": \" << point << \"\\n\";\n"
            "      → 이름과 점수를 출력한다. 결과: kim: 90 / lee: 80 (키 정렬 순)\n"
            "\n"
            "  auto [a, b] = make_pair(1, 2);\n"
            "      → pair를 생성하고 a=1, b=2로 한 번에 분해한다. pair.first,\n"
            "        pair.second 대신 사용하여 가독성이 높다.\n"
            "\n"
            "  cout << a + b << \"\\n\";\n"
            "      → 결과: 3\n"
            "\n"
            "[유의 사항]\n"
            "• for (auto x : v)에서 x를 변경해도 원본 v는 변경되지 않는다(복사). 원본을\n"
            "  변경하려면 for (auto& x : v)로 참조로 받아야 한다.\n"
            "• 구조적 바인딩 auto [a, b]는 C++17 이상에서만 동작한다. 컴파일 시\n"
            "  -std=c++17 플래그 또는 IDE의 C++17 설정이 필요하다.\n"
            "• auto가 의도와 다른 타입으로 추론될 수 있다(예: 참조가 복사로). 동작이\n"
            "  예상과 다르면 명시적 타입으로 확인한다."
        ),
        usage="map 순회 시 auto& [key, val], 이터레이터 타입 생략 등에서 코드가 짧고 명확해진다.",
        cons="auto 는 의도한 타입과 다르게 추론될 수 있어(예: 참조가 복사로) 성능·동작 의도를 분명히 해야 한다.",
        code=(
            "#include <bits/stdc++.h>\n"
            "using namespace std;\n"
            "\n"
            "int main() {\n"
            "    vector<int> v = {10, 20, 30};\n"
            "\n"
            "    // 범위 기반 for + 참조로 값 수정\n"
            "    for (auto& x : v) x += 1;\n"
            "    cout << \"수정 후: \";\n"
            "    for (auto x : v) cout << x << ' ';   // 11 21 31\n"
            "    cout << \"\\n\";\n"
            "\n"
            "    // map 순회 + 구조적 바인딩\n"
            "    map<string, int> score = {{\"kim\", 90}, {\"lee\", 80}};\n"
            "    for (const auto& [name, point] : score)\n"
            "        cout << name << \": \" << point << \"\\n\";\n"
            "\n"
            "    // pair 분해\n"
            "    auto [a, b] = make_pair(1, 2);\n"
            "    cout << \"a+b = \" << a + b << \"\\n\";   // 3\n"
            "    return 0;\n"
            "}\n"
        ),
    ),
]
