"""C++ 고급 문법 (코딩테스트 STL/문법 핵심 8꼭지)."""

from engine.models import Lesson

LESSONS = [

    Lesson(
        id="cpp-adv-01",
        lang="cpp", level="고급",
        title="우선순위 큐(priority_queue) — 최소/최대 힙",
        summary="기본 최대 힙 · greater 로 최소 힙",
        explanation=(
            "━━ 우선순위 큐(priority_queue) 란? ━━\n"
            "\n"
            "마트 계산대를 생각해 보세요. 일반 줄은 먼저 온 순서대로 계산하지만,\n"
            "VIP 줄은 어떤 순서로 왔든 '우선순위가 높은 손님'이 항상 먼저 계산받아요.\n"
            "priority_queue 가 바로 그 VIP 줄입니다!\n"
            "\n"
            "어떤 숫자를 넣든, 꺼낼 때는 항상 '가장 크거나 가장 작은 것'이 먼저 나와요.\n"
            "내부적으로는 '힙(heap)'이라는 특수한 트리 구조로 되어 있어서,\n"
            "넣기(push)와 꺼내기(pop)가 모두 O(log n)으로 빠르게 동작해요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  priority_queue<int> maxHeap;\n"
            "      →  정수(int)를 담는 최대 힙 우선순위 큐를 만들어요.\n"
            "         아무 옵션을 안 주면 '가장 큰 수'가 항상 맨 앞에 있는 최대 힙이에요.\n"
            "\n"
            "  for (int x : {3, 1, 4, 1, 5, 9}) maxHeap.push(x);\n"
            "      →  3, 1, 4, 1, 5, 9 를 하나씩 큐에 넣어요.\n"
            "         넣는 순서는 상관없어요. 내부적으로 자동으로 정렬돼요.\n"
            "\n"
            "  cout << maxHeap.top() << \"\\n\";\n"
            "      →  top()은 꺼내지 않고 가장 위에 있는 값(최댓값)만 들여다봐요.\n"
            "         결과는 9가 나와요. pop()을 따로 해야 실제로 제거돼요.\n"
            "\n"
            "  priority_queue<int, vector<int>, greater<int>> minHeap;\n"
            "      →  최소 힙을 만들어요. 세 번째 인자 greater<int>가 '작은 것이 먼저'\n"
            "         라는 비교 방식을 정해줘요. 이 긴 선언이 헷갈리면 통째로 외워버려도 돼요!\n"
            "\n"
            "  cout << minHeap.top() << \"\\n\";\n"
            "      →  최소 힙에서 top()을 하면 가장 작은 값이 나와요. 결과는 1.\n"
            "\n"
            "  while (!minHeap.empty()) { cout << minHeap.top() << ' '; minHeap.pop(); }\n"
            "      →  큐가 빌 때까지 계속 꺼내요. empty()로 비어있는지 확인하는 습관을 들이세요.\n"
            "         최소 힙에서 꺼내면 작은 것부터 나오므로 오름차순으로 출력돼요!\n"
            "\n"
            "주의할 점:\n"
            "  top()은 보기만 해요. 실제로 제거하려면 반드시 pop()도 해야 해요.\n"
            "  빈 큐에서 top()이나 pop()을 하면 프로그램이 강제 종료돼요(undefined behavior).\n"
            "  항상 empty()로 비어 있는지 확인하고 꺼내세요!"
        ),
        usage="다익스트라 최단경로, K번째 큰 수, 작업 스케줄링 등 '항상 최대/최소를 빠르게' 꺼내야 할 때.",
        cons="중간 원소 조회·임의 삭제가 불가능하다. 그런 연산이 필요하면 set/multiset 를 쓴다.",
        code=(
            "#include <bits/stdc++.h>\n"
            "using namespace std;\n"
            "\n"
            "int main() {\n"
            "    // 최대 힙 (기본)\n"
            "    priority_queue<int> maxHeap;\n"
            "    for (int x : {3, 1, 4, 1, 5, 9}) maxHeap.push(x);\n"
            "    cout << \"최댓값: \" << maxHeap.top() << \"\\n\";   // 9\n"
            "\n"
            "    // 최소 힙\n"
            "    priority_queue<int, vector<int>, greater<int>> minHeap;\n"
            "    for (int x : {3, 1, 4, 1, 5, 9}) minHeap.push(x);\n"
            "    cout << \"최솟값: \" << minHeap.top() << \"\\n\";   // 1\n"
            "\n"
            "    // 최소 힙에서 꺼내면 오름차순\n"
            "    cout << \"오름차순: \";\n"
            "    while (!minHeap.empty()) {\n"
            "        cout << minHeap.top() << ' ';\n"
            "        minHeap.pop();\n"
            "    }\n"
            "    cout << \"\\n\";\n"
            "    return 0;\n"
            "}\n"
        ),
    ),

    Lesson(
        id="cpp-adv-02",
        lang="cpp", level="고급",
        title="deque · stack · queue",
        summary="양끝 덱 · LIFO 스택 · FIFO 큐",
        explanation=(
            "━━ deque · stack · queue 란? ━━\n"
            "\n"
            "세 가지 자료구조를 실생활로 비유해볼게요.\n"
            "\n"
            "deque(덱)   →  양쪽 모두 열린 지하철 문.\n"
            "               앞에서도 타고 내릴 수 있고, 뒤에서도 타고 내릴 수 있어요.\n"
            "\n"
            "stack(스택) →  접시 쌓기.\n"
            "               맨 위에만 올릴 수 있고, 꺼낼 때도 맨 위 접시만 꺼낼 수 있어요.\n"
            "               나중에 들어간 것이 먼저 나오는 LIFO(Last In First Out) 구조예요.\n"
            "\n"
            "queue(큐)   →  편의점 계산대 줄.\n"
            "               먼저 온 사람이 먼저 나가요.\n"
            "               먼저 들어간 것이 먼저 나오는 FIFO(First In First Out) 구조예요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  deque<int> dq;\n"
            "      →  정수를 담는 양방향 큐(덱)를 만들어요.\n"
            "\n"
            "  dq.push_back(2);\n"
            "      →  2를 덱의 뒤쪽에 넣어요. 현재 덱: [2]\n"
            "\n"
            "  dq.push_front(1);\n"
            "      →  1을 덱의 앞쪽에 넣어요. 현재 덱: [1, 2]\n"
            "\n"
            "  dq.push_back(3);\n"
            "      →  3을 덱의 뒤쪽에 넣어요. 현재 덱: [1, 2, 3]\n"
            "\n"
            "  cout << dq.front() << ' ' << dq.back() << \"\\n\";\n"
            "      →  front()는 가장 앞(1), back()은 가장 뒤(3)를 봐요. 결과: 1 3\n"
            "\n"
            "  stack<int> st;\n"
            "      →  정수를 담는 스택(접시 쌓기)을 만들어요.\n"
            "\n"
            "  st.push(10); st.push(20); st.push(30);\n"
            "      →  10, 20, 30을 차례로 올려요. 제일 위에는 30이 있어요.\n"
            "         접시를 차례로 쌓는 것처럼 마지막에 넣은 30이 가장 위예요.\n"
            "\n"
            "  cout << st.top() << \"\\n\";\n"
            "      →  top()은 맨 위 접시(30)를 봐요. 스택은 나중에 넣은 게 먼저 보여요.\n"
            "\n"
            "  queue<int> q;\n"
            "      →  정수를 담는 큐(계산대 줄)를 만들어요.\n"
            "\n"
            "  q.push(10); q.push(20); q.push(30);\n"
            "      →  10, 20, 30을 순서대로 줄을 세워요. 10이 제일 앞에 있어요.\n"
            "\n"
            "  cout << q.front() << \"\\n\";\n"
            "      →  front()는 줄의 맨 앞(10)을 봐요. 큐는 먼저 넣은 게 먼저 나와요.\n"
            "\n"
            "주의할 점:\n"
            "  stack은 top()으로, queue는 front()로 첫 번째 값을 봐요. 헷갈리지 마세요!\n"
            "  두 자료구조 모두 중간 값을 직접 볼 수 없어요.\n"
            "  빈 상태에서 top()/front()/pop()을 하면 프로그램이 죽어요. 항상 empty() 확인 먼저!"
        ),
        usage="BFS 는 queue, DFS·괄호검사·후위표기는 stack, 슬라이딩 윈도우 최댓값은 deque 가 정석이다.",
        cons="stack/queue 는 중간 원소 접근이 안 된다. deque 는 인덱스 접근은 되지만 중간 삽입은 느리다.",
        code=(
            "#include <bits/stdc++.h>\n"
            "using namespace std;\n"
            "\n"
            "int main() {\n"
            "    deque<int> dq;\n"
            "    dq.push_back(2);\n"
            "    dq.push_front(1);\n"
            "    dq.push_back(3);\n"
            "    cout << \"덱 앞/뒤: \" << dq.front() << ' ' << dq.back() << \"\\n\"; // 1 3\n"
            "\n"
            "    stack<int> st;\n"
            "    st.push(10); st.push(20); st.push(30);\n"
            "    cout << \"스택 top: \" << st.top() << \"\\n\";  // 30 (마지막에 넣은 것)\n"
            "\n"
            "    queue<int> q;\n"
            "    q.push(10); q.push(20); q.push(30);\n"
            "    cout << \"큐 front: \" << q.front() << \"\\n\"; // 10 (처음에 넣은 것)\n"
            "    return 0;\n"
            "}\n"
        ),
    ),

    Lesson(
        id="cpp-adv-03",
        lang="cpp", level="고급",
        title="람다와 함수 객체",
        summary="[](){}  · 캡처 · 커스텀 정렬",
        explanation=(
            "━━ 람다(Lambda)와 함수 객체 란? ━━\n"
            "\n"
            "보통 함수는 이름을 붙여서 따로 만들어요.\n"
            "하지만 '딱 한 번만 쓸 건데 굳이 이름 짓기 귀찮다'고 느낄 때가 있어요.\n"
            "람다는 이름 없이 그 자리에서 즉석으로 만드는 일회용 함수예요!\n"
            "\n"
            "마치 배달앱에서 '이번 한 번만 이 주소로 배달'하는 것처럼,\n"
            "매번 새 함수를 등록하지 않고 그때그때 쓸 동작을 바로 전달해요.\n"
            "\n"
            "람다 문법: [캡처](매개변수) { 동작 }\n"
            "  [  ]  →  바깥 변수를 안 가져와요 (아무것도 캡처 안 함)\n"
            "  [&]   →  바깥 변수를 참조로 가져와요 (변경 가능)\n"
            "  [=]   →  바깥 변수를 복사해서 가져와요 (원본 변경 안 됨)\n"
            "  [x]   →  변수 x만 복사해서 가져와요\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  vector<int> v = {5, 2, 8, 1, 9, 3};\n"
            "      →  숫자 6개가 담긴 벡터를 만들어요.\n"
            "\n"
            "  sort(v.begin(), v.end(), [](int a, int b) { return a > b; });\n"
            "      →  벡터를 정렬하는데, 세 번째 인자로 람다를 넘겨요.\n"
            "         '두 원소 a, b를 비교할 때 a > b이면 a를 앞에 놓아라'는 뜻이에요.\n"
            "         즉 내림차순 정렬! []는 바깥 변수 안 씀, (int a, int b)는 비교할 두 값이에요.\n"
            "\n"
            "  for (int x : v) cout << x << ' ';\n"
            "      →  정렬된 벡터를 순서대로 출력해요. 결과: 9 8 5 3 2 1\n"
            "\n"
            "  int 기준 = 4;\n"
            "      →  비교 기준값 4를 담는 변수를 만들어요.\n"
            "\n"
            "  int cnt = count_if(v.begin(), v.end(), [기준](int x) { return x > 기준; });\n"
            "      →  벡터에서 조건을 만족하는 원소 개수를 세요.\n"
            "         [기준]은 바깥 변수 '기준'을 복사해서 람다 안으로 가져와요.\n"
            "         (int x) → 벡터 원소 하나하나\n"
            "         return x > 기준 → 기준(4)보다 크면 true → 개수에 포함\n"
            "         결과: 9, 8, 5가 4보다 크므로 cnt = 3\n"
            "\n"
            "주의할 점:\n"
            "  [&]로 캡처할 때 람다가 나중에 실행되면 그 사이에 변수가 사라질 수 있어요.\n"
            "  짧게 즉시 쓸 때는 괜찮지만, 람다를 나중에 쓰려고 저장할 때는 [=]로 복사하는 게 안전해요.\n"
            "  함수 객체(functor)는 operator()를 가진 구조체로 람다와 같은 역할을 해요.\n"
            "  람다는 함수 객체를 훨씬 짧게 표현하는 현대 C++ 방식이에요."
        ),
        usage="정렬 기준을 즉석에서 지정하거나, 알고리즘에 동작을 인자로 넘길 때 코드가 간결해진다.",
        cons="캡처를 [&] 로 무심코 쓰면 수명이 끝난 변수를 참조해 버그가 날 수 있어 캡처 범위를 명확히 해야 한다.",
        code=(
            "#include <bits/stdc++.h>\n"
            "using namespace std;\n"
            "\n"
            "int main() {\n"
            "    vector<int> v = {5, 2, 8, 1, 9, 3};\n"
            "\n"
            "    // 내림차순 정렬 (람다 비교자)\n"
            "    sort(v.begin(), v.end(), [](int a, int b) {\n"
            "        return a > b;\n"
            "    });\n"
            "    cout << \"내림차순: \";\n"
            "    for (int x : v) cout << x << ' ';\n"
            "    cout << \"\\n\";\n"
            "\n"
            "    // 값 캡처: 기준값보다 큰 원소 개수 세기\n"
            "    int 기준 = 4;\n"
            "    int cnt = count_if(v.begin(), v.end(), [기준](int x) {\n"
            "        return x > 기준;\n"
            "    });\n"
            "    cout << 기준 << \"보다 큰 원소 수: \" << cnt << \"\\n\"; // 3\n"
            "    return 0;\n"
            "}\n"
        ),
    ),

    Lesson(
        id="cpp-adv-04",
        lang="cpp", level="고급",
        title="이터레이터와 알고리즘 — lower_bound · upper_bound · accumulate",
        summary="이분 탐색 위치 · 구간 합",
        explanation=(
            "━━ lower_bound · upper_bound · accumulate 란? ━━\n"
            "\n"
            "도서관에서 책을 찾는다고 생각해봐요. 책이 가나다 순으로 정렬돼 있으면\n"
            "처음부터 찾지 않고 '대략 이쪽이겠지'하고 반으로 나눠가며 찾을 수 있어요.\n"
            "이것이 이분탐색(binary search)이고, lower_bound/upper_bound가 이걸 해줘요!\n"
            "\n"
            "lower_bound(시작, 끝, x)  →  x 이상인 값이 처음 나오는 위치를 찾아요\n"
            "upper_bound(시작, 끝, x)  →  x 초과인 값이 처음 나오는 위치를 찾아요\n"
            "\n"
            "예를 들어 [1, 2, 2, 2, 4, 5, 7]에서 2를 찾으면:\n"
            "  lower_bound → index 1 (처음 등장하는 2의 위치)\n"
            "  upper_bound → index 4 (2보다 큰 4의 위치)\n"
            "  두 위치의 차이(4-1=3)가 바로 2의 개수예요!\n"
            "\n"
            "accumulate는 범위의 모든 값을 더해줘요. 아주 간단해요!\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  vector<int> v = {1, 2, 2, 2, 4, 5, 7};\n"
            "      →  이미 정렬된 벡터를 만들어요. lower/upper_bound는 반드시 정렬 상태여야 해요!\n"
            "\n"
            "  auto lo = lower_bound(v.begin(), v.end(), 2);\n"
            "      →  2 이상인 값이 처음 나오는 위치를 찾아요.\n"
            "         반환값은 이터레이터(포인터 같은 것)예요. auto로 타입을 자동 추론해요.\n"
            "         v = [1, 2, 2, 2, 4, 5, 7]에서 2 이상이 처음 나오는 건 index 1이에요.\n"
            "\n"
            "  auto hi = upper_bound(v.begin(), v.end(), 2);\n"
            "      →  2 초과인 값이 처음 나오는 위치를 찾아요.\n"
            "         2 초과 = 3 이상이 처음 나오는 건 index 4 (값 4)예요.\n"
            "\n"
            "  cout << (lo - v.begin()) << \"\\n\";\n"
            "      →  이터레이터에서 begin()을 빼면 인덱스가 나와요. lo - v.begin() = 1\n"
            "         이 빼기 연산으로 '이터레이터 → 인덱스 번호' 변환을 해요.\n"
            "\n"
            "  cout << (hi - lo) << \"\\n\";\n"
            "      →  두 위치의 차이가 2의 개수예요. 4 - 1 = 3\n"
            "\n"
            "  int sum = accumulate(v.begin(), v.end(), 0);\n"
            "      →  v의 모든 원소를 더해요. 세 번째 인자 0은 시작값이에요.\n"
            "         1+2+2+2+4+5+7 = 23\n"
            "\n"
            "  cout << \"전체 합: \" << sum << \"\\n\";\n"
            "      →  결과 23을 출력해요.\n"
            "\n"
            "주의할 점:\n"
            "  lower_bound/upper_bound는 '정렬된 배열에서만' 정확하게 동작해요!\n"
            "  정렬 안 된 배열에 쓰면 결과가 완전히 엉뚱하게 나와요.\n"
            "  항상 sort()로 정렬한 다음에 사용하세요.\n"
            "  accumulate는 #include <numeric>이 필요해요 (bits/stdc++.h 쓰면 자동 포함)."
        ),
        usage="정렬된 배열에서 특정 값의 개수·삽입 위치를 빠르게 구하거나, 합/곱 누적을 한 줄로 처리할 때.",
        cons="lower_bound/upper_bound 는 범위가 반드시 정렬돼 있어야 정확하다. 정렬이 깨지면 결과가 틀린다.",
        code=(
            "#include <bits/stdc++.h>\n"
            "using namespace std;\n"
            "\n"
            "int main() {\n"
            "    vector<int> v = {1, 2, 2, 2, 4, 5, 7};  // 정렬된 상태\n"
            "\n"
            "    auto lo = lower_bound(v.begin(), v.end(), 2); // 2 이상 첫 위치\n"
            "    auto hi = upper_bound(v.begin(), v.end(), 2); // 2 초과 첫 위치\n"
            "    cout << \"2의 시작 인덱스: \" << (lo - v.begin()) << \"\\n\"; // 1\n"
            "    cout << \"2의 개수: \" << (hi - lo) << \"\\n\";              // 3\n"
            "\n"
            "    int sum = accumulate(v.begin(), v.end(), 0);\n"
            "    cout << \"전체 합: \" << sum << \"\\n\";   // 23\n"
            "    return 0;\n"
            "}\n"
        ),
    ),

    Lesson(
        id="cpp-adv-05",
        lang="cpp", level="고급",
        title="비트 연산과 비트마스킹",
        summary="& | ^ ~ << >> · 부분집합 표현",
        explanation=(
            "━━ 비트 연산과 비트마스킹 이란? ━━\n"
            "\n"
            "컴퓨터는 모든 것을 0과 1로 저장해요. 숫자 5는 이진수로 101이에요.\n"
            "비트 연산은 이 0과 1을 직접 다루는 연산이에요.\n"
            "\n"
            "전등 스위치로 비유해볼게요!\n"
            "방에 스위치 8개가 있어요(0번~7번). 각 스위치가 켜지면 1, 꺼지면 0이에요.\n"
            "mask = 10 (이진수 00001010) 은 1번과 3번 스위치만 켜진 상태예요.\n"
            "\n"
            "비트 연산자:\n"
            "  &  (AND)  →  둘 다 1이면 1  (두 스위치 모두 켜졌을 때만 작동)\n"
            "  |  (OR)   →  하나라도 1이면 1  (어느 스위치든 켜지면 작동)\n"
            "  ^  (XOR)  →  다르면 1  (하나만 켜졌을 때 작동)\n"
            "  ~  (NOT)  →  0→1, 1→0  (켜진 것은 끄고, 꺼진 것은 켜기)\n"
            "  << (왼쪽 시프트)   →  비트를 왼쪽으로 밀기 (1<<3 은 8)\n"
            "  >> (오른쪽 시프트) →  비트를 오른쪽으로 밀기\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  int mask = 0;\n"
            "      →  모든 스위치가 꺼진 상태로 시작해요. 이진수 00000000\n"
            "\n"
            "  mask |= (1 << 1);\n"
            "      →  1번 스위치를 켜요. (1<<1)은 이진수 00000010이에요.\n"
            "         OR 연산으로 해당 비트를 1로 만들어요. mask: 00000010 = 2\n"
            "\n"
            "  mask |= (1 << 3);\n"
            "      →  3번 스위치도 켜요. (1<<3)은 이진수 00001000이에요.\n"
            "         mask: 00001010 = 10 (2번 비트와 4번 비트가 켜진 상태)\n"
            "\n"
            "  cout << \"mask = \" << mask << \"\\n\";\n"
            "      →  mask 값 10을 출력해요 (이진수로는 1010)\n"
            "\n"
            "  cout << ((mask & (1 << 1)) ? 1 : 0) << \"\\n\";\n"
            "      →  1번 스위치가 켜져 있는지 확인해요.\n"
            "         mask & (1<<1) = 1010 & 0010 = 0010 (0이 아님) → 켜져 있으니 1 출력!\n"
            "         결과가 0이 아니면 해당 비트가 켜진 것, 0이면 꺼진 것이에요.\n"
            "\n"
            "  cout << __builtin_popcount(mask) << \"\\n\";\n"
            "      →  켜진 스위치(1인 비트)의 개수를 세요.\n"
            "         1010에서 1이 2개이므로 결과는 2\n"
            "         __builtin_popcount는 GCC가 제공하는 내장 함수로 매우 빨라요.\n"
            "\n"
            "  for (int s = 0; s < (1 << 3); s++) { ... }\n"
            "      →  (1<<3) = 8 이에요. s가 0~7 (이진수 000~111)까지 반복해요.\n"
            "         3개 원소의 모든 부분집합 8가지(공집합 포함)를 표현하는 거예요!\n"
            "         s=0: {} / s=1: {A} / s=2: {B} / s=3: {A,B} / ... / s=7: {A,B,C}\n"
            "\n"
            "  if (s & (1 << i)) cout << item[i];\n"
            "      →  s의 i번 비트가 1이면 item[i]를 출력해요.\n"
            "         부분집합에 i번 원소가 포함됐다는 뜻이에요!\n"
            "\n"
            "주의할 점:\n"
            "  (1<<i)처럼 반드시 괄호를 씌워야 해요. << 연산자 우선순위가 낮아서\n"
            "  1<<3 + 1 이라고 쓰면 1<<(3+1) = 16 이 되어 버려요!\n"
            "  n이 30 이상이면 1<<n 이 int 범위를 넘어요. 1LL<<n 처럼 long long으로 쓰세요.\n"
            "  코딩테스트에서 n<=20 정도까지만 비트마스크로 전체 탐색해요. n>=25면 시간초과 위험!"
        ),
        usage="집합 DP(외판원 TSP 등), 상태 압축, 부분집합 전체 탐색에서 메모리·속도를 크게 아낀다.",
        cons="가독성이 떨어지고 우선순위 실수가 잦다. (1<<i) 처럼 괄호를 꼭 씌우고, n이 크면 2^n 폭발에 주의.",
        code=(
            "#include <bits/stdc++.h>\n"
            "using namespace std;\n"
            "\n"
            "int main() {\n"
            "    int mask = 0;\n"
            "    mask |= (1 << 1);   // 1번 비트 켜기\n"
            "    mask |= (1 << 3);   // 3번 비트 켜기\n"
            "    cout << \"mask = \" << mask << \"\\n\";              // 10 (2진수 1010)\n"
            "    cout << \"1번 비트 켜짐? \" << ((mask & (1 << 1)) ? 1 : 0) << \"\\n\"; // 1\n"
            "    cout << \"켜진 비트 수: \" << __builtin_popcount(mask) << \"\\n\";     // 2\n"
            "\n"
            "    // {A,B,C} 3원소의 모든 부분집합 출력\n"
            "    string item[3] = {\"A\", \"B\", \"C\"};\n"
            "    for (int s = 0; s < (1 << 3); s++) {\n"
            "        cout << '{';\n"
            "        for (int i = 0; i < 3; i++)\n"
            "            if (s & (1 << i)) cout << item[i];\n"
            "        cout << \"} \";\n"
            "    }\n"
            "    cout << \"\\n\";\n"
            "    return 0;\n"
            "}\n"
        ),
    ),

    Lesson(
        id="cpp-adv-06",
        lang="cpp", level="고급",
        title="빠른 입출력 — ios_base::sync_with_stdio",
        summary="C 스트림 동기화 해제 · cin.tie 해제",
        explanation=(
            "━━ 빠른 입출력 — ios_base::sync_with_stdio 란? ━━\n"
            "\n"
            "cin/cout은 기본적으로 C언어의 scanf/printf와 함께 쓸 수 있도록 '동기화'되어 있어요.\n"
            "마치 두 팀이 같은 화이트보드를 공유하면서 서로 확인하며 쓰는 것처럼요.\n"
            "이 확인 과정 때문에 속도가 느려져요!\n"
            "\n"
            "sync_with_stdio(false)는 '이제 C언어 함수는 안 쓸 테니 동기화 그만해도 돼'라고 말하는 거예요.\n"
            "그러면 cin/cout이 독립적으로 동작해서 훨씬 빨라져요.\n"
            "\n"
            "cin.tie(NULL)은 또 다른 최적화예요. 기본적으로 cin은 읽기 전에 cout을 먼저 비워요(flush).\n"
            "'화면에 다 표시하고 나서 입력받을게'하는 건데, 이것도 불필요한 경우가 많아요.\n"
            "cin.tie(NULL)로 이 연결을 끊으면 더 빨라져요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  ios_base::sync_with_stdio(false);\n"
            "      →  cin/cout 과 scanf/printf의 동기화를 끊어요.\n"
            "         이 한 줄로 입출력이 몇 배 빨라질 수 있어요!\n"
            "         반드시 main() 맨 위에서 딱 한 번만 쓰세요.\n"
            "\n"
            "  cin.tie(NULL);\n"
            "      →  cin이 cout을 자동으로 flush하는 것을 막아요.\n"
            "         위의 sync_with_stdio(false)와 항상 세트로 쓰는 관용구예요.\n"
            "\n"
            "  int n = 5;\n"
            "      →  반복 횟수 5를 저장해요. 실제 문제에서는 cin >> n; 으로 입력받아요.\n"
            "\n"
            "  long long sum = 0;\n"
            "      →  합계를 저장할 변수예요. 큰 수가 될 수 있으니 long long을 써요.\n"
            "         int는 약 21억까지, long long은 약 920경까지 저장 가능해요.\n"
            "\n"
            "  for (int i = 1; i <= n; i++) {\n"
            "      →  1부터 n까지 반복해요.\n"
            "\n"
            "  sum += i;\n"
            "      →  합계에 i를 더해요. 1+2+3+4+5 = 15\n"
            "\n"
            "  cout << i << (i < n ? ' ' : '\\n');\n"
            "      →  i를 출력하고, 마지막이 아니면 공백, 마지막이면 줄바꿈을 출력해요.\n"
            "         endl 대신 '\\n'을 쓰는 게 핵심이에요!\n"
            "         endl은 출력 후 강제로 버퍼를 비워서(flush) 훨씬 느려요.\n"
            "\n"
            "  cout << \"합: \" << sum << \"\\n\";\n"
            "      →  최종 합계 15를 출력해요.\n"
            "\n"
            "주의할 점:\n"
            "  sync_with_stdio(false) 후에는 절대 scanf/printf를 섞어 쓰면 안 돼요!\n"
            "  순서가 뒤섞여서 결과가 이상하게 나올 수 있어요.\n"
            "  endl은 매번 flush를 하므로 입력이 많은 문제에서 TLE(시간초과)의 원인이 돼요.\n"
            "  이 두 줄은 코딩테스트에서 거의 모든 C++ 코드에 맨 위에 붙이는 '필수 주문'이에요!"
        ),
        usage="입력이 수십만 줄 이상인 백준 문제에서 시간초과를 피하는 거의 필수 관용구.",
        cons="동기화를 끄면 C 입출력(scanf/printf)과 섞어 쓰면 안 된다. main 시작부에 한 번만 설정한다.",
        code=(
            "#include <bits/stdc++.h>\n"
            "using namespace std;\n"
            "\n"
            "int main() {\n"
            "    ios_base::sync_with_stdio(false);\n"
            "    cin.tie(NULL);\n"
            "\n"
            "    // 데모: 입력 대신 고정값으로 빠른 출력 시연\n"
            "    int n = 5;\n"
            "    long long sum = 0;\n"
            "    for (int i = 1; i <= n; i++) {\n"
            "        sum += i;\n"
            "        cout << i << (i < n ? ' ' : '\\n');  // endl 대신 '\\n'\n"
            "    }\n"
            "    cout << \"합: \" << sum << \"\\n\";   // 15\n"
            "    return 0;\n"
            "}\n"
        ),
    ),

    Lesson(
        id="cpp-adv-07",
        lang="cpp", level="고급",
        title="multiset · multimap",
        summary="중복 허용 정렬 컨테이너",
        explanation=(
            "━━ multiset · multimap 이란? ━━\n"
            "\n"
            "set은 같은 값을 하나만 저장하는 자동 정렬 집합이에요.\n"
            "그런데 같은 값이 여러 개 있어야 한다면? 그때 multiset을 써요!\n"
            "\n"
            "실생활로 비유하면, 시험 점수 관리를 생각해봐요.\n"
            "set에서는 100점이 여러 명이어도 100점 하나만 기억해요.\n"
            "multiset에서는 100점이 5명이면 100이 5개 저장돼요.\n"
            "\n"
            "그리고 모든 원소가 자동으로 정렬되어 있어요!\n"
            "begin()은 항상 최솟값, rbegin()은 항상 최댓값을 가리켜요.\n"
            "삽입/삭제/탐색이 모두 O(log n)으로 빨라요.\n"
            "\n"
            "multimap은 같은 키(key)에 여러 값을 저장할 수 있는 정렬된 맵이에요.\n"
            "'김씨 학생이 여러 명인데 각각 점수를 저장하고 싶다'는 상황에 딱이에요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  multiset<int> ms;\n"
            "      →  정수를 담는 멀티셋을 만들어요. 중복 허용, 자동 정렬!\n"
            "\n"
            "  for (int x : {5, 1, 3, 1, 5, 1}) ms.insert(x);\n"
            "      →  5, 1, 3, 1, 5, 1을 하나씩 넣어요.\n"
            "         자동으로 정렬되니 내부는 {1, 1, 1, 3, 5, 5} 상태예요.\n"
            "\n"
            "  for (int x : ms) cout << x << ' ';\n"
            "      →  정렬된 순서로 출력해요. 결과: 1 1 1 3 5 5\n"
            "\n"
            "  cout << ms.count(1) << \"\\n\";\n"
            "      →  1이 몇 개 들어있는지 세요. 결과: 3\n"
            "\n"
            "  cout << *ms.begin() << \"\\n\";\n"
            "      →  begin()은 가장 작은 원소를 가리키는 이터레이터예요.\n"
            "         앞에 *를 붙여서 실제 값을 꺼내요. 결과: 1\n"
            "\n"
            "  ms.erase(ms.find(1));\n"
            "      →  ★★★ 매우 중요한 코드예요! ★★★\n"
            "         ms.erase(1) 이라고 하면 1이 '전부' 삭제돼요 (3개 모두!).\n"
            "         ms.find(1)은 1이 있는 위치(이터레이터) 하나를 반환해요.\n"
            "         그 위치 하나만 erase하면 1이 딱 '하나만' 삭제돼요.\n"
            "\n"
            "  cout << ms.count(1) << \"\\n\";\n"
            "      →  하나 삭제 후 1의 개수. 결과: 2 (3개에서 1개 지웠으니까)\n"
            "\n"
            "  multimap<string, int> mm;\n"
            "      →  문자열 키, 정수 값의 멀티맵을 만들어요.\n"
            "\n"
            "  mm.insert({\"kim\", 90}); mm.insert({\"kim\", 85});\n"
            "      →  같은 키 \"kim\"에 90과 85 두 값을 넣어요. 일반 map은 이게 안 돼요!\n"
            "\n"
            "  cout << mm.count(\"kim\") << \"\\n\";\n"
            "      →  \"kim\" 키의 개수. 결과: 2\n"
            "\n"
            "주의할 점:\n"
            "  erase(값)은 그 값 전부를 지워요. 하나만 지우려면 반드시 erase(find(값))을 써야 해요!\n"
            "  이건 코딩테스트에서 자주 실수하는 함정이에요. 꼭 기억하세요!\n"
            "  해시(unordered_*)보다 상수가 크고 메모리도 더 써요.\n"
            "  단순 조회만 필요하면 unordered_set/unordered_map 계열이 더 빨라요."
        ),
        usage="정렬 상태를 유지하면서 중복값을 다루거나, 최솟/최댓값을 계속 꺼내며 임의 삭제도 필요할 때.",
        cons="해시(unordered_*)보다 상수가 크고 메모리도 더 쓴다. 단순 조회만 필요하면 unordered 계열이 빠르다.",
        code=(
            "#include <bits/stdc++.h>\n"
            "using namespace std;\n"
            "\n"
            "int main() {\n"
            "    multiset<int> ms;\n"
            "    for (int x : {5, 1, 3, 1, 5, 1}) ms.insert(x);\n"
            "\n"
            "    cout << \"정렬+중복: \";\n"
            "    for (int x : ms) cout << x << ' ';   // 1 1 1 3 5 5\n"
            "    cout << \"\\n\";\n"
            "    cout << \"1의 개수: \" << ms.count(1) << \"\\n\";   // 3\n"
            "    cout << \"최솟값: \" << *ms.begin() << \"\\n\";      // 1\n"
            "\n"
            "    ms.erase(ms.find(1));   // 1을 '하나만' 삭제\n"
            "    cout << \"하나 삭제 후 1의 개수: \" << ms.count(1) << \"\\n\"; // 2\n"
            "\n"
            "    multimap<string, int> mm;\n"
            "    mm.insert({\"kim\", 90});\n"
            "    mm.insert({\"kim\", 85});\n"
            "    cout << \"kim 키 개수: \" << mm.count(\"kim\") << \"\\n\"; // 2\n"
            "    return 0;\n"
            "}\n"
        ),
    ),

    Lesson(
        id="cpp-adv-08",
        lang="cpp", level="고급",
        title="auto · 범위 기반 for · 구조적 바인딩",
        summary="타입 추론 · for(x : v) · auto [a,b]",
        explanation=(
            "━━ auto · 범위 기반 for · 구조적 바인딩 이란? ━━\n"
            "\n"
            "C++에서는 변수를 만들 때 타입을 직접 써야 해요.\n"
            "그런데 map의 이터레이터 타입을 쓰려면 이렇게 엄청나게 길어요:\n"
            "  map<string, int>::iterator it = m.begin();\n"
            "\n"
            "이걸 auto 하나로 간단하게 쓸 수 있어요:\n"
            "  auto it = m.begin();\n"
            "\n"
            "auto는 '오른쪽 값을 보고 알아서 타입을 정해줘'라는 뜻이에요.\n"
            "마치 짐 배달에서 '내용물에 맞는 박스를 알아서 골라줘'하는 것처럼요!\n"
            "\n"
            "범위 기반 for는 배열/벡터의 모든 원소를 순서대로 하나씩 꺼내주는 반복문이에요.\n"
            "인덱스(i=0; i<n; i++)를 쓰지 않아도 돼서 코드가 훨씬 깔끔해요.\n"
            "\n"
            "구조적 바인딩(C++17)은 pair나 tuple을 한 번에 여러 변수로 쪼개주는 기능이에요.\n"
            "마치 선물 세트를 열어서 각 물건에 이름표를 한꺼번에 붙이는 것처럼요!\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  vector<int> v = {10, 20, 30};\n"
            "      →  정수 벡터를 만들어요.\n"
            "\n"
            "  for (auto& x : v) x += 1;\n"
            "      →  v의 모든 원소를 순서대로 꺼내서 x라고 불러요.\n"
            "         &를 붙여서 참조로 받아요. 참조로 받아야 x를 바꿀 때 원본 v도 바뀌어요.\n"
            "         x += 1로 각 원소를 1씩 더해요. 결과: {11, 21, 31}\n"
            "\n"
            "  for (auto x : v) cout << x << ' ';\n"
            "      →  이번엔 & 없이 복사로 받아요. 출력만 할 때는 복사로 충분해요.\n"
            "         결과: 11 21 31\n"
            "\n"
            "  map<string, int> score = {{\"kim\", 90}, {\"lee\", 80}};\n"
            "      →  이름→점수 맵을 만들어요.\n"
            "\n"
            "  for (const auto& [name, point] : score)\n"
            "      →  map의 각 항목을 [name, point]로 쪼개서 받아요.\n"
            "         이게 구조적 바인딩이에요! pair를 분해해서 key→name, value→point로 받아요.\n"
            "         const auto&는 '복사 안 하고 참조로 받되 변경은 안 해'라는 뜻이에요.\n"
            "\n"
            "  cout << name << \": \" << point << \"\\n\";\n"
            "      →  이름과 점수를 출력해요. 결과: kim: 90 / lee: 80 (알파벳 순으로 정렬)\n"
            "\n"
            "  auto [a, b] = make_pair(1, 2);\n"
            "      →  pair를 만들고 a=1, b=2로 한 번에 분해해요.\n"
            "         예전엔 pair.first, pair.second를 써야 했는데 훨씬 편리해요!\n"
            "\n"
            "  cout << a + b << \"\\n\";\n"
            "      →  결과: 3\n"
            "\n"
            "주의할 점:\n"
            "  for (auto x : v)에서 x를 바꿔도 원본 v는 안 바뀌어요 (복사이므로).\n"
            "  원본을 바꾸려면 반드시 for (auto& x : v)로 참조로 받아야 해요.\n"
            "  구조적 바인딩 auto [a, b]는 C++17 이상에서만 동작해요.\n"
            "  컴파일 시 -std=c++17 플래그를 쓰거나 IDE에서 C++17을 설정해야 해요.\n"
            "  auto가 의도와 다른 타입으로 추론될 수 있으니 (예: 참조가 복사로),\n"
            "  동작이 이상하면 auto 대신 명시적 타입을 써서 확인해보세요."
        ),
        usage="map 순회 시 auto& [key, val], 이터레이터 타입 생략 등에서 코드가 짧고 명확해진다.",
        cons="auto 는 의도한 타입과 다르게 추론될 수 있어(예: 참조가 복사로) 성능·동작 의도를 분명히 해야 한다.",
        code=(
            "#include <bits/stdc++.h>\n"
            "using namespace std;\n"
            "\n"
            "int main() {\n"
            "    vector<int> v = {10, 20, 30};\n"
            "\n"
            "    // 범위 기반 for + 참조로 값 수정\n"
            "    for (auto& x : v) x += 1;\n"
            "    cout << \"수정 후: \";\n"
            "    for (auto x : v) cout << x << ' ';   // 11 21 31\n"
            "    cout << \"\\n\";\n"
            "\n"
            "    // map 순회 + 구조적 바인딩\n"
            "    map<string, int> score = {{\"kim\", 90}, {\"lee\", 80}};\n"
            "    for (const auto& [name, point] : score)\n"
            "        cout << name << \": \" << point << \"\\n\";\n"
            "\n"
            "    // pair 분해\n"
            "    auto [a, b] = make_pair(1, 2);\n"
            "    cout << \"a+b = \" << a + b << \"\\n\";   // 3\n"
            "    return 0;\n"
            "}\n"
        ),
    ),
]
