"""Java 고급 문법 (스트림/람다/자료구조/제네릭/비트/입출력/Optional)."""

from engine.models import Lesson

LESSONS = [

    Lesson(
        id="java-adv-01",
        lang="java", level="고급",
        title="스트림 API (stream/map/filter/collect)",
        summary="컬렉션을 선언적으로 가공 · 중간연산/최종연산",
        explanation=(
            "[개요]\n"
            "스트림 API는 컬렉션의 데이터를 선언적으로 필터링·변환·집계하는 기능이다.\n"
            "\n"
            "숫자 리스트에서 짝수만 골라 제곱한 뒤 새 리스트를 만드는 작업을 예로 든다.\n"
            "기존 for 루프 방식은 다음과 같다.\n"
            "  List<Integer> result = new ArrayList<>();\n"
            "  for (int n : nums) {\n"
            "      if (n % 2 == 0) result.add(n * n);\n"
            "  }\n"
            "\n"
            "스트림 API를 사용하면 동일한 처리를 한 줄로 표현할 수 있다.\n"
            "  nums.stream().filter(n -> n % 2 == 0).map(n -> n * n).collect(Collectors.toList())\n"
            "\n"
            "데이터가 원재료(리스트)로 들어와 필터(조건 미충족 제거) → 가공(변환) → 완제품 수집 순서로 흐르는 컨베이어 벨트 구조로 이해할 수 있다.\n"
            "\n"
            "[핵심 개념]\n"
            "스트림은 두 종류의 연산으로 구성된다.\n"
            "1) 중간 연산 (filter, map 등)\n"
            "   • 호출 시점에는 실제 실행되지 않고 처리 계획만 정의한다.\n"
            "2) 최종 연산 (collect, sum, count 등)\n"
            "   • 이 시점에 실제 계산이 한꺼번에 수행된다.\n"
            "이러한 방식을 지연 평가(Lazy Evaluation)라 하며, 불필요한 계산을 최소화한다.\n"
            "\n"
            "[코드 분석]\n"
            "  List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5, 6);\n"
            "  → 1~6의 숫자가 담긴 리스트를 생성한다. Arrays.asList()는 배열을 리스트로 변환하는 편의 메서드이다.\n"
            "\n"
            "  List<Integer> result = nums.stream()\n"
            "  → nums 리스트를 스트림(처리 흐름)으로 변환한다. 이 시점에는 계산이 수행되지 않는다.\n"
            "\n"
            "  .filter(n -> n % 2 == 0)\n"
            "  → 각 숫자 n 중 짝수(2로 나눈 나머지가 0)만 통과시킨다. n -> 조건 에서 화살표 왼쪽이 입력(n), 오른쪽이 참/거짓 판단식이다. 2, 4, 6만 남고 1, 3, 5는 제외된다.\n"
            "\n"
            "  .map(n -> n * n)\n"
            "  → 남은 숫자(2, 4, 6)를 각각 제곱으로 변환한다(2→4, 4→16, 6→36). map은 원소를 다른 값으로 1:1 변환하는 연산이다.\n"
            "\n"
            "  .collect(Collectors.toList());\n"
            "  → 변환된 값들을 List로 수집한다. 이 줄이 실행되는 시점에 앞의 filter와 map이 실제로 수행된다.\n"
            "\n"
            "  int sum = nums.stream().filter(n -> n > 3).mapToInt(Integer::intValue).sum();\n"
            "  → 3보다 큰 숫자(4, 5, 6)를 골라 int 기본형 스트림으로 변환한 뒤 합산한다. mapToInt를 쓰는 이유는 Integer 객체가 아닌 int 기본형이어야 .sum()을 사용할 수 있기 때문이다. Integer::intValue는 Integer 객체에서 int 기본값을 꺼내는 메서드 참조이다.\n"
            "\n"
            "  .collect(Collectors.joining(\", \"))\n"
            "  → 문자열들을 ', '로 연결하여 하나의 문자열로 만든다. [\"kim\", \"lee\", \"park\"] → 대문자 변환 후 → \"KIM, LEE, PARK\".\n"
            "\n"
            "[유의 사항]\n"
            "• 스트림은 한 번만 사용할 수 있다. 같은 스트림에 최종 연산을 두 번 호출하면 IllegalStateException이 발생한다.\n"
            "• 단순 for 루프보다 느릴 수 있고, 오류 발생 위치의 디버깅이 어려울 수 있다.\n"
            "• 코딩테스트보다는 실무 코드의 가독성을 높이는 데 강점이 있다."
        ),
        usage="데이터 필터링/변환/집계를 한 줄로 표현할 때. 코딩테스트보다는 실무 가독성에 강점.",
        cons="단순 반복엔 일반 for 보다 느리고 디버깅이 까다롭다. 대량 원소 박싱 비용도 주의.",
        code=(
            "import java.util.*;\n"
            "import java.util.stream.*;\n"
            "\n"
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5, 6);\n"
            "        // 짝수만 골라 제곱한 뒤 리스트로 수집\n"
            "        List<Integer> result = nums.stream()\n"
            "                .filter(n -> n % 2 == 0)\n"
            "                .map(n -> n * n)\n"
            "                .collect(Collectors.toList());\n"
            "        System.out.println(\"짝수의 제곱: \" + result);\n"
            "\n"
            "        int sum = nums.stream().filter(n -> n > 3).mapToInt(Integer::intValue).sum();\n"
            "        System.out.println(\"3 초과 합계: \" + sum);\n"
            "\n"
            "        List<String> names = Arrays.asList(\"kim\", \"lee\", \"park\");\n"
            "        String joined = names.stream().map(String::toUpperCase).collect(Collectors.joining(\", \"));\n"
            "        System.out.println(\"대문자 연결: \" + joined);\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-adv-02",
        lang="java", level="고급",
        title="람다와 함수형 인터페이스",
        summary="익명 함수 · Function/Predicate/Supplier/Consumer",
        explanation=(
            "[개요]\n"
            "람다(lambda)는 이름이 없는 짧은 함수이다.\n"
            "숫자를 받아 제곱해 반환하는 함수를 기존 방식으로 작성하면 다음과 같다.\n"
            "  int square(int x) { return x * x; }\n"
            "\n"
            "람다 방식으로는 동일한 내용을 한 줄로 작성할 수 있다.\n"
            "  x -> x * x\n"
            "화살표 왼쪽이 입력(x), 오른쪽이 반환할 계산식이며, 위 메서드와 의미가 동일하다.\n"
            "\n"
            "[핵심 개념]\n"
            "람다를 변수에 담으려면 함수형 인터페이스가 필요하다. 함수형 인터페이스란 추상 메서드(구현 없는 메서드)가 정확히 하나뿐인 인터페이스이다.\n"
            "\n"
            "Java가 기본 제공하는 함수형 인터페이스 5가지는 다음과 같다.\n"
            "• Function<T, R>       : T를 받아 R로 반환. 예) 숫자 → 제곱값\n"
            "• Predicate<T>         : T를 받아 true/false 반환. 예) 짝수 판단\n"
            "• Supplier<T>          : 입력 없이 T를 생성해 공급. 예) '안녕하세요' 반환\n"
            "• Consumer<T>          : T를 받아 소비, 결과 없음. 예) 출력\n"
            "• BiFunction<T, U, R>  : T와 U 두 개를 받아 R 반환. 예) 두 수의 합\n"
            "\n"
            "람다를 사용하면 함수(동작) 자체를 변수에 담아 다른 메서드에 인자로 전달할 수 있다. 정렬 기준을 메서드에 넘기거나, 버튼 클릭 시 실행할 동작을 미리 지정하는 경우에 활용된다.\n"
            "\n"
            "[코드 분석]\n"
            "  Function<Integer, Integer> square = x -> x * x;\n"
            "  → Integer를 받아 Integer를 반환하는 함수를 정의한다. 입력 x를 제곱해 반환하며, Function<입력타입, 반환타입> 형식이다.\n"
            "\n"
            "  Predicate<Integer> isEven = x -> x % 2 == 0;\n"
            "  → Integer를 받아 true/false를 반환하는 함수이다. 짝수면 true, 홀수면 false를 반환한다.\n"
            "\n"
            "  Supplier<String> hello = () -> \"안녕하세요\";\n"
            "  → 입력 없이(빈 괄호 ()) 항상 '안녕하세요' 문자열을 공급(반환)하는 함수이다. get() 호출 시 값이 반환된다.\n"
            "\n"
            "  Consumer<String> printer = s -> System.out.println(\"출력: \" + s);\n"
            "  → 문자열을 받아 출력하고 반환값은 없는 함수이다. 값을 소비만 한다.\n"
            "\n"
            "  BiFunction<Integer, Integer, Integer> add = (a, b) -> a + b;\n"
            "  → 정수 두 개(a, b)를 받아 더한 결과를 반환한다. BiFunction<첫번째입력, 두번째입력, 반환타입> 형식이다.\n"
            "\n"
            "  square.apply(5)\n"
            "  → Function 타입 함수는 .apply(인자)로 실행한다. 5를 넣으면 25가 반환된다.\n"
            "\n"
            "  isEven.test(4)\n"
            "  → Predicate 타입 함수는 .test(인자)로 실행한다. 4는 짝수이므로 true.\n"
            "\n"
            "  hello.get()\n"
            "  → Supplier 타입 함수는 .get()으로 실행하며 인자 없이 호출한다.\n"
            "\n"
            "  printer.accept(hello.get())\n"
            "  → Consumer 타입 함수는 .accept(인자)로 실행한다. hello.get()으로 '안녕하세요'를 얻은 뒤 printer에 전달한다.\n"
            "\n"
            "  Function<Integer, Integer> squarePlusOne = square.andThen(x -> x + 1);\n"
            "  → andThen은 함수 합성이다. square를 먼저 실행한 결과에 x+1을 적용한다. squarePlusOne.apply(4)는 4 제곱 = 16, 16 + 1 = 17을 반환한다.\n"
            "\n"
            "  String::toUpperCase\n"
            "  → 메서드 참조 방식으로 람다를 더 짧게 표현할 수 있다. s -> s.toUpperCase() 와 String::toUpperCase 는 동일한 의미이다.\n"
            "\n"
            "[유의 사항]\n"
            "• 람다를 과도하게 중첩하면 가독성이 떨어진다. 복잡한 로직은 일반 메서드로 분리하고, 람다에서 그 메서드를 참조하는 것이 바람직하다.\n"
            "• 람다 안에서 IOException 같은 체크 예외를 던지려면 try-catch로 감싸야 하므로 처리가 번거롭다."
        ),
        usage="콜백, 정렬 비교자(Comparator), 스트림 연산 등에 동작 자체를 인자로 넘길 때.",
        cons="과하게 중첩하면 가독성이 떨어진다. 체크 예외를 던지는 코드는 람다에서 다루기 번거롭다.",
        code=(
            "import java.util.function.*;\n"
            "\n"
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        Function<Integer, Integer> square = x -> x * x;\n"
            "        Predicate<Integer> isEven = x -> x % 2 == 0;\n"
            "        Supplier<String> hello = () -> \"안녕하세요\";\n"
            "        Consumer<String> printer = s -> System.out.println(\"출력: \" + s);\n"
            "        BiFunction<Integer, Integer, Integer> add = (a, b) -> a + b;\n"
            "\n"
            "        System.out.println(\"제곱(5): \" + square.apply(5));\n"
            "        System.out.println(\"4는 짝수? \" + isEven.test(4));\n"
            "        System.out.println(\"공급: \" + hello.get());\n"
            "        printer.accept(hello.get());\n"
            "        System.out.println(\"덧셈(3,7): \" + add.apply(3, 7));\n"
            "\n"
            "        // 함수 합성: andThen\n"
            "        Function<Integer, Integer> squarePlusOne = square.andThen(x -> x + 1);\n"
            "        System.out.println(\"제곱+1(4): \" + squarePlusOne.apply(4));\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-adv-03",
        lang="java", level="고급",
        title="우선순위 큐 (PriorityQueue)",
        summary="힙 기반 · 최소/최대 힙 · O(log n) 삽입/삭제",
        explanation=(
            "[개요]\n"
            "PriorityQueue(우선순위 큐)는 삽입 순서가 아니라 우선순위에 따라 원소를 꺼내는 자료구조이다. 응급실에서 도착 순서가 아니라 위급도가 높은 환자를 먼저 치료하는 방식과 동일하다.\n"
            "\n"
            "기본값은 숫자가 작은 것이 먼저 나오는 최소 힙(min-heap)이다. 최대 힙(숫자가 큰 것이 먼저)을 원하면 Collections.reverseOrder()를 지정한다.\n"
            "\n"
            "[핵심 개념]\n"
            "• 내부 구조는 이진 힙(Binary Heap) 트리이다.\n"
            "• 삽입과 삭제 모두 O(log n) 시간이 소요된다. 원소가 1000개여도 꺼내는 데 약 10번의 비교만 필요하다(log2(1000) ≈ 10). 일반 리스트에서 최솟값을 찾는 데 1000번 비교가 필요한 것에 비해 빠르다.\n"
            "\n"
            "주요 활용처는 다음과 같다.\n"
            "• 다익스트라 알고리즘: 현재까지 거리가 가장 짧은 정점을 빠르게 찾을 때\n"
            "• 상위 K개 값 추적: 대량 데이터 중 가장 큰 K개만 뽑을 때\n"
            "• 작업 스케줄링: 우선순위가 높은 작업을 먼저 처리할 때\n"
            "\n"
            "[코드 분석]\n"
            "  PriorityQueue<Integer> minHeap = new PriorityQueue<>();\n"
            "  → 비어 있는 최소 힙을 생성한다. Integer를 담으며 기본값은 작은 숫자 우선이다.\n"
            "\n"
            "  for (int v : new int[]{5, 1, 8, 3, 2}) minHeap.offer(v);\n"
            "  → 5, 1, 8, 3, 2를 하나씩 힙에 추가한다. offer(v)는 원소 추가 메서드이며, 추가할 때마다 힙 구조가 자동으로 유지된다.\n"
            "\n"
            "  while (!minHeap.isEmpty()) sb.append(minHeap.poll()).append(' ');\n"
            "  → 힙이 빌 때까지 poll()로 원소를 하나씩 꺼낸다. 항상 가장 작은 값이 먼저 나온다. 결과는 오름차순 1 2 3 5 8 이다.\n"
            "\n"
            "  PriorityQueue<Integer> maxHeap = new PriorityQueue<>(Collections.reverseOrder());\n"
            "  → Collections.reverseOrder()는 비교 순서를 역순으로 만든다. 이를 생성자에 지정하면 가장 큰 값이 먼저 나오는 최대 힙이 된다.\n"
            "\n"
            "  maxHeap.peek()\n"
            "  → 맨 앞 원소(현재 최댓값)를 제거하지 않고 확인만 한다. peek은 조회, poll은 꺼내며 제거한다.\n"
            "\n"
            "  PriorityQueue<String> byLen = new PriorityQueue<>(Comparator.comparingInt(String::length));\n"
            "  → 문자열을 길이 기준으로 정렬하는 힙이다. Comparator.comparingInt(String::length)는 각 문자열의 길이(int)를 기준으로 비교하며, 길이가 짧은 문자열이 먼저 나온다.\n"
            "\n"
            "[유의 사항]\n"
            "• for문으로 순회하면 정렬 순서대로 나오지 않는다. 우선순위 순서를 보장받으려면 반드시 poll()로 하나씩 꺼내야 한다.\n"
            "• 중간 원소를 찾거나 수정하는 연산은 O(n)으로 느리므로 그 목적에는 부적합하다.\n"
            "• 같은 우선순위를 가진 원소들 사이의 순서는 보장되지 않는다."
        ),
        usage="다익스트라 최단경로, 작업 스케줄링, K번째 최소/최대 값 추적 등.",
        cons="중간 원소 임의 접근/검색은 O(n)으로 느리다. 정렬된 전체 순회는 보장되지 않는다.",
        code=(
            "import java.util.*;\n"
            "\n"
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        // 최소 힙\n"
            "        PriorityQueue<Integer> minHeap = new PriorityQueue<>();\n"
            "        for (int v : new int[]{5, 1, 8, 3, 2}) minHeap.offer(v);\n"
            "        StringBuilder sb = new StringBuilder(\"최소힙 꺼내기: \");\n"
            "        while (!minHeap.isEmpty()) sb.append(minHeap.poll()).append(' ');\n"
            "        System.out.println(sb.toString().trim());\n"
            "\n"
            "        // 최대 힙\n"
            "        PriorityQueue<Integer> maxHeap = new PriorityQueue<>(Collections.reverseOrder());\n"
            "        for (int v : new int[]{5, 1, 8, 3, 2}) maxHeap.offer(v);\n"
            "        System.out.println(\"최댓값(peek): \" + maxHeap.peek());\n"
            "\n"
            "        // 문자열 길이 기준 우선순위\n"
            "        PriorityQueue<String> byLen = new PriorityQueue<>(Comparator.comparingInt(String::length));\n"
            "        byLen.add(\"가나다\"); byLen.add(\"가\"); byLen.add(\"가나\");\n"
            "        System.out.println(\"가장 짧은 단어: \" + byLen.poll());\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-adv-04",
        lang="java", level="고급",
        title="ArrayDeque (스택/큐)",
        summary="양쪽 끝 O(1) · Stack/LinkedList 대체",
        explanation=(
            "[개요]\n"
            "ArrayDeque(Deque = Double-Ended Queue, 양방향 큐)는 앞뒤 양쪽 모두에서 원소를 넣고 꺼낼 수 있는 자료구조이다. 일반 큐는 앞에서 나가고 뒤에서 들어오며, 스택은 한쪽 끝에서만 넣고 꺼내는 것과 대비된다.\n"
            "\n"
            "[핵심 개념]\n"
            "용도에 따라 두 가지로 사용한다.\n"
            "• 스택으로 사용: push(앞에 넣기) → pop(앞에서 꺼내기) → 후입선출(LIFO)\n"
            "• 큐로 사용: offer(뒤에 넣기) → poll(앞에서 꺼내기) → 선입선출(FIFO)\n"
            "\n"
            "구식 Stack 클래스 대신 ArrayDeque를 사용하는 이유는 다음과 같다.\n"
            "• 구식 Stack 클래스는 Vector를 상속받아 불필요한 동기화(thread-safe) 처리가 있어 느리다.\n"
            "• ArrayDeque는 배열 기반이라 캐시 효율이 좋고, 앞뒤 삽입/삭제가 모두 O(1)이다.\n"
            "• 공식 Java 문서도 Stack 대신 ArrayDeque 사용을 권장한다.\n"
            "\n"
            "[코드 분석]\n"
            "  Deque<Integer> stack = new ArrayDeque<>();\n"
            "  → 정수를 담는 양방향 큐를 생성한다. Deque는 인터페이스(설계도), ArrayDeque는 구현체이다. 스택 용도이므로 변수명을 stack으로 지정했다.\n"
            "\n"
            "  stack.push(1); stack.push(2); stack.push(3);\n"
            "  → 1, 2, 3을 순서대로 넣는다. push는 Deque의 앞쪽(First)에 추가하므로 내부 순서는 [3, 2, 1]이다(가장 마지막에 넣은 3이 앞에 위치).\n"
            "\n"
            "  stack.peek()\n"
            "  → 스택 맨 위(가장 최근에 넣은 것)를 제거하지 않고 조회한다. 결과는 3이다.\n"
            "\n"
            "  stack.pop()\n"
            "  → 스택 맨 위에서 원소를 꺼내며 제거한다. 3, 2, 1 순서로 나온다(후입선출).\n"
            "\n"
            "  Deque<String> queue = new ArrayDeque<>();\n"
            "  → 문자열을 담는 양방향 큐를 생성한다. 이번에는 큐 용도로 사용한다.\n"
            "\n"
            "  queue.offer(\"A\"); queue.offer(\"B\"); queue.offer(\"C\");\n"
            "  → A, B, C를 뒤쪽에 차례로 넣는다. offer는 Deque의 뒤쪽(Last)에 추가하므로 내부 순서는 [A, B, C]이다.\n"
            "\n"
            "  queue.poll()\n"
            "  → 앞쪽에서 원소를 꺼내며 제거한다. A, B, C 순서로 나온다(선입선출).\n"
            "\n"
            "  dq.offerFirst(10); dq.offerLast(20); dq.offerFirst(5);\n"
            "  → offerFirst는 앞에 넣기, offerLast는 뒤에 넣기이다. 결과 순서는 [5, 10, 20]이다.\n"
            "\n"
            "  dq.peekFirst(), dq.peekLast()\n"
            "  → 앞/뒤 원소를 제거하지 않고 조회한다.\n"
            "\n"
            "[유의 사항]\n"
            "• null을 저장할 수 없다. null을 offer하면 NullPointerException이 발생한다.\n"
            "• 인덱스로 중간 원소에 접근할 수 없다. 중간 원소 접근이 필요하면 ArrayList를 사용한다.\n"
            "• push/pop은 앞쪽(First)을 사용하고, offer/poll은 뒤에서 넣어 앞에서 꺼낸다. 이 차이에 유의한다."
        ),
        usage="DFS의 명시적 스택, BFS 큐, 슬라이딩 윈도우 최댓값(단조 덱) 등.",
        cons="null 저장 불가. 인덱스 임의 접근은 지원하지 않아 중간 조회엔 부적합.",
        code=(
            "import java.util.*;\n"
            "\n"
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        // 스택처럼 사용\n"
            "        Deque<Integer> stack = new ArrayDeque<>();\n"
            "        stack.push(1); stack.push(2); stack.push(3);\n"
            "        System.out.println(\"스택 top: \" + stack.peek());\n"
            "        System.out.print(\"스택 pop 순서: \");\n"
            "        while (!stack.isEmpty()) System.out.print(stack.pop() + \" \");\n"
            "        System.out.println();\n"
            "\n"
            "        // 큐처럼 사용\n"
            "        Deque<String> queue = new ArrayDeque<>();\n"
            "        queue.offer(\"A\"); queue.offer(\"B\"); queue.offer(\"C\");\n"
            "        System.out.print(\"큐 poll 순서: \");\n"
            "        while (!queue.isEmpty()) System.out.print(queue.poll() + \" \");\n"
            "        System.out.println();\n"
            "\n"
            "        // 양끝 활용\n"
            "        Deque<Integer> dq = new ArrayDeque<>();\n"
            "        dq.offerFirst(10); dq.offerLast(20); dq.offerFirst(5);\n"
            "        System.out.println(\"앞: \" + dq.peekFirst() + \", 뒤: \" + dq.peekLast());\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-adv-05",
        lang="java", level="고급",
        title="제네릭 와일드카드 (? extends / ? super)",
        summary="PECS · 읽기는 extends, 쓰기는 super",
        explanation=(
            "[개요]\n"
            "제네릭(Generic)에서 List<Integer>는 정수만, List<Double>은 실수만 담는 리스트이다. 정수든 실수든 Number이면 모두 받는 메서드를 만들고자 할 때 문제가 발생한다.\n"
            "\n"
            "List<Number>를 매개변수로 선언해도 List<Integer>는 받을 수 없다. Integer가 Number를 상속하더라도 List<Integer>는 List<Number>의 하위 타입이 아니기 때문이다. 이는 Java 제네릭에 공변성이 없다는 규칙이다. 이 문제를 해결하는 것이 와일드카드 ? 이다.\n"
            "\n"
            "[핵심 개념]\n"
            "와일드카드에는 두 종류가 있다.\n"
            "1) ? extends T (상한 와일드카드)\n"
            "   • 'T 또는 T의 하위 클래스'를 의미한다.\n"
            "   • List<? extends Number>는 List<Integer>와 List<Double>을 모두 받는다.\n"
            "   • 원소를 꺼내면 Number 타입으로 받는다.\n"
            "   • 원소를 추가할 수 없다. 구체적 타입을 알 수 없기 때문이다.\n"
            "2) ? super T (하한 와일드카드)\n"
            "   • 'T 또는 T의 상위 클래스'를 의미한다.\n"
            "   • List<? super Integer>는 List<Integer>, List<Number>, List<Object>를 모두 받는다.\n"
            "   • T(Integer)를 안전하게 추가할 수 있다.\n"
            "   • 원소를 꺼내면 Object 타입으로만 받는다.\n"
            "\n"
            "이 규칙은 PECS로 요약된다.\n"
            "• Producer(데이터를 꺼내는 쪽) → Extends 사용\n"
            "• Consumer(데이터를 넣는 쪽) → Super 사용\n"
            "정리하면, ? extends Number는 Number 타입으로 꺼내 읽기만 가능하고, ? super Integer는 Integer 타입을 안전하게 넣을 수 있다.\n"
            "\n"
            "[코드 분석]\n"
            "  static double sum(List<? extends Number> list) {\n"
            "  → Number 또는 그 하위 타입 리스트(Integer, Double 등)를 모두 받는다. 이 메서드는 리스트에서 값을 꺼내기만 한다(Producer → Extends).\n"
            "\n"
            "  for (Number n : list) total += n.doubleValue();\n"
            "  → 꺼낸 각 원소를 Number로 받아 doubleValue() 메서드로 실수 값을 얻어 합산한다.\n"
            "\n"
            "  static void fill(List<? super Integer> list) {\n"
            "  → Integer 또는 그 상위 타입 리스트(Number, Object 등)를 받는다. 이 메서드는 리스트에 Integer 값을 넣기만 한다(Consumer → Super).\n"
            "\n"
            "  for (int i = 1; i <= 3; i++) list.add(i);\n"
            "  → Integer(int가 자동 박싱됨)를 안전하게 넣는다. super Integer 덕분에 Integer는 어떤 상위 타입 리스트에도 넣을 수 있다.\n"
            "\n"
            "  List<Number> bucket = new ArrayList<>();\n"
            "  fill(bucket);\n"
            "  → Number 리스트도 List<? super Integer>에 해당하므로 fill에 전달할 수 있다. Integer는 Number의 하위 타입이므로 Number 리스트에 Integer를 넣는 것은 안전하다.\n"
            "\n"
            "[유의 사항]\n"
            "• ? extends 리스트에는 원소를 추가할 수 없다(null 제외). 시도하면 컴파일 에러가 발생한다.\n"
            "• ? super 리스트에서 꺼내면 Object로만 받으므로, 원래 타입으로 쓰려면 형변환이 필요하다.\n"
            "• 초기에는 이해가 어려우나, 유틸 메서드를 여러 타입에 유연하게 적용할 때 필수적인 개념이다."
        ),
        usage="여러 타입을 받는 유연한 유틸 메서드 작성 시. 컬렉션 복사/합산 함수 등.",
        cons="? extends 컬렉션엔 (null 외) 값을 넣을 수 없고, ? super 에서 꺼내면 Object 로만 받는다.",
        code=(
            "import java.util.*;\n"
            "\n"
            "public class Main {\n"
            "    // 생산자: extends 로 읽어서 합산\n"
            "    static double sum(List<? extends Number> list) {\n"
            "        double total = 0;\n"
            "        for (Number n : list) total += n.doubleValue();\n"
            "        return total;\n"
            "    }\n"
            "    // 소비자: super 로 Integer 들을 채워 넣기\n"
            "    static void fill(List<? super Integer> list) {\n"
            "        for (int i = 1; i <= 3; i++) list.add(i);\n"
            "    }\n"
            "    public static void main(String[] args) {\n"
            "        List<Integer> ints = Arrays.asList(1, 2, 3);\n"
            "        List<Double> dbls = Arrays.asList(1.5, 2.5);\n"
            "        System.out.println(\"정수 합: \" + sum(ints));\n"
            "        System.out.println(\"실수 합: \" + sum(dbls));\n"
            "\n"
            "        List<Number> bucket = new ArrayList<>();\n"
            "        fill(bucket);\n"
            "        System.out.println(\"채워진 리스트: \" + bucket);\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-adv-06",
        lang="java", level="고급",
        title="비트 연산과 마스킹",
        summary="& | ^ ~ << >> · 비트마스크 집합",
        explanation=(
            "[개요]\n"
            "컴퓨터는 모든 숫자를 2진수(0과 1의 조합)로 저장한다. 예를 들어 숫자 12는 2진수로 1100이다. 비트 연산은 이 0과 1을 직접 다루는 연산이다. 전구 4개가 일렬로 있고 각 전구가 1(켜짐) 또는 0(꺼짐)을 나타낸다고 하면, 1100은 전구4·전구3 켜짐, 전구2·전구1 꺼짐 상태이다.\n"
            "\n"
            "[핵심 개념]\n"
            "기본 비트 연산 6가지는 다음과 같다.\n"
            "• & (AND)  : 둘 다 켜져 있어야 결과가 켜짐. 1&1=1, 나머지는 0\n"
            "• | (OR)   : 하나만 켜져 있어도 결과가 켜짐. 0|0=0, 나머지는 1\n"
            "• ^ (XOR)  : 서로 달라야 결과가 켜짐. 같으면 0, 다르면 1\n"
            "• ~ (NOT)  : 모든 비트를 반전. 0→1, 1→0\n"
            "• << (왼쪽 시프트) : 비트를 왼쪽으로 이동. n<<k 는 n * 2^k 와 같다\n"
            "• >> (오른쪽 시프트): 비트를 오른쪽으로 이동. n>>k 는 n / 2^k 와 같다\n"
            "\n"
            "비트마스크(Bitmask)는 원소들의 집합을 정수 하나로 표현하는 방법이다. 예를 들어 원소 {0, 1, 2, 3} 중 {1, 3번 원소}를 선택하면 이진수 1010 = 10 이다.\n"
            "• i번째 원소 추가:  set |= (1 << i)\n"
            "• i번째 원소 제거:  set &= ~(1 << i)\n"
            "• i번째 원소 확인:  (set >> i) & 1  (0이면 없음, 1이면 있음)\n"
            "• i번째 원소 토글:  set ^= (1 << i)\n"
            "\n"
            "코딩테스트에서의 활용 이유는 다음과 같다.\n"
            "• 부분집합 탐색: n개 원소의 모든 부분집합은 2^n개이며, 0부터 (1<<n)-1까지 for문 하나로 모두 순회할 수 있다.\n"
            "• 메모리 절약: 집합을 boolean 배열 대신 정수 하나로 표현하여 공간을 절약한다.\n"
            "• 속도: 비트 연산은 CPU가 매우 빠르게 처리한다.\n"
            "\n"
            "[코드 분석]\n"
            "  int a = 0b1100, b = 0b1010;\n"
            "  → 0b는 2진수 표기 접두사이다. a=12(2진수 1100), b=10(2진수 1010).\n"
            "\n"
            "  System.out.println(\"AND: \" + (a & b));   // 8\n"
            "  → 1100 & 1010 = 1000 = 8. 두 자리 모두 1인 곳만 1이 된다.\n"
            "\n"
            "  System.out.println(\"OR : \" + (a | b));   // 14\n"
            "  → 1100 | 1010 = 1110 = 14. 하나라도 1이면 결과가 1이다.\n"
            "\n"
            "  System.out.println(\"XOR: \" + (a ^ b));   // 6\n"
            "  → 1100 ^ 1010 = 0110 = 6. 서로 다른 자리(비트)만 1이 된다.\n"
            "\n"
            "  System.out.println(\"왼쪽 시프트 3<<2: \" + (3 << 2));  // 12\n"
            "  → 3(2진수 011)을 왼쪽으로 2칸 이동하면 01100 = 12. 2^2=4를 곱한 것과 같다.\n"
            "\n"
            "  int set = 0;\n"
            "  → 빈 집합을 표현하는 정수. 모든 비트가 0이다.\n"
            "\n"
            "  set |= (1 << 1);\n"
            "  → 1번 원소를 집합에 추가한다. 1<<1은 2(이진수 0010). 0 | 0010 = 0010. |=는 OR 연산 결과를 다시 set에 저장하는 복합 연산자이다.\n"
            "\n"
            "  set |= (1 << 3);\n"
            "  → 3번 원소를 추가한다. 1<<3은 8(이진수 1000). 0010 | 1000 = 1010.\n"
            "\n"
            "  (set >> 3) & 1\n"
            "  → set의 3번 비트가 켜져 있는지 확인한다. 오른쪽으로 3칸 이동하면 3번 비트가 맨 오른쪽(0번 위치)으로 오고, & 1로 맨 오른쪽 비트만 남긴다. 0이면 꺼짐, 1이면 켜짐이다.\n"
            "\n"
            "  set &= ~(1 << 1);\n"
            "  → 1번 원소를 집합에서 제거한다. ~(1<<1) = ~0010 = ...11111101. &= 로 1번 비트만 0으로 만들고, 나머지 비트는 1 AND 1 = 1이라 유지된다.\n"
            "\n"
            "  Integer.bitCount(0b10110)\n"
            "  → 이진수에서 켜진 비트(1)의 개수를 센다. 10110에는 1이 3개이므로 결과는 3이다.\n"
            "\n"
            "  for (int mask = 0; mask < (1 << n); mask++) cnt++;\n"
            "  → n=3이면 1<<3=8. mask는 0~7의 모든 값을 순회하며, 각 mask가 {1,2,3}의 하나의 부분집합을 나타낸다. 총 8가지(2^3)이다.\n"
            "\n"
            "[유의 사항]\n"
            "• 비트 연산의 우선순위가 낮으므로 괄호를 반드시 사용한다. (a & b) == 0 으로 작성해야 하며, a & b == 0 은 b==0을 먼저 계산하여 오답이 된다.\n"
            "• int는 32비트이므로 최대 32개 원소의 부분집합만 표현할 수 있다. 더 많으면 long(64비트)을 사용한다.\n"
            "• >> 는 부호를 유지하는 오른쪽 시프트, >>> 는 부호 비트도 0으로 채우는 시프트이다."
        ),
        usage="부분집합 완전탐색(2^n), 비트마스크 DP, 플래그 집합, 빠른 곱셈/나눗셈(시프트).",
        cons="가독성이 낮아 실수하기 쉽고, 음수/오버플로 처리에 주의해야 한다(부호 비트).",
        code=(
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        int a = 0b1100, b = 0b1010;  // 12, 10\n"
            "        System.out.println(\"AND: \" + (a & b));   // 8\n"
            "        System.out.println(\"OR : \" + (a | b));   // 14\n"
            "        System.out.println(\"XOR: \" + (a ^ b));   // 6\n"
            "        System.out.println(\"왼쪽 시프트 3<<2: \" + (3 << 2));  // 12\n"
            "\n"
            "        int set = 0;\n"
            "        set |= (1 << 1);   // 1번 원소 추가\n"
            "        set |= (1 << 3);   // 3번 원소 추가\n"
            "        System.out.println(\"3번 포함? \" + (((set >> 3) & 1) == 1));\n"
            "        set &= ~(1 << 1);  // 1번 원소 제거\n"
            "        System.out.println(\"1번 포함? \" + (((set >> 1) & 1) == 1));\n"
            "        System.out.println(\"켜진 비트 수: \" + Integer.bitCount(0b10110));  // 3\n"
            "\n"
            "        // {1,2,3} 의 모든 부분집합 개수 출력\n"
            "        int n = 3, cnt = 0;\n"
            "        for (int mask = 0; mask < (1 << n); mask++) cnt++;\n"
            "        System.out.println(\"부분집합 개수: \" + cnt);  // 8\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-adv-07",
        lang="java", level="고급",
        title="입출력 최적화 (BufferedReader + StringBuilder)",
        summary="대량 입력은 버퍼링 · 출력은 모아서 한 번에",
        explanation=(
            "[개요]\n"
            "코딩테스트에서 입력이 수십만 줄에 이르면 Scanner 사용 시 시간 초과(TLE)가 발생할 수 있다. Scanner는 입력에서 데이터를 읽을 때마다 즉시 처리하기 때문이다.\n"
            "\n"
            "BufferedReader는 버퍼에 데이터를 한꺼번에 쌓아 두고 프로그램이 요청할 때 버퍼에서 꺼내주므로 훨씬 빠르다. 짐을 트럭에 가득 실어 한 번에 배달하는 방식에 해당한다.\n"
            "\n"
            "출력도 동일하다.\n"
            "• System.out.println()을 100만 번 호출하면 100만 번의 IO 요청이 발생하여 느리다.\n"
            "• StringBuilder에 모아 System.out.print(sb)로 한 번에 출력하면 1번의 IO로 끝나 빠르다.\n"
            "\n"
            "[성능 비교]\n"
            "대형 입력(10만 줄 이상)에서의 대략적 처리 시간은 다음과 같다.\n"
            "• Scanner: 약 2~3초\n"
            "• BufferedReader: 약 0.1~0.2초\n"
            "시간 제한 1초짜리 문제에서 Scanner를 쓰면 TLE가 발생할 수 있다.\n"
            "\n"
            "[코드 분석]\n"
            "  String input = \"3\\n10 20\\n5 7\\n100 1\\n\";\n"
            "  → 실제 코딩테스트에서는 키보드(System.in)로 입력받는다. 이 예제에서는 시연을 위해 입력 데이터를 문자열로 직접 작성했다.\n"
            "\n"
            "  BufferedReader br = new BufferedReader(new StringReader(input));\n"
            "  → 실제 코딩테스트에서는 다음과 같이 작성한다.\n"
            "       BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\n"
            "     BufferedReader가 안쪽 Reader를 감싸 버퍼링을 추가하여 빠르게 읽는다. StringReader는 이 예제에서만 사용하는 시연용 Reader이다.\n"
            "\n"
            "  StringBuilder sb = new StringBuilder();\n"
            "  → 출력을 모아둘 빈 문자열 버퍼를 생성한다. 문자열 + 연산보다 효율적으로 문자열을 이어 붙일 수 있다.\n"
            "\n"
            "  int n = Integer.parseInt(br.readLine().trim());\n"
            "  → br.readLine()은 한 줄을 통째로 읽어 문자열로 반환한다. .trim()은 앞뒤 공백이나 줄바꿈 문자를 제거한다(없으면 파싱 오류 가능). Integer.parseInt()는 문자열 '3'을 정수 3으로 변환한다.\n"
            "\n"
            "  StringTokenizer st = new StringTokenizer(br.readLine());\n"
            "  → 한 줄을 읽어 공백 기준으로 분리하는 도구를 만든다. split(\" \")보다 빠른 이유는 split이 정규식 엔진을 사용하는 반면 StringTokenizer는 단순 문자 분리라 더 가볍기 때문이다.\n"
            "\n"
            "  int x = Integer.parseInt(st.nextToken());\n"
            "  → StringTokenizer에서 다음 토큰(공백 전까지)을 꺼내 정수로 변환한다. 첫 호출은 '10' → 10, 두 번째 호출은 '20' → 20.\n"
            "\n"
            "  sb.append(x + y).append('\\n');\n"
            "  → 결과를 즉시 출력하지 않고 sb에 모은다. append()는 기존 내용 뒤에 이어 붙이며, '\\n'은 줄바꿈 문자이다.\n"
            "\n"
            "  System.out.print(sb);\n"
            "  → 모든 계산이 끝난 뒤 단 한 번만 출력한다. println 대신 print를 사용하여 끝에 줄바꿈이 중복 추가되지 않게 한다.\n"
            "\n"
            "[유의 사항]\n"
            "• br.readLine()은 IOException을 발생시킬 수 있으므로 main 메서드 선언에 throws IOException을 반드시 추가한다.\n"
            "• readLine()은 더 읽을 내용이 없으면 null을 반환한다. null 체크 없이 Integer.parseInt(null)을 호출하면 NumberFormatException이 발생한다.\n"
            "• 입력이 적은 경우(수십 줄 이내)는 Scanner로도 충분하며, 10만 줄 이상의 대형 입력에서 성능 차이가 크다."
        ),
        usage="백준 등 입력이 수십만 줄인 문제. 출력 줄 수가 많을 때 특히 효과적.",
        cons="코드가 길어지고 IOException 처리가 필요하다. 입력이 작으면 체감 차이는 거의 없다.",
        code=(
            "import java.io.*;\n"
            "import java.util.*;\n"
            "\n"
            "public class Main {\n"
            "    public static void main(String[] args) throws IOException {\n"
            "        // 데모: System.in 대신 고정 문자열을 같은 방식으로 처리\n"
            "        String input = \"3\\n10 20\\n5 7\\n100 1\\n\";\n"
            "        BufferedReader br = new BufferedReader(new StringReader(input));\n"
            "        StringBuilder sb = new StringBuilder();\n"
            "\n"
            "        int n = Integer.parseInt(br.readLine().trim());\n"
            "        for (int i = 0; i < n; i++) {\n"
            "            StringTokenizer st = new StringTokenizer(br.readLine());\n"
            "            int x = Integer.parseInt(st.nextToken());\n"
            "            int y = Integer.parseInt(st.nextToken());\n"
            "            sb.append(x + y).append('\\n');   // 출력은 모아서\n"
            "        }\n"
            "        System.out.print(sb);   // 마지막에 한 번만 출력\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-adv-08",
        lang="java", level="고급",
        title="Optional과 제네릭 메서드",
        summary="null 안전 처리 · 타입 매개변수 <T> 메서드",
        explanation=(
            "[개요]\n"
            "이 주제는 null 안전 처리를 위한 Optional과, 타입을 매개변수로 받는 제네릭 메서드를 함께 다룬다.\n"
            "\n"
            "[Optional]\n"
            "Java에서 가장 흔한 오류 중 하나가 NullPointerException(NPE)이며, 값이 없는 변수(null)를 사용하려 할 때 발생한다.\n"
            "  String name = null;\n"
            "  System.out.println(name.toUpperCase());  // NullPointerException\n"
            "\n"
            "Optional<T>는 값이 있을 수도, 없을 수도 있는 상자이다. 상자를 열기 전에 내용물 존재 여부를 확인하도록 강제하여 NPE를 예방한다.\n"
            "• Optional.of(값)        → 값이 담긴 상자(확실히 있음, null이면 에러)\n"
            "• Optional.empty()       → 빈 상자(확실히 없음)\n"
            "• Optional.ofNullable(x) → x가 null이면 빈 상자, 아니면 x가 담긴 상자\n"
            "\n"
            "[제네릭 메서드]\n"
            "타입을 매개변수로 받는 메서드이다. 예를 들어 '리스트에서 최댓값 찾기'는 정수 리스트든 문자열 리스트든 로직이 동일하다. 제네릭 메서드를 쓰면 타입별로 따로 작성하지 않고 하나로 구현할 수 있다.\n"
            "\n"
            "[코드 분석]\n"
            "  static <T extends Comparable<T>> Optional<T> maxOf(List<T> list) {\n"
            "  → <T extends Comparable<T>>는 T가 어떤 타입이든 되지만 비교 가능(Comparable)해야 함을 의미한다. Integer, String 등은 이미 Comparable을 구현하므로 T가 될 수 있다. 반환 타입이 Optional<T>이므로 값이 없을 수 있음을 호출자에게 명시한다.\n"
            "\n"
            "  if (list.isEmpty()) return Optional.empty();\n"
            "  → 리스트가 비어 있으면 빈 Optional을 반환한다. null 대신 Optional.empty()를 반환하여 호출자가 null 체크를 하지 않아도 된다.\n"
            "\n"
            "  T best = list.get(0);\n"
            "  for (T x : list) if (x.compareTo(best) > 0) best = x;\n"
            "  → 첫 번째 원소를 최댓값으로 놓고, 하나씩 비교하여 더 큰 것이 나오면 교체한다. compareTo()가 양수를 반환하면 x가 best보다 크다는 의미이다.\n"
            "\n"
            "  return Optional.of(best);\n"
            "  → 최댓값이 존재함이 확실하므로 Optional.of()로 감싸 반환한다. of()는 null이 아닌 값만 담을 수 있으며, null이면 NullPointerException이 발생한다.\n"
            "\n"
            "  Optional<Integer> m = maxOf(nums);\n"
            "  System.out.println(\"최댓값: \" + m.orElse(-1));\n"
            "  → orElse(-1)은 Optional에 값이 있으면 그 값, 없으면 -1을 반환한다. NPE 위험 없이 안전하게 값을 꺼낸다.\n"
            "\n"
            "  maxOf(empty).orElse(\"없음\")\n"
            "  → 빈 리스트는 Optional.empty()를 반환하므로 orElse(\"없음\")이 적용된다.\n"
            "\n"
            "  Optional.ofNullable(name).map(String::toUpperCase).orElse(\"손님\")\n"
            "  → name이 null이면 ofNullable이 Optional.empty()를 만든다. .map(String::toUpperCase)는 값이 있으면 대문자로 변환하고 없으면 빈 Optional을 유지한다. .orElse(\"손님\")은 최종적으로 값이 없으면 '손님'을 반환한다. 즉 name = null → Optional.empty() → map 생략 → '손님' 반환으로, 기본값을 자동으로 돌려주는 안전장치이다.\n"
            "\n"
            "[유의 사항]\n"
            "• Optional을 필드(멤버 변수)나 매개변수로 사용하는 것은 권장되지 않으며, 반환 타입으로만 쓰는 것이 Java 공식 권장 방식이다.\n"
            "• m.get()으로 값을 꺼낼 수 있으나, 값이 없으면 NoSuchElementException이 발생한다. 반드시 isPresent() 확인 후 사용하거나 안전한 orElse / orElseGet을 사용한다.\n"
            "• Optional.of(null)은 NullPointerException을 발생시킨다. null 가능성이 있으면 반드시 Optional.ofNullable()을 사용한다."
        ),
        usage="조회 결과가 없을 수 있는 메서드의 반환형, 타입 무관한 공통 알고리즘(최댓값 등) 작성.",
        cons="Optional 을 필드/매개변수로 남발하면 오히려 복잡해진다. 반환형 용도로 쓰는 것이 권장된다.",
        code=(
            "import java.util.*;\n"
            "\n"
            "public class Main {\n"
            "    // 제네릭 메서드: 리스트의 최댓값을 Optional 로 반환\n"
            "    static <T extends Comparable<T>> Optional<T> maxOf(List<T> list) {\n"
            "        if (list.isEmpty()) return Optional.empty();\n"
            "        T best = list.get(0);\n"
            "        for (T x : list) if (x.compareTo(best) > 0) best = x;\n"
            "        return Optional.of(best);\n"
            "    }\n"
            "    public static void main(String[] args) {\n"
            "        List<Integer> nums = Arrays.asList(3, 9, 1, 7);\n"
            "        Optional<Integer> m = maxOf(nums);\n"
            "        System.out.println(\"최댓값: \" + m.orElse(-1));\n"
            "\n"
            "        List<String> empty = new ArrayList<>();\n"
            "        System.out.println(\"빈 리스트 최댓값: \" + maxOf(empty).orElse(\"없음\"));\n"
            "\n"
            "        String name = null;\n"
            "        String shown = Optional.ofNullable(name).map(String::toUpperCase).orElse(\"손님\");\n"
            "        System.out.println(\"이름: \" + shown);\n"
            "    }\n"
            "}\n"
        ),
    ),
]
