"""Java 기초 문법 (스타터 — 8개 항목)."""

from engine.models import Lesson

LESSONS = [

    Lesson(
        id="java-basic-01",
        lang="java", level="기초",
        title="변수와 기본 타입",
        summary="기본형(int/long/double/boolean/char) · 참조형 · 선언과 초기화",
        explanation=(
            "[개요]\n"
            "변수는 값을 저장하는, 이름이 부여된 메모리 공간이다. 자바에서 변수를 선언할 때는\n"
            "저장할 데이터의 종류, 즉 타입(type)을 반드시 명시해야 한다. 정수를 담는 변수인지\n"
            "실수를 담는 변수인지 사전에 정의하는 것이다.\n"
            "\n"
            "[타입 명시의 필요성]\n"
            "• 데이터는 종류마다 필요한 메모리 크기가 다르다. 예를 들어 정수는 4바이트, 실수는\n"
            "  8바이트를 사용한다. 타입을 먼저 정해야 시스템이 적절한 크기의 공간을 할당한다.\n"
            "• 파이썬처럼 타입을 자동 추론하는 언어와 달리, 자바는 개발자가 직접 타입을 명시한다.\n"
            "• 이를 통해 의도하지 않은 타입 오류를 실행 이전 컴파일 단계에서 검출할 수 있다.\n"
            "\n"
            "[기본 타입(primitive) — 값 자체를 저장]\n"
            "• int     : 정수 (약 -21억 ~ 21억). 가장 널리 사용되는 숫자 타입이다.\n"
            "• long    : 더 큰 정수 (약 -900경 ~ 900경). 큰 수 계산에 사용한다.\n"
            "• double  : 소수점 숫자 (3.14, 9.8 등). 정밀도가 높다.\n"
            "• float   : 소수점 숫자 (double보다 정밀도가 낮아 사용 빈도가 낮다).\n"
            "• boolean : 참/거짓 (true 또는 false 두 값만 가진다).\n"
            "• char    : 문자 하나 ('A', '가' 등 한 글자).\n"
            "\n"
            "[코드 분석]\n"
            "• int age = 25;\n"
            "  → age라는 정수(int) 변수를 선언하고 25로 초기화한다. '='는 수학의 '같다'가 아니라\n"
            "    오른쪽 값을 왼쪽 변수에 대입하라는 연산자이다. 나이는 소수점이 없고 21억을\n"
            "    넘지 않으므로 int가 적합하다.\n"
            "• long big = 10000000000L;\n"
            "  → 100억은 int의 최대 범위(약 21억)를 초과하므로 long을 사용한다. 숫자 뒤의 대문자\n"
            "    L은 해당 리터럴이 long 타입임을 지정하는 표시이다. L을 생략하면 컴파일러가 int로\n"
            "    해석하여 범위 초과 오류가 발생한다.\n"
            "• double pi = 3.14;\n"
            "  → 소수점이 있는 값을 저장할 때 double을 사용한다. 자바에서 소수 리터럴(예: 3.14)은\n"
            "    기본적으로 double로 취급된다. float으로 지정하려면 3.14f처럼 f를 붙인다.\n"
            "• boolean ok = true;\n"
            "  → 참/거짓 두 가지 상태만 저장하는 변수이다. 값은 true 또는 false만 가능하다.\n"
            "    게임 종료 여부, 로그인 여부 같은 상태 표현에 사용한다.\n"
            "• char grade = 'A';\n"
            "  → 문자 하나를 저장하며 반드시 작은따옴표('')로 감싼다. 큰따옴표(\"\")는 여러 글자인\n"
            "    String에 사용하고, 작은따옴표는 char에 사용한다.\n"
            "• String name = \"홍길동\";\n"
            "  → 여러 글자로 구성된 문자열이다. String은 기본 타입이 아니라 참조형이며, 실제\n"
            "    데이터가 위치한 메모리 주소를 저장한다. 즉 데이터 자체가 아니라 데이터의 위치를\n"
            "    참조한다.\n"
            "• System.out.println(\"이름: \" + name + \", 나이: \" + age);\n"
            "  → 화면에 내용을 출력한다. + 연산자로 문자열과 변수를 연결한다. System.out은 표준\n"
            "    출력 장치를, println은 출력 후 줄바꿈을 의미한다.\n"
            "• System.out.println(\"큰 수: \" + big);\n"
            "  → long 타입 변수 big의 값을 출력한다. 100억이 문자열로 연결되어 출력된다.\n"
            "• System.out.println(\"원주율: \" + pi + \", 합격: \" + ok + \", 학점: \" + grade);\n"
            "  → double, boolean, char 타입 변수를 함께 출력한다. 자바는 + 연산 시 모든 타입을\n"
            "    문자열로 자동 변환하여 연결한다.\n"
            "• int max = Integer.MAX_VALUE;\n"
            "  → Integer.MAX_VALUE는 int의 최댓값 2,147,483,647을 나타내는 상수이다. 이 값을\n"
            "    초과하는 수를 int에 저장하면 오버플로가 발생하여 잘못된 음수 값이 나온다. 큰 수\n"
            "    계산 시 long을 선택해야 하는 근거가 된다.\n"
            "\n"
            "[유의 사항]\n"
            "• 메서드 내부에서 선언한 지역 변수는 자동으로 초기화되지 않는다. 값을 대입하지 않고\n"
            "  사용하면 컴파일 오류가 발생한다. 선언과 동시에, 또는 사용 이전에 반드시 초기화한다.\n"
            "• 단, 클래스의 필드(멤버 변수)와 배열 원소는 자동으로 0, false, null로 초기화된다."
        ),
        usage="모든 데이터 저장의 출발점. 큰 수 계산엔 long, 정밀 소수엔 double 을 쓴다.",
        cons="기본형은 null 을 가질 수 없고, int 끼리 큰 수를 곱하면 오버플로가 날 수 있어 long 으로 승격해야 한다.",
        code=(
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        int age = 25;            // 정수\n"
            "        long big = 10000000000L; // int 범위를 넘는 큰 정수\n"
            "        double pi = 3.14;        // 실수(기본 double)\n"
            "        boolean ok = true;       // 참/거짓\n"
            "        char grade = 'A';        // 문자 하나\n"
            "        String name = \"홍길동\";   // 참조형 문자열\n"
            "\n"
            "        System.out.println(\"이름: \" + name + \", 나이: \" + age);\n"
            "        System.out.println(\"큰 수: \" + big);\n"
            "        System.out.println(\"원주율: \" + pi + \", 합격: \" + ok + \", 학점: \" + grade);\n"
            "\n"
            "        int max = Integer.MAX_VALUE; // int 가 담을 수 있는 최댓값\n"
            "        System.out.println(\"int 최댓값: \" + max);\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-basic-02",
        lang="java", level="기초",
        title="표준 출력과 형변환",
        summary="print/println/printf · 캐스팅 · parse · String.valueOf",
        explanation=(
            "[개요]\n"
            "표준 출력은 프로그램이 화면에 데이터를 표시하는 기능이다. 형변환은 데이터의 타입을\n"
            "다른 타입으로 바꾸는 작업으로, 문자열 '3'을 숫자 3으로 바꾸거나 실수 3.7을 정수 3으로\n"
            "바꾸는 것이 이에 해당한다.\n"
            "\n"
            "[형변환의 필요성]\n"
            "• 사용자 입력은 항상 문자열(String) 형태로 전달된다. 키보드로 '25'를 입력해도\n"
            "  프로그램은 문자 '2'와 '5'로 받는다.\n"
            "• 입력값으로 산술 연산을 수행하려면 숫자 타입으로 변환해야 한다.\n"
            "\n"
            "[출력 방법 3가지]\n"
            "• System.out.print(...)   : 줄바꿈 없이 출력하며 다음 출력이 이어진다.\n"
            "• System.out.println(...) : 출력 후 자동 줄바꿈한다. 가장 널리 사용한다.\n"
            "• System.out.printf(...)  : 형식을 지정하여 출력한다. %d는 정수, %f는 실수, %s는 문자열.\n"
            "\n"
            "[형변환 2가지 방식]\n"
            "1) 자동 형변환: 작은 타입에서 큰 타입으로는 자동 변환된다(int → double). 정보 손실이 없다.\n"
            "2) 강제 캐스팅: 큰 타입에서 작은 타입으로는 (타입명)으로 강제 변환한다(double → int).\n"
            "   이때 표현 범위를 벗어나는 부분(소수점 등)은 버려진다.\n"
            "\n"
            "[코드 분석]\n"
            "• int a = 7, b = 2;\n"
            "  → a에 7, b에 2를 한 줄에 선언·초기화한다. 쉼표로 같은 타입의 변수를 여러 개 한 번에\n"
            "    선언할 수 있다.\n"
            "• System.out.println(a + \" / \" + b + \" = \" + (a / b));\n"
            "  → 정수끼리 나누면 소수점이 버려진다. 7 / 2는 3.5가 아니라 3이며, 이를 정수 나눗셈이라\n"
            "    한다. (a / b)를 괄호로 감싼 것은 + 연산보다 먼저 계산하기 위함이다.\n"
            "• double d = (double) a / b;\n"
            "  → (double) a는 정수 a를 실수로 강제 변환한다. 결과적으로 7.0 / 2가 되어 3.5가 된다.\n"
            "    한쪽이 double이면 다른 쪽도 자동으로 double로 승격되므로 한쪽만 변환해도 된다.\n"
            "• System.out.printf(\"실수 나눗셈: %.2f%n\", d);\n"
            "  → printf는 형식을 지정하여 출력한다. %.2f는 소수점 둘째 자리까지 실수로 출력하라는\n"
            "    의미이며(3.50 형태), %n은 플랫폼에 맞는 줄바꿈 기호이다. 뒤의 d가 %f 자리에 대입된다.\n"
            "• double pi = 3.99; int cut = (int) pi;\n"
            "  → (int) pi는 실수를 정수로 강제 변환한다. 반올림이 아니라 소수점을 버리므로 3.99와\n"
            "    3.1 모두 3이 된다. 반올림이 필요하면 Math.round()를 사용한다.\n"
            "• int parsed = Integer.parseInt(\"123\");\n"
            "  → 문자열 \"123\"을 정수 123으로 변환한다. 입력에서 읽은 숫자 문자열을 연산 가능한\n"
            "    숫자로 바꿀 때 필수이다. 숫자가 아닌 문자가 포함되면 NumberFormatException이\n"
            "    발생한다.\n"
            "• String text = String.valueOf(456);\n"
            "  → 정수 456을 문자열 \"456\"으로 변환한다. \"\" + 456처럼 빈 문자열과 더하는 방법도 있다.\n"
            "• System.out.println(\"parse 결과: \" + (parsed + 1));\n"
            "  → parsed는 숫자 123이므로 +1 연산 결과는 124이다. 문자열 \"123\"에 +1을 하면 \"1231\"이\n"
            "    되는 것과 달리 실제 덧셈이 수행된다.\n"
            "• System.out.println(\"valueOf 결과 길이: \" + text.length());\n"
            "  → text는 문자열 \"456\"이므로 글자 수는 3이다. .length()는 문자열의 길이를 반환하는\n"
            "    메서드이다.\n"
            "\n"
            "[유의 사항]\n"
            "• double에서 int로의 캐스팅은 반올림이 아니라 버림이다. 3.9를 (int)로 변환하면 3이 된다.\n"
            "• parseInt는 숫자 문자열에만 사용해야 하며, 알파벳이 포함되면 예외가 발생한다.\n"
            "• printf의 %f는 기본으로 소수점 6자리까지 출력하므로, 자릿수는 %.2f처럼 명시한다."
        ),
        usage="결과를 보기 좋게 찍을 때 printf, 입력 문자열을 숫자로 바꿀 때 parseInt 가 핵심.",
        cons="double → int 캐스팅은 반올림이 아니라 '버림'이라 의도와 다를 수 있다. parseInt 는 숫자가 아니면 예외를 던진다.",
        code=(
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        int a = 7, b = 2;\n"
            "        System.out.println(a + \" / \" + b + \" = \" + (a / b));   // 정수 나눗셈 → 3\n"
            "\n"
            "        double d = (double) a / b;   // 한쪽을 double 로 캐스팅 → 3.5\n"
            "        System.out.printf(\"실수 나눗셈: %.2f%n\", d);\n"
            "\n"
            "        double pi = 3.99;\n"
            "        int cut = (int) pi;          // 캐스팅은 버림 → 3\n"
            "        System.out.println(\"버림: \" + cut);\n"
            "\n"
            "        int parsed = Integer.parseInt(\"123\");  // 문자열 → 정수\n"
            "        String text = String.valueOf(456);      // 정수 → 문자열\n"
            "        System.out.println(\"parse 결과: \" + (parsed + 1));\n"
            "        System.out.println(\"valueOf 결과 길이: \" + text.length());\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-basic-03",
        lang="java", level="기초",
        title="조건문과 반복문",
        summary="if/else if/else · switch · for/while · break/continue",
        explanation=(
            "[개요]\n"
            "조건문은 조건의 참/거짓에 따라 서로 다른 코드를 실행하는 제어 구조이다. 반복문은\n"
            "동일한 작업을 여러 번 반복 실행하는 제어 구조로, 1부터 100까지의 합산 같은 작업을\n"
            "간결하게 표현할 수 있게 한다.\n"
            "\n"
            "[조건문 2종류]\n"
            "• if/else if/else : 조건식(true/false)에 따라 분기한다.\n"
            "• switch          : 하나의 값이 정해진 여러 경우로 나뉠 때 간결하게 표현한다.\n"
            "\n"
            "[반복문 3종류]\n"
            "• for      : 반복 횟수가 정해진 경우에 사용한다.\n"
            "• while    : 조건이 참인 동안 계속 반복하는 경우에 사용한다.\n"
            "• do-while : 최소 1회 실행한 뒤 조건을 검사한다.\n"
            "\n"
            "[코드 분석]\n"
            "• int score = 82;\n"
            "  → 점수를 저장하는 정수 변수를 선언하고 82로 초기화한다.\n"
            "• if (score >= 90) System.out.println(\"A\");\n"
            "  → score가 90 이상이면 'A'를 출력한다. if 뒤 괄호의 조건이 true일 때만 해당 문장이\n"
            "    실행된다.\n"
            "• else if (score >= 80) System.out.println(\"B\");\n"
            "  → 앞 조건(90 이상)이 false일 때 이 조건을 검사한다. score가 80 이상 90 미만이면 'B'를\n"
            "    출력한다.\n"
            "• else System.out.println(\"C\");\n"
            "  → 앞의 모든 조건이 false일 때 실행된다. 즉 score가 80 미만이면 'C'를 출력한다.\n"
            "• int day = 3; switch (day) { ... }\n"
            "  → day의 값에 따라 여러 case 중 일치하는 것을 실행한다. 다수의 if-else if보다 간결하다.\n"
            "• case 1: System.out.println(\"월\"); break;\n"
            "  → day가 1이면 '월'을 출력하고 switch 문을 종료한다. break가 없으면 다음 case로 계속\n"
            "    실행되는 fall-through가 발생한다.\n"
            "• case 3: System.out.println(\"수\"); break;\n"
            "  → day가 3이므로 이 case가 실행되어 '수'를 출력하고 switch를 종료한다.\n"
            "• default: System.out.println(\"기타\");\n"
            "  → 어떤 case와도 일치하지 않을 때 실행된다. if-else의 else에 해당한다.\n"
            "• int sum = 0; for (int i = 1; i <= 10; i++) { ... }\n"
            "  → for문은 세 부분으로 구성된다.\n"
            "    - int i = 1 : 초기식. 최초 1회만 실행되며 i를 1로 설정한다.\n"
            "    - i <= 10   : 조건식. 매 반복 전에 검사하여 i가 10 이하이면 반복한다.\n"
            "    - i++       : 증감식. 매 반복 후에 i를 1씩 증가시킨다.\n"
            "    결과적으로 i가 1부터 10까지 총 10회 반복한다.\n"
            "• if (i % 2 == 1) continue;\n"
            "  → i를 2로 나눈 나머지가 1이면(홀수이면) 이번 반복의 남은 부분을 건너뛴다. continue는\n"
            "    현재 반복을 종료하고 다음 반복으로 넘어간다. 따라서 홀수(1,3,5,7,9)는 제외되고\n"
            "    짝수만 sum에 더해진다.\n"
            "• sum += i;\n"
            "  → sum = sum + i의 축약 표현이다. 짝수 i를 sum에 누적한다.\n"
            "• System.out.println(\"1~10 짝수합: \" + sum);\n"
            "  → 2+4+6+8+10 = 30이 출력된다.\n"
            "• int n = 5, fact = 1; while (n > 1) { fact *= n; n--; }\n"
            "  → n이 1보다 큰 동안 반복하며 5! = 5×4×3×2×1을 계산한다. fact *= n은 fact = fact * n의\n"
            "    축약이고, n--은 n을 1 감소시킨다. fact는 5→20→60→120, n은 4→3→2→1로 변화하며\n"
            "    n이 1이 되면 종료한다.\n"
            "• System.out.println(\"5! = \" + fact);\n"
            "  → 팩토리얼 결과 120을 출력한다.\n"
            "\n"
            "[유의 사항]\n"
            "• switch의 각 case 끝에 break를 누락하면 다음 case도 실행되는 fall-through 버그가 발생한다.\n"
            "• while 반복문은 종료 조건을 누락하면 무한 루프에 빠진다.\n"
            "• for문의 증감 방향이 잘못되면 반복이 한 번도 실행되지 않을 수 있다.\n"
            "  예: for (int i = 1; i >= 10; i++)는 1이 10 이상이 아니므로 즉시 종료된다."
        ),
        usage="모든 흐름 제어의 기본. 횟수가 정해지면 for, 조건이 끝을 정하면 while 을 택한다.",
        cons="switch 의 break 누락 버그가 흔하다. 무한 while 은 종료 조건을 빠뜨리면 멈추지 않는다.",
        code=(
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        int score = 82;\n"
            "        if (score >= 90) System.out.println(\"A\");\n"
            "        else if (score >= 80) System.out.println(\"B\");\n"
            "        else System.out.println(\"C\");\n"
            "\n"
            "        int day = 3;\n"
            "        switch (day) {\n"
            "            case 1: System.out.println(\"월\"); break;\n"
            "            case 3: System.out.println(\"수\"); break;\n"
            "            default: System.out.println(\"기타\");\n"
            "        }\n"
            "\n"
            "        int sum = 0;\n"
            "        for (int i = 1; i <= 10; i++) {\n"
            "            if (i % 2 == 1) continue; // 홀수는 건너뜀\n"
            "            sum += i;                 // 짝수만 더함\n"
            "        }\n"
            "        System.out.println(\"1~10 짝수합: \" + sum); // 30\n"
            "\n"
            "        int n = 5, fact = 1;\n"
            "        while (n > 1) { fact *= n; n--; }\n"
            "        System.out.println(\"5! = \" + fact);       // 120\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-basic-04",
        lang="java", level="기초",
        title="배열(1차원/2차원)",
        summary="고정 길이 · new · length · 향상된 for · 2차원 배열",
        explanation=(
            "[개요]\n"
            "배열은 같은 타입의 데이터를 연속된 공간에 나열하여 저장하는 자료 구조이다. 학생 30명의\n"
            "점수처럼 동종 데이터 다수를 개별 변수 대신 score[0]~score[29]와 같이 인덱스로 관리한다.\n"
            "\n"
            "[배열의 필요성과 특징]\n"
            "• 동종 데이터 다수를 반복문과 함께 처리할 때 효율적이다.\n"
            "• 메모리에 연속 배치되므로 접근 속도가 빠르다.\n"
            "• 생성 시 정한 크기는 이후 변경할 수 없다(고정 길이).\n"
            "• 인덱스는 항상 0부터 시작한다.\n"
            "• 범위를 벗어난 인덱스 접근 시 ArrayIndexOutOfBoundsException이 발생한다.\n"
            "• 숫자 배열은 0, boolean은 false, 참조형은 null로 자동 초기화된다.\n"
            "\n"
            "[코드 분석]\n"
            "• int[] a = {5, 2, 9, 1};\n"
            "  → int형 배열 a를 선언과 동시에 초기화한다. a[0]=5, a[1]=2, a[2]=9, a[3]=1인 4칸 배열이\n"
            "    생성된다. 값을 나중에 채울 경우 int[] a = new int[4]처럼 크기만 먼저 지정한다.\n"
            "• int sum = 0; for (int x : a) sum += x;\n"
            "  → 향상된 for문(enhanced for)이다. 배열 a의 원소를 순서대로 x에 대입하며 반복한다. x가\n"
            "    5, 2, 9, 1로 들어와 sum에 누적된다. 인덱스가 필요 없을 때 간결하다.\n"
            "• System.out.println(\"길이: \" + a.length + \", 합: \" + sum);\n"
            "  → a.length는 배열의 원소 개수를 반환하며 여기서는 4이다. .length는 메서드가 아니라\n"
            "    필드이므로 괄호가 없다. String의 .length()와 구분해야 한다.\n"
            "• Arrays.sort(a);\n"
            "  → 배열 a를 오름차순으로 정렬한다. {5, 2, 9, 1}이 {1, 2, 5, 9}가 된다. Arrays는 자바가\n"
            "    제공하는 배열 유틸리티 클래스이며, 사용하려면 import java.util.Arrays가 필요하다.\n"
            "• System.out.println(\"정렬: \" + Arrays.toString(a));\n"
            "  → 배열을 그대로 println하면 주소 형태의 값이 출력된다. Arrays.toString(a)를 사용하면\n"
            "    [1, 2, 5, 9]처럼 가독성 있게 출력된다.\n"
            "• int[][] grid = { {1, 2, 3}, {4, 5, 6} };\n"
            "  → 2차원 배열이며 배열의 배열로 볼 수 있다. 행과 열로 구성된 표 형태 데이터에 사용한다.\n"
            "    grid[0]은 첫 행 {1, 2, 3}, grid[1]은 둘째 행 {4, 5, 6}이며, grid[0][2]는 첫 행의 세\n"
            "    번째 원소인 3이다.\n"
            "• for (int i = 0; i < grid.length; i++) {\n"
            "  → grid.length는 행의 수로 여기서는 2이다. i가 0과 1일 때 각 행을 차례로 처리한다.\n"
            "• for (int j = 0; j < grid[i].length; j++) {\n"
            "  → grid[i].length는 i번째 행의 열 수로 여기서는 3이다. 안쪽 for문이 각 행의 원소를\n"
            "    처리한다.\n"
            "• System.out.print(grid[i][j] + \" \");\n"
            "  → grid[i][j]는 i행 j열의 값이다. print로 같은 줄에 이어서 출력한다.\n"
            "• System.out.println();\n"
            "  → 한 행 처리가 끝나면 줄바꿈만 수행한다.\n"
            "\n"
            "[유의 사항]\n"
            "• 배열 크기는 생성 후 변경할 수 없다. 크기가 가변적이면 ArrayList를 사용한다.\n"
            "• 존재하지 않는 인덱스(예: a[4]) 접근 시 ArrayIndexOutOfBoundsException이 발생한다.\n"
            "• 배열 출력은 println(a) 대신 Arrays.toString(a)를 사용한다.\n"
            "• 2차원 배열 출력은 Arrays.deepToString(grid)를 사용한다."
        ),
        usage="크기가 고정된 데이터, 격자/표 형태 데이터 처리에 적합. 인접 메모리라 접근이 빠르다.",
        cons="길이를 만든 뒤 바꿀 수 없다(크기 변경이 필요하면 ArrayList). 범위를 벗어나면 예외가 난다.",
        code=(
            "import java.util.Arrays;\n"
            "\n"
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        int[] a = {5, 2, 9, 1};\n"
            "        int sum = 0;\n"
            "        for (int x : a) sum += x;           // 향상된 for\n"
            "        System.out.println(\"길이: \" + a.length + \", 합: \" + sum);\n"
            "\n"
            "        Arrays.sort(a);                     // 오름차순 정렬\n"
            "        System.out.println(\"정렬: \" + Arrays.toString(a));\n"
            "\n"
            "        int[][] grid = {                    // 2x3 2차원 배열\n"
            "            {1, 2, 3},\n"
            "            {4, 5, 6}\n"
            "        };\n"
            "        for (int i = 0; i < grid.length; i++) {\n"
            "            for (int j = 0; j < grid[i].length; j++) {\n"
            "                System.out.print(grid[i][j] + \" \");\n"
            "            }\n"
            "            System.out.println();\n"
            "        }\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-basic-05",
        lang="java", level="기초",
        title="문자열(String)과 주요 메서드",
        summary="불변 · length/charAt/substring/indexOf · split · StringBuilder",
        explanation=(
            "[개요]\n"
            "String은 문자들의 연속으로 구성된 문자열 타입이다. 'H','e','l','l','o'가 이어지면\n"
            "\"Hello\"가 된다. 자바의 String은 한 번 생성되면 내용을 변경할 수 없는 불변(immutable)\n"
            "객체이다.\n"
            "\n"
            "[불변의 의미와 이유]\n"
            "• s = \"Hello\" 이후 s = s + \" World\"를 실행하면 기존 문자열이 수정되는 것이 아니라 새\n"
            "  \"Hello World\" 문자열이 생성되고 s가 이를 참조하게 된다. 기존 \"Hello\"는 폐기된다.\n"
            "  따라서 반복문 안에서 + 연산을 다수 수행하면 성능이 크게 저하된다.\n"
            "• 불변 설계로 여러 곳에서 같은 문자열을 공유해도 변경 위험이 없다.\n"
            "• 자바는 동일 문자열을 재사용(String Pool)하여 메모리를 절약한다.\n"
            "\n"
            "[코드 분석]\n"
            "• String s = \"Hello, Java\";\n"
            "  → 문자열 변수 s를 선언하고 \"Hello, Java\"로 초기화한다. 인덱스는 H=0, e=1, l=2, l=3,\n"
            "    o=4, ,=5, 공백=6, J=7, a=8, v=9, a=10이다.\n"
            "• System.out.println(\"길이: \" + s.length());\n"
            "  → .length()는 문자열의 총 글자 수를 반환하며 공백과 특수문자도 각 1로 센다.\n"
            "    \"Hello, Java\"는 11글자이다. 배열의 .length와 달리 문자열은 .length() 괄호가 있다.\n"
            "• System.out.println(\"첫 글자: \" + s.charAt(0));\n"
            "  → .charAt(i)는 i번째 위치의 문자 하나를 반환한다. 인덱스는 0부터 시작하므로 charAt(0)은\n"
            "    'H'이다. 반환 타입은 char이며 String과 + 연산 시 문자열로 변환된다.\n"
            "• System.out.println(\"부분: \" + s.substring(7));\n"
            "  → .substring(a)는 a번째 위치부터 끝까지의 부분 문자열을 반환한다. 인덱스 7은 'J'이므로\n"
            "    \"Java\"가 반환된다. .substring(a, b)는 a부터 b 직전(b 미포함)까지 반환한다.\n"
            "• System.out.println(\"위치: \" + s.indexOf(\"Java\"));\n"
            "  → .indexOf(문자열)은 해당 문자열이 처음 나타나는 인덱스를 반환한다. \"Java\"는 인덱스\n"
            "    7에서 시작하므로 7을 반환한다. 없으면 -1을 반환하며, 이를 존재 여부 확인에 활용한다.\n"
            "• System.out.println(\"대문자: \" + s.toUpperCase());\n"
            "  → 모든 글자를 대문자로 변환한 새 문자열을 반환한다. 원본 s는 불변이므로 변경되지\n"
            "    않는다. 소문자 변환은 .toLowerCase()를 사용한다.\n"
            "• String line = \"3 5 7\"; String[] tokens = line.split(\" \");\n"
            "  → .split(구분자)는 구분자를 기준으로 문자열을 분리하여 배열로 반환한다. 공백으로\n"
            "    분리하면 {\"3\", \"5\", \"7\"} 배열이 생성된다. 공백으로 구분된 숫자 입력 처리에 자주\n"
            "    사용하는 패턴이다.\n"
            "• int total = 0; for (String t : tokens) total += Integer.parseInt(t);\n"
            "  → 배열의 각 원소를 순서대로 정수로 변환하여 누적한다. parseInt가 없으면 \"3\"+\"5\"+\"7\" =\n"
            "    \"357\"처럼 문자열 연결이 되므로 반드시 변환해야 한다.\n"
            "• StringBuilder sb = new StringBuilder();\n"
            "  → 내용을 계속 추가할 수 있는 가변 문자열 버퍼를 생성한다. String과 달리 내용을 직접\n"
            "    수정할 수 있어 반복 연결 시 훨씬 빠르다.\n"
            "• for (int i = 1; i <= 3; i++) sb.append(i).append('-');\n"
            "  → .append(값)은 버퍼 끝에 값을 추가한다. i=1일 때 \"1-\", i=2일 때 \"1-2-\", i=3일 때\n"
            "    \"1-2-3-\"로 누적된다. .append()는 자기 자신을 반환하므로 연쇄 호출이 가능하다.\n"
            "• System.out.println(\"빌더: \" + sb.toString());\n"
            "  → StringBuilder를 String으로 변환하여 출력한다. 결과는 \"1-2-3-\"이다.\n"
            "• System.out.println(\"내용 비교: \" + \"abc\".equals(\"abc\"));\n"
            "  → 문자열 내용 비교는 반드시 .equals()를 사용한다. ==는 두 변수가 같은 객체를 참조하는지\n"
            "    (주소)를 비교하고, .equals()는 두 문자열의 내용이 같은지(값)를 비교한다. 문자열 비교에\n"
            "    ==를 사용하면 우연히 true가 나올 수 있으나 신뢰할 수 없다.\n"
            "\n"
            "[유의 사항]\n"
            "• 반복문 안에서 String + 연산을 다수 수행하면 성능이 저하되므로 StringBuilder를 사용한다.\n"
            "• 문자열 비교는 반드시 .equals()를 사용하고 ==는 사용하지 않는다.\n"
            "• substring(7, 11)처럼 범위를 초과하면 StringIndexOutOfBoundsException이 발생한다.\n"
            "• split(\".\")은 점(.)이 정규식 특수문자이므로 split(\"\\\\.\")처럼 이스케이프해야 한다."
        ),
        usage="텍스트 파싱·가공의 기본. 입력 한 줄을 split 으로 토큰화하는 패턴이 매우 흔하다.",
        cons="불변이라 루프 안 + 연결은 비효율적이다(StringBuilder 권장). 내용 비교는 반드시 equals 로 한다.",
        code=(
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        String s = \"Hello, Java\";\n"
            "        System.out.println(\"길이: \" + s.length());\n"
            "        System.out.println(\"첫 글자: \" + s.charAt(0));\n"
            "        System.out.println(\"부분: \" + s.substring(7));      // Java\n"
            "        System.out.println(\"위치: \" + s.indexOf(\"Java\"));   // 7\n"
            "        System.out.println(\"대문자: \" + s.toUpperCase());\n"
            "\n"
            "        String line = \"3 5 7\";\n"
            "        String[] tokens = line.split(\" \");\n"
            "        int total = 0;\n"
            "        for (String t : tokens) total += Integer.parseInt(t);\n"
            "        System.out.println(\"토큰 합: \" + total);             // 15\n"
            "\n"
            "        StringBuilder sb = new StringBuilder();\n"
            "        for (int i = 1; i <= 3; i++) sb.append(i).append('-');\n"
            "        System.out.println(\"빌더: \" + sb.toString());        // 1-2-3-\n"
            "\n"
            "        System.out.println(\"내용 비교: \" + \"abc\".equals(\"abc\"));\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-basic-06",
        lang="java", level="기초",
        title="입력(Scanner vs BufferedReader)",
        summary="Scanner의 편의성 · BufferedReader의 속도 · 개념 비교",
        explanation=(
            "[개요]\n"
            "입력은 프로그램이 사용자 또는 파일로부터 데이터를 받는 과정이다. 코딩테스트에서는\n"
            "대부분 키보드 대신 파일 리다이렉션으로 입력을 전달하며, 사전에 준비된 입력 파일을\n"
            "프로그램에 주입하여 자동으로 테스트한다.\n"
            "\n"
            "[표준 입력을 읽는 두 가지 방법]\n"
            "1) Scanner — 편의성이 높으나 속도가 느림\n"
            "   • nextInt()  : 정수 하나를 읽는다.\n"
            "   • next()     : 공백으로 구분된 단어 하나를 읽는다.\n"
            "   • nextLine() : 한 줄 전체를 읽는다.\n"
            "   • 코드가 짧고 직관적이나 내부 처리가 많아 느리다. 입력이 10만~100만 개를 초과하면\n"
            "     시간 초과(TLE)가 발생할 수 있다.\n"
            "2) BufferedReader — 속도가 빠르나 파싱이 필요\n"
            "   • readLine() : 한 줄 전체를 문자열로 읽는다.\n"
            "   • 숫자가 필요하면 Integer.parseInt()로 직접 변환한다.\n"
            "   • 공백으로 나뉜 여러 숫자는 StringTokenizer 또는 split으로 분리한다.\n"
            "   • 입력을 버퍼에 모아 한 번에 처리하므로 빠르며, 코딩테스트의 표준으로 사용된다.\n"
            "\n"
            "[선택 기준]\n"
            "• 입력이 1,000개 이하: Scanner 사용 가능\n"
            "• 입력이 10,000개 이상: BufferedReader 사용 권장\n"
            "\n"
            "[코드 분석]\n"
            "• String input = \"3\\n10 20 30\\n\";\n"
            "  → 실제 코딩테스트에서는 System.in으로 입력을 받지만, 본 예제는 테스트 편의를 위해\n"
            "    문자열로 입력을 모사한다. 첫 줄이 \"3\"(개수), 둘째 줄이 \"10 20 30\"(숫자 3개)인\n"
            "    입력이다.\n"
            "• BufferedReader br = new BufferedReader(new StringReader(input));\n"
            "  → BufferedReader 객체를 생성한다. 실제 코드에서는 new BufferedReader(new\n"
            "    InputStreamReader(System.in))으로 작성한다. 내부 버퍼로 입력을 큰 단위로 읽어\n"
            "    속도가 빠르다.\n"
            "• int n = Integer.parseInt(br.readLine().trim());\n"
            "  → br.readLine()으로 첫 줄 \"3\"을 읽는다. .trim()은 앞뒤 공백과 개행을 제거한다.\n"
            "    Integer.parseInt()로 문자열 \"3\"을 정수 3으로 변환한다. trim()은 줄 끝에 공백이 섞여\n"
            "    있어도 안전하게 파싱하기 위함이다.\n"
            "• StringTokenizer st = new StringTokenizer(br.readLine());\n"
            "  → 둘째 줄 \"10 20 30\"을 읽어 공백 기준으로 분리할 준비를 한다. StringTokenizer는\n"
            "    split보다 빠르게 토큰을 분리하며, st.nextToken() 호출 시마다 \"10\", \"20\", \"30\"을\n"
            "    순서대로 반환한다.\n"
            "• int sum = 0; for (int i = 0; i < n; i++) {\n"
            "  → n번(3회) 반복한다. i는 0부터 n-1까지 증가한다.\n"
            "• sum += Integer.parseInt(st.nextToken());\n"
            "  → st.nextToken()으로 토큰을 하나씩 꺼내 parseInt로 변환한 뒤 sum에 누적한다. 결과는\n"
            "    10 + 20 + 30 = 60이다.\n"
            "• System.out.println(\"개수: \" + n);\n"
            "  → n은 3이므로 '개수: 3'이 출력된다.\n"
            "• System.out.println(\"합계: \" + sum);\n"
            "  → 합계 60이 출력된다.\n"
            "• // 참고: 실제로는 new BufferedReader(new InputStreamReader(System.in)) 로 만든다.\n"
            "  → 실제 제출 코드에서는 System.in으로 연결하여 파일 또는 키보드 입력을 읽는다.\n"
            "\n"
            "[유의 사항]\n"
            "• Scanner에서 nextInt() 직후 nextLine()을 사용하면 빈 문자열을 읽는 문제가 있다.\n"
            "  nextInt()는 숫자만 읽고 개행(\\n)을 남기므로, nextLine()이 그 빈 줄을 읽어버린다.\n"
            "• BufferedReader 사용 시 메서드 시그니처에 throws IOException을 추가해야 한다.\n"
            "• StringTokenizer의 nextToken()을 남은 토큰이 없는 상태에서 호출하면 예외가 발생한다."
        ),
        usage="코딩테스트에서 입력이 크면 BufferedReader 가 사실상 표준. 작은 입력엔 Scanner 가 편하다.",
        cons="Scanner 는 느리고 nextInt 와 nextLine 을 섞으면 개행 처리 함정이 있다. BufferedReader 는 IOException 처리와 파싱을 직접 해야 한다.",
        code=(
            "import java.io.BufferedReader;\n"
            "import java.io.IOException;\n"
            "import java.io.StringReader;\n"
            "import java.util.StringTokenizer;\n"
            "\n"
            "public class Main {\n"
            "    public static void main(String[] args) throws IOException {\n"
            "        // 표준입력 대신 고정 문자열로 데모(System.in 을 흉내 냄)\n"
            "        String input = \"3\\n10 20 30\\n\";\n"
            "        BufferedReader br = new BufferedReader(new StringReader(input));\n"
            "\n"
            "        int n = Integer.parseInt(br.readLine().trim()); // 첫 줄: 개수\n"
            "        StringTokenizer st = new StringTokenizer(br.readLine());\n"
            "        int sum = 0;\n"
            "        for (int i = 0; i < n; i++) {\n"
            "            sum += Integer.parseInt(st.nextToken());    // 토큰별 정수 파싱\n"
            "        }\n"
            "        System.out.println(\"개수: \" + n);\n"
            "        System.out.println(\"합계: \" + sum);            // 60\n"
            "\n"
            "        // 참고: 실제로는 new BufferedReader(new InputStreamReader(System.in)) 로 만든다.\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-basic-07",
        lang="java", level="기초",
        title="연산자와 형 승격",
        summary="산술/비교/논리/대입 · 정수 나눗셈 · 자동 타입 승격 규칙",
        explanation=(
            "[개요]\n"
            "연산자는 값들 사이에서 계산을 수행하는 기호이다. 형 승격(Type Promotion)은 서로 다른\n"
            "타입 간 연산 시 작은 타입이 큰 타입으로 자동 변환되는 규칙으로, 정보가 손실되지 않는\n"
            "방향으로 변환된다. 예를 들어 int와 double을 더하면 int가 double로 자동 변환된다.\n"
            "\n"
            "[승격 순서 (작은 → 큰)]\n"
            "• byte/short/char → int → long → float → double\n"
            "\n"
            "[연산자 4종류]\n"
            "• 산술: +(더하기) -(빼기) *(곱하기) /(나누기) %(나머지)\n"
            "• 비교: ==(같음) !=(다름) <(작음) <=(이하) >(큼) >=(이상) — 결과는 true/false\n"
            "• 논리: &&(AND) ||(OR) !(NOT)\n"
            "• 대입: = 와 복합대입 += -= *= /= %=\n"
            "\n"
            "[코드 분석]\n"
            "• int a = 7, b = 3;\n"
            "  → 정수 a, b를 선언하고 각각 7, 3으로 초기화한다.\n"
            "• System.out.println(\"몫: \" + (a / b) + \", 나머지: \" + (a % b));\n"
            "  → a / b는 정수 나눗셈이므로 7 / 3 = 2(몫만, 나머지 버림)이다. a % b는 나머지 연산으로\n"
            "    7 % 3 = 1(7 = 3×2 + 1)이다. 나머지 연산은 짝수/홀수 판별, 순환 인덱스 계산 등에 자주\n"
            "    사용한다.\n"
            "• double avg = (a + b) / 2.0;\n"
            "  → 2.0은 double 리터럴이다. int + int는 int이지만 int / double은 double로 승격된다.\n"
            "    (7 + 3) = 10(int) / 2.0(double) = 5.0(double)이다. 만약 2(int)로 나눴다면 10 / 2 =\n"
            "    5(int)가 되었을 것이다.\n"
            "• System.out.println(\"평균: \" + avg);\n"
            "  → double이므로 소수점을 포함한 5.0이 출력된다.\n"
            "• boolean cond = (a > 5) && (b < 5);\n"
            "  → (a > 5)는 7 > 5로 true, (b < 5)는 3 < 5로 true이다. true && true는 true이다. &&는\n"
            "    단축 평가를 수행하여 왼쪽이 false이면 오른쪽을 검사하지 않는다.\n"
            "• System.out.println(\"논리 결과: \" + cond);\n"
            "  → true가 출력된다.\n"
            "• int big = 100000;\n"
            "  → 십만을 big에 저장한다. int 범위(약 21억)보다 작으므로 안전하다.\n"
            "• long overflowSafe = (long) big * big;\n"
            "  → big * big = 100000 * 100000 = 100억으로, int 최댓값(약 21억)을 초과한다. (long) big으로\n"
            "    먼저 변환하면 이후 big(int)도 long으로 자동 승격되어 long 범위(약 900경)에서 안전하게\n"
            "    계산된다.\n"
            "• System.out.println(\"안전한 곱: \" + overflowSafe);\n"
            "  → 10000000000(100억)이 올바르게 출력된다.\n"
            "• System.out.println(\"위험한 곱(int): \" + (big * big));\n"
            "  → int끼리 곱하면 100억이 int 범위를 초과하여 오버플로가 발생한다. 결과로 1410065408\n"
            "    같은 잘못된 값이 나온다. 오버플로는 예외 없이 조용히 틀린 값을 내므로 위험하다.\n"
            "\n"
            "[복합 대입 연산자]\n"
            "• a += 3  → a = a + 3\n"
            "• a -= 3  → a = a - 3\n"
            "• a *= 3  → a = a * 3\n"
            "• a /= 3  → a = a / 3\n"
            "• a %= 3  → a = a % 3\n"
            "\n"
            "[유의 사항]\n"
            "• 정수끼리 나누면 소수점이 버려진다. 평균이나 확률 계산 시 한쪽을 double로 변환한다.\n"
            "• int 오버플로는 예외 없이 틀린 값을 내므로 큰 수 계산 시 long을 사용한다.\n"
            "• ==는 기본형 값 비교에 사용한다. 참조형(String, 배열 등) 내용 비교는 .equals()로 한다.\n"
            "• &&와 ||는 단축 평가를 하므로 오른쪽 피연산자에 부작용(side effect)이 있으면 주의한다."
        ),
        usage="수치 계산 전반의 기본. 평균·확률처럼 소수가 필요한 계산에선 형 승격을 의식해야 한다.",
        cons="정수 나눗셈으로 소수점이 사라지는 실수가 잦다. int 오버플로는 예외 없이 조용히 틀린 값을 낸다.",
        code=(
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        int a = 7, b = 3;\n"
            "        System.out.println(\"몫: \" + (a / b) + \", 나머지: \" + (a % b)); // 2, 1\n"
            "\n"
            "        double avg = (a + b) / 2.0;   // 2.0 때문에 double 로 승격\n"
            "        System.out.println(\"평균: \" + avg);                 // 5.0\n"
            "\n"
            "        boolean cond = (a > 5) && (b < 5);\n"
            "        System.out.println(\"논리 결과: \" + cond);            // true\n"
            "\n"
            "        int big = 100000;\n"
            "        long overflowSafe = (long) big * big;  // long 으로 승격해 오버플로 방지\n"
            "        System.out.println(\"안전한 곱: \" + overflowSafe);   // 10000000000\n"
            "        System.out.println(\"위험한 곱(int): \" + (big * big)); // 오버플로된 값\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-basic-08",
        lang="java", level="기초",
        title="메서드 정의와 호출",
        summary="static 메서드 · 매개변수/반환값 · 오버로딩 · 중첩 클래스",
        explanation=(
            "[개요]\n"
            "메서드는 특정 기능을 수행하는 코드를 묶어 이름을 부여한 코드 블록이다. 예를 들어 두 수를\n"
            "더하는 기능을 add() 메서드로 정의하면, 필요할 때마다 add(3, 4)처럼 호출하여 재사용한다.\n"
            "\n"
            "[메서드의 필요성]\n"
            "1) 중복 제거: 동일 코드를 반복하지 않고 메서드 하나로 재사용한다.\n"
            "2) 가독성: 코드의 의도가 명확해진다. 긴 main을 여러 메서드로 분리하면 읽기 쉽다.\n"
            "3) 유지보수: 한 곳만 수정하면 호출하는 모든 곳에 반영된다.\n"
            "\n"
            "[메서드 형식]\n"
            "  [접근제어자] static 반환타입 메서드이름(매개변수1, 매개변수2, ...) {\n"
            "      // 실행할 코드\n"
            "      return 반환값; // 반환타입이 void면 return 생략 가능\n"
            "  }\n"
            "• static     : 객체 생성 없이 클래스 이름만으로(또는 같은 클래스 내에서 이름만으로) 호출한다.\n"
            "• 반환타입    : 메서드가 반환하는 값의 타입. 반환값이 없으면 void.\n"
            "• 매개변수    : 메서드가 받는 입력값.\n"
            "\n"
            "[오버로딩(Overloading)]\n"
            "• 같은 이름의 메서드를 매개변수의 개수나 타입만 다르게 하여 여러 개 정의하는 것이다.\n"
            "• 예: add(int a, int b)와 add(double a, double b)는 이름이 같지만 별개의 메서드이다.\n"
            "• 자바는 호출 시 매개변수 타입을 보고 실행할 메서드를 자동으로 선택한다.\n"
            "\n"
            "[코드 분석]\n"
            "• static int add(int a, int b) {\n"
            "  → add 메서드를 정의한다. int a, int b는 정수 두 개를 입력받음을 의미하고, static은 객체\n"
            "    없이 호출 가능하게 하며, 앞의 int는 정수를 반환함을 의미한다.\n"
            "• return a + b;\n"
            "  → a + b를 계산하여 호출한 곳으로 반환한다. return 뒤의 값이 최종 결과이며, return을\n"
            "    만나면 메서드 실행이 즉시 종료된다.\n"
            "• static double add(double a, double b) {\n"
            "  → 이름은 add로 같지만 매개변수 타입이 double인 오버로딩 버전이다. add(3, 4)는 정수\n"
            "    버전이, add(1.5, 2.5)는 실수 버전이 실행된다.\n"
            "• return a + b;\n"
            "  → double끼리 더한 결과를 반환한다.\n"
            "• static void greet(String name) {\n"
            "  → 반환타입이 void이므로 값을 반환하지 않고 출력이라는 부작용(side effect)만 수행한다.\n"
            "    void 메서드는 return을 생략하거나 return;으로 조기 종료할 수 있다.\n"
            "• System.out.println(name + \"님, 환영합니다.\");\n"
            "  → 매개변수 name을 이용해 인사 문구를 출력한다.\n"
            "• static class Calculator {\n"
            "  → Main 클래스 내부에 Calculator 클래스를 정의한다. 자바의 모든 코드는 클래스 안에\n"
            "    존재하며, 관련 기능을 논리적으로 묶을 때 중첩 클래스를 사용한다. static을 붙이면 외부\n"
            "    클래스 객체 없이 사용할 수 있다.\n"
            "• int multiply(int a, int b) { return a * b; }\n"
            "  → Calculator의 multiply 메서드이다. static이 없으므로 인스턴스 메서드이며, 객체를 먼저\n"
            "    생성해야 호출할 수 있다.\n"
            "• System.out.println(\"정수 합: \" + add(3, 4));\n"
            "  → add(3, 4) 호출로 정수 버전이 실행되어 7을 반환하며 '정수 합: 7'이 출력된다.\n"
            "• System.out.println(\"실수 합: \" + add(1.5, 2.5));\n"
            "  → add(1.5, 2.5)는 double 버전이 실행되어 결과 4.0을 반환한다.\n"
            "• greet(\"홍길동\");\n"
            "  → greet를 호출한다. void이므로 반환값을 받을 변수가 필요 없으며 '홍길동님,\n"
            "    환영합니다.'가 출력된다.\n"
            "• Calculator calc = new Calculator();\n"
            "  → Calculator의 객체(인스턴스)를 생성한다. 인스턴스 메서드를 사용하려면 객체를 먼저\n"
            "    생성해야 한다. new 키워드가 메모리에 객체 공간을 할당하고 calc가 그 주소를 참조한다.\n"
            "• System.out.println(\"곱: \" + calc.multiply(6, 7));\n"
            "  → calc 객체를 통해 multiply를 호출한다. 6 * 7 = 42가 반환되어 '곱: 42'가 출력된다.\n"
            "\n"
            "[유의 사항]\n"
            "• static 메서드 안에서 static이 아닌 인스턴스 메서드나 필드를 직접 사용하면 오류가 발생한다.\n"
            "• 매개변수 이름(a, b)은 메서드 내부에서만 유효한 지역 변수이며 외부에서 사용할 수 없다.\n"
            "• 오버로딩은 반환 타입만 다를 때는 불가능하며, 반드시 매개변수의 개수나 타입이 달라야 한다.\n"
            "• 메서드 이름은 보통 소문자로 시작하고 단어가 바뀌면 대문자로 이어쓴다(camelCase)."
        ),
        usage="중복 코드를 함수로 묶어 재사용한다. 오버로딩으로 비슷한 기능을 같은 이름으로 제공할 수 있다.",
        cons="static 메서드는 인스턴스 상태(필드)에 접근할 수 없다. 매개변수가 많아지면 호출 의미가 흐려진다.",
        code=(
            "public class Main {\n"
            "    // 정수 두 개의 합을 반환하는 static 메서드\n"
            "    static int add(int a, int b) {\n"
            "        return a + b;\n"
            "    }\n"
            "\n"
            "    // 오버로딩: 같은 이름, 매개변수 타입이 다름(실수 버전)\n"
            "    static double add(double a, double b) {\n"
            "        return a + b;\n"
            "    }\n"
            "\n"
            "    // 반환값이 없는 메서드(void)\n"
            "    static void greet(String name) {\n"
            "        System.out.println(name + \"님, 환영합니다.\");\n"
            "    }\n"
            "\n"
            "    // 여러 클래스가 필요하면 static 중첩 클래스로 정리\n"
            "    static class Calculator {\n"
            "        int multiply(int a, int b) { return a * b; }\n"
            "    }\n"
            "\n"
            "    public static void main(String[] args) {\n"
            "        System.out.println(\"정수 합: \" + add(3, 4));        // 7\n"
            "        System.out.println(\"실수 합: \" + add(1.5, 2.5));    // 4.0\n"
            "        greet(\"홍길동\");\n"
            "\n"
            "        Calculator calc = new Calculator();\n"
            "        System.out.println(\"곱: \" + calc.multiply(6, 7));   // 42\n"
            "    }\n"
            "}\n"
        ),
    ),
]
