"""Java 고급 문법 (스트림/람다/자료구조/제네릭/비트/입출력/Optional)."""

from engine.models import Lesson

LESSONS = [

    Lesson(
        id="java-adv-01",
        lang="java", level="고급",
        title="스트림 API (stream/map/filter/collect)",
        summary="컬렉션을 선언적으로 가공 · 중간연산/최종연산",
        explanation=(
            "━━ 스트림 API 이란? ━━\n"
            "\n"
            "숫자 리스트에서 짝수만 골라 제곱한 뒤 새 리스트를 만들고 싶다고 해요.\n"
            "기존 for 루프 방식:\n"
            "  List<Integer> result = new ArrayList<>();\n"
            "  for (int n : nums) {\n"
            "      if (n % 2 == 0) result.add(n * n);\n"
            "  }\n"
            "\n"
            "스트림 API를 쓰면 이렇게 한 줄로 줄어요:\n"
            "  nums.stream().filter(n -> n % 2 == 0).map(n -> n * n).collect(Collectors.toList())\n"
            "\n"
            "마치 공장 컨베이어 벨트처럼 생각하세요.\n"
            "원재료(리스트)가 들어와서 -> 필터(조건 미충족 제거) -> 가공(변환) -> 완제품 수집 순서로 흘러가요.\n"
            "\n"
            "두 가지 핵심 개념:\n"
            "  1) 중간 연산 (filter, map 등)\n"
            "     - 실제로 아무것도 실행하지 않아요.\n"
            "     - '나중에 이렇게 처리할 거야'라고 계획만 세워요.\n"
            "  2) 최종 연산 (collect, sum, count 등)\n"
            "     - 이 시점에 실제 계산이 한꺼번에 일어나요.\n"
            "이것을 '지연 평가(Lazy Evaluation)'라고 해요.\n"
            "불필요한 계산을 최소화해 효율적이에요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5, 6);\n"
            "  -> 1~6 숫자가 담긴 리스트를 만들어요.\n"
            "     Arrays.asList()는 배열을 리스트로 바꿔주는 편의 메서드예요.\n"
            "\n"
            "  List<Integer> result = nums.stream()\n"
            "  -> nums 리스트를 스트림(처리 흐름)으로 변환해요. 아직 아무것도 계산 안 해요.\n"
            "\n"
            "  .filter(n -> n % 2 == 0)\n"
            "  -> 각 숫자 n에 대해 '짝수인 것(2로 나눈 나머지가 0인 것)'만 통과시켜요.\n"
            "     n -> 조건 에서 -> 왼쪽이 입력(n), 오른쪽이 참/거짓 판단 식이에요.\n"
            "     2, 4, 6 만 남고 1, 3, 5는 버려져요.\n"
            "\n"
            "  .map(n -> n * n)\n"
            "  -> 남은 숫자(2, 4, 6)를 각각 제곱으로 변환해요. 2->4, 4->16, 6->36.\n"
            "     map은 '원소를 다른 값으로 1:1 변환'할 때 쓰는 연산이에요.\n"
            "\n"
            "  .collect(Collectors.toList());\n"
            "  -> 변환된 값들을 List로 모아요.\n"
            "     이 줄이 실행되는 순간 비로소 위의 filter와 map이 실제로 수행돼요!\n"
            "\n"
            "  int sum = nums.stream().filter(n -> n > 3).mapToInt(Integer::intValue).sum();\n"
            "  -> 3보다 큰 숫자(4, 5, 6)를 골라서 int 기본형 스트림으로 바꾼 뒤 합산해요.\n"
            "     mapToInt를 쓰는 이유: Integer 객체가 아닌 int 기본형으로 바꿔야 .sum()을 쓸 수 있어요.\n"
            "     Integer::intValue 는 Integer 객체에서 int 기본값을 꺼내는 메서드 참조예요.\n"
            "\n"
            "  .collect(Collectors.joining(\", \"))\n"
            "  -> 문자열들을 ', '로 연결해서 하나의 문자열로 만들어요.\n"
            "     [\"kim\", \"lee\", \"park\"] -> 대문자 변환 후 -> \"KIM, LEE, PARK\"\n"
            "\n"
            "주의할 점:\n"
            "  스트림은 한 번만 사용할 수 있어요.\n"
            "  같은 스트림에 최종 연산을 두 번 호출하면 IllegalStateException 이 발생해요.\n"
            "  단순 for 루프보다 느릴 수 있고, 오류 발생 위치를 디버깅하기 어려울 수 있어요.\n"
            "  코딩테스트보다는 실무 코드 가독성을 높이는 데 강점이 있어요."
        ),
        usage="데이터 필터링/변환/집계를 한 줄로 표현할 때. 코딩테스트보다는 실무 가독성에 강점.",
        cons="단순 반복엔 일반 for 보다 느리고 디버깅이 까다롭다. 대량 원소 박싱 비용도 주의.",
        code=(
            "import java.util.*;\n"
            "import java.util.stream.*;\n"
            "\n"
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        List<Integer> nums = Arrays.asList(1, 2, 3, 4, 5, 6);\n"
            "        // 짝수만 골라 제곱한 뒤 리스트로 수집\n"
            "        List<Integer> result = nums.stream()\n"
            "                .filter(n -> n % 2 == 0)\n"
            "                .map(n -> n * n)\n"
            "                .collect(Collectors.toList());\n"
            "        System.out.println(\"짝수의 제곱: \" + result);\n"
            "\n"
            "        int sum = nums.stream().filter(n -> n > 3).mapToInt(Integer::intValue).sum();\n"
            "        System.out.println(\"3 초과 합계: \" + sum);\n"
            "\n"
            "        List<String> names = Arrays.asList(\"kim\", \"lee\", \"park\");\n"
            "        String joined = names.stream().map(String::toUpperCase).collect(Collectors.joining(\", \"));\n"
            "        System.out.println(\"대문자 연결: \" + joined);\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-adv-02",
        lang="java", level="고급",
        title="람다와 함수형 인터페이스",
        summary="익명 함수 · Function/Predicate/Supplier/Consumer",
        explanation=(
            "━━ 람다와 함수형 인터페이스 이란? ━━\n"
            "\n"
            "람다(lambda)란 이름 없는 짧은 함수예요.\n"
            "예를 들어, 숫자를 받아서 제곱해 돌려주는 함수를 기존 방식으로 만들면:\n"
            "  int square(int x) { return x * x; }\n"
            "\n"
            "람다 방식으로 같은 내용을 한 줄로 쓸 수 있어요:\n"
            "  x -> x * x\n"
            "\n"
            "-> 왼쪽이 입력(x), 오른쪽이 반환할 계산식이에요. 완전히 동일한 의미예요!\n"
            "\n"
            "이 람다를 변수에 담으려면 '함수형 인터페이스'가 필요해요.\n"
            "함수형 인터페이스란 추상 메서드(구현 없는 메서드)가 정확히 하나뿐인 인터페이스예요.\n"
            "\n"
            "Java가 기본 제공하는 함수형 인터페이스 5가지:\n"
            "  - Function<T, R>       : T를 받아서 R로 반환. 예) 숫자 -> 제곱값\n"
            "  - Predicate<T>         : T를 받아서 true/false 반환. 예) 짝수인지 판단\n"
            "  - Supplier<T>          : 입력 없이 T를 만들어 공급. 예) '안녕하세요' 반환\n"
            "  - Consumer<T>          : T를 받아서 소비, 결과 없음. 예) 출력\n"
            "  - BiFunction<T, U, R>  : T와 U 두 개를 받아서 R 반환. 예) 두 수의 합\n"
            "\n"
            "왜 람다가 필요한가요?\n"
            "함수(동작) 자체를 변수에 담아서 다른 메서드에 인자로 전달할 수 있어요.\n"
            "예: 정렬 기준을 메서드에 넘기거나, 버튼 클릭 시 실행할 동작을 미리 지정할 때 써요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  Function<Integer, Integer> square = x -> x * x;\n"
            "  -> Integer를 받아서 Integer를 반환하는 함수를 만들어요.\n"
            "     x라는 입력을 제곱해서 반환해요. Function<입력타입, 반환타입> 형식이에요.\n"
            "\n"
            "  Predicate<Integer> isEven = x -> x % 2 == 0;\n"
            "  -> Integer를 받아서 true/false를 반환하는 함수예요.\n"
            "     짝수면 true, 홀수면 false를 반환해요.\n"
            "\n"
            "  Supplier<String> hello = () -> \"안녕하세요\";\n"
            "  -> 입력 없이(빈 괄호 ()) 항상 '안녕하세요' 문자열을 공급(반환)하는 함수예요.\n"
            "     마치 자판기처럼 버튼만 누르면(get() 호출) 값이 나와요.\n"
            "\n"
            "  Consumer<String> printer = s -> System.out.println(\"출력: \" + s);\n"
            "  -> 문자열을 받아서 출력하고, 반환값은 없는 함수예요. 값을 소비만 하는 거예요.\n"
            "\n"
            "  BiFunction<Integer, Integer, Integer> add = (a, b) -> a + b;\n"
            "  -> 정수 두 개(a, b)를 받아서 더한 결과를 반환해요.\n"
            "     BiFunction<첫번째입력, 두번째입력, 반환타입> 형식이에요.\n"
            "\n"
            "  square.apply(5)\n"
            "  -> Function 타입 함수를 실행할 때는 .apply(인자)를 써요. 5를 넣으면 25가 나와요.\n"
            "\n"
            "  isEven.test(4)\n"
            "  -> Predicate 타입 함수를 실행할 때는 .test(인자)를 써요. 4는 짝수니까 true.\n"
            "\n"
            "  hello.get()\n"
            "  -> Supplier 타입 함수를 실행할 때는 .get()을 써요. 인자 없이 호출해요.\n"
            "\n"
            "  printer.accept(hello.get())\n"
            "  -> Consumer 타입 함수를 실행할 때는 .accept(인자)를 써요.\n"
            "     hello.get()으로 '안녕하세요'를 얻은 뒤 printer에게 전달해요.\n"
            "\n"
            "  Function<Integer, Integer> squarePlusOne = square.andThen(x -> x + 1);\n"
            "  -> andThen은 함수 합성이에요. square를 먼저 실행한 결과에 x+1을 또 적용해요.\n"
            "     squarePlusOne.apply(4)는 4 제곱 = 16, 16 + 1 = 17을 반환해요.\n"
            "     마치 공장 라인을 두 단계 연결하는 것과 같아요.\n"
            "\n"
            "  String::toUpperCase 같은 '메서드 참조' 방식으로 람다를 더 짧게 쓸 수도 있어요.\n"
            "  s -> s.toUpperCase()  와  String::toUpperCase  는 완전히 같은 의미예요.\n"
            "\n"
            "주의할 점:\n"
            "  람다를 너무 많이 중첩하면 오히려 읽기 어려워져요.\n"
            "  복잡한 로직은 일반 메서드로 분리하고, 람다에서 그 메서드를 참조하는 게 좋아요.\n"
            "  람다 안에서 IOException 같은 체크 예외를 던지려면 try-catch로 감싸야 해서 번거로워요."
        ),
        usage="콜백, 정렬 비교자(Comparator), 스트림 연산 등에 동작 자체를 인자로 넘길 때.",
        cons="과하게 중첩하면 가독성이 떨어진다. 체크 예외를 던지는 코드는 람다에서 다루기 번거롭다.",
        code=(
            "import java.util.function.*;\n"
            "\n"
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        Function<Integer, Integer> square = x -> x * x;\n"
            "        Predicate<Integer> isEven = x -> x % 2 == 0;\n"
            "        Supplier<String> hello = () -> \"안녕하세요\";\n"
            "        Consumer<String> printer = s -> System.out.println(\"출력: \" + s);\n"
            "        BiFunction<Integer, Integer, Integer> add = (a, b) -> a + b;\n"
            "\n"
            "        System.out.println(\"제곱(5): \" + square.apply(5));\n"
            "        System.out.println(\"4는 짝수? \" + isEven.test(4));\n"
            "        System.out.println(\"공급: \" + hello.get());\n"
            "        printer.accept(hello.get());\n"
            "        System.out.println(\"덧셈(3,7): \" + add.apply(3, 7));\n"
            "\n"
            "        // 함수 합성: andThen\n"
            "        Function<Integer, Integer> squarePlusOne = square.andThen(x -> x + 1);\n"
            "        System.out.println(\"제곱+1(4): \" + squarePlusOne.apply(4));\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-adv-03",
        lang="java", level="고급",
        title="우선순위 큐 (PriorityQueue)",
        summary="힙 기반 · 최소/최대 힙 · O(log n) 삽입/삭제",
        explanation=(
            "━━ 우선순위 큐 (PriorityQueue) 이란? ━━\n"
            "\n"
            "병원 응급실을 떠올려 보세요.\n"
            "환자들이 줄을 서지만, 먼저 온 순서대로 치료받는 게 아니라\n"
            "'가장 위급한 환자'가 먼저 치료받아요.\n"
            "PriorityQueue(우선순위 큐)가 딱 이렇게 동작해요!\n"
            "\n"
            "기본적으로는 '숫자가 작은 것이 먼저'인 최소 힙(min-heap)이에요.\n"
            "최대 힙(숫자가 큰 것이 먼저)을 원하면 Collections.reverseOrder()를 넣어주면 돼요.\n"
            "\n"
            "내부 구조는 '이진 힙(Binary Heap)'이라는 트리 구조예요.\n"
            "그래서 원소를 넣을 때도, 꺼낼 때도 O(log n) 시간이 걸려요.\n"
            "원소가 1000개 있어도 꺼내는 데 비교를 약 10번만 하면 돼요. (log2(1000) 약 10)\n"
            "일반 리스트에서 최솟값을 찾으려면 1000번 비교해야 하는 것과 비교하면 엄청 빠르죠!\n"
            "\n"
            "왜 쓰나요?\n"
            "  - 다익스트라 알고리즘: '현재까지 거리가 가장 짧은 정점'을 빠르게 찾아야 할 때\n"
            "  - 상위 K개 값 추적: 수백만 개 데이터 중 가장 큰 K개만 뽑을 때\n"
            "  - 작업 스케줄링: 우선순위 높은 작업을 먼저 처리할 때\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  PriorityQueue<Integer> minHeap = new PriorityQueue<>();\n"
            "  -> 비어있는 최소 힙을 만들어요.\n"
            "     Integer(정수)를 담고, 기본값이 '작은 숫자 우선'이에요.\n"
            "\n"
            "  for (int v : new int[]{5, 1, 8, 3, 2}) minHeap.offer(v);\n"
            "  -> 5, 1, 8, 3, 2를 하나씩 힙에 넣어요.\n"
            "     offer(v)는 원소를 추가하는 메서드예요.\n"
            "     넣을 때마다 내부적으로 힙 구조가 자동으로 유지돼요.\n"
            "\n"
            "  while (!minHeap.isEmpty()) sb.append(minHeap.poll()).append(' ');\n"
            "  -> 힙이 빌 때까지 poll()로 원소를 하나씩 꺼내요.\n"
            "     꺼낼 때마다 항상 가장 작은 값이 먼저 나와요.\n"
            "     결과: 1 2 3 5 8 (오름차순으로 나와요!)\n"
            "\n"
            "  PriorityQueue<Integer> maxHeap = new PriorityQueue<>(Collections.reverseOrder());\n"
            "  -> Collections.reverseOrder()는 비교 순서를 역순으로 만들어요.\n"
            "     이걸 생성자에 넣으면 '가장 큰 값이 먼저'인 최대 힙이 돼요.\n"
            "\n"
            "  maxHeap.peek()\n"
            "  -> 가장 앞의 원소(현재 최댓값)를 확인만 하고 꺼내지는 않아요.\n"
            "     peek은 '들여다보기'만 해요. poll은 꺼내면서 제거해요.\n"
            "\n"
            "  PriorityQueue<String> byLen = new PriorityQueue<>(Comparator.comparingInt(String::length));\n"
            "  -> 문자열을 길이 기준으로 정렬하는 힙이에요.\n"
            "     Comparator.comparingInt(String::length): 각 문자열의 길이(int)를 기준으로 비교해요.\n"
            "     길이가 짧은 문자열이 먼저 나와요.\n"
            "\n"
            "주의할 점:\n"
            "  PriorityQueue를 for문으로 순회해도 정렬 순서대로 나오지 않아요!\n"
            "  반드시 poll()로 하나씩 꺼내야 우선순위 순서를 보장받아요.\n"
            "  중간 원소를 찾거나 수정하는 건 O(n)으로 느려요. 그 목적엔 적합하지 않아요.\n"
            "  같은 우선순위를 가진 원소들 사이의 순서는 보장되지 않아요."
        ),
        usage="다익스트라 최단경로, 작업 스케줄링, K번째 최소/최대 값 추적 등.",
        cons="중간 원소 임의 접근/검색은 O(n)으로 느리다. 정렬된 전체 순회는 보장되지 않는다.",
        code=(
            "import java.util.*;\n"
            "\n"
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        // 최소 힙\n"
            "        PriorityQueue<Integer> minHeap = new PriorityQueue<>();\n"
            "        for (int v : new int[]{5, 1, 8, 3, 2}) minHeap.offer(v);\n"
            "        StringBuilder sb = new StringBuilder(\"최소힙 꺼내기: \");\n"
            "        while (!minHeap.isEmpty()) sb.append(minHeap.poll()).append(' ');\n"
            "        System.out.println(sb.toString().trim());\n"
            "\n"
            "        // 최대 힙\n"
            "        PriorityQueue<Integer> maxHeap = new PriorityQueue<>(Collections.reverseOrder());\n"
            "        for (int v : new int[]{5, 1, 8, 3, 2}) maxHeap.offer(v);\n"
            "        System.out.println(\"최댓값(peek): \" + maxHeap.peek());\n"
            "\n"
            "        // 문자열 길이 기준 우선순위\n"
            "        PriorityQueue<String> byLen = new PriorityQueue<>(Comparator.comparingInt(String::length));\n"
            "        byLen.add(\"가나다\"); byLen.add(\"가\"); byLen.add(\"가나\");\n"
            "        System.out.println(\"가장 짧은 단어: \" + byLen.poll());\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-adv-04",
        lang="java", level="고급",
        title="ArrayDeque (스택/큐)",
        summary="양쪽 끝 O(1) · Stack/LinkedList 대체",
        explanation=(
            "━━ ArrayDeque (양방향 큐) 이란? ━━\n"
            "\n"
            "일반 큐(줄 서기)는 앞에서만 나가고 뒤에서만 들어와요.\n"
            "스택은 뒤에서만 넣고 뒤에서만 꺼내요.\n"
            "ArrayDeque(Deque = Double-Ended Queue, 양방향 큐)는\n"
            "앞뒤 양쪽 모두 넣고 꺼낼 수 있는 자료구조예요!\n"
            "\n"
            "이름이 복잡해 보이지만 실제로는 아주 단순해요:\n"
            "  - 스택으로 쓸 때: push(앞에 넣기) -> pop(앞에서 꺼내기)  -> 후입선출(LIFO)\n"
            "  - 큐로 쓸 때: offer(뒤에 넣기) -> poll(앞에서 꺼내기) -> 선입선출(FIFO)\n"
            "\n"
            "왜 옛날 Stack 클래스 대신 ArrayDeque를 써야 하나요?\n"
            "  옛날 Stack 클래스는 Vector(구식 클래스)를 상속받아서\n"
            "  불필요한 동기화(thread-safe) 처리가 있어 느려요.\n"
            "  ArrayDeque는 배열 기반이라 캐시 효율이 좋고,\n"
            "  앞뒤 삽입/삭제가 모두 O(1)이에요.\n"
            "  공식 Java 문서도 Stack 대신 ArrayDeque 사용을 권장해요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  Deque<Integer> stack = new ArrayDeque<>();\n"
            "  -> 정수를 담는 양방향 큐를 만들어요.\n"
            "     Deque는 인터페이스(설계도), ArrayDeque는 그 구현체(실제 도구)예요.\n"
            "     스택처럼 쓸 예정이라 변수명을 stack이라고 지었어요.\n"
            "\n"
            "  stack.push(1); stack.push(2); stack.push(3);\n"
            "  -> 1, 2, 3을 순서대로 스택에 넣어요.\n"
            "     push는 Deque의 앞쪽(First)에 원소를 추가해요.\n"
            "     실제 내부 순서: [3, 2, 1] (가장 마지막에 넣은 3이 앞에 있어요)\n"
            "\n"
            "  stack.peek()\n"
            "  -> 스택의 맨 위(가장 최근에 넣은 것)를 꺼내지 않고 보기만 해요. 결과: 3\n"
            "     peek은 '들여다보기'만 하고 원소를 제거하지 않아요.\n"
            "\n"
            "  stack.pop()\n"
            "  -> 스택 맨 위에서 원소를 꺼내고 제거해요. 3, 2, 1 순서로 나와요 (후입선출).\n"
            "     마지막에 넣은 것이 먼저 나와요. 접시 쌓기와 똑같아요!\n"
            "\n"
            "  Deque<String> queue = new ArrayDeque<>();\n"
            "  -> 문자열을 담는 양방향 큐를 만들어요. 이번엔 큐처럼 쓸 거예요.\n"
            "\n"
            "  queue.offer(\"A\"); queue.offer(\"B\"); queue.offer(\"C\");\n"
            "  -> A, B, C를 뒤쪽에 차례로 넣어요. 내부 순서: [A, B, C]\n"
            "     offer는 Deque의 뒤쪽(Last)에 원소를 추가해요.\n"
            "\n"
            "  queue.poll()\n"
            "  -> 앞쪽에서 원소를 꺼내고 제거해요. A, B, C 순서로 나와요 (선입선출).\n"
            "     줄 서기와 똑같아요. 먼저 온 사람이 먼저 나가요.\n"
            "\n"
            "  dq.offerFirst(10); dq.offerLast(20); dq.offerFirst(5);\n"
            "  -> offerFirst: 앞에 넣기. offerLast: 뒤에 넣기.\n"
            "     결과 순서: [5, 10, 20] (5를 앞에, 10이 중간, 20이 뒤에)\n"
            "\n"
            "  dq.peekFirst(), dq.peekLast()\n"
            "  -> 앞/뒤를 꺼내지 않고 보기만 해요.\n"
            "\n"
            "주의할 점:\n"
            "  null을 저장할 수 없어요! null을 offer하면 NullPointerException이 발생해요.\n"
            "  인덱스로 중간 원소에 접근할 수 없어요.\n"
            "  중간 원소 접근이 필요하면 ArrayList를 써야 해요.\n"
            "  push/pop은 앞쪽(First)을 쓰고, offer/poll은 뒤->앞을 써요. 이 차이를 기억하세요."
        ),
        usage="DFS의 명시적 스택, BFS 큐, 슬라이딩 윈도우 최댓값(단조 덱) 등.",
        cons="null 저장 불가. 인덱스 임의 접근은 지원하지 않아 중간 조회엔 부적합.",
        code=(
            "import java.util.*;\n"
            "\n"
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        // 스택처럼 사용\n"
            "        Deque<Integer> stack = new ArrayDeque<>();\n"
            "        stack.push(1); stack.push(2); stack.push(3);\n"
            "        System.out.println(\"스택 top: \" + stack.peek());\n"
            "        System.out.print(\"스택 pop 순서: \");\n"
            "        while (!stack.isEmpty()) System.out.print(stack.pop() + \" \");\n"
            "        System.out.println();\n"
            "\n"
            "        // 큐처럼 사용\n"
            "        Deque<String> queue = new ArrayDeque<>();\n"
            "        queue.offer(\"A\"); queue.offer(\"B\"); queue.offer(\"C\");\n"
            "        System.out.print(\"큐 poll 순서: \");\n"
            "        while (!queue.isEmpty()) System.out.print(queue.poll() + \" \");\n"
            "        System.out.println();\n"
            "\n"
            "        // 양끝 활용\n"
            "        Deque<Integer> dq = new ArrayDeque<>();\n"
            "        dq.offerFirst(10); dq.offerLast(20); dq.offerFirst(5);\n"
            "        System.out.println(\"앞: \" + dq.peekFirst() + \", 뒤: \" + dq.peekLast());\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-adv-05",
        lang="java", level="고급",
        title="제네릭 와일드카드 (? extends / ? super)",
        summary="PECS · 읽기는 extends, 쓰기는 super",
        explanation=(
            "━━ 제네릭 와일드카드 이란? ━━\n"
            "\n"
            "먼저 제네릭(Generic)을 복습해요.\n"
            "List<Integer>는 정수만 담는 리스트, List<Double>은 실수만 담는 리스트예요.\n"
            "그런데 '정수든 실수든 뭐든 Number면 다 받을 수 있는 메서드'를 만들고 싶다면?\n"
            "\n"
            "List<Number>를 매개변수로 선언해도 List<Integer>는 받을 수 없어요!\n"
            "Integer가 Number를 상속하더라도, List<Integer>는 List<Number>의 하위 타입이 아니에요.\n"
            "이게 Java 제네릭의 규칙이에요. (공변성이 없어요)\n"
            "\n"
            "이 문제를 해결하는 게 바로 와일드카드 ? 예요.\n"
            "\n"
            "두 가지 와일드카드:\n"
            "  1) ? extends T  (상한 와일드카드)\n"
            "     'T 또는 T의 하위 클래스'를 의미해요.\n"
            "     List<? extends Number>는 List<Integer>도, List<Double>도 받을 수 있어요.\n"
            "     원소를 꺼내면 Number 타입으로 받아요.\n"
            "     원소를 추가할 수는 없어요! (어떤 구체적 타입인지 알 수 없으니까요)\n"
            "\n"
            "  2) ? super T  (하한 와일드카드)\n"
            "     'T 또는 T의 상위 클래스'를 의미해요.\n"
            "     List<? super Integer>는 List<Integer>도, List<Number>도, List<Object>도 받아요.\n"
            "     T(Integer)를 안전하게 추가할 수 있어요.\n"
            "     원소를 꺼내면 Object 타입으로만 받아요.\n"
            "\n"
            "이 규칙을 PECS라고 외워요:\n"
            "  Producer(생산자, 데이터를 꺼내는 쪽) -> Extends 사용\n"
            "  Consumer(소비자, 데이터를 넣는 쪽)   -> Super 사용\n"
            "\n"
            "마트 진열대로 비유하면:\n"
            "  ? extends Number: 진열대에서 물건을 꺼내서 읽을 수만 있어요. Number 타입으로 꺼낼 수 있어요.\n"
            "  ? super Integer:  진열대에 물건을 넣을 수 있어요. Integer 타입을 안전하게 넣을 수 있어요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  static double sum(List<? extends Number> list) {\n"
            "  -> Number 또는 Number의 하위 타입 리스트(Integer, Double 등)를 모두 받아요.\n"
            "     이 메서드는 리스트에서 값을 꺼내기만 해요 (Producer -> Extends).\n"
            "\n"
            "  for (Number n : list) total += n.doubleValue();\n"
            "  -> 꺼낸 각 원소를 Number로 받아요.\n"
            "     Number의 doubleValue() 메서드로 실수 값을 얻어 합산해요.\n"
            "\n"
            "  static void fill(List<? super Integer> list) {\n"
            "  -> Integer 또는 Integer의 상위 타입 리스트(Number, Object 등)를 받아요.\n"
            "     이 메서드는 리스트에 Integer 값을 넣기만 해요 (Consumer -> Super).\n"
            "\n"
            "  for (int i = 1; i <= 3; i++) list.add(i);\n"
            "  -> Integer(int가 자동 박싱됨)를 안전하게 넣어요.\n"
            "     super Integer 덕분에 Integer는 어떤 상위 타입 리스트에도 넣을 수 있어요.\n"
            "\n"
            "  List<Number> bucket = new ArrayList<>();\n"
            "  fill(bucket);\n"
            "  -> Number 리스트도 List<? super Integer>에 해당하므로 fill에 전달할 수 있어요.\n"
            "     Integer는 Number의 하위 타입이니까 Number 리스트에 Integer를 넣는 건 안전해요.\n"
            "\n"
            "주의할 점:\n"
            "  ? extends 리스트에는 원소를 추가할 수 없어요 (null 제외). 시도하면 컴파일 에러.\n"
            "  ? super 리스트에서 꺼내면 Object로만 받아요. 원래 타입으로 쓰려면 형변환이 필요해요.\n"
            "  이 개념은 처음엔 어렵지만, 유틸 메서드를 여러 타입에 유연하게 만들 때 꼭 필요해요."
        ),
        usage="여러 타입을 받는 유연한 유틸 메서드 작성 시. 컬렉션 복사/합산 함수 등.",
        cons="? extends 컬렉션엔 (null 외) 값을 넣을 수 없고, ? super 에서 꺼내면 Object 로만 받는다.",
        code=(
            "import java.util.*;\n"
            "\n"
            "public class Main {\n"
            "    // 생산자: extends 로 읽어서 합산\n"
            "    static double sum(List<? extends Number> list) {\n"
            "        double total = 0;\n"
            "        for (Number n : list) total += n.doubleValue();\n"
            "        return total;\n"
            "    }\n"
            "    // 소비자: super 로 Integer 들을 채워 넣기\n"
            "    static void fill(List<? super Integer> list) {\n"
            "        for (int i = 1; i <= 3; i++) list.add(i);\n"
            "    }\n"
            "    public static void main(String[] args) {\n"
            "        List<Integer> ints = Arrays.asList(1, 2, 3);\n"
            "        List<Double> dbls = Arrays.asList(1.5, 2.5);\n"
            "        System.out.println(\"정수 합: \" + sum(ints));\n"
            "        System.out.println(\"실수 합: \" + sum(dbls));\n"
            "\n"
            "        List<Number> bucket = new ArrayList<>();\n"
            "        fill(bucket);\n"
            "        System.out.println(\"채워진 리스트: \" + bucket);\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-adv-06",
        lang="java", level="고급",
        title="비트 연산과 마스킹",
        summary="& | ^ ~ << >> · 비트마스크 집합",
        explanation=(
            "━━ 비트 연산과 마스킹 이란? ━━\n"
            "\n"
            "컴퓨터는 모든 숫자를 2진수(0과 1의 조합)로 저장해요.\n"
            "예를 들어 숫자 12는 2진수로 1100이에요.\n"
            "비트 연산은 이 0과 1들을 직접 다루는 연산이에요.\n"
            "\n"
            "전구 4개가 일렬로 있는 상황을 상상해 보세요.\n"
            "각 전구가 1(켜짐) 또는 0(꺼짐)을 나타내요.\n"
            "  1100 = 전구4:켜짐, 전구3:켜짐, 전구2:꺼짐, 전구1:꺼짐\n"
            "\n"
            "기본 비트 연산 6가지:\n"
            "  & (AND)  : 둘 다 켜져 있어야 결과가 켜짐. 1&1=1, 나머지는 0\n"
            "  | (OR)   : 하나만 켜져 있어도 결과가 켜짐. 0|0=0, 나머지는 1\n"
            "  ^ (XOR)  : 서로 달라야 결과가 켜짐. 같으면 0, 다르면 1\n"
            "  ~ (NOT)  : 모든 비트를 뒤집어요. 0->1, 1->0\n"
            "  << (왼쪽 시프트) : 비트를 왼쪽으로 밀기. n<<k 는 n * 2^k 와 같아요\n"
            "  >> (오른쪽 시프트): 비트를 오른쪽으로 밀기. n>>k 는 n / 2^k 와 같아요\n"
            "\n"
            "비트마스크(Bitmask)란?\n"
            "  원소들의 집합을 정수 하나로 표현하는 방법이에요.\n"
            "  예: 원소 3개 {0, 1, 2} 중 {1, 3번 원소} 선택 -> 이진수 1010 = 10\n"
            "  i번째 원소 추가:  set |= (1 << i)\n"
            "  i번째 원소 제거:  set &= ~(1 << i)\n"
            "  i번째 원소 확인:  (set >> i) & 1  (0이면 없음, 1이면 있음)\n"
            "  i번째 원소 토글:  set ^= (1 << i)\n"
            "\n"
            "코딩테스트에서 왜 쓰나요?\n"
            "  부분집합 탐색: n개 원소의 모든 부분집합은 2^n개인데,\n"
            "  0부터 (1<<n)-1까지 for문 하나로 모든 부분집합을 순회할 수 있어요.\n"
            "  메모리 절약: 집합을 boolean 배열 대신 정수 하나로 표현해서 공간을 절약해요.\n"
            "  속도: 비트 연산은 CPU가 매우 빠르게 처리해요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  int a = 0b1100, b = 0b1010;\n"
            "  -> 0b는 2진수 표기 접두사예요. a=12(2진수 1100), b=10(2진수 1010).\n"
            "\n"
            "  System.out.println(\"AND: \" + (a & b));   // 8\n"
            "  -> 1100 & 1010 = 1000 = 8. 두 자리 모두 1인 곳(왼쪽 두 번째)만 1이 돼요.\n"
            "\n"
            "  System.out.println(\"OR : \" + (a | b));   // 14\n"
            "  -> 1100 | 1010 = 1110 = 14. 하나라도 1이면 결과가 1이에요.\n"
            "\n"
            "  System.out.println(\"XOR: \" + (a ^ b));   // 6\n"
            "  -> 1100 ^ 1010 = 0110 = 6. 서로 다른 자리(비트)만 1이 돼요.\n"
            "\n"
            "  System.out.println(\"왼쪽 시프트 3<<2: \" + (3 << 2));  // 12\n"
            "  -> 3(2진수 011)을 왼쪽으로 2칸 밀면 01100 = 12. 2^2=4를 곱한 것과 같아요.\n"
            "\n"
            "  int set = 0;\n"
            "  -> 빈 집합을 표현하는 정수. 모든 비트가 0이에요.\n"
            "\n"
            "  set |= (1 << 1);\n"
            "  -> 1번 원소를 집합에 추가해요. 1<<1은 2(이진수 0010). 0 | 0010 = 0010.\n"
            "     |=는 OR 연산 결과를 다시 set에 저장하는 복합 연산자예요.\n"
            "\n"
            "  set |= (1 << 3);\n"
            "  -> 3번 원소를 추가해요. 1<<3은 8(이진수 1000). 0010 | 1000 = 1010.\n"
            "\n"
            "  (set >> 3) & 1\n"
            "  -> set의 3번 비트가 켜져 있는지 확인해요.\n"
            "     오른쪽으로 3칸 밀면 3번 비트가 맨 오른쪽(0번 위치)으로 와요.\n"
            "     & 1로 맨 오른쪽 비트만 남겨요. 0이면 꺼짐, 1이면 켜짐.\n"
            "\n"
            "  set &= ~(1 << 1);\n"
            "  -> 1번 원소를 집합에서 제거해요.\n"
            "     ~(1<<1) = ~0010 = ...11111101. &= 로 1번 비트만 0으로 만들어요.\n"
            "     나머지 비트는 1 AND 1 = 1이라서 그대로 유지돼요.\n"
            "\n"
            "  Integer.bitCount(0b10110)\n"
            "  -> 이진수에서 켜진 비트(1인 것)의 개수를 세요. 10110에는 1이 3개. 결과: 3.\n"
            "\n"
            "  for (int mask = 0; mask < (1 << n); mask++) cnt++;\n"
            "  -> n=3이면 1<<3=8. mask는 0~7 사이의 모든 값을 순회해요.\n"
            "     각 mask가 {1,2,3} 의 하나의 부분집합을 나타내요. 총 8가지(2^3)예요.\n"
            "\n"
            "주의할 점:\n"
            "  비트 연산의 우선순위가 낮아서 괄호를 꼭 써야 해요.\n"
            "  (a & b) == 0 이라고 써야 해요. a & b == 0 이라고 쓰면 b==0을 먼저 계산해서 틀려요!\n"
            "  int는 32비트라서 최대 32개 원소의 부분집합만 표현해요. 더 많으면 long(64비트)을 써요.\n"
            "  >> 는 부호를 유지하는 오른쪽 시프트, >>> 는 부호 비트도 0으로 채우는 시프트예요."
        ),
        usage="부분집합 완전탐색(2^n), 비트마스크 DP, 플래그 집합, 빠른 곱셈/나눗셈(시프트).",
        cons="가독성이 낮아 실수하기 쉽고, 음수/오버플로 처리에 주의해야 한다(부호 비트).",
        code=(
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        int a = 0b1100, b = 0b1010;  // 12, 10\n"
            "        System.out.println(\"AND: \" + (a & b));   // 8\n"
            "        System.out.println(\"OR : \" + (a | b));   // 14\n"
            "        System.out.println(\"XOR: \" + (a ^ b));   // 6\n"
            "        System.out.println(\"왼쪽 시프트 3<<2: \" + (3 << 2));  // 12\n"
            "\n"
            "        int set = 0;\n"
            "        set |= (1 << 1);   // 1번 원소 추가\n"
            "        set |= (1 << 3);   // 3번 원소 추가\n"
            "        System.out.println(\"3번 포함? \" + (((set >> 3) & 1) == 1));\n"
            "        set &= ~(1 << 1);  // 1번 원소 제거\n"
            "        System.out.println(\"1번 포함? \" + (((set >> 1) & 1) == 1));\n"
            "        System.out.println(\"켜진 비트 수: \" + Integer.bitCount(0b10110));  // 3\n"
            "\n"
            "        // {1,2,3} 의 모든 부분집합 개수 출력\n"
            "        int n = 3, cnt = 0;\n"
            "        for (int mask = 0; mask < (1 << n); mask++) cnt++;\n"
            "        System.out.println(\"부분집합 개수: \" + cnt);  // 8\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-adv-07",
        lang="java", level="고급",
        title="입출력 최적화 (BufferedReader + StringBuilder)",
        summary="대량 입력은 버퍼링 · 출력은 모아서 한 번에",
        explanation=(
            "━━ 입출력 최적화 이란? ━━\n"
            "\n"
            "코딩테스트에서 입력이 수십만 줄이면 Scanner를 쓸 때 시간 초과(TLE)가 나는 경우가 있어요.\n"
            "왜 Scanner가 느리냐고요?\n"
            "\n"
            "Scanner는 입력에서 데이터를 읽을 때마다 즉시 처리해요.\n"
            "이건 마치 택배를 하나씩 하나씩 손으로 직접 전달하는 것과 같아요.\n"
            "\n"
            "BufferedReader는 큰 박스(버퍼)에 데이터를 한꺼번에 쌓아 놓고,\n"
            "프로그램이 요청할 때 버퍼에서 꺼내줘요. 훨씬 빠르죠!\n"
            "트럭에 짐을 가득 실어서 한꺼번에 배달하는 것과 같아요.\n"
            "\n"
            "출력도 마찬가지예요:\n"
            "  System.out.println() 100만 번 -> 100만 번 IO 요청 -> 느림\n"
            "  StringBuilder에 모아서 System.out.print(sb) 한 번 -> 1번 IO -> 빠름\n"
            "\n"
            "얼마나 빠른가요?\n"
            "  대형 입력(10만 줄 이상)에서:\n"
            "  Scanner:       약 2~3초\n"
            "  BufferedReader: 약 0.1~0.2초\n"
            "  시간 제한 1초짜리 문제에서 Scanner를 쓰면 TLE가 날 수 있어요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  String input = \"3\\n10 20\\n5 7\\n100 1\\n\";\n"
            "  -> 실제 코딩테스트에서는 키보드(System.in)로 입력받아요.\n"
            "     이 예제에서는 시연용으로 입력 데이터를 문자열로 직접 작성했어요.\n"
            "\n"
            "  BufferedReader br = new BufferedReader(new StringReader(input));\n"
            "  -> 실제 코딩테스트에서는 이렇게 써요:\n"
            "       BufferedReader br = new BufferedReader(new InputStreamReader(System.in));\n"
            "     BufferedReader가 안쪽 Reader를 감싸서 버퍼링을 추가해 빠르게 읽어요.\n"
            "     StringReader는 이 예제에서만 쓰는 시연용 Reader예요.\n"
            "\n"
            "  StringBuilder sb = new StringBuilder();\n"
            "  -> 출력을 모아둘 빈 문자열 버퍼를 만들어요.\n"
            "     문자열 + 연산보다 훨씬 효율적으로 문자열을 이어 붙일 수 있어요.\n"
            "\n"
            "  int n = Integer.parseInt(br.readLine().trim());\n"
            "  -> br.readLine(): 한 줄을 통째로 읽어서 문자열로 반환해요.\n"
            "     .trim(): 앞뒤의 공백이나 줄바꿈 문자를 제거해요. 없으면 파싱 오류가 날 수 있어요.\n"
            "     Integer.parseInt(): 문자열 '3'을 정수 3으로 변환해요.\n"
            "\n"
            "  StringTokenizer st = new StringTokenizer(br.readLine());\n"
            "  -> 한 줄을 읽어서 공백 기준으로 분리하는 도구를 만들어요.\n"
            "     split(\" \")보다 빠른 이유: split은 정규식 엔진을 사용하지만\n"
            "     StringTokenizer는 단순 문자 분리라서 더 가볍고 빠라요.\n"
            "\n"
            "  int x = Integer.parseInt(st.nextToken());\n"
            "  -> StringTokenizer에서 다음 토큰(공백 전까지)을 꺼내서 정수로 변환해요.\n"
            "     첫 번째 호출: '10' -> 10, 두 번째 호출: '20' -> 20.\n"
            "\n"
            "  sb.append(x + y).append('\\n');\n"
            "  -> 결과를 즉시 출력하지 않고 sb에 모아요.\n"
            "     append()는 기존 내용 뒤에 이어 붙여요. '\\n'은 줄바꿈 문자예요.\n"
            "\n"
            "  System.out.print(sb);\n"
            "  -> 모든 계산이 끝난 뒤 단 한 번만 출력해요.\n"
            "     println 대신 print를 써서 끝에 줄바꿈이 중복으로 추가되지 않게 해요.\n"
            "\n"
            "주의할 점:\n"
            "  br.readLine()은 IOException을 발생시킬 수 있어서\n"
            "  main 메서드 선언에 throws IOException 을 반드시 추가해야 해요.\n"
            "  readLine()은 더 읽을 내용이 없으면 null을 반환해요.\n"
            "  null 체크 없이 Integer.parseInt(null)을 하면 NumberFormatException이 나요!\n"
            "  입력이 적은 경우(수십 줄 이내)는 Scanner로도 충분해요.\n"
            "  10만 줄 이상의 대형 입력에서 체감 차이가 크게 나요."
        ),
        usage="백준 등 입력이 수십만 줄인 문제. 출력 줄 수가 많을 때 특히 효과적.",
        cons="코드가 길어지고 IOException 처리가 필요하다. 입력이 작으면 체감 차이는 거의 없다.",
        code=(
            "import java.io.*;\n"
            "import java.util.*;\n"
            "\n"
            "public class Main {\n"
            "    public static void main(String[] args) throws IOException {\n"
            "        // 데모: System.in 대신 고정 문자열을 같은 방식으로 처리\n"
            "        String input = \"3\\n10 20\\n5 7\\n100 1\\n\";\n"
            "        BufferedReader br = new BufferedReader(new StringReader(input));\n"
            "        StringBuilder sb = new StringBuilder();\n"
            "\n"
            "        int n = Integer.parseInt(br.readLine().trim());\n"
            "        for (int i = 0; i < n; i++) {\n"
            "            StringTokenizer st = new StringTokenizer(br.readLine());\n"
            "            int x = Integer.parseInt(st.nextToken());\n"
            "            int y = Integer.parseInt(st.nextToken());\n"
            "            sb.append(x + y).append('\\n');   // 출력은 모아서\n"
            "        }\n"
            "        System.out.print(sb);   // 마지막에 한 번만 출력\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-adv-08",
        lang="java", level="고급",
        title="Optional과 제네릭 메서드",
        summary="null 안전 처리 · 타입 매개변수 <T> 메서드",
        explanation=(
            "━━ Optional과 제네릭 메서드 이란? ━━\n"
            "\n"
            "[Optional이란?]\n"
            "Java에서 가장 흔한 에러 중 하나가 NullPointerException(NPE)이에요.\n"
            "값이 없는 변수(null)를 사용하려 할 때 발생해요.\n"
            "\n"
            "예를 들어:\n"
            "  String name = null;\n"
            "  System.out.println(name.toUpperCase());  // NullPointerException!\n"
            "\n"
            "Optional<T>는 '값이 있을 수도 없을 수도 있는 상자'예요.\n"
            "상자를 열기 전에 내용물이 있는지 확인하게 만들어서 NPE를 예방해요.\n"
            "\n"
            "택배 상자에 비유하면:\n"
            "  Optional.of(값)        -> 값이 담긴 상자 (확실히 있음, null이면 에러)\n"
            "  Optional.empty()       -> 빈 상자 (확실히 없음)\n"
            "  Optional.ofNullable(x) -> x가 null이면 빈 상자, 아니면 x가 담긴 상자\n"
            "\n"
            "[제네릭 메서드란?]\n"
            "타입을 매개변수로 받는 메서드예요.\n"
            "예를 들어 '리스트에서 최댓값 찾기'는 정수 리스트든 문자열 리스트든 로직이 같아요.\n"
            "제네릭 메서드를 쓰면 타입별로 따로 만들지 않고 하나로 만들 수 있어요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  static <T extends Comparable<T>> Optional<T> maxOf(List<T> list) {\n"
            "  -> <T extends Comparable<T>>: T는 어떤 타입이든 되지만, 비교 가능(Comparable)해야 해요.\n"
            "     Integer, String 등은 이미 Comparable을 구현했으니 T가 될 수 있어요.\n"
            "     반환 타입이 Optional<T>라서 '값이 없을 수도 있다'는 걸 호출자에게 명시해요.\n"
            "\n"
            "  if (list.isEmpty()) return Optional.empty();\n"
            "  -> 리스트가 비어 있으면 빈 Optional(빈 상자)를 반환해요.\n"
            "     null 대신 Optional.empty()를 반환해서 호출자가 null 체크를 안 해도 돼요.\n"
            "\n"
            "  T best = list.get(0);\n"
            "  for (T x : list) if (x.compareTo(best) > 0) best = x;\n"
            "  -> 첫 번째 원소를 일단 최댓값으로 놓고, 하나씩 비교하면서 더 큰 것이 나오면 교체해요.\n"
            "     compareTo()가 양수를 반환하면 x가 best보다 크다는 뜻이에요.\n"
            "\n"
            "  return Optional.of(best);\n"
            "  -> 최댓값이 있다는 게 확실하니 Optional.of()로 감싸서 반환해요.\n"
            "     of()는 null이 아닌 값만 담을 수 있어요. null이면 NullPointerException 발생.\n"
            "\n"
            "  Optional<Integer> m = maxOf(nums);\n"
            "  System.out.println(\"최댓값: \" + m.orElse(-1));\n"
            "  -> orElse(-1): Optional에 값이 있으면 그 값, 없으면 -1을 반환해요.\n"
            "     NPE 걱정 없이 안전하게 값을 꺼낼 수 있어요.\n"
            "\n"
            "  maxOf(empty).orElse(\"없음\")\n"
            "  -> 빈 리스트는 Optional.empty()를 반환하므로 orElse(\"없음\")이 실행돼요.\n"
            "\n"
            "  Optional.ofNullable(name).map(String::toUpperCase).orElse(\"손님\")\n"
            "  -> name이 null이면 ofNullable이 Optional.empty()를 만들어요.\n"
            "     .map(String::toUpperCase): 값이 있으면 대문자로 변환해요. 없으면 그냥 빈 Optional 유지.\n"
            "     .orElse(\"손님\"): 최종적으로 값이 없으면 '손님'을 반환해요.\n"
            "     name = null -> Optional.empty() -> map 생략 -> '손님' 반환.\n"
            "     마치 기본값을 자동으로 돌려주는 안전장치예요.\n"
            "\n"
            "주의할 점:\n"
            "  Optional을 필드(멤버 변수)로 선언하거나 매개변수로 쓰는 건 권장하지 않아요.\n"
            "  반환 타입으로만 쓰는 게 Java 공식 권장 방식이에요.\n"
            "  m.get()으로 값을 꺼낼 수도 있지만, 값이 없으면 NoSuchElementException이 나요.\n"
            "  반드시 isPresent() 확인 후 쓰거나 안전한 orElse / orElseGet 을 사용하세요.\n"
            "  Optional.of(null)은 NullPointerException이에요!\n"
            "  null 가능성이 있으면 반드시 Optional.ofNullable()을 써야 해요."
        ),
        usage="조회 결과가 없을 수 있는 메서드의 반환형, 타입 무관한 공통 알고리즘(최댓값 등) 작성.",
        cons="Optional 을 필드/매개변수로 남발하면 오히려 복잡해진다. 반환형 용도로 쓰는 것이 권장된다.",
        code=(
            "import java.util.*;\n"
            "\n"
            "public class Main {\n"
            "    // 제네릭 메서드: 리스트의 최댓값을 Optional 로 반환\n"
            "    static <T extends Comparable<T>> Optional<T> maxOf(List<T> list) {\n"
            "        if (list.isEmpty()) return Optional.empty();\n"
            "        T best = list.get(0);\n"
            "        for (T x : list) if (x.compareTo(best) > 0) best = x;\n"
            "        return Optional.of(best);\n"
            "    }\n"
            "    public static void main(String[] args) {\n"
            "        List<Integer> nums = Arrays.asList(3, 9, 1, 7);\n"
            "        Optional<Integer> m = maxOf(nums);\n"
            "        System.out.println(\"최댓값: \" + m.orElse(-1));\n"
            "\n"
            "        List<String> empty = new ArrayList<>();\n"
            "        System.out.println(\"빈 리스트 최댓값: \" + maxOf(empty).orElse(\"없음\"));\n"
            "\n"
            "        String name = null;\n"
            "        String shown = Optional.ofNullable(name).map(String::toUpperCase).orElse(\"손님\");\n"
            "        System.out.println(\"이름: \" + shown);\n"
            "    }\n"
            "}\n"
        ),
    ),
]
