"""Java 기초 문법 (스타터 — 8개 항목)."""

from engine.models import Lesson

LESSONS = [

    Lesson(
        id="java-basic-01",
        lang="java", level="기초",
        title="변수와 기본 타입",
        summary="기본형(int/long/double/boolean/char) · 참조형 · 선언과 초기화",
        explanation=(
            "━━ 변수와 기본 타입 이란? ━━\n"
            "\n"
            "변수는 '이름 붙인 상자'라고 생각하면 쉬워요.\n"
            "마치 책상 위에 여러 서랍이 있고, 각 서랍에 '연필', '지우개', '자'처럼 이름표를 붙이는 것과 같아요.\n"
            "자바에서는 상자를 만들 때 반드시 '어떤 종류의 물건을 담을 상자인지' 먼저 알려줘야 해요.\n"
            "이것이 바로 '타입(type)'이에요. 정수를 담을 상자인지, 소수점 숫자를 담을 상자인지 미리 정하는 거죠.\n"
            "\n"
            "왜 타입을 미리 정해야 할까요?\n"
            "컴퓨터는 메모리(기억 공간)에 데이터를 저장하는데, 정수는 4바이트, 실수는 8바이트처럼\n"
            "종류마다 필요한 공간 크기가 달라요. 타입을 먼저 알아야 컴퓨터가 딱 맞는 크기의 공간을 준비해요.\n"
            "파이썬처럼 타입을 자동으로 알아내는 언어도 있지만, 자바는 개발자가 직접 명시해야 해요.\n"
            "이 덕분에 '의도하지 않은 타입 오류'를 실행 전에 미리 잡을 수 있어요.\n"
            "\n"
            "기본 타입(primitive) — 값 자체를 저장하는 상자들:\n"
            "  int     → 정수 상자 (약 -21억 ~ 21억). 가장 많이 쓰는 숫자 타입이에요\n"
            "  long    → 더 큰 정수 상자 (약 -900경 ~ 900경). 큰 수 계산 시 사용해요\n"
            "  double  → 소수점 숫자 상자 (3.14, 9.8 등). 정밀도가 높아요\n"
            "  float   → 소수점 숫자 상자 (정밀도가 double보다 낮아서 잘 안 써요)\n"
            "  boolean → 참/거짓 상자 (true 또는 false, 딱 두 가지만 들어가요)\n"
            "  char    → 문자 하나 상자 ('A', '가' 등 딱 한 글자)\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  int age = 25;\n"
            "  → 'age'라는 이름의 정수(int) 상자를 만들고 25를 넣어요.\n"
            "    '='는 수학의 '같다'가 아니라 '오른쪽 값을 왼쪽 상자에 넣어라'는 명령이에요.\n"
            "    왜 int냐면, 나이는 소수점이 없는 정수이고 21억을 넘지 않으니까요!\n"
            "\n"
            "  long big = 10000000000L;\n"
            "  → 100억은 int 상자(최대 약 21억)에 들어가지 않아요. 그래서 더 큰 long 상자를 씁니다.\n"
            "    숫자 뒤의 대문자 L은 '이 숫자는 long 타입이야'라고 알려주는 표시예요.\n"
            "    L을 빠뜨리면 자바가 int로 읽으려다 '숫자가 너무 크다'며 에러를 내요!\n"
            "\n"
            "  double pi = 3.14;\n"
            "  → 소수점이 있는 숫자를 담을 때 double을 써요.\n"
            "    자바에서 소수점이 있는 숫자(예: 3.14)는 자동으로 double로 취급해요.\n"
            "    float을 쓰려면 3.14f처럼 뒤에 f를 붙여야 해요.\n"
            "\n"
            "  boolean ok = true;\n"
            "  → 맞다/틀리다, 켜짐/꺼짐처럼 두 가지 상태만 담는 상자예요.\n"
            "    값은 true(참) 또는 false(거짓) 딱 두 가지만 가능해요.\n"
            "    게임에서 '게임오버인가?', 로그인 화면에서 '로그인 됐는가?' 같은 상태를 저장할 때 써요.\n"
            "\n"
            "  char grade = 'A';\n"
            "  → 문자 하나를 담는 상자예요. 반드시 작은따옴표('')로 감싸야 해요.\n"
            "    큰따옴표(\"\")는 여러 글자인 String(문자열)에 쓰고, 작은따옴표는 char(글자 하나)에 써요.\n"
            "    헷갈리면 이렇게 기억해요: char는 딱 한 글자, String은 여러 글자.\n"
            "\n"
            "  String name = \"홍길동\";\n"
            "  → 여러 글자가 모인 '문자열'이에요. String은 기본 타입이 아니라 '참조형'이에요.\n"
            "    참조형은 실제 데이터가 있는 메모리 주소를 저장해요.\n"
            "    비유하자면 '홍길동의 집 주소가 적힌 메모지'를 가지고 있는 것처럼,\n"
            "    데이터 그 자체가 아니라 데이터가 있는 위치를 기억하는 거예요.\n"
            "\n"
            "  System.out.println(\"이름: \" + name + \", 나이: \" + age);\n"
            "  → 화면에 내용을 출력해요. + 기호로 문자열과 변수를 이어 붙일 수 있어요.\n"
            "    System.out은 '화면 출력 장치', println은 '출력 후 줄바꿈'을 뜻해요.\n"
            "    print + line(줄)이 합쳐진 단어로 '한 줄 출력'이라고 이해하면 돼요.\n"
            "\n"
            "  System.out.println(\"큰 수: \" + big);\n"
            "  → long 타입 변수 big의 값을 화면에 출력해요.\n"
            "    100억이라는 큰 수가 문자열로 이어 붙여져서 출력돼요.\n"
            "\n"
            "  System.out.println(\"원주율: \" + pi + \", 합격: \" + ok + \", 학점: \" + grade);\n"
            "  → double, boolean, char 타입 변수들을 한꺼번에 출력해요.\n"
            "    자바는 + 연산 시 어떤 타입이든 문자열로 자동 변환해서 이어 붙여요.\n"
            "\n"
            "  int max = Integer.MAX_VALUE;\n"
            "  → Integer.MAX_VALUE는 int가 담을 수 있는 최댓값인 2,147,483,647이에요.\n"
            "    자바가 미리 만들어 둔 상수예요. 이보다 큰 수를 int에 담으면 '오버플로'가 발생해\n"
            "    엉뚱한 음수 값이 나와요. 이런 걸 미리 알고 있어야 큰 수 계산 시 long을 선택할 수 있어요.\n"
            "\n"
            "주의할 점:\n"
            "  메서드(함수) 안에서 만든 변수(지역 변수)는 자동으로 0이 되지 않아요!\n"
            "  int x; 처럼 선언만 하고 값을 안 넣은 채 사용하면 컴파일 에러가 나요.\n"
            "  항상 선언과 동시에, 또는 사용 전에 반드시 초기화(값을 넣는 것)를 해야 해요.\n"
            "  단, 클래스의 필드(멤버 변수)나 배열 원소는 자동으로 0, false, null로 초기화돼요."
        ),
        usage="모든 데이터 저장의 출발점. 큰 수 계산엔 long, 정밀 소수엔 double 을 쓴다.",
        cons="기본형은 null 을 가질 수 없고, int 끼리 큰 수를 곱하면 오버플로가 날 수 있어 long 으로 승격해야 한다.",
        code=(
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        int age = 25;            // 정수\n"
            "        long big = 10000000000L; // int 범위를 넘는 큰 정수\n"
            "        double pi = 3.14;        // 실수(기본 double)\n"
            "        boolean ok = true;       // 참/거짓\n"
            "        char grade = 'A';        // 문자 하나\n"
            "        String name = \"홍길동\";   // 참조형 문자열\n"
            "\n"
            "        System.out.println(\"이름: \" + name + \", 나이: \" + age);\n"
            "        System.out.println(\"큰 수: \" + big);\n"
            "        System.out.println(\"원주율: \" + pi + \", 합격: \" + ok + \", 학점: \" + grade);\n"
            "\n"
            "        int max = Integer.MAX_VALUE; // int 가 담을 수 있는 최댓값\n"
            "        System.out.println(\"int 최댓값: \" + max);\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-basic-02",
        lang="java", level="기초",
        title="표준 출력과 형변환",
        summary="print/println/printf · 캐스팅 · parse · String.valueOf",
        explanation=(
            "━━ 표준 출력과 형변환 이란? ━━\n"
            "\n"
            "표준 출력은 프로그램이 화면에 글자를 표시하는 기능이에요.\n"
            "형변환은 데이터의 종류(타입)를 바꾸는 거예요.\n"
            "예를 들어 '3'이라는 글자(문자열)를 숫자 3으로 바꾸거나,\n"
            "실수 3.7을 정수 3으로 바꾸는 것이 형변환이에요.\n"
            "\n"
            "왜 형변환이 필요할까요?\n"
            "사용자가 입력한 값은 항상 '문자열(String)' 형태로 들어와요.\n"
            "예를 들어 키보드로 '25'를 입력해도 프로그램은 문자 '2'와 '5'로 받아요.\n"
            "이 값으로 계산(더하기, 빼기 등)을 하려면 숫자 25로 변환해야 해요!\n"
            "\n"
            "출력 방법 3가지:\n"
            "  System.out.print(...)   → 줄바꿈 없이 출력. 다음 출력이 바로 이어져요\n"
            "  System.out.println(...) → 출력 후 자동 줄바꿈. 가장 많이 써요\n"
            "  System.out.printf(...) → 형식을 지정해서 출력. %d는 정수, %f는 실수, %s는 문자열\n"
            "\n"
            "형변환 2가지 방법:\n"
            "  1) 자동 형변환: 작은 타입 → 큰 타입은 자동으로 변환돼요 (int → double)\n"
            "     물이 작은 컵에서 큰 컵으로 넘어갈 때 다 담기듯, 정보 손실이 없어요\n"
            "  2) 강제 캐스팅: 큰 타입 → 작은 타입은 (타입명)으로 강제 변환해요 (double → int)\n"
            "     큰 컵의 물을 작은 컵에 따를 때 넘치는 부분(소수점)이 버려져요\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  int a = 7, b = 2;\n"
            "  → a에 7, b에 2를 한 줄에 동시에 선언하고 초기화해요.\n"
            "    쉼표(,)로 같은 타입의 변수를 여러 개 한 번에 선언할 수 있어요.\n"
            "\n"
            "  System.out.println(a + \" / \" + b + \" = \" + (a / b));\n"
            "  → a/b의 결과를 출력하는데, 정수끼리 나누면 소수점이 버려져요.\n"
            "    7 / 2는 3.5가 아니라 3이 나와요! 이게 '정수 나눗셈'이에요.\n"
            "    (a / b)를 괄호로 감싼 건 + 연산보다 먼저 계산하게 하기 위해서예요.\n"
            "\n"
            "  double d = (double) a / b;\n"
            "  → (double) a는 정수 a를 실수로 강제 변환해요.\n"
            "    그러면 7.0 / 2가 되어 결과가 3.5가 돼요.\n"
            "    왜 한쪽만 바꿔도 될까요? 한쪽이 double이면 다른 쪽도 자동으로 double로 승격되거든요!\n"
            "\n"
            "  System.out.printf(\"실수 나눗셈: %.2f%n\", d);\n"
            "  → printf는 형식을 지정해서 출력해요.\n"
            "    %.2f는 '소수점 2자리까지 실수로 출력해'라는 뜻이에요 (3.50 형태)\n"
            "    %n은 줄바꿈 기호예요 (\\n과 같은데 플랫폼에 맞는 줄바꿈을 써줘요)\n"
            "    맨 뒤의 d는 출력할 값이에요. %f 자리에 d 값이 들어가요.\n"
            "\n"
            "  double pi = 3.99;\n"
            "  int cut = (int) pi;\n"
            "  → (int) pi는 실수 pi를 강제로 정수로 변환해요.\n"
            "    중요: 반올림이 아니라 소수점을 그냥 버려요!\n"
            "    3.99도 3.1도 모두 3이 돼요. 반올림하려면 Math.round()를 써야 해요.\n"
            "\n"
            "  int parsed = Integer.parseInt(\"123\");\n"
            "  → 문자열 \"123\"을 정수 123으로 변환해요.\n"
            "    입력에서 읽은 숫자 문자열을 실제로 계산할 수 있는 숫자로 바꿀 때 필수예요.\n"
            "    '숫자가 아닌 문자'가 들어오면 NumberFormatException 에러가 나요. (예: \"abc\")\n"
            "\n"
            "  String text = String.valueOf(456);\n"
            "  → 정수 456을 문자열 \"456\"으로 변환해요.\n"
            "    숫자를 문자열로 바꾸는 다른 방법은 \"\" + 456처럼 빈 문자열과 더하는 거예요.\n"
            "\n"
            "  System.out.println(\"parse 결과: \" + (parsed + 1));\n"
            "  → parsed는 이제 진짜 숫자 123이므로 +1을 하면 124가 돼요.\n"
            "    문자열 \"123\"에 +1을 하면 \"1231\"이 되는 것과 달리 실제 덧셈이 이루어져요.\n"
            "\n"
            "  System.out.println(\"valueOf 결과 길이: \" + text.length());\n"
            "  → text는 문자열 \"456\"이므로 글자 수는 3이에요.\n"
            "    .length()는 문자열이 몇 글자인지 알려주는 메서드예요.\n"
            "\n"
            "주의할 점:\n"
            "  double → int 캐스팅은 반올림이 아니라 '버림'이에요!\n"
            "  3.9를 (int)로 변환하면 4가 아니라 3이 돼요.\n"
            "  parseInt는 숫자 문자열에만 써야 해요. 알파벳이 들어오면 에러가 나요.\n"
            "  printf의 %f는 기본으로 소수점 6자리까지 출력하니, 자릿수 조절은 %.2f처럼 명시해요."
        ),
        usage="결과를 보기 좋게 찍을 때 printf, 입력 문자열을 숫자로 바꿀 때 parseInt 가 핵심.",
        cons="double → int 캐스팅은 반올림이 아니라 '버림'이라 의도와 다를 수 있다. parseInt 는 숫자가 아니면 예외를 던진다.",
        code=(
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        int a = 7, b = 2;\n"
            "        System.out.println(a + \" / \" + b + \" = \" + (a / b));   // 정수 나눗셈 → 3\n"
            "\n"
            "        double d = (double) a / b;   // 한쪽을 double 로 캐스팅 → 3.5\n"
            "        System.out.printf(\"실수 나눗셈: %.2f%n\", d);\n"
            "\n"
            "        double pi = 3.99;\n"
            "        int cut = (int) pi;          // 캐스팅은 버림 → 3\n"
            "        System.out.println(\"버림: \" + cut);\n"
            "\n"
            "        int parsed = Integer.parseInt(\"123\");  // 문자열 → 정수\n"
            "        String text = String.valueOf(456);      // 정수 → 문자열\n"
            "        System.out.println(\"parse 결과: \" + (parsed + 1));\n"
            "        System.out.println(\"valueOf 결과 길이: \" + text.length());\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-basic-03",
        lang="java", level="기초",
        title="조건문과 반복문",
        summary="if/else if/else · switch · for/while · break/continue",
        explanation=(
            "━━ 조건문과 반복문 이란? ━━\n"
            "\n"
            "조건문은 '상황에 따라 다른 행동을 하는' 기능이에요.\n"
            "마치 신호등처럼, 초록불이면 가고 빨간불이면 멈추는 것처럼요.\n"
            "\n"
            "반복문은 '같은 작업을 여러 번 반복하는' 기능이에요.\n"
            "1부터 100까지 더하는 코드를 100줄이 아닌 5줄로 쓸 수 있게 해줘요.\n"
            "\n"
            "조건문 2종류:\n"
            "  if/else if/else → 조건식(true/false)에 따라 분기해요\n"
            "  switch          → 값이 정해진 여러 갈래일 때 깔끔하게 써요\n"
            "\n"
            "반복문 3종류:\n"
            "  for      → 몇 번 반복할지 횟수가 정해진 경우에 써요\n"
            "  while    → 어떤 조건이 참인 동안 계속 반복하는 경우에 써요\n"
            "  do-while → 최소 1번은 실행하고, 그 다음부터 조건을 검사해요\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  int score = 82;\n"
            "  → 점수를 담는 정수 상자를 만들고 82를 넣어요.\n"
            "\n"
            "  if (score >= 90) System.out.println(\"A\");\n"
            "  → score가 90 이상이면 'A'를 출력해요.\n"
            "    if 뒤 괄호 안의 조건이 true일 때만 중괄호(또는 바로 뒤 문장)가 실행돼요.\n"
            "\n"
            "  else if (score >= 80) System.out.println(\"B\");\n"
            "  → 앞의 조건(90 이상)이 false일 때 이 조건을 검사해요.\n"
            "    score가 80 이상 90 미만이면 'B'를 출력해요.\n"
            "\n"
            "  else System.out.println(\"C\");\n"
            "  → 앞의 모든 조건이 false일 때 실행돼요.\n"
            "    즉, score가 80 미만이면 'C'를 출력해요.\n"
            "\n"
            "  int day = 3;\n"
            "  switch (day) { ... }\n"
            "  → day의 값에 따라 여러 case 중 맞는 것을 실행해요.\n"
            "    if-else if를 여러 개 쓰는 것보다 깔끔해요.\n"
            "\n"
            "  case 1: System.out.println(\"월\"); break;\n"
            "  → day가 1이면 '월'을 출력하고 switch 문을 빠져나가요.\n"
            "    break가 없으면 다음 case로 계속 실행돼요 (fall-through). 주의!\n"
            "\n"
            "  case 3: System.out.println(\"수\"); break;\n"
            "  → day가 3이니까 이 case가 실행돼요. '수'를 출력하고 switch를 종료해요.\n"
            "\n"
            "  default: System.out.println(\"기타\");\n"
            "  → 어떤 case와도 일치하지 않을 때 실행돼요. if-else의 else와 같아요.\n"
            "\n"
            "  int sum = 0;\n"
            "  for (int i = 1; i <= 10; i++) { ... }\n"
            "  → for문은 세 부분으로 구성돼요:\n"
            "    int i = 1   : 처음에 한 번만 실행 — i를 1로 시작해요\n"
            "    i <= 10     : 매 반복 전에 검사 — i가 10 이하이면 계속해요\n"
            "    i++         : 매 반복 후에 실행 — i를 1씩 증가시켜요\n"
            "    즉, i가 1, 2, 3, ..., 10이 될 때까지 총 10번 반복해요.\n"
            "\n"
            "  if (i % 2 == 1) continue;\n"
            "  → i를 2로 나눈 나머지가 1이면 (= 홀수이면) 이번 반복의 나머지를 건너뛰어요.\n"
            "    continue는 '이번 차례는 여기서 끝내고 다음 차례로 바로 가'라는 뜻이에요.\n"
            "    그래서 홀수(1, 3, 5, 7, 9)는 건너뛰고 짝수만 sum에 더해요.\n"
            "\n"
            "  sum += i;\n"
            "  → sum = sum + i 의 줄임 표현이에요. 짝수 i를 sum에 누적해서 더해요.\n"
            "\n"
            "  System.out.println(\"1~10 짝수합: \" + sum);\n"
            "  → 2+4+6+8+10 = 30이 출력돼요.\n"
            "\n"
            "  int n = 5, fact = 1;\n"
            "  while (n > 1) { fact *= n; n--; }\n"
            "  → n이 1보다 큰 동안 반복해요. 5! = 5×4×3×2×1을 계산하는 코드예요.\n"
            "    fact *= n은 fact = fact * n의 줄임이고, n--은 n을 1 감소시켜요.\n"
            "    진행: fact=5→20→60→120, n=4→3→2→1 순서로 n이 1이 되면 멈춰요.\n"
            "\n"
            "  System.out.println(\"5! = \" + fact);\n"
            "  → 5!(팩토리얼) 결과인 120을 출력해요.\n"
            "\n"
            "주의할 점:\n"
            "  switch의 각 case 끝에 break를 빠뜨리면 다음 case도 실행돼요 (fall-through 버그)\n"
            "  while 반복문은 종료 조건을 빠뜨리면 영원히 끝나지 않아요 (무한 루프)\n"
            "  for문의 증감 방향을 잘못 쓰면 처음부터 한 번도 실행 안 될 수 있어요\n"
            "  예: for (int i = 1; i >= 10; i++) 는 1이 10보다 크지 않으니 즉시 종료돼요"
        ),
        usage="모든 흐름 제어의 기본. 횟수가 정해지면 for, 조건이 끝을 정하면 while 을 택한다.",
        cons="switch 의 break 누락 버그가 흔하다. 무한 while 은 종료 조건을 빠뜨리면 멈추지 않는다.",
        code=(
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        int score = 82;\n"
            "        if (score >= 90) System.out.println(\"A\");\n"
            "        else if (score >= 80) System.out.println(\"B\");\n"
            "        else System.out.println(\"C\");\n"
            "\n"
            "        int day = 3;\n"
            "        switch (day) {\n"
            "            case 1: System.out.println(\"월\"); break;\n"
            "            case 3: System.out.println(\"수\"); break;\n"
            "            default: System.out.println(\"기타\");\n"
            "        }\n"
            "\n"
            "        int sum = 0;\n"
            "        for (int i = 1; i <= 10; i++) {\n"
            "            if (i % 2 == 1) continue; // 홀수는 건너뜀\n"
            "            sum += i;                 // 짝수만 더함\n"
            "        }\n"
            "        System.out.println(\"1~10 짝수합: \" + sum); // 30\n"
            "\n"
            "        int n = 5, fact = 1;\n"
            "        while (n > 1) { fact *= n; n--; }\n"
            "        System.out.println(\"5! = \" + fact);       // 120\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-basic-04",
        lang="java", level="기초",
        title="배열(1차원/2차원)",
        summary="고정 길이 · new · length · 향상된 for · 2차원 배열",
        explanation=(
            "━━ 배열 이란? ━━\n"
            "\n"
            "배열은 '같은 종류의 상자를 여러 개 나란히 붙여 놓은 것'이에요.\n"
            "예를 들어 학생 30명의 점수를 저장할 때, 변수 30개를 따로 만들면 너무 힘들잖아요?\n"
            "배열을 쓰면 score[0], score[1], ..., score[29] 처럼 번호로 관리할 수 있어요.\n"
            "\n"
            "왜 배열이 필요할까요?\n"
            "같은 종류의 데이터 여러 개를 한꺼번에 다룰 때 반복문과 함께 쓰면 매우 편해요.\n"
            "배열은 메모리에 연속으로 붙어 있어서 접근 속도가 매우 빠른 장점도 있어요.\n"
            "\n"
            "배열의 중요한 특징:\n"
            "  - 만들 때 크기를 정하면 나중에 바꿀 수 없어요 (고정 길이)\n"
            "  - 인덱스(번호)는 항상 0부터 시작해요\n"
            "  - 범위를 벗어난 인덱스를 쓰면 에러(ArrayIndexOutOfBoundsException)가 나요\n"
            "  - 숫자 배열은 0, boolean은 false, 참조형은 null로 자동 초기화돼요\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  int[] a = {5, 2, 9, 1};\n"
            "  → int형 배열 a를 만들면서 바로 값을 넣어요.\n"
            "    a[0]=5, a[1]=2, a[2]=9, a[3]=1 이렇게 4칸짜리 배열이 만들어져요.\n"
            "    값을 나중에 채울 때는 int[] a = new int[4]; 처럼 크기만 먼저 정해요.\n"
            "\n"
            "  int sum = 0;\n"
            "  for (int x : a) sum += x;\n"
            "  → 이게 '향상된 for문(enhanced for)'이에요.\n"
            "    배열 a의 원소를 하나씩 꺼내 x에 담아서 반복해요.\n"
            "    x가 5, 2, 9, 1 순서로 들어오고 sum에 계속 더해져요.\n"
            "    인덱스가 필요 없을 때 이 방식이 훨씬 간결해요.\n"
            "\n"
            "  System.out.println(\"길이: \" + a.length + \", 합: \" + sum);\n"
            "  → a.length는 배열의 원소 개수를 알려줘요. 여기선 4예요.\n"
            "    중요: .length는 메서드가 아니라 필드라 뒤에 괄호()가 없어요!\n"
            "    (String의 .length()와 다르니 헷갈리지 마세요)\n"
            "\n"
            "  Arrays.sort(a);\n"
            "  → 배열 a를 오름차순(작은 값부터 큰 값 순서)으로 정렬해요.\n"
            "    정렬 전: {5, 2, 9, 1} → 정렬 후: {1, 2, 5, 9}\n"
            "    Arrays는 자바가 제공하는 배열 도구 모음 클래스예요.\n"
            "    사용하려면 파일 위에 import java.util.Arrays; 를 적어야 해요.\n"
            "\n"
            "  System.out.println(\"정렬: \" + Arrays.toString(a));\n"
            "  → 배열을 그냥 println하면 이상한 주소값이 나와요.\n"
            "    Arrays.toString(a)를 써야 [1, 2, 5, 9] 처럼 보기 좋게 출력돼요.\n"
            "\n"
            "  int[][] grid = { {1, 2, 3}, {4, 5, 6} };\n"
            "  → 2차원 배열이에요. '배열의 배열'이라고 생각해요.\n"
            "    엑셀 표처럼 행과 열로 이루어진 데이터를 저장할 때 써요.\n"
            "    grid[0]은 첫 번째 행 {1, 2, 3}이고, grid[1]은 두 번째 행 {4, 5, 6}이에요.\n"
            "    grid[0][2]는 첫 번째 행의 세 번째 원소인 3이에요.\n"
            "\n"
            "  for (int i = 0; i < grid.length; i++) {\n"
            "  → grid.length는 행(row)의 수예요. 여기선 2예요.\n"
            "    i가 0과 1일 때 반복하므로 첫 번째 행, 두 번째 행을 차례로 처리해요.\n"
            "\n"
            "    for (int j = 0; j < grid[i].length; j++) {\n"
            "    → grid[i].length는 i번째 행의 열(column) 수예요. 여기선 3이에요.\n"
            "      안쪽 for문이 각 행의 원소를 하나씩 처리해요.\n"
            "\n"
            "      System.out.print(grid[i][j] + \" \");\n"
            "      → grid[i][j]는 i행 j열의 값을 꺼내요.\n"
            "        print(줄바꿈 없음)으로 같은 줄에 이어서 출력해요.\n"
            "\n"
            "    System.out.println();\n"
            "    → 한 행이 끝나면 줄바꿈만 해줘요. 아무 값도 출력 안 하고 줄만 바꿔요.\n"
            "\n"
            "주의할 점:\n"
            "  배열 크기는 만든 후 바꿀 수 없어요. 크기가 유동적이면 ArrayList를 써요.\n"
            "  a[4]처럼 존재하지 않는 인덱스를 쓰면 ArrayIndexOutOfBoundsException이 나요.\n"
            "  배열 출력 시 println(a) 대신 Arrays.toString(a)를 꼭 써야 해요.\n"
            "  2차원 배열 출력은 Arrays.deepToString(grid)를 써요."
        ),
        usage="크기가 고정된 데이터, 격자/표 형태 데이터 처리에 적합. 인접 메모리라 접근이 빠르다.",
        cons="길이를 만든 뒤 바꿀 수 없다(크기 변경이 필요하면 ArrayList). 범위를 벗어나면 예외가 난다.",
        code=(
            "import java.util.Arrays;\n"
            "\n"
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        int[] a = {5, 2, 9, 1};\n"
            "        int sum = 0;\n"
            "        for (int x : a) sum += x;           // 향상된 for\n"
            "        System.out.println(\"길이: \" + a.length + \", 합: \" + sum);\n"
            "\n"
            "        Arrays.sort(a);                     // 오름차순 정렬\n"
            "        System.out.println(\"정렬: \" + Arrays.toString(a));\n"
            "\n"
            "        int[][] grid = {                    // 2x3 2차원 배열\n"
            "            {1, 2, 3},\n"
            "            {4, 5, 6}\n"
            "        };\n"
            "        for (int i = 0; i < grid.length; i++) {\n"
            "            for (int j = 0; j < grid[i].length; j++) {\n"
            "                System.out.print(grid[i][j] + \" \");\n"
            "            }\n"
            "            System.out.println();\n"
            "        }\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-basic-05",
        lang="java", level="기초",
        title="문자열(String)과 주요 메서드",
        summary="불변 · length/charAt/substring/indexOf · split · StringBuilder",
        explanation=(
            "━━ 문자열(String) 이란? ━━\n"
            "\n"
            "String은 '문자들의 연속'이에요. 'H', 'e', 'l', 'l', 'o'가 이어지면 \"Hello\"가 되는 거죠.\n"
            "자바의 String은 한 번 만들어지면 내용을 바꿀 수 없어요 (불변, immutable).\n"
            "\n"
            "불변이 무슨 뜻이냐고요?\n"
            "s = \"Hello\"라고 만든 후, s = s + \" World\"를 하면 기존 \"Hello\"가 바뀌는 게 아니에요.\n"
            "새로운 \"Hello World\" 문자열이 새로 만들어지고 s가 그 새 문자열을 가리키게 돼요.\n"
            "기존 \"Hello\"는 버려져요. 그래서 반복문 안에서 + 연산을 많이 하면 엄청 느려져요!\n"
            "\n"
            "왜 불변으로 만들었을까요?\n"
            "여러 곳에서 같은 문자열을 공유해도 누군가 바꿔버릴 걱정이 없어요.\n"
            "또한 자바는 같은 문자열을 재사용(String Pool)해서 메모리를 절약해요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  String s = \"Hello, Java\";\n"
            "  → 문자열 변수 s를 만들고 \"Hello, Java\"를 넣어요.\n"
            "    인덱스: H=0, e=1, l=2, l=3, o=4, ,=5, 공백=6, J=7, a=8, v=9, a=10\n"
            "\n"
            "  System.out.println(\"길이: \" + s.length());\n"
            "  → .length()는 문자열의 총 글자 수를 반환해요. 공백과 특수문자도 1로 세요.\n"
            "    \"Hello, Java\"는 11글자라서 11이 나와요.\n"
            "    배열의 .length와 달리 문자열은 .length() 괄호가 있어요!\n"
            "\n"
            "  System.out.println(\"첫 글자: \" + s.charAt(0));\n"
            "  → .charAt(i)는 i번째 위치의 문자 하나를 꺼내요.\n"
            "    인덱스는 0부터 시작하므로 charAt(0)은 첫 글자 'H'예요.\n"
            "    char 타입으로 반환되는데, String과 + 로 합치면 자동으로 문자열이 돼요.\n"
            "\n"
            "  System.out.println(\"부분: \" + s.substring(7));\n"
            "  → .substring(a)는 a번째 위치부터 끝까지 잘라낸 부분 문자열이에요.\n"
            "    인덱스 7은 'J'이므로 \"Java\"가 반환돼요.\n"
            "    .substring(a, b)는 a부터 b 직전(b는 미포함)까지 잘라요.\n"
            "\n"
            "  System.out.println(\"위치: \" + s.indexOf(\"Java\"));\n"
            "  → .indexOf(찾을문자열)은 해당 문자열이 처음 나오는 인덱스를 반환해요.\n"
            "    \"Java\"는 인덱스 7에서 시작하므로 7이 반환돼요.\n"
            "    찾는 문자열이 없으면 -1을 반환해요. 이걸 이용해 존재 여부를 확인할 수 있어요.\n"
            "\n"
            "  System.out.println(\"대문자: \" + s.toUpperCase());\n"
            "  → 모든 글자를 대문자로 바꾼 새 문자열을 반환해요.\n"
            "    원본 s는 변하지 않아요 (불변이니까요!)\n"
            "    소문자로 바꾸려면 .toLowerCase()를 써요.\n"
            "\n"
            "  String line = \"3 5 7\";\n"
            "  String[] tokens = line.split(\" \");\n"
            "  → .split(구분자)는 구분자를 기준으로 문자열을 잘라 배열로 돌려줘요.\n"
            "    \" \"(공백)으로 자르면 {\"3\", \"5\", \"7\"} 3칸짜리 배열이 생겨요.\n"
            "    코딩테스트에서 '공백으로 구분된 숫자들'을 읽을 때 많이 쓰는 패턴이에요!\n"
            "\n"
            "  int total = 0;\n"
            "  for (String t : tokens) total += Integer.parseInt(t);\n"
            "  → 배열의 각 원소(\"3\", \"5\", \"7\")를 순서대로 꺼내 정수로 변환해서 더해요.\n"
            "    parseInt가 없으면 \"3\" + \"5\" + \"7\" = \"357\"처럼 문자열 연결이 돼요!\n"
            "\n"
            "  StringBuilder sb = new StringBuilder();\n"
            "  → 내용을 계속 추가할 수 있는 '가변 문자열 버퍼'를 만들어요.\n"
            "    String과 달리 내용을 직접 수정할 수 있어서 반복 연결 시 훨씬 빠르다.\n"
            "    마치 노트에 계속 글을 덧쓰는 것과 같아요. String은 매번 새 노트를 쓰는 거고요.\n"
            "\n"
            "  for (int i = 1; i <= 3; i++) sb.append(i).append('-');\n"
            "  → .append(값)은 버퍼 끝에 값을 이어 붙여요.\n"
            "    i=1: \"1-\", i=2: \"1-2-\", i=3: \"1-2-3-\" 순서로 쌓여요.\n"
            "    .append()는 sb 자신을 반환하므로 .append(i).append('-')처럼 이어 쓸 수 있어요.\n"
            "\n"
            "  System.out.println(\"빌더: \" + sb.toString());\n"
            "  → StringBuilder를 일반 String으로 변환해서 출력해요.\n"
            "    결과는 \"1-2-3-\"이에요.\n"
            "\n"
            "  System.out.println(\"내용 비교: \" + \"abc\".equals(\"abc\"));\n"
            "  → 문자열 내용 비교는 반드시 .equals()를 써야 해요!\n"
            "    == 는 '두 변수가 같은 객체를 가리키는지'를 검사해요 (주소 비교).\n"
            "    .equals()는 '두 문자열의 내용이 같은지'를 검사해요 (값 비교).\n"
            "    문자열 비교에 == 를 쓰면 가끔 true가 나오기도 하지만 믿으면 안 돼요!\n"
            "\n"
            "주의할 점:\n"
            "  반복문 안에서 String + 연산을 많이 하면 매우 느려져요 → StringBuilder를 써요.\n"
            "  문자열 비교는 반드시 .equals()를 쓰고 ==는 절대 쓰지 마세요.\n"
            "  substring(7, 11)처럼 범위를 초과하면 StringIndexOutOfBoundsException이 나요.\n"
            "  split(\".\")(점으로 자르기)은 점(.)이 정규식에서 특수문자라 split(\"\\\\.\")처럼 써야 해요."
        ),
        usage="텍스트 파싱·가공의 기본. 입력 한 줄을 split 으로 토큰화하는 패턴이 매우 흔하다.",
        cons="불변이라 루프 안 + 연결은 비효율적이다(StringBuilder 권장). 내용 비교는 반드시 equals 로 한다.",
        code=(
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        String s = \"Hello, Java\";\n"
            "        System.out.println(\"길이: \" + s.length());\n"
            "        System.out.println(\"첫 글자: \" + s.charAt(0));\n"
            "        System.out.println(\"부분: \" + s.substring(7));      // Java\n"
            "        System.out.println(\"위치: \" + s.indexOf(\"Java\"));   // 7\n"
            "        System.out.println(\"대문자: \" + s.toUpperCase());\n"
            "\n"
            "        String line = \"3 5 7\";\n"
            "        String[] tokens = line.split(\" \");\n"
            "        int total = 0;\n"
            "        for (String t : tokens) total += Integer.parseInt(t);\n"
            "        System.out.println(\"토큰 합: \" + total);             // 15\n"
            "\n"
            "        StringBuilder sb = new StringBuilder();\n"
            "        for (int i = 1; i <= 3; i++) sb.append(i).append('-');\n"
            "        System.out.println(\"빌더: \" + sb.toString());        // 1-2-3-\n"
            "\n"
            "        System.out.println(\"내용 비교: \" + \"abc\".equals(\"abc\"));\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-basic-06",
        lang="java", level="기초",
        title="입력(Scanner vs BufferedReader)",
        summary="Scanner의 편의성 · BufferedReader의 속도 · 개념 비교",
        explanation=(
            "━━ 입력 처리 이란? ━━\n"
            "\n"
            "프로그램이 사용자(또는 파일)로부터 데이터를 받는 것을 '입력'이라고 해요.\n"
            "코딩테스트에서는 대부분 키보드 대신 '파일 리다이렉션'으로 입력을 줘요.\n"
            "즉, 미리 만들어진 입력 파일을 프로그램에 넣어서 자동으로 테스트해요.\n"
            "\n"
            "자바에서 표준 입력(System.in)을 읽는 방법은 크게 두 가지예요:\n"
            "\n"
            "방법 1 — Scanner (편하지만 느림):\n"
            "  마치 창구 직원이 한 명씩 응대하듯, 입력을 하나씩 처리해요.\n"
            "  nextInt() — 정수 하나 읽기\n"
            "  next()    — 공백 구분 단어 하나 읽기\n"
            "  nextLine() — 한 줄 전체 읽기\n"
            "  코드가 짧고 직관적이지만, 내부에서 많은 처리를 해서 느려요.\n"
            "  입력 수가 10만~100만 개가 넘으면 시간 초과(TLE)가 날 수 있어요.\n"
            "\n"
            "방법 2 — BufferedReader (빠르지만 파싱 필요):\n"
            "  마치 대형 트럭이 한꺼번에 짐을 싣듯, 입력을 버퍼(임시 저장소)에 잔뜩 모아서 한 번에 처리해요.\n"
            "  readLine() — 한 줄 전체를 문자열로 읽기\n"
            "  숫자가 필요하면 Integer.parseInt()로 직접 변환해야 해요.\n"
            "  여러 숫자가 공백으로 나뉜 경우 StringTokenizer 또는 split으로 잘라야 해요.\n"
            "  코드가 Scanner보다 길지만 매우 빠르므로 코딩테스트 표준으로 쓰여요.\n"
            "\n"
            "선택 기준:\n"
            "  입력이 1,000개 이하 → Scanner 써도 괜찮아요\n"
            "  입력이 10,000개 이상 → BufferedReader를 써야 안전해요\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  String input = \"3\\n10 20 30\\n\";\n"
            "  → 실제 코딩테스트에서는 System.in으로 입력이 오지만, 이 예제에서는\n"
            "    테스트 편의를 위해 문자열로 입력을 흉내 냈어요.\n"
            "    첫 줄이 \"3\"(개수), 둘째 줄이 \"10 20 30\"(숫자 3개)인 입력이에요.\n"
            "\n"
            "  BufferedReader br = new BufferedReader(new StringReader(input));\n"
            "  → BufferedReader 객체를 만들어요.\n"
            "    실제로는 new BufferedReader(new InputStreamReader(System.in))처럼 써요.\n"
            "    BufferedReader는 내부에 버퍼를 두고 입력을 크게 잘라 읽어서 빠른 거예요.\n"
            "\n"
            "  int n = Integer.parseInt(br.readLine().trim());\n"
            "  → br.readLine()으로 첫 번째 줄 \"3\"을 읽어요.\n"
            "    .trim()은 앞뒤 공백이나 개행 문자를 제거해줘요.\n"
            "    Integer.parseInt()로 문자열 \"3\"을 정수 3으로 변환해요.\n"
            "    왜 trim()을 쓰냐면, 줄 끝에 공백이 섞여 있어도 안전하게 파싱되거든요.\n"
            "\n"
            "  StringTokenizer st = new StringTokenizer(br.readLine());\n"
            "  → 두 번째 줄 \"10 20 30\"을 읽고 StringTokenizer로 공백 기준 분리 준비를 해요.\n"
            "    StringTokenizer는 split보다 빠르게 토큰을 나눠줘요.\n"
            "    st.nextToken()을 호출할 때마다 \"10\", \"20\", \"30\" 순서로 꺼내줘요.\n"
            "\n"
            "  int sum = 0;\n"
            "  for (int i = 0; i < n; i++) {\n"
            "  → n번(3번) 반복해요. i는 0부터 시작해서 n-1까지 가요.\n"
            "\n"
            "      sum += Integer.parseInt(st.nextToken());\n"
            "  → st.nextToken()으로 토큰 하나씩 꺼내고, parseInt로 정수 변환 후 sum에 더해요.\n"
            "    10 + 20 + 30 = 60이 돼요.\n"
            "\n"
            "  System.out.println(\"개수: \" + n);\n"
            "  → n은 3이므로 '개수: 3'이 출력돼요.\n"
            "\n"
            "  System.out.println(\"합계: \" + sum);\n"
            "  → 합계인 60이 출력돼요.\n"
            "\n"
            "  // 참고: 실제로는 new BufferedReader(new InputStreamReader(System.in)) 로 만든다.\n"
            "  → 실제 코딩테스트 제출 코드에서는 이렇게 System.in으로 연결해요.\n"
            "    그러면 파일이나 키보드 입력을 자동으로 읽을 수 있어요.\n"
            "\n"
            "주의할 점:\n"
            "  Scanner에서 nextInt() 후 nextLine()을 바로 쓰면 빈 문자열을 읽는 함정이 있어요.\n"
            "  nextInt()는 숫자만 읽고 줄바꿈(\\n)을 남겨두거든요. nextLine()이 그 빈 줄을 먹어버려요.\n"
            "  BufferedReader는 throws IOException을 메서드 시그니처에 추가해야 해요.\n"
            "  StringTokenizer의 nextToken()에 더 이상 토큰이 없는데 호출하면 에러가 나요."
        ),
        usage="코딩테스트에서 입력이 크면 BufferedReader 가 사실상 표준. 작은 입력엔 Scanner 가 편하다.",
        cons="Scanner 는 느리고 nextInt 와 nextLine 을 섞으면 개행 처리 함정이 있다. BufferedReader 는 IOException 처리와 파싱을 직접 해야 한다.",
        code=(
            "import java.io.BufferedReader;\n"
            "import java.io.IOException;\n"
            "import java.io.StringReader;\n"
            "import java.util.StringTokenizer;\n"
            "\n"
            "public class Main {\n"
            "    public static void main(String[] args) throws IOException {\n"
            "        // 표준입력 대신 고정 문자열로 데모(System.in 을 흉내 냄)\n"
            "        String input = \"3\\n10 20 30\\n\";\n"
            "        BufferedReader br = new BufferedReader(new StringReader(input));\n"
            "\n"
            "        int n = Integer.parseInt(br.readLine().trim()); // 첫 줄: 개수\n"
            "        StringTokenizer st = new StringTokenizer(br.readLine());\n"
            "        int sum = 0;\n"
            "        for (int i = 0; i < n; i++) {\n"
            "            sum += Integer.parseInt(st.nextToken());    // 토큰별 정수 파싱\n"
            "        }\n"
            "        System.out.println(\"개수: \" + n);\n"
            "        System.out.println(\"합계: \" + sum);            // 60\n"
            "\n"
            "        // 참고: 실제로는 new BufferedReader(new InputStreamReader(System.in)) 로 만든다.\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-basic-07",
        lang="java", level="기초",
        title="연산자와 형 승격",
        summary="산술/비교/논리/대입 · 정수 나눗셈 · 자동 타입 승격 규칙",
        explanation=(
            "━━ 연산자와 형 승격 이란? ━━\n"
            "\n"
            "연산자는 '값들 사이에서 계산을 수행하는 기호'예요.\n"
            "+, -, *, / 같은 수학 기호들과 비슷하지만 컴퓨터만의 특별한 규칙이 있어요.\n"
            "\n"
            "형 승격(Type Promotion)은 '서로 다른 타입끼리 연산할 때 작은 타입이 큰 타입으로 자동 변환되는 것'이에요.\n"
            "예를 들어 정수 int와 실수 double을 더하면 int가 자동으로 double로 변환돼요.\n"
            "작은 그릇의 물을 큰 그릇에 옮기는 것처럼 정보가 손실되지 않는 방향으로 변환돼요.\n"
            "\n"
            "승격 순서 (작은 → 큰):\n"
            "  byte/short/char → int → long → float → double\n"
            "\n"
            "연산자 4가지 종류:\n"
            "  산술: + (더하기)  - (빼기)  * (곱하기)  / (나누기)  % (나머지)\n"
            "  비교: == (같음)  != (다름)  < (작음)  <= (이하)  > (큼)  >= (이상) → 결과는 true/false\n"
            "  논리: && (그리고, AND)  || (또는, OR)  ! (부정, NOT)\n"
            "  대입: = 와 복합대입 += -= *= /= %=\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  int a = 7, b = 3;\n"
            "  → 정수 a와 b를 선언하고 각각 7, 3을 넣어요.\n"
            "\n"
            "  System.out.println(\"몫: \" + (a / b) + \", 나머지: \" + (a % b));\n"
            "  → a / b는 정수 나눗셈이라 7 / 3 = 2 (몫만, 나머지 버림)예요.\n"
            "    a % b는 나머지 연산이라 7 % 3 = 1 (7 = 3×2 + 1)이에요.\n"
            "    나머지 연산(%)은 짝수/홀수 판별, 순환 인덱스 등에서 매우 자주 써요.\n"
            "\n"
            "  double avg = (a + b) / 2.0;\n"
            "  → 2.0은 double 리터럴이에요. int + int가 int이지만, int / double은 double로 승격돼요.\n"
            "    (7 + 3) = 10 (int) / 2.0 (double) = 5.0 (double)\n"
            "    만약 2 (int)로 나눴다면 10 / 2 = 5 (int)가 됐을 거예요.\n"
            "\n"
            "  System.out.println(\"평균: \" + avg);\n"
            "  → 5.0이 출력돼요. double이라 소수점이 보여요.\n"
            "\n"
            "  boolean cond = (a > 5) && (b < 5);\n"
            "  → (a > 5)는 7 > 5 → true\n"
            "    (b < 5)는 3 < 5 → true\n"
            "    true && true → true (둘 다 참이어야 AND가 참)\n"
            "    &&는 '단축 평가'를 해요: 왼쪽이 false이면 오른쪽은 아예 검사하지 않아요.\n"
            "\n"
            "  System.out.println(\"논리 결과: \" + cond);\n"
            "  → true가 출력돼요.\n"
            "\n"
            "  int big = 100000;\n"
            "  → 십만을 big에 넣어요. int 범위(약 21억)보다 훨씬 작아서 괜찮아요.\n"
            "\n"
            "  long overflowSafe = (long) big * big;\n"
            "  → big * big = 100000 * 100000 = 100억이에요.\n"
            "    그런데 100억은 int의 최댓값(약 21억)을 넘어요!\n"
            "    (long) big으로 먼저 big을 long으로 변환하면, 이후 big(int)도 자동으로 long으로 승격돼요.\n"
            "    그러면 long 범위(약 900경)에서 안전하게 계산돼요.\n"
            "\n"
            "  System.out.println(\"안전한 곱: \" + overflowSafe);\n"
            "  → 10000000000 (100억)이 올바르게 출력돼요.\n"
            "\n"
            "  System.out.println(\"위험한 곱(int): \" + (big * big));\n"
            "  → big * big을 int끼리 곱하면 100억이 int 범위를 넘어 '오버플로'가 발생해요.\n"
            "    결과가 1410065408처럼 전혀 엉뚱한 숫자가 나와요.\n"
            "    오버플로는 에러 없이 조용히 틀린 값이 나오므로 매우 위험해요!\n"
            "\n"
            "복합 대입 연산자 정리:\n"
            "  a += 3  →  a = a + 3  (더한 값을 다시 a에 저장)\n"
            "  a -= 3  →  a = a - 3\n"
            "  a *= 3  →  a = a * 3\n"
            "  a /= 3  →  a = a / 3\n"
            "  a %= 3  →  a = a % 3\n"
            "\n"
            "주의할 점:\n"
            "  정수끼리 나누면 소수점이 버려져요. 평균이나 확률을 구할 때 한 쪽을 double로 만들어요.\n"
            "  int 오버플로는 에러 없이 틀린 값이 나오므로 큰 수 계산 시 long을 써야 해요.\n"
            "  ==는 기본형 값 비교에 써요. 참조형(String, 배열 등) 내용 비교는 .equals()예요.\n"
            "  &&와 ||는 단축 평가를 하므로, 오른쪽에 부작용(side effect)이 있으면 주의해야 해요."
        ),
        usage="수치 계산 전반의 기본. 평균·확률처럼 소수가 필요한 계산에선 형 승격을 의식해야 한다.",
        cons="정수 나눗셈으로 소수점이 사라지는 실수가 잦다. int 오버플로는 예외 없이 조용히 틀린 값을 낸다.",
        code=(
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        int a = 7, b = 3;\n"
            "        System.out.println(\"몫: \" + (a / b) + \", 나머지: \" + (a % b)); // 2, 1\n"
            "\n"
            "        double avg = (a + b) / 2.0;   // 2.0 때문에 double 로 승격\n"
            "        System.out.println(\"평균: \" + avg);                 // 5.0\n"
            "\n"
            "        boolean cond = (a > 5) && (b < 5);\n"
            "        System.out.println(\"논리 결과: \" + cond);            // true\n"
            "\n"
            "        int big = 100000;\n"
            "        long overflowSafe = (long) big * big;  // long 으로 승격해 오버플로 방지\n"
            "        System.out.println(\"안전한 곱: \" + overflowSafe);   // 10000000000\n"
            "        System.out.println(\"위험한 곱(int): \" + (big * big)); // 오버플로된 값\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-basic-08",
        lang="java", level="기초",
        title="메서드 정의와 호출",
        summary="static 메서드 · 매개변수/반환값 · 오버로딩 · 중첩 클래스",
        explanation=(
            "━━ 메서드(Method) 이란? ━━\n"
            "\n"
            "메서드는 '이름 붙인 코드 블록'이에요. 특정 기능을 수행하는 코드를 묶어서 이름을 붙인 거예요.\n"
            "예를 들어 '두 수를 더하는 기능'을 add()라는 메서드로 만들면,\n"
            "필요할 때마다 add(3, 4) 처럼 간단히 호출해서 쓸 수 있어요.\n"
            "\n"
            "왜 메서드가 필요할까요?\n"
            "  1) 중복 코드 제거: 같은 코드를 여러 번 쓰지 않고 메서드 하나로 재사용해요.\n"
            "  2) 가독성: 코드의 의도가 명확해져요. 100줄짜리 main 대신 여러 메서드로 나누면 읽기 쉬워요.\n"
            "  3) 유지보수: 수정할 때 한 곳만 고치면 모든 곳에 적용돼요.\n"
            "\n"
            "메서드 형식:\n"
            "  [접근제어자] static 반환타입 메서드이름(매개변수1, 매개변수2, ...) {\n"
            "      // 실행할 코드\n"
            "      return 반환값; // 반환타입이 void면 return 생략 가능\n"
            "  }\n"
            "\n"
            "  static: 객체를 만들지 않고 클래스 이름만으로(또는 같은 클래스 내에서 이름만으로) 호출할 수 있어요.\n"
            "  반환타입: 메서드가 결과를 돌려주는 값의 타입. 결과가 없으면 void.\n"
            "  매개변수: 메서드가 받는 입력값들.\n"
            "\n"
            "오버로딩(Overloading):\n"
            "  같은 이름의 메서드를 매개변수 개수나 타입만 다르게 해서 여러 개 만드는 것이에요.\n"
            "  예: add(int a, int b)와 add(double a, double b)는 같은 이름이지만 다른 메서드예요.\n"
            "  자바가 호출 시 매개변수 타입을 보고 어떤 것을 쓸지 자동으로 선택해요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  static int add(int a, int b) {\n"
            "  → 'add'라는 이름의 메서드를 정의해요.\n"
            "    int a, int b는 이 메서드가 정수 두 개를 입력으로 받는다는 뜻이에요.\n"
            "    static은 객체 없이 바로 호출할 수 있게 해줘요.\n"
            "    앞의 int는 이 메서드가 정수를 결과로 돌려준다는 뜻이에요.\n"
            "\n"
            "      return a + b;\n"
            "  → a + b를 계산해서 결과를 호출한 곳으로 돌려줘요.\n"
            "    return 뒤의 값이 메서드의 최종 결과예요.\n"
            "    return을 만나면 메서드 실행이 즉시 끝나요.\n"
            "\n"
            "  static double add(double a, double b) {\n"
            "  → 같은 이름 add지만 매개변수 타입이 double로 다른 버전이에요.\n"
            "    이게 '오버로딩'이에요. 같은 이름으로 다른 타입을 처리해요.\n"
            "    add(3, 4)를 호출하면 정수 버전이, add(1.5, 2.5)를 호출하면 실수 버전이 실행돼요.\n"
            "\n"
            "      return a + b;\n"
            "  → double끼리 더한 결과를 돌려줘요.\n"
            "\n"
            "  static void greet(String name) {\n"
            "  → 반환타입이 void이므로 결과값을 돌려주지 않아요.\n"
            "    대신 화면에 출력하는 '부작용(side effect)'만 해요.\n"
            "    void 메서드는 return을 생략하거나, return;만 써서 일찍 종료할 수 있어요.\n"
            "\n"
            "      System.out.println(name + \"님, 환영합니다.\");\n"
            "  → 매개변수로 받은 name을 이용해 인사 문구를 출력해요.\n"
            "\n"
            "  static class Calculator {\n"
            "  → Main 클래스 안에 Calculator라는 또 다른 클래스를 만들어요.\n"
            "    자바에서 모든 코드는 클래스 안에 있어야 해요.\n"
            "    여러 기능을 논리적으로 묶을 때 중첩 클래스를 쓰면 편리해요.\n"
            "    static을 붙이면 외부 클래스 객체 없이도 이 클래스를 사용할 수 있어요.\n"
            "\n"
            "      int multiply(int a, int b) { return a * b; }\n"
            "  → Calculator 클래스의 multiply 메서드예요. static이 없으므로 인스턴스 메서드예요.\n"
            "    인스턴스 메서드는 객체를 먼저 만들어야 호출할 수 있어요.\n"
            "\n"
            "  System.out.println(\"정수 합: \" + add(3, 4));\n"
            "  → add(3, 4)를 호출하면 정수 버전 메서드가 실행되고 7을 돌려줘요.\n"
            "    반환된 7이 그 자리에 대입되어 '정수 합: 7'이 출력돼요.\n"
            "\n"
            "  System.out.println(\"실수 합: \" + add(1.5, 2.5));\n"
            "  → add(1.5, 2.5)는 double 버전 메서드가 실행돼요. 결과는 4.0이에요.\n"
            "\n"
            "  greet(\"홍길동\");\n"
            "  → greet 메서드를 호출해요. void라 반환값을 받을 변수가 필요 없어요.\n"
            "    '홍길동님, 환영합니다.'가 화면에 출력돼요.\n"
            "\n"
            "  Calculator calc = new Calculator();\n"
            "  → Calculator 클래스의 객체(인스턴스)를 만들어요.\n"
            "    인스턴스 메서드를 쓰려면 이렇게 객체를 먼저 만들어야 해요.\n"
            "    new 키워드가 메모리에 Calculator 객체 공간을 만들고, calc가 그 주소를 가져요.\n"
            "\n"
            "  System.out.println(\"곱: \" + calc.multiply(6, 7));\n"
            "  → calc 객체를 통해 multiply 메서드를 호출해요.\n"
            "    6 * 7 = 42가 계산되어 반환되고, '곱: 42'가 출력돼요.\n"
            "\n"
            "주의할 점:\n"
            "  static 메서드 안에서 static이 아닌 인스턴스 메서드나 필드를 직접 쓰면 에러가 나요.\n"
            "  매개변수의 이름(a, b)은 메서드 안에서만 유효한 지역 변수예요. 밖에서는 쓸 수 없어요.\n"
            "  오버로딩은 반환 타입만 다를 때는 안 돼요. 반드시 매개변수 개수나 타입이 달라야 해요.\n"
            "  메서드 이름은 보통 소문자로 시작하고, 단어가 바뀌면 대문자로 이어써요 (camelCase)."
        ),
        usage="중복 코드를 함수로 묶어 재사용한다. 오버로딩으로 비슷한 기능을 같은 이름으로 제공할 수 있다.",
        cons="static 메서드는 인스턴스 상태(필드)에 접근할 수 없다. 매개변수가 많아지면 호출 의미가 흐려진다.",
        code=(
            "public class Main {\n"
            "    // 정수 두 개의 합을 반환하는 static 메서드\n"
            "    static int add(int a, int b) {\n"
            "        return a + b;\n"
            "    }\n"
            "\n"
            "    // 오버로딩: 같은 이름, 매개변수 타입이 다름(실수 버전)\n"
            "    static double add(double a, double b) {\n"
            "        return a + b;\n"
            "    }\n"
            "\n"
            "    // 반환값이 없는 메서드(void)\n"
            "    static void greet(String name) {\n"
            "        System.out.println(name + \"님, 환영합니다.\");\n"
            "    }\n"
            "\n"
            "    // 여러 클래스가 필요하면 static 중첩 클래스로 정리\n"
            "    static class Calculator {\n"
            "        int multiply(int a, int b) { return a * b; }\n"
            "    }\n"
            "\n"
            "    public static void main(String[] args) {\n"
            "        System.out.println(\"정수 합: \" + add(3, 4));        // 7\n"
            "        System.out.println(\"실수 합: \" + add(1.5, 2.5));    // 4.0\n"
            "        greet(\"홍길동\");\n"
            "\n"
            "        Calculator calc = new Calculator();\n"
            "        System.out.println(\"곱: \" + calc.multiply(6, 7));   // 42\n"
            "    }\n"
            "}\n"
        ),
    ),
]
