"""Java 중급 문법 (컬렉션 · 제네릭 · 객체지향 · 예외 · 문자열 · 정렬)."""

from engine.models import Lesson

LESSONS = [

    Lesson(
        id="java-mid-01",
        lang="java", level="중급",
        title="List와 ArrayList",
        summary="가변 배열 · add/get/size · for-each",
        explanation=(
            "━━ List와 ArrayList 란? ━━\n"
            "\n"
            "리스트는 마트 가기 전에 쓰는 쇼핑 목록과 똑같아요.\n"
            "\"사과, 바나나, 포도\" 순서대로 적어두고, 나중에 \"멜론\"을 추가하거나\n"
            "\"바나나\"를 지울 수도 있죠. 순서도 유지돼요.\n"
            "\n"
            "Java의 일반 배열(int[] arr)과 비교하면:\n"
            "  - 배열은 크기를 미리 정해야 해요.  예: int[] arr = new int[5];  → 딱 5칸만!\n"
            "  - ArrayList는 크기가 자동으로 늘어나요. 아무리 추가해도 공간이 생겨요.\n"
            "\n"
            "그래서 '몇 개가 들어올지 모를 때' ArrayList를 써요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  import java.util.*;                          →  Java가 미리 만들어둔 도구 모음(컬렉션 라이브러리)을 불러와요.\n"
            "                                                  이 한 줄이 없으면 ArrayList, List 등을 전혀 쓸 수 없어요.\n"
            "\n"
            "  List<String> fruits = new ArrayList<>();     →  '문자열(String)만 담을 수 있는 리스트'를 만들어요.\n"
            "                                                  List<String>은 설계도(인터페이스), new ArrayList<>()는 실제 물건(구현체)이에요.\n"
            "                                                  <String> 부분이 '이 리스트는 String만 넣을 수 있어요'라고 못 박는 표시예요.\n"
            "                                                  인터페이스 타입으로 선언하는 이유: 나중에 LinkedList 등으로 바꿀 때 이 줄만 수정하면 돼요.\n"
            "\n"
            "  fruits.add(\"사과\");                          →  리스트 맨 끝에 \"사과\"를 추가해요. 쇼핑 목록에 항목 하나 적는 것과 같아요.\n"
            "  fruits.add(\"바나나\");                        →  \"바나나\"를 추가해요. 이제 리스트는 [사과, 바나나]가 됐어요.\n"
            "  fruits.add(\"포도\");                          →  \"포도\"를 추가해요. 최종 [사과, 바나나, 포도]예요.\n"
            "\n"
            "  System.out.println(\"개수: \" + fruits.size()); →  size()는 리스트 안에 있는 항목 수를 숫자로 알려줘요.\n"
            "                                                  지금 3개 들어 있으니 \"개수: 3\"이 출력돼요.\n"
            "\n"
            "  System.out.println(\"첫번째: \" + fruits.get(0)); →  get(0)은 0번 위치에 있는 항목을 꺼내요.\n"
            "                                                  Java는 번호를 항상 0부터 세요! 0=사과, 1=바나나, 2=포도.\n"
            "                                                  그러니까 첫 번째 = get(0)이에요.\n"
            "\n"
            "  for (String f : fruits) {                    →  fruits 안의 모든 항목을 하나씩 f에 담아서 반복해요.\n"
            "                                                  '사과' → '바나나' → '포도' 순서로 f에 들어와요.\n"
            "                                                  이걸 for-each 문이라고 해요. '리스트 안의 것들 하나하나에 대해'라는 뜻이에요.\n"
            "\n"
            "  System.out.println(\"과일 = \" + f);           →  현재 반복 중인 과일 이름 f를 출력해요.\n"
            "\n"
            "주의할 점:\n"
            "  get(인덱스)를 쓸 때 범위를 벗어나면 IndexOutOfBoundsException 에러가 나요.\n"
            "  예: 항목이 3개인데 fruits.get(5)를 하면 → 프로그램이 죽어버려요!\n"
            "  또, List<String>이라고 선언했으면 숫자(123)는 절대 넣을 수 없어요. 다른 타입을 넣으려 하면 컴파일 오류가 나요.\n"
            "  인덱스 범위: 0 이상, size()-1 이하만 유효해요."
        ),
        usage="크기가 변하는 목록을 다룰 때 기본으로 사용한다. 인덱스 조회가 빠르다(O(1)).",
        cons="중간 삽입/삭제는 뒤 요소를 모두 옮겨야 해서 O(n)으로 느리다. 그런 연산이 잦으면 LinkedList 고려.",
        code=(
            "import java.util.*;\n"
            "\n"
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        List<String> fruits = new ArrayList<>();\n"
            "        fruits.add(\"사과\");\n"
            "        fruits.add(\"바나나\");\n"
            "        fruits.add(\"포도\");\n"
            "        System.out.println(\"개수: \" + fruits.size());\n"
            "        System.out.println(\"첫번째: \" + fruits.get(0));\n"
            "        for (String f : fruits) {\n"
            "            System.out.println(\"과일 = \" + f);\n"
            "        }\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-mid-02",
        lang="java", level="중급",
        title="Map과 HashMap",
        summary="키-값 저장 · put/get · getOrDefault",
        explanation=(
            "━━ Map과 HashMap 이란? ━━\n"
            "\n"
            "Map은 영어 사전과 같아요.\n"
            "사전에서 \"apple\" 이라는 단어(키)를 찾으면 \"사과\" 라는 뜻(값)이 나오죠.\n"
            "Map도 마찬가지로 '키(key) → 값(value)' 쌍을 저장해요.\n"
            "\n"
            "예를 들어:\n"
            "  \"사과\" → 3번 등장\n"
            "  \"배\"   → 2번 등장\n"
            "이런 식으로 단어가 몇 번 나왔는지 셀 때 Map이 딱이에요!\n"
            "\n"
            "HashMap은 Map을 구현한 가장 흔한 방법이에요.\n"
            "해시(hash)라는 수학적 기법으로 값을 저장하기 때문에 찾는 속도가 매우 빨라요(평균 O(1)).\n"
            "전화번호부 앱에서 이름 검색하면 바로 번호가 나오는 것처럼요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  Map<String, Integer> count = new HashMap<>();   →  키는 String(문자열), 값은 Integer(정수)인 HashMap을 만들어요.\n"
            "                                                      즉, '단어 → 개수'를 기록할 사전을 만드는 거예요.\n"
            "\n"
            "  String[] words = {\"사과\", \"배\", \"사과\", \"사과\", \"배\"};  →  단어들이 담긴 배열이에요.\n"
            "                                                      사과가 3번, 배가 2번 들어있어요.\n"
            "\n"
            "  for (String w : words) {                        →  배열의 단어를 하나씩 w에 꺼내서 반복해요.\n"
            "\n"
            "  count.put(w, count.getOrDefault(w, 0) + 1);    →  이 줄이 핵심이에요! 단계별로 읽어볼게요.\n"
            "                                                      1) count.getOrDefault(w, 0)\n"
            "                                                         → 현재 w 단어의 카운트를 가져와요.\n"
            "                                                            만약 w가 처음 나온 단어라 Map에 없으면 기본값 0을 줘요.\n"
            "                                                      2) ... + 1\n"
            "                                                         → 거기에 1을 더해요. (새로 한 번 더 등장했으니까)\n"
            "                                                      3) count.put(w, ...)\n"
            "                                                         → 그 새 값으로 Map에 저장해요.\n"
            "                                                      결국: '사과'가 처음 나오면 0+1=1, 두 번째면 1+1=2, 세 번째면 2+1=3\n"
            "\n"
            "  System.out.println(\"사과 = \" + count.get(\"사과\")); →  get(\"사과\")로 \"사과\" 키에 저장된 값을 꺼내요. 3이 나와요.\n"
            "\n"
            "  System.out.println(\"배 = \" + count.get(\"배\"));     →  \"배\"는 2번 등장했으니 2가 나와요.\n"
            "\n"
            "  System.out.println(\"전체 = \" + count);              →  Map 전체를 출력하면 {사과=3, 배=2} 형태로 보여요.\n"
            "\n"
            "주의할 점:\n"
            "  count.get(\"키위\")처럼 없는 키를 get하면 null이 반환돼요. (에러는 아니지만 이걸 그대로 쓰면 NullPointerException 발생 가능!)\n"
            "  그래서 getOrDefault(키, 기본값)을 쓰는 게 훨씬 안전해요.\n"
            "  HashMap은 저장 순서가 보장되지 않아요. 출력할 때 넣은 순서와 다를 수 있어요.\n"
            "  순서를 유지하고 싶으면 LinkedHashMap을 쓰세요."
        ),
        usage="단어 빈도수 세기, 이름→점수 매핑 등 키로 값을 빠르게 찾아야 할 때 쓴다.",
        cons="저장 순서가 보장되지 않는다. 순서가 필요하면 LinkedHashMap, 정렬이 필요하면 TreeMap 을 쓴다.",
        code=(
            "import java.util.*;\n"
            "\n"
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        Map<String, Integer> count = new HashMap<>();\n"
            "        String[] words = {\"사과\", \"배\", \"사과\", \"사과\", \"배\"};\n"
            "        for (String w : words) {\n"
            "            count.put(w, count.getOrDefault(w, 0) + 1);\n"
            "        }\n"
            "        System.out.println(\"사과 = \" + count.get(\"사과\"));\n"
            "        System.out.println(\"배 = \" + count.get(\"배\"));\n"
            "        System.out.println(\"전체 = \" + count);\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-mid-03",
        lang="java", level="중급",
        title="Set과 HashSet",
        summary="중복 제거 · contains · 집합",
        explanation=(
            "━━ Set과 HashSet 이란? ━━\n"
            "\n"
            "Set은 우표 수집 앨범과 같아요.\n"
            "우표 수집가는 같은 우표를 두 장 갖지 않아요. 이미 있으면 새로 추가해도 의미가 없죠.\n"
            "Java의 Set도 마찬가지로 '중복을 허용하지 않는' 컬렉션이에요.\n"
            "\n"
            "언제 쓰냐고요?\n"
            "  - '이미 본 적 있는 번호인가?' 빠르게 확인할 때\n"
            "  - 배열에서 중복을 제거하고 싶을 때\n"
            "  - 방문한 좌표를 기록해서 '이미 방문했나?' 확인할 때 (BFS/DFS에서 자주 씀!)\n"
            "\n"
            "HashSet은 Set의 가장 흔한 구현체예요.\n"
            "HashMap처럼 해시 기법으로 동작하기 때문에 '포함 여부 확인(contains)'이 매우 빨라요(평균 O(1)).\n"
            "반면 ArrayList에서 contains를 쓰면 처음부터 끝까지 다 찾아야 해서 O(n)이에요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  int[] data = {1, 2, 2, 3, 3, 3, 4};  →  중복이 포함된 정수 배열이에요. 2는 두 번, 3은 세 번 들어있어요.\n"
            "\n"
            "  Set<Integer> set = new HashSet<>();   →  Integer(정수)를 담는 HashSet을 만들어요.\n"
            "                                            주의: 기본형 int는 제네릭에 못 써요. 래퍼 클래스 Integer를 써야 해요.\n"
            "\n"
            "  for (int x : data) {                 →  배열의 숫자를 하나씩 x에 꺼내요.\n"
            "\n"
            "  set.add(x);                          →  x를 Set에 추가해요.\n"
            "                                            이미 있는 값이면 그냥 무시돼요. 아무 오류도 안 나요.\n"
            "                                            1 추가 → {1}\n"
            "                                            2 추가 → {1, 2}\n"
            "                                            2 또 추가 → {1, 2}  (변화 없음!)\n"
            "                                            3 추가 → {1, 2, 3}\n"
            "                                            3 또 추가 → {1, 2, 3}  (변화 없음!)\n"
            "                                            3 또또 추가 → {1, 2, 3}  (변화 없음!)\n"
            "                                            4 추가 → {1, 2, 3, 4}\n"
            "\n"
            "  System.out.println(\"고유 개수: \" + set.size());       →  고유한 숫자가 몇 개인지 알려줘요. 결과: 4 (1,2,3,4)\n"
            "\n"
            "  System.out.println(\"3 포함? \" + set.contains(3));    →  3이 Set 안에 있으면 true, 없으면 false를 반환해요.\n"
            "                                                            결과: true\n"
            "\n"
            "  System.out.println(\"9 포함? \" + set.contains(9));    →  9는 data 배열에 없었으니 Set에도 없어요.\n"
            "                                                            결과: false\n"
            "\n"
            "실생활 활용 패턴:\n"
            "  // 배열에서 중복 제거\n"
            "  List<Integer> list = Arrays.asList(1, 2, 2, 3);\n"
            "  Set<Integer> unique = new HashSet<>(list);  // {1, 2, 3}\n"
            "\n"
            "주의할 점:\n"
            "  HashSet은 저장 순서가 보장되지 않아요. 출력하면 넣은 순서와 다를 수 있어요.\n"
            "  삽입 순서를 유지하고 싶으면 LinkedHashSet을 쓰세요.\n"
            "  정렬된 순서로 유지하고 싶으면 TreeSet을 쓰세요.\n"
            "  기본형 int 대신 Integer를 써야 해요. (자동 박싱되기도 하지만 명시적으로 쓰는 게 안전해요)"
        ),
        usage="중복 제거, '이미 본 적 있는지' 빠른 확인, 방문 체크 등에 쓴다(평균 O(1)).",
        cons="저장 순서가 보장되지 않는다. 삽입 순서 유지가 필요하면 LinkedHashSet 을 사용한다.",
        code=(
            "import java.util.*;\n"
            "\n"
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        int[] data = {1, 2, 2, 3, 3, 3, 4};\n"
            "        Set<Integer> set = new HashSet<>();\n"
            "        for (int x : data) {\n"
            "            set.add(x);\n"
            "        }\n"
            "        System.out.println(\"고유 개수: \" + set.size());\n"
            "        System.out.println(\"3 포함? \" + set.contains(3));\n"
            "        System.out.println(\"9 포함? \" + set.contains(9));\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-mid-04",
        lang="java", level="중급",
        title="제네릭(Generics)",
        summary="타입 매개변수 <T> · 타입 안전",
        explanation=(
            "━━ 제네릭(Generics) 이란? ━━\n"
            "\n"
            "제네릭은 '어떤 타입이든 담을 수 있는 만능 상자'를 만드는 방법이에요.\n"
            "\n"
            "비유: 택배 상자를 생각해보세요.\n"
            "  - 그냥 상자: 안에 뭐가 들어있는지 모르니까, 꺼낼 때 항상 확인해야 해요.\n"
            "  - 제네릭 상자: 상자에 '과일 전용', '책 전용' 라벨을 붙여요.\n"
            "                 그러면 꺼낼 때 '이건 반드시 과일이야'라고 확신할 수 있어요.\n"
            "\n"
            "제네릭 없이 쓰면 어떻게 될까요?\n"
            "  // 제네릭 없는 구식 방법\n"
            "  Object value = \"안녕\";\n"
            "  String s = (String) value;  // 강제 형변환 필요 → 실수하면 ClassCastException 에러!\n"
            "\n"
            "제네릭을 쓰면:\n"
            "  Box<String> box = new Box<>();\n"
            "  box.set(\"안녕\");\n"
            "  String s = box.get();  // 형변환 불필요! 컴파일러가 자동으로 String임을 알아요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  static class Box<T> {              →  <T>는 '타입 매개변수'예요. T는 그냥 이름이고, 나중에 실제 타입으로 교체돼요.\n"
            "                                         Box<String>이면 T가 String이 되고, Box<Integer>면 T가 Integer가 돼요.\n"
            "                                         관례상 T(Type), E(Element), K(Key), V(Value) 등을 써요.\n"
            "\n"
            "  private T value;                   →  T 타입의 value 필드를 선언해요. 아직 구체적인 타입은 모르는 상태예요.\n"
            "\n"
            "  public void set(T v) { this.value = v; }  →  T 타입의 값 v를 받아서 저장해요.\n"
            "                                                  Box<String>이면 String을 받고, Box<Integer>면 Integer를 받아요.\n"
            "\n"
            "  public T get() { return value; }   →  저장된 값을 T 타입으로 반환해요. 꺼낼 때 형변환이 필요 없어요!\n"
            "\n"
            "  Box<String> s = new Box<>();       →  이 순간 T가 String으로 확정돼요. 문자열 전용 상자가 됐어요.\n"
            "\n"
            "  s.set(\"안녕\");                      →  문자열 \"안녕\"을 넣어요. T=String이니까 String만 받아요. 숫자 넣으면 컴파일 오류!\n"
            "\n"
            "  System.out.println(\"문자열 상자: \" + s.get());  →  꺼낼 때 String 타입이 보장돼요. (String)으로 캐스팅 불필요.\n"
            "\n"
            "  Box<Integer> n = new Box<>();      →  이번엔 T가 Integer로 확정돼요. 정수 전용 상자예요.\n"
            "\n"
            "  n.set(42);                         →  정수 42를 넣어요. (int 42가 자동으로 Integer 42로 박싱돼요)\n"
            "\n"
            "  System.out.println(\"정수 상자: \" + n.get());    →  42가 출력돼요.\n"
            "\n"
            "왜 제네릭을 쓰냐고요?\n"
            "  1. 타입 안전: 잘못된 타입을 넣으면 실행 전에 컴파일 오류로 잡아줘요.\n"
            "  2. 형변환 불필요: 꺼낼 때 (String) 같은 캐스팅을 안 해도 돼요.\n"
            "  3. 코드 재사용: Box<String>도, Box<Integer>도, Box<Dog>도 같은 Box 클래스로 만들어요.\n"
            "\n"
            "주의할 점:\n"
            "  기본형(int, double, char 등)은 제네릭에 직접 못 써요.\n"
            "  대신 래퍼 클래스(Integer, Double, Character 등)를 써야 해요.\n"
            "  예: Box<int> → 오류!    Box<Integer> → 정상!\n"
            "  값을 넣고 꺼낼 때 자동으로 박싱/언박싱(int ↔ Integer 변환)이 일어나서 약간의 성능 오버헤드가 있어요."
        ),
        usage="여러 타입에 재사용 가능한 자료구조/유틸을 만들 때, 형변환 없이 타입 안전을 얻고 싶을 때 쓴다.",
        cons="기본형(int 등)은 직접 못 쓰고 래퍼(Integer)로 박싱돼 약간의 오버헤드가 있다. 과하면 코드가 복잡해진다.",
        code=(
            "public class Main {\n"
            "    static class Box<T> {\n"
            "        private T value;\n"
            "        public void set(T v) { this.value = v; }\n"
            "        public T get() { return value; }\n"
            "    }\n"
            "\n"
            "    public static void main(String[] args) {\n"
            "        Box<String> s = new Box<>();\n"
            "        s.set(\"안녕\");\n"
            "        System.out.println(\"문자열 상자: \" + s.get());\n"
            "        Box<Integer> n = new Box<>();\n"
            "        n.set(42);\n"
            "        System.out.println(\"정수 상자: \" + n.get());\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-mid-05",
        lang="java", level="중급",
        title="클래스 · 상속 · 인터페이스",
        summary="extends · implements · 오버라이딩",
        explanation=(
            "━━ 클래스 · 상속 · 인터페이스 란? ━━\n"
            "\n"
            "클래스는 설계도예요.\n"
            "  자동차 설계도가 있으면 그 도면으로 여러 대의 차를 만들 수 있듯이,\n"
            "  Dog 클래스(설계도)로 여러 마리의 개 객체를 만들 수 있어요.\n"
            "\n"
            "상속(extends)은 '부모 설계도를 물려받는 것'이에요.\n"
            "  예: '강아지(Puppy)'는 '개(Dog)'의 모든 특징을 가지면서, 추가로 '아기 울음소리'를 내요.\n"
            "  이런 부모-자식 관계를 코드로 표현할 때 extends를 써요.\n"
            "  자식은 부모의 모든 메서드와 필드를 그대로 사용할 수 있어요.\n"
            "\n"
            "인터페이스(interface)는 '이것만은 반드시 구현해야 해!'라는 약속이에요.\n"
            "  예: 음식점 알바 계약서에 '식사는 제공한다'고 적혀있으면,\n"
            "       이탈리안, 한식, 중식 등 어떤 음식점이든 반드시 식사를 제공해야 해요.\n"
            "  Animal 인터페이스에 sound() 메서드가 있으면,\n"
            "  Animal을 implements한 모든 클래스는 반드시 sound()를 구현해야 해요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  interface Animal {                  →  Animal 인터페이스를 선언해요.\n"
            "                                         '동물이라면 반드시 소리를 낼 수 있어야 한다'는 약속이에요.\n"
            "\n"
            "  String sound();                     →  메서드 선언만 있고, 구현({}안의 코드)이 없어요.\n"
            "                                         '소리를 내는 기능이 있어야 한다'는 규칙만 정해요.\n"
            "                                         실제로 어떤 소리인지는 각 동물 클래스가 결정해요.\n"
            "\n"
            "  static class Dog implements Animal { →  Dog 클래스가 Animal 인터페이스를 구현해요.\n"
            "                                          implements: '이 약속을 지키겠다'는 선언이에요.\n"
            "                                          이 줄부터 Dog는 sound() 메서드를 반드시 만들어야 해요.\n"
            "                                          (안 만들면 컴파일 오류!)\n"
            "\n"
            "  public String sound() { return \"멍멍\"; }  →  Dog가 sound()를 구현해요. 개 소리는 '멍멍'이에요.\n"
            "\n"
            "  static class Puppy extends Dog {    →  Puppy 클래스가 Dog 클래스를 상속해요.\n"
            "                                         Puppy는 Dog의 모든 것을 물려받아요.\n"
            "                                         하지만 소리만큼은 다르게 낼 거예요.\n"
            "\n"
            "  @Override                           →  부모(Dog)의 sound() 메서드를 덮어쓰겠다는 선언이에요.\n"
            "                                         이 애너테이션은 필수는 아니지만, 실수를 방지해줘요.\n"
            "                                         (메서드 이름을 잘못 써도 컴파일러가 잡아줘요)\n"
            "\n"
            "  public String sound() { return \"왈왈\"; }  →  Puppy만의 소리를 정의해요. 강아지는 '왈왈'이에요.\n"
            "\n"
            "  Animal a = new Dog();               →  Dog 객체를 만들었지만, Animal 타입으로 받아요.\n"
            "                                         이게 가능한 이유: Dog는 Animal을 implements했으니까요.\n"
            "                                         마치 '개는 동물이다'가 참인 것처럼요.\n"
            "\n"
            "  Animal b = new Puppy();             →  Puppy 객체도 Animal 타입으로 받을 수 있어요.\n"
            "                                         Puppy는 Dog를 extends하고, Dog는 Animal을 implements했으니까요.\n"
            "\n"
            "  System.out.println(\"개: \" + a.sound());     →  a는 Dog니까 sound()가 \"멍멍\"을 반환해요.\n"
            "  System.out.println(\"강아지: \" + b.sound());  →  b는 Puppy니까 @Override된 sound()가 \"왈왈\"을 반환해요.\n"
            "                                                      같은 Animal 타입이지만 실제 동작이 달라요! → 이게 다형성이에요.\n"
            "\n"
            "핵심 차이 정리:\n"
            "  extends: '부모의 것을 물려받아요'  → 하나만 가능 (단일 상속)\n"
            "  implements: '이 약속을 지킬게요'   → 여러 개 가능 (다중 구현)\n"
            "\n"
            "주의할 점:\n"
            "  Java는 extends를 하나만 쓸 수 있어요. (class A extends B, C → 오류!)\n"
            "  인터페이스는 여러 개 구현 가능해요. (class A implements B, C, D → 정상!)\n"
            "  상속 계층이 너무 깊어지면 (Dog → Puppy → BabyPuppy → ...) 코드 파악이 어려워요."
        ),
        usage="공통 동작을 부모로 묶어 코드 중복을 줄이고, 인터페이스로 구현을 교체 가능하게 설계할 때 쓴다.",
        cons="상속이 깊어지면 결합도가 높아져 유지보수가 어렵다. 단순 기능 공유는 상속보다 조합이 나을 때가 많다.",
        code=(
            "public class Main {\n"
            "    interface Animal {\n"
            "        String sound();\n"
            "    }\n"
            "    static class Dog implements Animal {\n"
            "        public String sound() { return \"멍멍\"; }\n"
            "    }\n"
            "    static class Puppy extends Dog {\n"
            "        @Override public String sound() { return \"왈왈\"; }\n"
            "    }\n"
            "\n"
            "    public static void main(String[] args) {\n"
            "        Animal a = new Dog();\n"
            "        Animal b = new Puppy();\n"
            "        System.out.println(\"개: \" + a.sound());\n"
            "        System.out.println(\"강아지: \" + b.sound());\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-mid-06",
        lang="java", level="중급",
        title="예외 처리(try/catch)",
        summary="try-catch-finally · 예외 던지기",
        explanation=(
            "━━ 예외 처리(try/catch) 란? ━━\n"
            "\n"
            "예외(Exception)는 프로그램 실행 중에 발생하는 예상치 못한 오류예요.\n"
            "\n"
            "비유: 계란 후라이를 만들 때를 생각해봐요.\n"
            "  try { 계란을 깨서 후라이 만들기 }\n"
            "  catch { 계란이 썩었으면 → 버리고 새 계란 꺼내기 }\n"
            "  finally { 어떻게 됐든 → 가스 불은 끄기 }\n"
            "\n"
            "예외가 왜 필요하냐고요?\n"
            "  예외 처리 없으면: 배열 범위 초과 → 프로그램 즉시 종료! 사용자는 아무것도 모름.\n"
            "  예외 처리 있으면: 에러를 잡아서 '잘못된 입력이에요. 다시 입력해주세요'라고 알려줄 수 있어요.\n"
            "\n"
            "자주 만나는 예외 종류:\n"
            "  ArrayIndexOutOfBoundsException  →  배열 범위 초과 (크기 3인데 arr[5] 접근)\n"
            "  NumberFormatException           →  문자를 숫자로 변환 실패 (\"abc\"를 int로 변환 시도)\n"
            "  NullPointerException            →  null인 변수를 사용하려 할 때\n"
            "  ArithmeticException             →  0으로 나누기\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  int[] arr = {10, 20, 30};       →  크기 3짜리 배열. 인덱스 0, 1, 2만 유효해요.\n"
            "\n"
            "  try {                           →  '이 블록 안의 코드를 실행해봐요. 위험할 수 있지만.'이라는 뜻이에요.\n"
            "\n"
            "  System.out.println(arr[5]);     →  arr[5]를 접근하려 해요. 하지만 인덱스 5는 없어요! → 예외 발생!\n"
            "                                     예외가 발생하면 이 줄 이후 try 블록 코드는 실행되지 않아요.\n"
            "                                     바로 catch 블록으로 점프해요.\n"
            "\n"
            "  } catch (ArrayIndexOutOfBoundsException e) {  →  배열 범위 초과 예외를 잡아요.\n"
            "                                                     e는 예외 객체예요. e.getMessage()로 오류 메시지를 볼 수 있어요.\n"
            "                                                     try 블록에서 이 타입의 예외가 나면 여기서 처리해요.\n"
            "\n"
            "  System.out.println(\"잘못된 인덱스 접근입니다\");  →  에러가 났을 때 보여줄 메시지를 출력해요.\n"
            "                                                         프로그램은 죽지 않고 이 메시지를 보여주고 계속 실행돼요.\n"
            "\n"
            "  } finally {                    →  try든 catch든 항상 실행되는 블록이에요.\n"
            "                                     '성공해도, 실패해도 반드시 실행'이에요.\n"
            "                                     파일 닫기, DB 연결 종료 같은 정리 작업에 써요.\n"
            "\n"
            "  System.out.println(\"처리 완료\");  →  try가 성공해도, catch가 실행돼도 항상 이 줄이 출력돼요.\n"
            "\n"
            "  int x = Integer.parseInt(\"abc\");  →  \"abc\"를 정수로 변환하려 해요. 불가능! → NumberFormatException 발생!\n"
            "\n"
            "  } catch (NumberFormatException e) {  →  문자→숫자 변환 실패 예외를 잡아요.\n"
            "\n"
            "  System.out.println(\"숫자가 아닙니다\");  →  변환 실패했을 때 안내 메시지를 출력해요.\n"
            "\n"
            "실행 흐름 정리:\n"
            "  (1) arr[5] 접근 시도 → 예외 발생\n"
            "  (2) catch 블록으로 이동 → '잘못된 인덱스 접근입니다' 출력\n"
            "  (3) finally 블록 실행 → '처리 완료' 출력\n"
            "  (4) 다음 try 블록으로 진행\n"
            "  (5) Integer.parseInt(\"abc\") 실패 → 예외 발생\n"
            "  (6) 두 번째 catch 블록 → '숫자가 아닙니다' 출력\n"
            "\n"
            "주의할 점:\n"
            "  빈 catch 블록은 절대 쓰지 마세요!\n"
            "  catch (Exception e) { }  → 예외를 그냥 묻어버려요. 버그를 숨기는 최악의 방법이에요.\n"
            "  catch 블록이 여러 개면 위에서부터 순서대로 확인해요. 더 구체적인 예외를 위에 써야 해요.\n"
            "  Exception 하나로 모든 예외를 잡을 수 있지만, 어떤 에러인지 구분이 안 돼요."
        ),
        usage="파일/네트워크/형변환처럼 실패 가능성이 있는 작업에서 프로그램이 죽지 않게 안전하게 처리할 때 쓴다.",
        cons="예외를 제어 흐름으로 남용하면 느리고 가독성이 나빠진다. 빈 catch 로 삼키면 버그를 숨기게 된다.",
        code=(
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        int[] arr = {10, 20, 30};\n"
            "        try {\n"
            "            System.out.println(\"값: \" + arr[5]);\n"
            "        } catch (ArrayIndexOutOfBoundsException e) {\n"
            "            System.out.println(\"잘못된 인덱스 접근입니다\");\n"
            "        } finally {\n"
            "            System.out.println(\"처리 완료\");\n"
            "        }\n"
            "        try {\n"
            "            int x = Integer.parseInt(\"abc\");\n"
            "            System.out.println(x);\n"
            "        } catch (NumberFormatException e) {\n"
            "            System.out.println(\"숫자가 아닙니다\");\n"
            "        }\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-mid-07",
        lang="java", level="중급",
        title="StringBuilder",
        summary="가변 문자열 · append · 빠른 문자열 조립",
        explanation=(
            "━━ StringBuilder 란? ━━\n"
            "\n"
            "Java에서 String은 '불변(immutable)'이에요.\n"
            "한 번 만들어진 String 객체는 절대 내용이 바뀌지 않아요.\n"
            "\n"
            "비유: String으로 문자열을 이어붙이는 건 매번 새 종이에 다 베껴 쓰는 것과 같아요.\n"
            "  \"안녕\" + \"하세요\" + \"!\"  →  \"안녕하세요!\" (새 종이에 전부 다시 씀)\n"
            "  반복문에서 1000번 이어붙이면? → 1000장의 종이를 만들어요. 엄청난 낭비!\n"
            "\n"
            "StringBuilder는 지우개 달린 화이트보드 같아요.\n"
            "  내용을 덧붙이거나 지울 때 새 보드를 만들지 않아요.\n"
            "  같은 보드에 계속 쓰면 돼요!\n"
            "  마지막에 toString()으로 '화이트보드에 적힌 내용을 종이에 옮겨서' 완성된 String을 만들어요.\n"
            "\n"
            "얼마나 빠르냐고요?\n"
            "  반복문에서 10,000번 이어붙이기:\n"
            "    String 사용: 약 130ms (느려서 실전에서 TLE 나요)\n"
            "    StringBuilder 사용: 약 1ms (100배 이상 빨라요!)\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  StringBuilder sb = new StringBuilder();  →  빈 화이트보드를 만들어요. 아직 아무것도 없어요.\n"
            "\n"
            "  for (int i = 1; i <= 5; i++) {           →  1부터 5까지 반복해요.\n"
            "\n"
            "  sb.append(i);                            →  화이트보드에 i를 덧붙여요.\n"
            "                                               i=1이면 보드: \"1\"\n"
            "                                               i=2이면 보드: \"1-2\" (아래 줄 포함)\n"
            "\n"
            "  if (i < 5) sb.append(\"-\");              →  i가 5보다 작을 때만 구분자 \"-\"를 붙여요.\n"
            "                                               마지막(5) 뒤에는 \"-\"가 안 붙게 하는 트릭이에요.\n"
            "                                               1 → \"1-\"\n"
            "                                               2 → \"1-2-\"\n"
            "                                               3 → \"1-2-3-\"\n"
            "                                               4 → \"1-2-3-4-\"\n"
            "                                               5 → \"1-2-3-4-5\" (마지막엔 - 안 붙음)\n"
            "\n"
            "  System.out.println(\"조립 결과: \" + sb.toString());  →  toString()으로 최종 String으로 변환해요.\n"
            "                                                           결과: \"1-2-3-4-5\"\n"
            "                                                           참고: println에 바로 sb 넣으면 자동으로 toString() 호출돼요.\n"
            "\n"
            "  sb.append(\" 끝\");                        →  기존 내용 뒤에 \" 끝\"을 더 붙여요.\n"
            "                                               보드: \"1-2-3-4-5 끝\"\n"
            "\n"
            "  System.out.println(\"길이: \" + sb.length());  →  현재 보드에 담긴 문자 수를 알려줘요.\n"
            "                                                      \"1-2-3-4-5 끝\"은 12글자예요.\n"
            "\n"
            "  System.out.println(\"뒤집기: \" + sb.reverse());  →  보드의 내용을 뒤집어요!\n"
            "                                                         \"1-2-3-4-5 끝\" → \"끝 5-4-3-2-1\"\n"
            "                                                         회문(팰린드롬) 판별 문제에서 자주 써요!\n"
            "\n"
            "StringBuilder의 주요 메서드 정리:\n"
            "  sb.append(x)         →  뒤에 붙이기 (x는 String, int, char, boolean 모두 가능)\n"
            "  sb.insert(i, x)      →  i번 위치에 x 삽입\n"
            "  sb.delete(s, e)      →  s번부터 e번 전까지 삭제\n"
            "  sb.reverse()         →  전체 뒤집기\n"
            "  sb.length()          →  현재 길이\n"
            "  sb.charAt(i)         →  i번 위치 문자 꺼내기\n"
            "  sb.toString()        →  최종 String으로 변환\n"
            "\n"
            "주의할 점:\n"
            "  멀티스레드 환경에서 여러 스레드가 동시에 같은 StringBuilder를 사용하면 데이터가 꼬일 수 있어요.\n"
            "  그런 경우엔 StringBuffer(동기화 지원)를 쓰세요. (코딩테스트에선 대부분 단일 스레드라 StringBuilder로 충분해요.)\n"
            "  new StringBuilder(1000) 처럼 초기 용량을 설정하면 메모리 재할당이 줄어 더 빨라요."
        ),
        usage="반복문에서 문자열을 많이 이어 붙일 때, 대량 출력을 모아 한 번에 출력할 때 필수로 쓴다.",
        cons="단발성 짧은 연결에는 오히려 번거롭다. 멀티스레드 공유 시에는 StringBuffer 가 안전하다.",
        code=(
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        StringBuilder sb = new StringBuilder();\n"
            "        for (int i = 1; i <= 5; i++) {\n"
            "            sb.append(i);\n"
            "            if (i < 5) sb.append(\"-\");\n"
            "        }\n"
            "        System.out.println(\"조립 결과: \" + sb.toString());\n"
            "        sb.append(\" 끝\");\n"
            "        System.out.println(\"길이: \" + sb.length());\n"
            "        System.out.println(\"뒤집기: \" + sb.reverse());\n"
            "    }\n"
            "}\n"
        ),
    ),

    Lesson(
        id="java-mid-08",
        lang="java", level="중급",
        title="Comparator와 정렬",
        summary="Collections.sort · Arrays.sort · 람다 비교자",
        explanation=(
            "━━ Comparator와 정렬 이란? ━━\n"
            "\n"
            "정렬이란 데이터를 특정 기준에 따라 순서대로 나열하는 것이에요.\n"
            "기본 정렬(오름차순)은 간단하지만, 내 입맛에 맞는 기준으로 정렬하려면 Comparator가 필요해요.\n"
            "\n"
            "비유: 도서관 사서가 책을 정리한다고 해봐요.\n"
            "  - 기본: 제목 가나다순 (Arrays.sort 기본 동작)\n"
            "  - 두꺼운 책부터: 페이지 수 내림차순 (Comparator 사용)\n"
            "  - 같은 두께면 제목 가나다순: 복합 기준 (Comparator 체이닝)\n"
            "\n"
            "Comparator의 동작 원리:\n"
            "  Comparator는 두 값 a, b를 받아서 숫자를 반환해요.\n"
            "  반환값이 음수: a가 b보다 앞에 와야 해요 (a < b)\n"
            "  반환값이 0:    a와 b는 순서 상관없어요 (a == b)\n"
            "  반환값이 양수: b가 a보다 앞에 와야 해요 (a > b)\n"
            "\n"
            "  오름차순: (a, b) -> a - b  (a < b이면 음수 → a가 앞으로)\n"
            "  내림차순: (a, b) -> b - a  (a > b이면 음수 → a가 앞으로)\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  Integer[] nums = {5, 2, 8, 1};                    →  정수 배열이에요.\n"
            "                                                         주의: int[]가 아니라 Integer[]야 해요.\n"
            "                                                         Comparator는 기본형(int)을 못 다루고 래퍼(Integer)를 써요.\n"
            "\n"
            "  Arrays.sort(nums, (a, b) -> b - a);              →  nums 배열을 정렬해요. 기준은 람다 (a, b) -> b - a 예요.\n"
            "                                                        (a, b) -> b - a 해석:\n"
            "                                                          a=5, b=8 이면 b-a = 8-5 = 3 (양수) → b인 8이 앞으로 → 내림차순!\n"
            "                                                          a=8, b=5 이면 b-a = 5-8 = -3 (음수) → a인 8이 앞으로 → 내림차순!\n"
            "                                                        결과: [8, 5, 2, 1]\n"
            "\n"
            "  System.out.println(\"내림차순: \" + Arrays.toString(nums));  →  배열을 보기 좋게 [8, 5, 2, 1] 형태로 출력해요.\n"
            "                                                                    배열은 그냥 println 하면 [I@1b6d3586 같이 이상하게 나와서\n"
            "                                                                    Arrays.toString()을 써야 해요.\n"
            "\n"
            "  List<String> words = new ArrayList<>(Arrays.asList(\"가나다\", \"가\", \"가나\"));  →  문자열 리스트를 만들어요.\n"
            "                                                                                          Arrays.asList로 배열을 리스트로 변환하고,\n"
            "                                                                                          new ArrayList<>()로 감싸야 크기 변경이 가능해요.\n"
            "\n"
            "  Collections.sort(words, Comparator.comparingInt(String::length));  →  단어들을 길이(글자 수) 오름차순으로 정렬해요.\n"
            "                                                                          Comparator.comparingInt(String::length):\n"
            "                                                                            각 단어의 .length() 값을 기준으로 비교해요.\n"
            "                                                                          \"가\"(1글자), \"가나\"(2글자), \"가나다\"(3글자) 순서로 정렬돼요.\n"
            "\n"
            "  System.out.println(\"길이순: \" + words);           →  [가, 가나, 가나다] 출력돼요.\n"
            "\n"
            "자주 쓰는 Comparator 패턴 모음:\n"
            "  // 오름차순 (기본)\n"
            "  Arrays.sort(nums);\n"
            "  Collections.sort(list);\n"
            "\n"
            "  // 내림차순\n"
            "  Arrays.sort(nums, (a, b) -> b - a);\n"
            "  Collections.sort(list, Collections.reverseOrder());\n"
            "\n"
            "  // 문자열 길이 오름차순\n"
            "  Collections.sort(list, Comparator.comparingInt(String::length));\n"
            "\n"
            "  // 점수 내림차순 (2차원 배열)\n"
            "  Arrays.sort(students, (a, b) -> b[1] - a[1]);\n"
            "\n"
            "  // 복합 정렬: 점수 내림차순, 같으면 이름 오름차순\n"
            "  list.sort(Comparator.comparingInt(Student::getScore).reversed()\n"
            "      .thenComparing(Student::getName));\n"
            "\n"
            "주의할 점:\n"
            "  (a, b) -> a - b 패턴은 오버플로우 위험이 있어요!\n"
            "  a = Integer.MIN_VALUE, b = 1 이면 a - b가 오버플로우돼요.\n"
            "  안전한 방법: Integer.compare(a, b) 또는 (a, b) -> Integer.compare(a, b) 사용!\n"
            "  int[] (기본형 배열)에는 Comparator를 직접 못 써요. Integer[]로 바꾸거나 다른 방법을 써야 해요.\n"
            "  비교자 로직이 일관성 없으면 (a>b인데 b>a로 판단 등) 예외나 잘못된 정렬이 나요."
        ),
        usage="문자열 길이순, 점수 내림차순 등 사용자 정의 기준으로 정렬할 때 쓴다.",
        cons="비교자 로직이 일관성(대소 관계 모순)을 깨면 예외가 나거나 잘못 정렬된다. 복잡하면 가독성이 떨어진다.",
        code=(
            "import java.util.*;\n"
            "\n"
            "public class Main {\n"
            "    public static void main(String[] args) {\n"
            "        Integer[] nums = {5, 2, 8, 1};\n"
            "        Arrays.sort(nums, (a, b) -> b - a);   // 내림차순\n"
            "        System.out.println(\"내림차순: \" + Arrays.toString(nums));\n"
            "\n"
            "        List<String> words = new ArrayList<>(Arrays.asList(\"가나다\", \"가\", \"가나\"));\n"
            "        Collections.sort(words, Comparator.comparingInt(String::length));\n"
            "        System.out.println(\"길이순: \" + words);\n"
            "    }\n"
            "}\n"
        ),
    ),
]
