"""Python 고급 문법 (제너레이터·데코레이터·컨텍스트 매니저·itertools·heapq·bisect·functools·빠른 입출력)."""

from engine.models import Lesson

LESSONS = [

    Lesson(
        id="py-adv-01",
        lang="python", level="고급",
        title="제너레이터와 이터레이터(yield)",
        summary="yield 로 값을 하나씩 지연 생성",
        explanation=(
            "[개요]\n"
            "제너레이터(Generator)는 값을 미리 전부 만들지 않고, 요청이 있을 때마다\n"
            "하나씩 지연 생성(lazy evaluation)하는 객체이다. 일반 함수는 return 시점에\n"
            "모든 결과를 한 번에 반환하지만, 제너레이터는 값이 필요한 순간에만 생성하므로\n"
            "메모리를 절약한다.\n"
            "\n"
            "[핵심 개념]\n"
            "• 이터레이터: 다음 값을 하나씩 꺼낼 수 있는 객체이다. next() 호출 시 다음 값을\n"
            "  반환하고, 더 이상 값이 없으면 StopIteration 예외를 발생시킨다.\n"
            "• 제너레이터: 함수 본문에 yield가 포함되면, 호출 시 즉시 실행되지 않고\n"
            "  제너레이터 객체를 반환한다. next() 호출 시점부터 실행이 진행된다.\n"
            "\n"
            "[코드 분석]\n"
            "  def countdown(n):       →  n부터 1까지 역순으로 세는 제너레이터 함수이다.\n"
            "                             yield가 있으므로 호출해도 즉시 실행되지 않고\n"
            "                             제너레이터 객체를 반환한다.\n"
            "  while n > 0:            →  n이 0보다 큰 동안 반복한다.\n"
            "  yield n                 →  n 값을 외부로 반환하고 해당 지점에서 실행을 멈춘다.\n"
            "                             next()가 호출될 때까지 대기하며, n의 현재 값을\n"
            "                             그대로 유지한다.\n"
            "  n -= 1                  →  다음 next() 호출 시 이 지점부터 이어서 실행하며\n"
            "                             n을 1 감소시킨다.\n"
            "  def fib(k):             →  피보나치 수열을 k개 생성하는 제너레이터이다.\n"
            "  a, b = 0, 1             →  피보나치의 첫 두 값 0과 1로 초기화한다.\n"
            "  for _ in range(k):      →  k번 반복한다.\n"
            "  yield a                 →  현재 피보나치 수 a를 반환하고 멈춘다.\n"
            "  a, b = b, a + b         →  다음 피보나치 수를 계산한다. a를 b로, b를 a+b로\n"
            "                             동시에 갱신한다.\n"
            "  gen = countdown(3)      →  호출 시 함수가 실행되지 않고 제너레이터 객체만\n"
            "                             생성되어 gen에 저장된다. 이 시점까지 어떤 값도\n"
            "                             생성되지 않는다.\n"
            "  next(gen), next(gen)    →  첫 next(gen)은 yield n까지 실행하여 3을 반환하고,\n"
            "                             두 번째 호출은 n -= 1 후 yield n에서 2를 반환한다.\n"
            "                             따라서 3 2가 출력된다.\n"
            "  list(countdown(5))      →  countdown(5)의 모든 값을 리스트로 변환하여\n"
            "                             [5, 4, 3, 2, 1]이 된다.\n"
            "  list(fib(8))            →  피보나치 수 8개를 리스트로 변환하여\n"
            "                             [0, 1, 1, 2, 3, 5, 8, 13]이 된다.\n"
            "  sum(x*x for x in ...)  →  x*x for x in range(1,6)은 제너레이터 표현식이며,\n"
            "                             리스트를 생성하지 않고 1+4+9+16+25=55를 바로 합산한다.\n"
            "\n"
            "[활용 목적]\n"
            "파일 100만 줄과 같은 대용량 데이터를 리스트로 만들면 전체가 메모리에 적재된다.\n"
            "제너레이터는 한 줄씩 꺼내 처리하고 폐기하므로 메모리 사용량이 거의 없다.\n"
            "\n"
            "[유의 사항]\n"
            "• 제너레이터는 일회성이다. 끝까지 소비하면 다시 사용할 수 없으며, 재사용하려면\n"
            "  새로 생성해야 한다.\n"
            "• len()으로 길이를 구하거나 인덱스로 접근(gen[0])할 수 없다."
        ),
        usage="대용량 데이터를 한 줄씩 흘려보낼 때, 무한 수열, 파이프라인 처리에 메모리 절약용으로 쓴다.",
        cons="한 번 소비하면 다시 못 돌린다(재사용하려면 다시 생성). 길이(len)나 인덱싱이 불가능하다.",
        code=(
            "def countdown(n):\n"
            "    while n > 0:\n"
            "        yield n          # 여기서 값을 내보내고 멈춘다\n"
            "        n -= 1\n"
            "\n"
            "def fib(k):\n"
            "    a, b = 0, 1\n"
            "    for _ in range(k):\n"
            "        yield a\n"
            "        a, b = b, a + b\n"
            "\n"
            "gen = countdown(3)\n"
            "print(next(gen), next(gen))   # 3 2\n"
            "print(list(countdown(5)))     # [5, 4, 3, 2, 1]\n"
            "print(list(fib(8)))           # [0, 1, 1, 2, 3, 5, 8, 13]\n"
            "\n"
            "# 제너레이터 표현식: 리스트를 만들지 않고 합계만 계산(메모리 절약)\n"
            "print(sum(x * x for x in range(1, 6)))   # 55\n"
        ),
    ),

    Lesson(
        id="py-adv-02",
        lang="python", level="고급",
        title="데코레이터",
        summary="함수를 감싸 기능을 덧붙이는 @문법",
        explanation=(
            "[개요]\n"
            "데코레이터(Decorator)는 원래 함수를 수정하지 않고 그 함수를 감싸\n"
            "기능을 추가하는 문법이다. 로깅, 실행시간 측정 등 공통 기능을 여러 함수에\n"
            "중복 없이 적용할 수 있다.\n"
            "\n"
            "[핵심 개념]\n"
            "• Python에서 함수는 값처럼 다른 함수에 인자로 전달할 수 있다.\n"
            "• 데코레이터는 함수를 인자로 받아 기능이 추가된 새 함수를 반환하는 함수이다.\n"
            "• @logged 한 줄은 add = logged(add)와 완전히 동일하다.\n"
            "\n"
            "[코드 분석]\n"
            "  import functools             →  functools 모듈을 가져온다. wraps를 사용한다.\n"
            "  def logged(func):            →  logged 데코레이터 함수를 정의한다. func 자리에\n"
            "                                 꾸며줄 원래 함수가 전달된다.\n"
            "  @functools.wraps(func)       →  wrapper 함수가 원래 func의 이름과 설명을\n"
            "                                 그대로 승계하도록 한다. 생략하면 add.__name__이\n"
            "                                 \"wrapper\"로 바뀌어 디버깅이 어려워진다.\n"
            "  def wrapper(*args, **kwargs): →  add(3, 4) 호출 시 이 wrapper 함수가 대신\n"
            "                                 실행된다. *args는 위치 인자 전부, **kwargs는\n"
            "                                 키워드 인자 전부를 받아 원래 함수에 그대로 전달한다.\n"
            "  print(f'호출: ...')           →  원래 함수 실행 전, 호출된 함수와 인자를 출력한다.\n"
            "  result = func(*args, **kwargs) →  원래 함수(add)를 전달받은 인자로 실행하고\n"
            "                                 결과를 result에 저장한다.\n"
            "  print(f'결과: {result}')      →  원래 함수 실행 후 결과를 출력한다.\n"
            "  return result                →  원래 함수의 반환값을 그대로 반환한다.\n"
            "                                 누락 시 add(3, 4)가 None이 된다.\n"
            "  return wrapper               →  wrapper 함수 자체를 반환한다. logged(add) 호출\n"
            "                                 결과로 wrapper가 반환된다.\n"
            "  @logged                      →  add = logged(add)와 동일하다. 이후 add 호출 시\n"
            "                                 실제로는 wrapper가 실행된다.\n"
            "  def add(a, b): return a+b   →  두 숫자를 더하는 원래 함수이다.\n"
            "  print(add(3, 4))             →  \"호출: add(3, 4)\", \"결과: 7\", \"7\" 순서로\n"
            "                                 출력된다.\n"
            "  print(add.__name__)          →  functools.wraps 덕분에 \"wrapper\"가 아닌\n"
            "                                 \"add\"가 출력된다.\n"
            "\n"
            "[활용 목적]\n"
            "다수의 함수에 동일한 부가 기능(예: 실행시간 측정)을 적용해야 할 때, 각 함수에\n"
            "같은 코드를 삽입하는 대신 데코레이터 하나를 정의해 @timer로 부착하면 된다.\n"
            "코드 중복 없이 공통 기능을 여러 함수에 추가할 수 있다.\n"
            "\n"
            "[유의 사항]\n"
            "• functools.wraps를 누락하면 add.__name__이 \"wrapper\"가 되어 디버깅 시\n"
            "  혼란을 유발한다. 항상 부착하는 것을 권장한다.\n"
            "• 데코레이터를 여러 개 중첩하면 바깥쪽부터 적용되고 안쪽부터 실행되므로\n"
            "  적용 순서에 유의해야 한다."
        ),
        usage="로깅, 실행시간 측정, 캐싱, 재시도, 접근 제어 등 여러 함수에 공통으로 끼워 넣을 때.",
        cons="중첩이 많으면 스택 추적이 복잡해지고 디버깅이 어렵다. 과용하면 흐름 파악이 힘들다.",
        code=(
            "import functools\n"
            "\n"
            "def logged(func):\n"
            "    @functools.wraps(func)\n"
            "    def wrapper(*args, **kwargs):\n"
            "        print(f'호출: {func.__name__}{args}')\n"
            "        result = func(*args, **kwargs)\n"
            "        print(f'결과: {result}')\n"
            "        return result\n"
            "    return wrapper\n"
            "\n"
            "@logged\n"
            "def add(a, b):\n"
            "    return a + b\n"
            "\n"
            "print(add(3, 4))\n"
            "print(add.__name__)   # wraps 덕분에 'add' 가 그대로 보인다\n"
        ),
    ),

    Lesson(
        id="py-adv-03",
        lang="python", level="고급",
        title="컨텍스트 매니저(with)",
        summary="자원 획득/해제를 자동으로 보장",
        explanation=(
            "[개요]\n"
            "컨텍스트 매니저(Context Manager)는 진입 시 자원을 획득하고, 블록을 벗어날 때\n"
            "정상 종료든 예외 발생이든 관계없이 자원을 반드시 해제하도록 보장하는 구조이다.\n"
            "파일 열기/닫기, 락 획득/해제, 연결 수립/종료 등 반드시 정리가 필요한 작업에\n"
            "with 문과 함께 사용한다.\n"
            "\n"
            "[핵심 개념]\n"
            "• __enter__: with 블록 진입 시 자동으로 호출된다.\n"
            "• __exit__: 블록에서 나올 때(정상 또는 예외) 반드시 호출된다.\n"
            "• 위 두 메서드를 구현한 객체를 컨텍스트 매니저라 한다.\n"
            "\n"
            "[코드 분석]\n"
            "  from contextlib import contextmanager\n"
            "                               →  contextmanager 데코레이터를 가져온다. 이를 쓰면\n"
            "                                  클래스 없이 제너레이터 함수 하나로 컨텍스트\n"
            "                                  매니저를 구현할 수 있다.\n"
            "  class Timer:                 →  Timer 컨텍스트 매니저 클래스를 정의한다.\n"
            "  def __enter__(self):         →  with Timer(): 블록 진입 시 자동 호출된다.\n"
            "                                  준비 작업을 여기에 작성한다.\n"
            "  print('시작')                →  블록 진입 시 \"시작\"을 출력한다.\n"
            "  return self                  →  as 키워드로 바인딩할 객체를 반환한다.\n"
            "                                  with Timer() as t: 에서 t가 self가 된다.\n"
            "  def __exit__(self, exc_type, exc, tb):\n"
            "                               →  with 블록 종료 시 항상 호출된다. 예외 발생 시\n"
            "                                  exc_type, exc, tb에 오류 정보가 전달된다.\n"
            "  print('종료(정리)')           →  블록 종료 시 \"종료(정리)\"를 출력한다.\n"
            "  return False                 →  False 반환 시 예외를 그대로 상위로 전파한다.\n"
            "                                  True 반환 시 예외를 삼켜 오류가 없는 것처럼\n"
            "                                  처리된다. 일반적으로 False가 안전하다.\n"
            "  with Timer():                →  Timer 객체를 생성하고 __enter__를 호출한다.\n"
            "  print('작업 중...')           →  with 블록 본문이다. 블록을 벗어나면 자동으로\n"
            "                                  __exit__가 호출된다.\n"
            "  @contextmanager              →  아래 함수를 컨텍스트 매니저로 만드는 데코레이터이다.\n"
            "  def tag(name):               →  HTML 태그처럼 여는/닫는 태그를 출력하는\n"
            "                                  컨텍스트 매니저이다.\n"
            "  print(f'<{name}>')           →  블록 진입 시 여는 태그를 출력한다(__enter__ 역할).\n"
            "  yield                        →  이 지점에서 with 블록 본문이 실행된다. yield\n"
            "                                  앞은 진입(준비), 뒤는 종료(정리)에 해당한다.\n"
            "  print(f'</{name}>')          →  블록 종료 시 닫는 태그를 출력한다(__exit__ 역할).\n"
            "  with tag('b'):               →  tag('b') 컨텍스트 매니저를 사용해 <b>를 출력하고\n"
            "                                  시작한다.\n"
            "  print('굵게')                →  블록 안에서 \"굵게\"를 출력하며, 이후 자동으로\n"
            "                                  </b>가 출력된다.\n"
            "\n"
            "[활용 목적]\n"
            "파일 작업 중 오류가 발생해도 자원을 항상 닫으려면 try/finally가 필요하다.\n"
            "with open('파일') as f: 를 사용하면 오류 발생 시에도 파일이 자동으로 닫히므로\n"
            "try/finally를 직접 작성할 필요가 없다.\n"
            "\n"
            "[유의 사항]\n"
            "• __exit__에서 return True를 하면 예외가 은폐된다. 실수로 오류를 무시하게 되는\n"
            "  함정이므로 주의해야 한다.\n"
            "• @contextmanager 사용 시 yield가 두 번 이상 있으면 오류가 발생한다. 반드시\n"
            "  정확히 한 번만 yield해야 한다."
        ),
        usage="파일·소켓·DB 연결·락 등 반드시 닫아야 하는 자원, 임시 상태 변경 후 원복할 때.",
        cons="__exit__ 의 반환값으로 예외를 삼킬 수 있어 실수하면 오류를 숨긴다. 남용하면 흐름이 가려진다.",
        code=(
            "from contextlib import contextmanager\n"
            "\n"
            "class Timer:\n"
            "    def __enter__(self):\n"
            "        print('시작')\n"
            "        return self\n"
            "    def __exit__(self, exc_type, exc, tb):\n"
            "        print('종료(정리)')\n"
            "        return False        # 예외를 삼키지 않음\n"
            "\n"
            "with Timer():\n"
            "    print('작업 중...')\n"
            "\n"
            "@contextmanager\n"
            "def tag(name):\n"
            "    print(f'<{name}>')\n"
            "    yield                  # 이 지점이 with 블록 본문\n"
            "    print(f'</{name}>')\n"
            "\n"
            "with tag('b'):\n"
            "    print('굵게')\n"
        ),
    ),

    Lesson(
        id="py-adv-04",
        lang="python", level="고급",
        title="itertools(조합/순열/product)",
        summary="조합·순열·곱집합을 효율적으로 생성",
        explanation=(
            "[개요]\n"
            "itertools는 순열, 조합, 곱집합 등 반복 가능한 경우의 수를 자동으로 생성하는\n"
            "표준 라이브러리이다. 중첩 for 문을 여러 개 작성하는 것보다 간결하고 오류가 적다.\n"
            "\n"
            "[핵심 개념]\n"
            "• 순열(Permutation): 순서가 있는 선택. AB와 BA를 서로 다른 경우로 본다.\n"
            "• 조합(Combination): 순서가 없는 선택. AB와 BA를 같은 경우로 본다.\n"
            "• 곱집합(Product): 두 집합의 모든 쌍을 생성한다.\n"
            "  예: {A,B} x {1,2} = (A,1), (A,2), (B,1), (B,2)\n"
            "\n"
            "[코드 분석]\n"
            "  from itertools import permutations, combinations, product\n"
            "                               →  itertools에서 세 함수를 가져온다.\n"
            "  nums = [1, 2, 3]             →  [1, 2, 3]을 nums에 저장한다.\n"
            "  list(permutations(nums, 2))  →  1, 2, 3 중 2개를 순서 있게 고르는 모든 경우이다.\n"
            "                                  (1,2), (1,3), (2,1), (2,3), (3,1), (3,2)로\n"
            "                                  총 3P2 = 6가지이다.\n"
            "  list(combinations(nums, 2))  →  1, 2, 3 중 2개를 순서 없이 고르는 모든 경우이다.\n"
            "                                  (1,2), (1,3), (2,3)로 총 3C2 = 3가지이다.\n"
            "  list(product([0,1], repeat=2)) →  [0,1]을 2번 반복한 곱집합이다.\n"
            "                                  00, 01, 10, 11의 2자리 이진수 4가지가 생성된다.\n"
            "  for a, b in product('AB', '12'):\n"
            "                               →  'AB'의 각 문자와 '12'의 각 문자의 모든 조합을\n"
            "                                  반복한다.\n"
            "  print(a + b, end=' ')        →  A1, A2, B1, B2 순서로 출력한다. end=' '는\n"
            "                                  줄바꿈 대신 공백으로 구분한다.\n"
            "\n"
            "[활용 목적]\n"
            "4개 중 3개를 고르는 모든 경우를 직접 구현하려면 3중 for 문과 중복 체크가 필요해\n"
            "복잡하다. combinations([1,2,3,4], 3) 한 줄로 대체할 수 있어 코드가 짧아지고\n"
            "오류가 줄어든다.\n"
            "\n"
            "[유의 사항]\n"
            "• 입력 크기가 커지면 경우의 수가 폭발적으로 증가한다. 10개의 순열은\n"
            "  10! = 3,628,800가지이며, n이 8~10을 초과하면 시간 초과를 의심해야 한다.\n"
            "• 결과를 list()로 한 번에 변환하면 전체 결과가 메모리에 적재된다. 결과가 많을\n"
            "  때는 for 문으로 하나씩 처리하는 것이 바람직하다."
        ),
        usage="완전탐색(브루트포스)에서 부분집합·순열·여러 칸 조합을 만들 때 직접 재귀 대신 사용한다.",
        cons="경우의 수가 폭발적으로 늘어나므로(n! 등) 큰 입력에선 시간초과. 결과를 list로 만들면 메모리 급증.",
        code=(
            "from itertools import permutations, combinations, product\n"
            "\n"
            "nums = [1, 2, 3]\n"
            "print(list(permutations(nums, 2)))   # 순열 nP2\n"
            "print(list(combinations(nums, 2)))   # 조합 nC2\n"
            "\n"
            "# 2자리 비밀번호 후보(00~11) 같은 곱집합\n"
            "print(list(product([0, 1], repeat=2)))\n"
            "\n"
            "# 중첩 for 문 대체\n"
            "for a, b in product('AB', '12'):\n"
            "    print(a + b, end=' ')   # A1 A2 B1 B2\n"
            "print()\n"
        ),
    ),

    Lesson(
        id="py-adv-05",
        lang="python", level="고급",
        title="heapq(우선순위 큐)",
        summary="최소 힙으로 최솟값을 O(log n)에 관리",
        explanation=(
            "[개요]\n"
            "heapq는 최소 힙(min-heap) 기반의 우선순위 큐를 제공하는 표준 라이브러리이다.\n"
            "가장 작은(우선순위가 높은) 값을 먼저 꺼내는 자료구조로, 트리 형태로 값을\n"
            "저장하며 항상 최솟값이 맨 위에 위치한다.\n"
            "\n"
            "[핵심 개념]\n"
            "• 힙(Heap)은 리스트 형태이지만, 항상 최솟값이 [0]번째 위치에 오도록 자동\n"
            "  정렬되는 특수한 리스트이다.\n"
            "• 삽입/삭제가 O(log n)으로 빠르며, 매번 전체 정렬(O(n log n))보다 효율적이다.\n"
            "\n"
            "[코드 분석]\n"
            "  import heapq                 →  heapq 모듈을 가져온다.\n"
            "  h = []                       →  빈 리스트를 힙으로 사용한다. heapq는 일반\n"
            "                                  리스트를 힙처럼 관리한다.\n"
            "  heapq.heappush(h, x)         →  값을 힙에 삽입한다. 삽입 시마다 최솟값이 h[0]에\n"
            "                                  오도록 자동 재배열된다.\n"
            "  heapq.heappop(h)             →  힙에서 최솟값을 꺼낸다. 꺼낸 후 다음 최솟값이\n"
            "                                  자동으로 h[0]으로 올라온다. 5,1,8,3 중 첫 pop은\n"
            "                                  1, 두 번째는 3이다.\n"
            "  data = [9, 2, 7, 4, 1]      →  기존 리스트를 힙으로 변환할 대상이다.\n"
            "  heapq.heapify(data)          →  data를 제자리에서 힙으로 재배열한다. 새 리스트를\n"
            "                                  생성하지 않고 O(n)으로 구성한다.\n"
            "  print(data[0])               →  힙의 맨 앞(최솟값)인 1을 출력한다. heapify 후에도\n"
            "                                  data는 리스트이나 힙 규칙을 따른다.\n"
            "  heapq.heappush(maxh, -x)    →  값에 -1을 곱해 삽입한다. -5,-1,-8,-3을 넣으면\n"
            "                                  -8이 가장 작아 맨 위에 온다.\n"
            "  -heapq.heappop(maxh)         →  -8을 꺼내고 -(-8) = 8을 출력한다. 부호를 반전해\n"
            "                                  최대 힙처럼 사용하는 기법이다.\n"
            "  pq = [(2,'낮음'),(0,'긴급'),(1,'보통')]\n"
            "                               →  (우선순위, 작업명) 튜플 리스트이다.\n"
            "  heapq.heapify(pq)            →  튜플의 첫 번째 값(숫자)을 기준으로 힙을 구성한다.\n"
            "  heapq.heappop(pq)            →  우선순위가 가장 작은(가장 급한) (0, '긴급')을\n"
            "                                  꺼낸다.\n"
            "\n"
            "[활용 목적]\n"
            "매번 전체 정렬(sort)은 O(n log n)이지만, 힙은 삽입/삭제가 O(log n)이다.\n"
            "다익스트라 알고리즘처럼 현재까지 가장 짧은 경로를 반복적으로 꺼내야 할 때\n"
            "훨씬 효율적이다.\n"
            "\n"
            "[유의 사항]\n"
            "• heapq는 최소 힙만 지원한다. 최대 힙이 필요하면 부호를 반전(-x)하는 기법을\n"
            "  사용해야 한다.\n"
            "• 힙에서 특정 원소를 탐색해 삭제하거나 수정할 수 없다. 이미 삽입된 값을 갱신하려면\n"
            "  별도의 무효 표시(lazy deletion) 기법을 사용해야 한다."
        ),
        usage="다익스트라 최단경로, 작업 스케줄링, '가장 작은/큰 K개', 실시간 중앙값 등.",
        cons="중간 임의 원소의 삭제·갱신이 직접 불가(보통 무효표시 기법 사용). 정렬 전체가 필요하면 sort가 낫다.",
        code=(
            "import heapq\n"
            "\n"
            "h = []\n"
            "for x in [5, 1, 8, 3]:\n"
            "    heapq.heappush(h, x)\n"
            "print(heapq.heappop(h))   # 1 (최솟값)\n"
            "print(heapq.heappop(h))   # 3\n"
            "\n"
            "data = [9, 2, 7, 4, 1]\n"
            "heapq.heapify(data)        # 제자리 힙 구성\n"
            "print(data[0])             # 1\n"
            "\n"
            "# 최대 힙: 부호 반전\n"
            "maxh = []\n"
            "for x in [5, 1, 8, 3]:\n"
            "    heapq.heappush(maxh, -x)\n"
            "print(-heapq.heappop(maxh))   # 8 (최댓값)\n"
            "\n"
            "# 우선순위 큐: (우선순위, 작업)\n"
            "pq = [(2, '낮음'), (0, '긴급'), (1, '보통')]\n"
            "heapq.heapify(pq)\n"
            "print(heapq.heappop(pq))   # (0, '긴급')\n"
        ),
    ),

    Lesson(
        id="py-adv-06",
        lang="python", level="고급",
        title="bisect(이분 탐색)",
        summary="정렬 리스트에서 위치를 O(log n)에 탐색",
        explanation=(
            "[개요]\n"
            "bisect는 이미 정렬된 리스트에서 이분 탐색으로 값의 삽입 위치를 O(log n)에\n"
            "찾아주는 표준 라이브러리이다. 탐색 범위를 절반씩 줄여가므로 1000개 원소도\n"
            "약 10회(log2(1000) ≈ 10) 비교로 위치를 찾는다.\n"
            "\n"
            "[핵심 개념]\n"
            "• bisect_left와 bisect_right는 같은 값이 여러 개일 때 차이가 발생한다.\n"
            "  [1, 3, 3, 3, 5]에서 3의 위치를 찾을 경우:\n"
            "  - bisect_left:  3들이 시작하는 위치(인덱스 1)를 반환한다.\n"
            "  - bisect_right: 3들이 끝난 다음 위치(인덱스 4)를 반환한다.\n"
            "• 두 값의 차이(right - left)로 특정 값의 개수를 O(log n)에 구할 수 있다.\n"
            "\n"
            "[코드 분석]\n"
            "  import bisect                →  bisect 모듈을 가져온다.\n"
            "  a = [1, 3, 3, 3, 5, 7]     →  정렬된 리스트이다. bisect는 반드시 정렬된\n"
            "                                  리스트에서만 사용해야 한다.\n"
            "  bisect.bisect_left(a, 3)    →  3이 들어갈 수 있는 가장 왼쪽 위치인 1을 반환한다.\n"
            "                                  인덱스 1에 3을 넣으면 왼쪽 3들의 앞이다.\n"
            "  bisect.bisect_right(a, 3)   →  3이 들어갈 수 있는 가장 오른쪽 위치인 4를 반환한다.\n"
            "                                  인덱스 4는 마지막 3의 바로 다음이다.\n"
            "  bisect_right - bisect_left  →  4 - 1 = 3이다. 리스트 안에 3이 3개 있음을\n"
            "                                  O(log n)으로 셀 수 있다.\n"
            "  bisect.insort(a, 4)          →  4를 정렬 순서를 유지하며 삽입하여\n"
            "                                  [1, 3, 3, 3, 4, 5, 7]이 된다.\n"
            "  print(a)                     →  4가 삽입된 [1, 3, 3, 3, 4, 5, 7]을 출력한다.\n"
            "  idx = bisect.bisect_left(a, 5)\n"
            "                               →  5 이상인 첫 번째 값의 인덱스를 찾는다.\n"
            "  print(a[idx])                →  해당 위치의 값인 5를 출력한다.\n"
            "\n"
            "[활용 목적]\n"
            "특정 값 이상인 첫 원소를 찾거나 특정 범위의 값 개수를 셀 때, 일반 for 문은\n"
            "O(n)이지만 bisect는 O(log n)이다. 데이터가 수십만 개일 때 성능 차이가 크다.\n"
            "\n"
            "[유의 사항]\n"
            "• 리스트가 정렬되어 있지 않으면 완전히 잘못된 결과가 나온다. 반드시 정렬 후\n"
            "  사용해야 한다.\n"
            "• insort의 삽입 위치 탐색은 O(log n)이지만, 실제 원소를 한 칸씩 밀어내는 작업은\n"
            "  O(n)이다. 삽입이 잦으면 느려질 수 있다."
        ),
        usage="정렬된 데이터에서 특정 값/범위 개수 세기, 좌표압축, LIS 길이(O(n log n)) 등에 쓴다.",
        cons="반드시 정렬 상태를 전제로 한다(아니면 틀린 결과). insort 삽입 자체는 원소 이동 때문에 O(n).",
        code=(
            "import bisect\n"
            "\n"
            "a = [1, 3, 3, 3, 5, 7]\n"
            "print(bisect.bisect_left(a, 3))    # 1\n"
            "print(bisect.bisect_right(a, 3))   # 4\n"
            "print(bisect.bisect_right(a, 3) - bisect.bisect_left(a, 3))  # 3의 개수 = 3\n"
            "\n"
            "# 정렬 유지 삽입\n"
            "bisect.insort(a, 4)\n"
            "print(a)   # [1, 3, 3, 3, 4, 5, 7]\n"
            "\n"
            "# x 이상인 첫 원소 찾기\n"
            "idx = bisect.bisect_left(a, 5)\n"
            "print(a[idx])   # 5\n"
        ),
    ),

    Lesson(
        id="py-adv-07",
        lang="python", level="고급",
        title="functools(lru_cache 메모이제이션, reduce)",
        summary="자동 캐싱과 누적 계산 도구",
        explanation=(
            "[개요]\n"
            "functools의 lru_cache는 함수 호출 결과를 자동으로 캐싱(메모이제이션)하는\n"
            "도구이며, reduce는 여러 값을 두 개씩 누적 결합해 하나로 축약하는 함수이다.\n"
            "\n"
            "[핵심 개념]\n"
            "• lru_cache: 함수 호출 결과를 자동으로 기억하고, 동일 인자로 다시 호출되면\n"
            "  재계산하지 않고 저장된 값을 즉시 반환한다.\n"
            "• reduce: 왼쪽부터 두 값씩 결합해 나간다. 예를 들어 [1, 2, 3, 4, 5]의 곱은\n"
            "  ((((1x2)x3)x4)x5) = 120으로 계산된다.\n"
            "\n"
            "[코드 분석]\n"
            "  from functools import lru_cache, reduce\n"
            "                               →  functools에서 lru_cache와 reduce를 가져온다.\n"
            "  from math import gcd         →  최대공약수를 구하는 gcd 함수를 가져온다.\n"
            "  @lru_cache(maxsize=None)     →  아래 fib 함수에 자동 캐시를 부착한다.\n"
            "                                  maxsize=None은 캐시 크기 제한 없이 모든 결과를\n"
            "                                  기억하라는 의미이다.\n"
            "  def fib(n):                  →  피보나치 수를 구하는 재귀 함수이다.\n"
            "  if n < 2: return n           →  n이 0이면 0, 1이면 1을 반환한다(피보나치 시작값).\n"
            "  return fib(n-1) + fib(n-2)  →  fib(30)은 fib(29)와 fib(28)이 필요하고, fib(29)는\n"
            "                                  fib(28)과 fib(27)이 필요하다. 캐시가 없으면\n"
            "                                  fib(28)이 수십 번 중복 계산되나, lru_cache로\n"
            "                                  각 n은 한 번만 계산된다.\n"
            "  print(fib(30))               →  832040을 거의 즉시 출력한다. 캐시가 없으면\n"
            "                                  2^30 = 약 10억 번 이상 계산해야 한다.\n"
            "  print(fib.cache_info())      →  캐시 적중(hits)과 미스(misses) 횟수를 출력한다.\n"
            "                                  fib(30)에서 hits가 수십 회임을 확인할 수 있다.\n"
            "  reduce(lambda acc, x: acc*x, range(1,6), 1)\n"
            "                               →  1부터 5까지의 곱(5! = 120)을 계산한다.\n"
            "                                  lambda acc, x: acc * x는 누적값(acc)에 x를\n"
            "                                  곱하라는 의미이며, 세 번째 인자 1은 초기값이다.\n"
            "  reduce(gcd, [24, 36, 60])    →  24와 36의 최대공약수(12)를 구한 뒤, 그 12와\n"
            "                                  60의 최대공약수(12)를 구한다. 세 수의\n"
            "                                  최대공약수인 12가 결과이다.\n"
            "\n"
            "[활용 목적]\n"
            "재귀로 구현한 DP(동적 프로그래밍)는 동일한 계산을 다수 반복한다. lru_cache 한\n"
            "줄만 추가하면 자동으로 메모이제이션이 적용되어 O(2^n)이 O(n)으로 감소한다.\n"
            "\n"
            "[유의 사항]\n"
            "• lru_cache의 인자는 해시 가능한(불변) 값이어야 한다. 리스트를 인자로 전달하면\n"
            "  오류가 발생하므로 튜플로 변환해 전달해야 한다.\n"
            "• 캐시는 메모리를 점유한다. 다양한 인자 조합으로 장시간 실행하면 메모리 부족이\n"
            "  발생할 수 있다."
        ),
        usage="피보나치·조합수 같은 겹치는 부분문제 재귀 DP 가속, 순수 함수의 반복 호출 결과 재사용.",
        cons="인자는 해시 가능(불변)해야 캐싱된다. 캐시가 메모리를 계속 점유하고, 부수효과 함수엔 위험.",
        code=(
            "from functools import lru_cache, reduce\n"
            "from math import gcd\n"
            "\n"
            "@lru_cache(maxsize=None)\n"
            "def fib(n):\n"
            "    if n < 2:\n"
            "        return n\n"
            "    return fib(n - 1) + fib(n - 2)\n"
            "\n"
            "print(fib(30))            # 832040 (캐시 덕분에 즉시)\n"
            "print(fib.cache_info())   # hits/misses 확인\n"
            "\n"
            "# reduce: 1*2*...*5 = 120\n"
            "print(reduce(lambda acc, x: acc * x, range(1, 6), 1))\n"
            "\n"
            "# reduce + gcd: 여러 수의 최대공약수\n"
            "print(reduce(gcd, [24, 36, 60]))   # 12\n"
        ),
    ),

    Lesson(
        id="py-adv-08",
        lang="python", level="고급",
        title="sys.stdin 빠른 입출력과 재귀한도",
        summary="대량 입력 가속과 setrecursionlimit",
        explanation=(
            "[개요]\n"
            "sys.stdin을 이용한 빠른 입출력과 sys.setrecursionlimit을 통한 재귀 한도 조정은\n"
            "대량 입력 및 깊은 재귀를 다루는 코딩테스트에서 필수적인 기법이다.\n"
            "\n"
            "[핵심 개념]\n"
            "• 빠른 입출력: 기본 input() 함수는 편리하나 느리다. 입력이 10만 줄일 경우\n"
            "  input()을 10만 번 호출하면 상당한 시간이 소요된다. sys.stdin을 사용하면\n"
            "  입력을 훨씬 빠르게 처리할 수 있다.\n"
            "• 재귀 한도: Python은 함수 호출 깊이(재귀 깊이)에 기본 제한(약 1000)이 있다.\n"
            "  DFS로 깊이 1000을 초과하는 그래프를 탐색하면 RecursionError가 발생한다.\n"
            "  sys.setrecursionlimit()으로 이 한도를 상향할 수 있다.\n"
            "\n"
            "[코드 분석]\n"
            "  import sys, io               →  sys(시스템 기능)와 io(입출력 기능) 모듈을 가져온다.\n"
            "  sample = '3\\n10 20\\n...'   →  실제 채점 환경에서는 키보드 입력이 들어오나, 여기서는\n"
            "                                  연습을 위해 입력값을 문자열로 직접 구성한다.\n"
            "                                  \\n은 줄바꿈을 의미한다.\n"
            "  sys.stdin = io.StringIO(sample)\n"
            "                               →  sys.stdin(표준 입력)을 sample 문자열로 대체한다.\n"
            "                                  이제 readline()이 sample을 읽는다.\n"
            "  input = sys.stdin.readline   →  input이라는 이름을 sys.stdin.readline 함수로\n"
            "                                  대체한다. 이후 input() 호출 시 한 줄을 빠르게\n"
            "                                  읽는다. 단, 줄 끝에 '\\n'이 포함되어 오므로 주의한다.\n"
            "  n = int(input())             →  첫 번째 줄 \"3\"을 읽어 정수 3으로 변환한다.\n"
            "  out = []                     →  결과를 모을 빈 리스트이다. print()를 반복하는 대신\n"
            "                                  리스트에 모아 한 번에 출력하면 훨씬 빠르다.\n"
            "  for _ in range(n):           →  n(=3)번 반복한다.\n"
            "  a, b = map(int, input().split())\n"
            "                               →  한 줄을 읽어 공백으로 분리한 뒤 각각 정수로 변환한다.\n"
            "                                  \"10 20\"을 읽으면 a=10, b=20이 된다.\n"
            "  out.append(str(a + b))       →  a+b 결과를 문자열로 변환해 out 리스트에 추가한다.\n"
            "  sys.stdout.write('\\n'.join(out) + '\\n')\n"
            "                               →  out 리스트의 모든 값을 줄바꿈으로 연결해 한 번에\n"
            "                                  출력한다. print()를 3번 호출하는 것보다 빠르며,\n"
            "                                  \"30\\n70\\n110\"이 출력된다.\n"
            "  sys.setrecursionlimit(10**6) →  재귀 허용 깊이를 100만으로 상향한다. 깊은 DFS\n"
            "                                  사용 시 RecursionError를 예방한다.\n"
            "  def depth(k):                →  k번 재귀 호출하는 테스트 함수이다.\n"
            "  if k == 0: return 0          →  재귀의 종료 조건(기저 조건)이다.\n"
            "  return 1 + depth(k - 1)     →  자기 자신을 k-1로 호출하는 재귀이다.\n"
            "  print(depth(2000))           →  기본 한도(약 1000)에서는 RecursionError가 나지만,\n"
            "                                  한도를 100만으로 상향했으므로 2000을 정상 출력한다.\n"
            "\n"
            "[활용 목적]\n"
            "코딩테스트에서 시간 초과(TLE)의 원인이 알고리즘이 아닌 느린 입출력인 경우가 있다.\n"
            "특히 입력이 10만 줄 이상인 문제에서는 sys.stdin.readline 사용만으로 통과 여부가\n"
            "갈릴 수 있다.\n"
            "\n"
            "[유의 사항]\n"
            "• sys.stdin.readline()으로 읽으면 줄 끝에 '\\n'이 포함된다. int() 변환 시에는\n"
            "  문제없으나, 문자열을 직접 사용할 때는 .strip()으로 제거해야 한다.\n"
            "• setrecursionlimit을 과도하게(100만 이상) 상향하면 메모리 부족으로 인터프리터\n"
            "  자체가 종료될 수 있다. 10^6 정도가 적정하다."
        ),
        usage="입력 줄 수가 수만~수십만인 백준 문제, 깊은 재귀 DFS/분할정복에서 필수.",
        cons="setrecursionlimit 을 너무 키우면 스택 초과로 인터프리터가 죽을 수 있다. readline 은 개행 처리 주의.",
        code=(
            "import sys, io\n"
            "\n"
            "# 데모: 실제 표준입력 대신 고정 데이터를 sys.stdin 에 주입\n"
            "sample = '3\\n10 20\\n30 40\\n50 60\\n'\n"
            "sys.stdin = io.StringIO(sample)\n"
            "\n"
            "input = sys.stdin.readline      # 빠른 입력\n"
            "n = int(input())\n"
            "out = []\n"
            "for _ in range(n):\n"
            "    a, b = map(int, input().split())\n"
            "    out.append(str(a + b))\n"
            "sys.stdout.write('\\n'.join(out) + '\\n')   # 한 번에 출력 → 30 70 110\n"
            "\n"
            "# 깊은 재귀를 위해 한도 상향\n"
            "sys.setrecursionlimit(10**6)\n"
            "\n"
            "def depth(k):\n"
            "    if k == 0:\n"
            "        return 0\n"
            "    return 1 + depth(k - 1)\n"
            "\n"
            "print(depth(2000))   # 기본 한도였다면 에러, 상향 후 2000\n"
        ),
    ),
]
