"""Python 고급 문법 (제너레이터·데코레이터·컨텍스트 매니저·itertools·heapq·bisect·functools·빠른 입출력)."""

from engine.models import Lesson

LESSONS = [

    Lesson(
        id="py-adv-01",
        lang="python", level="고급",
        title="제너레이터와 이터레이터(yield)",
        summary="yield 로 값을 하나씩 지연 생성",
        explanation=(
            "━━ 제너레이터(Generator) 이란? ━━\n"
            "\n"
            "비유: 일반 함수(return)는 음식점에서 주문을 받자마자 요리를 전부 만들어\n"
            "한 번에 접시에 담아 내오는 것과 같아요.\n"
            "반면, 제너레이터(yield)는 셰프가 손님이 \"다음 음식 주세요\"라고 요청할 때마다\n"
            "한 접시씩 만들어 내오는 방식이에요.\n"
            "음식(값)이 필요할 때만 만들기 때문에 재료(메모리)를 절약할 수 있어요.\n"
            "\n"
            "이터레이터가 무엇인가요?\n"
            "이터레이터는 \"다음 값을 하나씩 꺼낼 수 있는 객체\"예요.\n"
            "next()를 호출하면 다음 값을 하나 꺼내주고,\n"
            "더 이상 값이 없으면 StopIteration 오류를 내요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  def countdown(n):       →  n부터 1까지 거꾸로 세는 제너레이터 함수예요.\n"
            "                             함수 안에 yield가 있으면 호출해도 바로 실행되지 않고\n"
            "                             제너레이터 객체를 돌려줘요.\n"
            "  while n > 0:            →  n이 0보다 큰 동안 반복해요.\n"
            "  yield n                 →  n 값을 밖으로 내보내고 이 자리에서 잠깐 멈춰요.\n"
            "                             next()가 호출될 때까지 기다리며, 함수가 끝나지 않고\n"
            "                             n의 현재 값을 그대로 기억해요.\n"
            "  n -= 1                  →  yield 이후 다시 next()가 호출되면 이어서 실행해요.\n"
            "                             n을 1 줄여요.\n"
            "  def fib(k):             →  피보나치 수열을 k개 만들어내는 제너레이터예요.\n"
            "  a, b = 0, 1             →  피보나치의 첫 두 값인 0과 1로 시작해요.\n"
            "  for _ in range(k):      →  k번 반복해요.\n"
            "  yield a                 →  현재 피보나치 수 a를 내보내고 멈춰요.\n"
            "  a, b = b, a + b         →  다음 피보나치 수를 계산해요.\n"
            "                             a를 b로, b를 a+b로 동시에 바꿔요.\n"
            "  gen = countdown(3)      →  countdown(3)을 호출해도 함수가 실행되지 않아요.\n"
            "                             제너레이터 객체만 만들어서 gen에 저장해요.\n"
            "                             아직 아무 숫자도 만들지 않았어요.\n"
            "  next(gen), next(gen)    →  next(gen)을 처음 호출하면 yield n 까지 실행해서\n"
            "                             3을 내보내요. 두 번째 호출에서 n -= 1 후 다시\n"
            "                             yield n 에서 2를 내보내요. 그래서 3 2 가 출력돼요.\n"
            "  list(countdown(5))      →  countdown(5)의 모든 값을 한 번에 리스트로 만들어요.\n"
            "                             [5, 4, 3, 2, 1]이 돼요.\n"
            "  list(fib(8))            →  피보나치 수 8개를 리스트로 만들어요.\n"
            "                             [0, 1, 1, 2, 3, 5, 8, 13]이 돼요.\n"
            "  sum(x*x for x in ...)  →  x*x for x in range(1,6)이 제너레이터 표현식이에요.\n"
            "                             1+4+9+16+25=55를 리스트 없이 바로 합계 내요.\n"
            "\n"
            "왜(Why) 제너레이터를 쓰나요?\n"
            "파일 100만 줄을 읽어야 할 때, 리스트로 만들면 100만 줄이 전부 메모리에 올라가요.\n"
            "제너레이터는 한 줄씩 꺼내서 처리하고 버리기 때문에 메모리가 거의 안 들어요.\n"
            "\n"
            "주의할 점:\n"
            "  - 제너레이터는 딱 한 번만 쓸 수 있어요. 한 번 끝까지 다 꺼내면\n"
            "    다시 처음부터 못 써요. 다시 쓰려면 새로 만들어야 해요.\n"
            "  - len(gen) 처럼 길이를 구하거나 gen[0] 처럼 인덱스로 접근할 수 없어요."
        ),
        usage="대용량 데이터를 한 줄씩 흘려보낼 때, 무한 수열, 파이프라인 처리에 메모리 절약용으로 쓴다.",
        cons="한 번 소비하면 다시 못 돌린다(재사용하려면 다시 생성). 길이(len)나 인덱싱이 불가능하다.",
        code=(
            "def countdown(n):\n"
            "    while n > 0:\n"
            "        yield n          # 여기서 값을 내보내고 멈춘다\n"
            "        n -= 1\n"
            "\n"
            "def fib(k):\n"
            "    a, b = 0, 1\n"
            "    for _ in range(k):\n"
            "        yield a\n"
            "        a, b = b, a + b\n"
            "\n"
            "gen = countdown(3)\n"
            "print(next(gen), next(gen))   # 3 2\n"
            "print(list(countdown(5)))     # [5, 4, 3, 2, 1]\n"
            "print(list(fib(8)))           # [0, 1, 1, 2, 3, 5, 8, 13]\n"
            "\n"
            "# 제너레이터 표현식: 리스트를 만들지 않고 합계만 계산(메모리 절약)\n"
            "print(sum(x * x for x in range(1, 6)))   # 55\n"
        ),
    ),

    Lesson(
        id="py-adv-02",
        lang="python", level="고급",
        title="데코레이터",
        summary="함수를 감싸 기능을 덧붙이는 @문법",
        explanation=(
            "━━ 데코레이터(Decorator) 이란? ━━\n"
            "\n"
            "비유: 데코레이터는 선물 포장지와 같아요.\n"
            "선물(원래 함수) 자체는 그대로인데, 포장지(데코레이터)를 씌우면\n"
            "기능이 추가돼요. 예를 들어 함수를 호출할 때마다 자동으로 로그를 남기고 싶다면,\n"
            "함수마다 로그 코드를 넣는 대신 데코레이터 포장지 하나를 만들어 씌우면 돼요.\n"
            "\n"
            "핵심 아이디어:\n"
            "Python에서 함수는 값처럼 다른 함수에 전달할 수 있어요.\n"
            "데코레이터는 \"함수를 받아서 기능을 추가한 새 함수를 돌려주는 함수\"예요.\n"
            "@logged 한 줄은 add = logged(add) 와 완전히 동일해요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  import functools             →  functools 모듈을 가져와요.\n"
            "                                 여기서 wraps를 쓸 거예요.\n"
            "  def logged(func):            →  logged라는 데코레이터 함수를 만들어요.\n"
            "                                 func 자리에 꾸며줄 원래 함수가 들어와요.\n"
            "  @functools.wraps(func)       →  wrapper 함수가 원래 func의 이름·설명을\n"
            "                                 그대로 물려받게 해요. 이게 없으면\n"
            "                                 add.__name__이 \"wrapper\"로 바뀌어서\n"
            "                                 디버깅이 어려워져요.\n"
            "  def wrapper(*args, **kwargs): →  실제로 add(3, 4)를 호출하면 이 wrapper\n"
            "                                 함수가 대신 실행돼요. *args는 위치 인자 전부,\n"
            "                                 **kwargs는 키워드 인자 전부를 받아서\n"
            "                                 원래 함수에 그대로 넘겨줘요.\n"
            "  print(f'호출: ...')           →  원래 함수가 실행되기 전에\n"
            "                                 어떤 함수가 어떤 인자로 호출됐는지 출력해요.\n"
            "  result = func(*args, **kwargs) →  원래 함수(add)를 받은 인자로 실행하고\n"
            "                                 결과를 result에 저장해요.\n"
            "  print(f'결과: {result}')      →  원래 함수 실행 후 결과를 출력해요.\n"
            "  return result                →  원래 함수의 반환값을 그대로 돌려줘요.\n"
            "                                 이걸 빠뜨리면 add(3, 4)가 None이 돼요.\n"
            "  return wrapper               →  wrapper 함수 자체를 돌려줘요.\n"
            "                                 logged(add)를 호출하면 wrapper가 돌아와요.\n"
            "  @logged                      →  이 한 줄은 add = logged(add)와 똑같아요.\n"
            "                                 이후 add를 호출하면 실제로는 wrapper가 실행돼요.\n"
            "  def add(a, b): return a+b   →  두 숫자를 더하는 원래 함수예요.\n"
            "  print(add(3, 4))             →  \"호출: add(3, 4)\", \"결과: 7\", \"7\"\n"
            "                                 순서로 출력돼요.\n"
            "  print(add.__name__)          →  functools.wraps 덕분에 \"wrapper\"가 아닌\n"
            "                                 \"add\"가 출력돼요.\n"
            "\n"
            "왜(Why) 데코레이터를 쓰나요?\n"
            "함수가 100개 있는데 모두 실행시간을 측정하고 싶다면,\n"
            "100개 함수에 같은 코드를 붙이는 대신 데코레이터 하나만 만들어 @timer 로 붙이면 돼요.\n"
            "코드 중복 없이 공통 기능을 여러 함수에 추가할 수 있어요.\n"
            "\n"
            "주의할 점:\n"
            "  - functools.wraps를 빠뜨리면 add.__name__이 \"wrapper\"가 되어\n"
            "    디버깅 때 혼란스러워요. 항상 붙이는 습관을 들이세요.\n"
            "  - 데코레이터를 여러 개 겹치면 바깥쪽부터 씌워지고 안쪽부터 실행돼요.\n"
            "    순서가 중요해요."
        ),
        usage="로깅, 실행시간 측정, 캐싱, 재시도, 접근 제어 등 여러 함수에 공통으로 끼워 넣을 때.",
        cons="중첩이 많으면 스택 추적이 복잡해지고 디버깅이 어렵다. 과용하면 흐름 파악이 힘들다.",
        code=(
            "import functools\n"
            "\n"
            "def logged(func):\n"
            "    @functools.wraps(func)\n"
            "    def wrapper(*args, **kwargs):\n"
            "        print(f'호출: {func.__name__}{args}')\n"
            "        result = func(*args, **kwargs)\n"
            "        print(f'결과: {result}')\n"
            "        return result\n"
            "    return wrapper\n"
            "\n"
            "@logged\n"
            "def add(a, b):\n"
            "    return a + b\n"
            "\n"
            "print(add(3, 4))\n"
            "print(add.__name__)   # wraps 덕분에 'add' 가 그대로 보인다\n"
        ),
    ),

    Lesson(
        id="py-adv-03",
        lang="python", level="고급",
        title="컨텍스트 매니저(with)",
        summary="자원 획득/해제를 자동으로 보장",
        explanation=(
            "━━ 컨텍스트 매니저(Context Manager) 이란? ━━\n"
            "\n"
            "비유: 도서관에서 책을 빌릴 때를 생각해보세요.\n"
            "책을 빌리면(진입), 책을 읽고(작업), 반드시 반납해야 해요(종료).\n"
            "중간에 급하게 집에 가야 해도, 책은 반납 절차가 필요해요.\n"
            "with 문은 바로 이런 \"반드시 정리해야 하는 작업\"을 보장해줘요.\n"
            "파일을 열면 반드시 닫고, 락을 잡으면 반드시 해제하고,\n"
            "연결을 맺으면 반드시 끊어줘요. 중간에 오류가 나도요.\n"
            "\n"
            "__enter__ 와 __exit__ 가 뭔가요?\n"
            "with 블록에 들어갈 때 __enter__ 가 자동으로 호출되고,\n"
            "블록에서 나올 때(정상이든 오류든) __exit__ 가 반드시 호출돼요.\n"
            "이 두 메서드를 가진 객체를 컨텍스트 매니저라고 불러요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  from contextlib import contextmanager\n"
            "                               →  contextmanager 데코레이터를 가져와요.\n"
            "                                  이걸 쓰면 클래스 없이 제너레이터 함수 하나로\n"
            "                                  컨텍스트 매니저를 만들 수 있어요.\n"
            "  class Timer:                 →  Timer라는 컨텍스트 매니저 클래스를 만들어요.\n"
            "  def __enter__(self):         →  with Timer(): 블록에 진입할 때 자동으로 호출돼요.\n"
            "                                  \"준비 작업\"을 여기에 써요.\n"
            "  print('시작')                →  블록 진입 시 \"시작\"을 출력해요.\n"
            "  return self                  →  as 키워드로 받을 수 있는 객체를 돌려줘요.\n"
            "                                  with Timer() as t: 하면 t 가 self 가 돼요.\n"
            "  def __exit__(self, exc_type, exc, tb):\n"
            "                               →  with 블록이 끝날 때 항상 호출돼요.\n"
            "                                  예외가 났으면 exc_type, exc, tb에\n"
            "                                  오류 정보가 들어와요.\n"
            "  print('종료(정리)')           →  블록이 끝날 때 \"종료(정리)\"를 출력해요.\n"
            "  return False                 →  False를 돌려주면 예외가 있을 때 그대로\n"
            "                                  위로 전달해요. True를 돌려주면 예외를 삼켜서\n"
            "                                  오류가 없는 것처럼 돼요. 보통 False가 안전해요.\n"
            "  with Timer():                →  Timer 객체를 만들고 __enter__ 를 호출해요.\n"
            "  print('작업 중...')           →  with 블록 안의 코드예요. 블록을 나가면\n"
            "                                  자동으로 __exit__ 가 호출돼요.\n"
            "  @contextmanager              →  아래 함수를 컨텍스트 매니저로 만드는 데코레이터예요.\n"
            "  def tag(name):               →  HTML 태그처럼 여는/닫는 태그를 출력하는\n"
            "                                  컨텍스트 매니저예요.\n"
            "  print(f'<{name}>')           →  with 블록에 진입할 때 여는 태그를 출력해요.\n"
            "                                  (= __enter__ 역할)\n"
            "  yield                        →  이 지점에서 with 블록 안의 코드가 실행돼요.\n"
            "                                  yield 앞이 준비(진입), 뒤가 정리(종료)예요.\n"
            "  print(f'</{name}>')          →  with 블록이 끝나면 닫는 태그를 출력해요.\n"
            "                                  (= __exit__ 역할)\n"
            "  with tag('b'):               →  tag('b') 컨텍스트 매니저를 써서 <b>를\n"
            "                                  출력하고 시작해요.\n"
            "  print('굵게')                →  with 블록 안에서 \"굵게\"를 출력해요.\n"
            "                                  이후 자동으로 </b>가 출력돼요.\n"
            "\n"
            "왜(Why) 컨텍스트 매니저를 쓰나요?\n"
            "파일을 열고 작업하다가 오류가 나면, try/finally로 항상 닫아줘야 해요.\n"
            "with open('파일') as f: 를 쓰면 오류가 나도 파일이 자동으로 닫혀서\n"
            "try/finally를 직접 쓸 필요가 없어요.\n"
            "\n"
            "주의할 점:\n"
            "  - __exit__에서 return True 를 하면 예외가 숨겨져요.\n"
            "    실수로 오류를 무시하게 되는 함정이에요.\n"
            "  - @contextmanager를 쓸 때 yield가 두 번 이상 있으면 오류가 나요.\n"
            "    반드시 정확히 한 번만 yield 해야 해요."
        ),
        usage="파일·소켓·DB 연결·락 등 반드시 닫아야 하는 자원, 임시 상태 변경 후 원복할 때.",
        cons="__exit__ 의 반환값으로 예외를 삼킬 수 있어 실수하면 오류를 숨긴다. 남용하면 흐름이 가려진다.",
        code=(
            "from contextlib import contextmanager\n"
            "\n"
            "class Timer:\n"
            "    def __enter__(self):\n"
            "        print('시작')\n"
            "        return self\n"
            "    def __exit__(self, exc_type, exc, tb):\n"
            "        print('종료(정리)')\n"
            "        return False        # 예외를 삼키지 않음\n"
            "\n"
            "with Timer():\n"
            "    print('작업 중...')\n"
            "\n"
            "@contextmanager\n"
            "def tag(name):\n"
            "    print(f'<{name}>')\n"
            "    yield                  # 이 지점이 with 블록 본문\n"
            "    print(f'</{name}>')\n"
            "\n"
            "with tag('b'):\n"
            "    print('굵게')\n"
        ),
    ),

    Lesson(
        id="py-adv-04",
        lang="python", level="고급",
        title="itertools(조합/순열/product)",
        summary="조합·순열·곱집합을 효율적으로 생성",
        explanation=(
            "━━ itertools 이란? ━━\n"
            "\n"
            "비유: 메뉴판에서 점심 메뉴 2개를 고르는 경우를 생각해보세요.\n"
            "\"순열\"은 햄버거+피자와 피자+햄버거를 다른 것으로 봐요(순서가 중요).\n"
            "\"조합\"은 둘을 같은 것으로 봐요(순서가 없음).\n"
            "itertools는 이런 모든 경우를 자동으로 만들어주는 도구 상자예요.\n"
            "직접 중첩 for 문을 여러 개 쓰는 것보다 훨씬 간단하고 실수도 줄어요.\n"
            "\n"
            "세 가지 핵심 개념:\n"
            "  순열(Permutation): 순서가 있는 선택. AB와 BA는 다른 경우예요.\n"
            "  조합(Combination): 순서가 없는 선택. AB와 BA는 같은 경우예요.\n"
            "  곱집합(Product):   두 집합의 모든 쌍을 만들어요.\n"
            "                     {A,B} x {1,2} = (A,1), (A,2), (B,1), (B,2)\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  from itertools import permutations, combinations, product\n"
            "                               →  itertools에서 세 가지 함수를 가져와요.\n"
            "  nums = [1, 2, 3]             →  [1, 2, 3]을 nums에 저장해요.\n"
            "  list(permutations(nums, 2))  →  1, 2, 3 중 2개를 순서 있게 고르는 모든 경우예요.\n"
            "                                  (1,2), (1,3), (2,1), (2,3), (3,1), (3,2)\n"
            "                                  총 3P2 = 6가지가 나와요.\n"
            "  list(combinations(nums, 2))  →  1, 2, 3 중 2개를 순서 없이 고르는 모든 경우예요.\n"
            "                                  (1,2), (1,3), (2,3) 총 3C2 = 3가지예요.\n"
            "  list(product([0,1], repeat=2)) →  [0,1]을 2번 반복해서 곱집합을 만들어요.\n"
            "                                  00, 01, 10, 11 처럼 2자리 이진수 4가지가 나와요.\n"
            "  for a, b in product('AB', '12'):\n"
            "                               →  'AB'의 각 문자와 '12'의 각 문자의\n"
            "                                  모든 조합을 반복해요.\n"
            "  print(a + b, end=' ')        →  A1, A2, B1, B2 순서로 출력해요.\n"
            "                                  end=' ' 는 줄바꿈 대신 공백으로 구분해요.\n"
            "\n"
            "왜(Why) itertools를 쓰나요?\n"
            "4개 중 3개를 고르는 모든 경우를 직접 짜려면\n"
            "3중 for 문에 중복 체크까지 복잡해요.\n"
            "combinations([1,2,3,4], 3) 한 줄이면 끝이에요.\n"
            "코드가 짧아지고 실수도 줄어요.\n"
            "\n"
            "주의할 점:\n"
            "  - 입력 크기가 크면 경우의 수가 폭발적으로 늘어나요.\n"
            "    10개 중 10개 순열은 10! = 3,628,800가지예요.\n"
            "    n이 8~10을 넘어가면 시간초과를 의심해야 해요.\n"
            "  - 결과를 list()로 한 번에 변환하면 모든 결과가 메모리에 올라가요.\n"
            "    결과가 많을 때는 for 문으로 하나씩 처리하는 게 좋아요."
        ),
        usage="완전탐색(브루트포스)에서 부분집합·순열·여러 칸 조합을 만들 때 직접 재귀 대신 사용한다.",
        cons="경우의 수가 폭발적으로 늘어나므로(n! 등) 큰 입력에선 시간초과. 결과를 list로 만들면 메모리 급증.",
        code=(
            "from itertools import permutations, combinations, product\n"
            "\n"
            "nums = [1, 2, 3]\n"
            "print(list(permutations(nums, 2)))   # 순열 nP2\n"
            "print(list(combinations(nums, 2)))   # 조합 nC2\n"
            "\n"
            "# 2자리 비밀번호 후보(00~11) 같은 곱집합\n"
            "print(list(product([0, 1], repeat=2)))\n"
            "\n"
            "# 중첩 for 문 대체\n"
            "for a, b in product('AB', '12'):\n"
            "    print(a + b, end=' ')   # A1 A2 B1 B2\n"
            "print()\n"
        ),
    ),

    Lesson(
        id="py-adv-05",
        lang="python", level="고급",
        title="heapq(우선순위 큐)",
        summary="최소 힙으로 최솟값을 O(log n)에 관리",
        explanation=(
            "━━ heapq(힙 / 우선순위 큐) 이란? ━━\n"
            "\n"
            "비유: 병원 응급실을 생각해보세요.\n"
            "환자가 도착한 순서대로 치료하는 게 아니라, 가장 위급한 환자부터 먼저 치료해요.\n"
            "이게 우선순위 큐예요.\n"
            "heapq는 이런 \"가장 작은(= 우선순위가 높은) 것부터 꺼내는\" 자료구조예요.\n"
            "나무(트리) 모양으로 값을 저장하는데, 항상 가장 작은 값이 맨 위에 있어요.\n"
            "\n"
            "힙(Heap)이 뭔가요?\n"
            "힙은 리스트처럼 생겼지만, 항상 가장 작은 값이 [0]번째 위치에 있도록\n"
            "자동으로 정렬되는 특별한 리스트예요.\n"
            "삽입/삭제가 O(log n)으로 빠르고, 매번 전체 정렬(O(n log n))보다 효율적이에요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  import heapq                 →  heapq 모듈을 가져와요.\n"
            "  h = []                       →  빈 리스트를 힙으로 쓸 거예요.\n"
            "                                  heapq는 일반 리스트를 힙처럼 관리해요.\n"
            "  heapq.heappush(h, x)         →  값을 힙에 넣어요.\n"
            "                                  넣을 때마다 가장 작은 값이 h[0]에 오도록\n"
            "                                  자동으로 재배열돼요.\n"
            "  heapq.heappop(h)             →  힙에서 가장 작은 값을 꺼내요.\n"
            "                                  꺼내면 자동으로 다음 최솟값이 h[0]으로 올라와요.\n"
            "                                  5,1,8,3 중 첫 pop은 1, 두 번째는 3이에요.\n"
            "  data = [9, 2, 7, 4, 1]      →  기존 리스트를 힙으로 바꿀 거예요.\n"
            "  heapq.heapify(data)          →  data를 제자리에서 힙으로 재배열해요.\n"
            "                                  리스트를 새로 만들지 않고 O(n)으로 구성해요.\n"
            "  print(data[0])               →  힙의 맨 앞(최솟값)인 1을 출력해요.\n"
            "                                  heapify 후에도 data는 리스트지만 힙 규칙을 따라요.\n"
            "  heapq.heappush(maxh, -x)    →  값에 -1을 곱해서 넣어요.\n"
            "                                  -5,-1,-8,-3을 넣으면 -8이 가장 작아서 맨 위에 와요.\n"
            "  -heapq.heappop(maxh)         →  -8을 꺼내고 -(-8) = 8을 출력해요.\n"
            "                                  부호를 반전해서 최대 힙처럼 쓰는 트릭이에요.\n"
            "  pq = [(2,'낮음'),(0,'긴급'),(1,'보통')]\n"
            "                               →  (우선순위, 작업명) 튜플 리스트예요.\n"
            "  heapq.heapify(pq)            →  튜플의 첫 번째 값(숫자)을 기준으로 힙을 구성해요.\n"
            "  heapq.heappop(pq)            →  우선순위 0으로 가장 작은(= 가장 급한)\n"
            "                                  (0, '긴급')을 꺼내요.\n"
            "\n"
            "왜(Why) heapq를 쓰나요?\n"
            "매번 전체 정렬(sort)을 하면 O(n log n)이지만,\n"
            "힙을 쓰면 추가/삭제가 O(log n)이에요.\n"
            "다익스트라 알고리즘처럼 \"지금까지 가장 짧은 경로\"를\n"
            "반복해서 꺼내야 할 때 훨씬 빨라요.\n"
            "\n"
            "주의할 점:\n"
            "  - heapq는 최소 힙만 지원해요. 최대 힙이 필요하면\n"
            "    부호를 반전(-x)하는 트릭을 써야 해요.\n"
            "  - 힙에서 특정 원소를 찾아서 지우거나 수정할 수 없어요.\n"
            "    이미 들어간 값을 갱신하고 싶을 때는 \"무효 표시\" 기법을 따로 써야 해요."
        ),
        usage="다익스트라 최단경로, 작업 스케줄링, '가장 작은/큰 K개', 실시간 중앙값 등.",
        cons="중간 임의 원소의 삭제·갱신이 직접 불가(보통 무효표시 기법 사용). 정렬 전체가 필요하면 sort가 낫다.",
        code=(
            "import heapq\n"
            "\n"
            "h = []\n"
            "for x in [5, 1, 8, 3]:\n"
            "    heapq.heappush(h, x)\n"
            "print(heapq.heappop(h))   # 1 (최솟값)\n"
            "print(heapq.heappop(h))   # 3\n"
            "\n"
            "data = [9, 2, 7, 4, 1]\n"
            "heapq.heapify(data)        # 제자리 힙 구성\n"
            "print(data[0])             # 1\n"
            "\n"
            "# 최대 힙: 부호 반전\n"
            "maxh = []\n"
            "for x in [5, 1, 8, 3]:\n"
            "    heapq.heappush(maxh, -x)\n"
            "print(-heapq.heappop(maxh))   # 8 (최댓값)\n"
            "\n"
            "# 우선순위 큐: (우선순위, 작업)\n"
            "pq = [(2, '낮음'), (0, '긴급'), (1, '보통')]\n"
            "heapq.heapify(pq)\n"
            "print(heapq.heappop(pq))   # (0, '긴급')\n"
        ),
    ),

    Lesson(
        id="py-adv-06",
        lang="python", level="고급",
        title="bisect(이분 탐색)",
        summary="정렬 리스트에서 위치를 O(log n)에 탐색",
        explanation=(
            "━━ bisect(이분 탐색) 이란? ━━\n"
            "\n"
            "비유: 두꺼운 사전에서 단어를 찾을 때, 처음부터 한 장씩 넘기지 않죠.\n"
            "중간을 펼쳐서 찾는 단어가 앞쪽인지 뒤쪽인지 확인하고, 절반씩 줄여가며 찾아요.\n"
            "1000페이지 사전도 약 10번만 펼치면 찾을 수 있어요(log2(1000) ≈ 10).\n"
            "이게 이분 탐색이에요.\n"
            "bisect는 이미 정렬된 리스트에서 이분 탐색으로 빠르게 위치를 찾아줘요.\n"
            "\n"
            "bisect_left vs bisect_right 차이:\n"
            "같은 값이 여러 개 있을 때 차이가 나요.\n"
            "[1, 3, 3, 3, 5]에서 3의 위치를 찾으면:\n"
            "  bisect_left:  3들이 시작하는 위치(인덱스 1)를 알려줘요.\n"
            "  bisect_right: 3들이 끝난 다음 위치(인덱스 4)를 알려줘요.\n"
            "두 값의 차이(right - left)로 특정 값의 개수를 O(log n)에 구할 수 있어요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  import bisect                →  bisect 모듈을 가져와요.\n"
            "  a = [1, 3, 3, 3, 5, 7]     →  정렬된 리스트예요.\n"
            "                                  bisect는 반드시 정렬된 리스트에서만 써야 해요.\n"
            "  bisect.bisect_left(a, 3)    →  3이 들어갈 수 있는 가장 왼쪽 위치인 1을 출력해요.\n"
            "                                  인덱스 1에 3을 넣으면 왼쪽 3들의 앞이에요.\n"
            "  bisect.bisect_right(a, 3)   →  3이 들어갈 수 있는 가장 오른쪽 위치인 4를 출력해요.\n"
            "                                  인덱스 4는 마지막 3의 바로 다음이에요.\n"
            "  bisect_right - bisect_left  →  4 - 1 = 3이에요.\n"
            "                                  리스트 안에 3이 3개 있다는 걸 O(log n)으로 셀 수 있어요.\n"
            "  bisect.insort(a, 4)          →  4를 정렬 순서를 유지하면서 삽입해요.\n"
            "                                  [1, 3, 3, 3, 4, 5, 7]이 돼요.\n"
            "  print(a)                     →  4가 삽입된 [1, 3, 3, 3, 4, 5, 7]을 출력해요.\n"
            "  idx = bisect.bisect_left(a, 5)\n"
            "                               →  5 이상인 첫 번째 값의 인덱스를 찾아요.\n"
            "  print(a[idx])                →  그 위치의 값인 5를 출력해요.\n"
            "\n"
            "왜(Why) bisect를 쓰나요?\n"
            "리스트에서 특정 값 이상인 첫 원소를 찾거나,\n"
            "특정 범위의 값이 몇 개인지 세고 싶을 때,\n"
            "일반 for 문으로 찾으면 O(n)이지만 bisect는 O(log n)이에요.\n"
            "데이터가 수십만 개일 때 엄청난 차이가 나요.\n"
            "\n"
            "주의할 점:\n"
            "  - 리스트가 정렬되어 있지 않으면 완전히 틀린 결과가 나와요.\n"
            "    반드시 정렬 후 써야 해요.\n"
            "  - insort로 삽입 위치를 찾는 건 O(log n)이지만,\n"
            "    실제 원소를 한 칸씩 밀어내는 건 O(n)이에요.\n"
            "    삽입이 많으면 느려질 수 있어요."
        ),
        usage="정렬된 데이터에서 특정 값/범위 개수 세기, 좌표압축, LIS 길이(O(n log n)) 등에 쓴다.",
        cons="반드시 정렬 상태를 전제로 한다(아니면 틀린 결과). insort 삽입 자체는 원소 이동 때문에 O(n).",
        code=(
            "import bisect\n"
            "\n"
            "a = [1, 3, 3, 3, 5, 7]\n"
            "print(bisect.bisect_left(a, 3))    # 1\n"
            "print(bisect.bisect_right(a, 3))   # 4\n"
            "print(bisect.bisect_right(a, 3) - bisect.bisect_left(a, 3))  # 3의 개수 = 3\n"
            "\n"
            "# 정렬 유지 삽입\n"
            "bisect.insort(a, 4)\n"
            "print(a)   # [1, 3, 3, 3, 4, 5, 7]\n"
            "\n"
            "# x 이상인 첫 원소 찾기\n"
            "idx = bisect.bisect_left(a, 5)\n"
            "print(a[idx])   # 5\n"
        ),
    ),

    Lesson(
        id="py-adv-07",
        lang="python", level="고급",
        title="functools(lru_cache 메모이제이션, reduce)",
        summary="자동 캐싱과 누적 계산 도구",
        explanation=(
            "━━ functools(lru_cache · reduce) 이란? ━━\n"
            "\n"
            "lru_cache 비유: 수학 시험에서 같은 계산을 반복해야 한다면,\n"
            "계산기로 한 번 구한 값을 메모지에 적어두고\n"
            "다음에 같은 계산이 나오면 메모지를 보면 되잖아요.\n"
            "lru_cache가 바로 이 메모지 역할이에요.\n"
            "함수를 호출한 결과를 자동으로 기억해두고,\n"
            "같은 인자로 또 부르면 다시 계산하지 않고 기억한 값을 바로 돌려줘요.\n"
            "\n"
            "reduce 비유: reduce는 가위바위보 토너먼트처럼,\n"
            "여러 값들을 두 개씩 묶어서 하나로 줄여나가는 함수예요.\n"
            "[1, 2, 3, 4, 5]를 곱하면: ((((1x2)x3)x4)x5) = 120처럼\n"
            "왼쪽부터 두 개씩 합쳐요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  from functools import lru_cache, reduce\n"
            "                               →  functools에서 lru_cache와 reduce를 가져와요.\n"
            "  from math import gcd         →  최대공약수를 구하는 gcd 함수를 가져와요.\n"
            "  @lru_cache(maxsize=None)     →  아래 fib 함수에 자동 캐시(메모지)를 달아줘요.\n"
            "                                  maxsize=None은 캐시 크기 제한 없이\n"
            "                                  모든 결과를 기억하라는 뜻이에요.\n"
            "  def fib(n):                  →  피보나치 수를 구하는 재귀 함수예요.\n"
            "  if n < 2: return n           →  n이 0이면 0, 1이면 1을 바로 돌려줘요\n"
            "                                  (피보나치의 시작값).\n"
            "  return fib(n-1) + fib(n-2)  →  fib(30)을 구하려면 fib(29)와 fib(28)이 필요하고,\n"
            "                                  fib(29)는 fib(28)과 fib(27)이 필요해요.\n"
            "                                  캐시 없으면 fib(28)이 수십 번 중복 계산돼요.\n"
            "                                  lru_cache 덕분에 각 n은 딱 한 번만 계산해요.\n"
            "  print(fib(30))               →  832040을 거의 즉시 출력해요.\n"
            "                                  캐시가 없으면 2^30 = 10억 번 이상 계산해야 해요.\n"
            "  print(fib.cache_info())      →  캐시 적중(hits)과 미스(misses) 횟수를 출력해요.\n"
            "                                  fib(30)에서 hits가 수십 개임을 확인할 수 있어요.\n"
            "  reduce(lambda acc, x: acc*x, range(1,6), 1)\n"
            "                               →  1부터 5까지의 곱(5! = 120)을 계산해요.\n"
            "                                  lambda acc, x: acc * x 는\n"
            "                                  \"지금까지 곱한 값(acc)에 x를 곱해라\"예요.\n"
            "                                  세 번째 인자 1은 초기값이에요.\n"
            "  reduce(gcd, [24, 36, 60])    →  24와 36의 최대공약수(12)를 구하고,\n"
            "                                  그 12와 60의 최대공약수(12)를 구해요.\n"
            "                                  세 수의 최대공약수인 12가 나와요.\n"
            "\n"
            "왜(Why) lru_cache를 쓰나요?\n"
            "재귀로 짠 DP(동적 프로그래밍)는 같은 계산을 엄청나게 많이 반복해요.\n"
            "lru_cache 한 줄만 추가하면 자동으로 메모이제이션이 돼서\n"
            "O(2^n)이 O(n)으로 줄어들어요.\n"
            "\n"
            "주의할 점:\n"
            "  - lru_cache는 인자가 해시 가능한(변경 불가능한) 값이어야 해요.\n"
            "    리스트를 인자로 넘기면 오류가 나요. 튜플로 바꿔서 넘겨야 해요.\n"
            "  - 캐시는 메모리를 차지해요. 많은 인자 조합으로 오래 실행하면\n"
            "    메모리가 부족할 수 있어요."
        ),
        usage="피보나치·조합수 같은 겹치는 부분문제 재귀 DP 가속, 순수 함수의 반복 호출 결과 재사용.",
        cons="인자는 해시 가능(불변)해야 캐싱된다. 캐시가 메모리를 계속 점유하고, 부수효과 함수엔 위험.",
        code=(
            "from functools import lru_cache, reduce\n"
            "from math import gcd\n"
            "\n"
            "@lru_cache(maxsize=None)\n"
            "def fib(n):\n"
            "    if n < 2:\n"
            "        return n\n"
            "    return fib(n - 1) + fib(n - 2)\n"
            "\n"
            "print(fib(30))            # 832040 (캐시 덕분에 즉시)\n"
            "print(fib.cache_info())   # hits/misses 확인\n"
            "\n"
            "# reduce: 1*2*...*5 = 120\n"
            "print(reduce(lambda acc, x: acc * x, range(1, 6), 1))\n"
            "\n"
            "# reduce + gcd: 여러 수의 최대공약수\n"
            "print(reduce(gcd, [24, 36, 60]))   # 12\n"
        ),
    ),

    Lesson(
        id="py-adv-08",
        lang="python", level="고급",
        title="sys.stdin 빠른 입출력과 재귀한도",
        summary="대량 입력 가속과 setrecursionlimit",
        explanation=(
            "━━ sys.stdin 빠른 입출력 이란? ━━\n"
            "\n"
            "왜 빠른 입출력이 필요한가요?\n"
            "파이썬의 기본 input() 함수는 편리하지만 느려요.\n"
            "문제 입력이 10만 줄이면 input()을 10만 번 부르는 건 시간을 많이 잡아먹어요.\n"
            "마치 편지를 한 통씩 10만 번 받는 것 vs 편지 10만 통을 한 번에 받는 것의 차이예요.\n"
            "sys.stdin을 쓰면 훨씬 빠르게 입력을 받을 수 있어요.\n"
            "\n"
            "재귀 한도가 뭔가요?\n"
            "파이썬은 함수가 함수를 부르는 깊이(재귀 깊이)에 기본 제한이 있어요.\n"
            "약 1000번까지만 허용해요.\n"
            "DFS로 깊이 1000이 넘는 그래프를 탐색하면 RecursionError가 나요.\n"
            "sys.setrecursionlimit()으로 이 한도를 올릴 수 있어요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "  import sys, io               →  sys(시스템 기능)와 io(입출력 기능)\n"
            "                                  모듈을 가져와요.\n"
            "  sample = '3\\n10 20\\n...'   →  실제 채점 환경에서는 키보드 입력이 들어오지만,\n"
            "                                  여기서는 연습을 위해 직접 입력값을\n"
            "                                  문자열로 만들어요. \\n은 줄바꿈이에요.\n"
            "  sys.stdin = io.StringIO(sample)\n"
            "                               →  sys.stdin(표준 입력)을 sample 문자열로 바꿔요.\n"
            "                                  이제 readline()이 sample을 읽어요.\n"
            "  input = sys.stdin.readline   →  input이라는 이름을 sys.stdin.readline 함수로\n"
            "                                  바꿔요. 이제 input()을 부르면 한 줄을 빠르게 읽어요.\n"
            "                                  단, 줄 끝에 '\\n'이 붙어 오니 주의하세요.\n"
            "  n = int(input())             →  첫 번째 줄 \"3\"을 읽어서 정수 3으로 바꿔요.\n"
            "  out = []                     →  결과를 하나씩 모을 빈 리스트예요.\n"
            "                                  print() 대신 리스트에 모아서 한 번에 출력하면\n"
            "                                  훨씬 빨라요.\n"
            "  for _ in range(n):           →  n(=3)번 반복해요.\n"
            "  a, b = map(int, input().split())\n"
            "                               →  한 줄을 읽어서 공백으로 나눈 뒤 각각 정수로 바꿔요.\n"
            "                                  \"10 20\"을 읽으면 a=10, b=20이 돼요.\n"
            "  out.append(str(a + b))       →  a+b의 결과를 문자열로 바꿔서 out 리스트에 추가해요.\n"
            "  sys.stdout.write('\\n'.join(out) + '\\n')\n"
            "                               →  out 리스트의 모든 값을 줄바꿈으로 연결해서\n"
            "                                  한 번에 출력해요. print()를 3번 부르는 것보다\n"
            "                                  훨씬 빨라요. \"30\\n70\\n110\"이 출력돼요.\n"
            "  sys.setrecursionlimit(10**6) →  재귀 허용 깊이를 100만으로 늘려요.\n"
            "                                  깊은 DFS를 써야 할 때 RecursionError를 예방해요.\n"
            "  def depth(k):                →  k번 재귀 호출하는 테스트 함수예요.\n"
            "  if k == 0: return 0          →  재귀의 끝(기저 조건)이에요.\n"
            "  return 1 + depth(k - 1)     →  자기 자신을 k-1로 부르는 재귀예요.\n"
            "  print(depth(2000))           →  기본 한도(약 1000)라면 RecursionError가 나지만,\n"
            "                                  한도를 100만으로 올렸으니 2000을 정상 출력해요.\n"
            "\n"
            "왜(Why) 빠른 입출력이 중요한가요?\n"
            "코딩테스트에서 시간 초과(TLE)의 원인이 알고리즘이 아닌 느린 입출력인 경우가 있어요.\n"
            "특히 입력이 10만 줄 이상인 문제에서는 sys.stdin.readline을 쓰는 것만으로\n"
            "통과/실패가 갈릴 수 있어요.\n"
            "\n"
            "주의할 점:\n"
            "  - sys.stdin.readline()으로 읽으면 줄 끝에 '\\n'이 붙어요.\n"
            "    int()로 변환할 때는 괜찮지만 문자열을 직접 쓸 때는 .strip()을 해야 해요.\n"
            "  - setrecursionlimit을 너무 크게(100만 이상) 올리면 메모리가 부족해서\n"
            "    파이썬 인터프리터 자체가 죽을 수 있어요. 10^6 정도가 적당해요."
        ),
        usage="입력 줄 수가 수만~수십만인 백준 문제, 깊은 재귀 DFS/분할정복에서 필수.",
        cons="setrecursionlimit 을 너무 키우면 스택 초과로 인터프리터가 죽을 수 있다. readline 은 개행 처리 주의.",
        code=(
            "import sys, io\n"
            "\n"
            "# 데모: 실제 표준입력 대신 고정 데이터를 sys.stdin 에 주입\n"
            "sample = '3\\n10 20\\n30 40\\n50 60\\n'\n"
            "sys.stdin = io.StringIO(sample)\n"
            "\n"
            "input = sys.stdin.readline      # 빠른 입력\n"
            "n = int(input())\n"
            "out = []\n"
            "for _ in range(n):\n"
            "    a, b = map(int, input().split())\n"
            "    out.append(str(a + b))\n"
            "sys.stdout.write('\\n'.join(out) + '\\n')   # 한 번에 출력 → 30 70 110\n"
            "\n"
            "# 깊은 재귀를 위해 한도 상향\n"
            "sys.setrecursionlimit(10**6)\n"
            "\n"
            "def depth(k):\n"
            "    if k == 0:\n"
            "        return 0\n"
            "    return 1 + depth(k - 1)\n"
            "\n"
            "print(depth(2000))   # 기본 한도였다면 에러, 상향 후 2000\n"
        ),
    ),
]
