"""Python 중급 문법 (함수·람다·컴프리헨션·예외·OOP·모듈·collections·문자열)."""

from engine.models import Lesson

LESSONS = [

    Lesson(
        id="py-mid-01",
        lang="python", level="중급",
        title="함수와 기본/가변 인자 (*args, **kwargs)",
        summary="기본값 인자 · 가변 위치인자 *args · 가변 키워드인자 **kwargs",
        explanation=(
            "[개요]\n"
            "함수는 반복적으로 사용하는 작업을 하나의 이름으로 묶어 재사용하는 단위이다.\n"
            "동일한 로직을 매번 작성하는 대신 함수로 정의해 두면 이름 호출만으로 재사용할 수 있다.\n"
            "\n"
            "[핵심 개념]\n"
            "• 기본값 인자: 인자를 전달하지 않으면 미리 정의된 값을 사용한다.\n"
            "• *args: 개수가 정해지지 않은 위치 인자를 하나의 튜플로 받는다.\n"
            "• **kwargs: 이름=값 형태로 전달된 키워드 인자를 딕셔너리로 받는다.\n"
            "\n"
            "[코드 분석]\n"
            "  def add_all(*args, start=0):  → args 라는 이름으로 위치 인자 여러 개를 튜플로 받는다.\n"
            "                                   start=0 은 기본값이 0인 키워드 인자이다.\n"
            "  total = start               → 합계를 담을 변수를 start 값으로 초기화한다.\n"
            "  for v in args:              → 튜플 args 안의 값을 하나씩 꺼내며 반복한다.\n"
            "  total += v                  → 꺼낸 값을 total 에 더한다.\n"
            "  return total                → 최종 합계를 반환한다.\n"
            "\n"
            "  def make_user(**kwargs):    → 이름=값 형태의 인자들을 딕셔너리로 받는다.\n"
            "  return kwargs               → 받은 딕셔너리를 그대로 반환한다.\n"
            "\n"
            "  def bad_default(item, box=None):  → 기본값을 None 으로 지정한 올바른 패턴이다.\n"
            "  if box is None: box = []          → None 일 때만 새 리스트를 생성한다.\n"
            "                                       이렇게 하지 않으면 모든 호출이 같은 리스트를 공유하는 문제가 발생한다.\n"
            "  box.append(item)                  → 리스트에 item 을 추가한다.\n"
            "  return box                        → 결과 리스트를 반환한다.\n"
            "\n"
            "  print(add_all(1, 2, 3))           → args=(1,2,3), start=0 → 6\n"
            "  print(add_all(1, 2, 3, start=10)) → args=(1,2,3), start=10 → 16\n"
            "  print(add_all(*nums))             → *nums 는 리스트를 개별 인자로 풀어서 전달한다(언패킹).\n"
            "\n"
            "[유의 사항]\n"
            "• 기본값으로 [] 나 {} 같은 가변 객체를 사용하면 모든 호출이 같은 객체를 공유하여 값이 누적되는 버그가 발생한다.\n"
            "• 기본값은 None 으로 지정하고 함수 내부에서 새 객체를 생성해야 한다."
        ),
        usage=(
            "공통 로직을 함수로 묶어 재사용한다. *args/**kwargs 는 인자 개수가 유동적인 "
            "래퍼/데코레이터/로깅 함수에 유용하다. 코딩테스트에서는 재귀 함수(DFS/백트래킹)와 "
            "기본값을 활용한 재귀 깊이/누적값 전달에 자주 쓴다."
        ),
        cons=(
            "기본값에 [] 나 {} 같은 가변 객체를 쓰면 호출 간에 값이 누적되는 함정이 있다(반드시 None 으로).\n"
            "인자가 너무 많아지면 가독성이 떨어지고, **kwargs 남용은 어떤 인자가 필요한지 숨겨 디버깅을 어렵게 한다."
        ),
        code=(
            "def add_all(*args, start=0):\n"
            "    # 가변 위치 인자를 모두 더한다\n"
            "    total = start\n"
            "    for v in args:\n"
            "        total += v\n"
            "    return total\n"
            "\n"
            "def make_user(**kwargs):\n"
            "    # 키워드 인자를 딕셔너리로 받는다\n"
            "    return kwargs\n"
            "\n"
            "def bad_default(item, box=None):\n"
            "    # 가변 기본값 함정을 피하는 올바른 방법\n"
            "    if box is None:\n"
            "        box = []\n"
            "    box.append(item)\n"
            "    return box\n"
            "\n"
            "print(add_all(1, 2, 3))            # 6\n"
            "print(add_all(1, 2, 3, start=10))  # 16\n"
            "nums = [4, 5, 6]\n"
            "print(add_all(*nums))             # 언패킹 → 15\n"
            "print(make_user(name='홍길동', age=20))\n"
            "print(bad_default(1))             # [1]\n"
            "print(bad_default(2))             # [2] (누적되지 않음)\n"
        ),
    ),

    Lesson(
        id="py-mid-02",
        lang="python", level="중급",
        title="람다와 정렬 key",
        summary="익명 함수 lambda · sorted/sort 의 key · reverse",
        explanation=(
            "[개요]\n"
            "lambda 는 이름 없이 정의하는 일회용 함수이며, 간단한 연산을 즉석에서 처리할 때 사용한다.\n"
            "\n"
            "[핵심 개념]\n"
            "• lambda x: x * 2 는 x 를 받아 x*2 를 반환하는 함수로, def f(x): return x * 2 와 동일하다.\n"
            "• sorted 의 key 인자는 정렬 기준값을 산출하는 함수이다. 원소 전체가 아니라 key 가 반환한 값만 비교한다.\n"
            "\n"
            "[코드 분석]\n"
            "  people = [('kim', 30), ('lee', 20), ('park', 30), ('choi', 20)]\n"
            "    → (이름, 나이) 튜플 4개가 들어 있는 리스트이다.\n"
            "\n"
            "  sorted(people, key=lambda p: (p[1], p[0]))\n"
            "    → 각 사람 p 에서 (나이, 이름) 을 꺼내 비교한다.\n"
            "       튜플은 첫 번째 값을 먼저 비교하고 같으면 두 번째 값을 비교하므로\n"
            "       나이 오름차순, 같으면 이름 사전순으로 정렬된다.\n"
            "\n"
            "  sorted(people, key=lambda p: -p[1])\n"
            "    → 나이에 마이너스를 붙이면 큰 값이 작아져 내림차순이 된다. reverse=True 와 동일한 효과이다.\n"
            "\n"
            "  sorted(nums, key=lambda x: abs(x))\n"
            "    → 절댓값 기준으로 정렬한다. abs() 는 음수를 양수로 변환한다.\n"
            "\n"
            "  max(people, key=lambda p: p[1])\n"
            "    → 나이(p[1])가 가장 큰 사람을 반환한다.\n"
            "\n"
            "  list(map(lambda x: x * 2, nums))\n"
            "    → nums 의 모든 원소에 람다를 적용해 2배로 만든 새 리스트를 생성한다.\n"
            "\n"
            "[유의 사항]\n"
            "• lambda 는 한 줄짜리 식(expression)만 허용한다. if 블록이나 for 반복문 같은 여러 줄 로직은 사용할 수 없다.\n"
            "• 복잡한 정렬 기준은 별도 def 함수로 정의하는 편이 가독성에 유리하다."
        ),
        usage=(
            "정렬 기준을 한 줄로 지정할 때 가장 많이 쓴다. 코딩테스트에서 '여러 조건으로 정렬' "
            "(예: 나이 오름차순, 같으면 이름 사전순) 문제는 key=lambda x: (x[0], x[1]) 형태로 해결한다. "
            "max/min 의 key 인자에도 동일하게 쓴다."
        ),
        cons=(
            "lambda 는 한 줄 식만 가능하고 문장(if 블록, 반복문)을 넣을 수 없어 복잡한 로직엔 부적합하다.\n"
            "이름이 없어 디버깅 시 추적이 어렵고, 너무 복잡한 lambda 는 def 로 빼는 편이 가독성에 좋다."
        ),
        code=(
            "people = [('kim', 30), ('lee', 20), ('park', 30), ('choi', 20)]\n"
            "\n"
            "# 나이 오름차순, 같으면 이름 사전순 (다중 기준 정렬)\n"
            "by_age_name = sorted(people, key=lambda p: (p[1], p[0]))\n"
            "print(by_age_name)\n"
            "\n"
            "# 나이 내림차순\n"
            "by_age_desc = sorted(people, key=lambda p: -p[1])\n"
            "print(by_age_desc)\n"
            "\n"
            "nums = [3, 1, -5, 2, -8]\n"
            "# 절댓값 기준 정렬\n"
            "print(sorted(nums, key=lambda x: abs(x)))   # [1, 2, 3, -5, -8]\n"
            "print(max(people, key=lambda p: p[1]))      # 나이 최대\n"
            "double = list(map(lambda x: x * 2, nums))\n"
            "print(double)\n"
        ),
    ),

    Lesson(
        id="py-mid-03",
        lang="python", level="중급",
        title="리스트/딕셔너리 컴프리헨션 심화",
        summary="조건부 표현식 · 중첩 컴프리헨션 · dict/set 컴프리헨션",
        explanation=(
            "[개요]\n"
            "컴프리헨션은 반복문을 한 줄의 식으로 압축하는 파이썬 문법이다. 원소를 순회하며 필터링·변환하여 컬렉션을 생성한다.\n"
            "\n"
            "[핵심 개념]\n"
            "• 기본 구조: [결과식 for 변수 in 반복대상 if 조건]\n"
            "  조건에 맞는 원소만 걸러 결과식으로 변환한 뒤 리스트에 담는다.\n"
            "• 조건부 표현식(삼항 연산자): 값 자리에서 if-else 로 결과를 선택한다.\n"
            "  [x if x > 0 else 0 for x in nums] → 각 x 가 양수면 x, 아니면 0 으로 변환한다.\n"
            "• if 위치에 따른 차이:\n"
            "  - [x for x in nums if x > 0]        → if 가 for 뒤에 위치 → 필터링(특정 원소 제외)\n"
            "  - [x if x > 0 else 0 for x in nums] → if-else 가 for 앞에 위치 → 값 변환(모든 원소 포함)\n"
            "\n"
            "[코드 분석]\n"
            "  nums = [-2, 5, -1, 8, 0, -7]\n"
            "    → 양수와 음수가 섞인 리스트이다.\n"
            "\n"
            "  pos = [x for x in nums if x > 0]\n"
            "    → nums 에서 x 를 하나씩 꺼내 x > 0 인 원소(양수)만 리스트에 담는다. 결과: [5, 8]\n"
            "\n"
            "  clip = [x if x > 0 else 0 for x in nums]\n"
            "    → 모든 원소를 순회하며 양수는 그대로, 음수/0 은 0 으로 변환한다.\n"
            "       음수를 잘라내어(clip) 0 으로 만든다는 의미이다. 결과: [0, 5, 0, 8, 0, 0]\n"
            "\n"
            "  grid = [[r * 3 + c for c in range(3)] for r in range(2)]\n"
            "    → 바깥 컴프리헨션이 행(r=0,1)을, 안쪽이 각 행의 열(c=0,1,2) 값을 생성한다.\n"
            "       결과: [[0,1,2],[3,4,5]] (2행 3열 격자)\n"
            "\n"
            "  pairs = [(a, b) for a in [1, 2] for b in ['x', 'y']]\n"
            "    → for a, for b 가 이중 반복이며 앞의 for 가 바깥 루프이다.\n"
            "       (1,x), (1,y), (2,x), (2,y) 조합이 생성된다.\n"
            "\n"
            "  square_map = {x: x * x for x in range(1, 5)}\n"
            "    → {} 와 콜론을 사용하면 딕셔너리 컴프리헨션이다.\n"
            "       1→1, 2→4, 3→9, 4→16 매핑을 한 줄로 생성한다.\n"
            "\n"
            "  {len(w) for w in ['a', 'bb', 'cc', 'ddd']}\n"
            "    → {} 에 콜론 없이 값만 쓰면 집합(set) 컴프리헨션이다.\n"
            "       각 단어 길이의 집합 {1, 2, 3} 이 생성된다.\n"
            "\n"
            "[유의 사항]\n"
            "• 중첩이 2단계 이상이면 가독성이 저하되므로 일반 for 반복문이 더 명확하다.\n"
            "• 결과 전체를 메모리에 적재하므로, 데이터가 수백만 개 규모라면 제너레이터 (x for x in ...) 를 사용한다."
        ),
        usage=(
            "반복+변환+필터를 간결하게 처리할 때. 코딩테스트에서 입력 파싱(2차원 배열 생성), "
            "인덱스→값 매핑 딕셔너리 만들기, 조건에 맞는 원소만 추리기 등에 매우 자주 쓴다. "
            "일반 for 루프보다 약간 빠르기도 하다."
        ),
        cons=(
            "조건과 중첩이 많아지면 한 줄이 너무 길어져 오히려 읽기 어렵다(2중 이상 중첩은 일반 루프 권장).\n"
            "메모리에 결과 전체를 만들므로 거대한 데이터에는 제너레이터 표현식 (x for ...) 을 고려해야 한다."
        ),
        code=(
            "nums = [-2, 5, -1, 8, 0, -7]\n"
            "\n"
            "# 필터: 양수만\n"
            "pos = [x for x in nums if x > 0]\n"
            "print(pos)                       # [5, 8]\n"
            "\n"
            "# 값 분기: 음수는 0 으로\n"
            "clip = [x if x > 0 else 0 for x in nums]\n"
            "print(clip)                      # [0, 5, 0, 8, 0, 0]\n"
            "\n"
            "# 2차원 배열 생성\n"
            "grid = [[r * 3 + c for c in range(3)] for r in range(2)]\n"
            "print(grid)                      # [[0,1,2],[3,4,5]]\n"
            "\n"
            "# 이중 반복 펼치기\n"
            "pairs = [(a, b) for a in [1, 2] for b in ['x', 'y']]\n"
            "print(pairs)\n"
            "\n"
            "# dict / set 컴프리헨션\n"
            "square_map = {x: x * x for x in range(1, 5)}\n"
            "print(square_map)                # {1:1, 2:4, 3:9, 4:16}\n"
            "print({len(w) for w in ['a', 'bb', 'cc', 'ddd']})  # {1, 2, 3}\n"
        ),
    ),

    Lesson(
        id="py-mid-04",
        lang="python", level="중급",
        title="예외 처리 (try/except/finally)",
        summary="try/except/else/finally · 예외 종류 · raise",
        explanation=(
            "[개요]\n"
            "프로그램 실행 중에는 숫자 대신 문자 입력, 0 으로 나누기, 존재하지 않는 파일 접근 등\n"
            "예상치 못한 오류가 발생할 수 있다. 이러한 상황을 예외(Exception)라 하며, 처리하지 않으면 프로그램이 중단된다.\n"
            "try/except 는 오류 발생 시에도 프로그램을 중단하지 않고 대응하도록 하는 안전 장치이다.\n"
            "\n"
            "[핵심 개념]\n"
            "• try:     → 실패 가능성이 있는 코드를 배치한다.\n"
            "• except:  → 오류 발생 시 대신 실행할 코드를 배치한다.\n"
            "• else:    → 오류가 없었을 때만 실행한다.\n"
            "• finally: → 오류 발생 여부와 무관하게 항상 실행한다(마무리 정리).\n"
            "\n"
            "[코드 분석]\n"
            "  def safe_div(a, b):\n"
            "    → a 를 b 로 나누는 함수이며, b 가 0인 경우에 대비한다.\n"
            "\n"
            "  try:\n"
            "      result = a / b\n"
            "    → 나눗셈을 시도한다. b 가 0 이면 이 지점에서 예외가 발생한다.\n"
            "\n"
            "  except ZeroDivisionError:\n"
            "    → '0으로 나누기' 오류가 발생했을 때만 이 블록이 실행된다.\n"
            "       ZeroDivisionError 는 파이썬이 정의한 예외 이름이다.\n"
            "\n"
            "      print('0 으로 나눌 수 없음')\n"
            "      return None\n"
            "    → 오류 메시지를 출력하고 None(값 없음)을 반환한다.\n"
            "\n"
            "  else:\n"
            "      return result\n"
            "    → 오류가 없었을 때(나눗셈 성공)만 실행되어 결과를 반환한다.\n"
            "\n"
            "  finally:\n"
            "      print(f'나눗셈 시도: {a} / {b}')\n"
            "    → 성공/실패와 무관하게 항상 실행된다. 로그 기록, 파일 닫기 등에 사용한다.\n"
            "\n"
            "  except ValueError as e:\n"
            "    → ValueError 예외를 잡고 예외 객체를 e 라는 이름으로 받는다.\n"
            "       e 를 출력하면 오류 메시지를 확인할 수 있다.\n"
            "\n"
            "  raise ValueError('나이는 음수가 될 수 없음')\n"
            "    → 직접 예외를 생성하여 발생시킨다. 잘못된 입력값을 호출자에게 알리는 방법이다.\n"
            "\n"
            "[주요 예외 종류]\n"
            "• ValueError        → 잘못된 값 (int('abc') 처럼 변환 불가)\n"
            "• ZeroDivisionError → 0으로 나누기\n"
            "• IndexError        → 리스트 범위 초과 (list[999])\n"
            "• KeyError          → 딕셔너리에 없는 키\n"
            "• TypeError         → 타입 불일치 ('1' + 1 처럼)\n"
            "• FileNotFoundError → 파일이 없을 때\n"
            "\n"
            "[유의 사항]\n"
            "• except: 처럼 타입을 지정하지 않으면 모든 오류를 포괄적으로 잡는다.\n"
            "  이 경우 코드의 실제 버그(오타 등)까지 숨겨져 디버깅이 어려워진다.\n"
            "• 잡을 예외 타입을 구체적으로 명시해야 한다."
        ),
        usage=(
            "입력 검증, 파일/네트워크 처리 등 실패 가능성이 있는 작업의 안전한 처리에 쓴다. "
            "코딩테스트에서는 형변환 실패(int('a'))나 0 나눗셈 방어, 그리고 '값이 없을 때까지 입력 받기' "
            "패턴(try: input() except EOFError)에 활용한다."
        ),
        cons=(
            "except: 로 모든 예외를 통째로 잡으면 진짜 버그(오타 등)까지 숨겨 디버깅이 어려워진다 → 구체적 타입 지정.\n"
            "예외 처리는 정상 흐름 제어용이 아니다(반복적으로 예외에 의존하면 느리고 의도가 불명확)."
        ),
        code=(
            "def safe_div(a, b):\n"
            "    try:\n"
            "        result = a / b\n"
            "    except ZeroDivisionError:\n"
            "        print('0 으로 나눌 수 없음')\n"
            "        return None\n"
            "    else:\n"
            "        # 예외가 없을 때만 실행\n"
            "        return result\n"
            "    finally:\n"
            "        # 항상 실행\n"
            "        print(f'나눗셈 시도: {a} / {b}')\n"
            "\n"
            "print(safe_div(10, 2))   # 5.0\n"
            "print(safe_div(10, 0))   # None\n"
            "\n"
            "# 형변환 예외 처리\n"
            "for token in ['10', 'abc', '20']:\n"
            "    try:\n"
            "        print('숫자:', int(token))\n"
            "    except ValueError as e:\n"
            "        print('변환 실패:', token)\n"
            "\n"
            "# 직접 예외 발생\n"
            "def check_age(age):\n"
            "    if age < 0:\n"
            "        raise ValueError('나이는 음수가 될 수 없음')\n"
            "    return age\n"
            "\n"
            "try:\n"
            "    check_age(-5)\n"
            "except ValueError as e:\n"
            "    print('에러:', e)\n"
        ),
    ),

    Lesson(
        id="py-mid-05",
        lang="python", level="중급",
        title="클래스와 객체 (OOP 기초)",
        summary="class · __init__ · self · 메서드 · 상속",
        explanation=(
            "[개요]\n"
            "클래스는 객체를 생성하기 위한 설계도이며, 클래스로 생성한 실체가 객체(인스턴스)이다.\n"
            "  • Dog 클래스        = 설계도\n"
            "  • d = Dog('바둑이') = 설계도로 생성한 실제 객체\n"
            "객체는 속성(데이터)과 메서드(행동)를 함께 가진다.\n"
            "  • d.name = '바둑이' (속성 - 데이터)\n"
            "  • d.bark()          (메서드 - 행동)\n"
            "\n"
            "[코드 분석]\n"
            "  class Animal:\n"
            "    → Animal 이라는 클래스(설계도) 정의를 시작한다.\n"
            "\n"
            "  def __init__(self, name):\n"
            "    → __init__ 은 생성자로, 객체 생성 시 자동 호출된다.\n"
            "       self 는 객체 자신을 가리키며 항상 첫 번째 매개변수로 지정한다.\n"
            "\n"
            "  self.name = name\n"
            "    → 전달받은 name 값을 객체의 name 속성으로 저장한다.\n"
            "       self.name 으로 써야 해당 객체만의 속성이 된다.\n"
            "       name 만 쓰면 함수 내 지역변수가 되어 메서드 밖에서 사용할 수 없다.\n"
            "\n"
            "  def speak(self):\n"
            "      return f'{self.name} 가 소리를 낸다'\n"
            "    → speak 메서드는 동물이 소리를 내는 행동이다.\n"
            "       self.name 으로 객체의 이름을 가져와 문자열에 삽입한다.\n"
            "\n"
            "  class Dog(Animal):\n"
            "    → Dog 클래스가 Animal 클래스를 상속받는다.\n"
            "       부모(Animal)의 모든 속성과 메서드를 물려받으며,\n"
            "       추가·변경할 부분만 다시 정의하면 된다.\n"
            "\n"
            "  def speak(self):\n"
            "      return f'{self.name}: 멍멍!'\n"
            "    → 부모의 speak 를 오버라이딩(재정의)한 것이다.\n"
            "       Dog 객체에서 speak() 를 호출하면 이 버전이 실행된다.\n"
            "\n"
            "  def __str__(self):\n"
            "      return f'Dog(name={self.name})'\n"
            "    → print(d) 처럼 객체를 출력할 때 표시할 문자열을 정의한다.\n"
            "       정의하지 않으면 <__main__.Dog object at 0x...> 형태의 주소가 출력된다.\n"
            "\n"
            "  a = Animal('고양이')\n"
            "    → Animal 클래스로 '고양이' 객체를 생성한다.\n"
            "       __init__ 이 자동 호출되어 self.name = '고양이' 가 저장된다.\n"
            "\n"
            "  isinstance(d, Animal)  → True\n"
            "    → d(Dog 객체)가 Animal 타입에도 해당하는지 확인한다.\n"
            "       자식 클래스의 객체는 부모 타입으로도 인정된다.\n"
            "\n"
            "[유의 사항]\n"
            "• self 를 누락하면 인스턴스 메서드에 self 인자가 없다는 오류가 발생한다.\n"
            "• 클래스 변수(클래스 바로 아래 정의)와 인스턴스 변수(self.xxx)를 혼동하지 않아야 한다.\n"
            "  클래스 변수는 모든 객체가 공유하고, 인스턴스 변수는 객체마다 개별적으로 가진다."
        ),
        usage=(
            "상태와 동작이 함께 묶이는 대상(플레이어, 그래프 노드, 게임 보드 등)을 모델링할 때 쓴다. "
            "코딩테스트에서 자주 쓰진 않지만, 복잡한 시뮬레이션/객체 상태 관리나 우선순위 비교 객체를 "
            "정의할 때 유용하다."
        ),
        cons=(
            "단순한 데이터 묶음에는 클래스가 과하다(딕셔너리/튜플/namedtuple/dataclass 가 더 간단).\n"
            "self 누락, 클래스 변수와 인스턴스 변수 혼동 등 초보자가 실수하기 쉬운 지점이 많다."
        ),
        code=(
            "class Animal:\n"
            "    def __init__(self, name):\n"
            "        self.name = name      # 인스턴스 속성\n"
            "\n"
            "    def speak(self):\n"
            "        return f'{self.name} 가 소리를 낸다'\n"
            "\n"
            "class Dog(Animal):            # 상속\n"
            "    def speak(self):          # 오버라이딩\n"
            "        return f'{self.name}: 멍멍!'\n"
            "\n"
            "    def __str__(self):\n"
            "        return f'Dog(name={self.name})'\n"
            "\n"
            "a = Animal('고양이')\n"
            "d = Dog('바둑이')\n"
            "print(a.speak())     # 고양이 가 소리를 낸다\n"
            "print(d.speak())     # 바둑이: 멍멍!\n"
            "print(d)             # Dog(name=바둑이)  (__str__)\n"
            "print(isinstance(d, Animal))   # True (자식은 부모 타입)\n"
        ),
    ),

    Lesson(
        id="py-mid-06",
        lang="python", level="중급",
        title="모듈/패키지와 import",
        summary="import · from import · as · 표준 라이브러리",
        explanation=(
            "[개요]\n"
            "모듈은 이미 구현되어 제공되는 코드 묶음이다. 필요한 기능을 직접 구현하지 않고 모듈을 가져와(import) 사용한다.\n"
            "  • 모듈   = 하나의 .py 파일 (예: math.py)\n"
            "  • 패키지 = 모듈들이 모인 폴더 (예: collections 폴더 내 여러 .py 파일)\n"
            "\n"
            "[코드 분석]\n"
            "  import math\n"
            "    → math 모듈 전체를 가져온다.\n"
            "       이후 math.sqrt(9) 처럼 '모듈이름.함수' 형태로 사용한다.\n"
            "\n"
            "  from itertools import combinations, permutations\n"
            "    → itertools 모듈에서 combinations 와 permutations 만 가져온다.\n"
            "       이후 itertools. 접두 없이 combinations(...) 로 바로 사용한다.\n"
            "\n"
            "  from collections import Counter\n"
            "    → Counter 만 가져온다. 문자 빈도 계산에 유용하다.\n"
            "\n"
            "  import random as rnd\n"
            "    → random 모듈을 rnd 라는 별칭으로 가져온다.\n"
            "       이후 rnd.randint(...) 로 짧게 사용한다.\n"
            "\n"
            "  math.gcd(12, 18)\n"
            "    → 12 와 18 의 최대공약수를 구한다. 결과: 6 (gcd = Greatest Common Divisor)\n"
            "\n"
            "  math.sqrt(16)\n"
            "    → 16의 제곱근을 구한다. 결과: 4.0 (항상 실수형으로 반환된다)\n"
            "\n"
            "  list(combinations([1, 2, 3], 2))\n"
            "    → [1,2,3] 에서 2개를 고르는 조합을 모두 생성한다.\n"
            "       순서를 구분하지 않으므로 (1,2)와 (2,1)은 같은 조합이다.\n"
            "\n"
            "  list(permutations([1, 2], 2))\n"
            "    → [1,2] 에서 2개를 고르는 순열을 모두 생성한다.\n"
            "       순서를 구분하므로 (1,2)와 (2,1)은 다른 순열이다.\n"
            "\n"
            "  rnd.seed(42)\n"
            "    → 난수 생성의 시작점을 42로 고정한다.\n"
            "       같은 시드면 항상 같은 순서로 난수가 생성되어 테스트에 유용하다.\n"
            "\n"
            "  Counter('mississippi')\n"
            "    → 각 문자의 등장 횟수를 세어 딕셔너리 형태로 반환한다.\n"
            "\n"
            "  if __name__ == '__main__':\n"
            "    → 파일을 직접 실행했을 때만 이 블록이 실행된다.\n"
            "       다른 파일에서 import 한 경우에는 실행되지 않는다.\n"
            "       테스트 코드나 실행 진입점을 이 블록에 배치하는 관용구이다.\n"
            "\n"
            "[코딩테스트 필수 표준 라이브러리]\n"
            "• math        → gcd, sqrt, ceil, floor, inf\n"
            "• itertools   → combinations, permutations, product\n"
            "• collections → deque, defaultdict, Counter\n"
            "• heapq       → 최소/최대 힙(우선순위 큐)\n"
            "• bisect      → 이진탐색으로 정렬 리스트에 삽입/검색\n"
            "• sys         → sys.stdin.readline (빠른 입력)\n"
            "\n"
            "[유의 사항]\n"
            "• from 모듈 import * 는 어떤 이름이 도입되는지 알 수 없어 이름 충돌을 유발한다.\n"
            "• 두 모듈이 서로를 import 하는 순환 import 는 오류를 발생시키므로 피해야 한다."
        ),
        usage=(
            "코드를 파일 단위로 분리·재사용할 때 필수. 코딩테스트에서는 표준 라이브러리가 핵심 무기다: "
            "math.gcd, itertools.permutations/combinations, heapq, bisect, collections 등을 알면 "
            "직접 구현할 코드를 크게 줄일 수 있다."
        ),
        cons=(
            "from 모듈 import * 는 어떤 이름이 들어왔는지 불분명해 이름 충돌·가독성 문제가 생긴다(지양).\n"
            "무거운 패키지를 불필요하게 import 하면 시작이 느려지고, 순환 import(서로 import) 는 오류를 낸다."
        ),
        code=(
            "import math\n"
            "from itertools import combinations, permutations\n"
            "from collections import Counter\n"
            "import random as rnd\n"
            "\n"
            "print(math.gcd(12, 18))            # 6\n"
            "print(math.sqrt(16))               # 4.0\n"
            "\n"
            "# 조합/순열 (코딩테스트 단골)\n"
            "print(list(combinations([1, 2, 3], 2)))   # [(1,2),(1,3),(2,3)]\n"
            "print(list(permutations([1, 2], 2)))      # [(1,2),(2,1)]\n"
            "\n"
            "rnd.seed(42)                       # 시드 고정 → 결과 재현 가능\n"
            "print(rnd.randint(1, 100))\n"
            "\n"
            "print(Counter('mississippi'))\n"
            "\n"
            "if __name__ == '__main__':\n"
            "    print('이 파일을 직접 실행했습니다')\n"
        ),
    ),

    Lesson(
        id="py-mid-07",
        lang="python", level="중급",
        title="collections (deque, defaultdict, Counter)",
        summary="양방향 큐 deque · 기본값 딕셔너리 defaultdict · 빈도 Counter",
        explanation=(
            "[개요]\n"
            "collections 모듈은 일반 리스트·딕셔너리보다 특정 상황에서 더 효율적인 자료구조를 제공한다.\n"
            "대표적으로 deque, defaultdict, Counter 세 가지가 있다.\n"
            "\n"
            "[핵심 개념]\n"
            "• deque (양방향 큐)\n"
            "  - 일반 리스트는 앞에서 꺼내기(pop(0))가 O(n) 으로 느리다.\n"
            "  - deque 는 양쪽 끝에서의 추가/삭제가 모두 O(1) 이다.\n"
            "  - BFS(너비 우선 탐색)의 큐로는 deque 를 사용해야 한다.\n"
            "• defaultdict (기본값 딕셔너리)\n"
            "  - 일반 딕셔너리는 없는 키에 접근하면 KeyError 가 발생한다.\n"
            "  - defaultdict 는 없는 키 접근 시 지정된 기본값을 자동으로 생성한다.\n"
            "• Counter (빈도 계산 딕셔너리)\n"
            "  - 문자·단어의 등장 횟수를 한 줄로 계산한다.\n"
            "  - most_common(n) 으로 가장 많이 등장한 n 개를 바로 추출한다.\n"
            "\n"
            "[코드 분석]\n"
            "  q = deque([1, 2, 3])\n"
            "    → 1, 2, 3 이 들어 있는 deque 를 생성한다.\n"
            "\n"
            "  q.append(4)\n"
            "    → 오른쪽(뒤)에 4를 추가한다. deque([1, 2, 3, 4])\n"
            "\n"
            "  q.appendleft(0)\n"
            "    → 왼쪽(앞)에 0을 추가한다. deque([0, 1, 2, 3, 4])\n"
            "\n"
            "  q.popleft()\n"
            "    → 왼쪽(앞)에서 꺼낸다. 0이 제거되어 deque([1, 2, 3, 4]) 가 된다.\n"
            "       BFS 에서 큐의 원소를 하나 꺼낼 때 사용한다.\n"
            "\n"
            "  graph = defaultdict(list)\n"
            "    → 없는 키에 접근하면 자동으로 빈 리스트를 생성하는 딕셔너리이다.\n"
            "       그래프의 인접 리스트 구성에 유용하다.\n"
            "\n"
            "  for a, b in [(1, 2), (1, 3), (2, 3)]:\n"
            "      graph[a].append(b)\n"
            "    → 1→[2,3], 2→[3] 인 그래프를 구성한다.\n"
            "       graph[1] 이 없어도 자동으로 [] 가 생성되므로 append 를 바로 사용할 수 있다.\n"
            "\n"
            "  cnt = defaultdict(int)\n"
            "  for ch in 'banana':\n"
            "      cnt[ch] += 1\n"
            "    → 각 문자의 등장 횟수를 센다.\n"
            "       cnt['b'] 가 없어도 자동으로 0 이 생성되어 += 1 이 바로 동작한다.\n"
            "\n"
            "  c = Counter('mississippi')\n"
            "    → mississippi 의 각 문자 빈도를 한 번에 계산한다.\n"
            "       {'i': 4, 's': 4, 'p': 2, 'm': 1} 형태로 저장된다.\n"
            "\n"
            "  c.most_common(2)\n"
            "    → 빈도가 가장 높은 2개를 [(문자, 빈도)] 형태로 반환한다.\n"
            "\n"
            "[유의 사항]\n"
            "• deque 는 중간 위치 접근(d[5])이 O(n) 으로 느리다. 중간 접근이 잦으면 일반 리스트가 유리하다.\n"
            "• defaultdict 는 d[key] 로 존재 여부를 확인하면 키가 없어도 자동 생성되는 부작용이 있다.\n"
            "  존재 여부는 key in d 로 확인해야 한다."
        ),
        usage=(
            "코딩테스트의 핵심 도구다. deque 는 BFS/슬라이딩 윈도우/큐 시뮬레이션에, "
            "defaultdict 는 그래프 인접 리스트(defaultdict(list))나 그룹핑/빈도수 누적에, "
            "Counter 는 빈도수 문제·애너그램·최빈값 찾기에 거의 항상 등장한다."
        ),
        cons=(
            "deque 는 중간 인덱스 접근(d[i])이 O(n) 으로 느리다(임의 접근이 잦으면 리스트가 낫다).\n"
            "defaultdict 는 조회만 해도 키가 생겨 버리는 부작용이 있어, 단순 조회엔 일반 dict.get 이 안전하다."
        ),
        code=(
            "from collections import deque, defaultdict, Counter\n"
            "\n"
            "# deque: 양방향 큐 (BFS 큐로 사용)\n"
            "q = deque([1, 2, 3])\n"
            "q.append(4)        # 오른쪽 추가\n"
            "q.appendleft(0)    # 왼쪽 추가\n"
            "print(q)           # deque([0, 1, 2, 3, 4])\n"
            "print(q.popleft()) # 0 (왼쪽 제거, O(1))\n"
            "print(q.pop())     # 4 (오른쪽 제거)\n"
            "\n"
            "# defaultdict: 그래프 인접 리스트\n"
            "graph = defaultdict(list)\n"
            "for a, b in [(1, 2), (1, 3), (2, 3)]:\n"
            "    graph[a].append(b)\n"
            "print(dict(graph))     # {1: [2, 3], 2: [3]}\n"
            "\n"
            "cnt = defaultdict(int)\n"
            "for ch in 'banana':\n"
            "    cnt[ch] += 1       # 키 확인 없이 누적\n"
            "print(dict(cnt))       # {'b':1,'a':3,'n':2}\n"
            "\n"
            "# Counter: 빈도수 + 최빈값\n"
            "c = Counter('mississippi')\n"
            "print(c.most_common(2))   # [('i', 4), ('s', 4)]\n"
        ),
    ),

    Lesson(
        id="py-mid-08",
        lang="python", level="중급",
        title="문자열 포맷팅 (f-string, join, split 심화)",
        summary="f-string 표현식·정렬·자릿수 · join · split/rsplit/splitlines",
        explanation=(
            "[개요]\n"
            "프로그램에서 결과 출력과 입력 처리 시 문자열을 빈번하게 다루며, 파이썬은 이를 위한 포맷팅·분할·결합 도구를 제공한다.\n"
            "\n"
            "[핵심 개념]\n"
            "• f-string: f'...' 형태로 접두 f 를 붙이고 {} 안에 값을 넣어 변수를 문자열에 직접 삽입한다. 현대적이고 빠른 방식이다.\n"
            "• join: '구분자'.join(리스트) 형태로 여러 문자열을 하나로 결합한다.\n"
            "• split: s.split('구분자') 형태로 문자열을 분할하여 리스트로 반환한다.\n"
            "\n"
            "[코드 분석]\n"
            "  name, score = '홍길동', 92.3456\n"
            "    → 이름과 점수 변수를 정의한다.\n"
            "\n"
            "  f'{name} 님 점수: {score:.1f}점'\n"
            "    → {score:.1f} 는 소수점 첫째 자리까지 표시한다.\n"
            "       .1f 에서 1은 소수점 자릿수, f 는 실수(float)를 의미한다.\n"
            "       결과: '홍길동 님 점수: 92.3점'\n"
            "\n"
            "  f'합계: {3 + 4}'\n"
            "    → {} 안에 계산식도 사용할 수 있다. 결과: '합계: 7'\n"
            "\n"
            "  f'[{name:^8}]'\n"
            "    → :^8 은 폭 8칸에 가운데 정렬이다. :< 는 왼쪽, :> 는 오른쪽 정렬이다.\n"
            "       결과: '[ 홍길동  ]' (공백으로 채운다)\n"
            "\n"
            "  f'{1234567:,}'\n"
            "    → 천 단위마다 콤마를 삽입한다. 결과: '1,234,567'\n"
            "\n"
            "  f'{42:05d} / {255:x}'\n"
            "    → :05d 는 5자리로 맞추고 앞을 0으로 채운다. 결과: '00042'\n"
            "       :x 는 16진수로 변환한다. 255 → 'ff'\n"
            "\n"
            "  ', '.join(words)\n"
            "    → words 리스트의 원소들을 ', ' 로 결합한다.\n"
            "       ['파이썬', '자바', 'C++'] → '파이썬, 자바, C++'\n"
            "\n"
            "  ' '.join(map(str, nums))\n"
            "    → nums 가 숫자 리스트이므로 먼저 map(str, ...) 로 문자열로 변환해야 한다.\n"
            "       join 은 문자열 리스트만 받기 때문이다.\n"
            "       [3, 1, 4] → '3 1 4'\n"
            "\n"
            "  'a,b,c'.split(',')\n"
            "    → 쉼표를 기준으로 분할한다. 결과: ['a', 'b', 'c']\n"
            "\n"
            "  'a b c d'.split(maxsplit=1)\n"
            "    → 최대 1회만 분할한다. 결과: ['a', 'b c d']\n"
            "       첫 번째 공백에서 한 번만 자르고 나머지는 그대로 둔다.\n"
            "\n"
            "  'x=1=2'.rsplit('=', 1)\n"
            "    → 오른쪽에서부터 1회 분할한다. 결과: ['x=1', '2']\n"
            "       왼쪽 split 과 방향이 반대이다.\n"
            "\n"
            "  'line1\\nline2'.splitlines()\n"
            "    → 줄바꿈(\\n) 기준으로 분할한다. 결과: ['line1', 'line2']\n"
            "\n"
            "[유의 사항]\n"
            "• f-string 안에서 바깥과 같은 따옴표를 사용하면 문자열이 중단된다. 바깥이 ' 이면 안은 \" 를 사용한다.\n"
            "• join 은 모든 원소가 문자열이어야 하며, 숫자가 섞이면 TypeError 가 발생한다.\n"
            "• 출력이 많을 때 print 를 여러 번 호출하면 느리다. 결과를 리스트에 모아 '\\n'.join(...) 으로 한 번에 출력하면 훨씬 빠르다."
        ),
        usage=(
            "출력 형식 맞추기(표, 소수 자릿수)에 f-string 이 표준이다. 코딩테스트에서는 "
            "여러 줄/여러 값 출력을 '\\n'.join(...) 으로 모아 한 번에 print 하면 출력이 빨라 시간초과를 피한다. "
            "split/map 조합은 입력 파싱의 기본이다."
        ),
        cons=(
            "f-string 안에서 같은 종류의 따옴표를 중첩하면 충돌하므로 바깥/안쪽 따옴표를 다르게 써야 한다.\n"
            "join 은 모든 원소가 문자열이어야 하며(숫자 섞이면 TypeError), 반대로 문자열 + 반복 연결은 느리다."
        ),
        code=(
            "name, score = '홍길동', 92.3456\n"
            "\n"
            "# f-string: 식, 자릿수, 정렬\n"
            "print(f'{name} 님 점수: {score:.1f}점')   # 92.3\n"
            "print(f'합계: {3 + 4}')                    # 식 삽입 → 7\n"
            "print(f'[{name:^8}]')                      # 가운데 정렬 폭 8\n"
            "print(f'{1234567:,}')                      # 천 단위 콤마\n"
            "print(f'{42:05d} / {255:x}')               # 00042 / ff\n"
            "\n"
            "# join: 리스트를 한 줄 문자열로\n"
            "words = ['파이썬', '자바', 'C++']\n"
            "print(', '.join(words))                    # 파이썬, 자바, C++\n"
            "nums = [3, 1, 4, 1, 5]\n"
            "print(' '.join(map(str, nums)))            # 3 1 4 1 5\n"
            "\n"
            "# split 심화\n"
            "print('a,b,c'.split(','))                  # ['a', 'b', 'c']\n"
            "print('a b c d'.split(maxsplit=1))         # ['a', 'b c d']\n"
            "print('x=1=2'.rsplit('=', 1))              # ['x=1', '2']\n"
            "print('line1\\nline2'.splitlines())        # ['line1', 'line2']\n"
        ),
    ),
]
