"""Python 중급 문법 (함수·람다·컴프리헨션·예외·OOP·모듈·collections·문자열)."""

from engine.models import Lesson

LESSONS = [

    Lesson(
        id="py-mid-01",
        lang="python", level="중급",
        title="함수와 기본/가변 인자 (*args, **kwargs)",
        summary="기본값 인자 · 가변 위치인자 *args · 가변 키워드인자 **kwargs",
        explanation=(
            "━━ 함수와 가변 인자 란? ━━\n"
            "\n"
            "함수는 '자주 쓰는 작업을 묶어 이름을 붙인 레시피'예요.\n"
            "예를 들어 '두 수를 더하는 작업'을 매번 직접 쓰는 대신,\n"
            "한 번 함수로 만들어 두면 언제든 이름만 불러 쓸 수 있어요.\n"
            "\n"
            "기본값 인자는 '인자를 안 넣으면 미리 정해 둔 값을 써라'는 약속이에요.\n"
            "예: 카페에서 '사이즈를 말 안 하면 자동으로 미디움'인 것과 같아요.\n"
            "\n"
            "*args 는 '손님이 몇 명이 와도 다 받겠다'는 뷔페 접시 같은 개념이에요.\n"
            "몇 개의 값을 넘기든 전부 하나의 튜플(묶음)로 받아줘요.\n"
            "\n"
            "**kwargs 는 '이름표가 붙은 선물들을 다 받겠다'는 의미예요.\n"
            "name='홍길동', age=20 처럼 이름=값 형태로 넘긴 것들을 딕셔너리로 받아요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "\n"
            "  def add_all(*args, start=0):  →  'args'라는 이름으로 위치 인자 여러 개를 튜플로 받아요.\n"
            "                                   start=0 은 기본값이 0인 키워드 인자예요.\n"
            "  total = start               →  합계를 담을 변수를 start 값으로 초기화해요.\n"
            "  for v in args:              →  튜플 args 안의 값을 하나씩 꺼내며 반복해요.\n"
            "  total += v                  →  꺼낸 값을 total 에 더해요.\n"
            "  return total                →  최종 합계를 돌려줘요.\n"
            "\n"
            "  def make_user(**kwargs):    →  이름=값 형태의 인자들을 딕셔너리로 받아요.\n"
            "  return kwargs               →  받은 딕셔너리를 그대로 돌려줘요.\n"
            "\n"
            "  def bad_default(item, box=None):  →  기본값을 None 으로 놓은 올바른 패턴이에요.\n"
            "  if box is None: box = []          →  None 일 때만 새 리스트를 만들어요.\n"
            "                                       이렇게 하지 않으면 모든 호출이 같은 리스트를 공유하는 함정에 빠져요.\n"
            "  box.append(item)                  →  리스트에 item 을 추가해요.\n"
            "  return box                        →  결과 리스트를 돌려줘요.\n"
            "\n"
            "  print(add_all(1, 2, 3))           →  args=(1,2,3), start=0 → 6\n"
            "  print(add_all(1, 2, 3, start=10)) →  args=(1,2,3), start=10 → 16\n"
            "  print(add_all(*nums))             →  *nums 는 리스트를 풀어서 개별 인자로 전달해요(언패킹).\n"
            "\n"
            "주의할 점:\n"
            "  기본값으로 [] 나 {} 같은 '바뀔 수 있는 객체'를 쓰면\n"
            "  모든 함수 호출이 같은 리스트를 공유해서 값이 쌓이는 버그가 생겨요.\n"
            "  반드시 None 을 기본값으로 놓고, 함수 안에서 새로 만드세요."
        ),
        usage=(
            "공통 로직을 함수로 묶어 재사용한다. *args/**kwargs 는 인자 개수가 유동적인 "
            "래퍼/데코레이터/로깅 함수에 유용하다. 코딩테스트에서는 재귀 함수(DFS/백트래킹)와 "
            "기본값을 활용한 재귀 깊이/누적값 전달에 자주 쓴다."
        ),
        cons=(
            "기본값에 [] 나 {} 같은 가변 객체를 쓰면 호출 간에 값이 누적되는 함정이 있다(반드시 None 으로).\n"
            "인자가 너무 많아지면 가독성이 떨어지고, **kwargs 남용은 어떤 인자가 필요한지 숨겨 디버깅을 어렵게 한다."
        ),
        code=(
            "def add_all(*args, start=0):\n"
            "    # 가변 위치 인자를 모두 더한다\n"
            "    total = start\n"
            "    for v in args:\n"
            "        total += v\n"
            "    return total\n"
            "\n"
            "def make_user(**kwargs):\n"
            "    # 키워드 인자를 딕셔너리로 받는다\n"
            "    return kwargs\n"
            "\n"
            "def bad_default(item, box=None):\n"
            "    # 가변 기본값 함정을 피하는 올바른 방법\n"
            "    if box is None:\n"
            "        box = []\n"
            "    box.append(item)\n"
            "    return box\n"
            "\n"
            "print(add_all(1, 2, 3))            # 6\n"
            "print(add_all(1, 2, 3, start=10))  # 16\n"
            "nums = [4, 5, 6]\n"
            "print(add_all(*nums))             # 언패킹 → 15\n"
            "print(make_user(name='홍길동', age=20))\n"
            "print(bad_default(1))             # [1]\n"
            "print(bad_default(2))             # [2] (누적되지 않음)\n"
        ),
    ),

    Lesson(
        id="py-mid-02",
        lang="python", level="중급",
        title="람다와 정렬 key",
        summary="익명 함수 lambda · sorted/sort 의 key · reverse",
        explanation=(
            "━━ lambda (람다) 와 정렬 key 란? ━━\n"
            "\n"
            "lambda 는 '이름 없는 일회용 함수'예요.\n"
            "공장 전체를 세우지 않고 간단한 작업 하나만 즉석에서 처리하는\n"
            "이동식 작업대 같은 개념이에요.\n"
            "\n"
            "예: lambda x: x * 2  →  x를 받아서 x*2를 돌려주는 함수예요.\n"
            "이것은 아래 def 함수와 완전히 동일해요:\n"
            "  def f(x): return x * 2\n"
            "\n"
            "sorted 의 key 인자는 '정렬 기준을 어떻게 만들지'를 알려주는 함수예요.\n"
            "사람들을 키 순서로 줄 세울 때, 사람 전체를 비교하지 않고\n"
            "'키'라는 기준값만 꺼내서 비교하는 것과 같아요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "\n"
            "  people = [('kim', 30), ('lee', 20), ('park', 30), ('choi', 20)]\n"
            "    →  (이름, 나이) 튜플 4개가 들어 있는 리스트예요.\n"
            "\n"
            "  sorted(people, key=lambda p: (p[1], p[0]))\n"
            "    →  각 사람 p 에서 (나이, 이름) 을 꺼내서 비교해요.\n"
            "       튜플은 첫 번째 값 먼저, 같으면 두 번째 값을 비교하므로\n"
            "       '나이 오름차순, 같으면 이름 사전순'이 돼요.\n"
            "\n"
            "  sorted(people, key=lambda p: -p[1])\n"
            "    →  나이에 마이너스를 붙이면 큰 값이 작아져서 내림차순이 돼요.\n"
            "       reverse=True 와 같은 효과예요.\n"
            "\n"
            "  sorted(nums, key=lambda x: abs(x))\n"
            "    →  절댓값 기준으로 정렬해요. abs() 는 음수를 양수로 바꿔줘요.\n"
            "\n"
            "  max(people, key=lambda p: p[1])\n"
            "    →  나이(p[1])가 가장 큰 사람을 찾아요.\n"
            "\n"
            "  list(map(lambda x: x * 2, nums))\n"
            "    →  nums 의 모든 원소에 람다를 적용해 2배로 만든 새 리스트를 만들어요.\n"
            "\n"
            "주의할 점:\n"
            "  lambda 는 딱 한 줄짜리 '식(expression)' 만 가능해요.\n"
            "  if 블록이나 for 반복문처럼 여러 줄이 필요한 로직은 쓸 수 없어요.\n"
            "  복잡한 정렬 기준은 별도 def 함수로 만드는 게 더 읽기 쉬워요."
        ),
        usage=(
            "정렬 기준을 한 줄로 지정할 때 가장 많이 쓴다. 코딩테스트에서 '여러 조건으로 정렬' "
            "(예: 나이 오름차순, 같으면 이름 사전순) 문제는 key=lambda x: (x[0], x[1]) 형태로 해결한다. "
            "max/min 의 key 인자에도 동일하게 쓴다."
        ),
        cons=(
            "lambda 는 한 줄 식만 가능하고 문장(if 블록, 반복문)을 넣을 수 없어 복잡한 로직엔 부적합하다.\n"
            "이름이 없어 디버깅 시 추적이 어렵고, 너무 복잡한 lambda 는 def 로 빼는 편이 가독성에 좋다."
        ),
        code=(
            "people = [('kim', 30), ('lee', 20), ('park', 30), ('choi', 20)]\n"
            "\n"
            "# 나이 오름차순, 같으면 이름 사전순 (다중 기준 정렬)\n"
            "by_age_name = sorted(people, key=lambda p: (p[1], p[0]))\n"
            "print(by_age_name)\n"
            "\n"
            "# 나이 내림차순\n"
            "by_age_desc = sorted(people, key=lambda p: -p[1])\n"
            "print(by_age_desc)\n"
            "\n"
            "nums = [3, 1, -5, 2, -8]\n"
            "# 절댓값 기준 정렬\n"
            "print(sorted(nums, key=lambda x: abs(x)))   # [1, 2, 3, -5, -8]\n"
            "print(max(people, key=lambda p: p[1]))      # 나이 최대\n"
            "double = list(map(lambda x: x * 2, nums))\n"
            "print(double)\n"
        ),
    ),

    Lesson(
        id="py-mid-03",
        lang="python", level="중급",
        title="리스트/딕셔너리 컴프리헨션 심화",
        summary="조건부 표현식 · 중첩 컴프리헨션 · dict/set 컴프리헨션",
        explanation=(
            "━━ 컴프리헨션 이란? ━━\n"
            "\n"
            "컴프리헨션은 '반복문을 한 줄로 압축하는 파이썬만의 마법 문법'이에요.\n"
            "마치 요리할 때 '재료를 하나씩 꺼내서 손질해서 그릇에 담는' 과정을\n"
            "한 문장으로 요약하는 것과 같아요.\n"
            "\n"
            "기본 구조: [결과식  for 변수 in 반복대상  if 조건]\n"
            "  - '조건에 맞는 것만' 걸러서 → 결과식으로 변환해서 → 리스트에 담아요.\n"
            "\n"
            "조건부 표현식(삼항 연산자)은 '값 자리에서 if-else 로 결과를 고르는 것'이에요:\n"
            "  [x if x > 0 else 0 for x in nums]\n"
            "  → 각 x 가 0보다 크면 x 그대로, 아니면 0 으로 바꿔 담아요.\n"
            "\n"
            "헷갈리기 쉬운 위치 차이:\n"
            "  [x for x in nums if x > 0]       → if 는 for 뒤 → '필터링' (특정 원소 제외)\n"
            "  [x if x > 0 else 0 for x in nums] → if-else 는 for 앞 → '값 변환' (모든 원소 포함)\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "\n"
            "  nums = [-2, 5, -1, 8, 0, -7]\n"
            "    →  양수도 있고 음수도 있는 리스트예요.\n"
            "\n"
            "  pos = [x for x in nums if x > 0]\n"
            "    →  nums 에서 x 를 하나씩 꺼내요.\n"
            "       x > 0 인 것(양수)만 골라서 리스트에 담아요. 결과: [5, 8]\n"
            "\n"
            "  clip = [x if x > 0 else 0 for x in nums]\n"
            "    →  모든 원소를 꺼내되, 양수면 그대로, 음수/0 이면 0 으로 바꿔 담아요.\n"
            "       음수를 '잘라내서(clip)' 0으로 만든다는 의미예요. 결과: [0, 5, 0, 8, 0, 0]\n"
            "\n"
            "  grid = [[r * 3 + c for c in range(3)] for r in range(2)]\n"
            "    →  바깥 리스트 컴프리헨션이 행(r=0,1)을 만들고,\n"
            "       안쪽이 각 행의 열(c=0,1,2) 값을 만들어요.\n"
            "       결과: [[0,1,2],[3,4,5]] (2행 3열 격자)\n"
            "\n"
            "  pairs = [(a, b) for a in [1, 2] for b in ['x', 'y']]\n"
            "    →  for a, for b 가 이중 반복이에요. 앞 for 가 바깥 루프예요.\n"
            "       1과 x, 1과 y, 2와 x, 2와 y 조합이 만들어져요.\n"
            "\n"
            "  square_map = {x: x * x for x in range(1, 5)}\n"
            "    →  {} 를 쓰면 딕셔너리 컴프리헨션이에요.\n"
            "       1→1, 2→4, 3→9, 4→16 매핑을 한 줄에 만들어요.\n"
            "\n"
            "  {len(w) for w in ['a', 'bb', 'cc', 'ddd']}\n"
            "    →  {} 에 콜론(:) 없이 값만 쓰면 집합(set) 컴프리헨션이에요.\n"
            "       각 단어 길이의 집합 {1, 2, 3} 이 만들어져요.\n"
            "\n"
            "주의할 점:\n"
            "  중첩이 2단계 이상 되면 읽기 어려워져요. 그럴 땐 일반 for 반복문이 더 명확해요.\n"
            "  결과 전체를 메모리에 올리므로, 데이터가 수백만 개라면 제너레이터 (x for x in ...) 를 쓰세요."
        ),
        usage=(
            "반복+변환+필터를 간결하게 처리할 때. 코딩테스트에서 입력 파싱(2차원 배열 생성), "
            "인덱스→값 매핑 딕셔너리 만들기, 조건에 맞는 원소만 추리기 등에 매우 자주 쓴다. "
            "일반 for 루프보다 약간 빠르기도 하다."
        ),
        cons=(
            "조건과 중첩이 많아지면 한 줄이 너무 길어져 오히려 읽기 어렵다(2중 이상 중첩은 일반 루프 권장).\n"
            "메모리에 결과 전체를 만들므로 거대한 데이터에는 제너레이터 표현식 (x for ...) 을 고려해야 한다."
        ),
        code=(
            "nums = [-2, 5, -1, 8, 0, -7]\n"
            "\n"
            "# 필터: 양수만\n"
            "pos = [x for x in nums if x > 0]\n"
            "print(pos)                       # [5, 8]\n"
            "\n"
            "# 값 분기: 음수는 0 으로\n"
            "clip = [x if x > 0 else 0 for x in nums]\n"
            "print(clip)                      # [0, 5, 0, 8, 0, 0]\n"
            "\n"
            "# 2차원 배열 생성\n"
            "grid = [[r * 3 + c for c in range(3)] for r in range(2)]\n"
            "print(grid)                      # [[0,1,2],[3,4,5]]\n"
            "\n"
            "# 이중 반복 펼치기\n"
            "pairs = [(a, b) for a in [1, 2] for b in ['x', 'y']]\n"
            "print(pairs)\n"
            "\n"
            "# dict / set 컴프리헨션\n"
            "square_map = {x: x * x for x in range(1, 5)}\n"
            "print(square_map)                # {1:1, 2:4, 3:9, 4:16}\n"
            "print({len(w) for w in ['a', 'bb', 'cc', 'ddd']})  # {1, 2, 3}\n"
        ),
    ),

    Lesson(
        id="py-mid-04",
        lang="python", level="중급",
        title="예외 처리 (try/except/finally)",
        summary="try/except/else/finally · 예외 종류 · raise",
        explanation=(
            "━━ 예외 처리 란? ━━\n"
            "\n"
            "프로그램을 실행하다 보면 예상치 못한 오류가 생길 수 있어요.\n"
            "예를 들어 사용자가 숫자 대신 문자를 입력하거나, 0으로 나누려 하거나,\n"
            "파일이 존재하지 않는 경우처럼요.\n"
            "\n"
            "이런 상황을 '예외(Exception)'라고 하는데, 처리하지 않으면 프로그램이 그냥 멈춰버려요.\n"
            "try/except 는 '혹시 오류가 나도 프로그램을 멈추지 말고 내가 알아서 처리할게요'라는 안전망이에요.\n"
            "\n"
            "비유: 자동차를 운전할 때 '타이어가 펑크 나도 서행해서 안전하게 멈추는' 비상 시스템이에요.\n"
            "\n"
            "구조:\n"
            "  try:     → 실패할 수도 있는 코드를 여기에 써요.\n"
            "  except:  → 오류가 났을 때 대신 실행할 코드예요.\n"
            "  else:    → 오류가 없었을 때만 실행돼요.\n"
            "  finally: → 오류가 있든 없든 무조건 실행돼요(마무리 정리).\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "\n"
            "  def safe_div(a, b):\n"
            "    →  a 를 b 로 나누는 함수인데, b 가 0일 경우를 대비해요.\n"
            "\n"
            "  try:\n"
            "      result = a / b\n"
            "    →  나누기를 시도해요. b 가 0 이면 여기서 예외가 발생해요.\n"
            "\n"
            "  except ZeroDivisionError:\n"
            "    →  '0으로 나누기' 오류가 났을 때만 이 블록이 실행돼요.\n"
            "       ZeroDivisionError 는 파이썬이 정해둔 예외 이름이에요.\n"
            "\n"
            "      print('0 으로 나눌 수 없음')\n"
            "      return None\n"
            "    →  오류 메시지를 출력하고 None(아무것도 없음)을 반환해요.\n"
            "\n"
            "  else:\n"
            "      return result\n"
            "    →  오류가 없었을 때(나누기 성공)만 실행돼요. 결과를 반환해요.\n"
            "\n"
            "  finally:\n"
            "      print(f'나눗셈 시도: {a} / {b}')\n"
            "    →  성공이든 실패든 항상 실행돼요. 로그 남기기, 파일 닫기 등에 써요.\n"
            "\n"
            "  except ValueError as e:\n"
            "    →  ValueError 라는 예외를 잡고, 그 예외 객체를 e 라는 이름으로 받아요.\n"
            "       e 를 출력하면 오류 메시지를 볼 수 있어요.\n"
            "\n"
            "  raise ValueError('나이는 음수가 될 수 없음')\n"
            "    →  직접 예외를 만들어서 던져요.\n"
            "       '이 입력값은 잘못됐다'고 호출자에게 알리는 방법이에요.\n"
            "\n"
            "주요 예외 종류:\n"
            "  ValueError       → 잘못된 값 (int('abc') 처럼 변환 불가)\n"
            "  ZeroDivisionError → 0으로 나누기\n"
            "  IndexError       → 리스트 범위 초과 (list[999])\n"
            "  KeyError         → 딕셔너리에 없는 키\n"
            "  TypeError        → 타입 불일치 ('1' + 1 처럼)\n"
            "  FileNotFoundError → 파일이 없을 때\n"
            "\n"
            "주의할 점:\n"
            "  except: 처럼 타입을 안 쓰면 모든 오류를 다 잡아버려요.\n"
            "  그러면 내 코드의 진짜 버그(오타 등)도 숨겨져서 디버깅이 매우 어려워져요.\n"
            "  항상 잡을 예외 타입을 구체적으로 써주세요."
        ),
        usage=(
            "입력 검증, 파일/네트워크 처리 등 실패 가능성이 있는 작업의 안전한 처리에 쓴다. "
            "코딩테스트에서는 형변환 실패(int('a'))나 0 나눗셈 방어, 그리고 '값이 없을 때까지 입력 받기' "
            "패턴(try: input() except EOFError)에 활용한다."
        ),
        cons=(
            "except: 로 모든 예외를 통째로 잡으면 진짜 버그(오타 등)까지 숨겨 디버깅이 어려워진다 → 구체적 타입 지정.\n"
            "예외 처리는 정상 흐름 제어용이 아니다(반복적으로 예외에 의존하면 느리고 의도가 불명확)."
        ),
        code=(
            "def safe_div(a, b):\n"
            "    try:\n"
            "        result = a / b\n"
            "    except ZeroDivisionError:\n"
            "        print('0 으로 나눌 수 없음')\n"
            "        return None\n"
            "    else:\n"
            "        # 예외가 없을 때만 실행\n"
            "        return result\n"
            "    finally:\n"
            "        # 항상 실행\n"
            "        print(f'나눗셈 시도: {a} / {b}')\n"
            "\n"
            "print(safe_div(10, 2))   # 5.0\n"
            "print(safe_div(10, 0))   # None\n"
            "\n"
            "# 형변환 예외 처리\n"
            "for token in ['10', 'abc', '20']:\n"
            "    try:\n"
            "        print('숫자:', int(token))\n"
            "    except ValueError as e:\n"
            "        print('변환 실패:', token)\n"
            "\n"
            "# 직접 예외 발생\n"
            "def check_age(age):\n"
            "    if age < 0:\n"
            "        raise ValueError('나이는 음수가 될 수 없음')\n"
            "    return age\n"
            "\n"
            "try:\n"
            "    check_age(-5)\n"
            "except ValueError as e:\n"
            "    print('에러:', e)\n"
        ),
    ),

    Lesson(
        id="py-mid-05",
        lang="python", level="중급",
        title="클래스와 객체 (OOP 기초)",
        summary="class · __init__ · self · 메서드 · 상속",
        explanation=(
            "━━ 클래스와 객체 란? ━━\n"
            "\n"
            "클래스는 '설계도'예요. 예를 들어 '강아지'라는 클래스는\n"
            "'이름이 있고, 짖을 수 있다'는 설계도예요.\n"
            "\n"
            "그 설계도로 실제로 만든 것이 '객체(인스턴스)'예요.\n"
            "  Dog 클래스 = 강아지 설계도\n"
            "  d = Dog('바둑이') = 실제 바둑이라는 강아지 한 마리\n"
            "\n"
            "객체는 '속성(데이터)'과 '메서드(행동)'를 함께 가져요.\n"
            "  바둑이.name = '바둑이'  (속성 - 데이터)\n"
            "  바둑이.bark()           (메서드 - 행동)\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "\n"
            "  class Animal:\n"
            "    →  Animal 이라는 설계도(클래스)를 만들기 시작해요.\n"
            "\n"
            "  def __init__(self, name):\n"
            "    →  __init__ 은 '생성자'예요. 객체가 만들어질 때 자동으로 호출돼요.\n"
            "       self 는 '이 객체 자신'을 뜻해요. 항상 첫 번째 매개변수로 써야 해요.\n"
            "\n"
            "  self.name = name\n"
            "    →  넘어온 name 값을 이 객체의 name 속성으로 저장해요.\n"
            "       self.name 이라고 써야 '이 객체만의 name'이 돼요.\n"
            "       그냥 name 만 쓰면 함수 안의 지역변수라서 메서드 밖에서 쓸 수 없어요.\n"
            "\n"
            "  def speak(self):\n"
            "      return f'{self.name} 가 소리를 낸다'\n"
            "    →  speak 메서드는 이 동물이 소리를 내는 행동이에요.\n"
            "       self.name 으로 이 객체의 이름을 가져와 문자열에 넣어요.\n"
            "\n"
            "  class Dog(Animal):\n"
            "    →  Dog 클래스가 Animal 클래스를 '상속'받아요.\n"
            "       부모(Animal)의 모든 속성과 메서드를 자동으로 물려받아요.\n"
            "       새로 추가하거나 바꾸고 싶은 것만 다시 정의하면 돼요.\n"
            "\n"
            "  def speak(self):\n"
            "      return f'{self.name}: 멍멍!'\n"
            "    →  부모의 speak 를 '오버라이딩(덮어쓰기)'했어요.\n"
            "       Dog 객체에서 speak() 를 부르면 이 버전이 실행돼요.\n"
            "\n"
            "  def __str__(self):\n"
            "      return f'Dog(name={self.name})'\n"
            "    →  print(d) 처럼 객체를 출력할 때 보여줄 문자열을 정의해요.\n"
            "       이걸 안 쓰면 <__main__.Dog object at 0x...> 같은 주소가 나와요.\n"
            "\n"
            "  a = Animal('고양이')\n"
            "    →  Animal 설계도로 '고양이'라는 객체를 만들어요.\n"
            "       __init__ 이 자동 호출되어 self.name = '고양이' 가 저장돼요.\n"
            "\n"
            "  isinstance(d, Animal)  →  True\n"
            "    →  d(Dog 객체)가 Animal 타입이기도 한지 확인해요.\n"
            "       자식 클래스의 객체는 부모 타입으로도 인정돼요.\n"
            "\n"
            "주의할 점:\n"
            "  self 를 빠뜨리면 '인스턴스 메서드인데 self 인자가 없다'는 오류가 나요.\n"
            "  클래스 변수(클래스 바로 아래 정의)와 인스턴스 변수(self.xxx)를 혼동하지 마세요.\n"
            "  클래스 변수는 모든 객체가 공유하고, 인스턴스 변수는 객체마다 따로 가져요."
        ),
        usage=(
            "상태와 동작이 함께 묶이는 대상(플레이어, 그래프 노드, 게임 보드 등)을 모델링할 때 쓴다. "
            "코딩테스트에서 자주 쓰진 않지만, 복잡한 시뮬레이션/객체 상태 관리나 우선순위 비교 객체를 "
            "정의할 때 유용하다."
        ),
        cons=(
            "단순한 데이터 묶음에는 클래스가 과하다(딕셔너리/튜플/namedtuple/dataclass 가 더 간단).\n"
            "self 누락, 클래스 변수와 인스턴스 변수 혼동 등 초보자가 실수하기 쉬운 지점이 많다."
        ),
        code=(
            "class Animal:\n"
            "    def __init__(self, name):\n"
            "        self.name = name      # 인스턴스 속성\n"
            "\n"
            "    def speak(self):\n"
            "        return f'{self.name} 가 소리를 낸다'\n"
            "\n"
            "class Dog(Animal):            # 상속\n"
            "    def speak(self):          # 오버라이딩\n"
            "        return f'{self.name}: 멍멍!'\n"
            "\n"
            "    def __str__(self):\n"
            "        return f'Dog(name={self.name})'\n"
            "\n"
            "a = Animal('고양이')\n"
            "d = Dog('바둑이')\n"
            "print(a.speak())     # 고양이 가 소리를 낸다\n"
            "print(d.speak())     # 바둑이: 멍멍!\n"
            "print(d)             # Dog(name=바둑이)  (__str__)\n"
            "print(isinstance(d, Animal))   # True (자식은 부모 타입)\n"
        ),
    ),

    Lesson(
        id="py-mid-06",
        lang="python", level="중급",
        title="모듈/패키지와 import",
        summary="import · from import · as · 표준 라이브러리",
        explanation=(
            "━━ 모듈과 import 란? ━━\n"
            "\n"
            "모듈은 '남이 미리 만들어 둔 도구 상자'예요.\n"
            "수학 함수가 필요할 때 직접 만들지 않고, math 라는 도구 상자를 가져다 쓰면 돼요.\n"
            "\n"
            "비유: 요리할 때 재료를 직접 키우지 않고 마트에서 사오는 것처럼,\n"
            "코드도 다른 사람이 만든 모듈을 가져와(import) 쓰면 시간을 절약할 수 있어요.\n"
            "\n"
            "모듈 = 하나의 .py 파일 (예: math.py)\n"
            "패키지 = 모듈들이 모인 폴더 (예: collections 폴더 안에 여러 .py 파일)\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "\n"
            "  import math\n"
            "    →  math 도구 상자 전체를 가져와요.\n"
            "       이후 math.sqrt(9) 처럼 '상자이름.도구' 형태로 써요.\n"
            "\n"
            "  from itertools import combinations, permutations\n"
            "    →  itertools 상자에서 combinations 와 permutations 만 꺼내요.\n"
            "       이제 itertools. 없이 combinations(...) 바로 써요.\n"
            "\n"
            "  from collections import Counter\n"
            "    →  Counter 만 꺼내요. 글자 빈도 세기에 아주 유용해요.\n"
            "\n"
            "  import random as rnd\n"
            "    →  random 모듈을 rnd 라는 짧은 이름(별칭)으로 가져와요.\n"
            "       이후 rnd.randint(...) 처럼 짧게 써요.\n"
            "\n"
            "  math.gcd(12, 18)\n"
            "    →  12 와 18 의 최대공약수를 구해요. 결과: 6\n"
            "       gcd = Greatest Common Divisor (최대공약수)\n"
            "\n"
            "  math.sqrt(16)\n"
            "    →  16의 제곱근을 구해요. 결과: 4.0 (항상 실수형으로 나와요)\n"
            "\n"
            "  list(combinations([1, 2, 3], 2))\n"
            "    →  [1,2,3] 에서 2개를 고르는 '조합'을 모두 만들어요.\n"
            "       순서가 달라도 같은 것으로 취급해요: (1,2)와 (2,1)은 같은 조합이에요.\n"
            "\n"
            "  list(permutations([1, 2], 2))\n"
            "    →  [1,2] 에서 2개를 고르는 '순열'을 모두 만들어요.\n"
            "       순서가 다르면 다른 것으로 취급해요: (1,2)와 (2,1)은 다른 순열이에요.\n"
            "\n"
            "  rnd.seed(42)\n"
            "    →  난수 생성의 시작점을 42로 고정해요.\n"
            "       같은 시드면 항상 같은 순서로 난수가 나와서 테스트에 유용해요.\n"
            "\n"
            "  Counter('mississippi')\n"
            "    →  각 글자가 몇 번 나왔는지 세어 딕셔너리처럼 보여줘요.\n"
            "\n"
            "  if __name__ == '__main__':\n"
            "    →  이 파일을 직접 실행했을 때만 이 블록이 실행돼요.\n"
            "       다른 파일에서 import 했을 때는 실행되지 않아요.\n"
            "       테스트 코드나 실행 진입점을 이 블록 안에 넣는 관용구예요.\n"
            "\n"
            "코딩테스트 필수 표준 라이브러리:\n"
            "  math        → gcd, sqrt, ceil, floor, inf\n"
            "  itertools   → combinations, permutations, product\n"
            "  collections → deque, defaultdict, Counter\n"
            "  heapq       → 최소/최대 힙(우선순위 큐)\n"
            "  bisect      → 이진탐색으로 정렬 리스트에 삽입/검색\n"
            "  sys         → sys.stdin.readline (빠른 입력)\n"
            "\n"
            "주의할 점:\n"
            "  from 모듈 import * 는 어떤 이름이 들어왔는지 알 수 없어서 이름 충돌이 생겨요.\n"
            "  두 모듈이 서로를 import 하는 '순환 import'는 오류를 내므로 피하세요."
        ),
        usage=(
            "코드를 파일 단위로 분리·재사용할 때 필수. 코딩테스트에서는 표준 라이브러리가 핵심 무기다: "
            "math.gcd, itertools.permutations/combinations, heapq, bisect, collections 등을 알면 "
            "직접 구현할 코드를 크게 줄일 수 있다."
        ),
        cons=(
            "from 모듈 import * 는 어떤 이름이 들어왔는지 불분명해 이름 충돌·가독성 문제가 생긴다(지양).\n"
            "무거운 패키지를 불필요하게 import 하면 시작이 느려지고, 순환 import(서로 import) 는 오류를 낸다."
        ),
        code=(
            "import math\n"
            "from itertools import combinations, permutations\n"
            "from collections import Counter\n"
            "import random as rnd\n"
            "\n"
            "print(math.gcd(12, 18))            # 6\n"
            "print(math.sqrt(16))               # 4.0\n"
            "\n"
            "# 조합/순열 (코딩테스트 단골)\n"
            "print(list(combinations([1, 2, 3], 2)))   # [(1,2),(1,3),(2,3)]\n"
            "print(list(permutations([1, 2], 2)))      # [(1,2),(2,1)]\n"
            "\n"
            "rnd.seed(42)                       # 시드 고정 → 결과 재현 가능\n"
            "print(rnd.randint(1, 100))\n"
            "\n"
            "print(Counter('mississippi'))\n"
            "\n"
            "if __name__ == '__main__':\n"
            "    print('이 파일을 직접 실행했습니다')\n"
        ),
    ),

    Lesson(
        id="py-mid-07",
        lang="python", level="중급",
        title="collections (deque, defaultdict, Counter)",
        summary="양방향 큐 deque · 기본값 딕셔너리 defaultdict · 빈도 Counter",
        explanation=(
            "━━ collections 모듈의 3총사 란? ━━\n"
            "\n"
            "파이썬의 collections 모듈에는 일반 리스트·딕셔너리보다\n"
            "특정 상황에서 훨씬 편하고 빠른 자료구조들이 들어 있어요.\n"
            "\n"
            "[1] deque (데크) — 양쪽이 열린 큐\n"
            "\n"
            "일반 리스트는 앞에서 꺼내기(pop(0))가 O(n) 으로 느려요.\n"
            "데크는 양쪽 끝에서 추가/삭제가 모두 O(1) 로 빠른 '양방향 터널' 같은 구조예요.\n"
            "BFS(너비 우선 탐색)에서 큐로 쓸 때 반드시 deque 를 사용해야 해요.\n"
            "\n"
            "[2] defaultdict — 없는 키도 자동으로 만들어 주는 딕셔너리\n"
            "\n"
            "일반 딕셔너리에서 없는 키에 접근하면 KeyError 가 나요.\n"
            "defaultdict 는 없는 키에 접근하면 지정한 기본값을 자동으로 만들어줘요.\n"
            "예: 마트 창고에서 없는 칸을 달라고 하면 빈 칸을 자동으로 만들어 주는 것처럼요.\n"
            "\n"
            "[3] Counter — 원소 빈도를 자동으로 세는 딕셔너리\n"
            "\n"
            "글자·단어가 몇 번 나왔는지 세는 작업을 한 줄로 해결해요.\n"
            "most_common(n) 으로 가장 많이 나온 n 개를 바로 뽑을 수 있어요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "\n"
            "  q = deque([1, 2, 3])\n"
            "    →  1, 2, 3 이 들어 있는 데크를 만들어요.\n"
            "\n"
            "  q.append(4)\n"
            "    →  오른쪽(뒤)에 4를 추가해요. deque([1, 2, 3, 4])\n"
            "\n"
            "  q.appendleft(0)\n"
            "    →  왼쪽(앞)에 0을 추가해요. deque([0, 1, 2, 3, 4])\n"
            "\n"
            "  q.popleft()\n"
            "    →  왼쪽(앞)에서 꺼내요. 0이 꺼내지고 deque([1, 2, 3, 4]) 가 돼요.\n"
            "       BFS 에서 '큐에서 하나 꺼내기'할 때 이걸 써요.\n"
            "\n"
            "  graph = defaultdict(list)\n"
            "    →  없는 키에 접근하면 자동으로 빈 리스트를 만들어주는 딕셔너리예요.\n"
            "       그래프의 인접 리스트를 만들 때 아주 편해요.\n"
            "\n"
            "  for a, b in [(1, 2), (1, 3), (2, 3)]:\n"
            "      graph[a].append(b)\n"
            "    →  1→[2,3], 2→[3] 인 그래프를 만들어요.\n"
            "       graph[1] 이 없어도 자동으로 [] 가 만들어지므로 append 를 바로 쓸 수 있어요.\n"
            "\n"
            "  cnt = defaultdict(int)\n"
            "  for ch in 'banana':\n"
            "      cnt[ch] += 1\n"
            "    →  각 글자의 등장 횟수를 세요.\n"
            "       cnt['b'] 가 없어도 자동으로 0 이 만들어져서 += 1 이 바로 돼요.\n"
            "\n"
            "  c = Counter('mississippi')\n"
            "    →  mississippi 의 각 글자 빈도를 한 번에 세요.\n"
            "       {'i': 4, 's': 4, 'p': 2, 'm': 1} 같은 형태로 저장돼요.\n"
            "\n"
            "  c.most_common(2)\n"
            "    →  빈도가 가장 높은 2개를 [(글자, 빈도)] 형태로 반환해요.\n"
            "\n"
            "주의할 점:\n"
            "  deque 는 중간 위치 접근(d[5])이 O(n) 으로 느려요.\n"
            "  중간을 자주 접근해야 한다면 일반 리스트가 더 나아요.\n"
            "  defaultdict 는 존재 여부만 확인하려고 d[key] 를 쓰면\n"
            "  키가 없어도 자동으로 생겨버리는 부작용이 있어요. 존재 여부 확인은 key in d 를 쓰세요."
        ),
        usage=(
            "코딩테스트의 핵심 도구다. deque 는 BFS/슬라이딩 윈도우/큐 시뮬레이션에, "
            "defaultdict 는 그래프 인접 리스트(defaultdict(list))나 그룹핑/빈도수 누적에, "
            "Counter 는 빈도수 문제·애너그램·최빈값 찾기에 거의 항상 등장한다."
        ),
        cons=(
            "deque 는 중간 인덱스 접근(d[i])이 O(n) 으로 느리다(임의 접근이 잦으면 리스트가 낫다).\n"
            "defaultdict 는 조회만 해도 키가 생겨 버리는 부작용이 있어, 단순 조회엔 일반 dict.get 이 안전하다."
        ),
        code=(
            "from collections import deque, defaultdict, Counter\n"
            "\n"
            "# deque: 양방향 큐 (BFS 큐로 사용)\n"
            "q = deque([1, 2, 3])\n"
            "q.append(4)        # 오른쪽 추가\n"
            "q.appendleft(0)    # 왼쪽 추가\n"
            "print(q)           # deque([0, 1, 2, 3, 4])\n"
            "print(q.popleft()) # 0 (왼쪽 제거, O(1))\n"
            "print(q.pop())     # 4 (오른쪽 제거)\n"
            "\n"
            "# defaultdict: 그래프 인접 리스트\n"
            "graph = defaultdict(list)\n"
            "for a, b in [(1, 2), (1, 3), (2, 3)]:\n"
            "    graph[a].append(b)\n"
            "print(dict(graph))     # {1: [2, 3], 2: [3]}\n"
            "\n"
            "cnt = defaultdict(int)\n"
            "for ch in 'banana':\n"
            "    cnt[ch] += 1       # 키 확인 없이 누적\n"
            "print(dict(cnt))       # {'b':1,'a':3,'n':2}\n"
            "\n"
            "# Counter: 빈도수 + 최빈값\n"
            "c = Counter('mississippi')\n"
            "print(c.most_common(2))   # [('i', 4), ('s', 4)]\n"
        ),
    ),

    Lesson(
        id="py-mid-08",
        lang="python", level="중급",
        title="문자열 포맷팅 (f-string, join, split 심화)",
        summary="f-string 표현식·정렬·자릿수 · join · split/rsplit/splitlines",
        explanation=(
            "━━ 문자열 포맷팅과 split/join 이란? ━━\n"
            "\n"
            "프로그램에서 결과를 출력하거나 입력을 받을 때 문자열을 많이 다뤄요.\n"
            "파이썬은 이를 위한 편리한 도구들을 제공해요.\n"
            "\n"
            "[f-string] 변수를 문자열 안에 바로 끼워 넣기\n"
            "\n"
            "f'...' 형태로 앞에 f 를 붙이고, 넣고 싶은 값을 {} 안에 써요.\n"
            "이게 가장 현대적이고 빠른 방법이에요.\n"
            "\n"
            "비유: '나는 {나이}살입니다'에서 {나이} 자리를 실제 값으로 바꾸는 것처럼요.\n"
            "\n"
            "[join] 여러 문자열을 하나로 합치기\n"
            "\n"
            "'구분자'.join(리스트) 형태예요.\n"
            "비유: 구슬들을 실로 꿰어서 한 줄로 만드는 것처럼요.\n"
            "\n"
            "[split] 문자열을 잘라서 리스트로 나누기\n"
            "\n"
            "s.split('구분자') 로 잘라요.\n"
            "비유: 콤마로 나열된 '사과,배,포도'를 ['사과','배','포도']로 분리하는 것처럼요.\n"
            "\n"
            "코드 한 줄씩 읽기:\n"
            "\n"
            "  name, score = '홍길동', 92.3456\n"
            "    →  이름과 점수 변수를 만들어요.\n"
            "\n"
            "  f'{name} 님 점수: {score:.1f}점'\n"
            "    →  {score:.1f} 는 소수점 첫째 자리까지만 표시해요.\n"
            "       .1f 에서 1은 소수점 자릿수, f는 실수(float)를 의미해요.\n"
            "       결과: '홍길동 님 점수: 92.3점'\n"
            "\n"
            "  f'합계: {3 + 4}'\n"
            "    →  {} 안에 식(계산식)도 쓸 수 있어요. 결과: '합계: 7'\n"
            "\n"
            "  f'[{name:^8}]'\n"
            "    →  :^8 은 폭 8칸에 가운데 정렬이에요.\n"
            "       :< 는 왼쪽, :> 는 오른쪽 정렬이에요.\n"
            "       결과: '[ 홍길동  ]' (공백으로 채워요)\n"
            "\n"
            "  f'{1234567:,}'\n"
            "    →  천 단위마다 콤마를 넣어요. 결과: '1,234,567'\n"
            "\n"
            "  f'{42:05d} / {255:x}'\n"
            "    →  :05d 는 5자리로 맞추고 앞을 0으로 채워요. 결과: '00042'\n"
            "       :x 는 16진수로 변환해요. 255 → 'ff'\n"
            "\n"
            "  ', '.join(words)\n"
            "    →  words 리스트의 원소들을 ', ' 로 이어 붙여요.\n"
            "       ['파이썬', '자바', 'C++'] → '파이썬, 자바, C++'\n"
            "\n"
            "  ' '.join(map(str, nums))\n"
            "    →  nums 가 숫자 리스트라 먼저 map(str, ...) 로 문자열로 바꿔야 해요.\n"
            "       join 은 문자열 리스트만 받기 때문이에요.\n"
            "       [3, 1, 4] → '3 1 4'\n"
            "\n"
            "  'a,b,c'.split(',')\n"
            "    →  쉼표를 기준으로 잘라요. 결과: ['a', 'b', 'c']\n"
            "\n"
            "  'a b c d'.split(maxsplit=1)\n"
            "    →  최대 1번만 잘라요. 결과: ['a', 'b c d']\n"
            "       첫 번째 공백에서 한 번만 자르고 나머지는 그대로 둬요.\n"
            "\n"
            "  'x=1=2'.rsplit('=', 1)\n"
            "    →  오른쪽에서부터 1번 잘라요. 결과: ['x=1', '2']\n"
            "       왼쪽 split 과 방향이 반대예요.\n"
            "\n"
            "  'line1\\nline2'.splitlines()\n"
            "    →  줄바꿈(\\n) 기준으로 잘라요. 결과: ['line1', 'line2']\n"
            "\n"
            "주의할 점:\n"
            "  f-string 안에서 바깥과 같은 따옴표를 쓰면 문자열이 끊겨요.\n"
            "  바깥이 ' 이면 안은 \", 반대도 마찬가지예요.\n"
            "  join 은 모든 원소가 문자열이어야 해요. 숫자가 섞여 있으면 TypeError 가 나요.\n"
            "  출력이 많을 때 print 를 여러 번 쓰면 느려요.\n"
            "  결과를 리스트에 모아 '\\n'.join(...) 으로 한 번에 print 하면 훨씬 빨라요."
        ),
        usage=(
            "출력 형식 맞추기(표, 소수 자릿수)에 f-string 이 표준이다. 코딩테스트에서는 "
            "여러 줄/여러 값 출력을 '\\n'.join(...) 으로 모아 한 번에 print 하면 출력이 빨라 시간초과를 피한다. "
            "split/map 조합은 입력 파싱의 기본이다."
        ),
        cons=(
            "f-string 안에서 같은 종류의 따옴표를 중첩하면 충돌하므로 바깥/안쪽 따옴표를 다르게 써야 한다.\n"
            "join 은 모든 원소가 문자열이어야 하며(숫자 섞이면 TypeError), 반대로 문자열 + 반복 연결은 느리다."
        ),
        code=(
            "name, score = '홍길동', 92.3456\n"
            "\n"
            "# f-string: 식, 자릿수, 정렬\n"
            "print(f'{name} 님 점수: {score:.1f}점')   # 92.3\n"
            "print(f'합계: {3 + 4}')                    # 식 삽입 → 7\n"
            "print(f'[{name:^8}]')                      # 가운데 정렬 폭 8\n"
            "print(f'{1234567:,}')                      # 천 단위 콤마\n"
            "print(f'{42:05d} / {255:x}')               # 00042 / ff\n"
            "\n"
            "# join: 리스트를 한 줄 문자열로\n"
            "words = ['파이썬', '자바', 'C++']\n"
            "print(', '.join(words))                    # 파이썬, 자바, C++\n"
            "nums = [3, 1, 4, 1, 5]\n"
            "print(' '.join(map(str, nums)))            # 3 1 4 1 5\n"
            "\n"
            "# split 심화\n"
            "print('a,b,c'.split(','))                  # ['a', 'b', 'c']\n"
            "print('a b c d'.split(maxsplit=1))         # ['a', 'b c d']\n"
            "print('x=1=2'.rsplit('=', 1))              # ['x=1', '2']\n"
            "print('line1\\nline2'.splitlines())        # ['line1', 'line2']\n"
        ),
    ),
]
