"""4단계 — 딥러닝 본편 (ds4-04 ~ ds4-10).

ds4-01~03 의 순전파·역전파 위에 실제 학습에 필요한 장치들을 얹는다.
옵티마이저 · 미니배치 · 다중분류 · 과적합 방지 · CNN · RNN.
"""

from engine.models import Lesson

STAGE = "4. 딥러닝"

LESSONS = [

    Lesson(
        id="ds4-04-optimizer",
        lang="datasci", level=STAGE,
        title="옵티마이저 — SGD · 모멘텀 · Adam",
        summary="같은 신경망도 '내려가는 방법'에 따라 속도가 수십 배 다르다",
        explanation=(
            "[개요]\n"
            "ds4-03 에서는 기울기를 구해 그냥 빼기만 했다(w -= lr * dw).\n"
            "이걸 순수 경사하강법(SGD)이라 한다. 단순하지만 느리다.\n"
            "옵티마이저는 '어떻게 내려갈지'를 개선한 알고리즘들이다.\n"
            "\n"
            "[SGD 의 문제 — 골짜기에서 지그재그]\n"
            "  손실 지형이 한 방향은 가파르고 다른 방향은 완만한 골짜기라고 하자.\n"
            "  SGD 는 가파른 쪽으로 크게 튀며 좌우로 진동하고,\n"
            "  정작 가야 할 완만한 방향으로는 조금씩만 나아간다.\n"
            "\n"
            "[모멘텀 — 관성을 준다]\n"
            "    v = 0.9·v + g          (이전 속도를 90% 유지하며 기울기를 더한다)\n"
            "    w = w - lr·v\n"
            "\n"
            "  공이 굴러 내려가는 것과 같다.\n"
            "  · 같은 방향이 반복되면 속도가 쌓여 빨라진다\n"
            "  · 좌우로 진동하는 성분은 서로 상쇄된다\n"
            "  · 작은 웅덩이(지역 최솟값)를 관성으로 넘어간다\n"
            "\n"
            "[Adam — 파라미터마다 보폭을 다르게]\n"
            "  현재 가장 널리 쓰이는 기본값이다. 두 가지를 합쳤다.\n"
            "\n"
            "    m = 0.9·m + 0.1·g        1차 모멘트 = 기울기의 평균 (모멘텀 역할)\n"
            "    v = 0.999·v + 0.001·g²   2차 모멘트 = 기울기 제곱의 평균 (크기 기록)\n"
            "    w = w - lr·m̂ / (√v̂ + ε)\n"
            "\n"
            "  기울기가 계속 컸던 파라미터는 √v 가 커서 보폭이 자동으로 줄고,\n"
            "  기울기가 작았던 파라미터는 보폭이 커진다.\n"
            "  **파라미터마다 학습률이 따로 조정되는 셈이다.**\n"
            "\n"
            "[편향 보정(bias correction)이 필요한 이유]\n"
            "  m 과 v 를 0 에서 시작하므로 학습 초반에는 실제보다 작게 추정된다.\n"
            "  그래서 (1 - 0.9^t) 로 나눠 보정한다. t 가 커지면 분모가 1 에 가까워져\n"
            "  보정이 자연스럽게 사라진다. 이 항을 빼먹으면 초반 학습이 크게 느려진다.\n"
            "\n"
            "[무엇을 쓸까]\n"
            "  · 일단 Adam (lr=0.001 ~ 0.01) 으로 시작한다. 대부분 잘 된다.\n"
            "  · 이미지 분류에서 마지막 성능을 짜낼 때는 SGD+모멘텀이 더 나은 경우도 있다.\n"
            "  · 학습이 안 되면 옵티마이저보다 **학습률**을 먼저 의심하자.\n"
            "\n"
            "[코드 분석]\n"
            "  나선형 데이터 3클래스\n"
            "         → 직선으로는 절대 못 나누는 데이터다. 신경망이 필요한 상황이다.\n"
            "  state['m' + k], state['v' + k]\n"
            "         → 파라미터마다 상태를 따로 들고 있어야 한다.\n"
            "            옵티마이저가 '기억'을 갖는다는 게 SGD 와의 근본적 차이다.\n"
            "  mh = m / (1 - 0.9 ** t)\n"
            "         → 편향 보정. t 는 1부터 시작해야 한다. 0 이면 0으로 나누기가 된다.\n"
            "  np.sqrt(vh) + 1e-8\n"
            "         → ε. v 가 0 일 때 0 으로 나누는 것을 막는다.\n"
            "  같은 초기 가중치(seed=1)로 세 방법 비교\n"
            "         → 출발점이 같아야 공정한 비교가 된다.\n"
            "\n"
            "[유의 사항]\n"
            "  • Adam 은 학습률이 SGD 보다 훨씬 작아야 한다. 보통 0.001 근처다.\n"
            "    SGD 감각으로 0.5 를 주면 발산한다.\n"
            "  • 옵티마이저를 바꿔도 안 되면 문제는 다른 곳에 있다.\n"
            "    데이터 전처리·초기화·모델 구조를 점검하자."
        ),
        usage="모든 신경망 학습의 필수 선택. PyTorch 에서도 optim.Adam(...) 한 줄로 쓰지만 원리는 이것이다.",
        cons="Adam 이 항상 최선은 아니다. 일부 문제에서는 SGD+모멘텀이 더 잘 일반화된다는 보고가 많다.",
        code=(
            "import numpy as np\n"
            "\n"
            "def spiral(n_per, k, seed=0):\n"
            "    \"\"\"나선형 데이터 — 직선으로는 절대 나눌 수 없다\"\"\"\n"
            "    r = np.random.default_rng(seed)\n"
            "    X, y = [], []\n"
            "    for c in range(k):\n"
            "        rad = np.linspace(0.15, 1.0, n_per)\n"
            "        th = np.linspace(c * 4, (c + 1) * 4, n_per) + r.normal(0, 0.25, n_per)\n"
            "        X.append(np.c_[rad * np.sin(th), rad * np.cos(th)])\n"
            "        y.append(np.full(n_per, c))\n"
            "    return np.vstack(X), np.concatenate(y)\n"
            "\n"
            "X, y = spiral(100, 3, seed=0)\n"
            "print('데이터:', X.shape, '· 클래스 3개')\n"
            "\n"
            "def softmax(z):\n"
            "    e = np.exp(z - z.max(axis=1, keepdims=True))\n"
            "    return e / e.sum(axis=1, keepdims=True)\n"
            "\n"
            "def train(opt, epochs=800, H=64, seed=1):\n"
            "    r = np.random.default_rng(seed)\n"
            "    P = {'W1': r.normal(0, 1, (2, H)) * np.sqrt(2 / 2), 'b1': np.zeros(H),\n"
            "         'W2': r.normal(0, 1, (H, 3)) * np.sqrt(2 / H), 'b2': np.zeros(3)}\n"
            "    S = {('m' + k): np.zeros_like(v) for k, v in P.items()}\n"
            "    S.update({('v' + k): np.zeros_like(v) for k, v in P.items()})\n"
            "\n"
            "    Y = np.zeros((len(y), 3))\n"
            "    Y[np.arange(len(y)), y] = 1\n"
            "    n = len(X)\n"
            "    hist = []\n"
            "\n"
            "    for t in range(1, epochs + 1):\n"
            "        z1 = X @ P['W1'] + P['b1']\n"
            "        a1 = np.maximum(0, z1)\n"
            "        prob = softmax(a1 @ P['W2'] + P['b2'])\n"
            "        hist.append(float(-np.log(np.clip(prob[np.arange(n), y], 1e-9, 1)).mean()))\n"
            "\n"
            "        dz2 = (prob - Y) / n\n"
            "        da1 = dz2 @ P['W2'].T\n"
            "        dz1 = da1 * (z1 > 0)\n"
            "        G = {'W2': a1.T @ dz2, 'b2': dz2.sum(axis=0),\n"
            "             'W1': X.T @ dz1, 'b1': dz1.sum(axis=0)}\n"
            "\n"
            "        for k in P:\n"
            "            g = G[k]\n"
            "            if opt == 'sgd':\n"
            "                P[k] -= 0.5 * g\n"
            "            elif opt == 'momentum':\n"
            "                S['m' + k] = 0.9 * S['m' + k] + g\n"
            "                P[k] -= 0.5 * S['m' + k]\n"
            "            else:                                   # adam\n"
            "                S['m' + k] = 0.9 * S['m' + k] + 0.1 * g\n"
            "                S['v' + k] = 0.999 * S['v' + k] + 0.001 * (g * g)\n"
            "                mh = S['m' + k] / (1 - 0.9 ** t)     # 편향 보정\n"
            "                vh = S['v' + k] / (1 - 0.999 ** t)\n"
            "                P[k] -= 0.05 * mh / (np.sqrt(vh) + 1e-8)\n"
            "\n"
            "    a1 = np.maximum(0, X @ P['W1'] + P['b1'])\n"
            "    acc = float((softmax(a1 @ P['W2'] + P['b2']).argmax(axis=1) == y).mean())\n"
            "    return hist, acc\n"
            "\n"
            "print('\\n옵티마이저   100에폭    400에폭    800에폭   최종정확도')\n"
            "for opt in ['sgd', 'momentum', 'adam']:\n"
            "    h, acc = train(opt)\n"
            "    print(f'{opt:10s}  {h[100]:8.4f}  {h[400]:8.4f}  {h[-1]:8.4f}   {acc:8.3f}')\n"
            "\n"
            "print('\\n→ 100 에폭 시점의 손실을 보자.')\n"
            "print('  SGD 0.35 · 모멘텀 0.03 · Adam 0.008 — 40배 이상 차이난다.')\n"
            "print('  똑같은 신경망, 똑같은 초기값인데 내려가는 방법만 바꾼 결과다.')\n"
        ),
    ),

    Lesson(
        id="ds4-05-minibatch",
        lang="datasci", level=STAGE,
        title="미니배치 학습",
        summary="데이터를 조금씩 나눠 자주 갱신하기",
        explanation=(
            "[개요]\n"
            "지금까지는 매 에폭마다 전체 데이터로 기울기를 구했다(배치 경사하강법).\n"
            "데이터가 100만 개라면 한 번 갱신하려고 100만 개를 다 계산해야 한다.\n"
            "\n"
            "미니배치는 데이터를 작게 쪼개(보통 32~256개) 조각마다 갱신한다.\n"
            "\n"
            "[세 가지 방식]\n"
            "  배치(Batch)     : 전체를 보고 1번 갱신    정확하지만 느리다. 메모리도 부족해진다.\n"
            "  확률적(SGD)     : 1개 보고 1번 갱신       매우 불안정하게 요동친다.\n"
            "  미니배치        : 32~256개 보고 1번 갱신  둘의 절충. **실무 표준이다.**\n"
            "\n"
            "[미니배치의 장점]\n"
            "  1) 메모리 : 배치 크기만큼만 메모리에 올리면 된다. GPU 는 메모리가 한정적이다.\n"
            "  2) 속도   : 같은 데이터를 한 번 훑는 동안 갱신이 여러 번 일어난다.\n"
            "              데이터 1000개 · 배치 100 이면 1에폭에 10번 갱신된다.\n"
            "  3) 일반화 : 배치마다 기울기가 조금씩 달라 생기는 잡음이\n"
            "              오히려 얕은 지역 최솟값을 빠져나오게 돕는다.\n"
            "\n"
            "[용어 정리 — 자주 헷갈린다]\n"
            "  · 에폭(epoch)     : 전체 데이터를 한 번 다 본 것\n"
            "  · 배치 크기       : 한 번 갱신에 쓰는 데이터 개수\n"
            "  · 스텝(iteration) : 갱신 1회\n"
            "\n"
            "    데이터 1000개, 배치 100  →  1 에폭 = 10 스텝\n"
            "\n"
            "[배치 크기를 어떻게 정하나]\n"
            "  · 32, 64, 128, 256 처럼 2의 거듭제곱을 쓴다(GPU 효율).\n"
            "  · 크면 : 안정적이지만 갱신 횟수가 줄고 메모리를 많이 쓴다\n"
            "  · 작으면: 잡음이 많지만 갱신이 잦고 일반화에 유리할 수 있다\n"
            "  · 배치를 키우면 학습률도 함께 키우는 게 보통이다.\n"
            "\n"
            "[코드 분석]\n"
            "  perm = r.permutation(n)\n"
            "         → **에폭마다 반드시 섞는다.** 안 섞으면 배치 구성이 매번 같아\n"
            "            학습이 편향된다. 데이터가 클래스 순으로 정렬돼 있으면 치명적이다.\n"
            "  for s in range(0, n, bs)\n"
            "         → bs 간격으로 잘라 배치를 만든다. 마지막 배치는 더 작을 수 있다.\n"
            "  dz2 = (prob - Y_b) / len(idx)\n"
            "         → **배치 크기로 나눈다.** 전체 n 으로 나누면 기울기가\n"
            "            배치 크기에 따라 달라져 학습률 감각이 무너진다. 흔한 실수다.\n"
            "  스텝 수 비교\n"
            "         → 같은 20 에폭이라도 배치 크기에 따라 갱신 횟수가 크게 다르다.\n"
            "            배치 16 은 300 개 데이터에서 에폭당 19 스텝, 총 380 스텝이다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 배치 크기를 바꾸면 학습률도 다시 조정해야 한다. 둘은 묶여 있다.\n"
            "  • 배치가 너무 작으면(1~4) 기울기 잡음이 커서 수렴이 불안정하다.\n"
            "  • 검증·추론할 때는 배치를 나눌 필요가 없다(기울기를 안 구하므로).\n"
            "    다만 메모리가 부족하면 나눠서 계산한다."
        ),
        usage="딥러닝 학습의 기본 형태. PyTorch 의 DataLoader 가 하는 일이 정확히 이것이다.",
        cons="배치가 작으면 기울기가 요동쳐 수렴이 불안정하다. 배치 크기와 학습률을 함께 조정해야 한다.",
        code=(
            "import numpy as np\n"
            "\n"
            "def spiral(n_per, k, seed=0):\n"
            "    r = np.random.default_rng(seed)\n"
            "    X, y = [], []\n"
            "    for c in range(k):\n"
            "        rad = np.linspace(0.15, 1.0, n_per)\n"
            "        th = np.linspace(c * 4, (c + 1) * 4, n_per) + r.normal(0, 0.25, n_per)\n"
            "        X.append(np.c_[rad * np.sin(th), rad * np.cos(th)])\n"
            "        y.append(np.full(n_per, c))\n"
            "    return np.vstack(X), np.concatenate(y)\n"
            "\n"
            "X, y = spiral(100, 3, seed=0)\n"
            "n = len(X)\n"
            "Y = np.zeros((n, 3))\n"
            "Y[np.arange(n), y] = 1\n"
            "\n"
            "def softmax(z):\n"
            "    e = np.exp(z - z.max(axis=1, keepdims=True))\n"
            "    return e / e.sum(axis=1, keepdims=True)\n"
            "\n"
            "def train(batch_size, epochs=20, H=64, lr=0.05, seed=1):\n"
            "    r = np.random.default_rng(seed)\n"
            "    P = {'W1': r.normal(0, 1, (2, H)) * np.sqrt(2 / 2), 'b1': np.zeros(H),\n"
            "         'W2': r.normal(0, 1, (H, 3)) * np.sqrt(2 / H), 'b2': np.zeros(3)}\n"
            "    S = {('m' + k): np.zeros_like(v) for k, v in P.items()}\n"
            "    S.update({('v' + k): np.zeros_like(v) for k, v in P.items()})\n"
            "\n"
            "    bs = batch_size if batch_size > 0 else n     # 0 이면 전체 배치\n"
            "    step = 0\n"
            "    for ep in range(epochs):\n"
            "        perm = r.permutation(n)                   # 에폭마다 반드시 섞는다\n"
            "        for s in range(0, n, bs):\n"
            "            idx = perm[s:s + bs]\n"
            "            Xb, Yb = X[idx], Y[idx]\n"
            "            step += 1\n"
            "\n"
            "            z1 = Xb @ P['W1'] + P['b1']\n"
            "            a1 = np.maximum(0, z1)\n"
            "            prob = softmax(a1 @ P['W2'] + P['b2'])\n"
            "\n"
            "            dz2 = (prob - Yb) / len(idx)          # 배치 크기로 나눈다\n"
            "            da1 = dz2 @ P['W2'].T\n"
            "            dz1 = da1 * (z1 > 0)\n"
            "            G = {'W2': a1.T @ dz2, 'b2': dz2.sum(axis=0),\n"
            "                 'W1': Xb.T @ dz1, 'b1': dz1.sum(axis=0)}\n"
            "\n"
            "            for k in P:\n"
            "                g = G[k]\n"
            "                S['m' + k] = 0.9 * S['m' + k] + 0.1 * g\n"
            "                S['v' + k] = 0.999 * S['v' + k] + 0.001 * (g * g)\n"
            "                P[k] -= lr * (S['m' + k] / (1 - 0.9 ** step)) / (\n"
            "                    np.sqrt(S['v' + k] / (1 - 0.999 ** step)) + 1e-8)\n"
            "\n"
            "    a1 = np.maximum(0, X @ P['W1'] + P['b1'])\n"
            "    prob = softmax(a1 @ P['W2'] + P['b2'])\n"
            "    loss = float(-np.log(np.clip(prob[np.arange(n), y], 1e-9, 1)).mean())\n"
            "    acc = float((prob.argmax(axis=1) == y).mean())\n"
            "    return step, loss, acc\n"
            "\n"
            "print(f'데이터 {n}개 · 20 에폭 고정 · 같은 초기 가중치\\n')\n"
            "print('배치크기   총 스텝수     손실    정확도')\n"
            "for bs in [0, 128, 64, 32, 16]:\n"
            "    step, loss, acc = train(bs)\n"
            "    label = f'전체({n})' if bs == 0 else str(bs)\n"
            "    print(f'{label:>8s}   {step:8d}   {loss:7.4f}   {acc:6.3f}')\n"
            "\n"
            "print('\\n→ 같은 20 에폭이라도 배치가 작을수록 갱신 횟수가 많아')\n"
            "print('  훨씬 빠르게 손실이 내려간다.')\n"
            "print('  전체 배치는 20번만 갱신되므로 거의 학습되지 않았다.')\n"
        ),
    ),

    Lesson(
        id="ds4-06-multiclass",
        lang="datasci", level=STAGE,
        title="다중 분류 — softmax + 교차엔트로피",
        summary="클래스가 3개 이상일 때 · 원-핫 인코딩",
        explanation=(
            "[개요]\n"
            "ds4-03 의 XOR 은 0/1 이진 분류였다.\n"
            "손글씨 숫자(0~9)처럼 클래스가 여러 개면 출력층을 바꿔야 한다.\n"
            "\n"
            "    이진 분류 : 출력 1개 + sigmoid  + 이진 교차엔트로피\n"
            "    다중 분류 : 출력 K개 + softmax  + 교차엔트로피\n"
            "\n"
            "[softmax — 점수를 확률로]\n"
            "    softmax(z)ᵢ = e^zᵢ / Σ e^zⱼ\n"
            "\n"
            "  · 모든 값이 0~1 이 되고 합이 정확히 1 이다 → 확률로 읽을 수 있다\n"
            "  · 큰 값을 더 크게 강조한다(지수함수라서)\n"
            "  · [2.0, 1.0, 0.1] → [0.659, 0.242, 0.099]\n"
            "\n"
            "[원-핫 인코딩]\n"
            "  정답 라벨 2 를 그대로 쓰면 '2는 1보다 크다'는 잘못된 순서가 생긴다.\n"
            "  그래서 해당 위치만 1인 벡터로 바꾼다.\n"
            "\n"
            "    클래스 2 (전체 3개) → [0, 1, 0]\n"
            "\n"
            "  개·고양이·새 사이에 크기 관계가 없다는 것을 표현하는 방법이다.\n"
            "\n"
            "[교차엔트로피]\n"
            "    L = -Σ yᵢ·log(pᵢ)\n"
            "\n"
            "  원-핫이라 정답 위치만 남는다 → L = -log(정답 클래스의 확률)\n"
            "  정답에 0.9 를 줬으면 손실 0.105, 0.1 을 줬으면 2.303 이다.\n"
            "\n"
            "  구현 팁: 원-핫 행렬을 만들지 않고 prob[range(n), y] 로\n"
            "  정답 위치 확률만 뽑으면 메모리와 계산이 절약된다.\n"
            "\n"
            "[기울기는 또 단순하다]\n"
            "    ∂L/∂z = p - y      (softmax + 교차엔트로피 조합)\n"
            "\n"
            "  sigmoid + BCE 와 완전히 같은 형태다.\n"
            "  이 두 조합이 표준이 된 데는 이런 실용적 이유가 있다.\n"
            "\n"
            "[코드 분석]\n"
            "  z - z.max(axis=1, keepdims=True)\n"
            "         → 오버플로 방지. z 가 1000 이면 e^1000 은 inf 가 된다.\n"
            "            최댓값을 빼도 softmax 결과는 수학적으로 동일하다.\n"
            "            keepdims=True 를 빼면 모양이 어긋나 브로드캐스팅이 틀어진다.\n"
            "  Y[np.arange(n), y] = 1\n"
            "         → 원-핫 만들기. 행 번호와 클래스 번호를 짝지어 1을 넣는다.\n"
            "  prob[np.arange(n), y]\n"
            "         → 각 행에서 정답 클래스의 확률만 뽑는다.\n"
            "  혼동 행렬\n"
            "         → 어느 클래스를 어느 클래스로 착각하는지 본다.\n"
            "            전체 정확도만 보면 특정 클래스만 계속 틀리는 것을 놓친다.\n"
            "\n"
            "[유의 사항]\n"
            "  • softmax 는 '클래스가 서로 배타적'일 때 쓴다.\n"
            "    사진에 개와 고양이가 동시에 있을 수 있는 문제라면\n"
            "    각 클래스마다 sigmoid 를 따로 쓴다(다중 라벨 분류).\n"
            "  • 클래스가 불균형하면 정확도는 의미가 없다. 클래스별 재현율을 보자.\n"
            "  • PyTorch 의 CrossEntropyLoss 는 내부에 softmax 가 이미 들어 있다.\n"
            "    모델 출력에 softmax 를 또 씌우면 학습이 망가진다. 아주 흔한 실수다."
        ),
        usage="이미지 분류, 문서 분류, 다음 단어 예측 등 클래스가 여럿인 모든 문제. LLM 의 출력층도 이것이다.",
        cons="클래스 수가 수만 개면(어휘 전체 등) softmax 계산이 병목이 된다. 그때는 근사 기법을 쓴다.",
        code=(
            "import numpy as np\n"
            "\n"
            "def spiral(n_per, k, seed=0):\n"
            "    r = np.random.default_rng(seed)\n"
            "    X, y = [], []\n"
            "    for c in range(k):\n"
            "        rad = np.linspace(0.15, 1.0, n_per)\n"
            "        th = np.linspace(c * 4, (c + 1) * 4, n_per) + r.normal(0, 0.25, n_per)\n"
            "        X.append(np.c_[rad * np.sin(th), rad * np.cos(th)])\n"
            "        y.append(np.full(n_per, c))\n"
            "    return np.vstack(X), np.concatenate(y)\n"
            "\n"
            "K = 4\n"
            "X, y = spiral(90, K, seed=1)\n"
            "n = len(X)\n"
            "print(f'{K}개 클래스 · 데이터 {n}개')\n"
            "\n"
            "# 원-핫 인코딩\n"
            "Y = np.zeros((n, K))\n"
            "Y[np.arange(n), y] = 1\n"
            "print('\\n원-핫 예시')\n"
            "for i in [0, 90, 180, 270]:\n"
            "    print(f'  라벨 {y[i]} → {Y[i].astype(int)}')\n"
            "\n"
            "def softmax(z):\n"
            "    e = np.exp(z - z.max(axis=1, keepdims=True))\n"
            "    return e / e.sum(axis=1, keepdims=True)\n"
            "\n"
            "print('\\nsoftmax([2.0, 1.0, 0.1]) =',\n"
            "      softmax(np.array([[2.0, 1.0, 0.1]]))[0].round(3),\n"
            "      '  합계', float(softmax(np.array([[2.0, 1.0, 0.1]])).sum()))\n"
            "\n"
            "r = np.random.default_rng(1)\n"
            "H = 64\n"
            "P = {'W1': r.normal(0, 1, (2, H)) * np.sqrt(2 / 2), 'b1': np.zeros(H),\n"
            "     'W2': r.normal(0, 1, (H, K)) * np.sqrt(2 / H), 'b2': np.zeros(K)}\n"
            "S = {('m' + k): np.zeros_like(v) for k, v in P.items()}\n"
            "S.update({('v' + k): np.zeros_like(v) for k, v in P.items()})\n"
            "\n"
            "print('\\nepoch      손실   정확도')\n"
            "for t in range(1, 1501):\n"
            "    z1 = X @ P['W1'] + P['b1']\n"
            "    a1 = np.maximum(0, z1)\n"
            "    prob = softmax(a1 @ P['W2'] + P['b2'])\n"
            "\n"
            "    # 교차엔트로피 = -log(정답 클래스의 확률)\n"
            "    loss = float(-np.log(np.clip(prob[np.arange(n), y], 1e-9, 1)).mean())\n"
            "\n"
            "    dz2 = (prob - Y) / n          # softmax + CE 의 기울기\n"
            "    da1 = dz2 @ P['W2'].T\n"
            "    dz1 = da1 * (z1 > 0)\n"
            "    G = {'W2': a1.T @ dz2, 'b2': dz2.sum(axis=0),\n"
            "         'W1': X.T @ dz1, 'b1': dz1.sum(axis=0)}\n"
            "    for k in P:\n"
            "        S['m' + k] = 0.9 * S['m' + k] + 0.1 * G[k]\n"
            "        S['v' + k] = 0.999 * S['v' + k] + 0.001 * (G[k] * G[k])\n"
            "        P[k] -= 0.05 * (S['m' + k] / (1 - 0.9 ** t)) / (\n"
            "            np.sqrt(S['v' + k] / (1 - 0.999 ** t)) + 1e-8)\n"
            "\n"
            "    if t % 300 == 0:\n"
            "        acc = float((prob.argmax(axis=1) == y).mean())\n"
            "        print(f'{t:5d}  {loss:8.4f}  {acc:7.3f}')\n"
            "\n"
            "# 혼동 행렬\n"
            "pred = softmax(np.maximum(0, X @ P['W1'] + P['b1']) @ P['W2'] + P['b2']).argmax(axis=1)\n"
            "cm = np.zeros((K, K), dtype=int)\n"
            "for a, b in zip(y, pred):\n"
            "    cm[a, b] += 1\n"
            "print('\\n-- 혼동 행렬 (행=실제, 열=예측) --')\n"
            "print('      ' + ''.join(f'예측{j}  ' for j in range(K)))\n"
            "for i in range(K):\n"
            "    print(f'실제{i}  ' + ''.join(f'{v:5d}  ' for v in cm[i]))\n"
            "print('\\n대각선이 맞힌 개수다. 대각선 밖의 숫자가 어떤 착각을 하는지 알려준다.')\n"
            "off = [(i, j, int(cm[i, j])) for i in range(K) for j in range(K)\n"
            "       if i != j and cm[i, j] > 0]\n"
            "if off:\n"
            "    i, j, v = max(off, key=lambda t: t[2])\n"
            "    print(f'가장 잦은 착각: 실제 {i} → 예측 {j} 가 {v}건.')\n"
            "    print('나선 데이터라 두 클래스의 끝이 맞닿는 지점에서 헷갈린 것이다.')\n"
            "    print('전체 정확도만 봤다면 이 패턴을 놓쳤을 것이다.')\n"
        ),
    ),

    Lesson(
        id="ds4-07-regular",
        lang="datasci", level=STAGE,
        title="과적합 방지 — L2 · 드롭아웃 · 조기종료",
        summary="신경망은 데이터를 통째로 외울 수 있다",
        explanation=(
            "[개요]\n"
            "신경망은 파라미터가 많아 훈련 데이터를 통째로 암기할 수 있다.\n"
            "**잘못된 라벨까지 외운다.** 그래서 과적합 방지 장치가 반드시 필요하다.\n"
            "\n"
            "[이 레슨의 실험 설계]\n"
            "  훈련 데이터의 라벨 중 약 17% 를 일부러 무작위로 바꿨다.\n"
            "  현실의 데이터에도 잘못 붙은 라벨은 항상 있다.\n"
            "\n"
            "  규제 없는 모델은 훈련 정확도 **1.000** 을 찍는다.\n"
            "  오염된 라벨까지 100% 맞혔다는 뜻이다 — 외운 것이다.\n"
            "  그 대가로 검증 정확도는 0.731 로 떨어진다.\n"
            "\n"
            "[1) L2 정규화 (가중치 감쇠, weight decay)]\n"
            "    손실에 λ·Σw² 를 더한다 → 기울기에 λ·w 를 더하는 것과 같다\n"
            "\n"
            "  가중치가 커지지 못하게 눌러 결정 경계를 부드럽게 만든다.\n"
            "  3단계 Ridge 회귀와 완전히 같은 원리다.\n"
            "\n"
            "[2) 드롭아웃 (Dropout)]\n"
            "  학습할 때마다 뉴런 일부를 **무작위로 꺼버린다.**\n"
            "\n"
            "  · 특정 뉴런에만 의존하지 못하게 만든다\n"
            "  · 매번 다른 구조의 신경망을 학습하는 셈이라 앙상블 효과가 난다\n"
            "  · **추론할 때는 끄지 않는다.** 학습 때만 쓰는 장치다.\n"
            "\n"
            "  역스케일링(inverted dropout)\n"
            "    학습 때 살아남은 뉴런을 1/(1-p) 배로 키워 놓는다.\n"
            "    그러면 출력의 기댓값이 유지되어 추론 때 아무 보정도 필요 없다.\n"
            "    코드의 `/(1 - drop)` 이 이것이다.\n"
            "\n"
            "[3) 조기 종료 (Early Stopping)]\n"
            "  검증 손실이 더 이상 줄지 않으면 학습을 멈춘다.\n"
            "  가장 간단하면서 효과적이다. 추가 비용도 거의 없다.\n"
            "  '몇 에폭 참을지(patience)'를 정해두고, 그 사이 최고 성능 시점의\n"
            "  가중치를 저장해뒀다가 되돌린다.\n"
            "\n"
            "[4) 그 밖에]\n"
            "  · 데이터 증강 : 이미지를 뒤집고 자르고 회전시켜 데이터를 늘린다. 가장 근본적이다.\n"
            "  · 배치 정규화 : 층마다 출력 분포를 정규화한다. 부수적으로 규제 효과도 있다.\n"
            "  · 모델 축소   : 애초에 파라미터를 줄인다.\n"
            "\n"
            "[코드 분석]\n"
            "  dW2 = a1.T @ dz2 + l2 * W2\n"
            "         → L2 의 기울기 항. 손실에 (λ/2)·Σw² 를 더한 것에 해당한다.\n"
            "            **편향 b 에는 걸지 않는다.** 편향은 과적합의 원인이 아니다.\n"
            "  mask = (rr.random(a1.shape) > drop) / (1 - drop)\n"
            "         → 드롭아웃 마스크. True/False 가 1/0 이 되고, 살아남은 것은\n"
            "            1/(1-p) 배로 커진다. 역스케일링이 한 줄에 들어 있다.\n"
            "  da1 = da1 * mask\n"
            "         → **역전파에도 같은 마스크를 적용해야 한다.**\n"
            "            꺼진 뉴런으로는 기울기도 흐르면 안 된다. 빠뜨리기 쉬운 부분이다.\n"
            "  acc(tr, y_tr) vs acc(te, y[te])\n"
            "         → 훈련은 **오염된 라벨** 기준, 검증은 **정답 라벨** 기준으로 잰다.\n"
            "            훈련 정확도 1.000 은 '오염까지 외웠다'는 뜻이다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 규제가 과하면 과소적합이 된다. 아래 결과에서 λ=0.01 은\n"
            "    오히려 규제 없는 것보다 나쁘다. 적정값은 검증으로 찾아야 한다.\n"
            "  • 드롭아웃과 배치정규화를 함께 쓰면 충돌하는 경우가 있다.\n"
            "  • 추론 시 드롭아웃을 끄는 것을 잊으면 결과가 매번 달라진다.\n"
            "    PyTorch 에서 model.eval() 을 부르는 이유가 이것이다."
        ),
        usage="딥러닝 실무의 핵심 기술. 모델을 키우기 전에 규제부터 제대로 걸어야 한다.",
        cons="어떤 규제를 얼마나 걸지는 데이터마다 다르다. 결국 실험으로 찾아야 한다.",
        code=(
            "import numpy as np\n"
            "\n"
            "def spiral(n_per, k, seed=0):\n"
            "    r = np.random.default_rng(seed)\n"
            "    X, y = [], []\n"
            "    for c in range(k):\n"
            "        rad = np.linspace(0.15, 1.0, n_per)\n"
            "        th = np.linspace(c * 4, (c + 1) * 4, n_per) + r.normal(0, 0.5, n_per)\n"
            "        X.append(np.c_[rad * np.sin(th), rad * np.cos(th)])\n"
            "        y.append(np.full(n_per, c))\n"
            "    return np.vstack(X), np.concatenate(y)\n"
            "\n"
            "X, y = spiral(80, 3, seed=0)\n"
            "r = np.random.default_rng(5)\n"
            "idx = r.permutation(len(X))\n"
            "tr, te = idx[:80], idx[80:]\n"
            "\n"
            "# 훈련 라벨의 일부를 일부러 오염 (현실의 잘못된 라벨)\n"
            "y_tr = y[tr].copy()\n"
            "flip = r.choice(len(tr), int(len(tr) * 0.25), replace=False)\n"
            "y_tr[flip] = r.integers(0, 3, len(flip))\n"
            "print(f'훈련 {len(tr)}개 중 라벨 오염 {float((y_tr != y[tr]).mean()):.1%}')\n"
            "print('→ 규제가 없으면 이 잘못된 라벨까지 외워버린다\\n')\n"
            "\n"
            "def softmax(z):\n"
            "    e = np.exp(z - z.max(axis=1, keepdims=True))\n"
            "    return e / e.sum(axis=1, keepdims=True)\n"
            "\n"
            "def run(l2=0.0, drop=0.0, epochs=4000, H=128, seed=1):\n"
            "    rr = np.random.default_rng(seed)\n"
            "    W1 = rr.normal(0, 1, (2, H)) * np.sqrt(2 / 2)\n"
            "    b1 = np.zeros(H)\n"
            "    W2 = rr.normal(0, 1, (H, 3)) * np.sqrt(2 / H)\n"
            "    b2 = np.zeros(3)\n"
            "    Y = np.zeros((len(tr), 3))\n"
            "    Y[np.arange(len(tr)), y_tr] = 1\n"
            "    Xt, n = X[tr], len(tr)\n"
            "    st = [np.zeros_like(v) for v in (W1, W1, b1, b1, W2, W2, b2, b2)]\n"
            "    mW1, vW1, mb1, vb1, mW2, vW2, mb2, vb2 = st\n"
            "\n"
            "    for t in range(1, epochs + 1):\n"
            "        z1 = Xt @ W1 + b1\n"
            "        a1 = np.maximum(0, z1)\n"
            "        if drop > 0:\n"
            "            mask = (rr.random(a1.shape) > drop) / (1 - drop)   # 역스케일링\n"
            "            a1 = a1 * mask\n"
            "        prob = softmax(a1 @ W2 + b2)\n"
            "\n"
            "        dz2 = (prob - Y) / n\n"
            "        dW2 = a1.T @ dz2 + l2 * W2        # L2 는 가중치에만 (편향 제외)\n"
            "        db2 = dz2.sum(axis=0)\n"
            "        da1 = dz2 @ W2.T\n"
            "        if drop > 0:\n"
            "            da1 = da1 * mask               # 역전파에도 같은 마스크\n"
            "        dz1 = da1 * (z1 > 0)\n"
            "        dW1 = Xt.T @ dz1 + l2 * W1\n"
            "        db1 = dz1.sum(axis=0)\n"
            "\n"
            "        for p, g, m, v in [(W1, dW1, mW1, vW1), (b1, db1, mb1, vb1),\n"
            "                           (W2, dW2, mW2, vW2), (b2, db2, mb2, vb2)]:\n"
            "            m *= 0.9\n"
            "            m += 0.1 * g\n"
            "            v *= 0.999\n"
            "            v += 0.001 * (g * g)\n"
            "            p -= 0.01 * (m / (1 - 0.9 ** t)) / (\n"
            "                np.sqrt(v / (1 - 0.999 ** t)) + 1e-8)\n"
            "\n"
            "    def acc(part, lab):\n"
            "        a = np.maximum(0, X[part] @ W1 + b1)     # 추론 때는 드롭아웃 끔\n"
            "        return float((softmax(a @ W2 + b2).argmax(axis=1) == lab).mean())\n"
            "\n"
            "    return acc(tr, y_tr), acc(te, y[te])\n"
            "\n"
            "print('설정                  훈련(오염기준)   검증(정답기준)')\n"
            "results = []\n"
            "for name, kw in [('규제 없음', {}),\n"
            "                 ('L2  λ=0.001', {'l2': 0.001}),\n"
            "                 ('L2  λ=0.01', {'l2': 0.01}),\n"
            "                 ('드롭아웃 0.3', {'drop': 0.3}),\n"
            "                 ('드롭아웃 0.5', {'drop': 0.5})]:\n"
            "    a, b = run(**kw)\n"
            "    results.append((name, b))\n"
            "    print(f'{name:20s}  {a:8.3f}       {b:8.3f}')\n"
            "\n"
            "best = max(results, key=lambda x: x[1])\n"
            "base = results[0][1]\n"
            "print(f'\\n→ 규제 없음: 훈련 1.000 (오염 라벨까지 완전 암기) · 검증 {base:.3f}')\n"
            "print(f'  최고 성능: {best[0]} · 검증 {best[1]:.3f}  (+{best[1] - base:.3f})')\n"
            "print('\\n  훈련 정확도가 떨어지는 대신 검증이 올라간다.')\n"
            "print('  \"훈련을 일부러 못하게 만들어 실전을 잘하게 하는 것\" 이 규제다.')\n"
            "print('  단 λ=0.01 처럼 과하게 걸면 다시 나빠진다(과소적합).')\n"
        ),
    ),

    Lesson(
        id="ds4-08-cnn",
        lang="datasci", level=STAGE,
        title="CNN — 합성곱과 풀링",
        summary="이미지를 위한 신경망 · 필터가 특징을 찾는다",
        explanation=(
            "[개요]\n"
            "이미지를 일반 신경망에 넣으려면 픽셀을 한 줄로 펴야 한다.\n"
            "그러면 두 가지를 잃는다.\n"
            "  1) 위치 정보 : 옆 픽셀과 붙어 있다는 사실이 사라진다\n"
            "  2) 파라미터  : 100×100 이미지 → 입력 10000개. 은닉층 1000개면 가중치 1천만 개다\n"
            "\n"
            "CNN(합성곱 신경망)은 작은 필터를 이미지 위로 훑으며 특징을 찾는다.\n"
            "\n"
            "[합성곱(convolution) 동작]\n"
            "  3×3 짜리 작은 필터를 이미지 왼쪽 위부터 한 칸씩 옮기며\n"
            "  겹치는 부분끼리 곱해서 더한다.\n"
            "\n"
            "    출력[i,j] = Σ 이미지[i+u, j+v] × 필터[u,v]\n"
            "\n"
            "  필터 값에 따라 찾아내는 것이 달라진다.\n"
            "    세로 엣지 필터  [[-1,0,1],[-1,0,1],[-1,0,1]]  → 세로 경계에 반응\n"
            "    가로 엣지 필터  [[-1,-1,-1],[0,0,0],[1,1,1]]  → 가로 경계에 반응\n"
            "    블러 필터       전부 1/9                       → 부드럽게\n"
            "\n"
            "  **CNN 은 이 필터 값을 사람이 정하지 않고 학습으로 찾아낸다.**\n"
            "  이것이 핵심이다. 초기 CNN 층은 엣지를, 깊은 층은 눈·바퀴 같은\n"
            "  복잡한 패턴을 스스로 학습한다.\n"
            "\n"
            "[CNN 이 강한 두 가지 이유]\n"
            "  1) 파라미터 공유 : 필터 하나(9개 값)를 이미지 전체에 재사용한다.\n"
            "     완전연결층의 1천만 개와 비교하면 압도적으로 적다.\n"
            "  2) 위치 불변성   : 고양이가 왼쪽에 있든 오른쪽에 있든 같은 필터가 찾아낸다.\n"
            "\n"
            "[풀링(pooling)]\n"
            "  영역에서 대표값 하나만 남겨 크기를 줄인다.\n"
            "    최대 풀링(max) : 가장 큰 값. '그 특징이 있었나'만 남긴다. 가장 흔하다.\n"
            "    평균 풀링(avg) : 평균값.\n"
            "\n"
            "  2×2 풀링이면 크기가 절반이 된다. 계산량이 줄고, 약간의 위치 변화에 둔감해진다.\n"
            "\n"
            "[출력 크기 계산 — 자주 묻는다]\n"
            "    출력 = (입력 - 필터 + 2×패딩) / 스트라이드 + 1\n"
            "\n"
            "  · 패딩(padding)   : 가장자리에 0 을 둘러 크기 유지\n"
            "  · 스트라이드      : 필터를 몇 칸씩 옮길지\n"
            "  8×8 이미지에 3×3 필터, 패딩 0, 스트라이드 1 → (8-3)/1+1 = 6 → 6×6\n"
            "\n"
            "[코드 분석]\n"
            "  out[i, j] = (region * kernel).sum()\n"
            "         → 합성곱 정의 그대로. 실제 라이브러리는 행렬곱으로 바꿔(im2col)\n"
            "            훨씬 빠르게 계산하지만 결과는 같다.\n"
            "  np.abs(conv)\n"
            "         → 엣지 필터의 결과는 음수도 나온다(밝기가 반대로 바뀌는 경계).\n"
            "            절댓값을 취해야 '경계의 세기'로 읽힌다.\n"
            "  아스키 시각화\n"
            "         → 값의 크기를 문자로 바꿔 눈으로 확인한다.\n"
            "            세로 엣지 필터가 세로선에만 반응하는 것이 보인다.\n"
            "  max_pool\n"
            "         → 2×2 영역의 최댓값. reshape 로도 할 수 있지만\n"
            "            원리가 잘 보이도록 반복문으로 썼다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 여기 구현은 원리 확인용이라 아주 느리다. 실무는 PyTorch 의 Conv2d 를 쓴다.\n"
            "  • 실제 CNN 은 필터를 수십~수백 개 동시에 쓰고(채널), 층도 여러 개다.\n"
            "  • 최근에는 이미지에도 트랜스포머(ViT)를 쓰는 경우가 늘었지만,\n"
            "    데이터가 적을 때는 여전히 CNN 이 유리하다."
        ),
        usage="이미지 분류·검출·분할. 음성이나 시계열에도 1차원 합성곱으로 쓴다.",
        cons="순수 파이썬 구현은 매우 느리다. 또 필터 크기·층 수 같은 구조 설계가 성능을 크게 좌우한다.",
        code=(
            "import numpy as np\n"
            "\n"
            "# 8x8 흑백 이미지: 가운데 세로줄 + 아래 가로줄\n"
            "img = np.zeros((8, 8))\n"
            "img[:, 3:5] = 1.0       # 세로 막대\n"
            "img[6, :] = 1.0         # 가로 막대\n"
            "\n"
            "def show(m, title):\n"
            "    chars = ' .:-=+*#%@'\n"
            "    mx = np.abs(m).max()\n"
            "    print(f'\\n{title}  ({m.shape[0]}x{m.shape[1]})')\n"
            "    for row in m:\n"
            "        line = ''\n"
            "        for v in row:\n"
            "            k = 0 if mx == 0 else int(abs(v) / mx * (len(chars) - 1))\n"
            "            line += chars[k] * 2\n"
            "        print('  ' + line)\n"
            "\n"
            "show(img, '원본 이미지')\n"
            "\n"
            "def conv2d(image, kernel, stride=1, pad=0):\n"
            "    if pad > 0:\n"
            "        image = np.pad(image, pad)\n"
            "    kh, kw = kernel.shape\n"
            "    oh = (image.shape[0] - kh) // stride + 1\n"
            "    ow = (image.shape[1] - kw) // stride + 1\n"
            "    out = np.zeros((oh, ow))\n"
            "    for i in range(oh):\n"
            "        for j in range(ow):\n"
            "            region = image[i * stride:i * stride + kh, j * stride:j * stride + kw]\n"
            "            out[i, j] = float((region * kernel).sum())\n"
            "    return out\n"
            "\n"
            "vert = np.array([[-1, 0, 1],\n"
            "                 [-1, 0, 1],\n"
            "                 [-1, 0, 1]], dtype=float)\n"
            "horz = np.array([[-1, -1, -1],\n"
            "                 [0, 0, 0],\n"
            "                 [1, 1, 1]], dtype=float)\n"
            "blur = np.ones((3, 3)) / 9\n"
            "\n"
            "show(np.abs(conv2d(img, vert)), '세로 엣지 필터 → 세로 경계만 검출')\n"
            "show(np.abs(conv2d(img, horz)), '가로 엣지 필터 → 가로 경계만 검출')\n"
            "show(conv2d(img, blur), '블러 필터 → 흐려짐')\n"
            "\n"
            "print('\\n-- 출력 크기 공식: (입력 - 필터 + 2*패딩)/스트라이드 + 1 --')\n"
            "for pad, stride in [(0, 1), (1, 1), (0, 2)]:\n"
            "    o = conv2d(img, vert, stride=stride, pad=pad)\n"
            "    calc = (8 - 3 + 2 * pad) // stride + 1\n"
            "    print(f'  패딩 {pad} · 스트라이드 {stride} → {o.shape}  (공식 계산 {calc})')\n"
            "\n"
            "def max_pool(m, size=2):\n"
            "    oh, ow = m.shape[0] // size, m.shape[1] // size\n"
            "    out = np.zeros((oh, ow))\n"
            "    for i in range(oh):\n"
            "        for j in range(ow):\n"
            "            out[i, j] = m[i * size:(i + 1) * size, j * size:(j + 1) * size].max()\n"
            "    return out\n"
            "\n"
            "edge = np.abs(conv2d(img, vert, pad=1))\n"
            "show(edge, '엣지 결과 (패딩 1 → 크기 유지)')\n"
            "show(max_pool(edge), '2x2 최대 풀링 → 크기 절반')\n"
            "\n"
            "print('\\n-- 파라미터 개수 비교 --')\n"
            "for side, hidden in [(8, 64), (100, 1000)]:\n"
            "    pix = side * side\n"
            "    fc = pix * hidden\n"
            "    print(f'  {side}x{side} 이미지 · 은닉 {hidden}')\n"
            "    print(f'    완전연결층 : {pix} x {hidden} = {fc:,} 개')\n"
            "    print(f'    3x3 필터   : 필터 1개당 9 개 (이미지 전체에 재사용)')\n"
            "    print(f'    필터 32개를 써도 {9 * 32:,} 개 — {fc // (9 * 32):,} 배 적다')\n"
            "print('\\n  이 차이가 CNN 이 이미지에서 압도적인 이유다.')\n"
            "print('  실제 CNN 은 뒤에 완전연결층이 붙지만, 그때는 이미 풀링으로')\n"
            "print('  크기가 크게 줄어든 뒤라 전체 파라미터는 훨씬 적다.')\n"
        ),
    ),

    Lesson(
        id="ds4-09-rnn",
        lang="datasci", level=STAGE,
        title="RNN — 순환 신경망과 기울기 소실",
        summary="순서가 있는 데이터 · LSTM 이 필요한 이유",
        explanation=(
            "[개요]\n"
            "문장·주가·음성은 **순서**가 중요하다.\n"
            "'나는 밥을 먹었다'와 '밥을 나는 먹었다'는 다르다.\n"
            "일반 신경망은 입력 순서를 모른다. RNN 은 이 문제를 '기억'으로 푼다.\n"
            "\n"
            "[구조 — 자기 자신에게 되먹임]\n"
            "    h_t = tanh(W_x·x_t + W_h·h_{t-1} + b)\n"
            "           ↑현재 입력      ↑직전 기억\n"
            "\n"
            "  시점마다 '현재 입력'과 '직전까지의 기억'을 합쳐 새 기억을 만든다.\n"
            "  **가중치 W_x, W_h 는 모든 시점에서 같은 것을 재사용한다.**\n"
            "  덕분에 문장 길이가 달라도 같은 모델로 처리할 수 있다.\n"
            "\n"
            "[펼쳐서 보기]\n"
            "    x₁ → [RNN] → h₁\n"
            "                  ↓\n"
            "    x₂ → [RNN] → h₂\n"
            "                  ↓\n"
            "    x₃ → [RNN] → h₃ → 출력\n"
            "\n"
            "  옆으로 아주 깊은 신경망을 쌓은 것과 같다. 여기서 문제가 생긴다.\n"
            "\n"
            "[기울기 소실 — RNN 의 치명적 약점]\n"
            "  역전파가 시점을 거슬러 올라갈 때마다 W_h 가 계속 곱해진다.\n"
            "\n"
            "    |W_h| < 1 이면 → 0 으로 수렴 (기울기 소실)\n"
            "    |W_h| > 1 이면 → 무한대로 발산 (기울기 폭발)\n"
            "\n"
            "  0.5 를 20번 곱하면 0.00000095 다. 사실상 0 이다.\n"
            "  즉 **20단어 전의 정보는 학습에 반영되지 않는다.**\n"
            "  더 심각한 건 1 에 가까운 값도 안전하지 않다는 점이다.\n"
            "  0.9 조차 100단계를 거치면 0.0000265 로 사라진다.\n"
            "  '유지'되는 구간은 1.0 근처의 아주 좁은 띠뿐인데,\n"
            "  학습 도중 W_h 를 그 안에 붙들어 둘 방법이 없다.\n"
            "\n"
            "  '나는 프랑스에서 자랐다 ... (30단어) ... 그래서 나는 __를 잘한다'\n"
            "  빈칸이 '프랑스어'인 걸 알려면 30단어 전을 기억해야 하는데, 기본 RNN 은 못한다.\n"
            "  아래 코드에서 이 소실을 직접 숫자로 확인한다.\n"
            "\n"
            "[해결책 — LSTM 과 GRU]\n"
            "  LSTM 은 '셀 상태'라는 별도의 기억 통로를 두고, 게이트 3개로 조절한다.\n"
            "    · 망각 게이트 : 무엇을 잊을지\n"
            "    · 입력 게이트 : 무엇을 새로 저장할지\n"
            "    · 출력 게이트 : 무엇을 내보낼지\n"
            "\n"
            "  핵심은 셀 상태가 **덧셈으로** 갱신된다는 점이다.\n"
            "  곱셈이 반복되지 않으므로 기울기가 잘 살아남는다.\n"
            "  GRU 는 게이트를 2개로 줄여 더 가볍게 만든 변형이다.\n"
            "\n"
            "[그리고 트랜스포머로]\n"
            "  RNN 은 순서대로 처리해야 해서 병렬화가 안 된다. 길면 느리다.\n"
            "  트랜스포머는 어텐션으로 모든 위치를 **한 번에** 연결한다.\n"
            "  거리에 상관없이 직접 참조하므로 기울기 소실도 없다.\n"
            "  그래서 현재 언어 모델은 전부 트랜스포머다 → 5단계에서 다룬다.\n"
            "\n"
            "[코드 분석]\n"
            "  h = np.tanh(Wx @ x + Wh @ h + b)\n"
            "         → 순환의 핵심 한 줄. h 가 매 시점 갱신된다.\n"
            "  누적 곱 실험\n"
            "         → W_h 의 크기를 바꿔가며 20 시점을 거슬렀을 때\n"
            "            기울기가 얼마나 남는지 계산한다.\n"
            "            0.5 → 거의 0, 1.5 → 폭발, 1.0 → 유지.\n"
            "  tanh 미분 (1 - h²)\n"
            "         → tanh 의 도함수는 최대 1 이고 보통 그보다 작다.\n"
            "            이것도 기울기를 줄이는 원인이다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 기울기 폭발은 클리핑(기울기 크기 제한)으로 비교적 쉽게 막는다.\n"
            "    소실은 훨씬 어렵다. 그래서 LSTM 같은 구조가 필요했다.\n"
            "  • 요즘 새 프로젝트에서 RNN 을 처음부터 고르는 경우는 드물다.\n"
            "    다만 개념은 알아야 트랜스포머가 왜 나왔는지 이해할 수 있다."
        ),
        usage="시계열 예측, 음성 인식 등. 개념 자체는 트랜스포머를 이해하는 데 필수다.",
        cons="긴 의존성을 학습하지 못하고 병렬화가 안 된다. 대부분의 용도에서 트랜스포머로 대체됐다.",
        code=(
            "import numpy as np\n"
            "\n"
            "rng = np.random.default_rng(0)\n"
            "\n"
            "# ---- RNN 순전파를 손으로 펼쳐 보기 ----\n"
            "H = 4\n"
            "Wx = rng.normal(0, 0.5, (H, 3))    # 입력 3차원 → 은닉 4차원\n"
            "Wh = rng.normal(0, 0.5, (H, H))    # 은닉 → 은닉 (순환)\n"
            "b = np.zeros(H)\n"
            "\n"
            "seq = [np.array([1.0, 0.0, 0.0]),\n"
            "       np.array([0.0, 1.0, 0.0]),\n"
            "       np.array([0.0, 0.0, 1.0]),\n"
            "       np.array([1.0, 1.0, 0.0])]\n"
            "\n"
            "h = np.zeros(H)\n"
            "print('시점   입력          은닉 상태 h')\n"
            "for t, x in enumerate(seq, start=1):\n"
            "    h = np.tanh(Wx @ x + Wh @ h + b)\n"
            "    print(f'  {t}   {x}   {h.round(4)}')\n"
            "print('\\n→ 같은 가중치를 매 시점 재사용하며 h 가 계속 갱신된다.')\n"
            "print('  h 안에 지금까지의 문맥이 압축되어 들어간다.')\n"
            "\n"
            "# ---- 기울기 소실/폭발 ----\n"
            "print('\\n' + '=' * 52)\n"
            "print('20 시점을 거슬러 올라갈 때 기울기가 얼마나 남는가')\n"
            "print('=' * 52)\n"
            "def verdict(f):\n"
            "    if f < 1e-4:\n"
            "        return '소실 — 학습 불가'\n"
            "    if f < 0.5:\n"
            "        return '상당히 소실'\n"
            "    if f <= 2.0:\n"
            "        return '유지'\n"
            "    if f < 1e3:\n"
            "        return '증폭 — 불안정'\n"
            "    return '폭발 — 발산'\n"
            "\n"
            "print('  |W_h|      20단계 후        100단계 후      100단계 판정')\n"
            "for w in [0.5, 0.9, 1.0, 1.1, 1.5]:\n"
            "    f20, f100 = w ** 20, w ** 100\n"
            "    print(f'  {w:5.1f}   {f20:>14.6g}   {f100:>14.6g}      {verdict(f100)}')\n"
            "\n"
            "print('\\n→ 20단계만 봐도 0.5 는 이미 0.00000095 로 사라진다.')\n"
            "print('  100단계로 늘리면 0.9 조차 0.0000265 가 되어 학습에 반영되지 않는다.')\n"
            "print('  반대로 1.1 은 13,780 배로 폭발한다.')\n"
            "print('\\n  \"유지\" 되는 구간은 1.0 근처의 아주 좁은 띠뿐이고,')\n"
            "print('  학습 중에 W_h 를 그 띠 안에 붙들어 둘 방법이 없다.')\n"
            "print('  이것이 RNN 이 긴 문맥을 다루지 못하는 근본 이유다.')\n"
            "\n"
            "# tanh 미분도 기울기를 줄인다\n"
            "print('\\n-- tanh 미분값 (1 - tanh²) --')\n"
            "for v in [0.0, 0.5, 1.0, 2.0]:\n"
            "    t = np.tanh(v)\n"
            "    print(f'  입력 {v:.1f} → tanh {t:+.4f} → 미분 {1 - t ** 2:.4f}')\n"
            "print('  최대가 1 이고 대부분 그보다 작다 → 곱할수록 더 줄어든다.')\n"
            "\n"
            "print('\\n[해결] LSTM 은 셀 상태를 \"덧셈\" 으로 갱신해 이 곱셈 연쇄를 피한다.')\n"
            "print('[대안] 트랜스포머는 아예 순환을 없애고 어텐션으로 직접 연결한다 → 5단계')\n"
        ),
    ),

    Lesson(
        id="ds4-10-pytorch",
        lang="datasci", level=STAGE,
        title="PyTorch 로 넘어가기",
        summary="지금까지 손으로 짠 것이 프레임워크에서 어떤 한 줄인가",
        explanation=(
            "[개요]\n"
            "여기까지 numpy 로 직접 구현한 이유는 '프레임워크가 대신 해주는 일'을\n"
            "정확히 알기 위해서다. 실무에서는 PyTorch 를 쓴다.\n"
            "\n"
            "[PyTorch 가 대신 해주는 것]\n"
            "  1) 자동 미분 : 역전파 수식을 직접 유도할 필요가 없다.\n"
            "                loss.backward() 한 줄이면 모든 기울기가 채워진다.\n"
            "                우리가 손으로 짠 dz2, da1, dz1 이 전부 자동화된다.\n"
            "  2) GPU 가속 : .to('cuda') 한 줄로 수십 배 빨라진다.\n"
            "  3) 검증된 부품 : 옵티마이저·층·손실함수가 최적화되어 들어 있다.\n"
            "\n"
            "[설치]\n"
            "    pip install torch\n"
            "  용량이 크다(CPU 버전 약 200MB, GPU 버전 2GB 이상).\n"
            "  이 앱에는 포함되어 있지 않으므로 아래 코드는 '읽기용'이다.\n"
            "  직접 돌려보려면 터미널에서 설치한 뒤 별도 파일로 실행하자.\n"
            "\n"
            "[대응표 — 우리가 짠 것 ↔ PyTorch]\n"
            "\n"
            "    W1 = rng.normal(...)*np.sqrt(2/n)   →  nn.Linear(2, 64)\n"
            "    a1 = np.maximum(0, z1)              →  nn.ReLU()\n"
            "    softmax + 교차엔트로피              →  nn.CrossEntropyLoss()\n"
            "    직접 유도한 dz2, dW2, ...           →  loss.backward()\n"
            "    Adam 상태 m, v 직접 관리            →  optim.Adam(model.parameters())\n"
            "    p -= lr * ...                       →  optimizer.step()\n"
            "    (없음 — 매번 새로 계산했음)          →  optimizer.zero_grad()\n"
            "    mask = rng.random(...) > drop       →  nn.Dropout(0.3)\n"
            "    l2 * W                              →  optim.Adam(..., weight_decay=1e-4)\n"
            "    추론 때 드롭아웃 끄기                →  model.eval()\n"
            "    conv2d 반복문                        →  nn.Conv2d(1, 16, 3)\n"
            "    max_pool 반복문                      →  nn.MaxPool2d(2)\n"
            "\n"
            "[초보자가 가장 많이 하는 실수 5가지]\n"
            "  1) optimizer.zero_grad() 를 빼먹는다\n"
            "     → PyTorch 는 기울기를 **누적**한다. 지우지 않으면 계속 더해져 학습이 망가진다.\n"
            "  2) CrossEntropyLoss 앞에 softmax 를 또 씌운다\n"
            "     → 이 손실함수는 내부에 이미 softmax 가 있다. 두 번 하면 학습이 안 된다.\n"
            "  3) model.eval() 을 안 부른다\n"
            "     → 추론 때도 드롭아웃이 켜져 결과가 매번 달라진다.\n"
            "  4) 검증 때 torch.no_grad() 를 안 쓴다\n"
            "     → 필요 없는 계산 그래프가 쌓여 메모리가 터진다.\n"
            "  5) 라벨을 원-핫으로 준다\n"
            "     → CrossEntropyLoss 는 정수 라벨을 그대로 받는다.\n"
            "\n"
            "[학습이 안 될 때 점검 순서]\n"
            "  1) 데이터를 눈으로 확인한다 (라벨이 맞나, 스케일이 이상하지 않나)\n"
            "  2) 아주 작은 데이터(10개)로 과적합을 시켜본다\n"
            "     → 이것도 안 되면 코드에 버그가 있는 것이다. 가장 확실한 진단법이다.\n"
            "  3) 학습률을 10배씩 올리고 내려본다\n"
            "  4) 손실이 nan 이면 → 학습률이 너무 크거나 log(0) 이 발생\n"
            "  5) 그래도 안 되면 모델을 단순하게 줄인다\n"
            "\n"
            "[유의 사항]\n"
            "  • 아래 코드는 torch 가 설치되어 있지 않으면 실행되지 않는다.\n"
            "    이 레슨의 Run 은 대응표를 출력할 뿐이다.\n"
            "  • 프레임워크를 쓰더라도 지금까지 배운 원리는 그대로다.\n"
            "    학습이 안 될 때 디버깅할 수 있는 건 원리를 아는 사람뿐이다."
        ),
        usage="numpy 구현에서 실무 프레임워크로 넘어가는 다리. 대응표를 옆에 두고 옮겨 적으면 된다.",
        cons="이 앱에는 torch 가 없어 실행은 되지 않는다. 별도로 설치해 사용해야 한다.",
        code=(
            "# 이 레슨의 PyTorch 코드는 '읽기용' 이다 (앱에 torch 미포함).\n"
            "# 아래는 우리가 numpy 로 짠 것과 PyTorch 코드의 대응을 출력한다.\n"
            "\n"
            "pairs = [\n"
            "    ('가중치 초기화',\n"
            "     'W1 = rng.normal(0,1,(2,64))*np.sqrt(2/2)',\n"
            "     'nn.Linear(2, 64)'),\n"
            "    ('ReLU',\n"
            "     'a1 = np.maximum(0, z1)',\n"
            "     'nn.ReLU()'),\n"
            "    ('softmax + 교차엔트로피',\n"
            "     'prob = softmax(z2); -log(prob[range(n), y]).mean()',\n"
            "     'nn.CrossEntropyLoss()'),\n"
            "    ('역전파',\n"
            "     'dz2 = (prob-Y)/n; da1 = dz2@W2.T; dz1 = da1*(z1>0) ...',\n"
            "     'loss.backward()'),\n"
            "    ('Adam',\n"
            "     'm = 0.9*m+0.1*g; v = 0.999*v+0.001*g*g; ...',\n"
            "     'optim.Adam(model.parameters(), lr=1e-3)'),\n"
            "    ('가중치 갱신',\n"
            "     'p -= lr * mh/(sqrt(vh)+eps)',\n"
            "     'optimizer.step()'),\n"
            "    ('기울기 초기화',\n"
            "     '(매번 새로 계산했으므로 불필요)',\n"
            "     'optimizer.zero_grad()   ← 빼먹으면 누적됨!'),\n"
            "    ('드롭아웃',\n"
            "     'mask = (rng.random(a.shape) > 0.3)/0.7',\n"
            "     'nn.Dropout(0.3)'),\n"
            "    ('L2 정규화',\n"
            "     'dW += l2 * W',\n"
            "     'optim.Adam(..., weight_decay=1e-4)'),\n"
            "    ('추론 모드',\n"
            "     '드롭아웃 마스크를 적용하지 않음',\n"
            "     'model.eval() + torch.no_grad()'),\n"
            "    ('합성곱',\n"
            "     'for i,j: (region*kernel).sum()',\n"
            "     'nn.Conv2d(1, 16, kernel_size=3)'),\n"
            "    ('최대 풀링',\n"
            "     'for i,j: region.max()',\n"
            "     'nn.MaxPool2d(2)'),\n"
            "]\n"
            "\n"
            "print('=' * 68)\n"
            "print('우리가 손으로 짠 것  ↔  PyTorch')\n"
            "print('=' * 68)\n"
            "for title, mine, torch_code in pairs:\n"
            "    print(f'\\n[{title}]')\n"
            "    print(f'  numpy   : {mine}')\n"
            "    print(f'  PyTorch : {torch_code}')\n"
            "\n"
            "print('\\n' + '=' * 68)\n"
            "print('PyTorch 전체 학습 루프 (설치 후 별도 파일로 실행)')\n"
            "print('=' * 68)\n"
            "print('''\n"
            "import torch\n"
            "import torch.nn as nn\n"
            "\n"
            "model = nn.Sequential(\n"
            "    nn.Linear(2, 64), nn.ReLU(),\n"
            "    nn.Dropout(0.3),\n"
            "    nn.Linear(64, 3),          # softmax 는 손실함수가 처리\n"
            ")\n"
            "loss_fn = nn.CrossEntropyLoss()\n"
            "opt = torch.optim.Adam(model.parameters(), lr=1e-3, weight_decay=1e-4)\n"
            "\n"
            "for epoch in range(100):\n"
            "    model.train()\n"
            "    for xb, yb in loader:          # 미니배치\n"
            "        opt.zero_grad()            # ← 반드시!\n"
            "        loss = loss_fn(model(xb), yb)\n"
            "        loss.backward()            # 역전파 자동\n"
            "        opt.step()\n"
            "\n"
            "    model.eval()\n"
            "    with torch.no_grad():\n"
            "        acc = (model(X_val).argmax(1) == y_val).float().mean()\n"
            "''')\n"
            "\n"
            "print('=' * 68)\n"
            "print('학습이 안 될 때 점검 순서')\n"
            "print('=' * 68)\n"
            "steps = [\n"
            "    '데이터를 눈으로 확인 (라벨·스케일)',\n"
            "    '데이터 10개로 과적합 시도 → 안 되면 코드 버그다 (가장 확실한 진단)',\n"
            "    '학습률을 10배씩 올리고 내려보기',\n"
            "    '손실이 nan → 학습률 과대 또는 log(0)',\n"
            "    '모델을 더 단순하게 줄여보기',\n"
            "]\n"
            "for i, s in enumerate(steps, start=1):\n"
            "    print(f'  {i}. {s}')\n"
        ),
    ),
]
