"""4단계 — 딥러닝 (로드맵 + 핵심 개념 맛보기).

PyTorch 없이 numpy 만으로 신경망을 직접 만든다.
프레임워크가 대신 해주는 일이 실제로 무엇인지 알고 쓰기 위해서다.
"""

from engine.models import Lesson

STAGE = "4. 딥러닝"

LESSONS = [

    Lesson(
        id="ds4-01-roadmap",
        lang="datasci", level=STAGE,
        title="딥러닝 로드맵",
        summary="신경망은 무엇이고 왜 강한가",
        explanation=(
            "[개요]\n"
            "딥러닝은 머신러닝의 한 갈래로, '층을 깊게 쌓은 신경망'을 쓰는 방법이다.\n"
            "3단계의 선형회귀가 직선 하나였다면, 신경망은 그 직선을 수백 개 쌓고\n"
            "사이사이에 비선형 함수를 끼워 넣은 것이다.\n"
            "\n"
            "[왜 층을 쌓는가]\n"
            "  직선을 아무리 여러 개 이어 붙여도 결국 직선이다.\n"
            "    (w2 × (w1x + b1) + b2) = (w2w1)x + (w2b1 + b2)  ← 여전히 직선\n"
            "  그래서 층 사이에 '구부리는 장치'가 필요하다. 이것이 활성화 함수다.\n"
            "  구부린 직선을 여러 개 겹치면 어떤 복잡한 곡선도 흉내낼 수 있다.\n"
            "  이를 '보편 근사 정리'라 한다. 딥러닝이 강한 이론적 근거다.\n"
            "\n"
            "[신경망의 구조]\n"
            "  입력층 → 은닉층(여러 개) → 출력층\n"
            "\n"
            "  각 층에서 하는 일은 딱 두 가지다.\n"
            "    1) 선형 변환   z = Wx + b       (행렬 곱)\n"
            "    2) 비선형 변환 a = f(z)          (활성화 함수)\n"
            "  이 두 줄이 반복될 뿐이다. 아무리 큰 모델도 구조는 같다.\n"
            "\n"
            "[학습 방법 — 3단계와 완전히 동일하다]\n"
            "  1) 순전파(forward)  : 입력을 넣어 예측값을 낸다\n"
            "  2) 손실 계산        : 얼마나 틀렸나 잰다\n"
            "  3) 역전파(backward) : 각 가중치가 오차에 얼마나 기여했는지 거꾸로 계산\n"
            "  4) 가중치 갱신      : 기울기 반대로 조금 이동\n"
            "\n"
            "  3단계 선형회귀에서 한 일과 똑같다. 층이 여러 개라\n"
            "  기울기를 뒤에서 앞으로 연쇄법칙으로 전달하는 것만 다르다.\n"
            "\n"
            "[이 단계 커리큘럼]\n"
            "  ds4-02  퍼셉트론과 활성화 함수 — 신경망의 최소 단위\n"
            "  ds4-03  2층 신경망으로 XOR 풀기 — 역전파 직접 구현\n"
            "  (이후 확장 예정)\n"
            "    · 옵티마이저(SGD, Adam) · 배치 학습\n"
            "    · 과적합 방지(드롭아웃, 정규화, 조기종료)\n"
            "    · CNN(이미지) · RNN/LSTM(시계열)\n"
            "    · PyTorch 실전 사용법\n"
            "\n"
            "[유의 사항]\n"
            "  • 딥러닝이 항상 최선은 아니다. 표 형태 데이터에서는\n"
            "    부스팅 계열(XGBoost, LightGBM)이 더 좋은 경우가 많다.\n"
            "  • 딥러닝은 데이터가 많이 필요하다. 수백 건 규모면 단순한 모델이 낫다."
        ),
        usage="4단계 학습의 지도. 3단계 선형회귀와 무엇이 같고 다른지 짚어두는 용도.",
        cons="개념 정리 위주다. 실제 구현은 다음 레슨부터 시작한다.",
        code=(
            "import numpy as np\n"
            "\n"
            "# 층을 쌓아도 활성화 함수가 없으면 결국 직선 하나 — 직접 확인\n"
            "rng = np.random.default_rng(0)\n"
            "x = np.linspace(-3, 3, 7)\n"
            "\n"
            "W1, b1 = 2.0, 1.0\n"
            "W2, b2 = -0.5, 3.0\n"
            "\n"
            "two_layers = W2 * (W1 * x + b1) + b2\n"
            "one_line   = (W2 * W1) * x + (W2 * b1 + b2)\n"
            "\n"
            "print('2층 (활성화 없음):', two_layers.round(3))\n"
            "print('직선 1개         :', one_line.round(3))\n"
            "print('같은가?', bool(np.allclose(two_layers, one_line)))\n"
            "print('→ 활성화 함수가 없으면 층을 쌓는 의미가 없다\\n')\n"
            "\n"
            "# 활성화 함수를 넣으면 달라진다\n"
            "def relu(z):\n"
            "    return np.maximum(0, z)\n"
            "\n"
            "with_relu = W2 * relu(W1 * x + b1) + b2\n"
            "print('2층 (ReLU 사용)  :', with_relu.round(3))\n"
            "print('→ 더 이상 직선이 아니다. 구부러졌다.')\n"
        ),
    ),

    Lesson(
        id="ds4-02-perceptron",
        lang="datasci", level=STAGE,
        title="퍼셉트론과 활성화 함수",
        summary="뉴런 하나 · sigmoid · ReLU · softmax",
        explanation=(
            "[개요]\n"
            "퍼셉트론은 신경망의 최소 단위, 즉 뉴런 하나다.\n"
            "  입력들에 가중치를 곱해 더하고 → 활성화 함수를 통과시킨다\n"
            "    z = w1x1 + w2x2 + ... + b\n"
            "    a = f(z)\n"
            "\n"
            "생물학적 뉴런이 '신호가 일정 세기를 넘으면 발화한다'는 걸 흉내낸 것이다.\n"
            "\n"
            "[대표 활성화 함수]\n"
            "\n"
            "  1) Sigmoid   f(z) = 1 / (1 + e^-z)      결과 범위 0 ~ 1\n"
            "     · 확률로 해석할 수 있어 이진 분류의 출력층에 쓴다.\n"
            "     · 단점: z 가 크거나 작으면 기울기가 0 에 가까워진다(기울기 소실).\n"
            "       층이 깊어지면 앞쪽 층이 학습되지 않는다. 그래서 은닉층엔 잘 안 쓴다.\n"
            "\n"
            "  2) ReLU      f(z) = max(0, z)           결과 범위 0 ~ ∞\n"
            "     · 계산이 극도로 단순하고 기울기 소실이 없다.\n"
            "     · 현재 은닉층의 기본 선택이다. 딥러닝이 깊어질 수 있게 만든 주역.\n"
            "     · 단점: z 가 음수면 기울기가 0 이라 그 뉴런이 죽을 수 있다(dying ReLU).\n"
            "\n"
            "  3) Tanh      f(z) = (e^z - e^-z)/(e^z + e^-z)   결과 범위 -1 ~ 1\n"
            "     · 0 을 중심으로 대칭이라 sigmoid 보다 학습이 잘 된다.\n"
            "\n"
            "  4) Softmax   여러 값을 합이 1인 확률 분포로 변환\n"
            "     · 다중 분류의 출력층 전용이다.\n"
            "     · [2.0, 1.0, 0.1] → [0.659, 0.242, 0.099] 처럼 바꾼다.\n"
            "\n"
            "[코드 분석]\n"
            "  1 / (1 + np.exp(-z))\n"
            "         → sigmoid 정의 그대로. z 가 매우 작으면 exp 가 넘칠 수 있어\n"
            "            실무 라이브러리는 안정화 처리를 따로 한다.\n"
            "  np.maximum(0, z)\n"
            "         → ReLU. 각 원소를 0 과 비교해 큰 값을 남긴다.\n"
            "            np.max 가 아니라 np.maximum 이다. 전자는 최댓값 하나를 구한다.\n"
            "  e = np.exp(z - z.max())\n"
            "         → softmax 의 오버플로 방지 기법.\n"
            "            최댓값을 빼도 결과는 수학적으로 동일하지만 exp 가 넘치지 않는다.\n"
            "            실무 구현에서 반드시 쓰는 안정화 트릭이다.\n"
            "  e / e.sum()\n"
            "         → 합이 1 이 되도록 나눈다. 이제 확률로 읽을 수 있다.\n"
            "  AND 게이트 예시\n"
            "         → w=[1,1], b=-1.5 로 두면 둘 다 1일 때만 z>0 이 된다.\n"
            "            가중치를 사람이 손으로 정한 것이다. 학습은 이 값을 자동으로 찾는 일이다.\n"
            "\n"
            "[퍼셉트론의 한계 — XOR 문제]\n"
            "  AND, OR 는 뉴런 하나로 만들 수 있다. 직선 하나로 구분되기 때문이다.\n"
            "  하지만 XOR(둘이 다를 때만 1)은 직선 하나로 나눌 수 없다.\n"
            "  이 한계가 1970년대 AI 겨울을 불러왔고, 층을 쌓는 것으로 해결됐다.\n"
            "  다음 레슨에서 직접 확인한다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 은닉층은 ReLU, 이진분류 출력층은 sigmoid, 다중분류 출력층은 softmax 가 기본 공식이다.\n"
            "  • sigmoid 를 은닉층에 여러 겹 쓰면 기울기 소실로 학습이 안 된다."
        ),
        usage="모든 신경망의 기본 부품. 활성화 함수 선택은 성능에 직결된다.",
        cons="뉴런 하나로는 직선으로 나뉘는 문제만 풀 수 있다. XOR 같은 문제는 층을 쌓아야 한다.",
        code=(
            "import numpy as np\n"
            "\n"
            "def sigmoid(z):\n"
            "    return 1 / (1 + np.exp(-z))\n"
            "\n"
            "def relu(z):\n"
            "    return np.maximum(0, z)\n"
            "\n"
            "def tanh(z):\n"
            "    return np.tanh(z)\n"
            "\n"
            "def softmax(z):\n"
            "    e = np.exp(z - z.max())      # 오버플로 방지\n"
            "    return e / e.sum()\n"
            "\n"
            "z = np.array([-3.0, -1.0, 0.0, 1.0, 3.0])\n"
            "print('입력    :', z)\n"
            "print('sigmoid :', sigmoid(z).round(4))\n"
            "print('relu    :', relu(z))\n"
            "print('tanh    :', tanh(z).round(4))\n"
            "print()\n"
            "print('softmax([2.0, 1.0, 0.1]):', softmax(np.array([2.0, 1.0, 0.1])).round(4))\n"
            "print('합계:', float(softmax(np.array([2.0, 1.0, 0.1])).sum()))\n"
            "\n"
            "# 퍼셉트론 하나로 AND 게이트 만들기 (가중치를 손으로 지정)\n"
            "print('\\n-- 퍼셉트론 AND 게이트 --')\n"
            "w = np.array([1.0, 1.0])\n"
            "b = -1.5\n"
            "for x in [[0, 0], [0, 1], [1, 0], [1, 1]]:\n"
            "    x = np.array(x, dtype=float)\n"
            "    z = w @ x + b\n"
            "    out = 1 if z > 0 else 0\n"
            "    print(f'  {x.astype(int)} → z={z:5.1f} → {out}')\n"
            "\n"
            "print('\\n-- OR 게이트 (b 만 바꿈) --')\n"
            "b = -0.5\n"
            "for x in [[0, 0], [0, 1], [1, 0], [1, 1]]:\n"
            "    x = np.array(x, dtype=float)\n"
            "    print(f'  {x.astype(int)} → {1 if w @ x + b > 0 else 0}')\n"
            "\n"
            "print('\\n※ XOR 은 직선 하나로 나눌 수 없어 뉴런 하나로는 불가능하다.')\n"
        ),
    ),

    Lesson(
        id="ds4-03-backprop",
        lang="datasci", level=STAGE,
        title="2층 신경망 — 역전파로 XOR 풀기",
        summary="딥러닝의 심장, 역전파를 직접 구현",
        explanation=(
            "[개요]\n"
            "XOR 는 뉴런 하나로 못 푼다. 은닉층 하나를 넣어 2층으로 만들면 풀린다.\n"
            "이 레슨에서 신경망 전체를 numpy 로 처음부터 끝까지 만든다.\n"
            "PyTorch 가 자동으로 해주는 일을 손으로 해보는 것이다.\n"
            "\n"
            "[구조]\n"
            "  입력 2개 → 은닉층 4개(ReLU) → 출력 1개(sigmoid)\n"
            "\n"
            "  W1: (2, 4)   b1: (4,)\n"
            "  W2: (4, 1)   b2: (1,)\n"
            "  모양(shape)을 정확히 맞추는 것이 구현의 절반이다.\n"
            "\n"
            "[순전파 (forward)]\n"
            "  z1 = X @ W1 + b1      → 선형 변환\n"
            "  a1 = relu(z1)          → 비선형 변환\n"
            "  z2 = a1 @ W2 + b2\n"
            "  a2 = sigmoid(z2)       → 최종 예측(0~1 확률)\n"
            "\n"
            "[역전파 (backward) — 연쇄법칙]\n"
            "  '출력의 오차가 각 가중치 탓이 얼마나 되는가'를 뒤에서부터 계산한다.\n"
            "\n"
            "  dz2 = a2 - y                       ← 출력층 오차\n"
            "  dW2 = a1.T @ dz2 / n               ← W2 의 기울기\n"
            "  da1 = dz2 @ W2.T                   ← 오차를 은닉층으로 전달\n"
            "  dz1 = da1 * (z1 > 0)               ← ReLU 미분 (양수면 1, 음수면 0)\n"
            "  dW1 = X.T @ dz1 / n                ← W1 의 기울기\n"
            "\n"
            "  dz2 = a2 - y 가 이렇게 단순한 이유:\n"
            "  sigmoid + 이진 교차엔트로피 손실을 함께 쓰면 미분이 깔끔하게 정리된다.\n"
            "  이 조합을 쓰는 실용적 이유 중 하나다.\n"
            "\n"
            "[코드 분석]\n"
            "  rng.normal(0, 1, (2, 4)) * np.sqrt(2 / 2)\n"
            "         → He 초기화. ReLU 를 쓸 때 권장되는 초기값 설정이다.\n"
            "            전부 0 으로 초기화하면 모든 뉴런이 똑같이 학습돼 의미가 없다.\n"
            "            초기값 설정만으로 학습 성패가 갈리기도 한다.\n"
            "  X @ W1\n"
            "         → 행렬 곱. @ 는 numpy 의 행렬곱 연산자다.\n"
            "            (4,2) @ (2,4) = (4,4). 데이터 4개가 한 번에 처리된다.\n"
            "  np.clip(a2, 1e-7, 1 - 1e-7)\n"
            "         → log(0) 은 -무한대라 계산이 깨진다. 아주 작은 값으로 잘라 막는다.\n"
            "  loss = -(y*log(a2) + (1-y)*log(1-a2)).mean()\n"
            "         → 이진 교차엔트로피. 분류 문제의 표준 손실 함수다.\n"
            "            MSE 보다 분류에서 학습이 훨씬 빠르다.\n"
            "  (z1 > 0)\n"
            "         → ReLU 의 미분. True/False 가 1/0 으로 계산된다.\n"
            "            음수 구간은 기울기를 흘려보내지 않는다는 뜻이다.\n"
            "  keepdims=True\n"
            "         → 합계를 낼 때 차원을 유지한다. 이걸 빼면 모양이 어긋나\n"
            "            브로드캐스팅이 엉뚱하게 일어난다. 자주 하는 실수다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 손실이 안 줄면: 학습률, 초기화, 은닉층 크기 순서로 점검한다.\n"
            "  • XOR 은 초기값 운이 나쁘면 지역 최솟값에 빠질 수 있다. 시드를 바꿔보자.\n"
            "  • 실무에서는 이걸 직접 짜지 않고 PyTorch 를 쓴다.\n"
            "    하지만 이 과정을 알고 쓰는 것과 모르고 쓰는 것은 디버깅에서 완전히 다르다."
        ),
        usage="딥러닝 전체의 원리. 여기를 이해하면 프레임워크는 사용법만 익히면 된다.",
        cons="데이터 4개짜리 장난감 예제다. 실제 문제는 배치 처리·옵티마이저·정규화가 추가로 필요하다.",
        code=(
            "import numpy as np\n"
            "\n"
            "rng = np.random.default_rng(1)\n"
            "\n"
            "# XOR 데이터 — 둘이 다를 때만 1\n"
            "X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=float)\n"
            "y = np.array([[0], [1], [1], [0]], dtype=float)\n"
            "\n"
            "n_in, n_hidden, n_out = 2, 4, 1\n"
            "\n"
            "# He 초기화\n"
            "W1 = rng.normal(0, 1, (n_in, n_hidden)) * np.sqrt(2 / n_in)\n"
            "b1 = np.zeros(n_hidden)\n"
            "W2 = rng.normal(0, 1, (n_hidden, n_out)) * np.sqrt(2 / n_hidden)\n"
            "b2 = np.zeros(n_out)\n"
            "\n"
            "lr = 0.5\n"
            "n = len(X)\n"
            "\n"
            "print('epoch      손실')\n"
            "for epoch in range(3001):\n"
            "    # ---- 순전파 ----\n"
            "    z1 = X @ W1 + b1\n"
            "    a1 = np.maximum(0, z1)              # ReLU\n"
            "    z2 = a1 @ W2 + b2\n"
            "    a2 = 1 / (1 + np.exp(-z2))          # sigmoid\n"
            "\n"
            "    # ---- 손실 (이진 교차엔트로피) ----\n"
            "    p = np.clip(a2, 1e-7, 1 - 1e-7)\n"
            "    loss = -(y * np.log(p) + (1 - y) * np.log(1 - p)).mean()\n"
            "\n"
            "    # ---- 역전파 ----\n"
            "    dz2 = (a2 - y) / n\n"
            "    dW2 = a1.T @ dz2\n"
            "    db2 = dz2.sum(axis=0)\n"
            "\n"
            "    da1 = dz2 @ W2.T\n"
            "    dz1 = da1 * (z1 > 0)                # ReLU 미분\n"
            "    dW1 = X.T @ dz1\n"
            "    db1 = dz1.sum(axis=0)\n"
            "\n"
            "    # ---- 갱신 ----\n"
            "    W2 -= lr * dW2\n"
            "    b2 -= lr * db2\n"
            "    W1 -= lr * dW1\n"
            "    b1 -= lr * db1\n"
            "\n"
            "    if epoch % 500 == 0:\n"
            "        print(f'{epoch:5d}  {loss:10.6f}')\n"
            "\n"
            "print('\\n-- 학습 결과 --')\n"
            "z1 = X @ W1 + b1\n"
            "a1 = np.maximum(0, z1)\n"
            "out = 1 / (1 + np.exp(-(a1 @ W2 + b2)))\n"
            "for xi, yi, oi in zip(X, y, out):\n"
            "    print(f'  {xi.astype(int)} → 예측 {float(oi[0]):.4f}  (정답 {int(yi[0])})')\n"
            "\n"
            "acc = ((out > 0.5).astype(int) == y).mean()\n"
            "print(f'\\n정확도: {float(acc):.2f}')\n"
            "print('→ 은닉층 하나를 넣으니 직선으로 못 나누던 XOR 이 풀린다')\n"
        ),
    ),
]
