"""1단계 — 데이터 기초.

파이썬 기본 자료구조로 데이터를 다루는 감각을 먼저 잡고,
같은 일을 numpy 로 하면 왜 편하고 빨라지는지 이어서 배운다.
"""

from engine.models import Lesson

STAGE = "1. 데이터 기초"

LESSONS = [

    Lesson(
        id="ds1-01-intro",
        lang="datasci", level=STAGE,
        title="데이터 분석이란 · 환경 확인",
        summary="분석의 4단계 · numpy/pandas 설치 확인",
        explanation=(
            "[개요]\n"
            "데이터 분석은 '숫자 더미에서 판단에 쓸 수 있는 문장을 뽑아내는 일'이다.\n"
            "예를 들어 반 학생 30명의 점수표가 있을 때,\n"
            "  숫자 더미 → 30개의 점수\n"
            "  뽑아낸 문장 → '평균은 72점이고, 하위 5명이 전체 평균을 8점 끌어내리고 있다'\n"
            "이 문장을 만들어내는 과정 전체가 데이터 분석이다.\n"
            "\n"
            "[분석의 4단계]\n"
            "  1) 수집  — 데이터를 가져온다 (CSV 파일, 데이터베이스, API)\n"
            "  2) 전처리 — 빠진 값·잘못된 값·중복을 정리한다 (실무 시간의 70%가 여기)\n"
            "  3) 분석  — 평균·분포·관계를 계산한다\n"
            "  4) 해석  — 숫자를 사람이 읽을 문장/그래프로 바꾼다\n"
            "이 트랙은 1~3단계를 코드로 직접 해보는 데 집중한다.\n"
            "\n"
            "[왜 파이썬인가]\n"
            "• 문법이 짧아 데이터 다루는 코드가 거의 '말한 그대로' 나온다.\n"
            "• numpy·pandas 라는 도구가 압도적으로 강력하고, 딥러닝/LLM 까지 같은 언어로 이어진다.\n"
            "• 자바로 평균을 구하려면 반복문을 돌려야 하지만, 여기서는 arr.mean() 한 줄이다.\n"
            "\n"
            "[이 트랙에서 쓰는 도구]\n"
            "  • numpy  → 숫자 계산 전용 도구. '숫자 배열'을 통째로 계산한다.\n"
            "  • pandas → 표(엑셀 시트 같은 것) 전용 도구. numpy 위에 만들어져 있다.\n"
            "  두 도구는 이 앱에 이미 설치되어 있다. 아래 코드를 Run 해서 확인해 보자.\n"
            "\n"
            "[코드 분석]\n"
            "  import numpy as np\n"
            "         → numpy 를 가져오되 np 라는 짧은 이름으로 부르겠다는 뜻이다.\n"
            "            as np 는 전 세계가 쓰는 관례이므로 그대로 따르는 게 좋다.\n"
            "  np.__version__\n"
            "         → 설치된 버전 문자열. 이게 출력되면 정상 설치된 것이다.\n"
            "  scores = [88, 92, 79, 95, 61]\n"
            "         → 파이썬 리스트. 대괄호 안에 값을 쉼표로 나열한 '값들의 묶음'이다.\n"
            "  sum(scores) / len(scores)\n"
            "         → sum 은 합계, len 은 개수. 합계 ÷ 개수 = 평균.\n"
            "            파이썬 기본 기능만으로 계산한 방식이다.\n"
            "  np.mean(scores)\n"
            "         → numpy 로 같은 평균을 구한 것. 함수 하나로 끝난다.\n"
            "            결과는 같지만 데이터가 100만 개가 되면 속도 차이가 수십 배로 벌어진다.\n"
            "\n"
            "[유의 사항]\n"
            "  • ModuleNotFoundError 가 뜨면 라이브러리가 없는 것이다.\n"
            "    터미널에서 `python -m pip install numpy pandas` 로 설치한다.\n"
            "  • 이 트랙의 모든 코드는 Python 전용이다. Java·C++ 로는 실행되지 않는다."
        ),
        usage="가장 먼저 실행해서 환경이 정상인지 확인하는 용도. 이후 모든 레슨의 전제다.",
        cons="numpy/pandas 는 불러오는 데 시간이 걸린다(pandas 약 2초). 작은 계산이면 파이썬 기본 기능이 더 빠를 수도 있다.",
        code=(
            "import numpy as np\n"
            "import pandas as pd\n"
            "\n"
            "print('numpy  버전:', np.__version__)\n"
            "print('pandas 버전:', pd.__version__)\n"
            "\n"
            "scores = [88, 92, 79, 95, 61]\n"
            "print('점수:', scores)\n"
            "print('평균(파이썬 기본):', sum(scores) / len(scores))\n"
            "print('평균(numpy)     :', np.mean(scores))\n"
        ),
    ),

    Lesson(
        id="ds1-02-list",
        lang="datasci", level=STAGE,
        title="리스트로 데이터 다루기",
        summary="합계 · 평균 · 최대 · 최소 · 개수",
        explanation=(
            "[개요]\n"
            "리스트(list)는 값을 순서대로 담는 파이썬의 기본 그릇이다.\n"
            "데이터 분석에서 가장 먼저 만나는 형태이며, numpy 배열도 결국 리스트에서 출발한다.\n"
            "\n"
            "[핵심 개념]\n"
            "• 리스트는 대괄호로 만든다:  scores = [88, 92, 79]\n"
            "• 순서가 있다. 0번부터 센다:  scores[0] 은 88, scores[1] 은 92\n"
            "• 뒤에서부터도 셀 수 있다:   scores[-1] 은 마지막 값 79\n"
            "• 값을 바꿀 수 있다:         scores[0] = 100\n"
            "\n"
            "[요약에 쓰는 기본 함수]\n"
            "  • len(리스트)  → 개수\n"
            "  • sum(리스트)  → 합계\n"
            "  • max(리스트)  → 최댓값\n"
            "  • min(리스트)  → 최솟값\n"
            "  • sorted(리스트) → 정렬된 새 리스트 (원본은 그대로)\n"
            "이 다섯 개만으로도 '기술통계'의 절반은 구할 수 있다.\n"
            "\n"
            "[코드 분석]\n"
            "  scores = [88, 92, 79, 95, 61, 73]\n"
            "         → 6명의 점수를 리스트에 담는다.\n"
            "  n = len(scores)\n"
            "         → 6. 데이터 개수를 변수에 담아두면 평균 계산에서 재사용할 수 있다.\n"
            "  total = sum(scores)\n"
            "         → 88+92+79+95+61+73 = 488\n"
            "  avg = total / n\n"
            "         → 488 / 6 = 81.333... 평균이다.\n"
            "            나눗셈 / 는 항상 실수(float)를 만든다. 정수 나눗셈은 // 를 쓴다.\n"
            "  round(avg, 2)\n"
            "         → 81.33. 소수 셋째 자리에서 반올림해 둘째 자리까지 남긴다.\n"
            "            분석 결과를 사람에게 보여줄 땐 반올림이 거의 필수다.\n"
            "  sorted(scores)\n"
            "         → [61, 73, 79, 88, 92, 95] 오름차순 새 리스트.\n"
            "            scores 자체는 바뀌지 않는다. 원본을 바꾸려면 scores.sort() 를 쓴다.\n"
            "  sorted(scores, reverse=True)\n"
            "         → 내림차순. 상위 3명을 뽑을 때 [:3] 과 함께 자주 쓴다.\n"
            "  scores[:3]\n"
            "         → 슬라이싱. 처음부터 3개. '0번 이상 3번 미만'이라 3번은 포함되지 않는다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 인덱스는 0부터 시작한다. 첫 번째 값은 scores[1] 이 아니라 scores[0] 이다.\n"
            "  • 빈 리스트에 sum()/len() 은 되지만 max()/min() 은 에러가 난다.\n"
            "    나눗셈 전에 if n > 0: 으로 확인하는 습관을 들이자.\n"
            "  • sorted() 는 새 리스트를 만들고, .sort() 는 원본을 바꾼다. 둘을 혼동하기 쉽다."
        ),
        usage="데이터를 처음 받았을 때 '몇 개인지, 평균이 얼마인지, 최고/최저가 뭔지' 빠르게 확인할 때.",
        cons="데이터가 수십만 개를 넘어가면 반복문 기반이라 느려진다. 그때부터 numpy 가 필요하다.",
        code=(
            "scores = [88, 92, 79, 95, 61, 73]\n"
            "\n"
            "n = len(scores)\n"
            "total = sum(scores)\n"
            "avg = total / n\n"
            "\n"
            "print('개수 :', n)\n"
            "print('합계 :', total)\n"
            "print('평균 :', round(avg, 2))\n"
            "print('최고 :', max(scores))\n"
            "print('최저 :', min(scores))\n"
            "\n"
            "print('오름차순:', sorted(scores))\n"
            "print('상위 3명:', sorted(scores, reverse=True)[:3])\n"
        ),
    ),

    Lesson(
        id="ds1-03-comprehension",
        lang="datasci", level=STAGE,
        title="리스트 컴프리헨션 — 거르고 바꾸기",
        summary="[식 for 변수 in 리스트 if 조건]",
        explanation=(
            "[개요]\n"
            "분석에서 가장 많이 하는 두 가지 작업이 '거르기(filter)'와 '바꾸기(map)'다.\n"
            "  • 거르기 : 80점 이상만 남긴다\n"
            "  • 바꾸기 : 모든 점수에 5점을 더한다\n"
            "리스트 컴프리헨션은 이 두 가지를 한 줄로 쓰는 파이썬 고유의 문법이다.\n"
            "\n"
            "[기본 형태]\n"
            "  [ 식  for 변수 in 원본 ]              → 바꾸기\n"
            "  [ 식  for 변수 in 원본 if 조건 ]      → 거르면서 바꾸기\n"
            "\n"
            "  읽는 순서는 뒤에서 앞이다.\n"
            "  [s + 5 for s in scores if s >= 80]\n"
            "   ↑3.결과   ↑1.하나씩 꺼내서  ↑2.조건에 맞으면\n"
            "\n"
            "[반복문과 비교]\n"
            "  # 일반 반복문 — 4줄\n"
            "  result = []\n"
            "  for s in scores:\n"
            "      if s >= 80:\n"
            "          result.append(s)\n"
            "\n"
            "  # 컴프리헨션 — 1줄\n"
            "  result = [s for s in scores if s >= 80]\n"
            "  결과는 완전히 같다. 짧을 뿐 아니라 파이썬 내부에서 더 빠르게 처리된다.\n"
            "\n"
            "[코드 분석]\n"
            "  passed = [s for s in scores if s >= 80]\n"
            "         → scores 에서 하나씩 s 로 꺼내, 80 이상인 것만 모아 새 리스트를 만든다.\n"
            "  bonus = [s + 5 for s in scores]\n"
            "         → 모든 값에 5를 더한 새 리스트. 원본 scores 는 그대로다.\n"
            "  capped = [min(s + 5, 100) for s in scores]\n"
            "         → 5점을 더하되 100을 넘지 않게 자른다. min(a, b) 는 둘 중 작은 값이다.\n"
            "            '보너스를 주되 만점 초과는 없다'는 규칙을 그대로 표현한 것이다.\n"
            "  grades = ['A' if s >= 90 else 'B' if s >= 80 else 'C' for s in scores]\n"
            "         → 조건에 따라 다른 값을 넣는 형태(삼항 연산자).\n"
            "            90 이상이면 'A', 아니면 80 이상인지 다시 보고 'B', 그것도 아니면 'C'.\n"
            "            여기서 if 는 '거르기'가 아니라 '값 고르기'라 for 앞에 온다. 위치가 다르다.\n"
            "  len(passed) / len(scores) * 100\n"
            "         → 합격률(%). 개수의 비율을 백분율로 바꾸는 가장 흔한 계산이다.\n"
            "\n"
            "[유의 사항]\n"
            "  • if 가 for 뒤에 오면 '거르기', for 앞에 오면 '값 고르기'다. 위치가 의미를 바꾼다.\n"
            "  • 한 줄에 너무 많은 조건을 넣으면 읽기 어려워진다. 3개를 넘으면 반복문으로 풀어 쓰자.\n"
            "  • 컴프리헨션은 항상 '새 리스트'를 만든다. 원본은 절대 바뀌지 않는다."
        ),
        usage="조건에 맞는 데이터만 뽑거나, 단위 변환(원→달러, 점수→등급)할 때. 전처리의 기본 도구.",
        cons="데이터가 매우 클 때 전부 메모리에 새 리스트로 올린다. 그럴 땐 제너레이터(소괄호)나 numpy 를 쓴다.",
        code=(
            "scores = [88, 92, 79, 95, 61, 73]\n"
            "\n"
            "passed = [s for s in scores if s >= 80]\n"
            "print('80점 이상  :', passed)\n"
            "\n"
            "bonus = [s + 5 for s in scores]\n"
            "print('5점 가산   :', bonus)\n"
            "\n"
            "capped = [min(s + 5, 100) for s in scores]\n"
            "print('100점 상한 :', capped)\n"
            "\n"
            "grades = ['A' if s >= 90 else 'B' if s >= 80 else 'C' for s in scores]\n"
            "print('등급       :', grades)\n"
            "\n"
            "rate = len(passed) / len(scores) * 100\n"
            "print('합격률     :', round(rate, 1), '%')\n"
        ),
    ),

    Lesson(
        id="ds1-04-dict",
        lang="datasci", level=STAGE,
        title="딕셔너리로 데이터 묶기",
        summary="이름-값 쌍 · 한 행(row)을 표현하는 법",
        explanation=(
            "[개요]\n"
            "리스트는 값만 나열한다. 하지만 실제 데이터는 '이름이 붙은 값'이다.\n"
            "  리스트   : [88, 92, 79]            ← 이게 누구 점수인지 알 수 없다\n"
            "  딕셔너리 : {'국어': 88, '수학': 92} ← 무엇의 값인지 명확하다\n"
            "딕셔너리(dict)는 '키(key) → 값(value)' 쌍을 담는 그릇이다. 자바의 HashMap 과 같다.\n"
            "\n"
            "[핵심 개념]\n"
            "• 중괄호로 만든다:      person = {'name': '김철수', 'score': 88}\n"
            "• 키로 값을 꺼낸다:     person['name']  →  '김철수'\n"
            "• 없는 키를 꺼내면 에러: person['age'] → KeyError\n"
            "• 안전하게 꺼내기:      person.get('age', 0)  → 없으면 0 을 대신 준다\n"
            "\n"
            "[표 데이터의 표준 형태]\n"
            "실무에서 표 데이터는 보통 '딕셔너리의 리스트'로 표현된다.\n"
            "  rows = [\n"
            "      {'name': '김철수', 'score': 88},\n"
            "      {'name': '이영희', 'score': 92},\n"
            "  ]\n"
            "딕셔너리 하나가 표의 한 줄(행), 키가 열 이름이다.\n"
            "이 형태를 그대로 pandas 에 넣으면 곧바로 표가 된다 — 2단계에서 다룬다.\n"
            "\n"
            "[코드 분석]\n"
            "  rows = [{'name': ..., 'score': ..., 'dept': ...}, ...]\n"
            "         → 사원 4명의 이름·점수·부서. 표 하나를 파이썬으로 옮긴 것이다.\n"
            "  for r in rows: print(r['name'], r['score'])\n"
            "         → 한 행씩 꺼내 원하는 열만 출력한다.\n"
            "  [r['score'] for r in rows]\n"
            "         → 'score' 열만 뽑아 리스트로 만든다. 이걸 열 추출(column selection)이라 한다.\n"
            "            평균을 내려면 먼저 이렇게 숫자만 모아야 한다.\n"
            "  totals = {}\n"
            "  totals[d] = totals.get(d, 0) + r['score']\n"
            "         → 부서별 점수 합계를 누적한다.\n"
            "            get(d, 0) 은 '아직 그 부서가 없으면 0부터 시작하라'는 뜻이다.\n"
            "            이 패턴이 그룹별 집계(groupby)의 원리다. 자바의\n"
            "            map.put(k, map.getOrDefault(k, 0) + v) 와 똑같다.\n"
            "  counts[d] = counts.get(d, 0) + 1\n"
            "         → 부서별 인원수를 센다. 합계 ÷ 인원수 = 부서 평균.\n"
            "  totals[d] / counts[d]\n"
            "         → 부서별 평균. 그룹 집계의 완성형이다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 딕셔너리의 키는 중복될 수 없다. 같은 키에 다시 넣으면 덮어쓴다.\n"
            "  • 없는 키 접근은 KeyError 로 프로그램이 멈춘다. 실제 데이터엔 빠진 값이 흔하므로\n"
            "    .get(키, 기본값) 을 습관화하는 게 안전하다.\n"
            "  • 이 '직접 집계' 코드는 2단계에서 pandas 의 groupby 한 줄로 대체된다.\n"
            "    다만 원리를 알고 쓰는 것과 모르고 쓰는 것은 디버깅에서 크게 차이난다."
        ),
        usage="한 건의 데이터에 여러 속성이 있을 때(사원, 주문, 로그). 그룹별 집계의 기본 도구.",
        cons="열 단위 계산이 번거롭다. 열마다 리스트로 다시 뽑아야 해서, 표가 커지면 pandas 가 훨씬 낫다.",
        code=(
            "rows = [\n"
            "    {'name': '김철수', 'score': 88, 'dept': '영업'},\n"
            "    {'name': '이영희', 'score': 92, 'dept': '개발'},\n"
            "    {'name': '박민수', 'score': 79, 'dept': '영업'},\n"
            "    {'name': '최지우', 'score': 95, 'dept': '개발'},\n"
            "]\n"
            "\n"
            "print('-- 전체 --')\n"
            "for r in rows:\n"
            "    print(r['name'], r['score'], r['dept'])\n"
            "\n"
            "only_scores = [r['score'] for r in rows]\n"
            "print('점수 열   :', only_scores)\n"
            "print('전체 평균 :', round(sum(only_scores) / len(only_scores), 2))\n"
            "\n"
            "totals, counts = {}, {}\n"
            "for r in rows:\n"
            "    d = r['dept']\n"
            "    totals[d] = totals.get(d, 0) + r['score']\n"
            "    counts[d] = counts.get(d, 0) + 1\n"
            "\n"
            "print('-- 부서별 평균 --')\n"
            "for d in totals:\n"
            "    print(d, round(totals[d] / counts[d], 2))\n"
        ),
    ),

    Lesson(
        id="ds1-05-sort",
        lang="datasci", level=STAGE,
        title="정렬과 순위 매기기",
        summary="key= 로 기준 잡기 · 상위 N · 순위 계산",
        explanation=(
            "[개요]\n"
            "'매출 상위 5개 지점', '점수 순 등수' 처럼 분석 결과는 대개 정렬로 끝난다.\n"
            "핵심은 '무엇을 기준으로 정렬할지'를 지정하는 key 인자다.\n"
            "\n"
            "[key 인자]\n"
            "  sorted(rows, key=lambda r: r['score'])\n"
            "                    └────────┬────────┘\n"
            "                    각 항목에서 '비교에 쓸 값'을 꺼내는 함수\n"
            "\n"
            "  lambda r: r['score'] 는 '이름 없는 짧은 함수'다. 아래와 완전히 같은 뜻이다.\n"
            "      def get_score(r):\n"
            "          return r['score']\n"
            "  자바의 Comparator, `list.sort((a,b) -> a.score - b.score)` 에 해당한다.\n"
            "  다만 파이썬은 '비교 방법'이 아니라 '비교할 값'만 알려주면 된다는 게 더 간단하다.\n"
            "\n"
            "[코드 분석]\n"
            "  sorted(rows, key=lambda r: r['score'], reverse=True)\n"
            "         → 점수 내림차순. reverse=True 가 큰 값부터 정렬하게 만든다.\n"
            "  [:3]\n"
            "         → 앞에서 3개. 정렬 후 슬라이싱하면 '상위 3명'이 된다.\n"
            "  enumerate(ranked, start=1)\n"
            "         → 리스트를 돌면서 번호를 함께 준다. start=1 이므로 1등부터 시작한다.\n"
            "            enumerate 없이 하려면 카운터 변수를 따로 관리해야 해서 번거롭다.\n"
            "  key=lambda r: (-r['score'], r['name'])\n"
            "         → 정렬 기준이 두 개일 때. 튜플(소괄호)로 묶으면 앞에서부터 차례로 비교한다.\n"
            "            -r['score'] 처럼 음수를 붙이면 그 항목만 내림차순이 된다.\n"
            "            즉 '점수 높은 순, 점수가 같으면 이름 가나다순'이라는 뜻이다.\n"
            "            reverse=True 는 모든 기준을 뒤집으므로 이런 혼합 정렬엔 쓸 수 없다.\n"
            "  rows.sort(...)  vs  sorted(rows, ...)\n"
            "         → 앞은 원본을 바꾸고 아무것도 돌려주지 않는다(None).\n"
            "            뒤는 원본을 두고 새 리스트를 돌려준다. 분석에선 뒤쪽이 안전하다.\n"
            "\n"
            "[유의 사항]\n"
            "  • rows = rows.sort() 는 흔한 실수다. sort() 는 None 을 반환하므로 데이터가 사라진다.\n"
            "  • 음수 트릭(-r['score'])은 숫자에만 쓸 수 있다. 문자열은 그렇게 뒤집을 수 없다.\n"
            "  • 같은 값이 여럿일 때 순위를 어떻게 줄지(공동 1위 다음이 2위냐 3위냐)는\n"
            "    비즈니스 규칙이다. 코드로 정하기 전에 요구사항을 확인해야 한다."
        ),
        usage="리포트의 마지막 단계. TOP N 추출, 등수 부여, 랭킹 보드 만들기.",
        cons="정렬은 데이터 개수 N에 대해 N log N 시간이 든다. 상위 몇 개만 필요하면 heapq.nlargest 가 더 빠르다.",
        code=(
            "rows = [\n"
            "    {'name': '김철수', 'score': 88},\n"
            "    {'name': '이영희', 'score': 95},\n"
            "    {'name': '박민수', 'score': 79},\n"
            "    {'name': '최지우', 'score': 95},\n"
            "    {'name': '정하늘', 'score': 61},\n"
            "]\n"
            "\n"
            "ranked = sorted(rows, key=lambda r: r['score'], reverse=True)\n"
            "print('-- 점수 내림차순 --')\n"
            "for i, r in enumerate(ranked, start=1):\n"
            "    print(i, r['name'], r['score'])\n"
            "\n"
            "print('상위 3명:', [r['name'] for r in ranked[:3]])\n"
            "\n"
            "# 점수 높은 순, 동점이면 이름 가나다순\n"
            "tie = sorted(rows, key=lambda r: (-r['score'], r['name']))\n"
            "print('-- 동점 처리 --')\n"
            "for r in tie:\n"
            "    print(r['name'], r['score'])\n"
        ),
    ),

    Lesson(
        id="ds1-06-csv",
        lang="datasci", level=STAGE,
        title="CSV 데이터 읽기",
        summary="쉼표로 구분된 텍스트 → 파이썬 데이터",
        explanation=(
            "[개요]\n"
            "실제 데이터는 대부분 CSV(Comma-Separated Values) 파일로 온다.\n"
            "엑셀에서 '다른 이름으로 저장 → CSV' 하면 나오는, 쉼표로 칸을 나눈 순수 텍스트다.\n"
            "\n"
            "  name,score,dept        ← 첫 줄은 보통 열 이름(헤더)\n"
            "  김철수,88,영업\n"
            "  이영희,92,개발\n"
            "\n"
            "[직접 파싱해 보기]\n"
            "원리를 알기 위해 문자열 기능만으로 직접 잘라 본다.\n"
            "  • text.strip()        → 앞뒤 공백·줄바꿈 제거\n"
            "  • text.split('\\n')    → 줄 단위로 자르기\n"
            "  • line.split(',')     → 쉼표로 칸 자르기\n"
            "  • zip(header, values) → 열 이름과 값을 짝지어 딕셔너리로\n"
            "\n"
            "[코드 분석]\n"
            "  raw = '''name,score,dept\\n김철수,88,영업\\n...'''\n"
            "         → 삼중 따옴표는 여러 줄 문자열이다. 파일에서 읽은 내용을 흉내낸 것이다.\n"
            "  lines = raw.strip().split('\\n')\n"
            "         → 앞뒤 빈 줄을 없앤 뒤 줄 단위로 자른다. 결과는 문자열 리스트다.\n"
            "  header = lines[0].split(',')\n"
            "         → 첫 줄을 쉼표로 잘라 ['name', 'score', 'dept'] 를 얻는다.\n"
            "  for line in lines[1:]:\n"
            "         → 두 번째 줄부터가 실제 데이터다. [1:] 로 헤더를 건너뛴다.\n"
            "  values = line.split(',')\n"
            "         → ['김철수', '88', '영업']. 주의: 88 이 숫자가 아니라 문자열 '88' 이다.\n"
            "  row = dict(zip(header, values))\n"
            "         → zip 은 두 리스트를 앞에서부터 짝짓는다.\n"
            "            ('name','김철수'), ('score','88'), ('dept','영업')\n"
            "            dict() 로 감싸면 {'name': '김철수', ...} 딕셔너리가 된다.\n"
            "  row['score'] = int(row['score'])\n"
            "         → 문자열 '88' 을 정수 88 로 바꾼다. 이걸 빠뜨리면\n"
            "            sum() 에서 '문자열은 더할 수 없다'는 에러가 난다. 가장 흔한 실수다.\n"
            "  csv.DictReader\n"
            "         → 파이썬 표준 라이브러리. 위 과정을 알아서 해준다.\n"
            "            따옴표 안의 쉼표 같은 까다로운 경우까지 처리하므로 실무에선 이걸 쓴다.\n"
            "\n"
            "[유의 사항]\n"
            "  • CSV 에서 읽은 값은 전부 문자열이다. 숫자로 쓸 열은 반드시 int()/float() 변환.\n"
            "  • 값 안에 쉼표가 들어 있으면(\"서울, 강남\") 직접 split 은 깨진다. csv 모듈을 써야 한다.\n"
            "  • 한글 파일은 인코딩 문제가 잦다. 파일을 열 땐 encoding='utf-8' 을 명시하자.\n"
            "  • 2단계에서 배울 pandas 는 pd.read_csv('파일.csv') 한 줄로 이 모든 걸 끝낸다."
        ),
        usage="파일에서 데이터를 가져오는 첫 관문. 분석 파이프라인의 시작점.",
        cons="직접 파싱은 예외 상황(따옴표, 줄바꿈 포함 값)에 취약하다. 실무에선 csv 모듈이나 pandas 를 쓴다.",
        code=(
            "import csv\n"
            "import io\n"
            "\n"
            "raw = '''name,score,dept\n"
            "김철수,88,영업\n"
            "이영희,92,개발\n"
            "박민수,79,영업\n"
            "최지우,95,개발'''\n"
            "\n"
            "# 1) 직접 파싱 — 원리 확인\n"
            "lines = raw.strip().split('\\n')\n"
            "header = lines[0].split(',')\n"
            "rows = []\n"
            "for line in lines[1:]:\n"
            "    values = line.split(',')\n"
            "    row = dict(zip(header, values))\n"
            "    row['score'] = int(row['score'])   # 문자열 → 정수\n"
            "    rows.append(row)\n"
            "\n"
            "print('헤더:', header)\n"
            "print('첫 행:', rows[0])\n"
            "print('평균:', round(sum(r['score'] for r in rows) / len(rows), 2))\n"
            "\n"
            "# 2) csv 모듈 — 실무 방식\n"
            "print('-- csv.DictReader --')\n"
            "reader = csv.DictReader(io.StringIO(raw))\n"
            "for row in reader:\n"
            "    print(row['name'], int(row['score']))\n"
        ),
    ),

    Lesson(
        id="ds1-07-nparray",
        lang="datasci", level=STAGE,
        title="numpy 배열 첫걸음",
        summary="왜 리스트 대신 배열인가 · 벡터 연산",
        explanation=(
            "[개요]\n"
            "numpy 배열(ndarray)은 '같은 타입의 숫자만 담는, 크기가 고정된 리스트'다.\n"
            "제약이 늘어난 대신 압도적으로 빨라지고, 계산 코드가 짧아진다.\n"
            "\n"
            "[리스트와 무엇이 다른가]\n"
            "  리스트: [1, 2, 3] * 2  →  [1, 2, 3, 1, 2, 3]   (반복 — 붙여 늘린다)\n"
            "  배열  : np.array([1,2,3]) * 2  →  [2, 4, 6]     (계산 — 각 값에 곱한다)\n"
            "\n"
            "이 차이가 핵심이다. 배열은 '수학의 벡터'처럼 동작한다.\n"
            "리스트로 각 값에 2를 곱하려면 반복문이나 컴프리헨션이 필요하지만,\n"
            "배열은 그냥 * 2 라고 쓰면 된다. 이를 벡터 연산(vectorization)이라 한다.\n"
            "\n"
            "[왜 빠른가]\n"
            "• 리스트는 각 칸이 '어딘가에 있는 객체를 가리키는 주소'라 값이 메모리에 흩어져 있다.\n"
            "• 배열은 숫자 자체가 메모리에 빈틈없이 줄지어 있다.\n"
            "• 그래서 numpy 는 반복문을 파이썬이 아니라 내부 C 코드로 한 번에 처리한다.\n"
            "  데이터 100만 개 기준으로 보통 20~50배 빠르다.\n"
            "\n"
            "[코드 분석]\n"
            "  arr = np.array([88, 92, 79, 95, 61])\n"
            "         → 리스트를 배열로 바꾼다. 가장 기본적인 배열 생성법이다.\n"
            "  arr.dtype\n"
            "         → 배열에 담긴 숫자의 타입. int64(64비트 정수) 같은 값이 나온다.\n"
            "            배열은 한 가지 타입만 담는다. 그래서 계산이 빠른 것이다.\n"
            "  arr.shape\n"
            "         → 배열의 모양. (5,) 는 '값 5개짜리 1차원'이라는 뜻이다.\n"
            "            뒤의 쉼표는 '원소가 하나인 튜플'이라는 표시다.\n"
            "  arr + 5\n"
            "         → 모든 값에 5를 더한다. [93, 97, 84, 100, 66]\n"
            "  arr * 2, arr / 10\n"
            "         → 마찬가지로 전체에 적용된다. 반복문이 전혀 필요 없다.\n"
            "  arr2 = np.array([1, 2, 3, 4, 5])\n"
            "  arr + arr2\n"
            "         → 배열끼리 더하면 같은 위치끼리 더해진다.\n"
            "            [88+1, 92+2, 79+3, 95+4, 61+5] = [89, 94, 82, 99, 66]\n"
            "            길이가 다르면 에러가 난다.\n"
            "  np.zeros(5), np.ones(3), np.arange(0, 10, 2)\n"
            "         → 각각 0으로 채운 배열, 1로 채운 배열, 0부터 10 미만까지 2씩 증가.\n"
            "            arange 는 range 의 배열 버전이라고 보면 된다.\n"
            "  np.linspace(0, 1, 5)\n"
            "         → 0부터 1까지를 5등분한 값. [0, 0.25, 0.5, 0.75, 1]\n"
            "            그래프의 x축을 만들 때 자주 쓴다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 배열은 크기를 나중에 늘릴 수 없다. append 가 필요하면 리스트로 모은 뒤 마지막에 변환하자.\n"
            "  • 정수 배열에 실수를 넣으면 소수점이 잘린다. 실수를 쓸 거면 처음부터\n"
            "    np.array([1, 2, 3], dtype=float) 로 만들자.\n"
            "  • 배열 안의 값 하나(arr[0])는 파이썬 int 가 아니라 np.int64 다.\n"
            "    이대로 출력하면 'np.int64(88)' 처럼 보일 수 있으니 int() 로 감싸는 게 안전하다."
        ),
        usage="숫자 계산이 들어가는 모든 곳. 통계·머신러닝·딥러닝의 데이터는 전부 numpy 배열이다.",
        cons="문자열이나 서로 다른 타입이 섞인 데이터엔 맞지 않는다. 그런 표 데이터는 pandas 담당이다.",
        code=(
            "import numpy as np\n"
            "\n"
            "arr = np.array([88, 92, 79, 95, 61])\n"
            "print('배열  :', arr)\n"
            "print('타입  :', arr.dtype)\n"
            "print('모양  :', arr.shape)\n"
            "\n"
            "print('+5    :', arr + 5)\n"
            "print('*2    :', arr * 2)\n"
            "print('/10   :', arr / 10)\n"
            "\n"
            "arr2 = np.array([1, 2, 3, 4, 5])\n"
            "print('배열끼리 덧셈:', arr + arr2)\n"
            "\n"
            "print('zeros  :', np.zeros(5))\n"
            "print('ones   :', np.ones(3))\n"
            "print('arange :', np.arange(0, 10, 2))\n"
            "print('linspace:', np.linspace(0, 1, 5))\n"
            "\n"
            "# 리스트와의 차이 확인\n"
            "print('리스트 * 2:', [88, 92] * 2)\n"
            "print('배열   * 2:', np.array([88, 92]) * 2)\n"
        ),
    ),

    Lesson(
        id="ds1-08-indexing",
        lang="datasci", level=STAGE,
        title="배열 인덱싱 · 불리언 마스크",
        summary="조건으로 데이터 걸러내기 — 분석의 핵심 기술",
        explanation=(
            "[개요]\n"
            "'80점 이상만 보고 싶다'처럼 조건으로 데이터를 걸러내는 일은 분석에서 끝없이 반복된다.\n"
            "numpy 는 이걸 arr[arr >= 80] 한 줄로 해낸다. 불리언 마스크(boolean mask)라 부른다.\n"
            "\n"
            "[불리언 마스크의 원리]\n"
            "  arr = [88, 92, 79, 95, 61]\n"
            "\n"
            "  1) arr >= 80  을 계산하면 값이 아니라 True/False 배열이 나온다.\n"
            "     → [True, True, False, True, False]\n"
            "     이걸 '마스크'라고 한다. 통과시킬 자리를 표시한 가림막이다.\n"
            "\n"
            "  2) arr[마스크]  → True 인 자리의 값만 뽑아 새 배열을 만든다.\n"
            "     → [88, 92, 95]\n"
            "\n"
            "이 두 단계가 pandas 의 데이터 필터링과 완전히 같은 원리다.\n"
            "2단계에서 df[df['score'] >= 80] 을 만나면 여기가 떠올라야 한다.\n"
            "\n"
            "[코드 분석]\n"
            "  arr[0], arr[-1]\n"
            "         → 첫 값, 마지막 값. 리스트와 같은 방식이다.\n"
            "  arr[1:4]\n"
            "         → 1번 이상 4번 미만 → [92, 79, 95]. 끝 번호는 포함하지 않는다.\n"
            "  arr[[0, 2, 4]]\n"
            "         → 팬시 인덱싱. 원하는 위치를 리스트로 한꺼번에 지정한다.\n"
            "            리스트로는 안 되는, 배열만의 기능이다.\n"
            "  mask = arr >= 80\n"
            "         → True/False 배열. 원본과 길이가 같다.\n"
            "  arr[mask]\n"
            "         → 조건을 만족하는 값만. 필터링의 완성형이다.\n"
            "  mask.sum()\n"
            "         → True 를 1, False 를 0 으로 세므로 '조건을 만족하는 개수'가 된다.\n"
            "            이 트릭은 굉장히 자주 쓰인다. 합격자 수 세기 = (arr >= 80).sum()\n"
            "  mask.mean()\n"
            "         → 같은 원리로 '비율'이 나온다. 0.6 이면 60% 가 조건을 만족한다는 뜻이다.\n"
            "  arr[(arr >= 70) & (arr <= 90)]\n"
            "         → 조건 두 개. 반드시 & (and), | (or) 를 쓰고 각 조건을 괄호로 감싼다.\n"
            "            파이썬의 and/or 는 배열에 쓸 수 없어 에러가 난다.\n"
            "            괄호를 빼면 연산자 우선순위 때문에 엉뚱하게 계산되므로 필수다.\n"
            "  np.where(arr >= 80, '합격', '불합격')\n"
            "         → 조건에 따라 다른 값을 채운 배열을 만든다.\n"
            "            엑셀의 IF 함수와 같다. 등급 부여에 자주 쓴다.\n"
            "\n"
            "[유의 사항]\n"
            "  • and/or/not 은 배열에 못 쓴다. 각각 & / | / ~ 를 쓴다.\n"
            "  • 조건마다 괄호를 반드시 감싼다. arr >= 70 & arr <= 90 은 에러거나 오답이다.\n"
            "  • arr[mask] 는 새 배열(복사본)이다. 여기를 고쳐도 원본은 안 바뀐다.\n"
            "    반대로 arr[1:4] 슬라이싱은 원본을 들여다보는 창(view)이라 고치면 원본도 바뀐다."
        ),
        usage="이상치 제거, 조건별 집계, 특정 구간 추출. 전처리에서 가장 많이 쓰는 기술.",
        cons="마스크는 원본과 같은 길이의 배열을 새로 만든다. 데이터가 아주 크면 메모리를 두 배로 쓴다.",
        code=(
            "import numpy as np\n"
            "\n"
            "arr = np.array([88, 92, 79, 95, 61])\n"
            "\n"
            "print('첫 값    :', arr[0])\n"
            "print('마지막   :', arr[-1])\n"
            "print('1~3번    :', arr[1:4])\n"
            "print('0,2,4번  :', arr[[0, 2, 4]])\n"
            "\n"
            "mask = arr >= 80\n"
            "print('마스크   :', mask)\n"
            "print('80점 이상:', arr[mask])\n"
            "print('합격 인원:', mask.sum())\n"
            "print('합격률   :', round(float(mask.mean()) * 100, 1), '%')\n"
            "\n"
            "print('70~90점  :', arr[(arr >= 70) & (arr <= 90)])\n"
            "print('판정     :', np.where(arr >= 80, '합격', '불합격'))\n"
        ),
    ),

    Lesson(
        id="ds1-09-aggregate",
        lang="datasci", level=STAGE,
        title="배열 집계 함수",
        summary="mean · sum · std · min · max · argmax",
        explanation=(
            "[개요]\n"
            "집계(aggregation)는 여러 숫자를 하나의 대표값으로 줄이는 일이다.\n"
            "'우리 반 평균은?' '가장 높은 점수는?' 같은 질문에 답하는 단계다.\n"
            "\n"
            "[자주 쓰는 집계 함수]\n"
            "  arr.sum()    합계\n"
            "  arr.mean()   평균\n"
            "  arr.min()    최솟값        arr.argmin()  최솟값의 '위치'\n"
            "  arr.max()    최댓값        arr.argmax()  최댓값의 '위치'\n"
            "  arr.std()    표준편차 — 값이 평균에서 얼마나 흩어져 있는지\n"
            "  arr.var()    분산 — 표준편차의 제곱\n"
            "  np.median(arr)  중앙값 — 정렬했을 때 한가운데 값\n"
            "\n"
            "[평균 vs 중앙값 — 중요]\n"
            "  연봉 [3000, 3200, 3100, 3300, 50000] (단위 만원)\n"
            "    평균   : 12520  ← 한 명의 극단값에 완전히 끌려간다\n"
            "    중앙값 : 3200   ← 대다수의 실제 모습에 가깝다\n"
            "  극단값(이상치)이 있을 땐 중앙값이 더 정직한 대표값이다.\n"
            "  뉴스에서 '평균 연봉'과 '중위 연봉'을 구분해 쓰는 이유가 이것이다.\n"
            "\n"
            "[표준편차가 말해주는 것]\n"
            "  A반 점수 [70, 70, 70, 70]  → 평균 70, 표준편차 0    (모두 똑같다)\n"
            "  B반 점수 [40, 60, 80, 100] → 평균 70, 표준편차 22.4 (실력 차가 크다)\n"
            "  평균이 같아도 성격이 전혀 다른 집단이다. 평균만 보면 안 되는 이유다.\n"
            "\n"
            "[코드 분석]\n"
            "  arr.mean()\n"
            "         → 합계 ÷ 개수. 결과는 np.float64 라는 numpy 전용 실수형이다.\n"
            "  float(arr.mean())\n"
            "         → 파이썬 기본 float 으로 변환. 출력하거나 함수 반환값으로 쓸 땐\n"
            "            이렇게 변환하는 습관이 좋다. repr 이 깔끔해진다.\n"
            "  arr.argmax()\n"
            "         → 최댓값이 몇 번째에 있는지(위치). 값이 아니라 인덱스다.\n"
            "            names[arr.argmax()] 처럼 쓰면 '최고점자의 이름'을 찾을 수 있다.\n"
            "  arr.std()\n"
            "         → numpy 기본은 모집단 표준편차(N 으로 나눔)다.\n"
            "            표본 표준편차(N-1 로 나눔)가 필요하면 arr.std(ddof=1) 을 쓴다.\n"
            "            pandas 는 반대로 기본이 ddof=1 이다. 두 값이 미세하게 다르니 주의.\n"
            "  np.median(arr)\n"
            "         → 중앙값. 개수가 짝수면 가운데 두 값의 평균이다.\n"
            "  np.percentile(arr, 25)\n"
            "         → 하위 25% 지점의 값(1사분위수). 데이터 분포를 볼 때 쓴다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 빈 배열에 mean() 을 하면 nan(Not a Number)이 나오고 경고가 뜬다.\n"
            "  • std() 의 ddof 기본값이 numpy(0)와 pandas(1)에서 다르다. 값이 안 맞으면 여기를 의심하자.\n"
            "  • 평균만 보고 판단하지 말 것. 최소한 중앙값과 표준편차를 함께 봐야 한다."
        ),
        usage="데이터를 처음 받았을 때 성격을 파악하는 '기술통계' 단계. 모든 분석의 첫 화면.",
        cons="집계는 정보를 잃는 과정이다. 평균 하나로 줄이면 분포의 모양은 사라진다. 여러 지표를 함께 봐야 한다.",
        code=(
            "import numpy as np\n"
            "\n"
            "names = np.array(['김철수', '이영희', '박민수', '최지우', '정하늘'])\n"
            "arr = np.array([88, 92, 79, 95, 61])\n"
            "\n"
            "print('합계    :', int(arr.sum()))\n"
            "print('평균    :', round(float(arr.mean()), 2))\n"
            "print('중앙값  :', float(np.median(arr)))\n"
            "print('표준편차:', round(float(arr.std()), 2))\n"
            "print('최고    :', int(arr.max()), '→', names[arr.argmax()])\n"
            "print('최저    :', int(arr.min()), '→', names[arr.argmin()])\n"
            "print('1사분위 :', float(np.percentile(arr, 25)))\n"
            "\n"
            "# 평균이 같아도 성격이 다른 두 집단\n"
            "a = np.array([70, 70, 70, 70])\n"
            "b = np.array([40, 60, 80, 100])\n"
            "print('A반 평균/편차:', float(a.mean()), round(float(a.std()), 2))\n"
            "print('B반 평균/편차:', float(b.mean()), round(float(b.std()), 2))\n"
            "\n"
            "# 이상치가 평균을 끌고 가는 예\n"
            "pay = np.array([3000, 3200, 3100, 3300, 50000])\n"
            "print('연봉 평균  :', float(pay.mean()))\n"
            "print('연봉 중앙값:', float(np.median(pay)))\n"
        ),
    ),

    Lesson(
        id="ds1-10-2d",
        lang="datasci", level=STAGE,
        title="2차원 배열 · 축(axis)",
        summary="행과 열 · axis=0 은 세로, axis=1 은 가로",
        explanation=(
            "[개요]\n"
            "표 데이터는 2차원이다. 세로가 행(row, 사람), 가로가 열(column, 과목)이다.\n"
            "numpy 는 이를 2차원 배열로 표현하고, '어느 방향으로 계산할지'를 axis 로 지정한다.\n"
            "\n"
            "[axis 의 의미 — 가장 헷갈리는 부분]\n"
            "        국어  영어  수학\n"
            "  철수   80    90    70\n"
            "  영희   85    95    75\n"
            "  민수   60    70    65\n"
            "\n"
            "  axis=0 → 행 방향으로 훑는다(↓ 세로). 결과는 '과목별' 값 3개.\n"
            "           과목 평균을 구할 때 쓴다.\n"
            "  axis=1 → 열 방향으로 훑는다(→ 가로). 결과는 '사람별' 값 3개.\n"
            "           개인 평균을 구할 때 쓴다.\n"
            "\n"
            "  외우는 법: axis 는 '없어지는 축'이다.\n"
            "  shape 이 (3행, 3열) 일 때 axis=0 을 쓰면 행이 사라져 (3열,) 만 남는다.\n"
            "\n"
            "[코드 분석]\n"
            "  m = np.array([[80, 90, 70], [85, 95, 75], [60, 70, 65]])\n"
            "         → 대괄호가 두 겹이다. 안쪽 대괄호 하나가 한 행이다.\n"
            "  m.shape\n"
            "         → (3, 3). 앞이 행 개수, 뒤가 열 개수다.\n"
            "  m[0]\n"
            "         → 0번 행 전체 → [80, 90, 70] (철수의 세 과목 점수)\n"
            "  m[0, 1]\n"
            "         → 0행 1열 → 90 (철수의 영어). [행, 열] 순서다.\n"
            "  m[:, 0]\n"
            "         → 콜론(:)은 '전부'라는 뜻. 모든 행의 0번 열 → [80, 85, 60]\n"
            "            즉 국어 열 전체다. 열 하나를 뽑는 표준 방법이다.\n"
            "  m[1, :]\n"
            "         → 1행 전체. m[1] 과 같지만 의도가 더 분명하다.\n"
            "  m.mean(axis=0)\n"
            "         → 과목별 평균 [75, 85, 70]. 세로로 훑었다.\n"
            "  m.mean(axis=1)\n"
            "         → 개인별 평균 [80, 85, 65]. 가로로 훑었다.\n"
            "  m.mean()\n"
            "         → axis 를 안 주면 전체 9개 값의 평균 하나가 나온다.\n"
            "  m.sum(axis=1)\n"
            "         → 개인별 총점. 성적표의 '합계' 열이다.\n"
            "  m.T\n"
            "         → 전치(transpose). 행과 열을 뒤집는다. (3,3)→(3,3) 이지만 내용이 바뀐다.\n"
            "            데이터 방향이 반대로 들어왔을 때 바로잡는 데 쓴다.\n"
            "\n"
            "[유의 사항]\n"
            "  • m[0][1] 도 동작하지만 m[0, 1] 이 표준이고 더 빠르다.\n"
            "  • axis 방향은 초보자가 가장 많이 틀리는 부분이다.\n"
            "    헷갈리면 결과의 개수를 보자. 과목이 3개인데 결과가 3개면 axis=0 이 맞다.\n"
            "  • shape 을 자주 출력해 보는 습관이 디버깅 시간을 크게 줄여준다."
        ),
        usage="성적표·매출표 같은 표 데이터 계산. 딥러닝의 데이터 배치도 전부 이 구조다.",
        cons="차원이 3개 이상으로 늘면 axis 를 머릿속으로 따라가기 어려워진다. 그때는 shape 을 찍어가며 확인해야 한다.",
        code=(
            "import numpy as np\n"
            "\n"
            "names = ['철수', '영희', '민수']\n"
            "subjects = ['국어', '영어', '수학']\n"
            "m = np.array([\n"
            "    [80, 90, 70],\n"
            "    [85, 95, 75],\n"
            "    [60, 70, 65],\n"
            "])\n"
            "\n"
            "print('모양     :', m.shape)\n"
            "print('철수 전체:', m[0])\n"
            "print('철수 영어:', m[0, 1])\n"
            "print('국어 열  :', m[:, 0])\n"
            "\n"
            "print('-- 과목별 평균 (axis=0) --')\n"
            "for s, v in zip(subjects, m.mean(axis=0)):\n"
            "    print(s, round(float(v), 2))\n"
            "\n"
            "print('-- 개인별 평균 (axis=1) --')\n"
            "for nm, v in zip(names, m.mean(axis=1)):\n"
            "    print(nm, round(float(v), 2))\n"
            "\n"
            "print('전체 평균:', round(float(m.mean()), 2))\n"
            "print('개인 총점:', m.sum(axis=1))\n"
            "print('전치 후 모양:', m.T.shape)\n"
        ),
    ),

    Lesson(
        id="ds1-11-broadcast",
        lang="datasci", level=STAGE,
        title="브로드캐스팅",
        summary="모양이 다른 배열끼리 계산하는 규칙",
        explanation=(
            "[개요]\n"
            "브로드캐스팅은 모양이 다른 배열끼리 계산할 때 numpy 가 작은 쪽을 자동으로\n"
            "늘려 맞춰주는 규칙이다. 이미 arr + 5 를 쓸 때 사용하고 있었다.\n"
            "숫자 5 를 배열 길이만큼 [5,5,5,5,5] 로 늘려서 더한 것이다.\n"
            "\n"
            "[규칙]\n"
            "뒤쪽 차원부터 비교해서, 두 배열의 각 차원이\n"
            "  • 같거나\n"
            "  • 둘 중 하나가 1 이면\n"
            "계산이 가능하고, 1 인 쪽이 상대 크기만큼 복제된다. 아니면 에러다.\n"
            "\n"
            "  (3, 3) 과 (3,)  →  (3,) 가 각 행에 적용됨. 가능\n"
            "  (3, 3) 과 (3, 1) → (3,1) 이 각 열에 적용됨. 가능\n"
            "  (3, 3) 과 (2,)  →  3 과 2 가 안 맞음. 에러\n"
            "\n"
            "[실전에서 왜 중요한가]\n"
            "  • 과목별 난이도 보정: 각 과목에 다른 가산점을 준다\n"
            "  • 정규화: 각 열에서 그 열의 평균을 뺀다  →  머신러닝 전처리의 필수 과정\n"
            "  반복문 없이 한 줄로 끝나므로 코드가 짧고 빠르다.\n"
            "\n"
            "[코드 분석]\n"
            "  m + 5\n"
            "         → 스칼라 브로드캐스팅. 모든 칸에 5를 더한다.\n"
            "  bonus = np.array([5, 0, 10])\n"
            "  m + bonus\n"
            "         → (3,3) + (3,). bonus 가 모든 행에 똑같이 적용된다.\n"
            "            국어 +5, 영어 +0, 수학 +10. 즉 '과목별' 보정이다.\n"
            "  personal = np.array([[1], [2], [3]])\n"
            "  m + personal\n"
            "         → (3,3) + (3,1). 이번엔 세로로 늘어난다.\n"
            "            철수 +1, 영희 +2, 민수 +3. 즉 '사람별' 보정이다.\n"
            "            같은 세 개의 숫자라도 모양이 (3,) 이냐 (3,1) 이냐에 따라\n"
            "            적용 방향이 완전히 달라진다. 이게 브로드캐스팅의 핵심이다.\n"
            "  m.reshape(-1, 1)\n"
            "         → 모양 바꾸기. -1 은 '나머지는 알아서 계산하라'는 뜻이다.\n"
            "            (3,) 짜리를 (3,1) 로 세울 때 자주 쓴다.\n"
            "  centered = m - m.mean(axis=0)\n"
            "         → 각 열에서 그 열의 평균을 뺀다. 결과의 열 평균은 모두 0 이 된다.\n"
            "            '중심화(centering)'라 하며, 머신러닝 전처리의 첫 단계다.\n"
            "  (m - m.mean(axis=0)) / m.std(axis=0)\n"
            "         → 표준화(standardization). 평균 0, 표준편차 1 로 맞춘다.\n"
            "            단위가 다른 열(키 cm, 몸무게 kg)을 공정하게 비교할 수 있게 만든다.\n"
            "            2단계·3단계에서 계속 나오는 아주 중요한 변환이다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 에러 메시지 'operands could not be broadcast together' 는 모양 불일치다.\n"
            "    양쪽 .shape 을 출력해 보면 원인이 바로 보인다.\n"
            "  • (3,) 과 (3,1) 은 다르다. 전자는 가로 방향, 후자는 세로 방향으로 퍼진다.\n"
            "  • 표준편차가 0 인 열(모든 값이 같음)을 나누면 0으로 나누기가 되어 nan 이 된다."
        ),
        usage="정규화·표준화 같은 전처리, 가중치 적용, 편향(bias) 더하기. 딥러닝 계산의 뼈대다.",
        cons="자동으로 맞춰주다 보니 의도하지 않은 모양으로도 계산이 되어버려 조용한 버그가 생길 수 있다.",
        code=(
            "import numpy as np\n"
            "\n"
            "m = np.array([\n"
            "    [80, 90, 70],\n"
            "    [85, 95, 75],\n"
            "    [60, 70, 65],\n"
            "], dtype=float)\n"
            "\n"
            "print('원본:\\n', m)\n"
            "print('전체 +5:\\n', m + 5)\n"
            "\n"
            "bonus = np.array([5, 0, 10])            # (3,) → 과목별\n"
            "print('과목별 가산:\\n', m + bonus)\n"
            "\n"
            "personal = np.array([[1], [2], [3]])    # (3,1) → 사람별\n"
            "print('사람별 가산:\\n', m + personal)\n"
            "\n"
            "centered = m - m.mean(axis=0)\n"
            "print('중심화 후 열 평균:', centered.mean(axis=0).round(10))\n"
            "\n"
            "std = (m - m.mean(axis=0)) / m.std(axis=0)\n"
            "print('표준화:\\n', std.round(3))\n"
            "print('표준화 후 열 표준편차:', std.std(axis=0).round(10))\n"
        ),
    ),

    Lesson(
        id="ds1-12-random",
        lang="datasci", level=STAGE,
        title="난수와 샘플링",
        summary="가짜 데이터 만들기 · seed 로 결과 고정",
        explanation=(
            "[개요]\n"
            "분석을 연습하려면 데이터가 필요하다. 난수로 그럴듯한 가짜 데이터를 만들면\n"
            "실제 데이터 없이도 코드를 검증할 수 있다. 머신러닝의 데이터 분할·초기화도 난수를 쓴다.\n"
            "\n"
            "[재현성(reproducibility) — 가장 중요한 개념]\n"
            "난수는 실행할 때마다 달라진다. 그러면 어제 나온 분석 결과를 오늘 재현할 수 없다.\n"
            "그래서 '시드(seed)'를 고정한다. 시드가 같으면 항상 같은 난수가 나온다.\n"
            "  rng = np.random.default_rng(42)\n"
            "숫자 42 는 관례일 뿐 아무 값이나 된다. 중요한 건 '고정했다'는 사실이다.\n"
            "논문·실무 코드에서 시드 고정은 사실상 필수 규칙이다.\n"
            "\n"
            "[코드 분석]\n"
            "  rng = np.random.default_rng(42)\n"
            "         → 난수 생성기를 만든다. 예전 방식인 np.random.seed(42) 보다\n"
            "            이 방식이 현재 권장된다. 생성기를 변수로 들고 다닐 수 있어 안전하다.\n"
            "  rng.integers(0, 100, size=10)\n"
            "         → 0 이상 100 미만 정수 10개. 시험 점수를 흉내낼 때 쓴다.\n"
            "  rng.random(5)\n"
            "         → 0 이상 1 미만 실수 5개. 확률을 흉내낼 때 쓴다.\n"
            "  rng.normal(loc=70, scale=10, size=10)\n"
            "         → 정규분포(종 모양) 난수. loc 이 평균, scale 이 표준편차다.\n"
            "            현실의 키·몸무게·시험점수는 대체로 정규분포를 따르므로\n"
            "            진짜 같은 가짜 데이터를 만들 때 이걸 쓴다.\n"
            "  .round(1)\n"
            "         → 소수 첫째 자리까지. 실수 난수는 자릿수가 길어 보기 나쁘다.\n"
            "  rng.choice(names, size=3, replace=False)\n"
            "         → 목록에서 무작위로 뽑는다. replace=False 는 '중복 없이'라는 뜻이다.\n"
            "            추첨, 표본 추출에 쓴다.\n"
            "  rng.permutation(10)\n"
            "         → 0~9 를 무작위로 섞은 배열. 데이터를 훈련용/검증용으로 나눌 때\n"
            "            먼저 섞어야 편향이 없어진다. 3단계에서 다시 나온다.\n"
            "  같은 시드로 다시 만들어 비교\n"
            "         → 두 번째 생성기도 42 로 만들면 첫 번째와 완전히 같은 값이 나온다.\n"
            "            이게 재현성이다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 시드를 고정하지 않으면 실행마다 결과가 달라 채점·디버깅이 불가능해진다.\n"
            "  • 시드를 고정해도 numpy 버전이 크게 바뀌면 값이 달라질 수 있다.\n"
            "  • 난수로 만든 데이터는 어디까지나 연습용이다. 실제 현상의 성질은 담고 있지 않다."
        ),
        usage="연습용 데이터 생성, 훈련/검증 데이터 분할, 신경망 가중치 초기화, A/B 테스트 시뮬레이션.",
        cons="시드를 고정하면 '그 시드에서만 잘 되는' 결과에 속을 수 있다. 중요한 결론은 여러 시드로 확인해야 한다.",
        code=(
            "import numpy as np\n"
            "\n"
            "rng = np.random.default_rng(42)\n"
            "\n"
            "print('정수 난수  :', rng.integers(0, 100, size=10))\n"
            "print('실수 난수  :', rng.random(5).round(3))\n"
            "\n"
            "scores = rng.normal(loc=70, scale=10, size=10).round(1)\n"
            "print('정규분포   :', scores)\n"
            "print('평균/편차  :', round(float(scores.mean()), 2), round(float(scores.std()), 2))\n"
            "\n"
            "names = np.array(['철수', '영희', '민수', '지우', '하늘'])\n"
            "print('무작위 3명 :', rng.choice(names, size=3, replace=False))\n"
            "print('섞기       :', rng.permutation(10))\n"
            "\n"
            "# 재현성 확인 — 같은 시드는 같은 결과\n"
            "a = np.random.default_rng(42).integers(0, 100, size=5)\n"
            "b = np.random.default_rng(42).integers(0, 100, size=5)\n"
            "print('시드 42 재현:', a, b, '→ 같은가?', bool((a == b).all()))\n"
        ),
    ),
]
