"""5단계 — LLM · 트랜스포머 (로드맵 + 핵심 개념 맛보기).

GPT 계열 모델의 부품을 numpy 로 하나씩 만들어 본다.
'글자를 넣으면 다음 글자가 나온다'는 과정이 실제로 어떤 계산인지 확인하는 게 목적이다.
"""

from engine.models import Lesson

STAGE = "5. LLM · 트랜스포머"

LESSONS = [

    Lesson(
        id="ds5-01-roadmap",
        lang="datasci", level=STAGE,
        title="LLM 로드맵",
        summary="GPT 는 결국 '다음 단어 맞히기' 기계다",
        explanation=(
            "[개요]\n"
            "LLM(Large Language Model, 대규모 언어 모델)이 하는 일은 딱 하나다.\n"
            "  '지금까지의 글을 보고 다음에 올 토큰의 확률을 계산한다'\n"
            "\n"
            "  입력 : '오늘 날씨가 정말'\n"
            "  출력 : { '좋다': 0.42, '춥다': 0.18, '덥다': 0.15, ... }\n"
            "\n"
            "이걸 반복해서 한 글자씩 이어붙이면 문장이 된다.\n"
            "놀라운 대화 능력도 결국 이 단순한 작업을 어마어마한 규모로 한 결과다.\n"
            "\n"
            "[처리 파이프라인]\n"
            "  1) 토크나이저 : 문장 → 토큰 번호   '안녕하세요' → [1234, 5678]\n"
            "  2) 임베딩     : 토큰 번호 → 의미 벡터  1234 → [0.2, -0.5, ...] (수백~수천 차원)\n"
            "  3) 위치 인코딩: 단어의 순서 정보를 더한다\n"
            "  4) 트랜스포머 : 어텐션으로 문맥을 반영해 벡터를 다듬는다 (이걸 수십 번 반복)\n"
            "  5) 출력층     : 다음 토큰의 확률 분포를 만든다 (softmax)\n"
            "  6) 샘플링     : 확률에 따라 하나를 고른다\n"
            "\n"
            "[핵심 부품 — 셀프 어텐션]\n"
            "  '그 사과는 맛있었다. 그것은 빨갛다.'\n"
            "  '그것'이 무엇을 가리키는지 알아야 문장을 이해할 수 있다.\n"
            "  어텐션은 각 단어가 문장 속 다른 단어들을 얼마나 참고할지 계산한다.\n"
            "  '그것'이 '사과'에 높은 가중치를 주는 식이다.\n"
            "\n"
            "  2017년 논문 'Attention Is All You Need' 가 이 구조를 제안했고,\n"
            "  GPT·BERT·Claude 등 현재의 거의 모든 언어 모델이 여기서 출발한다.\n"
            "\n"
            "[모델 크기와 학습]\n"
            "  · 사전학습(pre-training) : 인터넷 규모의 텍스트로 다음 토큰 맞히기를 반복\n"
            "  · 미세조정(fine-tuning)  : 특정 용도에 맞게 추가 학습\n"
            "  · RLHF                   : 사람의 선호를 반영해 답변 품질을 다듬는 단계\n"
            "\n"
            "[이 단계 커리큘럼]\n"
            "  ds5-02  토크나이저 — 문장을 숫자로 바꾸기\n"
            "  ds5-03  임베딩과 셀프 어텐션 — 트랜스포머의 심장\n"
            "  (이후 확장 예정)\n"
            "    · 멀티헤드 어텐션 · 위치 인코딩 · 레이어 정규화\n"
            "    · 미니 GPT 학습시키기\n"
            "    · 프롬프트 엔지니어링 · RAG · 파인튜닝 실전\n"
            "\n"
            "[유의 사항]\n"
            "  • LLM 은 '사실'을 저장한 데이터베이스가 아니라 '그럴듯한 다음 토큰'을\n"
            "    계산하는 확률 모델이다. 그래서 자신 있게 틀린 말을 한다(환각).\n"
            "  • 실제 GPT 급 모델 학습에는 수천억 원 규모의 연산이 든다.\n"
            "    여기서는 원리를 이해하는 데 집중한다."
        ),
        usage="5단계 학습의 지도. LLM 을 쓰는 입장에서도 이 구조를 알면 한계와 강점이 보인다.",
        cons="개념 정리 위주다. 실제 부품 구현은 다음 레슨부터다.",
        code=(
            "import numpy as np\n"
            "\n"
            "# LLM 이 하는 일의 축소판: 다음 토큰 확률 → 샘플링\n"
            "def softmax(z):\n"
            "    e = np.exp(z - z.max())\n"
            "    return e / e.sum()\n"
            "\n"
            "vocab = ['좋다', '춥다', '덥다', '흐리다', '이상하다']\n"
            "logits = np.array([3.2, 2.1, 1.9, 0.8, 0.3])   # 모델이 계산한 점수\n"
            "\n"
            "probs = softmax(logits)\n"
            "print(\"입력: '오늘 날씨가 정말'\")\n"
            "print('\\n다음 토큰 확률:')\n"
            "for w, p in zip(vocab, probs):\n"
            "    bar = '#' * int(p * 50)\n"
            "    print(f'  {w:8s} {p:.4f}  {bar}')\n"
            "\n"
            "# temperature — 창의성 조절 손잡이\n"
            "print('\\n-- temperature 에 따른 확률 변화 --')\n"
            "for t in [0.3, 1.0, 2.0]:\n"
            "    p = softmax(logits / t)\n"
            "    print(f'  T={t}: {p.round(3)}')\n"
            "print('  T 가 낮으면 1등에 몰려 안정적(보수적),')\n"
            "print('  T 가 높으면 고르게 퍼져 다양한 답이 나온다(창의적).')\n"
            "\n"
            "# 확률에 따라 실제로 뽑아 보기\n"
            "rng = np.random.default_rng(42)\n"
            "picks = rng.choice(vocab, size=10, p=probs)\n"
            "print('\\n10번 샘플링:', list(picks))\n"
        ),
    ),

    Lesson(
        id="ds5-02-tokenizer",
        lang="datasci", level=STAGE,
        title="토크나이저 — 문장을 숫자로",
        summary="글자 단위 · 단어 단위 · 서브워드(BPE)",
        explanation=(
            "[개요]\n"
            "컴퓨터는 글자를 모른다. 숫자만 안다.\n"
            "그래서 문장을 잘게 쪼개(토큰) 각각에 번호를 붙여야 한다. 이 과정이 토큰화다.\n"
            "\n"
            "[쪼개는 세 가지 방식]\n"
            "\n"
            "  1) 글자 단위 (character)\n"
            "     '안녕하세요' → ['안','녕','하','세','요']\n"
            "     · 장점: 사전이 아주 작다(수백 개). 모르는 단어가 없다.\n"
            "     · 단점: 토큰 수가 많아져 문맥을 길게 못 본다.\n"
            "\n"
            "  2) 단어 단위 (word)\n"
            "     '나는 밥을 먹었다' → ['나는','밥을','먹었다']\n"
            "     · 장점: 의미 단위라 직관적이다.\n"
            "     · 단점: 사전이 수십만 개로 폭증한다.\n"
            "       사전에 없는 단어(OOV, Out-Of-Vocabulary)를 처리할 수 없다.\n"
            "       한국어는 조사 때문에 '밥을/밥이/밥은'이 전부 다른 단어가 된다.\n"
            "\n"
            "  3) 서브워드 (subword, BPE) ← 현재 표준\n"
            "     '먹었다' → ['먹','었다']\n"
            "     · 자주 붙어 나오는 조각을 하나로 합쳐가며 사전을 만든다.\n"
            "     · 장점: 사전 크기가 적당하고(3~10만) 모르는 단어도 조각으로 표현 가능.\n"
            "     · GPT, Claude 등 거의 모든 LLM 이 이 방식을 쓴다.\n"
            "\n"
            "[BPE 의 원리 — Byte Pair Encoding]\n"
            "  1) 처음엔 모두 글자 단위로 쪼갠다\n"
            "  2) 가장 자주 인접해 나오는 쌍을 찾는다\n"
            "  3) 그 쌍을 하나의 토큰으로 합친다\n"
            "  4) 원하는 사전 크기가 될 때까지 2~3 반복\n"
            "\n"
            "  'low low lower' 에서 'l'+'o' 가 자주 나오면 'lo' 를 새 토큰으로 만드는 식이다.\n"
            "\n"
            "[특수 토큰]\n"
            "  <pad> 길이 맞추기용 빈칸    <unk> 모르는 토큰\n"
            "  <bos> 문장 시작            <eos> 문장 끝\n"
            "  모델은 <eos> 를 만나면 생성을 멈춘다.\n"
            "\n"
            "[코드 분석]\n"
            "  sorted(set(text))\n"
            "         → 중복 없는 글자 목록을 정렬. 이게 사전(vocabulary)이 된다.\n"
            "            정렬하는 이유는 실행할 때마다 번호가 바뀌지 않게 하기 위해서다.\n"
            "  {ch: i for i, ch in enumerate(chars)}\n"
            "         → 글자 → 번호 매핑. 딕셔너리 컴프리헨션이다.\n"
            "  encode / decode\n"
            "         → 문장을 번호 리스트로, 번호 리스트를 다시 문장으로.\n"
            "            decode(encode(s)) == s 가 성립해야 올바른 토크나이저다.\n"
            "  Counter(zip(tokens, tokens[1:]))\n"
            "         → 인접한 쌍의 빈도를 센다. zip 으로 한 칸 밀어 짝짓는 기법이다.\n"
            "            BPE 병합 후보를 찾는 핵심 코드다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 한국어는 영어보다 토큰이 훨씬 많이 나온다. 같은 내용이라도 비용이 더 든다.\n"
            "  • 토크나이저가 다르면 같은 문장도 다른 번호가 된다.\n"
            "    모델과 토크나이저는 반드시 짝을 맞춰 써야 한다.\n"
            "  • LLM 의 '컨텍스트 길이'는 글자 수가 아니라 토큰 수 기준이다."
        ),
        usage="LLM 입력의 첫 관문. 토큰 수를 알면 API 비용과 컨텍스트 한계를 계산할 수 있다.",
        cons="글자 단위 토크나이저는 이해하기 쉽지만 실용성이 낮다. 실무에서는 BPE 계열을 쓴다.",
        code=(
            "from collections import Counter\n"
            "\n"
            "text = '나는 밥을 먹었다 나는 빵을 먹었다'\n"
            "\n"
            "# ---- 1) 글자 단위 토크나이저 ----\n"
            "chars = sorted(set(text))\n"
            "stoi = {ch: i for i, ch in enumerate(chars)}\n"
            "itos = {i: ch for ch, i in stoi.items()}\n"
            "\n"
            "def encode(s):\n"
            "    return [stoi[c] for c in s]\n"
            "\n"
            "def decode(ids):\n"
            "    return ''.join(itos[i] for i in ids)\n"
            "\n"
            "print('사전 크기:', len(chars))\n"
            "print('사전     :', chars)\n"
            "\n"
            "ids = encode('나는 밥을')\n"
            "print('\\n인코딩: 나는 밥을 →', ids)\n"
            "print('디코딩:', ids, '→', decode(ids))\n"
            "print('왕복 검증:', decode(encode(text)) == text)\n"
            "\n"
            "# ---- 2) 단어 단위 ----\n"
            "words = text.split()\n"
            "wvocab = sorted(set(words))\n"
            "print('\\n단어 사전:', wvocab, f'({len(wvocab)}개)')\n"
            "print('토큰 수 비교 → 글자:', len(encode(text)), '/ 단어:', len(words))\n"
            "\n"
            "# ---- 3) BPE 첫 단계: 가장 자주 붙어 나오는 쌍 찾기 ----\n"
            "tokens = list(text.replace(' ', '_'))\n"
            "pairs = Counter(zip(tokens, tokens[1:]))\n"
            "print('\\n-- 인접 쌍 빈도 상위 5 --')\n"
            "for (a, b), c in pairs.most_common(5):\n"
            "    print(f'  {a!r}+{b!r} : {c}회')\n"
            "\n"
            "best = pairs.most_common(1)[0][0]\n"
            "print(f'\\n→ {best[0]!r}+{best[1]!r} 를 하나의 토큰 {\"\".join(best)!r} 로 병합한다')\n"
            "print('  이 과정을 수만 번 반복한 것이 GPT 의 토크나이저다.')\n"
        ),
    ),

    Lesson(
        id="ds5-03-attention",
        lang="datasci", level=STAGE,
        title="임베딩과 셀프 어텐션",
        summary="Q·K·V — 트랜스포머의 심장을 numpy 로",
        explanation=(
            "[개요]\n"
            "토큰 번호는 그냥 번호일 뿐 의미가 없다. 3번과 4번이 비슷하다는 뜻이 아니다.\n"
            "그래서 각 토큰을 '의미를 담은 벡터'로 바꾼다. 이것이 임베딩이다.\n"
            "\n"
            "  '왕' → [0.8, 0.2, -0.5, ...]\n"
            "  '여왕' → [0.7, 0.3, -0.4, ...]   ← '왕'과 가까운 위치\n"
            "\n"
            "비슷한 의미의 단어는 벡터 공간에서 가까이 놓인다.\n"
            "임베딩 값은 사람이 정하는 게 아니라 학습으로 얻는다.\n"
            "\n"
            "[셀프 어텐션 — Q, K, V]\n"
            "도서관에서 자료를 찾는 과정에 비유하면 이해하기 쉽다.\n"
            "\n"
            "  Query (질문)  : 내가 찾는 것            '그것'이 뭘 가리키지?\n"
            "  Key   (색인)  : 각 자료의 검색용 표지    각 단어의 '나는 이런 단어다'\n"
            "  Value (내용)  : 실제 가져올 내용        각 단어가 전달할 정보\n"
            "\n"
            "  계산 순서:\n"
            "    1) score = Q @ K.T          질문과 색인을 대조 → 관련도 점수\n"
            "    2) score / √d               차원 수의 제곱근으로 나눈다 (스케일링)\n"
            "    3) weight = softmax(score)  점수를 합이 1인 가중치로\n"
            "    4) output = weight @ V      가중치대로 내용을 섞는다\n"
            "\n"
            "  이 네 줄이 트랜스포머의 핵심이다. 'Attention Is All You Need' 의 그 수식이다.\n"
            "\n"
            "[왜 √d 로 나누는가]\n"
            "  차원이 크면 내적 값이 커진다. 값이 크면 softmax 가 극단적으로 쏠려\n"
            "  한 곳만 1 이 되고 나머지가 0 이 된다. 그러면 기울기가 거의 0 이라 학습이 안 된다.\n"
            "  √d 로 나눠 적당한 크기로 유지하는 것이다. 그래서 'scaled' dot-product attention 이다.\n"
            "\n"
            "[코드 분석]\n"
            "  embedding = rng.normal(0, 1, (vocab_size, d_model))\n"
            "         → 임베딩 테이블. 실제로는 학습으로 얻지만 여기선 난수로 대신한다.\n"
            "            행 하나가 토큰 하나의 의미 벡터다.\n"
            "  X = embedding[token_ids]\n"
            "         → 팬시 인덱싱으로 여러 토큰의 벡터를 한 번에 꺼낸다.\n"
            "            (토큰 수, d_model) 모양이 된다.\n"
            "  Q, K, V = X @ Wq, X @ Wk, X @ Wv\n"
            "         → 같은 입력에서 세 가지 역할의 벡터를 만든다.\n"
            "            '셀프' 어텐션인 이유가 이것이다. Q·K·V 가 모두 자기 자신에서 나온다.\n"
            "  scores = Q @ K.T / np.sqrt(d_k)\n"
            "         → 모든 단어 쌍의 관련도. (n, n) 정사각 행렬이 된다.\n"
            "  mask 적용\n"
            "         → GPT 같은 생성 모델은 뒤쪽 단어를 미리 보면 안 된다(컨닝 방지).\n"
            "            위쪽 삼각형에 -무한대를 채우면 softmax 후 0 이 되어 차단된다.\n"
            "            이를 causal mask 라 한다.\n"
            "  weights @ V\n"
            "         → 가중 평균. 각 단어가 문맥을 반영한 새 벡터를 갖게 된다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 실제 트랜스포머는 이 어텐션을 여러 개 병렬로 돌린다(멀티헤드).\n"
            "    각 헤드가 문법·의미 등 서로 다른 관계에 집중한다.\n"
            "  • 어텐션은 토큰 수의 제곱에 비례해 계산량이 는다.\n"
            "    긴 컨텍스트가 비싼 근본 이유가 이것이다.\n"
            "  • 여기 코드는 학습되지 않은 난수 가중치라 결과에 의미는 없다.\n"
            "    '계산이 이렇게 흘러간다'는 구조만 보면 된다."
        ),
        usage="트랜스포머 구조 이해의 핵심. 이걸 알면 LLM 논문과 코드를 읽을 수 있다.",
        cons="난수 가중치를 쓴 시연이라 실제 의미는 나오지 않는다. 진짜 성능은 대규모 학습에서 나온다.",
        code=(
            "import numpy as np\n"
            "\n"
            "rng = np.random.default_rng(42)\n"
            "\n"
            "def softmax(z, axis=-1):\n"
            "    e = np.exp(z - z.max(axis=axis, keepdims=True))\n"
            "    return e / e.sum(axis=axis, keepdims=True)\n"
            "\n"
            "# ---- 임베딩 ----\n"
            "words = ['그', '사과', '는', '빨갛다']\n"
            "vocab_size, d_model = len(words), 8\n"
            "embedding = rng.normal(0, 1, (vocab_size, d_model))\n"
            "\n"
            "token_ids = np.array([0, 1, 2, 3])\n"
            "X = embedding[token_ids]\n"
            "print('토큰      :', words)\n"
            "print('임베딩 모양:', X.shape, '(토큰 수, 차원)')\n"
            "\n"
            "# ---- Q, K, V 만들기 ----\n"
            "d_k = 4\n"
            "Wq = rng.normal(0, 0.5, (d_model, d_k))\n"
            "Wk = rng.normal(0, 0.5, (d_model, d_k))\n"
            "Wv = rng.normal(0, 0.5, (d_model, d_k))\n"
            "\n"
            "Q, K, V = X @ Wq, X @ Wk, X @ Wv\n"
            "print('Q/K/V 모양:', Q.shape)\n"
            "\n"
            "# ---- 어텐션 ----\n"
            "scores = Q @ K.T / np.sqrt(d_k)\n"
            "print('\\n-- 관련도 점수 (스케일링 후) --')\n"
            "print(scores.round(3))\n"
            "\n"
            "weights = softmax(scores)\n"
            "print('\\n-- 어텐션 가중치 (행 합 = 1) --')\n"
            "print('        ' + '  '.join(f'{w:>6s}' for w in words))\n"
            "for w, row in zip(words, weights):\n"
            "    print(f'{w:>6s}  ' + '  '.join(f'{v:6.3f}' for v in row))\n"
            "print('행 합계:', weights.sum(axis=1).round(6))\n"
            "\n"
            "output = weights @ V\n"
            "print('\\n출력 모양:', output.shape, '→ 문맥이 반영된 새 벡터')\n"
            "\n"
            "# ---- causal mask (GPT 방식: 뒤를 못 보게) ----\n"
            "n = len(words)\n"
            "mask = np.triu(np.ones((n, n)), k=1) * -1e9\n"
            "masked = softmax(scores + mask)\n"
            "print('\\n-- causal mask 적용 (뒤쪽 단어 차단) --')\n"
            "print('        ' + '  '.join(f'{w:>6s}' for w in words))\n"
            "for w, row in zip(words, masked):\n"
            "    print(f'{w:>6s}  ' + '  '.join(f'{v:6.3f}' for v in row))\n"
            "print('→ 각 단어는 자기 앞쪽만 참고한다. GPT 가 다음 단어를 예측하는 방식이다.')\n"
        ),
    ),
]
