"""3단계 — 머신러닝 본편 (ds3-04 ~ ds3-12).

ds3-01~03 에서 잡은 원리(손실·경사하강·평가지표) 위에
회귀·분류·정규화·검증·트리·군집·차원축소를 numpy 로 직접 구현한다.
"""

from engine.models import Lesson

STAGE = "3. 머신러닝"

LESSONS = [

    Lesson(
        id="ds3-04-multireg",
        lang="datasci", level=STAGE,
        title="다중 선형회귀 · 정규방정식",
        summary="특성이 여러 개일 때 · 한 번에 정답을 구하는 공식",
        explanation=(
            "[개요]\n"
            "ds3-02 의 선형회귀는 특성이 1개(공부 시간)였다.\n"
            "현실은 특성이 여러 개다. 집값이라면 평수·방 개수·역까지 거리를 함께 본다.\n"
            "\n"
            "  ŷ = w₁x₁ + w₂x₂ + w₃x₃ + b\n"
            "\n"
            "특성이 늘어도 원리는 같다. 다만 행렬로 쓰면 훨씬 깔끔해진다.\n"
            "\n"
            "[행렬로 쓰기]\n"
            "  절편 b 를 따로 두지 않고, 값이 전부 1 인 열을 X 앞에 붙이면\n"
            "  b 도 가중치 중 하나로 흡수된다. 이 열을 편향 항(bias term)이라 한다.\n"
            "\n"
            "    Xb = [1, x₁, x₂, x₃]      θ = [b, w₁, w₂, w₃]\n"
            "    ŷ = Xb @ θ\n"
            "\n"
            "  식 하나로 전체 데이터의 예측이 끝난다.\n"
            "\n"
            "[정규방정식 — 경사하강 없이 한 번에]\n"
            "선형회귀는 MSE 를 최소로 만드는 θ 를 **공식으로 바로 구할 수 있다.**\n"
            "\n"
            "    θ = (Xᵀ X)⁻¹ Xᵀ y\n"
            "\n"
            "  경사하강법처럼 조금씩 내려갈 필요가 없다. 반복이 0회다.\n"
            "  선형회귀가 특별한 이유이며, 신경망에는 이런 공식이 없다.\n"
            "\n"
            "[언제 무엇을 쓰나]\n"
            "  정규방정식 : 특성 수가 적을 때(수천 개 이하). 정확하고 조정할 값이 없다.\n"
            "               단 (XᵀX)⁻¹ 계산이 특성 수의 세제곱에 비례해 느려진다.\n"
            "  경사하강법 : 특성이 매우 많거나 데이터가 메모리에 안 들어갈 때.\n"
            "               딥러닝은 공식이 없으므로 무조건 이쪽이다.\n"
            "\n"
            "[코드 분석]\n"
            "  np.column_stack([area, rooms, dist])\n"
            "         → 1차원 배열 여러 개를 열로 세워 (n, 3) 행렬을 만든다.\n"
            "  np.column_stack([np.ones(n), X])\n"
            "         → 맨 앞에 1 로 채운 편향 열을 붙인다. (n, 4) 가 된다.\n"
            "  np.linalg.solve(A, b)\n"
            "         → A⁻¹b 를 구한다. inv() 로 역행렬을 만든 뒤 곱하는 것보다\n"
            "            수치적으로 안정적이고 빠르다. 역행렬은 되도록 직접 만들지 않는다.\n"
            "  np.linalg.lstsq(Xb, y, rcond=None)\n"
            "         → 최소제곱해를 바로 구한다. XᵀX 가 역행렬이 없는 경우\n"
            "            (특성끼리 완전히 겹칠 때)에도 답을 내주는 가장 안전한 방법이다.\n"
            "  경사하강법 비교\n"
            "         → 표준화한 특성으로 800회 반복해 거의 같은 답에 도달하는지 확인한다.\n"
            "            표준화하지 않으면 특성마다 크기가 달라(평수 40 vs 거리 3)\n"
            "            학습이 지그재그로 흔들리며 잘 수렴하지 않는다.\n"
            "\n"
            "[다중공선성 — 특성끼리 겹칠 때]\n"
            "  '평수'와 '평방미터'를 둘 다 넣으면 두 열이 사실상 같은 정보다.\n"
            "  이때 XᵀX 의 역행렬이 불안정해져 가중치가 터무니없이 커지거나\n"
            "  부호가 뒤집힌다. 계수 해석이 무의미해진다.\n"
            "  → 상관계수가 아주 높은 특성은 하나만 남기거나, 다음 레슨의 정규화를 쓴다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 정규방정식은 특성이 수만 개면 매우 느려진다. 그땐 경사하강법이다.\n"
            "  • 계수의 크기를 '중요도'로 읽으면 안 된다. 단위가 다르면 크기도 달라진다.\n"
            "    중요도를 비교하려면 표준화한 뒤의 계수를 봐야 한다."
        ),
        usage="수치 예측의 기본기. 특성 여러 개로 값을 맞히는 거의 모든 문제의 출발점.",
        cons="직선(평면) 관계만 표현한다. 곡선 관계는 특성을 제곱해 추가하거나 다른 모델이 필요하다.",
        code=(
            "import numpy as np\n"
            "\n"
            "rng = np.random.default_rng(42)\n"
            "n = 200\n"
            "\n"
            "# 특성 3개: 평수 / 방 개수 / 역까지 거리(km)\n"
            "area = rng.uniform(10, 40, n)\n"
            "rooms = rng.integers(1, 5, n).astype(float)\n"
            "dist = rng.uniform(0.1, 3.0, n)\n"
            "\n"
            "# 실제 관계: 가격 = 1.5*평수 + 3*방 - 5*거리 + 10 + 잡음\n"
            "y = 1.5 * area + 3.0 * rooms - 5.0 * dist + 10.0 + rng.normal(0, 2, n)\n"
            "\n"
            "X = np.column_stack([area, rooms, dist])\n"
            "Xb = np.column_stack([np.ones(n), X])      # 편향 열 추가\n"
            "print('X 모양 :', X.shape, '→ 편향 추가 후:', Xb.shape)\n"
            "\n"
            "# ---- 1) 정규방정식 (반복 0회) ----\n"
            "theta = np.linalg.solve(Xb.T @ Xb, Xb.T @ y)\n"
            "print('\\n-- 정규방정식 --')\n"
            "for name, v, real in zip(['절편', '평수', '방개수', '거리'],\n"
            "                         theta, [10.0, 1.5, 3.0, -5.0]):\n"
            "    print(f'  {name:6s} 추정 {v:7.3f}   실제 {real:6.2f}')\n"
            "\n"
            "# lstsq — 더 안전한 방법\n"
            "theta2, *_ = np.linalg.lstsq(Xb, y, rcond=None)\n"
            "print('  lstsq 와 같은가?', bool(np.allclose(theta, theta2)))\n"
            "\n"
            "# ---- 2) 경사하강법 (표준화 필수) ----\n"
            "mu, sd = X.mean(axis=0), X.std(axis=0)\n"
            "Xs = (X - mu) / sd\n"
            "w = np.zeros(3)\n"
            "b = 0.0\n"
            "lr = 0.1\n"
            "for epoch in range(800):\n"
            "    err = y - (Xs @ w + b)\n"
            "    w += lr * 2 * (Xs.T @ err) / n\n"
            "    b += lr * 2 * err.mean()\n"
            "\n"
            "# 표준화된 가중치를 원래 단위로 되돌리기\n"
            "w_real = w / sd\n"
            "b_real = b - (w * mu / sd).sum()\n"
            "print('\\n-- 경사하강법 --')\n"
            "for name, v in zip(['절편', '평수', '방개수', '거리'],\n"
            "                   [b_real, *w_real]):\n"
            "    print(f'  {name:6s} 추정 {v:7.3f}')\n"
            "\n"
            "print('\\n두 방법의 차이(최대):',\n"
            "      round(float(np.abs(theta - np.array([b_real, *w_real])).max()), 6))\n"
            "print('→ 같은 답에 도달한다. 가는 길이 다를 뿐이다.')\n"
        ),
    ),

    Lesson(
        id="ds3-05-logistic",
        lang="datasci", level=STAGE,
        title="로지스틱 회귀",
        summary="분류를 '확률'로 푸는 표준 모델",
        explanation=(
            "[개요]\n"
            "합격/불합격 같은 이진 분류에 선형회귀를 그대로 쓰면 안 된다.\n"
            "직선은 1.7 이나 -0.3 같은 값을 뱉는데, 확률은 0~1 이어야 하기 때문이다.\n"
            "\n"
            "그래서 직선의 출력을 sigmoid 로 눌러 0~1 로 만든다.\n"
            "\n"
            "    z = w·x + b            ← 직선 (범위 -∞ ~ ∞)\n"
            "    p = 1 / (1 + e^-z)     ← sigmoid (범위 0 ~ 1)\n"
            "\n"
            "이름이 '회귀'지만 하는 일은 분류다. 역사적 명칭일 뿐이다.\n"
            "\n"
            "[손실 함수 — 왜 MSE 가 아닌가]\n"
            "분류에는 이진 교차엔트로피(BCE)를 쓴다.\n"
            "\n"
            "    L = -[ y·log(p) + (1-y)·log(1-p) ]\n"
            "\n"
            "  · 정답이 1 인데 p=0.99 → -log(0.99) ≈ 0.01   벌점 거의 없음\n"
            "  · 정답이 1 인데 p=0.01 → -log(0.01) ≈ 4.6    벌점 아주 큼\n"
            "\n"
            "  '자신 있게 틀린 것'에 훨씬 큰 벌점을 준다.\n"
            "  MSE 를 쓰면 sigmoid 와 만나 손실 지형이 울퉁불퉁해져(비볼록)\n"
            "  학습이 잘 안 된다. BCE 는 볼록해서 안정적으로 수렴한다.\n"
            "\n"
            "[기울기가 놀랍도록 단순하다]\n"
            "  sigmoid + BCE 를 함께 쓰면 미분이 정리되어\n"
            "\n"
            "    ∂L/∂w = Xᵀ(p - y) / n\n"
            "\n"
            "  선형회귀의 기울기와 형태가 똑같다. 이 조합을 쓰는 실용적 이유다.\n"
            "  (ds4-03 의 dz2 = a2 - y 도 같은 이유로 단순했다)\n"
            "\n"
            "[결정 경계]\n"
            "  p = 0.5 가 되는 지점이 경계다. p=0.5 는 z=0 을 뜻하므로\n"
            "  경계는 w·x + b = 0 이라는 **직선**이다.\n"
            "  로지스틱 회귀는 결국 직선(평면)으로 나누는 모델이라는 뜻이다.\n"
            "  XOR 처럼 직선으로 안 나뉘는 문제는 못 푼다 → 신경망이 필요하다.\n"
            "\n"
            "[코드 분석]\n"
            "  p_true = 1 / (1 + np.exp(-z_true))\n"
            "  y = (rng.random(n) < p_true).astype(float)\n"
            "         → 확률에 따라 0/1 을 뽑아 현실적인 데이터를 만든다.\n"
            "            경계 근처는 섞이므로 정확도가 100% 가 나오지 않는 게 정상이다.\n"
            "  np.clip(p, 1e-9, 1 - 1e-9)\n"
            "         → log(0) = -무한대 를 막는다. 빠뜨리면 손실이 nan 이 된다.\n"
            "  Xs.T @ (p - y) / n\n"
            "         → 기울기. 반복문 없이 전체 데이터로 한 번에 계산한다.\n"
            "  (p >= 0.5).astype(int)\n"
            "         → 확률을 0/1 판정으로 바꾼다. 임계값 0.5 는 기본값일 뿐\n"
            "            상황에 따라 조정한다(암 진단이면 0.3 으로 낮춰 재현율을 올린다).\n"
            "\n"
            "[유의 사항]\n"
            "  • 특성 표준화를 하지 않으면 수렴이 매우 느리다.\n"
            "  • 두 클래스가 완전히 분리되면 가중치가 무한대로 발산한다(완전분리 문제).\n"
            "    이때는 정규화(다음 레슨)를 걸어야 한다.\n"
            "  • 출력 p 는 '모델이 계산한 점수'이지 실제 확률과 정확히 같지는 않다.\n"
            "    확률로 쓰려면 보정(calibration)이 따로 필요하다."
        ),
        usage="이진 분류의 기본 모델. 해석이 쉬워 금융·의료처럼 근거를 설명해야 하는 곳에서 여전히 1순위.",
        cons="직선으로 나뉘는 문제만 풀 수 있다. 특성 간 상호작용은 직접 만들어 넣어야 한다.",
        code=(
            "import numpy as np\n"
            "\n"
            "rng = np.random.default_rng(0)\n"
            "n = 300\n"
            "\n"
            "study = rng.uniform(0, 10, n)      # 공부 시간\n"
            "attend = rng.uniform(40, 100, n)   # 출석률\n"
            "\n"
            "z_true = 0.8 * study + 0.06 * attend - 8\n"
            "p_true = 1 / (1 + np.exp(-z_true))\n"
            "y = (rng.random(n) < p_true).astype(float)     # 합격 여부\n"
            "\n"
            "X = np.column_stack([study, attend])\n"
            "mu, sd = X.mean(axis=0), X.std(axis=0)\n"
            "Xs = (X - mu) / sd\n"
            "\n"
            "w = np.zeros(2)\n"
            "b = 0.0\n"
            "lr = 0.5\n"
            "\n"
            "print('epoch      손실     정확도')\n"
            "marks = [0, 5, 10, 25, 50, 100, 200, 400, 1000, 2000]\n"
            "for epoch in range(2001):\n"
            "    z = Xs @ w + b\n"
            "    p = 1 / (1 + np.exp(-z))\n"
            "    pc = np.clip(p, 1e-9, 1 - 1e-9)\n"
            "    loss = -(y * np.log(pc) + (1 - y) * np.log(1 - pc)).mean()\n"
            "\n"
            "    if epoch in marks:\n"
            "        acc = ((p >= 0.5).astype(float) == y).mean()\n"
            "        print(f'{epoch:5d}  {loss:8.4f}  {acc:8.3f}')\n"
            "\n"
            "    w -= lr * (Xs.T @ (p - y)) / n\n"
            "    b -= lr * (p - y).mean()\n"
            "\n"
            "print('\\n→ 초반 100 에폭 안에 대부분 수렴한다.')\n"
            "print('  로지스틱 회귀는 손실이 볼록(convex)해서 지역 최솟값이 없다.')\n"
            "print('  어디서 시작하든 같은 답에 도달한다 — 신경망과 다른 점이다.')\n"
            "\n"
            "# 원래 단위로 되돌린 계수\n"
            "w_real = w / sd\n"
            "b_real = b - (w * mu / sd).sum()\n"
            "print('\\n학습된 계수 : 공부 %.3f · 출석 %.3f · 절편 %.3f'\n"
            "      % (w_real[0], w_real[1], b_real))\n"
            "print('실제 계수   : 공부 0.800 · 출석 0.060 · 절편 -8.000')\n"
            "\n"
            "# 몇 명 예측해 보기\n"
            "print('\\n-- 예측 --')\n"
            "for s, a in [(2, 50), (5, 70), (8, 90)]:\n"
            "    zz = w_real[0] * s + w_real[1] * a + b_real\n"
            "    pp = 1 / (1 + np.exp(-zz))\n"
            "    print(f'  공부 {s}h · 출석 {a}%  →  합격 확률 {pp:.3f}'\n"
            "          f'  ({\"합격\" if pp >= 0.5 else \"불합격\"})')\n"
        ),
    ),

    Lesson(
        id="ds3-06-overfit",
        lang="datasci", level=STAGE,
        title="과적합과 정규화",
        summary="문제집을 외운 모델 · 가중치에 벌점 주기(Ridge)",
        explanation=(
            "[개요]\n"
            "모델을 복잡하게 만들면 훈련 데이터는 완벽하게 맞힌다.\n"
            "그런데 새 데이터에서는 오히려 더 틀린다. 이것이 과적합이다.\n"
            "\n"
            "[다항 회귀로 직접 보기]\n"
            "직선 대신 곡선을 쓰려면 특성에 제곱·세제곱을 추가하면 된다.\n"
            "\n"
            "    차수 1 : ŷ = w₁x + b                   너무 단순 → 과소적합\n"
            "    차수 3 : ŷ = w₃x³ + w₂x² + w₁x + b     적당\n"
            "    차수 9 : ŷ = w₉x⁹ + ... + b            너무 복잡 → 과적합\n"
            "\n"
            "차수 9 는 훈련 점을 거의 정확히 통과하지만, 점 사이에서 미친 듯이 출렁인다.\n"
            "검증 오차를 보면 이게 바로 드러난다.\n"
            "\n"
            "[검증 오차는 U자를 그린다 — 아래 실행 결과를 꼭 보자]\n"
            "  '복잡할수록 나빠진다'가 아니다. 처음에는 복잡해질수록 **좋아진다.**\n"
            "\n"
            "    차수 1 → 3 → 5 : 검증 오차가 **줄어든다**  (과소적합에서 벗어나는 중)\n"
            "    차수 5         : 가장 좋은 지점 (이 데이터의 적정 복잡도)\n"
            "    차수 9         : 검증 오차가 **폭증한다**  (과적합 시작)\n"
            "\n"
            "  훈련 오차는 계속 줄지만 검증 오차는 U자를 그린다.\n"
            "  그 바닥을 찾는 것이 모델 선택의 전부다.\n"
            "  실제 관계가 3차식인데 차수 5가 최적으로 나오는 것도 정상이다 —\n"
            "  데이터가 30개뿐이고 잡음이 있어서, 진짜 차수를 정확히 맞히지는 못한다.\n"
            "\n"
            "[과적합의 신호]\n"
            "  훈련 오차 ↓↓  ·  검증 오차 ↑    ← 전형적인 과적합\n"
            "  훈련 오차 높음 · 검증 오차 높음  ← 과소적합(모델이 너무 단순)\n"
            "  두 오차가 비슷하게 낮음          ← 좋은 상태\n"
            "\n"
            "[정규화(Regularization) — 가중치에 벌점]\n"
            "과적합한 모델은 가중치가 비정상적으로 크다. 작은 입력 변화에\n"
            "출력이 크게 흔들리기 때문이다. 그래서 손실에 '가중치 크기' 벌점을 더한다.\n"
            "\n"
            "    Ridge(L2) : L = MSE + λ·Σw²    가중치를 전체적으로 작게 누른다\n"
            "    Lasso(L1) : L = MSE + λ·Σ|w|   일부 가중치를 아예 0 으로 만든다(특성 선택)\n"
            "\n"
            "  λ(람다)가 벌점의 세기다.\n"
            "    λ = 0     → 정규화 없음. 과적합 그대로\n"
            "    λ 가 크면 → 가중치가 0 에 가까워져 과소적합\n"
            "  적당한 λ 는 교차검증(다음 레슨)으로 찾는다.\n"
            "\n"
            "[Ridge 의 닫힌 해]\n"
            "    w = (XᵀX + λI)⁻¹ Xᵀy\n"
            "  정규방정식에 λI 를 더한 것뿐이다.\n"
            "  이 λI 덕분에 역행렬이 항상 존재해 다중공선성 문제까지 완화된다.\n"
            "  **단 절편(편향 항)에는 벌점을 주지 않는다.** I 의 첫 원소를 0 으로 둔다.\n"
            "\n"
            "[코드 분석]\n"
            "  xs = x / 3.0\n"
            "         → 다항 특성을 만들기 전에 x 범위를 줄인다.\n"
            "            x 가 3 이면 x⁹ = 19683 이라 열마다 크기가 수만 배 차이 나서\n"
            "            행렬 계산이 불안정해진다. 스케일 조정은 다항 회귀의 필수 준비다.\n"
            "  np.vander(xs, deg + 1, increasing=True)\n"
            "         → [1, x, x², ..., x^deg] 열을 한 번에 만든다.\n"
            "            첫 열이 1 이므로 편향 항이 자동으로 포함된다.\n"
            "  reg = np.eye(d); reg[0, 0] = 0\n"
            "         → 단위행렬을 만들되 첫 원소만 0. 절편은 벌점에서 제외한다는 뜻이다.\n"
            "  np.linalg.solve(A.T @ A + lam * reg, A.T @ y)\n"
            "         → Ridge 의 닫힌 해.\n"
            "  rmse\n"
            "         → 오차를 원래 단위로 읽으려고 MSE 에 제곱근을 씌운 값이다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 검증 오차로 모델을 고르고 또 그 검증 오차를 성능으로 보고하면 안 된다.\n"
            "    고르는 데 쓴 순간 그 데이터도 학습에 관여한 것이다.\n"
            "  • 정규화를 걸기 전에 특성 표준화를 먼저 해야 한다.\n"
            "    크기가 큰 특성이 벌점을 독차지하기 때문이다.\n"
            "  • 데이터를 더 모으는 것이 정규화보다 근본적인 해결책이다."
        ),
        usage="모델이 훈련에선 좋은데 실제로 못 쓸 때. 실무 머신러닝의 절반이 이 싸움이다.",
        cons="λ 를 잘못 잡으면 과소적합으로 넘어간다. 적정값은 교차검증으로 찾아야 해서 계산이 늘어난다.",
        code=(
            "import numpy as np\n"
            "\n"
            "rng = np.random.default_rng(3)\n"
            "\n"
            "# 실제 관계: y = 0.5x³ - 2x + 잡음\n"
            "n = 30\n"
            "x = np.sort(rng.uniform(-3, 3, n))\n"
            "y = 0.5 * x ** 3 - 2 * x + rng.normal(0, 2.0, n)\n"
            "\n"
            "idx = rng.permutation(n)\n"
            "tr, te = idx[:20], idx[20:]\n"
            "xs = x / 3.0                       # 다항 특성 스케일 조정\n"
            "\n"
            "def fit_poly(deg, lam=0.0):\n"
            "    A = np.vander(xs[tr], deg + 1, increasing=True)\n"
            "    d = deg + 1\n"
            "    reg = np.eye(d)\n"
            "    reg[0, 0] = 0.0                # 절편에는 벌점 없음\n"
            "    w = np.linalg.solve(A.T @ A + lam * reg, A.T @ y[tr])\n"
            "    def rmse(part):\n"
            "        P = np.vander(xs[part], deg + 1, increasing=True)\n"
            "        return float(np.sqrt(((y[part] - P @ w) ** 2).mean()))\n"
            "    return w, rmse(tr), rmse(te)\n"
            "\n"
            "print('-- 차수를 올려가며 (정규화 없음) --')\n"
            "print('차수   훈련RMSE   검증RMSE   최대|가중치|')\n"
            "for deg in [1, 3, 5, 9]:\n"
            "    w, r_tr, r_te = fit_poly(deg)\n"
            "    print(f'{deg:3d}   {r_tr:8.3f}   {r_te:8.3f}   {np.abs(w).max():10.1f}')\n"
            "\n"
            "print('\\n→ 훈련 오차는 계속 줄지만, 검증 오차는 U자를 그린다.')\n"
            "print('  차수 5 가 바닥이고 차수 9 에서 폭증한다 = 과적합.')\n"
            "print('  가중치 최댓값이 777 까지 뛰는 것이 과적합의 지문이다.')\n"
            "\n"
            "print('\\n-- 차수 9 에 Ridge 벌점 걸기 --')\n"
            "print('  λ       훈련RMSE   검증RMSE   최대|가중치|')\n"
            "for lam in [0.0, 0.001, 0.01, 0.1, 1.0, 10.0]:\n"
            "    w, r_tr, r_te = fit_poly(9, lam)\n"
            "    print(f'{lam:6.3f}   {r_tr:8.3f}   {r_te:8.3f}   {np.abs(w).max():10.1f}')\n"
            "\n"
            "print('\\n→ λ 를 키우면 가중치가 눌리고 검증 오차가 개선된다.')\n"
            "print('  너무 키우면 다시 나빠진다(과소적합). 적정값은 교차검증으로 찾는다.')\n"
        ),
    ),

    Lesson(
        id="ds3-07-cv",
        lang="datasci", level=STAGE,
        title="교차검증 · 하이퍼파라미터 탐색",
        summary="한 번 나눈 결과를 믿지 마라 · k-fold",
        explanation=(
            "[개요]\n"
            "훈련/검증을 한 번만 나누면, 결과가 '어떻게 쪼갰느냐'에 크게 흔들린다.\n"
            "운 좋게 쉬운 데이터가 검증에 몰리면 성능이 실제보다 좋아 보인다.\n"
            "\n"
            "교차검증(k-fold cross validation)은 이 운을 없앤다.\n"
            "\n"
            "[k-fold 동작]\n"
            "  데이터를 k 조각으로 나눈 뒤, 한 조각씩 돌아가며 검증에 쓴다.\n"
            "\n"
            "    1회차: [검증][훈련][훈련][훈련][훈련]\n"
            "    2회차: [훈련][검증][훈련][훈련][훈련]\n"
            "    ...\n"
            "    5회차: [훈련][훈련][훈련][훈련][검증]\n"
            "\n"
            "  모든 데이터가 정확히 한 번씩 검증에 쓰인다.\n"
            "  k 번의 점수를 평균내면 훨씬 믿을 만한 추정치가 된다.\n"
            "  **표준편차도 함께 본다.** 편차가 크면 그 모델은 불안정하다는 뜻이다.\n"
            "\n"
            "[k 는 몇으로]\n"
            "  k=5 또는 k=10 이 관례다.\n"
            "    k 가 크면 : 훈련 데이터가 많아져 추정이 정확하지만 계산이 k 배로 늘어난다.\n"
            "    k = n     : LOOCV(하나만 빼기). 데이터가 아주 적을 때만.\n"
            "\n"
            "[하이퍼파라미터 탐색]\n"
            "  · 파라미터        : 데이터로 학습되는 값 (w, b)\n"
            "  · 하이퍼파라미터  : 사람이 정해줘야 하는 값 (λ, 학습률, 트리 깊이, k)\n"
            "\n"
            "  후보를 나열하고 각각 교차검증해서 가장 좋은 것을 고른다.\n"
            "  이를 그리드 서치(grid search)라 한다.\n"
            "\n"
            "[중요 — 3분할이 정석이다]\n"
            "  훈련(train) / 검증(validation) / 시험(test)\n"
            "    · 훈련 : 가중치를 학습\n"
            "    · 검증 : 하이퍼파라미터를 고름 (교차검증은 여기서 일어난다)\n"
            "    · 시험 : 최종 성능 보고. **딱 한 번만 쓴다.**\n"
            "\n"
            "  검증 점수로 λ 를 고른 뒤 그 검증 점수를 최종 성능으로 보고하면\n"
            "  실제보다 부풀려진 숫자가 된다. 고르는 데 이미 써버렸기 때문이다.\n"
            "\n"
            "[코드 분석]\n"
            "  np.array_split(idx, k)\n"
            "         → 인덱스를 k 조각으로 나눈다. 개수가 안 나눠떨어져도\n"
            "            알아서 크기를 맞춰준다. 직접 자르다 마지막 조각을 흘리는 실수를 막는다.\n"
            "  np.concatenate([folds[j] for j in range(k) if j != i])\n"
            "         → i 번째를 뺀 나머지를 훈련용으로 합친다.\n"
            "  rng.permutation(n)\n"
            "         → 나누기 전에 반드시 섞는다. 데이터가 정렬되어 있으면\n"
            "            각 조각의 성격이 달라져 결과가 왜곡된다.\n"
            "  scores.mean(), scores.std()\n"
            "         → 평균과 함께 편차를 본다. 편차가 크면 신뢰할 수 없는 모델이다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 분류에서 클래스 비율이 치우쳤다면 각 조각의 비율을 맞춰야 한다\n"
            "    (계층적 k-fold). 안 그러면 어떤 조각엔 양성이 하나도 없을 수 있다.\n"
            "  • 시계열 데이터에 일반 k-fold 를 쓰면 안 된다.\n"
            "    미래로 과거를 예측하는 꼴이 되어(시간 누수) 성능이 부풀려진다.\n"
            "  • 전처리(표준화)는 각 폴드의 훈련 부분에서만 계산해야 한다.\n"
            "    전체 데이터로 먼저 표준화하면 검증 정보가 새어든다."
        ),
        usage="모델·하이퍼파라미터를 고르는 표준 절차. 논문과 실무 모두 이 방식으로 성능을 보고한다.",
        cons="k 배로 학습해야 해서 시간이 오래 걸린다. 딥러닝처럼 학습이 비싼 모델엔 부담이 크다.",
        code=(
            "import numpy as np\n"
            "\n"
            "rng = np.random.default_rng(7)\n"
            "\n"
            "n = 60\n"
            "x = np.sort(rng.uniform(-3, 3, n))\n"
            "y = 0.5 * x ** 3 - 2 * x + rng.normal(0, 2.0, n)\n"
            "xs = x / 3.0\n"
            "\n"
            "def ridge_rmse(tr, te, deg, lam):\n"
            "    A = np.vander(xs[tr], deg + 1, increasing=True)\n"
            "    reg = np.eye(deg + 1)\n"
            "    reg[0, 0] = 0.0\n"
            "    w = np.linalg.solve(A.T @ A + lam * reg, A.T @ y[tr])\n"
            "    P = np.vander(xs[te], deg + 1, increasing=True)\n"
            "    return float(np.sqrt(((y[te] - P @ w) ** 2).mean()))\n"
            "\n"
            "def cross_val(deg, lam, k=5, seed=0):\n"
            "    idx = np.random.default_rng(seed).permutation(n)\n"
            "    folds = np.array_split(idx, k)\n"
            "    out = []\n"
            "    for i in range(k):\n"
            "        te = folds[i]\n"
            "        tr = np.concatenate([folds[j] for j in range(k) if j != i])\n"
            "        out.append(ridge_rmse(tr, te, deg, lam))\n"
            "    return np.array(out)\n"
            "\n"
            "# 한 번만 나눈 결과가 얼마나 흔들리는지\n"
            "print('-- 단일 분할을 시드만 바꿔 5번 --')\n"
            "single = []\n"
            "for seed in range(5):\n"
            "    r = np.random.default_rng(seed)\n"
            "    idx = r.permutation(n)\n"
            "    single.append(ridge_rmse(idx[:48], idx[48:], 9, 0.01))\n"
            "    print(f'  seed {seed}: RMSE {single[-1]:.3f}')\n"
            "print(f'  → 최소 {min(single):.3f} ~ 최대 {max(single):.3f} 로 크게 흔들린다')\n"
            "\n"
            "print('\\n-- 5-fold 교차검증으로 λ 고르기 (차수 9) --')\n"
            "print('   λ      평균RMSE   표준편차')\n"
            "best = (None, 1e18)\n"
            "for lam in [0.0, 0.001, 0.01, 0.1, 1.0, 10.0]:\n"
            "    s = cross_val(9, lam)\n"
            "    print(f'{lam:6.3f}   {s.mean():8.3f}   {s.std():8.3f}')\n"
            "    if s.mean() < best[1]:\n"
            "        best = (lam, s.mean())\n"
            "\n"
            "print(f'\\n선택된 λ = {best[0]}  (교차검증 평균 RMSE {best[1]:.3f})')\n"
            "print('→ 이 λ 로 전체 훈련 데이터를 다시 학습시킨 뒤,')\n"
            "print('  따로 떼어둔 시험 데이터로 딱 한 번 최종 성능을 잰다.')\n"
        ),
    ),

    Lesson(
        id="ds3-08-tree",
        lang="datasci", level=STAGE,
        title="의사결정나무",
        summary="스무고개로 분류하기 · 지니 불순도",
        explanation=(
            "[개요]\n"
            "의사결정나무는 '예/아니오' 질문을 이어가며 분류한다. 스무고개와 같다.\n"
            "\n"
            "    공부시간 > 5 ?\n"
            "     ├ 아니오 → 출석률 > 70 ?\n"
            "     │           ├ 아니오 → 불합격\n"
            "     │           └ 예     → 합격\n"
            "     └ 예     → 합격\n"
            "\n"
            "사람이 읽을 수 있는 규칙이 그대로 나온다는 게 가장 큰 장점이다.\n"
            "금융 심사처럼 '왜 거절했는지' 설명해야 하는 분야에서 특히 강하다.\n"
            "\n"
            "[좋은 질문이란 — 지니 불순도]\n"
            "질문을 던진 뒤 양쪽이 최대한 '순수'해지는 게 좋은 질문이다.\n"
            "\n"
            "    지니 불순도 = 1 - Σ pᵢ²\n"
            "\n"
            "  · 전부 같은 클래스 [10명 합격, 0명 불합격] → 1 - 1² = 0      완전 순수\n"
            "  · 반반           [5명 합격, 5명 불합격]  → 1 - (0.25+0.25) = 0.5  가장 지저분\n"
            "\n"
            "  0 에 가까울수록 좋다. 이진 분류에서 최댓값은 0.5 다.\n"
            "\n"
            "[분할 기준]\n"
            "  나눈 뒤의 불순도를 개수로 가중평균해서 가장 작아지는 질문을 고른다.\n"
            "\n"
            "    가중 불순도 = (왼쪽 개수·왼쪽 지니 + 오른쪽 개수·오른쪽 지니) / 전체\n"
            "\n"
            "  모든 특성 × 모든 임계값을 다 시도해 최선을 찾는다(탐욕적 탐색).\n"
            "  전체를 보고 최적의 트리를 찾는 게 아니라 매 단계 최선만 고른다.\n"
            "\n"
            "[언제 멈추나 — 과적합의 위험]\n"
            "  끝까지 나누면 모든 잎이 순수해져 훈련 정확도가 100% 가 된다.\n"
            "  하지만 그건 데이터를 통째로 외운 것이라 새 데이터에서 무너진다.\n"
            "  트리는 **과적합에 가장 취약한 모델**이다.\n"
            "\n"
            "  그래서 멈춤 조건을 건다.\n"
            "    · max_depth        : 최대 깊이\n"
            "    · min_samples_split: 이 개수 미만이면 더 안 나눔\n"
            "    · 순수해지면 중단\n"
            "\n"
            "[코드 분석]\n"
            "  np.bincount(y, minlength=2) / len(y)\n"
            "         → 클래스별 비율. minlength=2 를 줘야 한쪽 클래스가 없어도\n"
            "            길이 2 배열이 나와 계산이 안전하다.\n"
            "  for t in np.unique(col)[:-1]\n"
            "         → 후보 임계값. 가장 큰 값은 제외한다.\n"
            "            그 값으로 나누면 오른쪽이 비어 분할이 성립하지 않기 때문이다.\n"
            "  build(X, y, depth)\n"
            "         → 재귀로 트리를 만든다. 딕셔너리로 노드를 표현했다.\n"
            "            잎이면 {'leaf': 예측값}, 아니면 {'f':특성, 't':임계값, 'L':..., 'R':...}\n"
            "  잡음 특성 3개를 일부러 섞었다\n"
            "         → y 와 아무 관계 없는 난수 열이다. 깊은 트리는 이 잡음에서도\n"
            "            '규칙'을 찾아내며 과적합한다. 실제 데이터에도 쓸모없는 열은 항상 있다.\n"
            "  깊이별 정확도 비교\n"
            "         → 훈련 정확도는 1.000 까지 오르지만 검증 정확도는\n"
            "            깊이 3 에서 정점(0.830)을 찍고 깊이 4 부터 떨어진다(0.760).\n"
            "            이 꺾이는 지점이 적정 깊이다.\n"
            "  잎에 (n=.., 합격 ..%) 표시\n"
            "         → 잎의 예측값만 보면 양쪽 가지가 똑같아 보일 때가 있다.\n"
            "            비율을 함께 보면 '나눈 뒤 순도가 올라갔다'는 것이 드러난다.\n"
            "            트리는 다수결로 라벨을 정하므로, 60%:90% 처럼 비율이 달라도\n"
            "            둘 다 같은 라벨이 될 수 있다. 무의미한 분할이 아니다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 트리 하나는 데이터가 조금만 바뀌어도 구조가 확 달라진다(불안정).\n"
            "    그래서 실무에서는 트리를 여러 개 묶어 쓴다 → 다음 레슨.\n"
            "  • 트리는 표준화가 필요 없다. 크기가 아니라 순서만 보기 때문이다.\n"
            "    (거리 기반인 k-NN·k-means 와 대조적이다)\n"
            "  • 축에 수직인 선으로만 나눈다. 대각선 경계는 계단 모양으로 근사한다."
        ),
        usage="규칙을 설명해야 하는 분류. 부스팅·랜덤포레스트 같은 강력한 모델의 기본 부품이기도 하다.",
        cons="단독으로는 과적합이 심하고 불안정하다. 실무에서 트리 하나만 쓰는 경우는 드물다.",
        code=(
            "import numpy as np\n"
            "\n"
            "rng = np.random.default_rng(42)\n"
            "\n"
            "# 합격/불합격 데이터 (공부시간, 출석률 + 쓸모없는 잡음 3개)\n"
            "n = 300\n"
            "study = rng.uniform(0, 10, n)\n"
            "attend = rng.uniform(40, 100, n)\n"
            "noise1 = rng.uniform(0, 1, n)\n"
            "noise2 = rng.uniform(0, 1, n)\n"
            "noise3 = rng.uniform(0, 1, n)\n"
            "z = 0.8 * study + 0.06 * attend - 8\n"
            "y = (rng.random(n) < 1 / (1 + np.exp(-z))).astype(int)\n"
            "X = np.column_stack([study, attend, noise1, noise2, noise3])\n"
            "\n"
            "idx = rng.permutation(n)\n"
            "tr, te = idx[:100], idx[100:]      # 훈련을 적게 줘서 과적합이 드러나게\n"
            "\n"
            "def gini(labels):\n"
            "    if len(labels) == 0:\n"
            "        return 0.0\n"
            "    p = np.bincount(labels, minlength=2) / len(labels)\n"
            "    return float(1 - (p ** 2).sum())\n"
            "\n"
            "print('지니 예시:')\n"
            "print('  [1,1,1,1]     →', gini(np.array([1, 1, 1, 1])))\n"
            "print('  [0,0,1,1]     →', gini(np.array([0, 0, 1, 1])))\n"
            "print('  [0,0,0,1]     →', gini(np.array([0, 0, 0, 1])))\n"
            "\n"
            "def best_split(X, y):\n"
            "    best_f, best_t, best_score = None, None, 1e18\n"
            "    for f in range(X.shape[1]):\n"
            "        col = X[:, f]\n"
            "        for t in np.unique(col)[:-1]:\n"
            "            left = y[col <= t]\n"
            "            right = y[col > t]\n"
            "            if len(left) == 0 or len(right) == 0:\n"
            "                continue\n"
            "            score = (len(left) * gini(left) + len(right) * gini(right)) / len(y)\n"
            "            if score < best_score:\n"
            "                best_f, best_t, best_score = f, float(t), score\n"
            "    return best_f, best_t, best_score\n"
            "\n"
            "def leaf(y):\n"
            "    return {'leaf': int(np.bincount(y, minlength=2).argmax()),\n"
            "            'n': int(len(y)),\n"
            "            'pos': float(y.mean()) if len(y) else 0.0}\n"
            "\n"
            "def build(X, y, depth, max_depth, min_samples=2):\n"
            "    if depth >= max_depth or len(y) < min_samples or gini(y) == 0.0:\n"
            "        return leaf(y)\n"
            "    f, t, _ = best_split(X, y)\n"
            "    if f is None:\n"
            "        return leaf(y)\n"
            "    m = X[:, f] <= t\n"
            "    return {'f': f, 't': t,\n"
            "            'L': build(X[m], y[m], depth + 1, max_depth, min_samples),\n"
            "            'R': build(X[~m], y[~m], depth + 1, max_depth, min_samples)}\n"
            "\n"
            "def predict_one(node, row):\n"
            "    while 'leaf' not in node:\n"
            "        node = node['L'] if row[node['f']] <= node['t'] else node['R']\n"
            "    return node['leaf']\n"
            "\n"
            "def accuracy(tree, part):\n"
            "    pred = np.array([predict_one(tree, r) for r in X[part]])\n"
            "    return float((pred == y[part]).mean())\n"
            "\n"
            "depths = [1, 2, 3, 4, 6, 8, 12]\n"
            "rows = []\n"
            "for d in depths:\n"
            "    tree = build(X[tr], y[tr], 0, d)\n"
            "    rows.append((d, accuracy(tree, tr), accuracy(tree, te)))\n"
            "best_d = max(rows, key=lambda r: r[2])[0]\n"
            "\n"
            "print('\\n-- 깊이별 정확도 --')\n"
            "print('깊이   훈련    검증')\n"
            "for d, a_tr, a_te in rows:\n"
            "    print(f'{d:3d}   {a_tr:.3f}   {a_te:.3f}' + ('  ← 최고' if d == best_d else ''))\n"
            "\n"
            "print(f'\\n→ 훈련 정확도는 1.000 까지 오르지만, 검증은 깊이 {best_d} 에서 정점을 찍고')\n"
            "print('  그 뒤로 떨어진다. 잡음 특성에서 가짜 규칙을 찾아낸 것이다 = 과적합')\n"
            "\n"
            "# 학습된 규칙 출력\n"
            "names = ['공부시간', '출석률', '잡음1', '잡음2', '잡음3']\n"
            "def show(node, indent=''):\n"
            "    if 'leaf' in node:\n"
            "        tag = '합격' if node['leaf'] == 1 else '불합격'\n"
            "        print(f\"{indent}→ {tag}  (n={node['n']}, 합격 {node['pos']:.0%})\")\n"
            "        return\n"
            "    print(f\"{indent}{names[node['f']]} <= {node['t']:.2f} ?\")\n"
            "    print(f'{indent}  예:')\n"
            "    show(node['L'], indent + '    ')\n"
            "    print(f'{indent}  아니오:')\n"
            "    show(node['R'], indent + '    ')\n"
            "\n"
            "print('\\n-- 학습된 규칙 (깊이 2) --')\n"
            "show(build(X[tr], y[tr], 0, 2))\n"
            "print('\\n※ 읽는 법 두 가지')\n"
            "print('  1) 두 잎의 라벨이 같아도 합격 비율은 다르다.')\n"
            "print('     트리는 다수결로 라벨을 정하므로 60% 도 97% 도 모두 \"합격\" 이 된다.')\n"
            "print('  2) 오른쪽 가지가 \"잡음2\" 를 기준으로 삼았다.')\n"
            "print('     y 와 아무 상관 없는 난수인데도 이 훈련 데이터에서는 우연히')\n"
            "print('     지니 불순도가 가장 많이 줄었기 때문이다.')\n"
            "print('     깊이를 키울수록 이런 가짜 규칙이 늘어난다. 이것이 과적합의 정체다.')\n"
        ),
    ),

    Lesson(
        id="ds3-09-ensemble",
        lang="datasci", level=STAGE,
        title="앙상블 · 배깅",
        summary="약한 모델 여럿의 다수결이 강한 모델 하나를 이긴다",
        explanation=(
            "[개요]\n"
            "앙상블은 여러 모델의 예측을 합쳐 하나의 답을 내는 방법이다.\n"
            "실무 표 데이터에서 가장 좋은 성능을 내는 모델은 거의 항상 앙상블이다.\n"
            "\n"
            "[왜 합치면 좋아지는가]\n"
            "  각 모델이 서로 다른 실수를 한다면, 다수결에서 실수가 상쇄된다.\n"
            "\n"
            "  정확도 60% 짜리 모델 하나 → 60%\n"
            "  정확도 60% 짜리 **서로 독립적인** 모델 5개의 다수결 → 약 68%\n"
            "  같은 모델 5개면 아무 효과가 없다. **다양성이 핵심이다.**\n"
            "\n"
            "[다양성을 만드는 방법]\n"
            "  1) 배깅(Bagging) : 데이터를 복원추출로 다르게 뽑아 각각 학습\n"
            "     · 복원추출(bootstrap) = 뽑은 걸 도로 넣고 또 뽑는다. 중복이 생긴다.\n"
            "     · 각 모델이 조금씩 다른 데이터를 보므로 서로 다른 실수를 한다.\n"
            "  2) 랜덤 특성   : 각 분할에서 특성 일부만 후보로 쓴다\n"
            "     · 배깅 + 랜덤 특성 + 의사결정나무 = **랜덤 포레스트**\n"
            "  3) 부스팅(Boosting) : 앞 모델이 틀린 데이터에 가중치를 주고 다음 모델을 학습\n"
            "     · 순차적으로 오차를 줄여간다. XGBoost·LightGBM 이 여기에 속한다.\n"
            "     · 캐글 표 데이터 대회 우승 모델은 거의 전부 부스팅 계열이다.\n"
            "\n"
            "[배깅 vs 부스팅]\n"
            "  배깅   : 모델들을 **병렬로** 독립 학습 → 분산을 줄인다(과적합 완화)\n"
            "  부스팅 : 모델들을 **순차로** 학습        → 편향을 줄인다(정확도 상승)\n"
            "  배깅은 안정적이고, 부스팅은 더 정확하지만 과적합에 주의해야 한다.\n"
            "\n"
            "[무엇과 비교해야 공정한가 — 이 레슨의 핵심]\n"
            "  앙상블의 효과는 '**앙상블에 들어간 개별 모델들**'과 비교해야 한다.\n"
            "  각 모델은 데이터 일부(복원추출)와 특성 일부만 보므로 혼자서는 약하다.\n"
            "  그 약한 모델들의 평균 성능보다 다수결이 얼마나 나은지가 앙상블의 순수한 이득이다.\n"
            "\n"
            "  아래 실행 결과에서 개별 평균은 0.65 언저리인데 다수결은 0.79 로 올라간다.\n"
            "  개별 모델 중 최악은 0.46(동전 던지기보다 못함)인데도,\n"
            "  묶으면 그 어떤 개별 모델보다도 좋아진다. 이것이 앙상블의 힘이다.\n"
            "\n"
            "[코드 분석]\n"
            "  약한 학습기로 '깊이 8 트리 + 데이터 일부 + 특성 일부' 를 쓴다.\n"
            "  깊은 트리는 과적합해서 불안정하다. 배깅은 바로 이 불안정을 잡아주는 도구다.\n"
            "\n"
            "  rng.integers(0, n, n)\n"
            "         → 복원추출(bootstrap). 0~n-1 에서 n 개를 중복 허용해 뽑는다.\n"
            "            평균적으로 원본의 약 63% 만 뽑히고 나머지는 빠진다.\n"
            "            빠진 37% 를 검증에 쓰는 기법을 OOB(out-of-bag) 평가라 한다.\n"
            "  feats = rng.choice(5, 3, replace=False)\n"
            "         → 랜덤 특성. 각 트리가 5개 중 3개만 보게 한다.\n"
            "            운 나쁘게 잡음 특성만 뽑힌 트리는 성능이 형편없다(그래서 최저 0.46).\n"
            "            하지만 그런 트리들의 실수는 서로 방향이 달라 다수결에서 상쇄된다.\n"
            "  preds.mean(axis=0) >= 0.5\n"
            "         → 다수결. 0/1 예측의 평균이 0.5 이상이면 1 로 본다.\n"
            "  개수를 늘려가며 관찰\n"
            "         → 다수결 정확도가 오르다가 평평해진다.\n"
            "            배깅은 모델을 많이 넣어도 과적합하지 않는다는 게 큰 장점이다.\n"
            "            (부스팅은 너무 많이 넣으면 과적합한다. 이 점이 다르다)\n"
            "\n"
            "[유의 사항]\n"
            "  • 앙상블은 해석 가능성을 잃는다. 트리 100개의 다수결은 설명하기 어렵다.\n"
            "  • 모델들이 비슷하면 효과가 없다. 다양성이 없으면 그냥 느려지기만 한다.\n"
            "  • 예측할 때 모델 수만큼 계산해야 하므로 응답 속도가 느려진다.\n"
            "  • 여기 랜덤포레스트는 원리 확인용이라 튜닝하지 않았다.\n"
            "    특성을 전부 쓰는 잘 조정된 트리 하나가 더 나을 수도 있다.\n"
            "    실무에서는 트리 깊이·특성 개수·모델 수를 교차검증으로 맞춘다."
        ),
        usage="표 형태 데이터에서 성능이 필요할 때의 정답에 가깝다. 캐글·실무 모두 기본 선택.",
        cons="해석이 어렵고, 학습·예측 비용이 모델 수만큼 늘어난다.",
        code=(
            "import numpy as np\n"
            "\n"
            "rng = np.random.default_rng(42)\n"
            "\n"
            "n = 300\n"
            "study = rng.uniform(0, 10, n)\n"
            "attend = rng.uniform(40, 100, n)\n"
            "noise1 = rng.uniform(0, 1, n)         # 쓸모없는 특성 3개 (일부러 넣음)\n"
            "noise2 = rng.uniform(0, 1, n)\n"
            "noise3 = rng.uniform(0, 1, n)\n"
            "z = 0.8 * study + 0.06 * attend - 8\n"
            "y = (rng.random(n) < 1 / (1 + np.exp(-z))).astype(int)\n"
            "X = np.column_stack([study, attend, noise1, noise2, noise3])\n"
            "\n"
            "idx = rng.permutation(n)\n"
            "tr, te = idx[:100], idx[100:]\n"
            "\n"
            "def gini(labels):\n"
            "    if len(labels) == 0:\n"
            "        return 0.0\n"
            "    p = np.bincount(labels, minlength=2) / len(labels)\n"
            "    return float(1 - (p ** 2).sum())\n"
            "\n"
            "def best_split(X, y, feats):\n"
            "    bf, bt, bs = None, None, 1e18\n"
            "    for f in feats:\n"
            "        col = X[:, f]\n"
            "        for t in np.quantile(col, [.1, .2, .3, .4, .5, .6, .7, .8, .9]):\n"
            "            m = col <= t\n"
            "            if m.all() or (~m).all():\n"
            "                continue\n"
            "            s = (m.sum() * gini(y[m]) + (~m).sum() * gini(y[~m])) / len(y)\n"
            "            if s < bs:\n"
            "                bf, bt, bs = f, float(t), s\n"
            "    return bf, bt\n"
            "\n"
            "def build(X, y, depth, max_depth, feats):\n"
            "    if depth >= max_depth or len(y) < 2 or gini(y) == 0.0:\n"
            "        return {'leaf': int(np.bincount(y, minlength=2).argmax())}\n"
            "    f, t = best_split(X, y, feats)\n"
            "    if f is None:\n"
            "        return {'leaf': int(np.bincount(y, minlength=2).argmax())}\n"
            "    m = X[:, f] <= t\n"
            "    return {'f': f, 't': t,\n"
            "            'L': build(X[m], y[m], depth + 1, max_depth, feats),\n"
            "            'R': build(X[~m], y[~m], depth + 1, max_depth, feats)}\n"
            "\n"
            "def predict(tree, Xp):\n"
            "    out = []\n"
            "    for row in Xp:\n"
            "        nd = tree\n"
            "        while 'leaf' not in nd:\n"
            "            nd = nd['L'] if row[nd['f']] <= nd['t'] else nd['R']\n"
            "        out.append(nd['leaf'])\n"
            "    return np.array(out)\n"
            "\n"
            "def bagging(n_models, seed=0):\n"
            "    r = np.random.default_rng(seed)\n"
            "    models = []\n"
            "    for _ in range(n_models):\n"
            "        boot = r.integers(0, len(tr), len(tr))       # 복원추출\n"
            "        feats = r.choice(5, 3, replace=False)         # 특성 5개 중 3개만\n"
            "        models.append(build(X[tr[boot]], y[tr[boot]], 0, 8, feats))\n"
            "    P = np.array([predict(m, X[te]) for m in models])\n"
            "    indiv = np.array([(p == y[te]).mean() for p in P])\n"
            "    vote = float(((P.mean(axis=0) >= 0.5).astype(int) == y[te]).mean())\n"
            "    return indiv, vote\n"
            "\n"
            "print('-- 개별 모델(약한 학습기) vs 다수결 --')\n"
            "print('모델수   개별평균   개별최저   개별최고   다수결')\n"
            "for k in [3, 5, 11, 21, 41]:\n"
            "    indiv, vote = bagging(k)\n"
            "    print(f'{k:5d}    {indiv.mean():7.3f}   {indiv.min():7.3f}   '\n"
            "          f'{indiv.max():7.3f}   {vote:6.3f}')\n"
            "\n"
            "print('\\n→ 개별 모델 평균은 0.65 언저리, 최악은 0.46 으로 동전 던지기만도 못하다.')\n"
            "print('  그런데 다수결로 묶으면 0.79 까지 오른다.')\n"
            "print('  서로 다른 실수가 상쇄되기 때문이다 — 이것이 앙상블의 힘이다.')\n"
            "print('\\n  모델 수를 늘릴수록 다수결이 오르다가 평평해진다.')\n"
            "print('  배깅은 많이 넣어도 과적합하지 않는다.')\n"
        ),
    ),

    Lesson(
        id="ds3-10-kmeans",
        lang="datasci", level=STAGE,
        title="k-means 군집 (비지도학습)",
        summary="정답 없이 비슷한 것끼리 묶기",
        explanation=(
            "[개요]\n"
            "지금까지는 정답(y)이 있는 지도학습이었다.\n"
            "군집(clustering)은 정답 없이 데이터의 구조만 보고 비슷한 것끼리 묶는다.\n"
            "\n"
            "  · 고객 세분화 : 구매 패턴이 비슷한 고객을 그룹으로\n"
            "  · 이상 탐지   : 어느 군집에도 안 속하는 데이터 찾기\n"
            "  · 이미지 압축 : 비슷한 색을 하나로 묶기\n"
            "\n"
            "[k-means 동작 — 2단계 반복]\n"
            "  1) 중심점 k 개를 아무렇게나 놓는다\n"
            "  2) 할당 : 각 점을 가장 가까운 중심에 배정한다\n"
            "  3) 갱신 : 각 그룹의 평균 위치로 중심을 옮긴다\n"
            "  4) 중심이 안 움직일 때까지 2~3 반복\n"
            "\n"
            "  '평균(mean)으로 중심을 옮긴다'가 이름의 유래다.\n"
            "\n"
            "[k 는 몇으로 — 엘보 방법]\n"
            "  k 를 사람이 정해줘야 한다는 게 가장 큰 약점이다.\n"
            "\n"
            "  관성(inertia) = 각 점과 자기 중심 사이 거리 제곱의 합\n"
            "  k 를 키우면 관성은 무조건 줄어든다(k=n 이면 0).\n"
            "  그래서 '급격히 줄다가 완만해지는 꺾인 지점'을 고른다.\n"
            "  그래프 모양이 팔꿈치 같아서 엘보(elbow) 방법이라 한다.\n"
            "\n"
            "[코드 분석]\n"
            "  ((X[:, None, :] - C[None, :, :]) ** 2).sum(axis=2)\n"
            "         → 모든 점과 모든 중심의 거리 제곱을 한 번에 구한다.\n"
            "            X 는 (n, d), C 는 (k, d) 인데\n"
            "            X[:, None, :] 로 (n, 1, d) 를 만들고\n"
            "            C[None, :, :] 로 (1, k, d) 를 만들면\n"
            "            브로드캐스팅으로 (n, k, d) 가 되고, 마지막 축을 더해 (n, k) 가 된다.\n"
            "            이중 반복문 없이 거리 행렬을 만드는 표준 기법이다.\n"
            "  d.argmin(axis=1)\n"
            "         → 각 점이 어느 중심에 가장 가까운지(라벨).\n"
            "  X[lab == j].mean(axis=0)\n"
            "         → j번 그룹의 새 중심.\n"
            "  if (lab == j).any() else C[j]\n"
            "         → 아무 점도 안 배정된 빈 군집 처리. 이걸 빼먹으면\n"
            "            빈 배열의 평균이 nan 이 되어 전체가 망가진다.\n"
            "  np.allclose(newC, C)\n"
            "         → 중심이 더 안 움직이면 조기 종료.\n"
            "  여러 시드로 반복\n"
            "         → k-means 는 초기 중심에 따라 결과가 달라진다.\n"
            "            여러 번 돌려 관성이 가장 작은 것을 고르는 게 표준이다(k-means++ 도 있다).\n"
            "\n"
            "[유의 사항]\n"
            "  • 거리 기반이므로 **표준화가 필수**다. 연봉(천만 단위)과 나이(십 단위)를\n"
            "    그대로 쓰면 연봉이 거리를 지배한다.\n"
            "  • 원형에 가까운 덩어리만 잘 찾는다. 초승달·고리 모양은 못 찾는다\n"
            "    (그런 데이터엔 DBSCAN 같은 밀도 기반 방법을 쓴다).\n"
            "  • 군집 결과에 '정답'은 없다. 나온 그룹이 의미 있는지는 사람이 해석해야 한다."
        ),
        usage="고객 세분화, 문서 주제 묶기, 색상 양자화. 데이터에 어떤 덩어리가 있는지 탐색할 때.",
        cons="k 를 미리 정해야 하고, 초기값에 따라 결과가 달라지며, 원형 군집만 잘 찾는다.",
        code=(
            "import numpy as np\n"
            "\n"
            "rng = np.random.default_rng(42)\n"
            "\n"
            "# 실제로는 3덩어리인 데이터 (모델은 이 사실을 모른다)\n"
            "true_centers = np.array([[2.0, 2.0], [8.0, 3.0], [5.0, 9.0]])\n"
            "X = np.vstack([rng.normal(c, 0.8, size=(60, 2)) for c in true_centers])\n"
            "print('데이터:', X.shape)\n"
            "\n"
            "def kmeans(X, k, seed, iters=100):\n"
            "    r = np.random.default_rng(seed)\n"
            "    C = X[r.choice(len(X), k, replace=False)].copy()\n"
            "    lab = np.zeros(len(X), dtype=int)\n"
            "    for step in range(iters):\n"
            "        d = ((X[:, None, :] - C[None, :, :]) ** 2).sum(axis=2)\n"
            "        lab = d.argmin(axis=1)\n"
            "        newC = np.array([X[lab == j].mean(axis=0) if (lab == j).any() else C[j]\n"
            "                         for j in range(k)])\n"
            "        if np.allclose(newC, C):\n"
            "            break\n"
            "        C = newC\n"
            "    inertia = float(((X - C[lab]) ** 2).sum())\n"
            "    return lab, C, inertia, step\n"
            "\n"
            "lab, C, inertia, steps = kmeans(X, 3, seed=0)\n"
            "print(f'\\nk=3 · {steps}번 만에 수렴 · 관성 {inertia:.1f}')\n"
            "# 군집 번호는 실행마다 뒤바뀌므로, 비교하려면 양쪽을 같은 기준으로 정렬한다\n"
            "print('   찾은 중심        실제 중심')\n"
            "for got, real in zip(sorted(C.tolist()), sorted(true_centers.tolist())):\n"
            "    print(f'  [{got[0]:5.2f}, {got[1]:5.2f}]   [{real[0]:5.2f}, {real[1]:5.2f}]')\n"
            "print('→ 정답을 알려준 적이 없는데 실제 중심을 거의 정확히 찾아냈다')\n"
            "\n"
            "print('\\n군집별 개수:', np.bincount(lab).tolist())\n"
            "\n"
            "print('\\n-- 엘보 방법: k 를 바꿔가며 관성 --')\n"
            "prev = None\n"
            "for k in range(1, 7):\n"
            "    best = min(kmeans(X, k, seed=s)[2] for s in range(5))\n"
            "    drop = '' if prev is None else f'  (감소 {prev - best:7.1f})'\n"
            "    print(f'  k={k}  관성 {best:8.1f}{drop}')\n"
            "    prev = best\n"
            "print('\\n→ k=3 이후로 감소 폭이 확 줄어든다. 여기가 팔꿈치다.')\n"
            "\n"
            "print('\\n-- 초기값에 따른 결과 차이 --')\n"
            "for s in range(5):\n"
            "    print(f'  seed {s}: 관성 {kmeans(X, 3, seed=s)[2]:.1f}')\n"
            "print('  → 여러 번 돌려 가장 작은 것을 고른다')\n"
        ),
    ),

    Lesson(
        id="ds3-11-pca",
        lang="datasci", level=STAGE,
        title="PCA 차원 축소",
        summary="정보를 최대한 지키며 열 개수 줄이기",
        explanation=(
            "[개요]\n"
            "특성이 100개인 데이터가 있다. 전부 필요할까?\n"
            "대개는 몇 개의 '진짜 축'이 데이터를 대부분 설명하고, 나머지는 그 조합이다.\n"
            "PCA(주성분 분석)는 그 축을 찾아 열 개수를 줄인다.\n"
            "\n"
            "[왜 줄이나]\n"
            "  · 차원의 저주 : 특성이 많으면 거리 개념이 무의미해지고 데이터가 희박해진다\n"
            "  · 시각화      : 100차원은 못 그린다. 2차원으로 줄이면 눈으로 볼 수 있다\n"
            "  · 잡음 제거   : 분산이 작은 축은 대개 잡음이다\n"
            "  · 속도        : 열이 적으면 학습이 빠르다\n"
            "\n"
            "[핵심 아이디어 — 분산이 큰 방향을 찾는다]\n"
            "  데이터가 가장 넓게 퍼진 방향이 정보를 가장 많이 담고 있다.\n"
            "  그 방향을 제1 주성분(PC1)이라 한다.\n"
            "  PC1 과 **직각인 방향** 중 가장 넓게 퍼진 것이 PC2 다. 이런 식으로 이어진다.\n"
            "\n"
            "  키와 몸무게처럼 상관이 높은 두 특성이 있으면,\n"
            "  '체격'이라는 하나의 축이 대부분을 설명한다. PCA 는 이 축을 자동으로 찾아낸다.\n"
            "\n"
            "[계산 순서]\n"
            "  1) 중심화 : 각 열에서 그 열의 평균을 뺀다 (필수)\n"
            "  2) 공분산 행렬을 구한다\n"
            "  3) 고유값 분해 → 고유벡터가 방향, 고유값이 그 방향의 분산\n"
            "  4) 고유값이 큰 순으로 정렬해 위에서 k 개를 고른다\n"
            "  5) 데이터를 그 축들에 투영한다\n"
            "\n"
            "[설명된 분산 비율]\n"
            "  각 고유값 ÷ 고유값 총합 = 그 주성분이 설명하는 정보의 비율\n"
            "  누적이 90~95% 되는 지점까지 쓰는 게 관례다.\n"
            "\n"
            "[코드 분석]\n"
            "  Xc = X - X.mean(axis=0)\n"
            "         → 중심화. 이걸 빼먹으면 첫 주성분이 '원점에서 데이터 덩어리까지의\n"
            "            방향'을 가리켜 완전히 엉뚱한 결과가 나온다.\n"
            "  np.cov(Xc, rowvar=False)\n"
            "         → 공분산 행렬. rowvar=False 는 '행이 관측치, 열이 변수'라는 뜻이다.\n"
            "            기본값(True)은 반대라 결과가 완전히 달라진다. 자주 하는 실수다.\n"
            "  np.linalg.eigh(cov)\n"
            "         → 대칭 행렬 전용 고유값 분해. 공분산 행렬은 항상 대칭이므로\n"
            "            일반용 eig() 보다 이쪽이 빠르고 정확하다(실수만 나온다).\n"
            "  order = vals.argsort()[::-1]\n"
            "         → eigh 는 고유값을 오름차순으로 준다. 큰 것부터 쓰려고 뒤집는다.\n"
            "  Z = Xc @ vecs[:, :k]\n"
            "         → 투영. (n, d) @ (d, k) = (n, k). 열이 d 개에서 k 개로 줄었다.\n"
            "  복원 : Z @ vecs[:, :k].T + mean\n"
            "         → 줄인 데이터를 다시 원래 차원으로 되돌린다.\n"
            "            원본과의 차이가 '버린 정보'다. k 를 늘리면 이 오차가 줄어든다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 단위가 다른 특성이 섞여 있으면 **표준화 후에** PCA 를 해야 한다.\n"
            "    안 하면 값이 큰 특성이 주성분을 독차지한다.\n"
            "  • 주성분은 원래 특성들의 혼합이라 의미를 해석하기 어렵다.\n"
            "    'PC1 이 0.7 증가' 가 무슨 뜻인지 설명하기 곤란하다.\n"
            "  • 분산이 큰 방향이 항상 '유용한' 방향은 아니다.\n"
            "    분류에 중요한 축이 분산은 작을 수도 있다."
        ),
        usage="특성이 너무 많을 때의 전처리, 고차원 데이터 시각화, 잡음 제거.",
        cons="주성분의 의미를 해석하기 어렵고, 비선형 구조는 잡지 못한다.",
        code=(
            "import numpy as np\n"
            "\n"
            "rng = np.random.default_rng(42)\n"
            "n = 200\n"
            "\n"
            "# 실제로는 '체격'이라는 하나의 축이 대부분을 설명하는 데이터\n"
            "base = rng.normal(0, 1, n)\n"
            "height = 170 + 8 * base + rng.normal(0, 1.5, n)\n"
            "weight = 65 + 9 * base + rng.normal(0, 2.0, n)\n"
            "shoe = 250 + 12 * base + rng.normal(0, 3.0, n)\n"
            "noise = rng.normal(50, 5, n)              # 무관한 특성\n"
            "\n"
            "X = np.column_stack([height, weight, shoe, noise])\n"
            "names = ['키', '몸무게', '신발', '잡음']\n"
            "print('원본 모양:', X.shape)\n"
            "\n"
            "# 단위가 다르므로 표준화 후 PCA\n"
            "Xs = (X - X.mean(axis=0)) / X.std(axis=0)\n"
            "\n"
            "Xc = Xs - Xs.mean(axis=0)\n"
            "cov = np.cov(Xc, rowvar=False)\n"
            "vals, vecs = np.linalg.eigh(cov)\n"
            "order = vals.argsort()[::-1]\n"
            "vals, vecs = vals[order], vecs[:, order]\n"
            "\n"
            "# 고유벡터의 부호는 수학적으로 임의다(방향만 의미 있음).\n"
            "# 읽기 쉽도록 '절댓값이 가장 큰 성분이 양수'가 되게 통일한다.\n"
            "for j in range(vecs.shape[1]):\n"
            "    if vecs[np.abs(vecs[:, j]).argmax(), j] < 0:\n"
            "        vecs[:, j] *= -1\n"
            "\n"
            "ratio = vals / vals.sum()\n"
            "print('\\n-- 설명된 분산 비율 --')\n"
            "cum = 0.0\n"
            "for i, r in enumerate(ratio, start=1):\n"
            "    cum += r\n"
            "    print(f'  PC{i}: {r:.4f}   누적 {cum:.4f}')\n"
            "\n"
            "print('\\n-- PC1 의 구성 (각 특성이 얼마나 기여하나) --')\n"
            "for nm, v in zip(names, vecs[:, 0]):\n"
            "    print(f'  {nm:5s} {v:+.3f}')\n"
            "print('  → 키·몸무게·신발이 함께 움직이는 \"체격\" 축이다')\n"
            "\n"
            "print('\\n-- PC2 의 구성 --')\n"
            "for nm, v in zip(names, vecs[:, 1]):\n"
            "    print(f'  {nm:5s} {v:+.3f}')\n"
            "print('  → 잡음 특성이 따로 떨어져 나온다')\n"
            "\n"
            "# 2차원으로 줄였다가 복원해서 손실 확인\n"
            "print('\\n-- 차원 축소 후 복원 오차 --')\n"
            "for k in [1, 2, 3, 4]:\n"
            "    Z = Xc @ vecs[:, :k]\n"
            "    back = Z @ vecs[:, :k].T\n"
            "    err = float(np.sqrt(((Xc - back) ** 2).mean()))\n"
            "    print(f'  {4}차원 → {k}차원 → 복원 :  평균오차 {err:.4f}'\n"
            "          f'   (정보 {ratio[:k].sum():.1%} 유지)')\n"
            "\n"
            "Z2 = Xc @ vecs[:, :2]\n"
            "print(f'\\n2차원으로 줄인 결과 모양: {Z2.shape}  (앞 3개)')\n"
            "print(np.round(Z2[:3], 3))\n"
        ),
    ),

    Lesson(
        id="ds3-12-workflow",
        lang="datasci", level=STAGE,
        title="회귀 평가지표 · 전체 워크플로",
        summary="MSE·RMSE·MAE·R² · 데이터 누수 없이 파이프라인 짜기",
        explanation=(
            "[개요]\n"
            "3단계의 마무리로, 지금까지 배운 것을 하나의 흐름으로 잇는다.\n"
            "그리고 회귀 문제의 평가지표를 정리한다.\n"
            "\n"
            "[회귀 평가지표]\n"
            "  MSE  = 평균( (실제-예측)² )       큰 오차에 큰 벌점. 단위가 제곱이라 해석이 어렵다.\n"
            "  RMSE = √MSE                      원래 단위로 돌아온다. 가장 많이 쓴다.\n"
            "  MAE  = 평균( |실제-예측| )        이상치에 덜 민감하다.\n"
            "  R²   = 1 - SS_res/SS_tot         '평균으로 찍기'보다 얼마나 나은가. 1 이 만점.\n"
            "\n"
            "  R² 읽는 법\n"
            "    1.0  완벽\n"
            "    0.7  분산의 70% 를 설명\n"
            "    0.0  평균으로 찍는 것과 똑같음\n"
            "    음수 평균으로 찍느니만 못함 (모델이 잘못됐다는 확실한 신호)\n"
            "\n"
            "  RMSE 와 MAE 중 무엇을 볼지는 목적이 정한다.\n"
            "  큰 실수를 절대 하면 안 되는 문제면 RMSE, 이상치가 많으면 MAE 다.\n"
            "\n"
            "[데이터 누수(leakage) — 가장 흔하고 치명적인 실수]\n"
            "  전처리를 **전체 데이터로 먼저** 하면, 검증 데이터의 정보가 훈련에 새어든다.\n"
            "\n"
            "    ❌ 잘못  : 전체를 표준화 → 그 다음 분할\n"
            "    ✅ 올바름: 분할 → 훈련의 평균·표준편차 계산 → 그 값으로 검증도 변환\n"
            "\n"
            "  표준화에 쓰인 평균에 이미 검증 데이터가 섞였기 때문이다.\n"
            "  성능이 실제보다 좋게 나오고, 배포하면 무너진다.\n"
            "\n"
            "[어떤 전처리가 특히 위험한가]\n"
            "  누수의 파괴력은 전처리 종류에 따라 크게 다르다.\n"
            "\n"
            "    표준화        : 선형 모델에서는 사실상 차이가 없다.\n"
            "                    (평균을 빼고 나누는 선형 변환이라 계수가 그만큼 보정된다)\n"
            "                    그래도 습관은 지켜야 한다. 트리·거리 기반에서는 영향이 생긴다.\n"
            "    결측치 대체    : 중간 정도. 검증 데이터의 분포가 훈련에 스며든다.\n"
            "    **특성 선택**  : 치명적. 없는 성능을 만들어낸다.\n"
            "\n"
            "  아래 코드는 가장 위험한 특성 선택으로 실험한다.\n"
            "  **y 와 아무 관계도 없는 순수 난수 특성 400개**를 만들어 놓고,\n"
            "  전체 데이터에서 'y 와 상관이 높은 10개'를 골라 학습시킨다.\n"
            "  결과는 검증 R² 가 +0.24 — '분산의 24% 를 설명한다'는 그럴듯한 숫자가 나온다.\n"
            "  전부 가짜다. 400개를 뒤지면 우연히 상관이 높아 보이는 것이 반드시 나오고,\n"
            "  그 '우연'을 검증 데이터까지 보고 골랐기 때문이다.\n"
            "  훈련 데이터에서만 고르면 R² 가 음수로 나와 '쓸모없다'고 정직하게 알려준다.\n"
            "\n"
            "[표준 워크플로]\n"
            "  1) 분할        train / test 로 먼저 나눈다. 무조건 첫 단계다.\n"
            "  2) 전처리 학습 훈련 데이터에서만 평균·표준편차를 구한다\n"
            "  3) 변환        같은 값으로 훈련·시험 모두 변환\n"
            "  4) 학습        훈련 데이터로만 모델을 만든다\n"
            "  5) 평가        시험 데이터로 딱 한 번 측정\n"
            "\n"
            "[코드 분석]\n"
            "  mu, sd = X[tr].mean(axis=0), X[tr].std(axis=0)\n"
            "         → **훈련 부분만으로** 통계를 계산한다. 이게 핵심이다.\n"
            "  Xs = (X - mu) / sd\n"
            "         → 훈련에서 얻은 값으로 전체를 변환한다.\n"
            "            시험 데이터의 평균이 0 이 아니어도 정상이다. 그게 맞는 것이다.\n"
            "  ss_res = ((y - pred) ** 2).sum()\n"
            "  ss_tot = ((y - y.mean()) ** 2).sum()\n"
            "  r2 = 1 - ss_res / ss_tot\n"
            "         → R² 정의 그대로. ss_tot 은 '평균으로만 찍었을 때의 오차'다.\n"
            "  기준선(baseline) 비교\n"
            "         → 무조건 평균으로 찍는 모델의 성능을 함께 낸다.\n"
            "            모델이 이걸 못 이기면 쓸 이유가 없다. 항상 기준선을 먼저 재자.\n"
            "  np.ix_(rtr, sel)\n"
            "         → 행 목록과 열 목록으로 부분 행렬을 뽑는다.\n"
            "            RX[rtr, sel] 이라고 쓰면 짝을 지어 원소만 골라내므로 결과가 다르다.\n"
            "            행·열을 각각 지정할 때는 np.ix_ 를 써야 한다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 시험 데이터는 최종 보고 때 딱 한 번만 쓴다. 여러 번 보면 그것도 검증셋이 된다.\n"
            "  • R² 는 특성을 추가하면 무조건 올라간다. 쓸모없는 특성을 넣어도 오른다.\n"
            "    특성 수를 보정한 '조정 R²' 를 함께 보는 게 정확하다.\n"
            "  • 평가지표 하나만 보지 말자. RMSE 와 R² 를 함께 보면 그림이 명확해진다."
        ),
        usage="3단계의 총정리. 실제 회귀 프로젝트는 이 순서 그대로 진행된다.",
        cons="지표는 모델의 '평균적' 성능만 말한다. 어떤 구간에서 크게 틀리는지는 잔차를 따로 봐야 한다.",
        code=(
            "import numpy as np\n"
            "\n"
            "rng = np.random.default_rng(42)\n"
            "n = 300\n"
            "\n"
            "area = rng.uniform(10, 40, n)\n"
            "rooms = rng.integers(1, 5, n).astype(float)\n"
            "dist = rng.uniform(0.1, 3.0, n)\n"
            "y = 1.5 * area + 3.0 * rooms - 5.0 * dist + 10.0 + rng.normal(0, 3, n)\n"
            "X = np.column_stack([area, rooms, dist])\n"
            "\n"
            "# ---- 1) 분할이 가장 먼저 ----\n"
            "idx = rng.permutation(n)\n"
            "tr, te = idx[:210], idx[210:]\n"
            "print(f'훈련 {len(tr)}건 · 시험 {len(te)}건')\n"
            "\n"
            "# ---- 2~3) 훈련 데이터로만 전처리 기준 계산 ----\n"
            "mu, sd = X[tr].mean(axis=0), X[tr].std(axis=0)\n"
            "Xs = (X - mu) / sd\n"
            "print(f'훈련 평균(표준화 후): {Xs[tr].mean(axis=0).round(6) + 0.0}  ← 0 이 맞다')\n"
            "print(f'시험 평균(표준화 후): {Xs[te].mean(axis=0).round(3)}  ← 0 이 아닌 게 정상')\n"
            "\n"
            "# ---- 4) 학습 ----\n"
            "A = np.column_stack([np.ones(len(tr)), Xs[tr]])\n"
            "theta = np.linalg.solve(A.T @ A, A.T @ y[tr])\n"
            "\n"
            "def predict(part):\n"
            "    P = np.column_stack([np.ones(len(part)), Xs[part]])\n"
            "    return P @ theta\n"
            "\n"
            "# ---- 5) 평가 ----\n"
            "def report(name, part):\n"
            "    pred = predict(part)\n"
            "    true = y[part]\n"
            "    mse = float(((true - pred) ** 2).mean())\n"
            "    mae = float(np.abs(true - pred).mean())\n"
            "    ss_res = float(((true - pred) ** 2).sum())\n"
            "    ss_tot = float(((true - true.mean()) ** 2).sum())\n"
            "    r2 = 1 - ss_res / ss_tot\n"
            "    print(f'  {name}  MSE {mse:7.3f} · RMSE {np.sqrt(mse):6.3f} · '\n"
            "          f'MAE {mae:6.3f} · R² {r2:.4f}')\n"
            "\n"
            "print('\\n-- 성능 --')\n"
            "report('훈련', tr)\n"
            "report('시험', te)\n"
            "\n"
            "# 기준선: 무조건 훈련 평균으로 찍기\n"
            "base = y[tr].mean()\n"
            "b_rmse = float(np.sqrt(((y[te] - base) ** 2).mean()))\n"
            "print(f'\\n  기준선(평균으로 찍기) RMSE {b_rmse:.3f} · R² 0.0000')\n"
            "print('  → 모델이 기준선을 크게 이겨야 의미가 있다')\n"
            "print('\\n※ 여기서는 시험 성능이 훈련보다 살짝 좋게 나왔다.')\n"
            "print('  과적합이 없고 시험 데이터가 우연히 쉬웠을 때 생기는 정상적인 현상이다.')\n"
            "print('  보통은 훈련 쪽이 조금 더 좋다.')\n"
            "\n"
            "# ---- 데이터 누수가 성능을 얼마나 속이는가 ----\n"
            "print('\\n' + '=' * 58)\n"
            "print('데이터 누수 실험 — 특성 선택을 어디서 하느냐')\n"
            "print('=' * 58)\n"
            "\n"
            "r2rng = np.random.default_rng(0)\n"
            "m, p = 120, 400\n"
            "# 특성 400개 전부 순수 난수. y 와 아무 관계도 없다.\n"
            "RX = r2rng.normal(0, 1, (m, p))\n"
            "ry = r2rng.normal(0, 1, m)\n"
            "ridx = r2rng.permutation(m)\n"
            "rtr, rte = ridx[:80], ridx[80:]\n"
            "\n"
            "def r2(true, pred):\n"
            "    return float(1 - ((true - pred) ** 2).sum() / ((true - true.mean()) ** 2).sum())\n"
            "\n"
            "def fit_eval(sel):\n"
            "    A = np.column_stack([np.ones(len(rtr)), RX[np.ix_(rtr, sel)]])\n"
            "    w = np.linalg.lstsq(A, ry[rtr], rcond=None)[0]\n"
            "    P = np.column_stack([np.ones(len(rte)), RX[np.ix_(rte, sel)]])\n"
            "    return r2(ry[rtr], A @ w), r2(ry[rte], P @ w)\n"
            "\n"
            "# ❌ 전체 데이터에서 y 와 상관 높은 특성 10개 고르기\n"
            "c_all = np.array([abs(np.corrcoef(RX[:, j], ry)[0, 1]) for j in range(p)])\n"
            "leak_tr, leak_te = fit_eval(np.argsort(c_all)[::-1][:10])\n"
            "\n"
            "# ✅ 훈련 데이터에서만 고르기\n"
            "c_tr = np.array([abs(np.corrcoef(RX[rtr, j], ry[rtr])[0, 1]) for j in range(p)])\n"
            "ok_tr, ok_te = fit_eval(np.argsort(c_tr)[::-1][:10])\n"
            "\n"
            "print('진실: 특성 400개는 전부 난수다. y 와 아무 관계도 없다.')\n"
            "print('      따라서 정직한 검증 R² 는 0 이하여야 한다.\\n')\n"
            "print(f'  ❌ 누수 (전체로 특성선택)   훈련 R² {leak_tr:6.3f}   검증 R² {leak_te:+.3f}')\n"
            "print(f'  ✅ 올바름 (훈련만으로 선택)  훈련 R² {ok_tr:6.3f}   검증 R² {ok_te:+.3f}')\n"
            "print()\n"
            "print('  누수 쪽은 \"분산의 24% 를 설명한다\" 는 그럴듯한 결과를 낸다. 전부 가짜다.')\n"
            "print('  검증 데이터를 보고 특성을 골랐으니, 그 검증 점수는 이미 오염됐다.')\n"
            "print('  올바른 쪽은 음수 R² 로 \"이 특성들은 쓸모없다\" 고 정직하게 말해준다.')\n"
            "print('\\n  특성 선택·결측치 대체·이상치 제거는 반드시 훈련 데이터 안에서만 하자.')\n"
        ),
    ),
]
