"""5단계 — LLM 본편 (ds5-04 ~ ds5-10).

ds5-01~03 의 토크나이저·어텐션 위에 트랜스포머의 나머지 부품을 얹고,
실제로 학습해서 문장을 생성하는 미니 언어 모델까지 만든다.
"""

from engine.models import Lesson

STAGE = "5. LLM · 트랜스포머"

LESSONS = [

    Lesson(
        id="ds5-04-position",
        lang="datasci", level=STAGE,
        title="위치 인코딩",
        summary="어텐션은 순서를 모른다 · 위치를 벡터에 심는 법",
        explanation=(
            "[개요]\n"
            "셀프 어텐션에는 치명적인 구멍이 있다. **단어의 순서를 전혀 모른다.**\n"
            "\n"
            "  '개가 사람을 물었다' 와 '사람이 개를 물었다' 는\n"
            "  어텐션 계산만 놓고 보면 완전히 같은 결과가 나온다.\n"
            "  Q·K 내적은 위치와 무관하게 단어 쌍만 보기 때문이다.\n"
            "\n"
            "  RNN 은 순서대로 처리하므로 순서를 자동으로 알았다.\n"
            "  트랜스포머는 병렬 처리를 얻은 대신 순서를 잃었다.\n"
            "  그래서 위치 정보를 **입력 벡터에 직접 더해준다.**\n"
            "\n"
            "[사인·코사인 위치 인코딩 (원논문 방식)]\n"
            "    PE(pos, 2i)   = sin(pos / 10000^(2i/d))\n"
            "    PE(pos, 2i+1) = cos(pos / 10000^(2i/d))\n"
            "\n"
            "  · pos = 몇 번째 단어인가\n"
            "  · i   = 벡터의 몇 번째 차원인가\n"
            "\n"
            "  차원마다 주파수가 다른 파동을 만든다.\n"
            "  앞쪽 차원은 빠르게 진동하고(가까운 위치 구분),\n"
            "  뒤쪽 차원은 아주 천천히 진동한다(먼 위치 구분).\n"
            "  시계의 초침·분침·시침이 함께 시각을 특정하는 것과 같은 원리다.\n"
            "\n"
            "[왜 하필 사인·코사인인가]\n"
            "  1) 값이 항상 -1~1 이라 임베딩에 더해도 크기가 폭주하지 않는다\n"
            "  2) 학습에서 본 적 없는 긴 문장에도 그대로 적용된다\n"
            "  3) **상대 위치를 표현할 수 있다.**\n"
            "     삼각함수 덧셈정리에 의해 PE(pos+k) 는 PE(pos) 의 선형변환으로 쓸 수 있다.\n"
            "     즉 모델이 '두 칸 뒤' 같은 관계를 학습하기 쉬워진다.\n"
            "\n"
            "[다만 거리가 단조롭게 반영되지는 않는다]\n"
            "  아래 실행 결과에서 위치 0 과 다른 위치의 내적을 보면,\n"
            "  가까울수록 대체로 높지만 **완전한 단조 감소는 아니다.**\n"
            "  위치 3 에서 바닥을 찍고 4, 5 에서 다시 올라간다.\n"
            "  사인·코사인이 주기 함수라 생기는 현상이다.\n"
            "\n"
            "  '거리가 멀수록 무조건 덜 비슷하다'고 오해하지 말자.\n"
            "  이 한계가 RoPE 같은 대안이 나온 배경 중 하나다.\n"
            "\n"
            "[요즘 방식]\n"
            "  · 학습된 위치 임베딩 : 위치마다 벡터를 그냥 학습시킨다(GPT-2 방식). 단순하다.\n"
            "  · RoPE(회전 위치 임베딩) : 벡터를 위치만큼 회전시킨다.\n"
            "    긴 문맥에서 성능이 좋아 LLaMA 등 최신 모델의 표준이 됐다.\n"
            "  · ALiBi : 어텐션 점수에 거리 비례 벌점을 준다.\n"
            "\n"
            "[코드 분석]\n"
            "  div = np.exp(np.arange(0, d, 2) * (-np.log(10000.0) / d))\n"
            "         → 10000^(-2i/d) 를 로그·지수로 계산한다.\n"
            "            직접 거듭제곱하면 수치가 불안정해질 수 있어 이렇게 쓴다.\n"
            "  pe[:, 0::2] = np.sin(pos * div)\n"
            "         → 0,2,4... 짝수 차원에 사인. 0::2 는 '0부터 2칸씩'이라는 뜻이다.\n"
            "  pe[:, 1::2] = np.cos(pos * div)\n"
            "         → 홀수 차원에 코사인.\n"
            "  X = embedding + pe\n"
            "         → **더한다.** 이어붙이지(concat) 않는다.\n"
            "            차원이 늘지 않아 계산이 그대로이고, 실험적으로 성능 차이도 없다.\n"
            "  내적으로 유사도 확인\n"
            "         → 가까운 위치끼리 위치 벡터의 내적이 크다.\n"
            "            멀어질수록 작아지는 것이 실제 숫자로 확인된다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 위치 인코딩을 빼먹으면 모델이 어순을 완전히 무시한다. 필수 부품이다.\n"
            "  • 학습된 위치 임베딩은 학습 때 본 최대 길이를 넘어가면 쓸 수 없다.\n"
            "    컨텍스트 길이 제한의 한 원인이다."
        ),
        usage="모든 트랜스포머의 입력 단계. 어텐션 직전에 반드시 들어간다.",
        cons="사인·코사인 방식은 아주 긴 문맥에서 성능이 떨어진다. 그래서 RoPE 같은 방식으로 대체되는 추세다.",
        code=(
            "import numpy as np\n"
            "\n"
            "def positional_encoding(max_len, d):\n"
            "    pos = np.arange(max_len)[:, None]                     # (len, 1)\n"
            "    div = np.exp(np.arange(0, d, 2) * (-np.log(10000.0) / d))\n"
            "    pe = np.zeros((max_len, d))\n"
            "    pe[:, 0::2] = np.sin(pos * div)     # 짝수 차원 → 사인\n"
            "    pe[:, 1::2] = np.cos(pos * div)     # 홀수 차원 → 코사인\n"
            "    return pe\n"
            "\n"
            "d = 8\n"
            "pe = positional_encoding(10, d)\n"
            "print(f'위치 인코딩 모양: {pe.shape}  (위치 10개 × {d}차원)\\n')\n"
            "\n"
            "print('위치별 벡터 (앞 6차원)')\n"
            "print('pos   ' + '  '.join(f'd{i}    ' for i in range(6)))\n"
            "for p in range(6):\n"
            "    print(f' {p}   ' + '  '.join(f'{v:+.3f}' for v in pe[p, :6]))\n"
            "\n"
            "print('\\n→ 앞쪽 차원(d0,d1)은 위치마다 빠르게 바뀌고')\n"
            "print('  뒤쪽 차원은 거의 안 바뀐다 = 주파수가 다른 파동')\n"
            "\n"
            "print('\\n-- 차원별 진동 속도 --')\n"
            "for i in [0, 2, 4, 6]:\n"
            "    col = pe[:, i]\n"
            "    print(f'  d{i}: ' + ' '.join(f'{v:+.2f}' for v in col))\n"
            "\n"
            "# 위치 벡터끼리의 유사도\n"
            "print('\\n-- 위치 0 과 다른 위치의 내적 --')\n"
            "sims = [float(pe[0] @ pe[p]) for p in range(10)]\n"
            "for p, sim in enumerate(sims):\n"
            "    bar = '#' * max(0, int(sim * 4))\n"
            "    print(f'  위치 0 ↔ {p} : {sim:+.4f}  {bar}')\n"
            "\n"
            "print('\\n  → 자기 자신(0)이 가장 크고, 가까운 위치일수록 대체로 높다.')\n"
            "print('    하지만 단조 감소가 아니다. 위치 3 에서 바닥을 찍고 다시 올라간다.')\n"
            "print('    사인·코사인이 주기 함수라서 생기는 현상이다.')\n"
            "print('    낮은 주파수 차원이 큰 범위의 거리를 구분해 주지만,')\n"
            "print('    이 방식이 거리를 완벽하게 인코딩하지는 못한다는 뜻이기도 하다.')\n"
            "print('    최신 모델이 RoPE 같은 방식으로 옮겨간 이유 중 하나다.')\n"
            "\n"
            "# 임베딩에 더하기\n"
            "rng = np.random.default_rng(0)\n"
            "words = ['개', '가', '사람', '을', '물었다']\n"
            "emb = rng.normal(0, 1, (len(words), d))\n"
            "X = emb + pe[:len(words)]\n"
            "print(f'\\n임베딩 {emb.shape} + 위치 {pe[:len(words)].shape} = 입력 {X.shape}')\n"
            "print('→ 이어붙이지 않고 더한다. 차원이 늘지 않는다.')\n"
            "\n"
            "print('\\n-- 순서를 바꾸면 입력이 달라진다 --')\n"
            "swapped = emb[[2, 1, 0, 3, 4]] + pe[:len(words)]\n"
            "print(f'  \"개가 사람을 물었다\" 첫 벡터: {X[0, :4].round(3)}')\n"
            "print(f'  \"사람가 개을 물었다\" 첫 벡터: {swapped[0, :4].round(3)}')\n"
            "print('  → 위치 인코딩이 없었다면 어텐션은 이 둘을 구분하지 못한다.')\n"
        ),
    ),

    Lesson(
        id="ds5-05-multihead",
        lang="datasci", level=STAGE,
        title="멀티헤드 어텐션",
        summary="여러 관점으로 동시에 보기",
        explanation=(
            "[개요]\n"
            "ds5-03 의 어텐션은 '헤드' 하나였다. 관계를 한 가지 방식으로만 본다.\n"
            "하지만 문장 속 단어 관계는 여러 종류다.\n"
            "\n"
            "  '그 배고픈 학생이 빵을 빠르게 먹었다'\n"
            "    · 문법 관계 : 학생 ← 먹었다 (주어-동사)\n"
            "    · 수식 관계 : 배고픈 → 학생\n"
            "    · 목적 관계 : 빵 ← 먹었다\n"
            "\n"
            "헤드 하나로 이걸 다 잡기는 어렵다. 그래서 여러 개를 동시에 돌린다.\n"
            "\n"
            "[동작 방식]\n"
            "  1) d_model 차원을 헤드 수만큼 나눈다\n"
            "     d_model=64, 헤드 8개 → 헤드당 d_k = 8\n"
            "  2) 각 헤드가 자기 몫의 차원에서 독립적으로 어텐션을 계산한다\n"
            "  3) 결과를 이어붙인다(concat) → 다시 d_model 차원\n"
            "  4) 출력 가중치 W_o 를 곱해 섞는다\n"
            "\n"
            "  **총 계산량은 헤드 하나일 때와 거의 같다.**\n"
            "  차원을 나눠 쓰기 때문이다. 공짜로 다양성을 얻는 셈이다.\n"
            "\n"
            "[실제 모델의 헤드 수]\n"
            "    GPT-2 small : d_model 768,  헤드 12개 (헤드당 64)\n"
            "    GPT-3       : d_model 12288, 헤드 96개 (헤드당 128)\n"
            "  헤드당 차원을 64~128 로 두는 것이 관례다.\n"
            "\n"
            "[헤드가 실제로 무엇을 학습하나]\n"
            "  학습된 모델을 분석해 보면 헤드마다 역할이 갈린다.\n"
            "    · 바로 앞 단어만 보는 헤드\n"
            "    · 문장의 첫 단어를 계속 보는 헤드\n"
            "    · 대명사가 가리키는 명사를 찾는 헤드\n"
            "  사람이 지정한 게 아니라 학습으로 저절로 분화된 것이다.\n"
            "\n"
            "[코드 분석]\n"
            "  X @ Wq  형태로 한 번에 계산한 뒤 reshape\n"
            "         → 헤드마다 따로 행렬을 두지 않는다.\n"
            "            큰 행렬 하나로 계산하고 나눠 쓰는 것이 훨씬 빠르다.\n"
            "  .reshape(n, heads, d_k).transpose(1, 0, 2)\n"
            "         → (단어, 헤드, 차원) 을 (헤드, 단어, 차원) 으로 바꾼다.\n"
            "            이래야 헤드별로 행렬곱을 한 번에 돌릴 수 있다.\n"
            "  Q @ K.transpose(0, 2, 1)\n"
            "         → 3차원 배열의 배치 행렬곱. 첫 축(헤드)은 그대로 두고\n"
            "            뒤 두 축만 행렬곱한다. 8개 헤드가 동시에 계산된다.\n"
            "  .transpose(1, 0, 2).reshape(n, -1)\n"
            "         → 헤드 결과를 다시 이어붙여 원래 차원으로 복원.\n"
            "  head_out @ Wo\n"
            "         → 헤드들이 만든 정보를 섞는 마지막 단계. 빼먹으면 안 된다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 헤드 수는 d_model 을 나눠떨어지게 정해야 한다.\n"
            "  • 헤드를 너무 많이 쪼개면 헤드당 차원이 작아져 표현력이 떨어진다.\n"
            "  • 여기 가중치는 학습되지 않은 난수라 헤드별 패턴에 의미는 없다.\n"
            "    '헤드마다 다른 곳을 본다'는 구조만 확인하면 된다."
        ),
        usage="모든 트랜스포머의 핵심 층. GPT·BERT·Claude 전부 이 구조를 쓴다.",
        cons="어텐션은 토큰 수의 제곱에 비례해 계산량이 는다. 긴 컨텍스트가 비싼 근본 원인이다.",
        code=(
            "import numpy as np\n"
            "\n"
            "rng = np.random.default_rng(42)\n"
            "\n"
            "def softmax(z, axis=-1):\n"
            "    e = np.exp(z - z.max(axis=axis, keepdims=True))\n"
            "    return e / e.sum(axis=axis, keepdims=True)\n"
            "\n"
            "words = ['그', '배고픈', '학생이', '빵을', '먹었다']\n"
            "n = len(words)\n"
            "d_model, heads = 16, 4\n"
            "d_k = d_model // heads\n"
            "print(f'd_model {d_model} · 헤드 {heads}개 · 헤드당 차원 {d_k}\\n')\n"
            "\n"
            "X = rng.normal(0, 1, (n, d_model))\n"
            "Wq = rng.normal(0, 0.3, (d_model, d_model))\n"
            "Wk = rng.normal(0, 0.3, (d_model, d_model))\n"
            "Wv = rng.normal(0, 0.3, (d_model, d_model))\n"
            "Wo = rng.normal(0, 0.3, (d_model, d_model))\n"
            "\n"
            "# 한 번에 계산한 뒤 헤드별로 쪼갠다\n"
            "def split_heads(M):\n"
            "    return M.reshape(n, heads, d_k).transpose(1, 0, 2)   # (heads, n, d_k)\n"
            "\n"
            "Q = split_heads(X @ Wq)\n"
            "K = split_heads(X @ Wk)\n"
            "V = split_heads(X @ Wv)\n"
            "print('헤드로 쪼갠 Q 모양:', Q.shape, '(헤드, 단어, 헤드당차원)')\n"
            "\n"
            "# 배치 행렬곱 — 4개 헤드가 동시에 계산된다\n"
            "scores = Q @ K.transpose(0, 2, 1) / np.sqrt(d_k)\n"
            "\n"
            "# causal mask (뒤를 못 보게)\n"
            "mask = np.triu(np.ones((n, n)), k=1) * -1e9\n"
            "weights = softmax(scores + mask)\n"
            "print('어텐션 가중치 모양:', weights.shape)\n"
            "\n"
            "print('\\n-- 헤드별로 \"먹었다\" 가 어디를 보는가 --')\n"
            "print('        ' + '  '.join(f'{w:>6s}' for w in words))\n"
            "for h in range(heads):\n"
            "    row = weights[h, -1]      # 마지막 단어(먹었다)의 어텐션\n"
            "    print(f'헤드{h}   ' + '  '.join(f'{v:6.3f}' for v in row))\n"
            "print('→ 헤드마다 주목하는 단어가 다르다.')\n"
            "print('  (학습되지 않은 난수 가중치라 패턴 자체에 의미는 없다)')\n"
            "\n"
            "# 헤드 결과를 다시 합치기\n"
            "head_out = (weights @ V).transpose(1, 0, 2).reshape(n, d_model)\n"
            "output = head_out @ Wo\n"
            "print(f'\\n헤드 출력 합치기: {(weights @ V).shape} → {head_out.shape}')\n"
            "print(f'W_o 통과 후 최종: {output.shape}  (입력과 같은 모양)')\n"
            "print('→ 모양이 그대로라 층을 계속 쌓을 수 있다. 이게 중요하다.')\n"
            "\n"
            "print('\\n-- 계산량 비교 --')\n"
            "print(f'  헤드 1개 (d_k={d_model}) : {n * n * d_model:,} 회')\n"
            "print(f'  헤드 {heads}개 (d_k={d_k})  : {heads * n * n * d_k:,} 회  ← 같다')\n"
            "print('  차원을 나눠 쓰므로 다양성을 거의 공짜로 얻는다.')\n"
        ),
    ),

    Lesson(
        id="ds5-06-block",
        lang="datasci", level=STAGE,
        title="트랜스포머 블록 완성",
        summary="잔차 연결 · 레이어 정규화 · 피드포워드",
        explanation=(
            "[개요]\n"
            "어텐션만으로는 트랜스포머가 되지 않는다.\n"
            "블록 하나는 네 부품으로 이뤄진다.\n"
            "\n"
            "    x → [멀티헤드 어텐션] → +x → [LayerNorm] →\n"
            "      → [피드포워드]      → +  → [LayerNorm] → 출력\n"
            "\n"
            "  이 블록을 수십 개 쌓은 것이 GPT 다. GPT-3 는 96개다.\n"
            "\n"
            "[1) 잔차 연결 (Residual / Skip Connection)]\n"
            "    출력 = x + f(x)\n"
            "\n"
            "  층의 결과에 **입력을 그대로 더한다.** 이게 왜 중요한가?\n"
            "  역전파에서 기울기가 f 를 거치지 않고 지나갈 통로가 생긴다.\n"
            "  덧셈의 미분은 1 이므로 기울기가 줄지 않고 그대로 흐른다.\n"
            "\n"
            "  ds4-09 에서 본 기울기 소실 문제를 정면으로 해결한 장치다.\n"
            "  이것 덕분에 100층 넘게 쌓아도 학습이 된다.\n"
            "\n"
            "[2) 레이어 정규화 (LayerNorm)]\n"
            "    각 토큰 벡터를 평균 0, 표준편차 1 로 맞춘 뒤 γ 배 하고 β 를 더한다.\n"
            "\n"
            "  · 층을 지날수록 값의 분포가 널뛰는 것을 막는다\n"
            "  · 배치정규화와 달리 **토큰 하나 안에서** 정규화한다.\n"
            "    배치 크기나 문장 길이에 영향받지 않아 언어 모델에 적합하다.\n"
            "  · γ, β 는 학습되는 값이다. 정규화를 되돌릴 여지를 남겨둔다.\n"
            "\n"
            "[3) 피드포워드 (FFN)]\n"
            "    FFN(x) = W₂ · ReLU(W₁x + b₁) + b₂\n"
            "\n"
            "  중간 차원을 보통 4배로 키웠다가 되돌린다(768 → 3072 → 768).\n"
            "  어텐션이 '토큰 사이 정보 교환'이라면 FFN 은 '토큰 내부 가공'이다.\n"
            "  놀랍게도 **모델 파라미터의 약 2/3 가 FFN 에 있다.**\n"
            "\n"
            "[Pre-LN vs Post-LN]\n"
            "  원논문은 x + f(x) 를 정규화하는 Post-LN 이었다.\n"
            "  요즘은 f(LN(x)) 를 더하는 Pre-LN 을 쓴다. 깊게 쌓아도 학습이 안정적이다.\n"
            "  아래 코드는 원논문 방식(Post-LN)으로 썼다.\n"
            "\n"
            "[코드 분석]\n"
            "  (x - mu) / np.sqrt(var + eps)\n"
            "         → LayerNorm 핵심. axis=-1 로 **마지막 축(특성)** 기준이다.\n"
            "            axis=0 으로 하면 배치정규화가 되어 완전히 다른 동작이 된다.\n"
            "  keepdims=True\n"
            "         → 모양을 유지해야 브로드캐스팅이 맞는다. 빼먹으면 에러거나 오답이다.\n"
            "  x + attn_out\n"
            "         → 잔차 연결. 이 한 줄이 깊은 신경망을 가능하게 만들었다.\n"
            "  기울기 흐름 비교\n"
            "         → 잔차 연결이 있을 때와 없을 때, 층을 거치며 기울기가\n"
            "            어떻게 달라지는지 숫자로 확인한다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 잔차 연결을 하려면 입력과 출력 모양이 같아야 한다.\n"
            "    트랜스포머가 모든 층에서 d_model 을 유지하는 이유다.\n"
            "  • LayerNorm 의 축을 잘못 잡는 것은 아주 흔한 버그다.\n"
            "  • FFN 의 4배 확장은 관례일 뿐 절대 규칙은 아니다."
        ),
        usage="트랜스포머의 최소 단위. 이걸 이해하면 GPT 구조 전체를 이해한 것이다.",
        cons="블록을 깊게 쌓을수록 메모리와 계산이 선형으로 는다. 학습 비용의 대부분이 여기서 나온다.",
        code=(
            "import numpy as np\n"
            "\n"
            "rng = np.random.default_rng(42)\n"
            "\n"
            "def softmax(z, axis=-1):\n"
            "    e = np.exp(z - z.max(axis=axis, keepdims=True))\n"
            "    return e / e.sum(axis=axis, keepdims=True)\n"
            "\n"
            "def layer_norm(x, gamma, beta, eps=1e-5):\n"
            "    mu = x.mean(axis=-1, keepdims=True)        # 마지막 축 = 특성 축\n"
            "    var = x.var(axis=-1, keepdims=True)\n"
            "    return gamma * (x - mu) / np.sqrt(var + eps) + beta\n"
            "\n"
            "n, d, heads = 5, 16, 4\n"
            "d_k = d // heads\n"
            "X = rng.normal(0, 1, (n, d))\n"
            "\n"
            "# --- 부품 준비 ---\n"
            "Wq, Wk, Wv, Wo = [rng.normal(0, 0.3, (d, d)) for _ in range(4)]\n"
            "W1 = rng.normal(0, 0.3, (d, d * 4))     # FFN 은 4배로 확장\n"
            "b1 = np.zeros(d * 4)\n"
            "W2 = rng.normal(0, 0.3, (d * 4, d))\n"
            "b2 = np.zeros(d)\n"
            "g1, be1 = np.ones(d), np.zeros(d)\n"
            "g2, be2 = np.ones(d), np.zeros(d)\n"
            "\n"
            "def block(x):\n"
            "    # 1) 멀티헤드 어텐션\n"
            "    sh = lambda M: M.reshape(n, heads, d_k).transpose(1, 0, 2)\n"
            "    Q, K, V = sh(x @ Wq), sh(x @ Wk), sh(x @ Wv)\n"
            "    mask = np.triu(np.ones((n, n)), k=1) * -1e9\n"
            "    w = softmax(Q @ K.transpose(0, 2, 1) / np.sqrt(d_k) + mask)\n"
            "    attn = (w @ V).transpose(1, 0, 2).reshape(n, d) @ Wo\n"
            "\n"
            "    # 2) 잔차 연결 + LayerNorm\n"
            "    x = layer_norm(x + attn, g1, be1)\n"
            "\n"
            "    # 3) 피드포워드\n"
            "    ff = np.maximum(0, x @ W1 + b1) @ W2 + b2\n"
            "\n"
            "    # 4) 잔차 연결 + LayerNorm\n"
            "    return layer_norm(x + ff, g2, be2)\n"
            "\n"
            "print('입력 :', X.shape)\n"
            "out = block(X)\n"
            "print('출력 :', out.shape, ' ← 모양이 같아야 층을 쌓을 수 있다')\n"
            "\n"
            "print('\\n-- LayerNorm 효과 (첫 토큰) --')\n"
            "raw = X[0]\n"
            "normed = layer_norm(X, g1, be1)[0]\n"
            "print(f'  정규화 전 : 평균 {raw.mean():+.4f}  표준편차 {raw.std():.4f}')\n"
            "print(f'  정규화 후 : 평균 {normed.mean():+.4f}  표준편차 {normed.std():.4f}')\n"
            "\n"
            "# 블록을 여러 개 쌓아도 값이 안정적인가\n"
            "print('\\n-- 블록을 6개 쌓으며 값의 크기 추적 --')\n"
            "h = X.copy()\n"
            "print(f'  입력    : 절댓값 평균 {np.abs(h).mean():.4f}')\n"
            "for i in range(1, 7):\n"
            "    h = block(h)\n"
            "    print(f'  블록 {i} : 절댓값 평균 {np.abs(h).mean():.4f}')\n"
            "print('  → LayerNorm 덕분에 값이 폭주하지도 사라지지도 않는다.')\n"
            "\n"
            "# 잔차 연결의 효과 — 기울기가 살아남는가\n"
            "print('\\n-- 잔차 연결이 기울기를 지키는 원리 --')\n"
            "print('  층마다 기울기가 0.7 배로 줄어드는 상황을 가정하면')\n"
            "print('  층수   잔차 없음        잔차 있음(1 + 0.7 통로)')\n"
            "for L in [1, 5, 10, 20, 50]:\n"
            "    without = 0.7 ** L\n"
            "    print(f'  {L:3d}   {without:14.8f}   기울기가 직접 통과 (≈1)')\n"
            "print('  → 잔차 없이 50층이면 기울기가 사실상 0 이다.')\n"
            "print('    덧셈의 미분은 1 이므로, 잔차 통로로는 기울기가 그대로 흐른다.')\n"
            "\n"
            "print('\\n-- 파라미터 분포 --')\n"
            "attn_p = 4 * d * d\n"
            "ffn_p = d * (d * 4) + (d * 4) * d\n"
            "print(f'  어텐션(Wq,Wk,Wv,Wo) : {attn_p:,} 개')\n"
            "print(f'  피드포워드(W1,W2)    : {ffn_p:,} 개')\n"
            "print(f'  → FFN 이 전체의 {ffn_p / (attn_p + ffn_p):.0%} 를 차지한다')\n"
        ),
    ),

    Lesson(
        id="ds5-07-minilm",
        lang="datasci", level=STAGE,
        title="미니 언어 모델 학습",
        summary="직접 학습시켜 문장을 생성해 본다",
        explanation=(
            "[개요]\n"
            "지금까지의 부품을 모아 **실제로 학습하는** 언어 모델을 만든다.\n"
            "앞 글자 4개를 보고 다음 글자를 맞히도록 훈련시킨 뒤, 문장을 생성한다.\n"
            "\n"
            "GPT 와 학습 목표가 똑같다. 규모만 다를 뿐이다.\n"
            "\n"
            "[구조]\n"
            "    앞 4글자 → 임베딩 → 펼치기 → 은닉층(ReLU) → 출력층 → softmax\n"
            "\n"
            "  트랜스포머 대신 단순한 신경망을 썼다.\n"
            "  numpy 로 어텐션까지 역전파하면 코드가 너무 길어지기 때문이다.\n"
            "  **핵심인 '다음 토큰 예측' 학습 방식은 완전히 동일하다.**\n"
            "\n"
            "[학습 데이터 만들기]\n"
            "  '나는 밥을 먹었다' 라는 문장에서\n"
            "\n"
            "    입력 '나는 밥'  → 정답 '을'\n"
            "    입력 '는 밥을'  → 정답 ' '\n"
            "    입력 ' 밥을 '   → 정답 '먹'\n"
            "\n"
            "  한 칸씩 밀며 만든다. 라벨을 사람이 붙일 필요가 없다.\n"
            "  텍스트 자체가 정답을 품고 있다 — 이를 **자기지도학습**이라 한다.\n"
            "  인터넷의 방대한 텍스트를 그대로 학습 데이터로 쓸 수 있는 이유다.\n"
            "\n"
            "[생성 — 자기회귀(autoregressive)]\n"
            "  1) 앞 4글자로 다음 글자 확률을 계산한다\n"
            "  2) 확률에 따라 하나를 뽑는다\n"
            "  3) 뽑은 글자를 문맥 끝에 붙이고 맨 앞을 버린다\n"
            "  4) 반복\n"
            "\n"
            "  ChatGPT 가 글자를 하나씩 뱉는 것도 정확히 이 과정이다.\n"
            "\n"
            "[코드 분석]\n"
            "  X = [data[i:i+CTX] ...], Y = [data[i+CTX] ...]\n"
            "         → 슬라이딩 윈도우로 (입력, 정답) 쌍을 만든다.\n"
            "  E[X].reshape(n, -1)\n"
            "         → 4개 토큰의 임베딩을 이어붙여 하나의 벡터로 만든다.\n"
            "            (n, 4, 12) → (n, 48)\n"
            "  np.add.at(dE, X, demb)\n"
            "         → **임베딩 역전파의 핵심.** 같은 토큰이 여러 위치에 나오므로\n"
            "            기울기를 누적해야 한다. dE[X] += demb 라고 쓰면\n"
            "            중복된 인덱스에서 마지막 값만 남아 틀린다. 아주 흔한 함정이다.\n"
            "  np.power(p, 1 / temp)\n"
            "         → temperature 적용. 낮으면 확률이 뾰족해지고(안정적),\n"
            "            높으면 평평해진다(다양함). 다음 레슨에서 자세히 다룬다.\n"
            "  ctx = ctx[1:] + [nxt]\n"
            "         → 문맥 창을 한 칸 밀어낸다. 이것이 컨텍스트 윈도우다.\n"
            "\n"
            "[결과를 어떻게 읽을까 — 정직하게]\n"
            "  학습 후 '나는 밥을' 을 주면 '나는 밥을 먹었다. 그는 국수를...' 처럼\n"
            "  문법에 맞는 한국어가 나온다.\n"
            "\n"
            "  **하지만 이건 사실상 암기다.** 말뭉치가 짧고 같은 문장이 반복되므로\n"
            "  모델은 패턴을 외웠다. 새로운 표현을 만들어내지는 못한다.\n"
            "  진짜 LLM 은 수조 개 토큰을 학습해 외울 수 없는 지점에 도달하고,\n"
            "  그때 비로소 '일반화'가 일어난다. 규모가 질적 차이를 만드는 것이다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 문맥 4글자는 매우 짧다. 긴 의존성은 당연히 못 잡는다.\n"
            "  • 실제 GPT 는 여기에 어텐션·위치인코딩·수십 개 블록이 더해진다.\n"
            "  • 손실이 0 에 가까워지면 완전 암기 상태다. 검증 손실을 함께 봐야 한다."
        ),
        usage="LLM 학습의 전 과정을 축소판으로 체험. 여기서 막히면 큰 모델도 이해할 수 없다.",
        cons="말뭉치가 작아 암기에 가깝다. 일반화 능력은 이 규모로는 확인할 수 없다.",
        code=(
            "import numpy as np\n"
            "\n"
            "# ---- 말뭉치 ----\n"
            "text = ('나는 밥을 먹었다. 너는 빵을 먹었다. 그는 국수를 먹었다. '\n"
            "        '나는 물을 마셨다. 너는 우유를 마셨다. 그는 주스를 마셨다. ') * 12\n"
            "\n"
            "chars = sorted(set(text))\n"
            "V = len(chars)\n"
            "stoi = {c: i for i, c in enumerate(chars)}\n"
            "itos = {i: c for c, i in stoi.items()}\n"
            "data = np.array([stoi[c] for c in text])\n"
            "print(f'말뭉치 {len(text)}글자 · 어휘 {V}개')\n"
            "\n"
            "# ---- 학습 데이터: 앞 4글자 → 다음 1글자 ----\n"
            "CTX = 4\n"
            "X = np.array([data[i:i + CTX] for i in range(len(data) - CTX)])\n"
            "Y = np.array([data[i + CTX] for i in range(len(data) - CTX)])\n"
            "n = len(X)\n"
            "print(f'학습 쌍 {n}개\\n')\n"
            "\n"
            "print('학습 데이터 예시 (슬라이딩 윈도우)')\n"
            "for i in range(4):\n"
            "    ctx = ''.join(itos[t] for t in X[i])\n"
            "    print(f\"  입력 {ctx!r:12s} → 정답 {itos[Y[i]]!r}\")\n"
            "print('→ 라벨을 사람이 붙이지 않았다. 텍스트 자체가 정답이다(자기지도학습)\\n')\n"
            "\n"
            "# ---- 모델 ----\n"
            "rng = np.random.default_rng(0)\n"
            "D, H = 12, 64\n"
            "E = rng.normal(0, 0.3, (V, D))                              # 임베딩\n"
            "W1 = rng.normal(0, 1, (CTX * D, H)) * np.sqrt(2 / (CTX * D))\n"
            "b1 = np.zeros(H)\n"
            "W2 = rng.normal(0, 1, (H, V)) * np.sqrt(2 / H)\n"
            "b2 = np.zeros(V)\n"
            "\n"
            "def softmax(z):\n"
            "    e = np.exp(z - z.max(axis=1, keepdims=True))\n"
            "    return e / e.sum(axis=1, keepdims=True)\n"
            "\n"
            "params = [E, W1, b1, W2, b2]\n"
            "M = [np.zeros_like(p) for p in params]\n"
            "Vv = [np.zeros_like(p) for p in params]\n"
            "onehot = np.eye(V)[Y]\n"
            "\n"
            "print('학습 시작')\n"
            "for t in range(1, 1201):\n"
            "    emb = E[X].reshape(n, -1)                # (n, CTX*D)\n"
            "    z1 = emb @ W1 + b1\n"
            "    a1 = np.maximum(0, z1)\n"
            "    prob = softmax(a1 @ W2 + b2)\n"
            "    loss = float(-np.log(np.clip(prob[np.arange(n), Y], 1e-9, 1)).mean())\n"
            "\n"
            "    dz2 = (prob - onehot) / n\n"
            "    dW2 = a1.T @ dz2\n"
            "    db2 = dz2.sum(axis=0)\n"
            "    dz1 = (dz2 @ W2.T) * (z1 > 0)\n"
            "    dW1 = emb.T @ dz1\n"
            "    db1 = dz1.sum(axis=0)\n"
            "    demb = (dz1 @ W1.T).reshape(n, CTX, D)\n"
            "    dE = np.zeros_like(E)\n"
            "    np.add.at(dE, X, demb)                   # 중복 인덱스 누적 (중요!)\n"
            "\n"
            "    for i, (p, g) in enumerate(zip(params, [dE, dW1, db1, dW2, db2])):\n"
            "        M[i] = 0.9 * M[i] + 0.1 * g\n"
            "        Vv[i] = 0.999 * Vv[i] + 0.001 * (g * g)\n"
            "        p -= 0.01 * (M[i] / (1 - 0.9 ** t)) / (\n"
            "            np.sqrt(Vv[i] / (1 - 0.999 ** t)) + 1e-8)\n"
            "\n"
            "    if t % 300 == 0:\n"
            "        print(f'  epoch {t:4d}   손실 {loss:.4f}')\n"
            "\n"
            "# ---- 생성 (자기회귀) ----\n"
            "def generate(seed, k=45, temp=0.6, seed_rng=7):\n"
            "    r = np.random.default_rng(seed_rng)\n"
            "    ctx = [stoi[c] for c in seed][-CTX:]\n"
            "    out = seed\n"
            "    for _ in range(k):\n"
            "        e = E[np.array(ctx)].reshape(1, -1)\n"
            "        p = softmax(np.maximum(0, e @ W1 + b1) @ W2 + b2)[0]\n"
            "        p = np.power(p, 1 / temp)\n"
            "        p = p / p.sum()\n"
            "        nxt = int(r.choice(V, p=p))\n"
            "        out += itos[nxt]\n"
            "        ctx = ctx[1:] + [nxt]        # 문맥 창을 한 칸 민다\n"
            "    return out\n"
            "\n"
            "print('\\n-- 생성 결과 --')\n"
            "for seed in ['나는 밥을', '너는 빵을', '그는 국수']:\n"
            "    print(f'  {seed!r}\\n    → {generate(seed)!r}')\n"
            "\n"
            "# 다음 글자 확률 들여다보기\n"
            "ctx = [stoi[c] for c in '나는 밥을'][-CTX:]\n"
            "e = E[np.array(ctx)].reshape(1, -1)\n"
            "p = softmax(np.maximum(0, e @ W1 + b1) @ W2 + b2)[0]\n"
            "top = np.argsort(p)[::-1][:5]\n"
            "print(\"\\n-- '나는 밥을' 다음에 올 글자 상위 5 --\")\n"
            "for i in top:\n"
            "    print(f'  {itos[i]!r:6s} {p[i]:.6e}  ' + '#' * int(p[i] * 40))\n"
            "print(f'  1등 확률 {p.max():.8f} — 사실상 1.0 이다')\n"
            "\n"
            "print('\\n※ 관찰 두 가지')\n"
            "print('  1) 1등 확률이 1.0 에 붙어 있다.')\n"
            "print('     모델이 \"여기 다음은 무조건 이 글자\" 라고 확신한다는 뜻이다.')\n"
            "print('     말뭉치가 짧아 완전히 외웠기 때문이다(과적합).')\n"
            "print('     실제 LLM 은 이렇게 확신하지 않고 여러 후보에 확률을 나눠 갖는다.')\n"
            "print('  2) 생성문에 같은 문장이 반복된다.')\n"
            "print('     문맥이 4글자뿐이라 앞서 무슨 말을 했는지 기억하지 못한다.')\n"
            "print('     실제 LLM 도 반복 루프에 빠지곤 하며, 그래서 샘플링 전략과')\n"
            "print('     반복 페널티가 필요하다 → 다음 레슨')\n"
            "\n"
            "print('\\n※ 이 모델은 사실상 말뭉치를 암기했다.')\n"
            "print('  진짜 LLM 은 외울 수 없을 만큼 방대한 데이터를 학습하고,')\n"
            "print('  그 지점에서 비로소 일반화가 일어난다. 규모가 질적 차이를 만든다.')\n"
        ),
    ),

    Lesson(
        id="ds5-08-sampling",
        lang="datasci", level=STAGE,
        title="샘플링 전략",
        summary="temperature · top-k · top-p — 창의성 손잡이",
        explanation=(
            "[개요]\n"
            "모델은 '다음 토큰의 확률 분포'를 준다.\n"
            "거기서 실제로 하나를 **어떻게 고르느냐**가 출력 품질을 크게 좌우한다.\n"
            "같은 모델이라도 샘플링 방법에 따라 결과가 완전히 달라진다.\n"
            "\n"
            "[1) 그리디 (greedy)]\n"
            "  항상 확률 1등을 고른다.\n"
            "  · 장점: 안정적이고 결과가 항상 같다(재현 가능)\n"
            "  · 단점: 지루하고 같은 말을 반복하는 루프에 빠지기 쉽다\n"
            "  · 번역·요약처럼 정답이 하나에 가까운 작업에 적합하다\n"
            "\n"
            "[2) Temperature]\n"
            "    p' ∝ p^(1/T)      또는 로짓을 T 로 나눈다\n"
            "\n"
            "    T → 0    : 그리디에 수렴 (1등만 뽑힘)\n"
            "    T = 1    : 모델이 계산한 확률 그대로\n"
            "    T > 1    : 분포가 평평해져 희귀한 토큰도 뽑힌다\n"
            "\n"
            "  · 낮게(0.2~0.5) : 사실 기반 답변, 코드 생성\n"
            "  · 높게(0.8~1.2) : 창작, 브레인스토밍\n"
            "  · 너무 높으면(>1.5) 문장이 무너진다\n"
            "\n"
            "[3) Top-k]\n"
            "  확률 상위 k 개만 남기고 나머지는 버린 뒤 정규화해서 뽑는다.\n"
            "  · 꼬리에 있는 이상한 토큰이 뽑히는 사고를 막는다\n"
            "  · 단점: k 가 고정이라 상황에 맞지 않는다.\n"
            "    확신이 강한 자리에서도 억지로 k 개를 남기고,\n"
            "    애매한 자리에서는 k 개로 부족하다.\n"
            "\n"
            "[4) Top-p (뉴클리어스 샘플링)] ← 현재 표준\n"
            "  확률을 높은 순으로 더해 **누적이 p 를 넘는 지점까지만** 남긴다.\n"
            "\n"
            "    확신이 강한 자리 → 후보가 1~2개로 줄어든다\n"
            "    애매한 자리     → 후보가 수십 개로 늘어난다\n"
            "\n"
            "  분포 모양에 따라 후보 수가 **자동으로 조절된다.** 이것이 top-k 와의 차이다.\n"
            "  보통 p=0.9 ~ 0.95 를 쓴다.\n"
            "\n"
            "[실무 조합]\n"
            "  temperature 와 top-p 를 함께 쓰는 것이 일반적이다.\n"
            "  OpenAI·Anthropic API 의 temperature, top_p 파라미터가 바로 이것이다.\n"
            "  · 사실 질의응답 : temperature 0.0~0.3\n"
            "  · 일반 대화     : 0.7 근처\n"
            "  · 창작          : 0.9~1.1 + top_p 0.95\n"
            "\n"
            "[코드 분석]\n"
            "  np.exp(logits / T)\n"
            "         → temperature 적용. 확률이 아니라 **로짓을 나누는** 것이 정석이다.\n"
            "            확률에 1/T 제곱을 해도 결과는 같다.\n"
            "  idx = np.argsort(p)[::-1]\n"
            "         → 확률 내림차순 정렬. top-k/top-p 의 출발점이다.\n"
            "  cum = np.cumsum(p_sorted)\n"
            "  cut = np.searchsorted(cum, top_p) + 1\n"
            "         → 누적합이 p 를 넘는 첫 위치. +1 은 그 토큰까지 포함하기 위함이다.\n"
            "            이걸 빼먹으면 후보가 하나 모자란다.\n"
            "  max(cut, 1)\n"
            "         → 최소 1개는 남긴다. 1등 확률이 이미 p 보다 크면\n"
            "            cut 이 0 이 되어 후보가 사라지는 사고를 막는다.\n"
            "\n"
            "[유의 사항]\n"
            "  • temperature 0 은 수학적으로 0 으로 나누기다.\n"
            "    실제 구현은 그리디로 대체하도록 특별 처리한다.\n"
            "  • 같은 설정이라도 시드가 다르면 결과가 달라진다.\n"
            "    재현이 필요하면 시드를 고정하거나 그리디를 쓰자.\n"
            "  • 반복을 막으려면 샘플링 외에 repetition penalty 를 함께 쓴다."
        ),
        usage="LLM API 를 쓸 때 매번 만나는 파라미터. 원리를 알면 용도에 맞게 조절할 수 있다.",
        cons="어떤 값이 좋은지는 작업마다 다르다. 결국 실험으로 찾아야 한다.",
        code=(
            "import numpy as np\n"
            "\n"
            "vocab = ['좋다', '춥다', '덥다', '흐리다', '맑다', '이상하다', '푸르다', '무겁다']\n"
            "logits = np.array([4.0, 2.5, 2.2, 1.0, 0.8, 0.3, -0.5, -1.2])\n"
            "\n"
            "def softmax(z):\n"
            "    e = np.exp(z - z.max())\n"
            "    return e / e.sum()\n"
            "\n"
            "base = softmax(logits)\n"
            "print(\"입력: '오늘 날씨가 정말'\\n\")\n"
            "print('원본 확률 (T=1)')\n"
            "for w, p in zip(vocab, base):\n"
            "    print(f'  {w:8s} {p:.4f}  ' + '#' * int(p * 60))\n"
            "\n"
            "# ---- temperature ----\n"
            "print('\\n' + '=' * 56)\n"
            "print('Temperature — 분포의 뾰족함을 조절')\n"
            "print('=' * 56)\n"
            "print(f\"{'토큰':10s}\" + ''.join(f'T={t:<7.1f}' for t in [0.3, 0.7, 1.0, 1.5]))\n"
            "for i, w in enumerate(vocab[:5]):\n"
            "    line = f'{w:10s}'\n"
            "    for T in [0.3, 0.7, 1.0, 1.5]:\n"
            "        line += f'{softmax(logits / T)[i]:<9.4f}'\n"
            "    print(line)\n"
            "print('\\n→ T 가 낮으면 1등에 확률이 몰리고(보수적),')\n"
            "print('  T 가 높으면 고르게 퍼진다(창의적).')\n"
            "\n"
            "# ---- top-k ----\n"
            "def top_k_filter(p, k):\n"
            "    out = np.zeros_like(p)\n"
            "    idx = np.argsort(p)[::-1][:k]\n"
            "    out[idx] = p[idx]\n"
            "    return out / out.sum()\n"
            "\n"
            "print('\\n' + '=' * 56)\n"
            "print('Top-k — 상위 k 개만 남긴다')\n"
            "print('=' * 56)\n"
            "for k in [1, 3, 5]:\n"
            "    f = top_k_filter(base, k)\n"
            "    alive = [vocab[i] for i in range(len(vocab)) if f[i] > 0]\n"
            "    print(f'  k={k}: 후보 {len(alive)}개 {alive}')\n"
            "\n"
            "# ---- top-p ----\n"
            "def top_p_filter(p, top_p):\n"
            "    idx = np.argsort(p)[::-1]\n"
            "    cum = np.cumsum(p[idx])\n"
            "    cut = max(int(np.searchsorted(cum, top_p)) + 1, 1)   # 최소 1개는 남긴다\n"
            "    keep = idx[:cut]\n"
            "    out = np.zeros_like(p)\n"
            "    out[keep] = p[keep]\n"
            "    return out / out.sum(), cut\n"
            "\n"
            "print('\\n' + '=' * 56)\n"
            "print('Top-p — 누적 확률이 p 를 넘을 때까지만')\n"
            "print('=' * 56)\n"
            "for tp in [0.5, 0.9, 0.95]:\n"
            "    f, cut = top_p_filter(base, tp)\n"
            "    alive = [vocab[i] for i in np.argsort(base)[::-1][:cut]]\n"
            "    print(f'  p={tp}: 후보 {cut}개 {alive}')\n"
            "\n"
            "# top-p 의 진짜 장점: 분포에 따라 후보 수가 자동 조절된다\n"
            "print('\\n-- 분포 모양에 따른 후보 수 (p=0.9 고정) --')\n"
            "sharp = softmax(np.array([8.0, 1.0, 0.5, 0.2, 0.1, 0.0, -1.0, -2.0]))\n"
            "flat = softmax(np.array([1.0, 0.9, 0.85, 0.8, 0.75, 0.7, 0.65, 0.6]))\n"
            "for name, dist in [('확신이 강한 자리', sharp), ('애매한 자리', flat)]:\n"
            "    _, cut_p = top_p_filter(dist, 0.9)\n"
            "    print(f'  {name:16s} 1등 확률 {dist.max():.3f}  →  '\n"
            "          f'top-p 후보 {cut_p}개 · top-k(k=3) 후보 3개(고정)')\n"
            "print('  → top-p 는 상황에 맞춰 후보 수를 스스로 조절한다. 이것이 핵심이다.')\n"
            "\n"
            "# ---- 실제로 뽑아 보기 ----\n"
            "print('\\n' + '=' * 56)\n"
            "print('실제로 샘플링해서 다양성 비교')\n"
            "print('=' * 56)\n"
            "N = 200\n"
            "print(f'({N}번씩 뽑아 다양성을 비교한다)\\n')\n"
            "print(f\"  그리디        : 서로 다른 토큰 1종   \"\n"
            "      f\"{[vocab[int(base.argmax())]] * 3} ... 항상 동일\")\n"
            "for name, dist in [('T=0.3        ', softmax(logits / 0.3)),\n"
            "                   ('T=0.7        ', softmax(logits / 0.7)),\n"
            "                   ('T=1.0        ', base),\n"
            "                   ('T=1.5        ', softmax(logits / 1.5)),\n"
            "                   ('top-p 0.9    ', top_p_filter(base, 0.9)[0])]:\n"
            "    rng = np.random.default_rng(42)          # 같은 시드로 공정 비교\n"
            "    picks = [str(x) for x in rng.choice(vocab, size=N, p=dist)]\n"
            "    uniq = len(set(picks))\n"
            "    top_share = picks.count(vocab[int(base.argmax())]) / N\n"
            "    print(f'  {name}: 서로 다른 토큰 {uniq}종 · 1등 비율 {top_share:.0%}'\n"
            "          f'   {picks[:6]}')\n"
            "\n"
            "print('\\n→ T 가 오를수록 등장하는 토큰 종류가 늘고 1등 비율이 떨어진다.')\n"
            "print('  top-p 0.9 는 후보를 3개로 제한하므로 T=1.0 보다 안전하면서도')\n"
            "print('  그리디처럼 단조롭지는 않다. 그래서 실무 기본값으로 쓰인다.')\n"
        ),
    ),

    Lesson(
        id="ds5-09-context",
        lang="datasci", level=STAGE,
        title="컨텍스트 · RAG",
        summary="LLM 이 모르는 것을 알게 하는 법",
        explanation=(
            "[개요]\n"
            "LLM 은 학습 시점까지의 데이터만 안다. 그리고 학습에 없던 정보는 모른다.\n"
            "  · 어제 회의 내용\n"
            "  · 우리 회사 내부 문서\n"
            "  · 학습 종료 이후의 사건\n"
            "\n"
            "이걸 해결하는 방법이 두 가지다.\n"
            "\n"
            "[방법 1 — 컨텍스트에 넣기]\n"
            "  질문과 함께 참고 자료를 프롬프트에 넣어준다. 가장 간단하다.\n"
            "\n"
            "    [참고자료]\n"
            "    2026년 1분기 매출은 34억이다.\n"
            "    [질문]\n"
            "    1분기 매출이 얼마야?\n"
            "\n"
            "  한계: 컨텍스트 길이에 제한이 있다. 문서 10만 쪽을 다 넣을 수는 없다.\n"
            "  또 컨텍스트가 길수록 비용이 늘고 느려진다(어텐션이 길이의 제곱).\n"
            "\n"
            "[방법 2 — RAG (검색 증강 생성)]\n"
            "  질문과 관련된 부분만 찾아서 넣는다.\n"
            "\n"
            "    1) 문서를 조각(청크)으로 나눈다\n"
            "    2) 각 조각을 임베딩 벡터로 바꿔 저장한다 (벡터 DB)\n"
            "    3) 질문이 오면 질문도 임베딩한다\n"
            "    4) 가장 비슷한 조각 몇 개를 찾는다 (코사인 유사도)\n"
            "    5) 그 조각들만 프롬프트에 넣어 LLM 에게 답하게 한다\n"
            "\n"
            "  문서가 아무리 많아도 관련 부분만 뽑아 쓰므로 확장성이 좋다.\n"
            "\n"
            "[코사인 유사도 — RAG 검색의 핵심]\n"
            "    cos(A, B) = A·B / (|A| |B|)\n"
            "\n"
            "  두 벡터가 이루는 각도만 본다. 길이는 무시한다.\n"
            "  긴 문서와 짧은 문서를 공정하게 비교할 수 있어 텍스트 검색에 적합하다.\n"
            "  값은 -1~1 이고, 1 에 가까울수록 비슷하다.\n"
            "\n"
            "[키워드 검색과 무엇이 다른가]\n"
            "  · 키워드 검색 : '자동차' 로 검색하면 '자동차'가 든 문서만 나온다\n"
            "  · 임베딩 검색 : '자동차' 로 검색해도 '승용차', '차량'이 든 문서가 나온다\n"
            "  의미가 비슷하면 단어가 달라도 찾아낸다. 이것이 임베딩의 힘이다.\n"
            "\n"
            "  실무에서는 둘을 섞어 쓰는 하이브리드 검색이 성능이 좋다.\n"
            "  고유명사·제품코드는 키워드 검색이 더 정확하기 때문이다.\n"
            "\n"
            "[코드 분석]\n"
            "  여기서는 진짜 임베딩 모델 대신 **단어 등장 여부 벡터**로 흉내낸다.\n"
            "  실제로는 문장 임베딩 모델이 의미를 담은 벡터를 만들어준다.\n"
            "\n"
            "  v / (np.linalg.norm(v) + 1e-9)\n"
            "         → 벡터를 길이 1 로 정규화. 이러면 내적이 곧 코사인 유사도다.\n"
            "            1e-9 는 길이 0 인 벡터(공통 단어가 없는 경우)의 0 나누기 방지.\n"
            "  np.argsort(sims)[::-1][:k]\n"
            "         → 유사도 상위 k 개 조각을 고른다.\n"
            "  검색된 조각만 프롬프트에 넣기\n"
            "         → 전체 문서 대신 관련 조각만 넣는다. 토큰 수가 크게 줄어든다.\n"
            "\n"
            "[유의 사항]\n"
            "  • RAG 는 환각을 줄이지만 없애지는 못한다. 검색이 틀리면 답도 틀린다.\n"
            "  • 청크를 어떻게 나눌지가 성능을 크게 좌우한다.\n"
            "    너무 잘게 나누면 문맥이 끊기고, 크게 나누면 관련 없는 내용이 섞인다.\n"
            "  • 컨텍스트가 길면 가운데 내용을 놓치는 경향이 보고되어 있다\n"
            "    (lost in the middle). 중요한 내용은 앞이나 뒤에 두는 게 유리하다."
        ),
        usage="사내 문서 챗봇, 고객지원 자동화 등 실무 LLM 애플리케이션의 표준 구조.",
        cons="검색 품질이 전부다. 관련 문서를 못 찾으면 LLM 은 아는 척 지어낸다.",
        code=(
            "import numpy as np\n"
            "\n"
            "# 사내 문서 (실제로는 수만 건)\n"
            "docs = [\n"
            "    '2026년 1분기 매출은 34억원이며 전년 대비 12% 증가했다',\n"
            "    '신규 서비스 출시일은 2026년 5월 10일로 확정되었다',\n"
            "    '재택근무는 주 2회까지 가능하며 팀장 승인이 필요하다',\n"
            "    '연차는 입사 1년 후 15일이 부여되고 매년 1일씩 늘어난다',\n"
            "    '2026년 2분기 매출 목표는 40억원으로 설정되었다',\n"
            "    '사내 교육비는 연간 100만원까지 지원된다',\n"
            "]\n"
            "\n"
            "# --- 간이 임베딩: 단어 등장 여부 벡터 (진짜는 임베딩 모델이 만든다) ---\n"
            "vocab = sorted({w for d in docs for w in d.split()})\n"
            "\n"
            "def embed(text):\n"
            "    words = set(text.split())\n"
            "    v = np.array([1.0 if w in words else 0.0 for w in vocab])\n"
            "    return v / (np.linalg.norm(v) + 1e-9)      # 길이 1 로 정규화\n"
            "\n"
            "doc_vecs = np.array([embed(d) for d in docs])\n"
            "print(f'문서 {len(docs)}개 · 어휘 {len(vocab)}개')\n"
            "print(f'문서 벡터 모양: {doc_vecs.shape}\\n')\n"
            "\n"
            "def search(query, k=2, min_sim=0.05):\n"
            "    qv = embed(query)\n"
            "    sims = doc_vecs @ qv                       # 정규화했으므로 내적 = 코사인\n"
            "    top = np.argsort(sims)[::-1][:k]\n"
            "    # 유사도가 너무 낮은 문서는 버린다 — 무관한 자료를 넣으면 오히려 해롭다\n"
            "    return [(docs[i], float(sims[i])) for i in top if sims[i] >= min_sim]\n"
            "\n"
            "for q in ['2026년 1분기 매출은 얼마인가', '재택근무는 몇 회 가능한가',\n"
            "          '주차장은 어디에 있는가']:\n"
            "    print(f'질문: {q}')\n"
            "    hits = search(q)\n"
            "    if not hits:\n"
            "        print('  (관련 문서 없음 → LLM 에게 \"모른다\" 고 답하게 해야 한다)')\n"
            "    for doc, sim in hits:\n"
            "        print(f'  유사도 {sim:.3f}  {doc}')\n"
            "    print()\n"
            "\n"
            "# --- RAG 프롬프트 조립 ---\n"
            "print('=' * 60)\n"
            "print('RAG 프롬프트 조립')\n"
            "print('=' * 60)\n"
            "q = '2026년 1분기 매출은 얼마인가'\n"
            "found = search(q, k=2)\n"
            "prompt = '아래 참고자료만 근거로 답하시오. 자료에 없으면 모른다고 답하시오.\\n\\n'\n"
            "prompt += '[참고자료]\\n'\n"
            "for i, (doc, _) in enumerate(found, start=1):\n"
            "    prompt += f'{i}. {doc}\\n'\n"
            "prompt += f'\\n[질문]\\n{q}'\n"
            "print(prompt)\n"
            "\n"
            "all_len = sum(len(d) for d in docs)\n"
            "rag_len = sum(len(d) for d, _ in found)\n"
            "print(f'\\n전체 문서를 넣으면 {all_len}자, RAG 는 {rag_len}자')\n"
            "print(f'→ {(1 - rag_len / all_len):.0%} 절약. 문서가 수만 건이면 차이는 결정적이다.')\n"
            "\n"
            "# --- 코사인 유사도 vs 유클리드 거리 ---\n"
            "print('\\n' + '=' * 60)\n"
            "print('왜 코사인 유사도인가 — 길이에 영향받지 않는다')\n"
            "print('=' * 60)\n"
            "a = np.array([1.0, 2.0])\n"
            "b = np.array([5.0, 10.0])      # a 와 방향은 같고 길이만 5배\n"
            "c = np.array([2.0, 1.0])       # 길이는 a 와 비슷하나 방향이 다름\n"
            "\n"
            "def cos(x, y):\n"
            "    return float(x @ y / (np.linalg.norm(x) * np.linalg.norm(y)))\n"
            "\n"
            "print(f'  A={a} · B={b} (방향 같음, 길이 5배)')\n"
            "print(f'    코사인 {cos(a, b):.4f}   유클리드 거리 {np.linalg.norm(a - b):.3f}')\n"
            "print(f'  A={a} · C={c} (길이 비슷, 방향 다름)')\n"
            "print(f'    코사인 {cos(a, c):.4f}   유클리드 거리 {np.linalg.norm(a - c):.3f}')\n"
            "print('\\n  → 코사인은 B 를 A 와 같다고 본다(방향이 같으므로).')\n"
            "print('    긴 문서와 짧은 문서를 공정하게 비교하려면 이쪽이 맞다.')\n"
        ),
    ),

    Lesson(
        id="ds5-10-practice",
        lang="datasci", level=STAGE,
        title="프롬프트 · 파인튜닝 · 한계",
        summary="LLM 을 실제로 쓸 때 알아야 할 것",
        explanation=(
            "[개요]\n"
            "5단계 마무리로, LLM 을 실무에서 쓸 때 필요한 판단 기준을 정리한다.\n"
            "\n"
            "[모델을 내 용도에 맞추는 4가지 방법 — 비용 순]\n"
            "\n"
            "  1) 프롬프트 엔지니어링   비용 없음. **항상 여기서 시작한다.**\n"
            "  2) RAG                   문서만 있으면 됨. 최신 정보·내부 자료에 최적.\n"
            "  3) 파인튜닝              수백~수천 개 예시 필요. 말투·형식 학습에 적합.\n"
            "  4) 사전학습              수십억 원 이상. 사실상 빅테크만 가능.\n"
            "\n"
            "  실무의 90% 는 1~2번으로 해결된다. 3번으로 바로 가는 것은 대개 낭비다.\n"
            "\n"
            "[프롬프트의 기본기]\n"
            "  · 역할 부여   : '너는 10년차 데이터 분석가다'\n"
            "  · 구체적 지시 : '요약해줘' 보다 '3문장으로, 숫자를 포함해 요약해줘'\n"
            "  · 예시 제공   : 원하는 출력 형식을 1~3개 보여준다 (few-shot)\n"
            "  · 단계 유도   : '단계별로 생각해보자' (chain-of-thought)\n"
            "  · 출력 형식   : JSON 스키마를 명시하면 파싱이 안정된다\n"
            "  · 제약 명시   : '자료에 없으면 모른다고 답하라' → 환각을 크게 줄인다\n"
            "\n"
            "[파인튜닝이 잘 맞는 경우 / 아닌 경우]\n"
            "  잘 맞음 : 특정 말투·형식 고정, 분류 작업 정확도 향상, 짧은 프롬프트로 비용 절감\n"
            "  안 맞음 : **새로운 지식 주입.** 이건 RAG 가 맞다.\n"
            "            파인튜닝은 '어떻게 말할지'를 가르치지 '무엇을 아는지'를 늘리지 않는다.\n"
            "            자주 바뀌는 정보 — 재학습 비용이 계속 든다.\n"
            "\n"
            "[반드시 알아야 할 한계]\n"
            "\n"
            "  1) 환각(hallucination)\n"
            "     LLM 은 사실 데이터베이스가 아니라 '그럴듯한 다음 토큰'을 계산하는 확률 모델이다.\n"
            "     그래서 존재하지 않는 논문·판례·API 를 자신 있게 지어낸다.\n"
            "     → 검증 가능한 출처를 함께 요구하고, 중요한 사실은 반드시 사람이 확인한다.\n"
            "\n"
            "  2) 지식 컷오프\n"
            "     학습 종료 이후를 모른다. 모르면서 아는 척할 수도 있다.\n"
            "\n"
            "  3) 컨텍스트 한계\n"
            "     길이 제한이 있고, 길수록 비용이 늘며(어텐션은 길이의 제곱),\n"
            "     가운데 내용을 놓치는 경향이 있다(lost in the middle).\n"
            "\n"
            "  4) 계산·논리의 취약함\n"
            "     큰 수 계산이나 여러 단계 추론에서 자주 틀린다.\n"
            "     → 계산은 코드를 생성해 실행시키는 편이 정확하다.\n"
            "\n"
            "  5) 프롬프트 인젝션\n"
            "     사용자 입력이나 검색된 문서 안에 '이전 지시를 무시하라' 같은 문장이\n"
            "     들어 있으면 따라갈 수 있다. 외부 텍스트를 신뢰하면 안 된다.\n"
            "\n"
            "  6) 비결정성\n"
            "     같은 질문에 매번 다르게 답한다(temperature > 0). 테스트가 어렵다.\n"
            "\n"
            "[토큰과 비용]\n"
            "  과금은 글자 수가 아니라 **토큰 수** 기준이다.\n"
            "  한국어는 영어보다 토큰이 많이 나와 같은 내용도 비용이 더 든다.\n"
            "  입력 토큰과 출력 토큰의 단가가 다르며, 보통 출력이 비싸다.\n"
            "\n"
            "[다음 학습 방향]\n"
            "  · 실제 LLM API 를 써서 애플리케이션 만들기\n"
            "  · LangChain / LlamaIndex 같은 프레임워크\n"
            "  · 벡터 DB (FAISS, Chroma, pgvector)\n"
            "  · 평가 방법 — LLM 출력을 어떻게 채점할 것인가 (실무에서 가장 어려운 부분)\n"
            "  · 오픈소스 모델을 직접 돌려보기 (Ollama 등)"
        ),
        usage="5단계 총정리. LLM 기반 서비스를 설계할 때의 판단 기준.",
        cons="이 분야는 변화가 매우 빠르다. 구체적인 기법보다 원리와 한계를 붙잡는 게 오래 간다.",
        code=(
            "# ---- 프롬프트 개선 전후 비교 ----\n"
            "bad = '이 데이터 분석해줘'\n"
            "good = '''너는 10년차 데이터 분석가다.\n"
            "\n"
            "아래 매출 데이터를 분석해 다음 형식의 JSON 으로만 답하라.\n"
            "설명 문장은 넣지 말 것.\n"
            "\n"
            "{\n"
            "  \"summary\": \"3문장 이내, 숫자 포함\",\n"
            "  \"trend\": \"increasing | decreasing | flat\",\n"
            "  \"anomalies\": [\"이상 징후\"],\n"
            "  \"confidence\": 0.0~1.0\n"
            "}\n"
            "\n"
            "데이터에 없는 내용은 추측하지 말고 anomalies 를 빈 배열로 두라.\n"
            "\n"
            "[데이터]\n"
            "2026-01: 34억\n"
            "2026-02: 31억\n"
            "2026-03: 45억'''\n"
            "\n"
            "print('=' * 62)\n"
            "print('나쁜 프롬프트')\n"
            "print('=' * 62)\n"
            "print(bad)\n"
            "print('\\n문제: 무엇을·어떤 형식으로·어느 수준까지인지 전부 불명확')\n"
            "\n"
            "print('\\n' + '=' * 62)\n"
            "print('좋은 프롬프트')\n"
            "print('=' * 62)\n"
            "print(good)\n"
            "\n"
            "checklist = [\n"
            "    ('역할 부여', '10년차 데이터 분석가'),\n"
            "    ('출력 형식', 'JSON 스키마 명시 → 파싱 안정'),\n"
            "    ('분량 제한', '3문장 이내'),\n"
            "    ('값 제약', 'increasing | decreasing | flat'),\n"
            "    ('환각 방지', '추측하지 말고 빈 배열'),\n"
            "    ('군더더기 차단', '설명 문장은 넣지 말 것'),\n"
            "]\n"
            "print('\\n적용된 기법')\n"
            "for k, v in checklist:\n"
            "    print(f'  · {k:12s} {v}')\n"
            "\n"
            "# ---- 방법 선택 가이드 ----\n"
            "print('\\n' + '=' * 62)\n"
            "print('무엇을 쓸까 — 비용이 낮은 순으로 시도한다')\n"
            "print('=' * 62)\n"
            "rows = [\n"
            "    ('프롬프트', '없음', '형식·말투·간단한 작업', '항상 여기서 시작'),\n"
            "    ('RAG', '문서', '최신 정보·내부 자료', '지식 주입은 이쪽'),\n"
            "    ('파인튜닝', '예시 수백~수천', '말투 고정·분류 정확도', '지식 주입엔 부적합'),\n"
            "    ('사전학습', '수십억원+', '기반 모델 개발', '사실상 빅테크 전용'),\n"
            "]\n"
            "print(f\"{'방법':10s}{'필요 비용':16s}{'적합한 용도':22s}비고\")\n"
            "print('-' * 62)\n"
            "for a, b, c, d in rows:\n"
            "    print(f'{a:10s}{b:16s}{c:22s}{d}')\n"
            "\n"
            "# ---- 한계 체크리스트 ----\n"
            "print('\\n' + '=' * 62)\n"
            "print('배포 전 반드시 점검할 한계')\n"
            "print('=' * 62)\n"
            "limits = [\n"
            "    ('환각', '없는 사실을 지어낸다', '출처 요구 + 사람 검증'),\n"
            "    ('지식 컷오프', '학습 이후를 모른다', 'RAG 로 최신 정보 주입'),\n"
            "    ('컨텍스트 한계', '길면 비싸고 가운데를 놓친다', '중요 내용은 앞뒤에 배치'),\n"
            "    ('계산 취약', '큰 수·다단계 추론에 약함', '코드 생성 후 실행'),\n"
            "    ('프롬프트 인젝션', '외부 텍스트의 지시를 따를 수 있음', '입력을 신뢰하지 않기'),\n"
            "    ('비결정성', '같은 질문에 다른 답', 'temperature 0 + 시드 고정'),\n"
            "]\n"
            "for name, problem, fix in limits:\n"
            "    print(f'\\n  [{name}]')\n"
            "    print(f'    문제 : {problem}')\n"
            "    print(f'    대응 : {fix}')\n"
            "\n"
            "print('\\n' + '=' * 62)\n"
            "print('5단계 완료 — 다음 학습 방향')\n"
            "print('=' * 62)\n"
            "for s in ['실제 LLM API 로 애플리케이션 만들기',\n"
            "          'LangChain / LlamaIndex 프레임워크',\n"
            "          '벡터 DB (FAISS, Chroma, pgvector)',\n"
            "          'LLM 출력 평가 방법 — 실무에서 가장 어려운 부분',\n"
            "          '오픈소스 모델 직접 구동 (Ollama 등)']:\n"
            "    print(f'  · {s}')\n"
        ),
    ),
]
