"""3단계 — 머신러닝 (로드맵 + 핵심 개념 맛보기).

sklearn 없이 numpy 만으로 원리를 직접 구현한다.
라이브러리 사용법보다 '학습이란 무엇인가'를 코드로 이해하는 데 목적이 있다.
"""

from engine.models import Lesson

STAGE = "3. 머신러닝"

LESSONS = [

    Lesson(
        id="ds3-01-roadmap",
        lang="datasci", level=STAGE,
        title="머신러닝 로드맵",
        summary="학습이란 무엇인가 · 이 단계에서 배울 것",
        explanation=(
            "[개요]\n"
            "머신러닝은 '규칙을 사람이 짜지 않고, 데이터에서 찾아내게 하는 것'이다.\n"
            "\n"
            "  전통적 프로그래밍 : 규칙 + 데이터  →  답\n"
            "  머신러닝          : 데이터 + 답    →  규칙\n"
            "\n"
            "스팸 필터를 예로 들면, 예전에는 '광고라는 단어가 있으면 스팸' 같은 규칙을\n"
            "사람이 하나하나 썼다. 머신러닝은 스팸 메일 10만 통을 보여주고\n"
            "'무엇이 스팸을 스팸으로 만드는가'를 스스로 찾아내게 한다.\n"
            "\n"
            "[크게 세 갈래]\n"
            "  1) 지도학습 (supervised)   — 정답이 있는 데이터로 배운다\n"
            "     · 회귀(regression)  : 숫자를 맞힌다 (집값, 매출, 온도)\n"
            "     · 분류(classification): 종류를 맞힌다 (스팸/정상, 개/고양이)\n"
            "  2) 비지도학습 (unsupervised) — 정답 없이 구조를 찾는다\n"
            "     · 군집(clustering)  : 비슷한 것끼리 묶는다 (고객 세분화)\n"
            "     · 차원 축소         : 열이 너무 많을 때 중요한 것만 남긴다\n"
            "  3) 강화학습 (reinforcement) — 시행착오로 보상을 최대화한다 (게임 AI, 로봇)\n"
            "\n"
            "  실무의 90% 는 지도학습이다. 이 단계도 지도학습에 집중한다.\n"
            "\n"
            "[반드시 이해해야 할 개념 — 과적합]\n"
            "  시험 공부에 비유하면,\n"
            "    · 문제집을 통째로 외운 학생 → 문제집은 100점, 실제 시험은 40점\n"
            "    · 원리를 이해한 학생        → 문제집 85점, 실제 시험도 82점\n"
            "  앞이 과적합(overfitting)이다. 훈련 데이터에만 잘 맞는 상태다.\n"
            "\n"
            "  그래서 데이터를 반드시 나눈다.\n"
            "    훈련(train) 70% : 학습에 쓴다\n"
            "    검증(test)  30% : 성능 측정에만 쓴다. 학습에는 절대 쓰지 않는다.\n"
            "  검증 데이터를 학습에 쓰는 것을 '데이터 유출(leakage)'이라 하며,\n"
            "  실무에서 가장 흔하고 치명적인 실수다.\n"
            "\n"
            "[이 단계 커리큘럼]\n"
            "  ds3-02  선형회귀 — 경사하강법으로 직선 찾기 (학습의 원리)\n"
            "  ds3-03  분류와 평가지표 — k-NN, 정확도·정밀도·재현율\n"
            "  (이후 확장 예정)\n"
            "    · 로지스틱 회귀 · 의사결정나무 · 랜덤포레스트\n"
            "    · 교차검증 · 하이퍼파라미터 튜닝\n"
            "    · k-means 군집 · PCA 차원축소\n"
            "    · scikit-learn 실전 사용법\n"
            "\n"
            "[선행 조건]\n"
            "  1단계의 numpy 배열·브로드캐스팅, 2단계의 표준화를 이해하고 있어야 한다.\n"
            "  특히 (x - 평균) / 표준편차 표준화는 머신러닝에서 거의 항상 필요하다."
        ),
        usage="3단계 학습의 지도. 어디쯤 왔는지 헷갈릴 때 돌아와서 보면 된다.",
        cons="개념 정리 위주라 실행 코드는 간단하다. 실제 구현은 다음 레슨부터다.",
        code=(
            "import numpy as np\n"
            "\n"
            "# 훈련/검증 데이터 나누기 — 머신러닝의 첫 단계\n"
            "rng = np.random.default_rng(42)\n"
            "\n"
            "X = rng.normal(50, 15, 20).round(1)      # 특성(공부 시간 등)\n"
            "y = (X * 1.5 + rng.normal(0, 5, 20)).round(1)   # 정답(점수)\n"
            "\n"
            "idx = rng.permutation(len(X))            # 먼저 섞는다 (편향 방지)\n"
            "cut = int(len(X) * 0.7)\n"
            "train_idx, test_idx = idx[:cut], idx[cut:]\n"
            "\n"
            "X_train, y_train = X[train_idx], y[train_idx]\n"
            "X_test,  y_test  = X[test_idx],  y[test_idx]\n"
            "\n"
            "print('전체:', len(X), '건')\n"
            "print('훈련:', len(X_train), '건 →', X_train)\n"
            "print('검증:', len(X_test), '건 →', X_test)\n"
            "print()\n"
            "print('※ 검증 데이터는 학습에 절대 쓰지 않는다.')\n"
            "print('   여기를 어기면 성능이 좋아 보이지만 실제로는 쓸모없는 모델이 된다.')\n"
        ),
    ),

    Lesson(
        id="ds3-02-linreg",
        lang="datasci", level=STAGE,
        title="선형회귀 — 경사하강법",
        summary="기계가 '학습'한다는 게 무슨 뜻인지 코드로",
        explanation=(
            "[개요]\n"
            "가장 단순한 학습 모델은 직선이다.\n"
            "  예측값 ŷ = w × x + b        (w=기울기, b=절편)\n"
            "공부 시간 x 로 점수 y 를 예측한다고 하면, 좋은 w 와 b 를 찾는 게 학습이다.\n"
            "\n"
            "[1단계 — 얼마나 틀렸는지 재기 (손실 함수)]\n"
            "  MSE(평균제곱오차) = 평균( (실제 - 예측)² )\n"
            "  제곱하는 이유:\n"
            "    · +오차와 -오차가 상쇄되는 것을 막는다\n"
            "    · 큰 오차에 더 큰 벌점을 준다\n"
            "  이 값이 작을수록 좋은 모델이다. 학습의 목표는 MSE 를 최소로 만드는 것이다.\n"
            "\n"
            "[2단계 — 어느 방향으로 고칠지 찾기 (경사하강법)]\n"
            "  안개 낀 산에서 가장 낮은 곳으로 내려간다고 상상하자.\n"
            "  전체 지형은 안 보이지만, 발밑의 기울기는 느낄 수 있다.\n"
            "  가장 가파르게 내려가는 방향으로 한 걸음씩 반복하면 결국 골짜기에 닿는다.\n"
            "\n"
            "  기울기(gradient)를 수식으로 구하면 (n은 데이터 개수):\n"
            "    ∂MSE/∂w = -2/n × Σ x(y - ŷ)\n"
            "    ∂MSE/∂b = -2/n × Σ (y - ŷ)\n"
            "\n"
            "  그리고 반대 방향으로 조금씩 이동한다.\n"
            "    w = w - 학습률 × 기울기\n"
            "\n"
            "[3단계 — 학습률(learning rate)]\n"
            "  한 걸음의 보폭이다. 이 값이 학습의 성패를 좌우한다.\n"
            "    너무 작으면 : 수렴이 한없이 느리다\n"
            "    너무 크면   : 골짜기를 건너뛰어 발산한다(손실이 nan 이 된다)\n"
            "  보통 0.001 ~ 0.1 사이에서 시작해 조정한다.\n"
            "\n"
            "[코드 분석]\n"
            "  X_norm = (X - X.mean()) / X.std()\n"
            "         → 표준화. 이걸 빼먹으면 x 값이 커서 기울기가 폭발한다.\n"
            "            머신러닝에서 전처리가 필수인 이유가 여기서 드러난다.\n"
            "  y_pred = w * X_norm + b\n"
            "         → 현재 w, b 로 전체 예측. 브로드캐스팅 덕에 반복문이 없다.\n"
            "  error = y - y_pred\n"
            "         → 각 데이터의 오차.\n"
            "  loss = (error ** 2).mean()\n"
            "         → MSE. 이 숫자가 줄어드는 것이 곧 '학습되고 있다'는 증거다.\n"
            "  dw = -2 * (X_norm * error).mean()\n"
            "  db = -2 * error.mean()\n"
            "         → 기울기. 수식을 그대로 옮긴 것이다.\n"
            "  w -= lr * dw\n"
            "         → 기울기 반대 방향으로 이동. 이 한 줄이 '학습'의 전부다.\n"
            "  for epoch in range(200)\n"
            "         → 에폭(epoch)은 전체 데이터를 한 번 다 본 횟수다.\n"
            "            200번 반복하며 조금씩 개선한다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 손실이 nan 이 되면 학습률이 너무 크다. 10분의 1로 줄여보자.\n"
            "  • 손실이 거의 안 줄면 학습률이 너무 작거나 표준화를 안 한 것이다.\n"
            "  • 이 코드가 딥러닝의 축소판이다. 신경망도 똑같이 손실을 정의하고\n"
            "    기울기를 구해 반대로 이동한다. 층이 여러 개일 뿐이다."
        ),
        usage="머신러닝·딥러닝 전체를 관통하는 원리. 여기를 이해하면 나머지는 응용이다.",
        cons="직선 관계만 표현할 수 있다. 곡선 관계는 특성을 추가하거나 다른 모델이 필요하다.",
        code=(
            "import numpy as np\n"
            "\n"
            "rng = np.random.default_rng(42)\n"
            "\n"
            "# 데이터: 공부시간 → 점수 (실제 관계는 y = 7x + 30 + 잡음)\n"
            "X = rng.uniform(1, 10, 50)\n"
            "y = 7 * X + 30 + rng.normal(0, 5, 50)\n"
            "\n"
            "# 표준화 — 필수 전처리\n"
            "X_mean, X_std = X.mean(), X.std()\n"
            "X_norm = (X - X_mean) / X_std\n"
            "\n"
            "w, b = 0.0, 0.0      # 시작점\n"
            "lr = 0.1             # 학습률\n"
            "\n"
            "print('epoch    손실(MSE)        w        b')\n"
            "for epoch in range(201):\n"
            "    y_pred = w * X_norm + b\n"
            "    error = y - y_pred\n"
            "    loss = (error ** 2).mean()\n"
            "\n"
            "    dw = -2 * (X_norm * error).mean()\n"
            "    db = -2 * error.mean()\n"
            "\n"
            "    w -= lr * dw\n"
            "    b -= lr * db\n"
            "\n"
            "    if epoch % 40 == 0:\n"
            "        print(f'{epoch:5d}  {loss:12.4f}  {w:7.3f}  {b:7.3f}')\n"
            "\n"
            "# 표준화된 w 를 원래 스케일로 되돌리기\n"
            "real_w = w / X_std\n"
            "real_b = b - w * X_mean / X_std\n"
            "print()\n"
            "print(f'학습 결과 : y = {real_w:.2f}x + {real_b:.2f}')\n"
            "print(f'실제 정답 : y = 7.00x + 30.00')\n"
            "\n"
            "# 예측해 보기\n"
            "for h in [3, 5, 8]:\n"
            "    print(f'  {h}시간 공부 → 예상 {real_w * h + real_b:.1f}점')\n"
        ),
    ),

    Lesson(
        id="ds3-03-classify",
        lang="datasci", level=STAGE,
        title="분류와 평가지표",
        summary="k-NN 직접 구현 · 정확도만 보면 안 되는 이유",
        explanation=(
            "[개요]\n"
            "분류는 '이것이 어느 종류인가'를 맞히는 문제다.\n"
            "가장 직관적인 분류 모델이 k-NN(k-Nearest Neighbors, k-최근접 이웃)이다.\n"
            "\n"
            "[k-NN 의 원리 — 학습이 없는 학습]\n"
            "  새 데이터가 들어오면,\n"
            "    1) 기존 데이터 전부와의 거리를 잰다\n"
            "    2) 가까운 k 개를 고른다\n"
            "    3) 그 k 개의 다수결로 종류를 정한다\n"
            "  '끼리끼리 모인다'는 상식을 그대로 알고리즘으로 만든 것이다.\n"
            "  학습 단계가 따로 없어서 게으른 학습(lazy learning)이라 부른다.\n"
            "\n"
            "[거리 — 유클리드 거리]\n"
            "  두 점 사이의 직선 거리다. 피타고라스 정리 그대로다.\n"
            "    d = √( (x1-x2)² + (y1-y2)² )\n"
            "  특성의 단위가 다르면(키 cm, 몸무게 kg) 큰 단위가 거리를 지배한다.\n"
            "  그래서 k-NN 도 표준화가 필수다.\n"
            "\n"
            "[평가지표 — 정확도만 보면 안 되는 이유]\n"
            "  암 진단 모델이 있다. 실제 환자는 1000명 중 10명뿐이다.\n"
            "  '무조건 정상'이라고 답하는 모델의 정확도는 99% 다.\n"
            "  하지만 환자를 한 명도 못 찾았으므로 완전히 쓸모없다.\n"
            "  이것이 '불균형 데이터'에서 정확도가 속이는 대표적인 예다.\n"
            "\n"
            "  혼동 행렬(confusion matrix)\n"
            "                 예측:양성   예측:음성\n"
            "    실제:양성        TP          FN     ← 놓친 환자\n"
            "    실제:음성        FP          TN\n"
            "\n"
            "  정확도(accuracy)  = (TP+TN) / 전체        전체 중 맞힌 비율\n"
            "  정밀도(precision) = TP / (TP+FP)          양성이라 한 것 중 진짜 비율\n"
            "  재현율(recall)    = TP / (TP+FN)          진짜 양성 중 찾아낸 비율\n"
            "  F1 = 2 × 정밀도 × 재현율 / (정밀도 + 재현율)   둘의 조화평균\n"
            "\n"
            "  어느 걸 중시할지는 상황이 정한다.\n"
            "    · 암 진단 → 재현율. 놓치면 사람이 죽는다. 오진은 재검사로 걸러진다.\n"
            "    · 스팸 필터 → 정밀도. 중요한 메일이 스팸함에 가면 안 된다.\n"
            "\n"
            "[코드 분석]\n"
            "  np.sqrt(((train - point) ** 2).sum(axis=1))\n"
            "         → 모든 훈련 데이터와의 거리를 한 번에 계산한다.\n"
            "            브로드캐스팅으로 반복문 없이 처리된다.\n"
            "            axis=1 은 각 행(각 데이터)별로 합산한다는 뜻이다.\n"
            "  np.argsort(dist)[:k]\n"
            "         → 거리가 작은 순으로 정렬한 인덱스에서 앞 k 개.\n"
            "  np.bincount(labels).argmax()\n"
            "         → 라벨별 개수를 세고 가장 많은 것의 번호. 다수결이다.\n"
            "  (pred == y_test).mean()\n"
            "         → 정확도. True=1 로 평균내면 맞힌 비율이 된다.\n"
            "\n"
            "[유의 사항]\n"
            "  • k 는 보통 홀수로 정한다. 짝수면 동점이 생긴다.\n"
            "  • k 가 너무 작으면(1) 잡음에 민감하고, 너무 크면 경계가 뭉개진다.\n"
            "  • k-NN 은 예측할 때마다 전체 데이터와 거리를 재므로 데이터가 크면 매우 느리다.\n"
            "  • 불균형 데이터에서는 정확도를 믿지 말자. 재현율·정밀도를 함께 봐야 한다."
        ),
        usage="분류 문제의 출발점. 평가지표 개념은 모든 분류 모델에 그대로 적용된다.",
        cons="데이터가 커지면 예측이 느리다. 특성이 많아지면(차원의 저주) 거리 개념 자체가 무의미해진다.",
        code=(
            "import numpy as np\n"
            "\n"
            "rng = np.random.default_rng(42)\n"
            "\n"
            "# 두 그룹: 0=불합격군, 1=합격군 (공부시간, 출석률)\n"
            "g0 = rng.normal([3, 60], [1.0, 8], size=(30, 2))\n"
            "g1 = rng.normal([7, 85], [1.0, 8], size=(30, 2))\n"
            "X = np.vstack([g0, g1])\n"
            "y = np.array([0] * 30 + [1] * 30)\n"
            "\n"
            "# 표준화 (거리 기반이라 필수)\n"
            "X = (X - X.mean(axis=0)) / X.std(axis=0)\n"
            "\n"
            "# 훈련/검증 분리\n"
            "idx = rng.permutation(len(X))\n"
            "cut = int(len(X) * 0.7)\n"
            "X_train, y_train = X[idx[:cut]], y[idx[:cut]]\n"
            "X_test,  y_test  = X[idx[cut:]], y[idx[cut:]]\n"
            "\n"
            "def knn_predict(point, X_train, y_train, k=5):\n"
            "    dist = np.sqrt(((X_train - point) ** 2).sum(axis=1))\n"
            "    nearest = np.argsort(dist)[:k]\n"
            "    return int(np.bincount(y_train[nearest]).argmax())\n"
            "\n"
            "pred = np.array([knn_predict(p, X_train, y_train, k=5) for p in X_test])\n"
            "\n"
            "# 혼동 행렬\n"
            "tp = int(((pred == 1) & (y_test == 1)).sum())\n"
            "fp = int(((pred == 1) & (y_test == 0)).sum())\n"
            "fn = int(((pred == 0) & (y_test == 1)).sum())\n"
            "tn = int(((pred == 0) & (y_test == 0)).sum())\n"
            "\n"
            "print('-- 혼동 행렬 --')\n"
            "print(f'          예측1  예측0')\n"
            "print(f'  실제1   {tp:4d}  {fn:5d}')\n"
            "print(f'  실제0   {fp:4d}  {tn:5d}')\n"
            "\n"
            "acc = (tp + tn) / len(y_test)\n"
            "prec = tp / (tp + fp) if (tp + fp) else 0.0\n"
            "rec = tp / (tp + fn) if (tp + fn) else 0.0\n"
            "f1 = 2 * prec * rec / (prec + rec) if (prec + rec) else 0.0\n"
            "\n"
            "print()\n"
            "print(f'정확도 : {acc:.3f}')\n"
            "print(f'정밀도 : {prec:.3f}')\n"
            "print(f'재현율 : {rec:.3f}')\n"
            "print(f'F1     : {f1:.3f}')\n"
            "\n"
            "# k 를 바꿔가며 비교\n"
            "print('\\n-- k 값에 따른 정확도 --')\n"
            "for k in [1, 3, 5, 7, 9]:\n"
            "    p = np.array([knn_predict(pt, X_train, y_train, k) for pt in X_test])\n"
            "    print(f'  k={k}: {(p == y_test).mean():.3f}')\n"
        ),
    ),
]
