"""2단계 — 통계 · 전처리.

pandas 로 표 데이터를 다루고, 실무에서 가장 오래 붙잡게 되는
'데이터 씻기(전처리)'와 '요약해서 읽기(기술통계)'를 익힌다.
"""

from engine.models import Lesson

STAGE = "2. 통계 · 전처리"

LESSONS = [

    Lesson(
        id="ds2-01-dataframe",
        lang="datasci", level=STAGE,
        title="DataFrame 첫걸음",
        summary="파이썬으로 만드는 엑셀 시트",
        explanation=(
            "[개요]\n"
            "DataFrame 은 pandas 의 핵심이자 '파이썬 안의 엑셀 시트'다.\n"
            "행(row)과 열(column)이 있고, 열마다 이름과 타입이 있다.\n"
            "1단계의 '딕셔너리 리스트'를 그대로 넣으면 바로 표가 된다.\n"
            "\n"
            "[구성 요소]\n"
            "  • DataFrame : 표 전체 (2차원)\n"
            "  • Series    : 열 하나 (1차원). df['score'] 를 꺼내면 Series 다.\n"
            "  • Index     : 각 행의 이름표. 지정하지 않으면 0,1,2... 가 자동으로 붙는다.\n"
            "\n"
            "[만드는 방법 두 가지]\n"
            "  1) 열 기준 — 딕셔너리의 키가 열 이름, 값이 열 전체\n"
            "     pd.DataFrame({'name': [...], 'score': [...]})\n"
            "  2) 행 기준 — 딕셔너리 하나가 한 행\n"
            "     pd.DataFrame([{'name': ..., 'score': ...}, ...])\n"
            "  실무에서는 API 응답이 대개 2번 형태로 오고, 직접 만들 땐 1번이 편하다.\n"
            "\n"
            "[코드 분석]\n"
            "  import pandas as pd\n"
            "         → as pd 는 전 세계 공통 관례다.\n"
            "  df = pd.DataFrame({...})\n"
            "         → 딕셔너리로 표를 만든다. 각 리스트의 길이가 같아야 한다.\n"
            "            길이가 다르면 'All arrays must be of the same length' 에러가 난다.\n"
            "  df.shape\n"
            "         → (행 개수, 열 개수). 데이터를 받으면 가장 먼저 확인하는 값이다.\n"
            "  df.columns\n"
            "         → 열 이름 목록.\n"
            "  df.dtypes\n"
            "         → 열별 타입. 숫자여야 할 열이 object(문자열)로 되어 있으면\n"
            "            계산이 안 되므로 여기서 문제를 미리 잡아낸다.\n"
            "  df['score']\n"
            "         → 열 하나를 꺼낸다. 결과는 Series 다.\n"
            "  df[['name', 'score']]\n"
            "         → 대괄호를 두 겹 쓰면 여러 열을 표(DataFrame) 형태로 꺼낸다.\n"
            "            한 겹은 Series, 두 겹은 DataFrame — 자주 헷갈리는 부분이다.\n"
            "  df.iloc[0]\n"
            "         → 위치(0번째)로 행을 꺼낸다. i 는 integer 의 i 다.\n"
            "  df.loc[0]\n"
            "         → 인덱스 이름이 0인 행을 꺼낸다. 지금은 결과가 같지만\n"
            "            인덱스를 이름으로 바꾸면 완전히 달라진다.\n"
            "  df.set_index('name')\n"
            "         → name 열을 행 이름표로 만든다. 이후 df.loc['김철수'] 로 조회할 수 있다.\n"
            "\n"
            "[유의 사항]\n"
            "  • df['score'] 는 Series, df[['score']] 는 DataFrame 이다. 모양이 다르다.\n"
            "  • pandas 는 불러오는 데 약 2초 걸린다. 작은 계산에는 오히려 무겁다.\n"
            "  • 대부분의 pandas 함수는 원본을 바꾸지 않고 '새 표'를 돌려준다.\n"
            "    결과를 변수에 다시 담지 않으면 아무 일도 일어나지 않는다."
        ),
        usage="CSV·DB·API 에서 받은 표 데이터를 다루는 모든 작업의 출발점.",
        cons="메모리에 전부 올리는 방식이라 수 GB 데이터엔 부적합하다. 그 규모는 Polars/Spark 나 DB 를 쓴다.",
        code=(
            "import pandas as pd\n"
            "\n"
            "df = pd.DataFrame({\n"
            "    'name':  ['김철수', '이영희', '박민수', '최지우', '정하늘'],\n"
            "    'dept':  ['영업', '개발', '영업', '개발', '기획'],\n"
            "    'score': [88, 92, 79, 95, 61],\n"
            "    'year':  [3, 5, 2, 7, 1],\n"
            "})\n"
            "\n"
            "print(df)\n"
            "print('모양   :', df.shape)\n"
            "print('열 이름:', list(df.columns))\n"
            "print('타입:\\n', df.dtypes)\n"
            "\n"
            "print('-- score 열 (Series) --')\n"
            "print(df['score'])\n"
            "\n"
            "print('-- 두 열 (DataFrame) --')\n"
            "print(df[['name', 'score']])\n"
            "\n"
            "print('-- 0번 행 --')\n"
            "print(df.iloc[0])\n"
            "\n"
            "print('-- 이름을 인덱스로 --')\n"
            "print(df.set_index('name').loc['최지우'])\n"
        ),
    ),

    Lesson(
        id="ds2-02-explore",
        lang="datasci", level=STAGE,
        title="데이터 훑어보기",
        summary="head · info · describe — 처음 3분에 하는 일",
        explanation=(
            "[개요]\n"
            "새 데이터를 받으면 바로 분석에 들어가지 않는다.\n"
            "먼저 '어떻게 생긴 데이터인가'를 확인한다. 이 과정을 EDA(탐색적 데이터 분석)라 한다.\n"
            "숙련자일수록 이 단계에 시간을 많이 쓴다. 여기서 놓친 문제는 뒤에서 반드시 터진다.\n"
            "\n"
            "[처음 3분에 하는 4가지]\n"
            "  1) df.shape      → 몇 행 몇 열인가\n"
            "  2) df.head()     → 실제 값이 어떻게 생겼나\n"
            "  3) df.info()     → 타입은 맞나, 빠진 값은 없나\n"
            "  4) df.describe() → 숫자 열의 범위가 상식적인가\n"
            "\n"
            "[describe() 읽는 법]\n"
            "  count  개수 (전체 행 수보다 적으면 결측치가 있다는 뜻)\n"
            "  mean   평균\n"
            "  std    표준편차 (클수록 값이 흩어져 있다)\n"
            "  min    최솟값 (음수면 안 되는 값에 음수가 있는지 확인)\n"
            "  25%    하위 25% 지점\n"
            "  50%    중앙값 (mean 과 크게 다르면 분포가 한쪽으로 치우친 것)\n"
            "  75%    상위 25% 지점\n"
            "  max    최댓값 (나이가 200 같은 말도 안 되는 값이 여기서 잡힌다)\n"
            "\n"
            "[코드 분석]\n"
            "  df.head(3)\n"
            "         → 위에서 3줄. 숫자를 안 주면 5줄이다. tail() 은 아래쪽이다.\n"
            "            데이터가 뒤쪽에서 깨진 경우가 있어 head 와 tail 을 함께 보는 게 좋다.\n"
            "  df.info()\n"
            "         → 열별 타입과 '비어 있지 않은 값의 개수'를 보여준다.\n"
            "            전체가 5행인데 non-null 이 4면 그 열에 결측치가 1개 있는 것이다.\n"
            "  df.describe()\n"
            "         → 숫자 열의 요약 통계. 문자 열은 기본적으로 빠진다.\n"
            "  df.describe(include='object')\n"
            "         → 문자 열 요약. unique(고유값 수), top(최빈값), freq(그 빈도)를 보여준다.\n"
            "  df['dept'].value_counts()\n"
            "         → 범주별 개수. 어떤 값이 몇 번 나오는지 센다.\n"
            "            분류 데이터를 볼 때 가장 먼저 쓰는 함수다.\n"
            "  df['dept'].unique()\n"
            "         → 중복 없는 값 목록. 오타로 '영업'과 '영업 '(뒤에 공백)이\n"
            "            따로 잡히는 문제를 여기서 발견한다.\n"
            "  df.isna().sum()\n"
            "         → 열별 결측치 개수. 전처리 계획을 세우는 근거가 된다.\n"
            "\n"
            "[유의 사항]\n"
            "  • describe() 의 count 가 행 수보다 작으면 반드시 결측치를 먼저 처리해야 한다.\n"
            "  • mean 과 50%(중앙값)가 크게 벌어지면 이상치나 치우친 분포를 의심하자.\n"
            "  • info() 에서 숫자여야 할 열이 object 면, 값에 문자가 섞여 있다는 신호다."
        ),
        usage="데이터를 받은 직후 반드시 하는 첫 단계. 여기서 전처리 계획이 나온다.",
        cons="요약값만 보면 분포의 모양(봉우리가 두 개인지 등)은 알 수 없다. 결국 시각화가 필요하다.",
        code=(
            "import pandas as pd\n"
            "import numpy as np\n"
            "\n"
            "df = pd.DataFrame({\n"
            "    'name':  ['김철수', '이영희', '박민수', '최지우', '정하늘', '한서준'],\n"
            "    'dept':  ['영업', '개발', '영업', '개발', '기획', '개발'],\n"
            "    'score': [88, 92, 79, 95, 61, np.nan],\n"
            "    'year':  [3, 5, 2, 7, 1, 4],\n"
            "})\n"
            "\n"
            "print('모양:', df.shape)\n"
            "print('\\n-- head(3) --')\n"
            "print(df.head(3))\n"
            "\n"
            "print('\\n-- info() --')\n"
            "df.info()\n"
            "\n"
            "print('\\n-- describe() --')\n"
            "print(df.describe())\n"
            "\n"
            "print('\\n-- 부서별 인원 --')\n"
            "print(df['dept'].value_counts())\n"
            "\n"
            "print('\\n-- 고유 부서 --')\n"
            "print(df['dept'].unique())\n"
            "\n"
            "print('\\n-- 결측치 개수 --')\n"
            "print(df.isna().sum())\n"
        ),
    ),

    Lesson(
        id="ds2-03-filter",
        lang="datasci", level=STAGE,
        title="행 필터링 · 열 선택",
        summary="조건으로 원하는 데이터만 남기기",
        explanation=(
            "[개요]\n"
            "'개발팀 중 점수 90 이상' 같은 조건 추출은 분석에서 가장 자주 하는 일이다.\n"
            "원리는 1단계의 numpy 불리언 마스크와 완전히 같다.\n"
            "\n"
            "[동작 원리]\n"
            "  df['score'] >= 90\n"
            "     → True/False 로 채워진 Series 가 나온다 (마스크)\n"
            "  df[df['score'] >= 90]\n"
            "     → True 인 행만 남긴 새 DataFrame\n"
            "\n"
            "  numpy 의 arr[arr >= 90] 과 똑같은 구조다. 대상이 배열에서 표로 바뀌었을 뿐이다.\n"
            "\n"
            "[조건 여러 개]\n"
            "  반드시 & (그리고), | (또는) 를 쓰고 각 조건을 괄호로 감싼다.\n"
            "     df[(df['dept'] == '개발') & (df['score'] >= 90)]\n"
            "  파이썬의 and/or 를 쓰면 'truth value is ambiguous' 에러가 난다.\n"
            "  괄호를 빠뜨리면 우선순위 때문에 엉뚱하게 계산되므로 습관을 들여야 한다.\n"
            "\n"
            "[코드 분석]\n"
            "  df[df['score'] >= 90]\n"
            "         → 점수 90 이상인 행만.\n"
            "  df[(df['dept'] == '개발') & (df['score'] >= 90)]\n"
            "         → 두 조건을 동시에 만족하는 행.\n"
            "  df[df['dept'].isin(['개발', '기획'])]\n"
            "         → 목록 중 하나에 해당하는 행. == 를 여러 번 | 로 잇는 것보다 훨씬 깔끔하다.\n"
            "  df[~(df['dept'] == '영업')]\n"
            "         → ~ 는 조건을 뒤집는다(NOT). '영업이 아닌' 행.\n"
            "            df[df['dept'] != '영업'] 와 같은 결과다.\n"
            "  df.query('score >= 90 and dept == \"개발\"')\n"
            "         → 조건을 문자열로 쓰는 방식. and/or 를 그대로 쓸 수 있어 읽기 쉽다.\n"
            "            열 이름에 공백이 없을 때만 편하게 쓸 수 있다.\n"
            "  df.loc[df['score'] >= 90, 'name']\n"
            "         → loc[행 조건, 열 이름]. 조건에 맞는 행에서 특정 열만 꺼낸다.\n"
            "            필터링과 열 선택을 한 번에 하는 표준 방법이다.\n"
            "  df.loc[df['score'] >= 90, ['name', 'score']]\n"
            "         → 열이 여러 개면 리스트로 준다.\n"
            "  .reset_index(drop=True)\n"
            "         → 필터링하면 인덱스가 0,3,5 처럼 띄엄띄엄 남는다.\n"
            "            이걸 0,1,2 로 다시 매긴다. drop=True 는 옛 인덱스를 버리라는 뜻이다.\n"
            "\n"
            "[유의 사항]\n"
            "  • and/or/not 대신 &, |, ~ 를 쓴다. 각 조건은 괄호로 감싼다.\n"
            "  • 필터링 결과는 새 DataFrame 이다. 변수에 담지 않으면 사라진다.\n"
            "  • 필터 결과를 바로 수정하면 SettingWithCopyWarning 이 뜰 수 있다.\n"
            "    수정할 거면 .copy() 로 명확히 복사본을 만들자."
        ),
        usage="특정 조건의 고객·기간·지역만 분석할 때. 이상치 제거에도 그대로 쓴다.",
        cons="조건이 5~6개로 늘면 한 줄이 너무 길어진다. 그럴 땐 마스크를 변수로 나눠서 조합하는 게 낫다.",
        code=(
            "import pandas as pd\n"
            "\n"
            "df = pd.DataFrame({\n"
            "    'name':  ['김철수', '이영희', '박민수', '최지우', '정하늘', '한서준'],\n"
            "    'dept':  ['영업', '개발', '영업', '개발', '기획', '개발'],\n"
            "    'score': [88, 92, 79, 95, 61, 90],\n"
            "    'year':  [3, 5, 2, 7, 1, 4],\n"
            "})\n"
            "\n"
            "print('-- 90점 이상 --')\n"
            "print(df[df['score'] >= 90])\n"
            "\n"
            "print('\\n-- 개발팀 & 90점 이상 --')\n"
            "print(df[(df['dept'] == '개발') & (df['score'] >= 90)])\n"
            "\n"
            "print('\\n-- 개발 또는 기획 (isin) --')\n"
            "print(df[df['dept'].isin(['개발', '기획'])])\n"
            "\n"
            "print('\\n-- 영업이 아닌 (~) --')\n"
            "print(df[~(df['dept'] == '영업')])\n"
            "\n"
            "print('\\n-- query 방식 --')\n"
            "print(df.query('score >= 90 and dept == \"개발\"'))\n"
            "\n"
            "print('\\n-- 조건 + 열 선택 --')\n"
            "print(df.loc[df['score'] >= 90, ['name', 'score']].reset_index(drop=True))\n"
        ),
    ),

    Lesson(
        id="ds2-04-newcolumn",
        lang="datasci", level=STAGE,
        title="새 열 만들기 · 값 변환",
        summary="파생 변수 · apply · map",
        explanation=(
            "[개요]\n"
            "원본 데이터에 없는 열을 계산해서 만드는 것을 '파생 변수(derived feature)'라 한다.\n"
            "  매출 - 비용 = 이익, 점수 → 등급, 생년월일 → 나이\n"
            "머신러닝 성능의 상당 부분이 이 파생 변수를 얼마나 잘 만드느냐에 달려 있다.\n"
            "이 작업을 특히 '피처 엔지니어링(feature engineering)'이라 부른다.\n"
            "\n"
            "[만드는 3가지 방법]\n"
            "  1) 벡터 연산  df['b'] = df['a'] * 2          가장 빠름. 우선 이걸 시도한다.\n"
            "  2) np.where   df['b'] = np.where(조건, A, B)  조건 2갈래일 때\n"
            "  3) apply      df['b'] = df['a'].apply(함수)   복잡한 규칙일 때. 느리다.\n"
            "\n"
            "[코드 분석]\n"
            "  df['total'] = df['score'] + df['bonus']\n"
            "         → 열끼리 계산해 새 열을 만든다. 같은 행끼리 자동으로 계산된다.\n"
            "            반복문이 전혀 필요 없다.\n"
            "  df['rate'] = (df['score'] / 100 * 100).round(1)\n"
            "         → 계산 후 반올림. round() 는 열 전체에 적용된다.\n"
            "  df['pass'] = np.where(df['score'] >= 80, '합격', '불합격')\n"
            "         → 조건에 따라 두 값 중 하나. 엑셀의 IF 와 같다.\n"
            "  def grade(s): ...\n"
            "  df['grade'] = df['score'].apply(grade)\n"
            "         → 값 하나하나에 함수를 적용한다.\n"
            "            조건이 3갈래 이상이면 np.where 보다 이게 읽기 쉽다.\n"
            "            단 파이썬 함수를 행마다 호출하므로 느리다. 큰 데이터에선 주의.\n"
            "  df['dept_en'] = df['dept'].map({'영업': 'Sales', ...})\n"
            "         → 딕셔너리로 값을 치환한다. 코드값 → 사람이 읽는 이름 변환에 쓴다.\n"
            "            매핑에 없는 값은 NaN(빈 값)이 되므로 주의해야 한다.\n"
            "  pd.cut(df['score'], bins=[0,70,80,90,100], labels=[...])\n"
            "         → 연속된 숫자를 구간으로 나눠 범주로 만든다.\n"
            "            나이 → 연령대, 점수 → 등급 처럼 '구간화(binning)'에 쓴다.\n"
            "            구간은 기본적으로 '초과 ~ 이하' 다. 70 은 0~70 구간에 들어간다.\n"
            "  df.drop(columns=['bonus'])\n"
            "         → 열 삭제. 원본은 그대로고 새 표를 돌려준다.\n"
            "  df.rename(columns={'score': '점수'})\n"
            "         → 열 이름 바꾸기.\n"
            "\n"
            "[유의 사항]\n"
            "  • apply 는 편하지만 느리다. 벡터 연산으로 가능하면 그쪽을 먼저 쓰자.\n"
            "  • map 에 없는 값은 조용히 NaN 이 된다. 변환 후 isna().sum() 으로 확인하는 습관.\n"
            "  • pd.cut 의 구간 경계 포함 여부(right=True/False)를 확인하지 않으면\n"
            "    경계값이 엉뚱한 등급으로 들어간다."
        ),
        usage="분석 목적에 맞는 지표를 만들 때. 머신러닝 입력 데이터를 준비하는 핵심 작업.",
        cons="파생 변수를 무분별하게 늘리면 열이 수백 개가 되어 오히려 모델 성능이 떨어진다.",
        code=(
            "import pandas as pd\n"
            "import numpy as np\n"
            "\n"
            "df = pd.DataFrame({\n"
            "    'name':  ['김철수', '이영희', '박민수', '최지우', '정하늘'],\n"
            "    'dept':  ['영업', '개발', '영업', '개발', '기획'],\n"
            "    'score': [88, 92, 79, 95, 61],\n"
            "    'bonus': [5, 0, 10, 0, 15],\n"
            "})\n"
            "\n"
            "df['total'] = df['score'] + df['bonus']\n"
            "df['pass'] = np.where(df['total'] >= 90, '합격', '불합격')\n"
            "\n"
            "def grade(s):\n"
            "    if s >= 95: return 'A'\n"
            "    if s >= 85: return 'B'\n"
            "    if s >= 75: return 'C'\n"
            "    return 'D'\n"
            "\n"
            "df['grade'] = df['total'].apply(grade)\n"
            "df['dept_en'] = df['dept'].map({'영업': 'Sales', '개발': 'Dev', '기획': 'Plan'})\n"
            "df['band'] = pd.cut(df['score'], bins=[0, 70, 80, 90, 100],\n"
            "                    labels=['70이하', '70대', '80대', '90대'])\n"
            "\n"
            "print(df)\n"
            "print('\\n-- bonus 열 제거 --')\n"
            "print(df.drop(columns=['bonus', 'dept_en']).head(3))\n"
            "print('\\n-- 열 이름 변경 --')\n"
            "print(df.rename(columns={'score': '점수', 'total': '총점'}).columns.tolist())\n"
        ),
    ),

    Lesson(
        id="ds2-05-sort",
        lang="datasci", level=STAGE,
        title="정렬 · 상위 N · 순위",
        summary="sort_values · nlargest · rank",
        explanation=(
            "[개요]\n"
            "리포트는 대개 '상위 10개'로 끝난다. pandas 의 정렬 도구를 익혀두면\n"
            "1단계에서 lambda 로 하던 일을 훨씬 짧게 쓸 수 있다.\n"
            "\n"
            "[코드 분석]\n"
            "  df.sort_values('score', ascending=False)\n"
            "         → score 기준 내림차순. ascending=True(기본)면 오름차순이다.\n"
            "            1단계의 sorted(rows, key=lambda r: r['score']) 를 대체한다.\n"
            "  df.sort_values(['dept', 'score'], ascending=[True, False])\n"
            "         → 기준이 여러 개. 부서는 가나다순, 그 안에서 점수는 높은 순.\n"
            "            ascending 에 리스트를 주면 기준마다 방향을 따로 정할 수 있다.\n"
            "            1단계의 음수 트릭(-r['score'])보다 훨씬 직관적이다.\n"
            "  df.nlargest(3, 'score')\n"
            "         → 상위 3개. 정렬 후 head(3) 과 결과는 같지만\n"
            "            전체를 정렬하지 않아 데이터가 클 때 더 빠르다.\n"
            "  df.nsmallest(2, 'score')\n"
            "         → 하위 2개.\n"
            "  df['rank'] = df['score'].rank(ascending=False, method='min')\n"
            "         → 등수를 매긴다. method 가 동점 처리 방식이다.\n"
            "            'min'   : 공동 1위 두 명 다음은 3위 (스포츠 방식, 가장 흔함)\n"
            "            'dense' : 공동 1위 다음이 2위 (건너뛰지 않음)\n"
            "            'average': 공동 1,2위를 1.5위로 (기본값, 소수가 나와 어색)\n"
            "            실무에서는 대부분 method='min' 이 자연스럽다.\n"
            "  .astype(int)\n"
            "         → rank 결과는 실수(1.0)라 정수로 바꿔주면 보기 좋다.\n"
            "  df.sort_index()\n"
            "         → 인덱스 기준 정렬. 정렬을 되돌릴 때 쓴다.\n"
            "\n"
            "[유의 사항]\n"
            "  • sort_values 는 새 표를 돌려준다. df 자체는 그대로다.\n"
            "  • 결측치(NaN)는 기본적으로 맨 뒤로 간다. na_position='first' 로 바꿀 수 있다.\n"
            "  • rank 의 기본 method='average' 는 1.5 같은 소수 등수를 만든다.\n"
            "    등수를 정수로 보여줘야 한다면 method='min' 을 명시하자."
        ),
        usage="랭킹 리포트, TOP N 추출, 등수 부여. 분석 결과를 보고서로 만드는 마지막 단계.",
        cons="전체 정렬은 데이터가 클 때 비용이 크다. 상위 몇 개만 필요하면 nlargest 가 낫다.",
        code=(
            "import pandas as pd\n"
            "\n"
            "df = pd.DataFrame({\n"
            "    'name':  ['김철수', '이영희', '박민수', '최지우', '정하늘', '한서준'],\n"
            "    'dept':  ['영업', '개발', '영업', '개발', '기획', '개발'],\n"
            "    'score': [88, 95, 79, 95, 61, 90],\n"
            "})\n"
            "\n"
            "print('-- 점수 내림차순 --')\n"
            "print(df.sort_values('score', ascending=False))\n"
            "\n"
            "print('\\n-- 부서 오름 + 점수 내림 --')\n"
            "print(df.sort_values(['dept', 'score'], ascending=[True, False]))\n"
            "\n"
            "print('\\n-- 상위 3명 --')\n"
            "print(df.nlargest(3, 'score'))\n"
            "\n"
            "print('\\n-- 하위 2명 --')\n"
            "print(df.nsmallest(2, 'score'))\n"
            "\n"
            "df['rank_min'] = df['score'].rank(ascending=False, method='min').astype(int)\n"
            "df['rank_dense'] = df['score'].rank(ascending=False, method='dense').astype(int)\n"
            "print('\\n-- 동점 처리 비교 (95점 두 명) --')\n"
            "print(df.sort_values('score', ascending=False))\n"
        ),
    ),

    Lesson(
        id="ds2-06-groupby",
        lang="datasci", level=STAGE,
        title="groupby — 그룹별 집계",
        summary="분할 → 적용 → 결합 (split-apply-combine)",
        explanation=(
            "[개요]\n"
            "'부서별 평균 점수', '월별 매출 합계' 처럼 그룹으로 묶어 집계하는 일은\n"
            "데이터 분석의 절반이라 해도 과언이 아니다. SQL 의 GROUP BY 와 같은 개념이다.\n"
            "\n"
            "[동작 원리 — split-apply-combine]\n"
            "  1) 분할(split)  : 부서 값이 같은 행끼리 묶는다\n"
            "  2) 적용(apply)  : 각 묶음에 평균을 계산한다\n"
            "  3) 결합(combine): 결과를 하나의 표로 합친다\n"
            "\n"
            "1단계에서 딕셔너리로 직접 짰던 코드가 바로 이 세 단계였다.\n"
            "  totals[d] = totals.get(d, 0) + r['score']   ← 분할 + 적용을 손으로 한 것\n"
            "pandas 는 이걸 한 줄로 줄여준다.\n"
            "\n"
            "[코드 분석]\n"
            "  df.groupby('dept')['score'].mean()\n"
            "         → dept 로 묶고, score 열의 평균. 결과는 Series 다.\n"
            "            읽는 법: '무엇으로 묶어서(groupby) / 어떤 열을(['score']) / 어떻게(mean)'\n"
            "  .round(2)\n"
            "         → 평균은 소수가 길게 나오므로 반올림해서 본다.\n"
            "  df.groupby('dept')['score'].agg(['count', 'mean', 'min', 'max'])\n"
            "         → 여러 집계를 한 번에. 결과는 DataFrame 이다.\n"
            "            부서별 인원수·평균·최저·최고를 한 표로 본다. 리포트에 그대로 쓸 수 있다.\n"
            "  df.groupby('dept').agg(인원=('name','count'), 평균=('score','mean'))\n"
            "         → 결과 열 이름을 직접 정하는 방식(named aggregation).\n"
            "            형식은 새이름=('대상 열', '집계 함수') 다.\n"
            "            열 이름이 한글로 깔끔하게 나와 보고서용으로 좋다.\n"
            "  df.groupby(['dept', 'grade'])['score'].mean()\n"
            "         → 두 개 기준으로 묶기. 결과 인덱스가 두 단계(MultiIndex)가 된다.\n"
            "  .reset_index()\n"
            "         → 그룹 키가 인덱스로 들어간 것을 다시 일반 열로 꺼낸다.\n"
            "            결과를 다시 필터링하거나 저장할 때 거의 항상 필요하다.\n"
            "  df.groupby('dept')['score'].transform('mean')\n"
            "         → 집계 결과를 '원래 행 개수 그대로' 되돌려준다.\n"
            "            각 사람 옆에 '소속 부서 평균'을 붙일 때 쓴다.\n"
            "            이걸로 '부서 평균보다 높은 사람'을 찾는 계산이 한 줄로 가능하다.\n"
            "\n"
            "[유의 사항]\n"
            "  • groupby 결과의 그룹 키는 인덱스가 된다. 열로 쓰려면 reset_index() 를 하자.\n"
            "  • 그룹 키에 결측치(NaN)가 있으면 기본적으로 그 행은 통째로 빠진다.\n"
            "    dropna=False 를 주면 NaN 도 하나의 그룹으로 잡힌다.\n"
            "  • mean() 은 NaN 을 알아서 빼고 계산한다. 편리하지만\n"
            "    '결측치가 많은 그룹의 평균'을 그대로 믿으면 위험하다. count 를 함께 봐야 한다."
        ),
        usage="부서별·지역별·월별 집계. 대시보드와 리포트의 거의 모든 숫자가 여기서 나온다.",
        cons="그룹이 수십만 개로 많아지면 느려지고 메모리를 많이 쓴다. 그 규모는 DB 에서 집계하는 게 낫다.",
        code=(
            "import pandas as pd\n"
            "\n"
            "df = pd.DataFrame({\n"
            "    'name':  ['김철수', '이영희', '박민수', '최지우', '정하늘', '한서준'],\n"
            "    'dept':  ['영업', '개발', '영업', '개발', '기획', '개발'],\n"
            "    'score': [88, 92, 79, 95, 61, 90],\n"
            "    'year':  [3, 5, 2, 7, 1, 4],\n"
            "})\n"
            "\n"
            "print('-- 부서별 평균 --')\n"
            "print(df.groupby('dept')['score'].mean().round(2))\n"
            "\n"
            "print('\\n-- 부서별 여러 집계 --')\n"
            "print(df.groupby('dept')['score'].agg(['count', 'mean', 'min', 'max']).round(2))\n"
            "\n"
            "print('\\n-- 이름 지정 집계 --')\n"
            "summary = df.groupby('dept').agg(\n"
            "    인원=('name', 'count'),\n"
            "    평균점수=('score', 'mean'),\n"
            "    평균연차=('year', 'mean'),\n"
            ").round(2).reset_index()\n"
            "print(summary)\n"
            "\n"
            "print('\\n-- transform: 각 행에 부서 평균 붙이기 --')\n"
            "df['dept_avg'] = df.groupby('dept')['score'].transform('mean').round(2)\n"
            "df['above'] = df['score'] > df['dept_avg']\n"
            "print(df[['name', 'dept', 'score', 'dept_avg', 'above']])\n"
        ),
    ),

    Lesson(
        id="ds2-07-missing",
        lang="datasci", level=STAGE,
        title="결측치 다루기",
        summary="isna · fillna · dropna — 전처리의 절반",
        explanation=(
            "[개요]\n"
            "실제 데이터에는 빈 칸이 반드시 있다. 설문 미응답, 센서 오류, 시스템 누락 등.\n"
            "pandas 는 이를 NaN(Not a Number)으로 표시한다.\n"
            "결측치를 그대로 두면 계산이 NaN 으로 오염되거나 머신러닝 모델이 아예 학습되지 않는다.\n"
            "\n"
            "[처리 전략 3가지]\n"
            "  1) 삭제(dropna)  — 결측 행/열을 버린다\n"
            "     · 데이터가 충분하고 결측이 적을 때만. 5% 미만이 기준선이다.\n"
            "     · 함부로 쓰면 데이터가 절반으로 줄어든다.\n"
            "  2) 대체(fillna)  — 다른 값으로 채운다\n"
            "     · 평균/중앙값 : 숫자 열. 이상치가 있으면 중앙값이 안전하다.\n"
            "     · 최빈값      : 범주 열\n"
            "     · 0 또는 '미상' : 결측 자체가 의미 있을 때\n"
            "  3) 유지          — 결측이 '정보'인 경우 (예: 미가입자의 결제일)\n"
            "     · 별도의 '결측 여부' 열을 만들어 두는 방법도 있다.\n"
            "\n"
            "[코드 분석]\n"
            "  df.isna()\n"
            "         → 각 칸이 결측인지 True/False 로 표시한 같은 크기의 표.\n"
            "  df.isna().sum()\n"
            "         → 열별 결측 개수. True=1 로 세어진다. 가장 먼저 확인하는 값이다.\n"
            "  df.isna().sum().sum()\n"
            "         → 전체 결측 개수.\n"
            "  df.isna().mean().round(3)\n"
            "         → 열별 결측 '비율'. 30% 를 넘으면 그 열을 쓸지 다시 생각해야 한다.\n"
            "  df.dropna()\n"
            "         → 결측이 하나라도 있는 행을 전부 삭제.\n"
            "  df.dropna(subset=['score'])\n"
            "         → score 열이 비어 있는 행만 삭제. 실무에서 훨씬 자주 쓰는 형태다.\n"
            "            분석에 꼭 필요한 열만 지정하는 게 데이터 손실을 줄인다.\n"
            "  df['score'].fillna(df['score'].mean())\n"
            "         → 평균으로 채우기. mean() 은 NaN 을 빼고 계산하므로 안전하다.\n"
            "  df['score'].fillna(df['score'].median())\n"
            "         → 중앙값으로 채우기. 이상치가 있을 때 평균보다 안전하다.\n"
            "  df['dept'].fillna('미상')\n"
            "         → 범주 열은 고정 문자열로 채우는 경우가 많다.\n"
            "  df.groupby('dept')['score'].transform('mean')\n"
            "         → 그룹별 평균으로 채우기. 전체 평균보다 훨씬 정확하다.\n"
            "            '개발팀 결측은 개발팀 평균으로' 채우는 방식이다.\n"
            "  df['score'].ffill()\n"
            "         → 바로 위 값으로 채운다(forward fill). 시계열 데이터에서 쓴다.\n"
            "            주가·센서값처럼 '직전 값이 유지된다'고 볼 수 있을 때만 타당하다.\n"
            "\n"
            "[유의 사항]\n"
            "  • NaN == NaN 은 False 다. 결측 확인은 반드시 isna() 로 해야 한다.\n"
            "  • 평균으로 채우면 그 열의 분산이 실제보다 작아진다. 통계 해석 시 주의.\n"
            "  • 어떻게 채웠는지 반드시 기록해 두자. 나중에 결과를 설명할 수 없게 된다.\n"
            "  • pandas 3.0 부터 inplace=True 사용은 권장되지 않는다.\n"
            "    df['x'] = df['x'].fillna(...) 처럼 다시 대입하는 방식을 쓰자."
        ),
        usage="모든 실제 데이터 분석의 필수 단계. 이걸 건너뛰면 뒤의 모든 숫자를 믿을 수 없다.",
        cons="어떤 방법을 써도 없던 정보를 만들어내는 것이므로 왜곡이 생긴다. 처리 방법과 이유를 반드시 남겨야 한다.",
        code=(
            "import pandas as pd\n"
            "import numpy as np\n"
            "\n"
            "df = pd.DataFrame({\n"
            "    'name':  ['김철수', '이영희', '박민수', '최지우', '정하늘', '한서준'],\n"
            "    'dept':  ['영업', '개발', '영업', '개발', None, '개발'],\n"
            "    'score': [88, np.nan, 79, 95, 61, np.nan],\n"
            "    'year':  [3, 5, np.nan, 7, 1, 4],\n"
            "})\n"
            "\n"
            "print(df)\n"
            "print('\\n-- 열별 결측 개수 --')\n"
            "print(df.isna().sum())\n"
            "print('\\n-- 열별 결측 비율 --')\n"
            "print(df.isna().mean().round(3))\n"
            "print('전체 결측 개수:', int(df.isna().sum().sum()))\n"
            "\n"
            "print('\\n-- dropna(): 결측 있는 행 전부 삭제 --')\n"
            "print(df.dropna())\n"
            "\n"
            "print('\\n-- dropna(subset=[score]) --')\n"
            "print(df.dropna(subset=['score']))\n"
            "\n"
            "filled = df.copy()\n"
            "filled['score'] = filled['score'].fillna(filled['score'].median())\n"
            "filled['year'] = filled['year'].fillna(filled['year'].mean().round(1))\n"
            "filled['dept'] = filled['dept'].fillna('미상')\n"
            "print('\\n-- 중앙값/평균/문자로 채우기 --')\n"
            "print(filled)\n"
            "print('남은 결측:', int(filled.isna().sum().sum()))\n"
            "\n"
            "print('\\n-- 그룹 평균으로 채우기 --')\n"
            "g = df.copy()\n"
            "g['score'] = g['score'].fillna(g.groupby('dept')['score'].transform('mean'))\n"
            "print(g[['name', 'dept', 'score']])\n"
        ),
    ),

    Lesson(
        id="ds2-08-outlier",
        lang="datasci", level=STAGE,
        title="중복 · 이상치 처리",
        summary="drop_duplicates · IQR 규칙 · z-score",
        explanation=(
            "[개요]\n"
            "결측치 다음으로 데이터를 망치는 두 가지가 중복과 이상치다.\n"
            "  • 중복  : 같은 데이터가 두 번 들어옴 (시스템 재전송, 병합 실수)\n"
            "  • 이상치: 나머지와 동떨어진 값 (입력 실수 또는 진짜 특이 사례)\n"
            "\n"
            "[이상치 판별 — IQR 규칙 (가장 널리 쓰임)]\n"
            "  Q1 = 하위 25% 지점,  Q3 = 상위 25% 지점\n"
            "  IQR = Q3 - Q1              ← 가운데 50% 가 퍼진 폭\n"
            "  정상 범위 : Q1 - 1.5×IQR  ~  Q3 + 1.5×IQR\n"
            "  이 범위를 벗어나면 이상치로 본다.\n"
            "\n"
            "  왜 1.5 인가? 통계학자 튜키(Tukey)가 정한 경험칙이다.\n"
            "  정규분포라면 약 0.7% 만 이 범위를 벗어난다. 절대 규칙이 아니라 관례다.\n"
            "  박스플롯 그래프의 수염(whisker) 길이가 바로 이 기준이다.\n"
            "\n"
            "[다른 방법 — z-score]\n"
            "  z = (값 - 평균) / 표준편차\n"
            "  |z| > 3 이면 이상치로 본다. 데이터가 정규분포에 가까울 때 적합하다.\n"
            "  단 평균·표준편차 자체가 이상치에 끌려가므로 IQR 보다 덜 안정적이다.\n"
            "\n"
            "[코드 분석]\n"
            "  df.duplicated()\n"
            "         → 각 행이 '앞에 이미 나온 행과 같은지' True/False.\n"
            "            첫 등장은 False, 두 번째부터 True 다.\n"
            "  df.duplicated(subset=['name'])\n"
            "         → 특정 열만 기준으로 중복 판정. 이름이 같으면 중복으로 본다.\n"
            "  df.drop_duplicates(subset=['name'], keep='last')\n"
            "         → 중복 제거. keep='first'(기본)는 첫 행을, 'last'는 마지막 행을 남긴다.\n"
            "            최신 데이터를 남기려면 시간순 정렬 후 keep='last' 를 쓴다.\n"
            "  q1 = df['score'].quantile(0.25)\n"
            "         → 하위 25% 지점의 값.\n"
            "  iqr = q3 - q1\n"
            "  low, high = q1 - 1.5*iqr, q3 + 1.5*iqr\n"
            "         → 정상 범위의 경계.\n"
            "  df[(df['score'] < low) | (df['score'] > high)]\n"
            "         → 범위를 벗어난 행 = 이상치.\n"
            "  df['score'].clip(low, high)\n"
            "         → 이상치를 삭제하지 않고 경계값으로 눌러 담는다(winsorizing).\n"
            "            데이터 개수를 유지하면서 극단값 영향만 줄이는 방법이다.\n"
            "  z = (df['score'] - df['score'].mean()) / df['score'].std()\n"
            "         → z-score. 평균에서 표준편차 몇 배만큼 떨어졌는지를 나타낸다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 이상치를 무조건 지우면 안 된다. 부정거래 탐지에서는 이상치가 바로 찾는 대상이다.\n"
            "    '왜 이 값이 나왔는지' 확인이 먼저고, 삭제는 그 다음이다.\n"
            "  • 데이터가 적으면(30개 미만) IQR 기준이 불안정하다.\n"
            "  • 중복 제거 전에 '정말 중복인지' 확인하자. 동명이인일 수도 있다."
        ),
        usage="데이터 품질 검증 단계. 평균·상관계수 같은 통계량은 이상치에 크게 흔들린다.",
        cons="이상치 기준(1.5, 3)은 관례일 뿐 정답이 아니다. 도메인 지식 없이 기계적으로 적용하면 위험하다.",
        code=(
            "import pandas as pd\n"
            "\n"
            "df = pd.DataFrame({\n"
            "    'name':  ['김철수', '이영희', '박민수', '최지우', '정하늘', '이영희', '한서준'],\n"
            "    'dept':  ['영업', '개발', '영업', '개발', '기획', '개발', '영업'],\n"
            "    'score': [88, 92, 79, 95, 61, 92, 250],\n"
            "})\n"
            "\n"
            "print('-- 중복 판정 --')\n"
            "print(df.duplicated())\n"
            "print('중복 개수:', int(df.duplicated().sum()))\n"
            "\n"
            "dedup = df.drop_duplicates(subset=['name'], keep='first').reset_index(drop=True)\n"
            "print('\\n-- 중복 제거 후 --')\n"
            "print(dedup)\n"
            "\n"
            "q1 = dedup['score'].quantile(0.25)\n"
            "q3 = dedup['score'].quantile(0.75)\n"
            "iqr = q3 - q1\n"
            "low, high = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n"
            "print(f'\\nQ1={q1}  Q3={q3}  IQR={iqr}')\n"
            "print(f'정상 범위: {low} ~ {high}')\n"
            "\n"
            "print('\\n-- 이상치 --')\n"
            "print(dedup[(dedup['score'] < low) | (dedup['score'] > high)])\n"
            "\n"
            "print('\\n-- 이상치 제거 후 평균 --')\n"
            "clean = dedup[(dedup['score'] >= low) & (dedup['score'] <= high)]\n"
            "print('제거 전 평균:', round(float(dedup['score'].mean()), 2))\n"
            "print('제거 후 평균:', round(float(clean['score'].mean()), 2))\n"
            "\n"
            "print('\\n-- clip 으로 눌러담기 --')\n"
            "print(dedup['score'].clip(low, high).tolist())\n"
            "\n"
            "z = (dedup['score'] - dedup['score'].mean()) / dedup['score'].std()\n"
            "print('\\nz-score:', z.round(2).tolist())\n"
        ),
    ),

    Lesson(
        id="ds2-09-stats",
        lang="datasci", level=STAGE,
        title="기술통계 제대로 읽기",
        summary="평균 · 중앙값 · 분산 · 분포의 치우침",
        explanation=(
            "[개요]\n"
            "기술통계(descriptive statistics)는 데이터를 몇 개의 숫자로 요약하는 일이다.\n"
            "중요한 건 계산이 아니라 '해석'이다. 같은 평균이라도 전혀 다른 데이터일 수 있다.\n"
            "\n"
            "[대표값 3형제]\n"
            "  평균(mean)   : 모두 더해 나눈 값. 모든 값을 반영하지만 이상치에 약하다.\n"
            "  중앙값(median): 정렬했을 때 한가운데. 이상치에 강하다.\n"
            "  최빈값(mode) : 가장 자주 나온 값. 범주형 데이터의 대표값이다.\n"
            "\n"
            "[산포도 — 얼마나 흩어져 있나]\n"
            "  범위(range)      : 최대 - 최소. 간단하지만 이상치에 완전히 좌우된다.\n"
            "  분산(variance)   : 편차(값-평균)를 제곱해 평균낸 것.\n"
            "                     제곱하는 이유는 +편차와 -편차가 상쇄되는 걸 막기 위해서다.\n"
            "  표준편차(std)    : 분산의 제곱근. 원래 단위로 돌아와서 해석하기 쉽다.\n"
            "  IQR             : Q3 - Q1. 가운데 50% 의 폭. 이상치에 강하다.\n"
            "\n"
            "[분포의 치우침 — skewness(왜도)]\n"
            "  왜도 ≈ 0  : 좌우 대칭 (정규분포)\n"
            "  왜도 > 0  : 오른쪽 꼬리가 길다. 평균 > 중앙값 (소득 분포가 대표적)\n"
            "  왜도 < 0  : 왼쪽 꼬리가 길다. 평균 < 중앙값 (쉬운 시험의 점수 분포)\n"
            "\n"
            "  실무 판단 요령: 평균과 중앙값을 비교하면 왜도를 대충 알 수 있다.\n"
            "  평균이 중앙값보다 훨씬 크면 위쪽에 극단값이 있다는 뜻이다.\n"
            "\n"
            "[코드 분석]\n"
            "  s.mean(), s.median(), s.mode()\n"
            "         → 대표값 3형제. mode() 는 여러 개일 수 있어 Series 로 나온다.\n"
            "  s.std()\n"
            "         → pandas 기본은 표본 표준편차(ddof=1, n-1 로 나눔)다.\n"
            "            numpy 기본(ddof=0)과 다르므로 값이 미세하게 차이난다.\n"
            "            표본에서 모집단을 추정할 땐 n-1 이 맞다.\n"
            "  s.quantile([0.25, 0.5, 0.75])\n"
            "         → 사분위수를 한 번에.\n"
            "  s.skew()\n"
            "         → 왜도. 0 에서 얼마나 벗어났는지 본다.\n"
            "  s.kurt()\n"
            "         → 첨도. 뾰족한 정도. 0보다 크면 정규분포보다 뾰족하고 꼬리가 두껍다.\n"
            "  (s - s.mean()) / s.std()\n"
            "         → 표준화(z-score). 단위가 다른 열을 비교 가능하게 만든다.\n"
            "            키(cm)와 몸무게(kg)를 같은 잣대로 놓는 방법이다.\n"
            "  (s - s.min()) / (s.max() - s.min())\n"
            "         → 정규화(min-max). 0~1 사이로 압축한다.\n"
            "            신경망 입력에 자주 쓰지만 이상치가 있으면 나머지가 뭉개진다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 평균 하나만 보고 보고하지 말자. 최소한 중앙값·표준편차를 함께 봐야 한다.\n"
            "  • 표준편차의 단위는 원래 데이터와 같다. '점수 표준편차 12점'처럼 읽으면 된다.\n"
            "  • 데이터가 30개 미만이면 왜도·첨도는 신뢰하기 어렵다."
        ),
        usage="분석 리포트의 첫 페이지. 데이터의 성격을 한눈에 설명하는 표준 양식.",
        cons="요약 숫자는 분포의 모양을 감춘다. 봉우리가 두 개인 데이터도 평균·표준편차는 평범해 보인다.",
        code=(
            "import pandas as pd\n"
            "import numpy as np\n"
            "\n"
            "rng = np.random.default_rng(42)\n"
            "normal = pd.Series(rng.normal(70, 10, 200).round(1))\n"
            "skewed = pd.Series(np.concatenate([rng.normal(3000, 300, 195),\n"
            "                                   rng.normal(30000, 3000, 5)]).round(0))\n"
            "\n"
            "def report(name, s):\n"
            "    print(f'-- {name} --')\n"
            "    print('  평균    :', round(float(s.mean()), 2))\n"
            "    print('  중앙값  :', round(float(s.median()), 2))\n"
            "    print('  표준편차:', round(float(s.std()), 2))\n"
            "    print('  최소/최대:', float(s.min()), '/', float(s.max()))\n"
            "    q = s.quantile([0.25, 0.5, 0.75])\n"
            "    print('  Q1/Q2/Q3:', [round(float(v), 1) for v in q])\n"
            "    print('  IQR     :', round(float(q[0.75] - q[0.25]), 2))\n"
            "    print('  왜도    :', round(float(s.skew()), 3))\n"
            "\n"
            "report('정규분포에 가까운 점수', normal)\n"
            "print()\n"
            "report('치우친 연봉 (극단값 5건)', skewed)\n"
            "\n"
            "print('\\n※ 연봉은 평균 > 중앙값 → 오른쪽으로 치우침(왜도 > 0)')\n"
            "\n"
            "print('\\n-- 표준화 / 정규화 (앞 5개) --')\n"
            "z = (normal - normal.mean()) / normal.std()\n"
            "mm = (normal - normal.min()) / (normal.max() - normal.min())\n"
            "print('z-score :', z.head(5).round(3).tolist())\n"
            "print('min-max :', mm.head(5).round(3).tolist())\n"
        ),
    ),

    Lesson(
        id="ds2-10-corr",
        lang="datasci", level=STAGE,
        title="상관관계",
        summary="두 변수가 함께 움직이는가 · 인과와의 차이",
        explanation=(
            "[개요]\n"
            "상관관계(correlation)는 '한 값이 커질 때 다른 값도 커지는가'를 -1 ~ +1 로 나타낸다.\n"
            "  +1 에 가까움 : 같이 커진다 (공부 시간 ↔ 점수)\n"
            "   0 에 가까움 : 관계 없다\n"
            "  -1 에 가까움 : 하나가 커지면 다른 건 작아진다 (가격 ↔ 판매량)\n"
            "\n"
            "[해석 기준 (관례)]\n"
            "  |r| 0.7 이상 : 강한 상관\n"
            "  |r| 0.4~0.7  : 중간\n"
            "  |r| 0.2~0.4  : 약함\n"
            "  |r| 0.2 미만 : 거의 없음\n"
            "  분야마다 기준이 다르다. 사회과학은 0.3 도 의미 있게 본다.\n"
            "\n"
            "[상관 ≠ 인과 — 가장 중요한 원칙]\n"
            "  아이스크림 판매량과 익사 사고 건수의 상관계수는 매우 높다.\n"
            "  하지만 아이스크림이 익사를 일으키는 게 아니다. 둘 다 '더위' 때문이다.\n"
            "  이런 숨은 원인을 교란변수(confounding variable)라 한다.\n"
            "\n"
            "  상관계수는 '함께 움직인다'는 사실만 말한다. '왜'는 절대 말해주지 않는다.\n"
            "  인과를 주장하려면 실험(A/B 테스트)이나 인과추론 기법이 필요하다.\n"
            "  분석 리포트에서 가장 흔하고 위험한 실수가 이 둘을 섞는 것이다.\n"
            "\n"
            "[코드 분석]\n"
            "  df.corr(numeric_only=True)\n"
            "         → 모든 숫자 열 쌍의 상관계수 표(상관 행렬).\n"
            "            numeric_only=True 를 주지 않으면 문자 열 때문에 에러가 난다.\n"
            "            대각선은 자기 자신과의 상관이라 항상 1 이다.\n"
            "  df['a'].corr(df['b'])\n"
            "         → 두 열만 골라 계산.\n"
            "  method='spearman'\n"
            "         → 순위 기반 상관. 곡선 관계나 이상치가 있을 때 더 안정적이다.\n"
            "            기본값 'pearson' 은 '직선 관계'만 잡아낸다.\n"
            "  .round(3)\n"
            "         → 상관계수는 소수 셋째 자리까지가 관례다.\n"
            "\n"
            "[피어슨이 못 잡는 관계]\n"
            "  y = x² 처럼 U자 곡선 관계는 피어슨 상관이 0 에 가깝게 나온다.\n"
            "  '관계가 없다'가 아니라 '직선 관계가 없다'는 뜻이다.\n"
            "  그래서 상관계수만 믿지 말고 산점도를 반드시 그려봐야 한다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 상관관계는 인과관계가 아니다. 리포트에 '때문에'라고 쓰기 전에 세 번 생각하자.\n"
            "  • 이상치 하나가 상관계수를 크게 바꾼다. 이상치 처리를 먼저 하자.\n"
            "  • 데이터가 적으면 우연히 높은 상관이 나온다. 표본 수를 함께 봐야 한다."
        ),
        usage="어떤 변수가 결과와 관련 있는지 탐색할 때. 머신러닝 변수 선택의 출발점.",
        cons="직선 관계만 측정한다. 곡선 관계·조건부 관계는 놓친다. 인과 판단에는 쓸 수 없다.",
        code=(
            "import pandas as pd\n"
            "import numpy as np\n"
            "\n"
            "rng = np.random.default_rng(0)\n"
            "n = 100\n"
            "study = rng.normal(5, 2, n).clip(0, 12)              # 공부 시간\n"
            "score = (study * 7 + rng.normal(50, 5, n)).clip(0, 100)   # 점수 (공부와 연관)\n"
            "shoe = rng.normal(260, 10, n)                        # 신발 크기 (무관)\n"
            "\n"
            "df = pd.DataFrame({\n"
            "    'study': study.round(1),\n"
            "    'score': score.round(1),\n"
            "    'shoe':  shoe.round(0),\n"
            "})\n"
            "\n"
            "print('-- 상관 행렬 --')\n"
            "print(df.corr(numeric_only=True).round(3))\n"
            "\n"
            "print('\\n공부시간 ↔ 점수 :', round(float(df['study'].corr(df['score'])), 3))\n"
            "print('신발크기 ↔ 점수 :', round(float(df['shoe'].corr(df['score'])), 3))\n"
            "\n"
            "print('\\n-- 스피어만(순위 기반) --')\n"
            "print(round(float(df['study'].corr(df['score'], method='spearman')), 3))\n"
            "\n"
            "# 피어슨이 못 잡는 U자 관계\n"
            "x = pd.Series(np.linspace(-10, 10, 100))\n"
            "y = x ** 2\n"
            "print('\\nU자 관계 y=x² 의 피어슨 상관:', round(float(x.corr(y)), 3))\n"
            "print('→ 0 에 가깝지만 관계가 없는 게 아니라 \"직선\" 관계가 없는 것이다')\n"
        ),
    ),

    Lesson(
        id="ds2-11-merge",
        lang="datasci", level=STAGE,
        title="표 합치기 — merge · concat",
        summary="SQL 의 JOIN 을 pandas 로",
        explanation=(
            "[개요]\n"
            "실무 데이터는 여러 표에 나뉘어 있다. 사원표와 부서표, 주문표와 상품표.\n"
            "이를 공통 열(key)로 이어 붙이는 게 merge 다. SQL 의 JOIN 과 같은 개념이다.\n"
            "\n"
            "[merge — 옆으로 붙이기 (열 방향)]\n"
            "  how='inner' (기본) : 양쪽 다 있는 키만 남긴다\n"
            "  how='left'         : 왼쪽 표는 전부 남기고, 오른쪽은 있으면 붙인다\n"
            "  how='right'        : 반대\n"
            "  how='outer'        : 양쪽 전부 남긴다. 없는 쪽은 NaN\n"
            "\n"
            "  실무에서는 how='left' 를 압도적으로 많이 쓴다.\n"
            "  '기준 표(고객 목록)는 그대로 두고 추가 정보를 붙인다'가 가장 흔한 요구이기 때문이다.\n"
            "\n"
            "[concat — 아래로 쌓기 (행 방향)]\n"
            "  같은 구조의 표를 이어 붙일 때. 1월 데이터 + 2월 데이터 같은 경우다.\n"
            "\n"
            "[코드 분석]\n"
            "  pd.merge(emp, dept, on='dept_id', how='left')\n"
            "         → dept_id 를 기준으로 옆으로 붙인다.\n"
            "            emp 의 모든 행은 유지되고, 짝이 없으면 NaN 이 채워진다.\n"
            "  left_on=..., right_on=...\n"
            "         → 두 표의 키 열 이름이 다를 때 각각 지정한다.\n"
            "  pd.concat([df1, df2], ignore_index=True)\n"
            "         → 아래로 쌓는다. ignore_index=True 는 인덱스를 0부터 다시 매긴다.\n"
            "            이걸 빼면 0,1,0,1 처럼 중복 인덱스가 생겨 나중에 문제가 된다.\n"
            "  indicator=True\n"
            "         → 각 행이 어느 쪽에서 왔는지 _merge 열로 표시한다.\n"
            "            both / left_only / right_only.\n"
            "            조인이 의도대로 됐는지 검증할 때 매우 유용하다.\n"
            "  len(merged) vs len(emp)\n"
            "         → 조인 후 행 수 확인. 늘어났다면 키가 중복된 것이다.\n"
            "            이게 실무에서 가장 자주 터지는 조인 사고다.\n"
            "\n"
            "[유의 사항]\n"
            "  • 조인 후 행 수를 반드시 확인하자. 키가 중복이면 행이 곱해져서 불어난다.\n"
            "    사원 5명 × 중복 부서 2건 = 10행이 되는 식이다.\n"
            "  • how='inner' 는 조용히 데이터를 버린다. 몇 건이 사라졌는지 확인하자.\n"
            "  • 키 열의 타입이 다르면(한쪽은 정수, 한쪽은 문자열) 하나도 매칭되지 않는다.\n"
            "  • 양쪽에 같은 이름의 열이 있으면 _x, _y 가 붙는다. suffixes 로 바꿀 수 있다."
        ),
        usage="여러 소스의 데이터를 하나로 모을 때. 실무 분석의 거의 필수 과정.",
        cons="키 중복으로 행이 폭증하는 사고가 흔하다. 조인 전후 행 수 확인을 습관화해야 한다.",
        code=(
            "import pandas as pd\n"
            "\n"
            "emp = pd.DataFrame({\n"
            "    'name':    ['김철수', '이영희', '박민수', '최지우'],\n"
            "    'dept_id': [1, 2, 1, 9],\n"
            "    'score':   [88, 92, 79, 95],\n"
            "})\n"
            "dept = pd.DataFrame({\n"
            "    'dept_id':   [1, 2, 3],\n"
            "    'dept_name': ['영업', '개발', '기획'],\n"
            "})\n"
            "\n"
            "print('-- inner (양쪽 다 있는 것만) --')\n"
            "print(pd.merge(emp, dept, on='dept_id', how='inner'))\n"
            "\n"
            "print('\\n-- left (왼쪽 전부 유지) --')\n"
            "left = pd.merge(emp, dept, on='dept_id', how='left')\n"
            "print(left)\n"
            "print('→ dept_id=9 는 부서표에 없어 NaN')\n"
            "\n"
            "print('\\n-- outer + indicator --')\n"
            "print(pd.merge(emp, dept, on='dept_id', how='outer', indicator=True))\n"
            "\n"
            "print('\\n-- 행 수 검증 --')\n"
            "print('원본:', len(emp), '→ 조인 후:', len(left), '→ 안전' if len(left) == len(emp) else '→ 확인 필요')\n"
            "\n"
            "jan = pd.DataFrame({'month': ['1월'] * 2, 'sales': [100, 200]})\n"
            "feb = pd.DataFrame({'month': ['2월'] * 2, 'sales': [150, 250]})\n"
            "print('\\n-- concat (아래로 쌓기) --')\n"
            "print(pd.concat([jan, feb], ignore_index=True))\n"
        ),
    ),

    Lesson(
        id="ds2-12-pivot",
        lang="datasci", level=STAGE,
        title="피벗 테이블 · 교차표",
        summary="엑셀 피벗을 코드로 · 긴 형태 ↔ 넓은 형태",
        explanation=(
            "[개요]\n"
            "피벗 테이블은 '행 기준 × 열 기준'으로 값을 요약한 표다. 엑셀의 피벗 테이블과 같다.\n"
            "groupby 결과를 사람이 보기 좋은 격자 형태로 재배치한 것이라고 보면 된다.\n"
            "\n"
            "[긴 형태(long) vs 넓은 형태(wide)]\n"
            "  긴 형태 — 한 행이 하나의 관측값. 저장·계산에 유리하다.\n"
            "     이름   과목   점수\n"
            "     철수   국어   80\n"
            "     철수   수학   70\n"
            "\n"
            "  넓은 형태 — 격자. 사람이 읽기 좋다.\n"
            "     이름   국어  수학\n"
            "     철수    80   70\n"
            "\n"
            "  pivot_table 은 긴 → 넓은, melt 는 넓은 → 긴 방향 변환이다.\n"
            "  데이터베이스는 긴 형태로 저장하고, 보고서는 넓은 형태로 만든다.\n"
            "\n"
            "[코드 분석]\n"
            "  df.pivot_table(index='name', columns='subject', values='score')\n"
            "         → 행은 이름, 열은 과목, 칸에는 점수.\n"
            "            같은 칸에 값이 여러 개면 기본적으로 평균을 낸다.\n"
            "  aggfunc='sum'\n"
            "         → 합계로 집계. 'mean', 'count', 'max' 등을 쓸 수 있다.\n"
            "  margins=True\n"
            "         → 행·열의 합계(All) 줄을 추가한다. 리포트에 바로 쓸 수 있다.\n"
            "  fill_value=0\n"
            "         → 값이 없는 칸을 0 으로 채운다. NaN 이 보기 싫을 때.\n"
            "  pd.crosstab(df['dept'], df['grade'])\n"
            "         → 교차표(빈도표). 두 범주형 변수의 조합별 개수를 센다.\n"
            "            '부서별 등급 분포' 같은 걸 볼 때 쓴다.\n"
            "  normalize='index'\n"
            "         → 행 기준 비율로 바꾼다. 각 행의 합이 1 이 된다.\n"
            "            그룹 크기가 달라도 공정하게 비교할 수 있다.\n"
            "  df.melt(id_vars=['name'], var_name='subject', value_name='score')\n"
            "         → 넓은 형태를 다시 긴 형태로. id_vars 는 그대로 둘 열이다.\n"
            "\n"
            "[유의 사항]\n"
            "  • pivot_table 은 중복 값을 자동으로 집계한다.\n"
            "    의도치 않게 평균이 나올 수 있으니 aggfunc 을 명시하는 게 안전하다.\n"
            "  • pivot() 은 중복이 있으면 에러가 난다. pivot_table() 은 집계해서 넘어간다.\n"
            "  • 열이 MultiIndex 로 나오면 후속 처리가 번거롭다. reset_index() 로 정리하자."
        ),
        usage="경영 보고서, 대시보드 요약표. 엑셀로 넘기기 전 마지막 가공 단계.",
        cons="범주 값이 많으면 열이 수백 개로 폭증한다. 사전에 상위 N 개만 남기는 처리가 필요하다.",
        code=(
            "import pandas as pd\n"
            "\n"
            "df = pd.DataFrame({\n"
            "    'name':    ['철수', '철수', '철수', '영희', '영희', '영희', '민수', '민수', '민수'],\n"
            "    'subject': ['국어', '영어', '수학'] * 3,\n"
            "    'score':   [80, 90, 70, 85, 95, 75, 60, 70, 65],\n"
            "    'dept':    ['영업'] * 3 + ['개발'] * 3 + ['영업'] * 3,\n"
            "})\n"
            "\n"
            "print('-- 긴 형태(원본) --')\n"
            "print(df.head(4))\n"
            "\n"
            "print('\\n-- 피벗: 이름 × 과목 --')\n"
            "pv = df.pivot_table(index='name', columns='subject', values='score')\n"
            "print(pv)\n"
            "\n"
            "print('\\n-- 합계 줄 추가 --')\n"
            "print(df.pivot_table(index='name', columns='subject', values='score',\n"
            "                     aggfunc='sum', margins=True, margins_name='합계'))\n"
            "\n"
            "print('\\n-- 부서 × 과목 평균 --')\n"
            "print(df.pivot_table(index='dept', columns='subject', values='score',\n"
            "                     aggfunc='mean').round(1))\n"
            "\n"
            "df['grade'] = pd.cut(df['score'], [0, 70, 85, 100], labels=['하', '중', '상'])\n"
            "print('\\n-- 교차표: 부서 × 등급 (개수) --')\n"
            "print(pd.crosstab(df['dept'], df['grade']))\n"
            "\n"
            "print('\\n-- 교차표 비율 (행 기준) --')\n"
            "print(pd.crosstab(df['dept'], df['grade'], normalize='index').round(3))\n"
            "\n"
            "print('\\n-- melt: 넓은 → 긴 --')\n"
            "print(pv.reset_index().melt(id_vars=['name'], var_name='subject',\n"
            "                            value_name='score').head(5))\n"
        ),
    ),

    Lesson(
        id="ds2-13-pipeline",
        lang="datasci", level=STAGE,
        title="전처리 파이프라인 실습",
        summary="CSV 읽기 → 정제 → 집계 → 리포트 한 바퀴",
        explanation=(
            "[개요]\n"
            "지금까지 배운 것을 하나로 이어 실제 분석 한 바퀴를 돌려본다.\n"
            "실무의 분석 코드는 대부분 아래 순서를 그대로 따른다.\n"
            "\n"
            "[표준 파이프라인]\n"
            "  1) 읽기      pd.read_csv()\n"
            "  2) 훑어보기  shape / info / describe / isna\n"
            "  3) 정제      타입 변환 → 중복 제거 → 결측 처리 → 이상치 처리\n"
            "  4) 파생      필요한 열 계산\n"
            "  5) 집계      groupby / pivot_table\n"
            "  6) 저장      to_csv()\n"
            "\n"
            "  순서가 중요하다. 예를 들어 이상치 제거를 결측 처리보다 먼저 하면\n"
            "  NaN 때문에 비교 연산이 엉킬 수 있다.\n"
            "\n"
            "[코드 분석]\n"
            "  pd.read_csv(io.StringIO(raw))\n"
            "         → 실제로는 pd.read_csv('data.csv') 로 파일을 읽는다.\n"
            "            여기서는 파일 없이 실습하려고 문자열을 파일처럼 감쌌다.\n"
            "            1단계에서 손으로 split 하던 걸 한 줄로 끝낸다.\n"
            "  pd.to_numeric(df['score'], errors='coerce')\n"
            "         → 숫자로 변환하되, 변환 실패한 값은 NaN 으로 만든다.\n"
            "            '없음', 'N/A' 같은 문자가 섞여 있을 때 필수다.\n"
            "            errors='coerce' 가 없으면 에러로 멈춰버린다.\n"
            "  df['dept'].str.strip()\n"
            "         → 문자열 앞뒤 공백 제거. '영업'과 '영업 '이 다른 값으로\n"
            "            잡히는 문제를 막는다. 실무에서 정말 자주 생긴다.\n"
            "  .str 접근자\n"
            "         → 문자열 열에 문자열 메서드를 한 번에 적용한다.\n"
            "            .str.upper(), .str.replace(), .str.contains() 등이 있다.\n"
            "  drop_duplicates → fillna → 이상치 → 파생 → 집계\n"
            "         → 위 표준 순서대로 진행한다.\n"
            "  df.to_csv('out.csv', index=False, encoding='utf-8-sig')\n"
            "         → 저장. index=False 는 인덱스 열을 빼는 것이고,\n"
            "            utf-8-sig 는 엑셀에서 한글이 깨지지 않게 하는 인코딩이다.\n"
            "            (실습에서는 파일 대신 문자열로 출력했다)\n"
            "\n"
            "[유의 사항]\n"
            "  • 각 단계마다 shape 을 찍어 몇 건이 사라졌는지 기록하자.\n"
            "    나중에 '데이터가 왜 줄었나' 질문에 답할 수 있어야 한다.\n"
            "  • 원본 df 를 직접 고치지 말고 .copy() 로 작업본을 만들자.\n"
            "  • 전처리 과정은 반드시 코드로 남긴다. 엑셀에서 손으로 고치면 재현이 불가능하다."
        ),
        usage="실무 분석의 표준 흐름. 이 순서를 몸에 익히면 어떤 데이터가 와도 당황하지 않는다.",
        cons="데이터마다 필요한 정제가 다르다. 이 순서는 뼈대일 뿐 그대로 복사해 쓸 수는 없다.",
        code=(
            "import pandas as pd\n"
            "import io\n"
            "\n"
            "raw = '''name,dept,score,year\n"
            "김철수,영업,88,3\n"
            "이영희,개발 ,92,5\n"
            "박민수,영업,없음,2\n"
            "최지우,개발,95,7\n"
            "정하늘,기획,61,1\n"
            "이영희,개발,92,5\n"
            "한서준,영업,250,4'''\n"
            "\n"
            "# 1) 읽기\n"
            "df = pd.read_csv(io.StringIO(raw))\n"
            "print('1) 읽기      :', df.shape)\n"
            "\n"
            "# 2) 타입 정리 — '없음' 은 NaN 으로\n"
            "df['score'] = pd.to_numeric(df['score'], errors='coerce')\n"
            "df['dept'] = df['dept'].str.strip()\n"
            "print('2) 타입 정리 : 결측', int(df['score'].isna().sum()), '건 발견')\n"
            "\n"
            "# 3) 중복 제거\n"
            "before = len(df)\n"
            "df = df.drop_duplicates(subset=['name'], keep='first')\n"
            "print('3) 중복 제거 :', before, '→', len(df))\n"
            "\n"
            "# 4) 결측 처리 — 부서 중앙값으로\n"
            "df['score'] = df['score'].fillna(df.groupby('dept')['score'].transform('median'))\n"
            "df['score'] = df['score'].fillna(df['score'].median())\n"
            "print('4) 결측 처리 : 남은 결측', int(df['score'].isna().sum()), '건')\n"
            "\n"
            "# 5) 이상치 처리 — IQR\n"
            "q1, q3 = df['score'].quantile([0.25, 0.75])\n"
            "iqr = q3 - q1\n"
            "low, high = q1 - 1.5 * iqr, q3 + 1.5 * iqr\n"
            "before = len(df)\n"
            "df = df[(df['score'] >= low) & (df['score'] <= high)]\n"
            "print(f'5) 이상치    : {before} → {len(df)}  (정상범위 {low:.1f}~{high:.1f})')\n"
            "\n"
            "# 6) 파생 변수\n"
            "df['grade'] = pd.cut(df['score'], [0, 70, 85, 100], labels=['하', '중', '상'])\n"
            "\n"
            "# 7) 집계\n"
            "print('\\n-- 최종 데이터 --')\n"
            "print(df.reset_index(drop=True))\n"
            "print('\\n-- 부서별 요약 --')\n"
            "print(df.groupby('dept').agg(인원=('name', 'count'),\n"
            "                             평균=('score', 'mean')).round(1))\n"
            "\n"
            "# 8) 저장 (문자열로 확인)\n"
            "print('\\n-- CSV 출력 --')\n"
            "print(df.to_csv(index=False))\n"
        ),
    ),
]
